### ISSUE TITLE
Bug when PSX games exceed 63 (webMAN MOD 1.41.06)

### ISSUE THREAD

**Issue by shawly** [aldostools/webMAN-MOD#10]
If I put more than 63 cue Files along with the bins (can be more bins, they don't get recognized anyway) so the number of PlaystationOne games exceeds 63, there appears a bug that suddenly loadingicons in the Playstation 3 games list appear above the PS3 games, if there are about 75 games the list of PSX games suddenly decreases to 13 games and the PS3 games increase to more than 60 and then a long list of loadingicons appear above and below the PS3 games there are some PSX games.

I refreshed XML several times and when I delete all the games until there are exactly 63 PSX games or less, the bug disappears.
![imag0219](https://cloud.githubusercontent.com/assets/6448794/5695704/59256100-99af-11e4-8ebe-ea10c11e2213.jpg)

This Bug also appears in webMAN 1.41 non modded, so this might be a webMAN problem.
I can't try this with iso files, since iso doesn't support multitrack games which I have plenty of.

**Comment by shawly** [comment]
Working on a solution yet?

**Comment by aldostools** [comment]
Try changing the "plugin memory" to MAX or STANDARD on /setup.ps3

On "Min" or "Min+" only 32KB is allocated for PSX. Each entry use aprox. 0.5K each. Thus only 63 games are listed.

"Max" allocates 192KB for PSX category. It should allow up to approx. 375 games.
"Standard" allocates 160KB for PSX category. It should allow aprox. 310 games.

The memory is allocated only during the scanning of content. When the scan is completed, the allocated memory is free and should have low impact in other processes.
