### ISSUE TITLE
Games not showing in XMB->WebMan when disabling Grouping of Content on wb1.43.35

### ISSUE THREAD

**Issue by maxy3d** [aldostools/webMAN-MOD#10]
Using Rebug 4.80.1. When using webMAN MOD 1.43.35 and disabling Grouping of Content, all games disapear from webman XMB directory. Rebooting, Refresing xml and html does nothing. 
With webMAN MOD 1.43.33 all works fine,( Have not try 1.43.34).

**Comment by aldostools** [comment]
Please test if the issue still happens with this build:
http://aldostools.org/temp/test/webftp_server_full.sprx

**Comment by maxy3d** [comment]
With the file above , Its working great. Its 1.43.35 and all games are showing without the Grouping. 
Thx Aldostools.
