### ISSUE TITLE
Add Button Combo for restore syscalls!

### ISSUE THREAD

**Issue by cloud-strife7777** [aldostools/webMAN-MOD#1000]
Please add a Button Combo for restore syscalls! :)

**Comment by aldostools** [comment]
The combo R2+SQUARE is customizable in /setup.ps3

PS3MAPI must be enabled in shortcuts
https://github.com/aldostools/webMAN-MOD/wiki/Setup-Options#xmbin-game-pad-shortcuts

Make sure that Fully disabled is NOT selected in /syscall8.ps3mapi

All other options can restore the syscall 8

**Comment by cloud-strife7777** [comment]
What do I have to enter in box custom Combo?

**Comment by aldostools** [comment]
Use this command to disable the syscalls
`/xmb.ps3$disable_syscalls`

Use this command  to restore the syscalls
`/syscall.ps3mapi?sce=1`

Make sure that Cobra has enabled the option "Allow Restore Syscalls".

**Comment by cloud-strife7777** [comment]
Hm fuck dont work for me. :( pls help

**Comment by aldostools** [comment]
It works if you disabled the CFW Syscalls with R2+△. 
The command `/syscall.ps3mapi?sce=1`  is equivalent to go to PS3MAPI > Syscalls > Re-Enable CFW Syscalls.

If you disabled the CFW Syscalls using CFW Tools menu the system may be preventing the syscalls to be re-enabled.

IMHO it's easier to re-enable the CFW Syscalls using CFW Tools menu or going to Settings > System Update.
Or simply restart the console.

Another method is adding a bookmark to `http://0/syscall.ps3mapi?sce=1` in PS3 Internet browser.

**Comment by cloud-strife7777** [comment]
But I use R2+△ Combo then R2 + Square but dont work. The Website works fine. But i need a combo i Love Combos.

But the Website has a BUG. After syscall restore dont no webman Mod Combo more i need a restart.

**Comment by aldostools** [comment]
I just tested it, and it's working fine on my system. This screen appears pressing R2+△
![image](https://github.com/aldostools/webMAN-MOD/assets/974897/d1eb5677-70f0-44fa-8cd2-f8e00afb7245)

This screen appears if I try to enter to sLaunchMenu with L2+R2 with CFW Syscalls disabled
![image](https://github.com/aldostools/webMAN-MOD/assets/974897/d51d3805-2c50-49dd-908f-927e6bd72ec8)

If I press R2+**▢**, I get this message:
![image](https://github.com/aldostools/webMAN-MOD/assets/974897/e6858d2a-1b84-4c3e-b850-9b365bd38d75)

I have configured this combo in /setup.ps3 for R2+**▢**  (remember to SAVE the settings)
![image](https://github.com/aldostools/webMAN-MOD/assets/974897/f7f32bb0-f49d-4949-9f9d-52caa94db5c2)

If it isn't working for you, you must be doing something wrong.

**Comment by cloud-strife7777** [comment]
I have this so & save & restart. But Not works.

**Comment by aldostools** [comment]
I have configured my system and captured the screens showing that it's working. I cannot do more... I'm closing this case.

**Comment by cloud-strife7777** [comment]
But now it only works if the admin is activated! I had deactivated it and that's why it didn't work! Is that normal? And when I restored syscalls with custom combo, no other webman mod combos & s launch work anymore! Please fix!

**Comment by aldostools** [comment]
Only Admin mode has access to PS3MAPI module. That's why you can't restore the syscalls with that combo in User mode.

In User mode all functions are limited to mount games and a few other tasks while it's activated. Change to Admin mode before do anything special like re-enable syscalls.

**Comment by cloud-strife7777** [comment]
I use now Update system to Recover syscalls without Admin.

**Comment by aldostools** [comment]
I told you 3 days ago that System Update is an easier method:

> IMHO it's easier to re-enable the CFW Syscalls using CFW Tools menu or going to Settings > System Update. Or simply restart the console.

**Comment by cloud-strife7777** [comment]
Yeah but I love your webman mod Combos. Nevermind.

**Comment by aldostools** [comment]
You could enable Admin mode, then disable syscalls in the same combo, but that needs more customization.

You can learn about all the possibilities in:
https://github.com/aldostools/webMAN-MOD/wiki/Web-Commands

**Comment by cloud-strife7777** [comment]
I use system Update best way. Thx for all!
