### ISSUE TITLE
Request to support longer game names/addresses (& another thing)

### ISSUE THREAD

**Issue by pirsir76** [aldostools/webMAN-MOD#1001]
Hey Aldo,

I submitted this as an issue earlier but dismissed it as I thought it might only affect a few games.
But after a thorough inspection I discovered it affected a lot more than a few games; closer to a few hundred (if you include translations which have longer game names than usual.)

The issue:
Games with long names cannot be selected in the webMAN-MOD interface. This section of the interface:  PS3webMAN [Setup]/Files/...
I discovered that the size limits on names includes the names of the files that the games are in as well. (The file path.)
I've found it helpful to put .bin .cue games in files to keep them together.

Here's one PSX game that's affected by the problem:
Quaddle Family Mysteries 3, The - The Case of the Scarce Scarab - Parlor - Family Room [LSP-060103-0.1]
This game is un-selectable in webMAN-MOD.

Here's the length of the game file path on my PS3 set-up:
/dev_hdd0/PSX/Q/Quaddle Family Mysteries 3, The - The Case of the Scarce Scarab - Parlor - Family Room [LSP-060103-0.1]/Quaddle Family Mysteries 3, The - The Case of the Scarce Scarab - Parlor - Family Room [LSP-060103-0.1].cue

For this game to be selectable, webMAN-MOD would have to support file paths up to 228 columns long (if I'm not mistaken.)
Perhaps increasing the size to 250 columns would help, if that's possible?

Another thing:
While inspecting what the problem was with un-selectable games in webMAN, I also noticed something else.
Games with certain legal characters become un-selectable in webMAN.
One example is this game serial: [BLJM-61322]
If you include that serial in the game name, no matter how short the name is, it will be un-selectable in webMAN.
I found this out with the game: Dengeki Bunko - Fighting Climax Ignition (Japan) [T-En by Tsukimori v1.03] [BLJM-61322]

I discovered other legal combinations besides [BLJM-61322] that also make the game un-selectable.

Hoping you can help. (The game name length is the more important issue I think.)

Thanks!

**Comment by aldostools** [comment]
There are no plans in the short term to increase the length of files.

Try putting the games directly in /PSXISO or /PSXISO/Q without the directory that repeats the file name in the middle of the path.

Additionally try making the file name shorter. e.g. /dev_hdd0/PSXISO/Q/Quaddle Family Mysteries 3 [LSP-060103-0.1].cue

The file name in is example is very descriptive and the full path only has 66 characters

**Comment by pirsir76** [comment]
Thanks for the response Aldo, I will take your advice.
 What about the 2nd minor issue with the serial [BLJM-61322] making the game un-selectable?

**Comment by aldostools** [comment]
Try shortening the file name. I think the issue is the same: the file name is too long.

e.g. /dev_hdd0/PS3ISO/Dengeki Bunko - Fighting Climax Ignition [BLJM-61322].iso

**Comment by pirsir76** [comment]
> Try shortening the file name. I think the issue is the same: the file name is too long.
> 
> e.g. /dev_hdd0/PS3ISO/Dengeki Bunko - Fighting Climax Ignition [BLJM-61322].iso

It's not that it's too long with this game name, even a file path of: /dev_hdd0/PS3ISO/ [BLJM-61322] is un-selectable.
I narrowed it down to just having this  [BLJM-61322] in the file name makes the game un-selectable.

**Comment by aldostools** [comment]
It seems your game is not meeting some of the requirements described in:
https://github.com/aldostools/webMAN-MOD/wiki/Game-Paths-&-Covers

The games stored in PS3ISO must has file extension .ISO or .iso (or .bin, .img, .mdf)

Try removing the title id from the file name and check if the game is listed in the next scan.

**Comment by pirsir76** [comment]
Yep, that was the issue. Thanks a heap Aldo, I will close this "issue" now. :)
