### ISSUE TITLE
[Bug?] Can't call icon from other rcos

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#1007]
Aldo, looks like the command: 

/popup.ps3?<msg>&icon=<rsc_icon>&rco=<plugin_name>

can't call icons from other rco, only explore_plugin, 

i'm trying

/popup.ps3?Test&icon=1&rco=xai_plugin

and it returns the icons from the explore_plugin

**Comment by aldostools** [comment]
No description provided => No answer expected.

**Comment by LuanTeles** [comment]
> No description provided => No answer expected.

Heheh, you answered while i was editing the message :P

I hit enter by mistake

**Comment by aldostools** [comment]
The parameter &icon=&lt;name> must be the name of the texture image of up to 63 characters.

If you provide a number, it will return the system_plugin icons if the value is between 0 and 17, and from explore_plugin if the value is between 18 and 50.

````Basic
// system_plugin icons
"tex_notification_info",            //0
"tex_notification_friend",          //1
"tex_notification_headset",         //2
"tex_notification_caution",         //3
"tex_notification_keypad",          //4
"tex_notification_mediasever",      //5
"tex_temporary_icon",               //6
"tex_notification_psbutton_insensitive",    //7
"tex_notification_settings",        //8
"tex_notification_trophy_bronze",   //9
"tex_notification_trophy_silver",   //10
"tex_notification_trophy_gold",     //11
"tex_notification_trophy_platinum", //12
"tex_pointer_hand",                 //13
"tex_pointer_pen",                  //14
"tex_pointer_arrow",                //15
"tex_pointer_grab",                 //16
"tex_arrow_right",                  //17
// explore_plugin icons
"tex_psn_big",                      //18
"tex_psplus_icon",                  //19
"tex_Signing_In",                   //20
"tex_new_ws",                       //21
"tex_check_ws",                     //22
"tex_urgent_ws",                    //23
"item_tex_cam_icon",                //24
"item_tex_Profile_LevelIcon",       //25
"item_tex_ps_store",                //26
"tex_album_icon",                   //27
"item_tex_Players",                 //28
"tex_indi_NewRoom",                 //29
"tex_music",                        //30
"tex_photo",                        //31
"tex_video",                        //32
"tex_game",                         //33
"tex_lock_icon",                    //34
"tex_indi_Sign_out",                //35-Error icon
"tex_indi_Message",                 //36
"tex_Message_Sent",                 //37
"item_tex_CardBallon",              //38
"tex_loading_icon",                 //39
"tex_Avatar_Default",               //40
"item_tex_disc_bd",                 //41-PS3
"item_tex_disc_icon",               //42-CD
"item_tex_disc_cd_ps2",             //43-PS2
"item_tex_disc_ps1",                //44-PSX
"item_tex_disc_bd_contents",        //45-BD
"item_tex_disc_dvd",                //46-DVD
"game_tex_disc_unknown",            //47
"item_tex_psp_icon",                //48
"tex_indi_AFK",                     //49
"tex_go_game",                      //50

**Comment by LuanTeles** [comment]
Thanks for the clarification, i was using only the IDs, using the name works.

**Comment by LuanTeles** [comment]
@aldostools 

Hm... looks like the rco must be called first by the system before webman can access it

At leat it is the case of xai plugin

That's why on my first try the command was not working with the icon name and then when you said it again, i tested and it worked

/popup.ps3?Penis&icon=tex_check2_ws&rco=xai_plugin

doesn't work until i use a XMBML action to call it first and load in memory

Is there anything that can be done? i'm just asking this because i'm using xai_plugin as a icon container to  be called via webMAN commands popups, but i can use explore_plugin for that if there is no solution.

**Comment by aldostools** [comment]
Yes. The system plugin containing the resource must be loaded in memory.

The system plugin is referenced through View_Find (paf_F21655F3). paf_CF068D31 is not used in the project.

Check if /vshplugin.ps3mapi can be used. I only use resources from system_plugin or explore_plugin.

You could try also adding new resources to system_plugin.rco or explore_plugin_full.rco or replacing the ones unused.

**Comment by LuanTeles** [comment]
> Yes. The system plugin containing the resource must be loaded in memory.
> 
> The system plugin is referenced through View_Find (paf_F21655F3). paf_CF068D31 is not used in the project.
> 
> Check if /vshplugin.ps3mapi can be used. I only use resources from system_plugin or explore_plugin.
> 
> You could try also adding new resources to system_plugin.rco or explore_plugin_full.rco or replacing the ones unused.


Thanks aldo, i'll add the icons in the explore_plugin, i was just avoiding it because i have 16 of them, but i need to edit them anyway.
