### ISSUE TITLE
Serious WEBMAN bug from 1.47.01+ involving gameboot

### ISSUE THREAD

**Issue by raidriarxzant** [aldostools/webMAN-MOD#101]
Modifying game_ext_plugin.sprx causes error "This software cannot be started due to region restrictions" error whenever webMAN 1.47+ is installed. No such issue when using 1.46.02 or earlier. Bug appears both on Habib 4.81.02 and Rebug 4.81.02 when both are updated to Cobra payload 7.52

**Comment by Joonie86** [comment]
Closing old issues that have no further feedback. Please try the latest wMM and report back.
