### ISSUE TITLE
[Improvement] Script Execution

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#1016]
Aldo, it's not a big issue, but i'm wondering if something can be improved in the script execution part (If it is the case) , 2~3/10 times that i turn on my PS3 the system might freeze on HEN and even on CFW. (Happens on HEN more often than on CFW)

I can make more tests if needed, but i'm just expeculating that is something related to the Notification or Beep, because sometimes the beeps play and then it freezes before the notification.  On CFW i use wait 9 two times to match the XMB loading times and the freezes occurs in the notification part of the script  (When the XMB is loaded) and ON HEN, just after the activation

Do you have any suggestion?

**Comment by aldostools** [comment]
It depends on what commands you're running when the system hangs and at what moment your are executing the script.

When the system starts and when a game is launched are critical moments that could freeze the console due high memory consumption or kernel panic.

It would be helpful if you check Cobra debug log using socat.

**Comment by LuanTeles** [comment]
> It depends on what commands you're running when the system hangs and at what moment your are executing the script.
> 
> When the system starts and when a game is launched are critical moments that could freeze the console due high memory consumption or kernel panic.
> 
> It would be helpful if you check Cobra debug log using socat.

K, i just got a new laptop and now i have a working LAN port, finally i should be able to use socat, i'll do some tests and let you know
