### ISSUE TITLE
PS3 ISO's launching into a black screen.

### ISSUE THREAD

**Issue by majinmagikarp** [aldostools/webMAN-MOD#1020]
Before the most recent update everything was working perfectly. However, after downloading the most recent update for Webman everytime I try and load a PS3 game through both the Webman folder and my official PSN downloads I'm met with a black screen. I cannot quit back to XMB and when I press the power button after about 10 seconds it beeps 3 times. Homebrew apps such as Multiman and Irisman work fine, as does any PS2 iso I try and load. It just seems to be PS3 games specifically. I've tried downloading NoBD cfw and am met with the same result. But when I uninstall Webman everything works fine. I've also tried downgrading Webman to the previous version and still nothing. I'm running Evilnat 4.90 CEX Cobra 8.4 on a regular slim PS3.

**Comment by aldostools** [comment]
If your PS3 games are stored on NTFS or exFAT drives, it is possible that you could get a black screen due an incompatibility in .ntfs[] generated by multiMAN.

Try running prepISO to generate the proper .ntfs[] files again. If that doesn't work, try the following:

Try removing all USB drives, delete /dev_hdd0/tmp/wm_config.bin and reboot.
Go to /setup.ps3, disable content scanning at startup and save.
Connect back the USB drives and run prepISO.

**Comment by majinmagikarp** [comment]
> If your PS3 games are stored on NTFS or exFAT drives, it is possible that you could get a black screen due an incompatibility in .ntfs[] generated by multiMAN.
> 
> Try running prepISO to generate the proper .ntfs[] files again. If that doesn't work, try the following:
> 
> Try removing all USB drives, delete /dev_hdd0/tmp/wm_config.bin and reboot. Go to /setup.ps3, disable content scanning at startup and save. Connect back the USB drives and run prepISO.

I forgot to mention almost all of my games are in JB Folder format and everything is stored on my internal HDD. I don't have any kind of external storage connected to my PS3. Do you think I need to convert them to iso for them to work? As I said before there were no issues with anything before I updated. I was hoping downloading the previous version of Webman would fix the issue but I experienced the same problem.

**Comment by aldostools** [comment]
It's weird that your PSN games or games in JB folder format don't work from the internal HDD, even after having instaleld the previous version of webMAN MOD.

webMAN MOD only mounts the game. Cobra is who plays the game. It should be the same process also for IRISMAN or multiMAN (unless you have Cobra disabled).

I recommend that test creating an ISO and check if they work. Also test if inserting a PS3 physical disc in the tray makes a difference.

Also verify that Cobra is enabled. Another test that you could perform is to install webMAN MOD Lite Edition.

**Comment by majinmagikarp** [comment]
Deleting wm_config.bin seems to have fixed it. Thanks for the help I've been pulling my hair out the past 3 days trying to figure this out.

**Comment by Rezdj** [comment]
Hello, I'm having the same problem (with my games in JB folder) but i can't find where is wm_config.bin on my ps3 hdd...
edit: If it's in dev_hdd0/tmp I found it. If not I didn't find it and I have no freaking idea of where this could be.

**Comment by aldostools** [comment]
> Hello, I'm having the same problem (with my games in JB folder) but i can't find where is wm_config.bin on my ps3 hdd... edit: If it's in dev_hdd0/tmp I found it. If not I didn't find it and I have no freaking idea of where this could be.

The settings are stored in `/dev_hdd0/tmp/wm_config.bin`

**Comment by Rezdj** [comment]
thank you mister aldostools, next time I bootup my ps3, I'll remove it and see if it resolve my problem.

I profit of your response to thank you for your tools, those are extremely useful and bugfree!

**Comment by Rezdj** [comment]
I might have found the issue with my problems, I can't try it since i'm 700km away from my ps3 but it's probably something corrupt in the game's dump. I should seriously verify next time I dump something...
The fact it didn't work on rpcs3 too should have been a big enough indicator. 
edit : the dump was fucked, now with a good dump it worked!

**Comment by sagbadjaronis-pixel** [comment]
J'ai téléchargé Borderlands 2 en version ISO  quand je le lance avec Irisman le jeu s'affiche mais quand je veux jouer l'écran devient noir et le système se bloque que dois-je faire pour régler ce problème ? Pourtant le jeu n'est pas sur un externe

**Comment by aldostools** [comment]
Use an original Bluray disc of the game to get the dump. The downloaded games come from untrusted sources and the files could be corrupted.

If you downloaded a Redump ISO, you may have missed to include the dokey file needed to decrypt the 1:1 image.
