### ISSUE TITLE
PrepISO 1.31 - Does not detect more than 1 PS1 Game on ExFAT

### ISSUE THREAD

**Issue by biggles110** [aldostools/webMAN-MOD#1023]
Tested on PS3HEN 3.2.2, HFW 4.90.1, WMM 1.47.45 on a superslim, usb formatted in MBR ExFAT, prep iso only seems to detect 1 ps1 game in the PSXISO folder/ game subfolders.
Looking at /dev_hdd0/tmp/wmtmp, there is only a single ntfs info generated for that single game, so the problem suggest an issue with PrepISO?

This only appears to happen with ps1 games. 
PS3ISO, PKG, PS2ISO appears to be scanned fine, and all content shows in webmanmod.
Tested with both a thumbdrive and an external hdd, same issue.
Scan for /dev_ntfs has been disabled.

If I format these drives with MBR NTFS, all ps1 games are detected.

**Comment by aldostools** [comment]
The exFAT library has some issues related to the way in which it scan the files and use the folder handles.
It's possible that the issue could be related to the subfolder in PSXISO of the exFAT.

If it's working fine with NTFS, I recommend you that keep using that format. 
NTFS is preferred for PS3 over exFAT which is a relatively new HDD format supported.

**Comment by biggles110** [comment]
Thanks for the feedback. There is indeed an issue with subfolders in PSXISO on ExFAT it seems!
I have observed that the first (by date?) subfolder is identified and scanned, but doesn't resume after that.
If you happen to have an empty subfolder, then no games show at all.
If you don't use any subfolders and place everything in PSXISO, then all games are detected ok.

**Comment by aldostools** [comment]
Check [prepISO 1.32](https://github.com/aldostools/webMAN-MOD/releases/download/1.47.45/prepISO_1.32.pkg) https://github.com/aldostools/webMAN-MOD/commit/19712af477b8498d6fb17425de13ecee321a5739

It should fix the issues scanning the subfolders in PSXISO (and other folders)

**Comment by biggles110** [comment]
That seems to have done the trick!

Though I have noticed a different issue, though not sure if its environmental. PKG files in the PKG folder no longer appear to mount/install. After the loaded message, throws an error. This was working in 1.31.

Same with PS2ISO. In 1.31 it used to say "unsupported in hen", but now just throws an error instead.

**Comment by aldostools** [comment]
Thank you for your feedback. I will try to verify this issue later tonight or in the week.

**Comment by aldostools** [comment]
I found the issue. [prepISO 1.33](https://github.com/aldostools/webMAN-MOD/releases/download/1.47.45/prepISO_1.33.pkg) https://github.com/aldostools/webMAN-MOD/commit/49b694f95c92cccc029d8e96b064578a4210263d was uploaded
