### ISSUE TITLE
[Feature Request] Detect PS2 ISOs in DVD/CD folder additionally

### ISSUE THREAD

**Issue by TheAEffect** [aldostools/webMAN-MOD#1028]
Hello, 

I am currently using a micro SD card in connection with MX4SIO in the PS2. Now I wanted to use the microSD card in a USB stick on the PS3. However, since OPL is structured differently and uses the DVD and CD folders, I wanted to ask whether it is possible to specify in the settings in a checkbox that the CD and/or DVD folders should also be searched when scanning for PS2 ISOs.

The reason for this is that under Fat32 or exFat it is not possible to create a symlink to another folder. 

Best regards 

Artur :)

**Comment by aldostools** [comment]
Hello Artur,
I made the changes, but I haven't tested it yet. I still need to create a test environment for your scenario.

~~Unzip the sprx, upload it to /dev_hdd0/plugins/webftp_server.sprx and make sure that boot_plugins.txt has that path.~~

~~Go to /setup.ps3, check /dev_bdvd and SAVE. It should scan /PS3ISO, /PS2ISO, /PSXISO, etc. in the /dev_bdvd.~~

The ISO is supposed to be copied to the internal HDD when the game is mounted.

**Comment by TheAEffect** [comment]
Hello Aldo, 

thanks for the quick response.

I have replaced webftp_server.sprx (but in filezilla the old date of the file was still displayed, probably no change compared to the already existing one). Anyway, I then deleted and replaced it. The path in boot_plugins.txt is also correct.

Unfortunately, the games are not listed under PS2ISO.
Have I forgotten something / done something wrong?

Before the replacement, the menu looked like this:
![image](https://github.com/aldostools/webMAN-MOD/assets/100756263/b798d7cc-e6f7-4e5e-b1fc-791b5af7ab50)

Afterwards like this (with selection of /dev_bdvd):
![image](https://github.com/aldostools/webMAN-MOD/assets/100756263/0607bc83-b3c5-4046-a528-9b961625a4d9)

The micro SD card in the adapter (aka USB stick). Has the following folder structure:

<img src='https://github.com/aldostools/webMAN-MOD/assets/100756263/c0e0cfb5-6307-4bd9-bf27-6b80e7b7eef3)' width='150'> <img src='https://github.com/aldostools/webMAN-MOD/assets/100756263/e2e23807-9882-4815-823e-3345186197a2)' width='250'>

**Comment by aldostools** [comment]
The settings in /setup.ps3 look fine.

The folders scanned in the DVD are /PS2ISO, /PS3ISO, /PSPISO, /DVDISO, /PSXISO.

If that doesn't work, then you'll have to wait until I prepare a test environment to make the corrections (if required).

**Comment by TheAEffect** [comment]
Okay, now I understand. So I have to create additional folders within DVD, right?

I'll test the behavior under MX4SIO and PS3 to see if all ISOs are recognized and will give feedback later.

**Comment by aldostools** [comment]
No. In the root of the disc. SO they are found as /dev_bdvd/PS2ISO/filename.ISO

**Comment by TheAEffect** [comment]
But why as a disk? The ISOs are on a micro SD card / USB stick.

Or do I not understand the structure here? I was wondering why /dev_bdvd is scanned. I thought /dev_usb000 or /dev_usb001 should be enough.

Perhaps the confusion also lies in the naming of the "DVD" and "CD" folder. Open PS2 Loader (OPL) unfortunately needs these folders to recognize games that have been burned on a DVD. PS2 games that fit on a CD are placed in the "CD" folder.

That's why I asked if it is possible to look for ISOs on a USB stick not only within /PS2ISO, but also in the folders /DVD and /CD

**Comment by aldostools** [comment]
Oh I misunderstood your request... I thought you wanted to scan the ISO stored in physical DVD/CD inserted in the disc tray.

I will have to make changes to scan the folders CD/DVD like you requested originally.

**Comment by TheAEffect** [comment]
That would be great! Many thanks in advance

**Comment by aldostools** [comment]
You can download the new version from [Github](https://github.com/aldostools/webMAN-MOD/releases) or [Brewology](https://store.brewology.com/ahomebrew.php?brewid=310) or use the online updater.

CD and DVD folders now are scanned as PS2 games. If these folders don't exist in USB drives, the folders ISO and GAMES_DUP are scanned if they exist.

* There is no need to configure any additional settings.
* The folder name CD and DVD can be customized in the language files adding the keys: CUSTOM_PATH1 and CUSTOM_PATH2

**Comment by TheAEffect** [comment]
Just tested it and it works perfectly. Many thanks for the quick implementation!
