### ISSUE TITLE
Bug Webman Urgente

### ISSUE THREAD

**Issue by LordMonarca** [aldostools/webMAN-MOD#1029]
Estou usando CFW 4.90 eu meus 9 amigos também!! Sobre o Webamn Quando tentamos ligar o PS3, Usando o controle o vídeo não reconhece o controle e não conecta maaaas se eu ligar o vídeo Pelo próprio botão Do PS3 o botão OFF/ON e ligar o controle do ps3 o controle incrivelmente conectar tentar concertar isso porfavor tá diminuindo minhas boa experiência com vídeo game!

**Comment by aldostools** [comment]
Make sure "Disable content scan on startup" is checked in /setup.ps3

If this option is disabled, the system may be unstable randomly. Other than that, I don't know what else could be causing that issue.
