### ISSUE TITLE
Feature request : RETRO SUB CATEGORIES

### ISSUE THREAD

**Issue by ghost** [aldostools/webMAN-MOD#103]
Hey aldo, could you implement reto subcategories? because having a lot of roms with diferrent plataforms is a pain in the ass, categorizing by its console would be nice

**Comment by aldostools** [comment]
This build implements sub-groups for the following 35 paths under /ROMS folder in /dev_hdd0, /dev_usb*, /dev_sd, /dev_ms or /dev_cf:
"ATARI", "AMIGA", "BMSX", "DOOM", "DOSBOX", "FBA", "FMSX", "FUSE", "GB", "GBC", "GBA", "GG", "GEN", "GW", "HANDY", "HATARI", "INTV", "LUA", "JAGUAR", "LYNX", "MAME", "MEGAD", "NES", "NGP", "O2EM", "PCE", "PCFX", "SGX", "SNES", "QUAKE", "VICE", "VBOY", "WSWAM", "VECX", "ZX81"

Download SPRX: [webMAN-MOD_1.47.22.zip](https://github.com/aldostools/webMAN-MOD/files/3255336/webMAN-MOD_1.47.22.zip) (extract and copy the sprx to /dev_hdd0/plugins)

The ROMS list is generated in separated XML for each sub-folder.
Each XML supports the maximum amount of memory defined in /setup.ps3
This means that the number of ROMS supported per category has been increased significantly.

**Comment by aldostools** [comment]
The build 1.47.22 19168e8c2fed5b6f0bb2d6ad9e933add148cc01e now scans for content in the following 60 sub-folders under **/ROMS** folder in /dev_hdd0, /dev_usb*, /dev_sd, /dev_ms or /dev_cf:

"2048", "MAME", "MAME078", "MAME2000", "MAME2003", "FBA", "FBA2012", "ATARI", "ATARI2600", "ATARI5200", "ATARI7800", "JAGUAR", "LYNX", "HANDY", "HATARI", "NXENGINE", "AMIGA", "VICE", "DOSBOX", "GW", "DOOM", "QUAKE", "LUA", "O2EM", "INTV", "BMSX", "FMSX", "PCE", "PCFX", "SGX", "NGP", "NES", "FCEUMM", "NESTOPIA", "QNES", "GB", "GAMBATTE", "TGBDUAL", "GBC", "GBA", "VBOY", "VBA", "MGBA", "POKEMINI", "GENESIS", "GEN", "MEGAD", "GEARBOY", "GG", "ZX81", "FUSE", "SNES", "MSNES", "SNES9X", "SNES9X2005", "SNES9X2010", "SNES9X_NEXT", "THEODORE", "VECX", "WSWAM"

A custom label for these folders can be defined in /dev_hdd0/tmp/wm_lang/LANG_EMUS.TXT
(Use [/dev_hdd0/tmp/wm_lang/LANG_ROMS.TXT](https://github.com/aldostools/webMAN-MOD/blob/master/_Projects_/updater/custom/dev_hdd0/tmp/wm_lang/LANG_ROMS.TXT) as template)

If the file with the custom names doesn't exist, the template file [/dev_hdd0/tmp/wm_lang/LANG_ROMS.TXT](https://github.com/aldostools/webMAN-MOD/blob/master/_Projects_/updater/custom/dev_hdd0/tmp/wm_lang/LANG_ROMS.TXT) will be used.

If none of these files exist or the label is not found, the name of the sub-directory will be used (e.g. NES)

This build 19168e8c2fed5b6f0bb2d6ad9e933add148cc01e also fixes the listing of ROMS broken for HTML and sLaunch in the test build included in the zip above.
