### ISSUE TITLE
[Feature Request] Autoconvert .ISO to .BIN.ENC for PS2 Games

### ISSUE THREAD

**Issue by TheAEffect** [aldostools/webMAN-MOD#1032]
Hi Aldo,

I wanted to ask whether it is possible to automatically convert the `.ISO` for PS2-Games into `.BIN.ENC` and move it to `/dev_hdd0/PS2ISO/` on HEN-compatible consoles only. The reason is that PS2 `ISOs` cannot be started on HEN.

Currently only one error message is displayed: 
<img src="https://github.com/aldostools/webMAN-MOD/assets/100756263/a3500b34-b45b-4df4-a708-ed17226a8788" width="250">

This is not necessary on CFW, as `.ISO` can be loaded here (this is also copied to the internal hard disk as `.ISO` by default).

The only reason Multiman is used is for conversion and manual copying to `/dev_hdd0/PS2ISO/` and renaming from `.bin.enc` (lowercase) to `.BIN.ENC` (uppercase)

If this could be implemented, it would be a significant relief.

Many thanks in advance.

Best regards
Artur

**Comment by aldostools** [comment]
Hello Mr Artur Schnell,
The automatic convesion is not feasible due the increased demand of memory resources.

Use [Apollo Save Tool](https://store.brewology.com/ahomebrew.php?brewid=321) to convert PS2 ISO to PS2 Classics. The `.BIN.ENC` is created directly in `/dev_hdd0/PS2ISO/`

**Comment by Msx325** [comment]
M
