### ISSUE TITLE
Psn error after install webman

### ISSUE THREAD

**Issue by KiraPsN** [aldostools/webMAN-MOD#1033]
An error has occurred. Your psn session has been terminated. (80028E01)

**Comment by aldostools** [comment]
This error is not related to webMAN MOD. Check the [error codes in psdevwiki](https://www.psdevwiki.com/ps3/Error_Codes#Generic_errors)

<table>
<tr><td>Unable to connect to PSN<td>0x80028E01<td>HTTP status error was returned from the server // Reboot console and try connecting again (PSN may be down for maintenance),<br>if this fails, try connecting later; if setting up a network connection, settings may be incorrect; if issues continue then check internet connection
</table>
