### ISSUE TITLE
Add router to webman mod scan content

### ISSUE THREAD

**Issue by Gurinkajidan** [aldostools/webMAN-MOD#1037]
So I was trying to use my router disk to have a PS3 folder where I could use webman to scan its content with ps3 iso and be able to play them. The problems are that for example it works as a smb1 share and uses user and password as credential to access the folders on it. Can someone help ? I cant even add this folder as a DLNA media server, Is just on me I bet this is doable I am just too newb

**Comment by aldostools** [comment]
webMAN MOD -or more specifically Cobra payload- mount games using the netiso protocol implemented in ps3netsrv.
It cannot mount games through DLNA or SMB.

Check in your router is supported by some of the several ports of ps3netsrv:
https://github.com/aldostools/webMAN-MOD/tree/master/_Projects_/ps3netsrv#other-ports--forks

**Comment by Gurinkajidan** [comment]
Couldn´t find any , this is my router:
 https://www.alticelabs.com/wp-content/uploads/2022/10/FL_GR241AG_FiberGateway-4x4_ALB_EN.pdf
it has veip0** port forwarding and security rules for some old games like age of empires III so I got some faith it was possible
I have been using windows ps3netserver to grab the files as mapped network from the router and give it t the console, but even with all cable connected from pc to router and pc to ps3 is still not fast enough to prevent lagginmg on video (in game most of the time has no lag)

**Comment by aldostools** [comment]
In that case you should consider replacing the router with one supported by ps3netsrv or attaching a device that support ps3netsrv like: android device, laptop, PC, Raspberry Pi, etc. Then share the router disk from that device.

ps3netsrv is supported by a large variety of devices that support OpenWrt, Java, Android, Linux, Windows or Mac.

**Comment by Gurinkajidan** [comment]
Have to find better hardware thank you aldo :)
