### ISSUE TITLE
WebMAN spawning infinite notifications by holding combo buttons

### ISSUE THREAD

**Issue by Kyogre** [aldostools/webMAN-MOD#104]
For example, if you hold select+start combo for some seconds, you will got infinite system info notifications instead of single one. Thus we need an option (enabled by default) that will restrict such spawning, or even option to disable execution of commands when combo-buttons were held instead of single press.

**Comment by RandQalan** [comment]
hold same combo again will turn it off

**Comment by Kyogre** [comment]
yea, you are right, thank you
