### ISSUE TITLE
[Issue] Move command with wildcard

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#1041]
Aldo i'm using  to move downloaded themes to the theme folder

/move.ps3/dev_hdd0/download/theme/*.p3t&to=/dev_hdd0/theme

![image](https://github.com/aldostools/webMAN-MOD/assets/110236244/466c7d93-0551-44b4-ac9c-30f3287e5bea)

But as you can see not all themes are being moved

![image](https://github.com/aldostools/webMAN-MOD/assets/110236244/6d70f74d-b8cb-4a20-a197-07a442e4cada)

To move all i need to run the command multiple times, do you have any idea?

**Comment by aldostools** [comment]
It looks like moving the files from the directory causes that the pointer to the next file change, resulting in some files being skipped.

This may affects the DELETE, RENAME and MOVE operations. It requires additional tests and probably a change in the way the files are scanned in file_scan.h.

**Comment by aldostools** [comment]
Try this fix 🤓 
[webftp_server.zip](https://github.com/aldostools/webMAN-MOD/files/14728994/webftp_server.zip)

**Comment by LuanTeles** [comment]
Thank you Aldo, it's working now :)

**Comment by LouisGarry** [comment]
> This may affects the DELETE, RENAME and MOVE operations. It requires additional tests and probably a change in the way the files are scanned in file_scan.h.

Hello Aldo, the change here creates a compilation error if #define USE_NTFS in flags.h commented.

**Comment by aldostools** [comment]
> Hello Aldo, the change here creates a compilation error if #define USE_NTFS in flags.h commented.

Thanks for the bug report. It has been fixed. 👍
