### ISSUE TITLE
Webman prepiso

### ISSUE THREAD

**Issue by stergios007** [aldostools/webMAN-MOD#1043]
Hi 
I have a problem with webman and prepiso. I follow the guide fro mr marios youtube how to recognise ps3 ntfs format. I have hen 4.90 and the previous version of webman that came out 2 days ago. I foll step by step the tutorial of mr marios and in the end it doesnt appear folder with name dvd. I create a folder with the name PKG.i refresh from the webman set up xbm and games but nothing happens. I didnt try after the refresh to restart the console.

**Comment by aldostools** [comment]
Try deleting /dev_hdd0/tmp/wm_config.bin to reset the config to the default.

Then go to /setup.ps3 only check "Disable content scan at startup" and save the settings.

Make sure that the folder `PKG` is in the root directory of the pendrive formatted in NTFS. The folder name must be in caps.

Inside `PKG` put the package files .pkg (the file extension must be in lower case).

Plug the pendrive in the USB port 0 (the one closest to the BD drive) and run prepISO.

Wait while it scan the files. You will get a black screen for a few seconds before return to XMB. If you installed 1.47.46 you may hear a trophy sound when the scan is done.

Go to webMAN Games > Blu-ray and DVD folder and launch the [PKG].

If the folder still doesn't appear, go to Remote Play and exit to refresh XMB. The folder should be there.

**Comment by stergios007** [comment]
You are amazing.it works when i delete wm_config.bin. thank u very much u are amazing. I didnt go to remote play. Thank u again
