### ISSUE TITLE
PS1.SELFEMU Notification

### ISSUE THREAD

**Issue by PolymetricPeacock** [aldostools/webMAN-MOD#1047]
Hello! I've noticed a strange notification that appears upon launching a PlayStation One game from WebMAN Mod.

> ps1.selfemu

The thing that's strange to me is that it never a appears when loading a physical disc, and an option with similar naming can be found in the Scan for Content section of /setup.ps3. What exactly does this mean, and is it possible to disable this notification from appearing as it doesn't appear from loading a PlayStation One game under normal circumstances? Thank you in advance!

**Comment by aldostools** [comment]
That message tells you which emulator is being used. There are 2 emulators and some games work better with one of them.

It only appears when a PSXISO is mounted through webMAN MOD. It doesn't appear when a physical disc or PS1 Classic game is launched.
