### ISSUE TITLE
USB support for ps2 emulation?

### ISSUE THREAD

**Issue by sneps85** [aldostools/webMAN-MOD#105]
Is it possible to make use of PS3 mics for e.g. a PS2 singstar game?

**Comment by ghost** [comment]
You can use wired version of singstar mics in ps2 games, but only on old fat PS3 models. Supported models are cech a/b/c/e.

Anyway you can use your ps2 discs with PS3 version of singstar. That way you get compatibility for all PS3 models, and mics models. For help follow this tutorial: http://www.psx-place.com/threads/tut-mounting-ps2-singstar-on-ps3-using-webman-mod-mount_ps2-feature.12368/
