### ISSUE TITLE
Admin display is displayed incorrectly!

### ISSUE THREAD

**Issue by cloud-strife7777** [aldostools/webMAN-MOD#1050]
Admin display is shown the wrong way round! If it says Admin is active then it is deactivated and vice versa. Please fix.

**Comment by aldostools** [comment]
Thank you for your comment. Could you provide screen capture and the steps to reproduce the issue?

**Comment by cloud-strife7777** [comment]
Look, when you activate Admin it says Admin deactivated in the top right corner!

**Comment by cloud-strife7777** [comment]
Thank you!!! It works already!! :)
