### ISSUE TITLE
Doesn't read my ISO files 

### ISSUE THREAD

**Issue by benjioffway** [aldostools/webMAN-MOD#1051]
Hello, I am having a problem being able to run my .ISO games through a USB in Ntfs format and nothing, I also tried with 32fat format but nope, my console is a super PS3, it came out model cech 4301a 
To detail my error in more detail, I connect my USB, I open prepISO I scan the games with webman, it scans it and when I try to open it it says, "mounting" and at the end a red sign in the upper right corner that says "Error". Please a solution

**Comment by aldostools** [comment]
Is the external HDD larger than 2TB? If so, it's possible that you need to increase the cluster size.

Have you checked if the ISO is too fragmented? If the number of segments is too large, the ISO could fail.

Did you enter to multiMAN after having scanned the games? Some versions of multiMAN can corrupt the cached files created by prepISO. To solve this, you have to run prepISO again.

It could be also a hardware issue like deffective USB port, the enclosure, disk going to sleep mode, etc.

**Comment by benjioffway** [comment]
My USB drive is less than 2TB, the game I'm trying to mount I don't know if it is fragmented, it is a single .ISO drive 
The steps I follow are these
-I connect my USB drive 
-I open prepiso
-I scan the game with WebMAN
-It reads the game, I try to open it and I get an error when mounting the .ISO

**Comment by aldostools** [comment]
You only have to run prepISO and wait until the game list is updated when it returns to XMB. prepISO send the scan command automatically to webMAN.

Verify that the game is not corrupted after copy it. Try making a new copy of one small ISO in the external drive to verify if it's an issue with the HDD or with the games.

If you're using NTFS make sure that the ISOs are not using NTFS compression.

You also could try a different external drive or pendrive. Or downgrade to a previous version.

As a last resort, you should try using FAT32 with split ISO.

**Comment by RinMaru** [comment]
> Is the external HDD larger than 2TB? If so, it's possible that you need to increase the cluster size.
> 
> Have you checked if the ISO is too fragmented? If the number of segments is too large, the ISO could fail.
> 
> Did you enter to multiMAN after having scanned the games? Some versions of multiMAN can corrupt the cached files created by prepISO. To solve this, you have to run prepISO again.
> 
> It could be also a hardware issue like deffective USB port, the enclosure, disk going to sleep mode, etc.

How big does the cluster size need to be? 32k ntfs is as far as you can go before Webman doesnt see it. If you use exfat you can do 64k but only simple file manager will see it and not webman mod.
