### ISSUE TITLE
[Bug?] Duplicated Games

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#1056]
Aldo, I don't play games on PS3, but today I tested some games to see how performance improves with higher overclocks. I connected my external HDD and scanned the games, but I'm consistently getting duplicated games. Any idea why?

I just have one USB connected.

![image](https://github.com/aldostools/webMAN-MOD/assets/110236244/8b9bf52e-67e8-4d25-8466-9444129dbfeb)

**Comment by aldostools** [comment]
Please upload this file /dev_hdd0/xmlhost/game_plugin/mygames.xml

Maybe looking at the XML I could identify what's whappening... the picture of a single game is not enough information.

**Comment by LuanTeles** [comment]
here you are

[mygames.zip](https://github.com/aldostools/webMAN-MOD/files/14938871/mygames.zip)

**Comment by aldostools** [comment]
Can you show a screenshot of the "Scan for content" in /setup.ps3?

I see your disk is in an USB HUB because it's reading USB07 which is not a standard port.

**Comment by aldostools** [comment]
You could try attaching the USB disk to USB01 or USB00

**Comment by LuanTeles** [comment]
Yeap, i'm using a USB hub, i use this since years and it's always usb007, i never had this problem before

![image](https://github.com/aldostools/webMAN-MOD/assets/110236244/24286b90-8958-4367-b8d8-ec232577ab2f)

I can only wonder if it's something in the new version of webMAN or the overclocks, that's the only difference I have since the last time it worked correctly

![image](https://github.com/aldostools/webMAN-MOD/assets/110236244/99c745a7-fb30-47a1-b906-70a18d3f07e9)

**Comment by LuanTeles** [comment]
Anyway, i'll try without the HUB (i doubt that it is the problem) and going back to stock clock values.

**Comment by aldostools** [comment]
There is the problem: /dev_usb007 is listed twice (both settings are checked)

**Comment by LuanTeles** [comment]
> There is the problem: /dev_usb007 is listed twice (both settings are checked)

Oh i just saw that, lol, it never happened before.

**Comment by aldostools** [comment]
Give me few minutes. I'll try to fix it.

**Comment by aldostools** [comment]
Extract the sprx of [webftp_server.zip](https://github.com/aldostools/webMAN-MOD/files/14940609/webftp_server.zip) in /dev_hdd0/plugins

Then restart and refresh XML. /setup.ps3 should not list usb7 twice

**Comment by LuanTeles** [comment]
> Extract the sprx of [webftp_server.zip](https://github.com/aldostools/webMAN-MOD/files/14940609/webftp_server.zip) in /dev_hdd0/plugins
> 
> Then restart and refresh XML. /setup.ps3 should not list usb7 twice

Thank you aldo, fixed =)
