### ISSUE TITLE
FTP on ps3hen 4.91 hfw issues

### ISSUE THREAD

**Issue by eliekh05** [aldostools/webMAN-MOD#1058]
i can't do ftp on ps3hen 4.91 hfw using webman mod using my home router but my mobile data hotspot i can

Specs:

PS3 Super Slim HFW and Hen

Files and folder manager: webman mod and multiman

Versions: All latest

Devices trying to use: phone and windows 11 laptop

Patches: PSN Patch

expected:

it should provide the website of webman

actually:

it doesn't ping to PS3 and doesn't even show me the page

**Comment by aldostools** [comment]
Verify your network settings in XMB > Settings > Network. 
Make sure that you can navigate the internet using the PS3 Internet browser.

Verify if you have ADMIN/USER MODE checked in XMB/In-Game PAD SHORTCUTS of [/setup.ps3](https://github.com/aldostools/webMAN-MOD/wiki/Setup-Options#xmbin-game-pad-shortcuts)
Uncheck it if it's checked and save the settings.

Also verify if you checked the options "Disable FTP Service" or "Disable remote access to FTP/WWW services".
Uncheck them if they're checked and save the settings.

Alternatively you can delete /dev_hdd0/tmp/wm_config.bin and restart the PS3.

From PC use FileZilla FTP Client. It's proven to be very stable with webMAN MOD's FTP server.
https://github.com/aldostools/webMAN-MOD/wiki/Setup-Options#webman-mod-setup-1

**Comment by eliekh05** [comment]
> Verify your network settings in XMB > Settings > Network. 
> 
> Make sure that you can navigate the internet using the PS3 Internet browser.
> 
> 
> 
> Verify if you have ADMIN/USER MODE checked in XMB/In-Game PAD SHORTCUTS of [/setup.ps3](https://github.com/aldostools/webMAN-MOD/wiki/Setup-Options#xmbin-game-pad-shortcuts)
> 
> Uncheck it if it's checked and save the settings.
> 
> 
> 
> Also verify if you checked the options "Disable FTP Service" or "Disable remote access to FTP/WWW services".
> 
> Uncheck them if they're checked and save the settings.
> 
> 
> 
> Alternatively you can delete /dev_hdd0/tmp/wm_config.bin and restart the PS3.
> 
> 
> 
> From PC use FileZilla FTP Client. It's proven to be very stable with webMAN MOD's FTP server.
> 
> https://github.com/aldostools/webMAN-MOD/wiki/Setup-Options#webman-mod-setup-1
> 
> 
> 
> 

i have network connection because i can install game patches and everything in the reply are unchecked

**Comment by aldostools** [comment]
Then the network connection between your PC and PS3 should be blocked by your PC's firewall or router settings.

You may want to temporarily disable your Windows firewall to check if it's blocking the access to PS3.
https://www.lifewire.com/turn-off-and-disable-firewall-in-windows-11-5192308

Another option that you could try is connecting the PS3 directly to PC without the router.
https://consolemods.org/wiki/PS3:Transferring_Files_with_FTP
https://www.psx-place.com/threads/very-simple-way-to-direct-connect-ps3-to-pc.17052/

**Comment by eliekh05** [comment]
> Then the network connection between your PC and PS3 should be blocked by your PC's firewall or router settings.
> 
> 
> 
> You may want to temporarily disable your Windows firewall to check if it's blocking the access to PS3.
> 
> https://www.lifewire.com/turn-off-and-disable-firewall-in-windows-11-5192308
> 
> 
> 
> Another option that you could try is connecting the PS3 directly to PC without the router.
> 
> https://consolemods.org/wiki/PS3:Transferring_Files_with_FTP
> 
> https://www.psx-place.com/threads/very-simple-way-to-direct-connect-ps3-to-pc.17052/
> 
> 

i think there is problem with the webman mod in the code because in older it is working and i am telling you that there is no problem with the network itself because i can download the updates for the games

**Comment by aldostools** [comment]
It's weird, because nobody else has reported issues with FTP and I don't have issues either 🤔

**Comment by eliekh05** [comment]
> It's weird, because nobody else has reported issues with FTP and I don't have issues either 🤔 

so what to do

**Comment by aldostools** [comment]
Use older version if it's working as you said.

**Comment by eliekh05** [comment]
> Use older version if it's working as you said.

if older version worked means you did something wrong if it did not work i will reinstall the hfw firmware without losing any data

**Comment by aldostools** [comment]
It's possible that there is something wrong, but if I cannot reproduce the bug I cannot fix it... it's working fine on my side.

**Comment by eliekh05** [comment]
> It's possible that there is something wrong, but if I cannot reproduce the bug I cannot fix it... it's working fine on my side.
> 
> 

is there a way register it as domain not ip and is it possible that i just have reinstall the firmware without loosing data but not working

**Comment by eliekh05** [comment]
> It's possible that there is something wrong, but if I cannot reproduce the bug I cannot fix it... it's working fine on my side.
> 
> 

all this time it was network router

**Comment by R3DDx7** [comment]
> i can't do ftp on ps3hen 4.91 hfw using webman mod using my home router but my mobile data hotspot i can
> 
> Specs:
> 
> PS3 Super Slim HFW and Hen
> 
> Files and folder manager: webman mod and multiman
> 
> Versions: All latest
> 
> Devices trying to use: phone and windows 11 laptop
> 
> Patches: PSN Patch
> 
> expected:
> 
> it should provide the website of webman
> 
> actually:
> 
> it doesn't ping to PS3 and doesn't even show me the page

------------------------------------------------------------------
**UPDATE NVM i see that it has been resolved... CHEERS!!!**

not sure if this has been resolved yet...
but maybe it has something to do with your particular router, or an internal setting you have enabled on the router?
