### ISSUE TITLE
webMAN-MOD SERIOUS bug insta freeze ps3

### ISSUE THREAD

**Issue by Jezza-x3** [aldostools/webMAN-MOD#106]
When booting my ps3, it's as if it's forcing Disable CFW syscalls and delete history files with the R2 and Triangle button. 3 seconds after turning it on I hear the beep like it's been pressed. When I load the screen it just freezes. I can ONLY get around this by booting into safemode(or video changing settings) and turning on "Disable CFW syscalls and delete history files at system startup" so R2 and triangle doesn't work. Then when I get in game I'm spammed with messages at the top right about "Not in XMB"

I don't know how to replicate this. (meaning if I reinstall the firmware Idk how to make it do this again)

**Comment by Joonie86** [comment]
Closing old issues that have no further feedback. Please try the latest wMM and report back.
