### ISSUE TITLE
[Question] Select Multiple Folders

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#1062]
Aldo, i need to copy multiple folders through file manager and i'm wondering if is there any way to select multiple folders?

If not, would it be difficult to implement? (Questions via check boxes) This would make it easier to copy and delete multiple folders.

![image](https://github.com/aldostools/webMAN-MOD/assets/110236244/e5e70db0-42c0-4a3b-8891-1cc7348aeb29)

**Comment by aldostools** [comment]
it would need a good amount of coding in javascript.

Use IRISMAN or multiMAN. They allow copy of multiple selected folders. They copy faster too.

**Comment by LuanTeles** [comment]
> it would need a good amount of coding in javascript.
> 
> Use IRISMAN or multiMAN. They allow copy of multiple selected folders. They copy faster too.

Oh, in that case, I'd rather opt for a homebrew file manager as well. Unfortunately, I left my gamepad at the beach house, so for now, I'm relying on webman. 

Thanks.

**Comment by aldostools** [comment]
pad.aldostools.org works perfectly fine with IRISMAN. It also works with multiMAN although it's a bit harder to use.
