### ISSUE TITLE
FPS combo blackscreen!

### ISSUE THREAD

**Issue by cloud-strife7777** [aldostools/webMAN-MOD#1064]
FPS display sometimes randomly gives black screen.

**Comment by aldostools** [comment]
It's caused by the plugin VshFpsCounter. If it's showing the CPU/RSX speed, try setting `showClockSpeeds: Off` for xmb and game in /dev_hdd0/tmp/wm_res/VshFpsCounter.yaml

That should reduce the black screens. Also don't add it to /dev_hdd0/boot_plugins.txt. Instead use L3+R3 to load it.
