### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by cloud-strife7777** [aldostools/webMAN-MOD#1066]
different colors for text display FPS possible?

**Comment by aldostools** [comment]
Thank you for your message. Unfortunately the configuration file VshFpsCounter.yaml does not accept the color as parameter.

It should be possible modifying the vector m_ColorText{ 1, 1, 1, 1 }; in the source code.

You could request the feature to @TheRouletteBoi in his [Github repository](https://github.com/TheRouletteBoi/RouLetteVshMenu/releases/tag/fps-counter-2.7). He is the author of VshFpsCounter.
