### ISSUE TITLE
Makes Hen freeze if run with other plugins

### ISSUE THREAD

**Issue by Gerhardbosch10** [aldostools/webMAN-MOD#1068]
if webmann run alone it works fine but if run with ps3xpad it makes the whole ps3 freeze and you need to remove power cable for reboot and I am using the latest version

**Comment by aldostools** [comment]
Try loading ps3xpad through PS3MAPI GUI via web or check if the lite edition don't cause issues (in case the freeze is due lack of memory).

**Comment by Gerhardbosch10** [comment]
I'll do try that as soon as I wake up was busy trying to get it to work most of the night. thnx for the help

**Comment by LuanTeles** [comment]
> if webmann run alone it works fine but if run with ps3xpad it makes the whole ps3 freeze and you need to remove power cable for reboot and I am using the latest version


Are you using a SSD? if so , it's a known issue.

You can load just fine with PS3MAPI or you can create a boot_init.txt to load your plugins via webMAN.

**Comment by Gerhardbosch10** [comment]
I'm gonna start trying things now it doesnt have a ssd it's the basic super slim version with i think 14gb internal storage

**Comment by Gerhardbosch10** [comment]
to do the boot_init.txt do i just add that to the main directory and stil leave the plugin in the plugin folder and just add the directory there instead of the boot_plugin

**Comment by aldostools** [comment]
boot_init.txt and autoexec.bat only accept scripts commands.

Here are the web commands to load VSH plugins:
`/loadprx.ps3/<path>` - load prx in slot 6
`/loadprx.ps3?slot=<n>&prx=<path>` - load sprx in the specifed slot (default slot 6)

**Comment by Gerhardbosch10** [comment]
tried using PS3MAPI but it just says deviced denied access basically even though i enabled it in webman settings

**Comment by aldostools** [comment]
In that case you have to ask  in PSX-PLACE forums for support. Maybe the author of the other plugin could answer.

**Comment by Gerhardbosch10** [comment]
for the boot init do i just put it in the main directory if so i did put it there with the first command but didnt do anything. oh and i found out if me running webman,multiman and hen i have 2156kb free memory could that be the problem

**Comment by Gerhardbosch10** [comment]
ill go ask there than as well

**Comment by aldostools** [comment]
> for the boot init do i just put it in the main directory if so i did put it there with the first command but didnt do anything. oh and i found out if me running webman,multiman and hen i have 2156kb free memory could that be the problem

Load the plugin from XMB. When you run multiMAN or other apps VSH is unloaded.

**Comment by Gerhardbosch10** [comment]
the plugin isn't there. you just have to add it into the plugin folder and add the directory in boot_plugins it usually loads when you load hen but after it tells me it loaded hen and the webman mod it freezes on hen screen Ill ask on the other plugins page as well for help

**Comment by Gerhardbosch10** [comment]
just decided to give up not worth struggeling

**Comment by LuanTeles** [comment]
Mine is working just fine

You can use my PS3 Pro mode, it has a plugin manager, you can enable/disable the plugins that you want without any issues.
