### ISSUE TITLE
external gamedata not working

### ISSUE THREAD

**Issue by kyvaughn** [aldostools/webMAN-MOD#107]
When i try to use external gamedata webman appears to successfully recognize and use the fat32 usb drive but when I load a game that requires installation files it says there is not enough room. The amount of available room is consistent with what is available on the internal storage. So even though there is room it seems to be using the internal storage space as the reference to available room not the usb drive.

**Comment by aldostools** [comment]
Only the folder **/dev_hdd0/game** is redirected to USB. The system will continue reporting the real free space on each device, including the internal HDD.

You could try using the following options available on Rebug CFW:

* **Fake Free Space**
Fake the amount of free space on the HDD, in ”Fake Limit Size” function.
– ”Off” : deactivate Fake Free Space function.
– ”On” : activate Fake Free Space function.
– ”On (Ignored in NP Trophy)” : activate Fake Free Space function exept for trophy functions.

* **Fake Limit Size**
Set the amount of free space on the HDD in MB when the ”Fake Free Space” function is activated.

More info about these settings: https://rebug.me/debug-settings/rebug-settings/

Note: The external gamedata is not compatible with games that use large files (4GB) due the file size limitation of FAT32.

**Comment by kyvaughn** [comment]
Thank you for your quick responce...
Well I don't use Rebug. Is there a stand alone app or may I make a feature request?

**Comment by kyvaughn** [comment]
I could not find any 3rd party homebrew. Please consider adding this functionality to webman mod. Keep up the great work.

**Comment by aldostools** [comment]
The fake free space on HDD is a feature already available in Rebug... If you need the feature, consider to install that custom firmware or increase the free space replacing the internal HDD with one with more storage capacity or removing content of the internal HDD (e.g. game data, movies, etc.).

**Comment by kyvaughn** [comment]
external gamedata was a freely available self-contained application and also implemented in multiman and you still integrated that feature. I don't think what I'm asking for is outside of the scope of this utility. Rebug has too many features that can really hose your system and I don't want them for just one feature.
