### ISSUE TITLE
[Quetion] Script

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#1070]
Aldo, is there a way to make a command or script that only runs when the gameboot is triggered?

I need to do some commands and a remap right after starting the gameboot, because using ingame.bat or GAME-ID.bat the command is executed when all the resources are already loaded.

For example the remap of the system_plugin.rco, i was using the onxmb.bat to map and the ingame.bat to unmap it, so it was working but we found those problems so i needed to remove it

So i need a way that the remap command is executed only when the game boot process started but still not ingame, is it possible?

**Comment by aldostools** [comment]
You can run events on specific games creating scripts per title id:
/dev_hdd0/tmp/wm_ingame/`TITLEID`.bat

This script is fired when the poll thread detects that a game has been started.
`/dev_hdd0/ingame.bat`

This script is fired when the poll thread detects a game exit or VSH is loaded.
`/dev_hdd0/onxmb.bat`

**NOTE**: There could be a small delay between the actual event and the moment when the poll thread detect it.

**Comment by aldostools** [comment]
I think what you're looking for can only be done with a kernel hook in PS3HEN/ Cobra / Mamba.

**Comment by LuanTeles** [comment]
> You can run events on specific games creating scripts per title id: /dev_hdd0/tmp/wm_ingame/`TITLEID`.bat
> 
> This script is fired when the poll thread detects that a game has been started. `/dev_hdd0/ingame.bat`
> 
> This script is fired when the poll thread detects a game exit or VSH is loaded. `/dev_hdd0/onxmb.bat`
> 
> **NOTE**: There could be a small delay between the actual event and the moment when the poll thread detect it.


Both TITLEID.bat and ingame.bat are executing the remap when the system_plugin.rco is already loaded ingame, so the remap will not be loaded.

The remap need to be done between the gameboot and game launching.

> I think what you're looking for can only be done with a kernel hook in PS3HEN/ Cobra / Mamba.

Ah, not worth the hassle then.

**Comment by LuanTeles** [comment]
Aldo, i just talked to Nat, seems like it's possible

![image](https://github.com/aldostools/webMAN-MOD/assets/110236244/56f0ae3a-03db-4f11-b00d-c5164e4576d9)
