### ISSUE TITLE
Retro ROMS cover download (scrape)

### ISSUE THREAD

**Issue by araujoraveli** [aldostools/webMAN-MOD#1077]
Would it be possible to implement an option within the webmanmod menu to automatically download game covers into the ROMs folder?
I use RECALBOX on a Raspberry Pi 3b+ and it has this feature, it is an open source system, I could see the code and use it as a base, what do you say?
One of the websites used for this is: [https://www.screenscraper.fr](https://www.screenscraper.fr)

Another point, would it be possible to implement a resource similar to "gamelist.xml" for MAME/FBNEO/ARCADE games? 
If you rename the "game.zip" it simply doesn't work, it only works if you leave the name exactly as it was originally. Having this "gamelist.xml" we would have the option to customize the name of the game as we wish and the file would point to the real "game.zip".
Would that be possible too?

GREAT WORK! Thank you for this fantastic tool!

**Comment by aldostools** [comment]
Actually there is one option that shows online covers on demand, but don't download them. This could slowdown the browsing of the games.

To make the XMB scrolling faster it's recommended to install locally the covers packs:
https://github.com/aldostools/Resources/releases/tag/1.0

**Comment by aldostools** [comment]
In regards to RECALBOX if you want you could create a standalone app that download the covers from my github repository.
https://github.com/aldostools/Resources/tree/main/COV
https://github.com/aldostools/Resources/tree/main/PSX

Or if you prefer you could submit a pull request for IRISMAN. It already has the option to download the covers for the scanned games, but it's pointing to an external repository that added restrictions.

**Comment by aldostools** [comment]
The gamelist.xml is a nice idea. I could implement a `gamelist.txt` similar to [LANG_ROMS.TXT](https://github.com/aldostools/webMAN-MOD/blob/master/_Projects_/updater/update/dev_hdd0/tmp/wm_lang/LANG_ROMS.TXT) that is used to rename the emulator folders. The GAMELIST.TXT could be placed in the same folder of the ROMS.

**Comment by aldostools** [comment]
Check webMAN MOD 1.47.46e. It now supports `gamelists.txt` for ROMS

**Comment by araujoraveli** [comment]
I'm traveling, I only now had time to respond.

The gamelist.txt resource is very good, it will help immensely!
I'll test it over the weekend, great job and thanks!

About Scraps, maybe I didn't explain it correctly or the translator is trolling me hahaha
I don't know if you know, the website I mentioned in question (there are others) provides the images for download, they have their own tool that recognizes the roms in a folder on the PC and downloads the covers as you configure it and coincidentally it already comes in format and sizes that webmanmod already accepts (at least I haven't had any problems so far)...
Recalbox does exactly the same thing, but natively on their system, it scans the "roms" folder and downloads (only the roms found) the images automatically, avoiding having to create a pack of images to download.
Imagine the amount of image packs to download and have the covers and icons for each emulator or game :V hahaha Much more practical and saves disk space.

[https://www.skraper.net/](https://www.skraper.net/)

Would this option be possible in WebmanMOD? Or just creating a separate homebrew?
Sorry for the huge text and bad English, I'm using the translator.

**Comment by aldostools** [comment]
Thank you for your feedback. For cover scrapping it would be required a separated homebrew for that. IRISMAN already can do something similar but I think the site with the covers is blocking it, and it needs to be updated to download them from github.

Unfortunately I don't have the time nor the motivation to do it.

**Comment by araujoraveli** [comment]
Okay, I understand.
I've been using it for a week and everything is ok so far, it works very well.
One last suggestion/request, if possible, would you like to include a specific character or command to HIDE roms on the XMB using gamelist.txt? There are some games that need more than one file to work.
An example is the game Quake, which needs the files "pak0.pak" and "pak1.pak" to be complete, and always lists both files in the xmb. If there was a way to hide one of the files from the list in the xmb, it would be better organized.

Example in gamelist.txt:

```
pak0.pak [Quake]
pak1.pak [COMMAND/NAME OR CHARACTER TO HIDE IN XMB]
```

Greetings!

**Comment by aldostools** [comment]
Hello @araujoraveli 
You can add the file names that you want to ignore in the content scanning to `/dev_hdd0/tmp/wm_res/wm_ignore.txt`

Or edit `wm_ignore.txt` from /setup.ps3 > Scan for content. Click on the button with the Hand holding a Pencil
![image](https://github.com/aldostools/webMAN-MOD/assets/974897/c14b9e59-fac7-4482-9d93-ff3819630418)

**Comment by araujoraveli** [comment]
I did not know it! haha
Thanks for everything, and everything working perfectly 100%!
Thanks

**Comment by araujoraveli** [comment]
I did not know it! haha
Thanks for everything, and everything working perfectly 100%!
Thanks
