### ISSUE TITLE
Is custom mounting possible?

### ISSUE THREAD

**Issue by Rast1234** [aldostools/webMAN-MOD#108]
Hello. I wonder if it's possible to mount folder or file with fat32 filesystem as /dev_usb000 to eliminate the need for USB stick to export/import savegames, download files, etc.
If it's not possibe now, would it be hard to add? I can try implementing it, if it's even possible, just need hints where to start.

**Comment by Joonie86** [comment]
The closest thing you can get is 
"It can auto-mount any custom folder or ISO. Official only can mount AUTOBOOT.ISO" 

and for other features you wanted, can easily be resolved if you use FTP transfer to manually copy and downloaded files to PC or USB.
