### ISSUE TITLE
Updating Webman mod resets the VSH FPS Plugin settings back to default

### ISSUE THREAD

**Issue by Cosmic-Starlight** [aldostools/webMAN-MOD#1083]
hello, so ive been noticing this behavior for a few versions already, like for example on the xmb i only personally on the xmb only use the temp and maybe the fan speed, stuff like framerate, ram and Fahrenheit,  and what firmware version are useless to me, and on games i only use framerate, temp and fan speed fahrenheit and the rest are useless to me.

anyways thats not the point, the mild annoyance is having to manually go and edit the file every time i update webman. i would be very thankful if some sort of check could be implemented that prevents the settings from being completely re-written.

whether its updating manually trough the pkg or automatically trough its xmb subfolder the result is the same, the settings get overwritten back to defaults

i understand if this isnt high on your list of priorities

**Comment by aldostools** [comment]
Thank you for your feedback. VshFpsCounter.yaml has been removed from the update package.

**Comment by cloud-strife7777** [comment]
I use Always a Backup from .yaml file and copy Back after Update.
