### ISSUE TITLE
Feature request: Temperature Celsius/Fahrenheit setup (L3+R3 plugin)

### ISSUE THREAD

**Issue by kuba1044** [aldostools/webMAN-MOD#1085]
By default, CPU and GPU temperature values ​​appear in both Celsius and Fahrenheit, is it possible to select only Celsius?

**Comment by aldostools** [comment]
Yes, edit /dev_hdd0/tmp/wm_res/VshFpsCounter.yaml

Change `temperatureType: BOTH` to  `temperatureType: CELSIUS` for xmb: & game: sections in the yaml file.
![image](https://github.com/aldostools/webMAN-MOD/assets/974897/7fd266f3-182c-438f-a011-e523dc026da5)

**Comment by kuba1044** [comment]
Thank you. Would it be possible to add a setting for this (and others) in the webman settings?

**Comment by aldostools** [comment]
No. VshFpsCounter is a different addon. You should edit your config with a text editor.

You can use `0/edit.ps3/dev_hdd0/tmp/wm_res/VshFpsCounter.yaml` if you need to edit the file from the PS3 with webMAN MOD.
