### ISSUE TITLE
CoverFlow GUI

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#1087]
Aldo,

The CoverFlow GUI is bugged in the standard display area (default setting). I made some adjustments to make it work properly on both full pixel and standard size (the navbar was cut and scrollable with a white bar). However, sizes -1 and -2 are still bugged.

[games.zip](https://github.com/user-attachments/files/15975386/games.zip)

**Comment by aldostools** [comment]
Could you make a PR?

**Comment by LuanTeles** [comment]
> Could you make a PR?

OK, just give me a few minutes

**Comment by aldostools** [comment]
Don't rush... anyway I'm busy ATM 😄

**Comment by LuanTeles** [comment]
I'll making a PR right now


Before
![image](https://github.com/aldostools/webMAN-MOD/assets/110236244/c7467e93-2d13-48f8-b532-471f6aa0ee37)
![image](https://github.com/aldostools/webMAN-MOD/assets/110236244/b06f0814-631f-49ab-9b6d-7ffabb533305)

After ( I also moved the item index to not be overlapped when the fps counter is enabled)

![image](https://github.com/aldostools/webMAN-MOD/assets/110236244/b9102df4-7e6b-4b18-af6e-5471568da970)

**Comment by aldostools** [comment]
Your html didn't work on my PS3. Try this one
[games.zip](https://github.com/user-attachments/files/15975823/games.zip)

**Comment by LuanTeles** [comment]
I made the changes on the top of your new file, it's working here

[games test2.zip](https://github.com/user-attachments/files/15975980/games.test2.zip)

EDIT:

Your new code doesn't seem to affect anything in my end.

I tried the Display Areas and the resolution options (all of them are bugged, but i think nobody changes it)

**Comment by aldostools** [comment]
Thank you for your feedback. I tested my games.html in 480p, 720p and 1080p and it displayed properly on these resolutions.

Your latest games_test2.zip had left/right margins too big and the top/left index was moved to the right. I disaproved your changes.

**Comment by LuanTeles** [comment]
> Thank you for your feedback. I tested my games.html in 480p, 720p and 1080p and it displayed properly on these resolutions.
> 
> Your latest games_test2.zip had left/right margins too big and the top/left index was moved to the right. I disaproved your changes.

Oh, I meant the resolution options in the web browser menu. XD I moved the index to the right because of the FPS counter plugin, so it doesn't overlap the index info. (I keep it enabled on my end)

The important changes are the ones that fix the standard display area, which is the default PS3 setting. Of course, you can adjust it however you like. I just made some changes to fix it according to my preferences.

But i think fixing the layout for the standard display area is important. (you'll probably fix it in a better way than me)

**Comment by LuanTeles** [comment]
Ah, about the margins, it was the only way I could fix the display issues in the standard display area. It looks okay in that setting, but in full pixel, the margins are noticeably bigger.

I couldn't think in any other way to achieve this, sorry :'(

**Comment by aldostools** [comment]
Who play PS3 on SD these days? SD is obsolete. Don't be cheap 😝
