### ISSUE TITLE
FTP:Can't download from Ps3 to PC

### ISSUE THREAD

**Issue by marvolo666** [aldostools/webMAN-MOD#109]
It reportted  an error when using webMAN-MOD FTP on downloaing file from PS3 to PC.

While upload from PC to PS3,it works normal.

Forbiden FTP on webMAN setup,and use mutiMAN FTP.It works normal both upload and download.

**Comment by Joonie86** [comment]
Closing old issues that have no further feedback. Please try the latest wMM and report back.
