### ISSUE TITLE
Remaps

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#1090]
Aldo, seems like all my remaps are being unmapped by multiMAN, but i'm using protected remaps

	/remap.ps3/dev_hdd0/xmlhost/game_plugin/games.xml&to=/./dev_hdd0/xmlhost/game_plugin/mygames.xml
	/remap.ps3/dev_hdd0/xmlhost/game_plugin/retro.xml&to=/./dev_hdd0/xmlhost/game_plugin/ROMS.xml
	
do you have any clue?

Edit
That's strange i am able to delete mapped files

**Comment by aldostools** [comment]
Are you using HEN, Cobra or Mamba?

I think the mappath.c modified by bguerville in latest HEN removed all the features that I added including the protected mappings.

**Comment by LuanTeles** [comment]
I'm on CFW Cobra, but i just tested on HEN and same thing is happening, protected paths by webMAN is being unmapped and i'm also able to delete the mapped files.

The ones i added in the HEN payload are working fine,

**Comment by aldostools** [comment]
I have tested the map path using protected new paths and they are working properly on Evilnat 4.91.2 Cobra 8.5 BETA 9. multiMAN is not deleting the mappings starting with the prefix /./

Probably you're experiencing a layer 8 error. It's normally found in front of the TV and behind the gamepad.

Take in count that if you're testing the mappings with Chrome, the URLs containing traversal paths like /.. or /./ are removed before sent the request to the server.

![image](https://github.com/aldostools/webMAN-MOD/assets/974897/271f4bb1-9421-4776-a5a6-698696a949f6)

`/remap.ps3/dev_hdd0/xmlhost/game_plugin/retro.xml&to=/./dev_hdd0/xmlhost/game_plugin/ROMS.xml`
Is converted by Chrome to:
`/remap.ps3/dev_hdd0/xmlhost/game_plugin/retro.xml&to=/dev_hdd0/xmlhost/game_plugin/ROMS.xml`

To bypass this conversion you have to use a escape sequence for the first / instead of ascii characters:
`/remap.ps3/dev_hdd0/xmlhost/game_plugin/retro.xml&to=%2F./dev_hdd0/xmlhost/game_plugin/ROMS.xml`

![image](https://github.com/aldostools/webMAN-MOD/assets/974897/92e5b3ef-cf9b-4a44-851a-40b8e4177b61)


Another alternative is mapping paths with syscall 35.

**Comment by LuanTeles** [comment]
> 
> Probably you're experiencing a layer 8 error. It's normally found in front of the TV and behind the gamepad.
> 

😄😄😄


> Take in count that if you're testing the mappings with Chrome, the URLs containing traversal paths like /.. or /./ are removed before sent the request to the server.
> 
> ![image](https://private-user-images.githubusercontent.com/974897/344483386-271f4bb1-9421-4776-a5a6-698696a949f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3NjkyMzMsIm5iZiI6MTcxOTc2ODkzMywicGF0aCI6Ii85NzQ4OTcvMzQ0NDgzMzg2LTI3MWY0YmIxLTk0MjEtNDc3Ni1hNWE2LTY5ODY5NmE5NDlmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQxNzM1MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDU4MzA4Y2NlYzcxNTRmMTgwNWU2MDc3YTdjZDBkZmFmYjczYWY4NzkzMWYwMWUxM2FkYWZmNjE5ODE1YTdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.apvYPUss2ERIjhNXVmCNvjX8LnrPBEm21ckt1bvpT8k)
> 
> `/remap.ps3/dev_hdd0/xmlhost/game_plugin/retro.xml&to=/./dev_hdd0/xmlhost/game_plugin/ROMS.xml` Is converted by Chrome to: `/remap.ps3/dev_hdd0/xmlhost/game_plugin/retro.xml&to=/dev_hdd0/xmlhost/game_plugin/ROMS.xml`
> 
> To bypass this conversion you have to use a escape sequence for the first / instead of ascii characters: `/remap.ps3/dev_hdd0/xmlhost/game_plugin/retro.xml&to=%2F./dev_hdd0/xmlhost/game_plugin/ROMS.xml`
> 
> Another alternative is mapping paths with syscall 35.

You are right, i'm using microsoft edge (chromium based) and indeed it's removing the /. Thanks

![image](https://github.com/aldostools/webMAN-MOD/assets/110236244/47baf1d0-18ba-4729-b4e0-b620f68a9e0e)

**Comment by aldostools** [comment]
I don't have your same setup, but I did a simple test remapping /dev_hdd0/PKG to /dev_hdd0/tmp from boot_init.txt and it also worked fine. The mapping was not removed by multiMAN or calling /remap.ps3

`/remap.ps3/dev_hdd0/PKG&to=/./dev_hdd0/tmp`

**Comment by LuanTeles** [comment]
> I don't have your same setup, but I did a simplete test remapping /dev_hdd0/PKG to /dev_hdd0/tmp from boot_init.txt and it also worked fine. The mapping was not removed by multiMAN or calling /remap.ps3
> 
> `/remap.ps3/dev_hdd0/PKG&to=/./dev_hdd0/tmp`

The problem was indeed my web browser. Sorry for wasting your time. I remember you mentioned Chrome once, but I was using Edge and didn't realize it has the same behavior. Now that you mentioned it again, I remembered that Edge is also based on Chromium.

I feel embarrassed. I already fixed it here , thanks again hehe

**Comment by aldostools** [comment]
Probably you're the unique person in the world that use that crap from Micro$uck 😆 

Everyone use Chrome. That's why I didn't mention Edge

**Comment by LuanTeles** [comment]
> Probably you're the unique person in the world that use that crap from Micro$uck 😆
> 
> Everyone use Chrome. That's why I didn't mention Edge

You can judge me, I was a loyal Chrome user for the past 10 years or more, but IMO, the Chromium-based Edge browser is much better than Google Chrome. I don't even miss anything from Chrome, Edge is top tier.

But this only applies to the Edge introduced in Windows 11. Before that, it was really bad.

I think you should give it a shot :P

You'll also be surprised that on mobile, I use the Samsung web browser hahaha. It's a shame the Windows version has been removed from the MS Store for some reason but this one was a beast :P
