### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#1091]
Aldo, this thread caught my attention: [Getting the current user](https://www.psx-place.com/threads/getting-the-current-user.1419/#post-8900). It's exactly what I've been needing for some time. Can a wait command for the logged user and an if-logged condition be added?

I'm currently using this to execute commands only when the user is logged into the system:

:xmb_check
if exist /dev_hdd0/home/$USERID$/localusername
	wait 5
	goto settings
else
	wait 5
	/pad.ps3?accept
	/pad.ps3?accept
	wait 5
	goto settings
end if

It works, but most of the time the pad command is executed when the user is logged in. I use this because some commands, such as installing a theme, will make the system hang if no user is logged in.

**Comment by aldostools** [comment]
Try this [webftp_server_test_wait_user_&_if_logout_&_if_login.zip](https://github.com/user-attachments/files/16074851/webftp_server_test_wait_user_._if_logout_._if_login.zip)

Syntax of new commands:
`wait user`
`if login`
`if logout`

**Comment by aldostools** [comment]
In this new build I have added support for multiple script commands in a single line. Use the semicolon ; as command separator.
[webftp_server_test2.zip](https://github.com/user-attachments/files/16075719/webftp_server_test2.zip)

Example:
```
if login; popup User is logged in; end
if logout; popup User is logged out; beep5; end
```

**Comment by LuanTeles** [comment]
Thank you Aldo, it's perfectly working, both commands and the multiple commands in a single line too
