### ISSUE TITLE
Mounting PSXISO with ps3netsvr is broken

### ISSUE THREAD

**Issue by ImmortalJ** [aldostools/webMAN-MOD#11]
Hello Aldo,

Just wanted to let you know of this issue I ran into.

When I try to mount a PSX bin/cue in the web interface, it shows Error, and it shows that it was trying to mount a .iso extension in the filename instead of the bin.

Thanks for everything!
ImmortalJ

**Comment by aldostools** [comment]
The issue should be fixed in the latest build. If the problem persists, please reopen the issue.
