### ISSUE TITLE
Issue with PS3 game background/sound in XMB after mounting game ISO

### ISSUE THREAD

**Issue by goomba000** [aldostools/webMAN-MOD#110]
I have a minor problem with displaying a PS3 game's media on the XMB.  Here's what happens:

- If the PS3 has just been started, the problem doesn't occur:  When either a PS3 game installed from PSN or a game disc is highlighted in the XMB, the fullscreen background image will be displayed and sound played (if present for that game) after a second or two.
- After mounting an ISO with Webman-MOD (PS1/2/3), the function above stops working.  Only the game icon is displayed when the game entry is highlighted in the XMB
- However, upon exiting a game (PS1/2/3) back to the XMB, it works again.  A PS3 game ISO (mounted with webman prior to playing the game) or PSN PS3 games will show their background and play sound again without issue.

Update: In addition to playing a game and exiting, doing triangle -> Check for update in the XMB also solves the problem.

Software:
Rebug 4.81.2
Webman-MOD 1.47.05

**Comment by aldostools** [comment]
Thank you for your feedback.

It must be a lack of free memory in XMB when the system starts.

My suggestions are:
1- Disable the scanning of content every time the system starts.
2- Try to use only 1 or 2 plugins (wMM + PSNpatch or wMM only) in /boot_plugins.txt
(in Rebug, wMM usually loads from dev_flash and may not be listed in /boot_plugins.txt)
3- If the problem persists, check if the issue also occurs with sMAN.

**Comment by goomba000** [comment]
Hi Aldo, sorry for the late reply.

So I disabled content scanning and disabled all plugins (I only had webftp_server.sprx and PSNPatch so I disabled that last one).  I don't use the Rebug wMM. Unfortunately the problem persists.

About sMAN, should I uninstall wMM before enabling it?  If so, could you give me the correct procedure? Thanks!

**Comment by AndreaHH90** [comment]
Hello!
Same here. Doing triangle/Check for updates in the XMB fixes temporarily this issue, but it is enough to change the game or restart the PS3 to get the issue back.

CFW FERROX 4.82 v1.00 COBRA 7.53
webMAN MOD 1.47.06

**Comment by marius3d** [comment]
Hello, i have exactly the same issue. Also running Rebug CFW 4.82 Lite and webMAN MOD 1.47.06

**Comment by aldostools** [comment]
I think I finally found the cause of this issue... Apparently the missing PIC1.PNG/ICON0.PAM is a side effect when "eula_cddb_plugin" is used as wm_proxy to mount games from XMB,

So in the following PKG uses "idle_plugin" as wm_proxy (which doesn't seem to cause the issue).
https://www.sendspace.com/file/e0k4ub

The idle_plugin was changed to eula_cdb_plugin in the first commit of february 26, 2017, due at that time I was experiencing some freezes mounting ntfs games and "eula_cdb_plugin" looked as a solution. Many changes/improvements were made later. So I think idle_plugin could be used again (if it pass the testing).

Your feedback would be appreciated...

**Comment by RandQalan** [comment]
@aldostools Working now for me and found no other problems so far
If anything most things are running better.

**Comment by aldostools** [comment]
@RandQalan Thank you for your feedback. If no issue is reported, I'll release the test version as 1.47.07

**Comment by VetaLioSTV** [comment]
@aldostools hi again. Thanks for your **WebMan Mod** , i have the same behaviour.
E.g. : at start all stuff from webman works(like check cpu/gpu temperature with SELECT+START), but if you're mounting ISO and trying to do the same stuff in game(go to XMB with PS button and use SELECT+START), webman mod features will not work.

As i remember,all was fine before i had installed CFW with cobra stuff,so i'm getting impression that when you're using WMM with Cobra stuff,it will override hotkeys(?) after mounting game or what?

Any advices,thanks!

**Comment by Joonie86** [comment]
Closing old issues that have no further feedback. Please try the latest wMM and report back.
