### ISSUE TITLE
mobile.html formatting issues. (misaligned icons, which can be easily fixed)

### ISSUE THREAD

**Issue by korn3r** [aldostools/webMAN-MOD#1102]
Hi.
Screenshot
https://imgur.com/vRkt111

Left screnshot: stock one (notice how some elements are slightly off to the right compared to other ones)
Middle screenshot (dont mind translation, i was lazy to edit original file to make screenshot also english, its about icons anyway): i added "\&nbsp;" to all elements that are not "off to the right" and now everything is aligned (except thermometer icon near "CPU & RSX"
Right one: i also edited style for "CPU & RSX" entry, adding left padding. "...style="position:relative;top:6px;left:3px"> "(notice **;left:3px**)

Not very hard to fix, just wanted you to know there is an issue. Sorry for bothering in case you dont care much about that UI :)

PS: There are also items that require adding "\&nbsp;" at the bottom of menu, not only ones on screenshot. Just in case...

**Comment by aldostools** [comment]
If you submit a pull request or upload the modified files to a zip in this thread it would be easier for me to update for the next release.

**Comment by korn3r** [comment]
[mobile.zip](https://github.com/user-attachments/files/16432187/mobile.zip)

**Comment by aldostools** [comment]
Perfect. Thank you. I will upload it to the repo and update it in the release packages.
