### ISSUE TITLE
Won't uninstall and other weird sideeffects.

### ISSUE THREAD

**Issue by Kanononon** [aldostools/webMAN-MOD#1103]
I installed webMAN-MOD full edition, then deleted it and installed webMAN-MOD lite to try it out. I read that you can switch between the two editions by pressing L1+R1+triangle. I tried it and a note popped up saying something like "unloaded webMAN". I am very sure that I pressed L1+R1+triangle and not the combination for unloading webMAN. Since then none of the button combinations, that I tried worked and both uninstalling methods (via options and via browser) didn't work. A note popped up saying "delete.ps3: OK" and nothing happend. When selecting the unload webMAN-MOD option a note pops up saying "webMAN not ready". Mounting games and changing fan speed still works. I am using HEN on a Super Slim.

**Comment by korn3r** [comment]
Try installing webman mod via pkg without uninstalling previous version, then try to uninstall again.

Also it might be dumb question, but did you reboot console before trying to uninstall webman after unload happened?

**Comment by aldostools** [comment]
The combo L1+R1+△ is intended to work with the full edition installed.
It lets you switch back and forward between Full and Lite editions. 
The message "Unloaded webMAN" is normal, since the switch is done unloading one plugin and loading the other.
A second message should appear a few seconds later when the other plugin is loaded.

The Lite edition should be installed ONLY if you're going to play games from local storage and won't use any other feature.

Use the online updater and use that version. Then use L1+R1+△ if you want to switch to Lite edition to play games with big demand of memory.

**Comment by Kanononon** [comment]
> Try installing webman mod via pkg without uninstalling previous version, then try to uninstall again.
> 
> Also it might be dumb question, but did you reboot console before trying to uninstall webman after unload happened?

Which version should I install now? And yes I did reboot the console after the unload happend and then I tried uninstalling it.

**Comment by korn3r** [comment]
> 
> Which version should I install now? And yes I did reboot the console after the unload happend and then I tried uninstalling it.

I suppose you can just install full version to completely rewrite everything and uninstall it later, but i suspect there is no difference when it comes to "uninstalling".

i would do like that: install full -> uninstall -> reboot -> install what i want. i use lite edition, but as mentioned actual maintainer of this app above, use lite only if you dont need features that are present in full.

**Comment by Kanononon** [comment]
> > Which version should I install now? And yes I did reboot the console after the unload happend and then I tried uninstalling it.
> 
> I suppose you can just install full version to completely rewrite everything and uninstall it later, but i suspect there is no difference when it comes to "uninstalling".
> 
> i would do like that: install full -> uninstall -> reboot -> install what i want. i use lite edition, but as mentioned actual maintainer of this app above, use lite only if you dont need features that are present in full.

I installed the full version and everything seems to work for now. Thank you. I have one question though. Is there visible difference between the lite version and the full version? Because when I installed the lite version it still showed all options in the xmb and I still was able to change fan speed mode, which shouldn't have been possible according to a forum post from a couple of years ago.

**Comment by korn3r** [comment]
@Kanononon 
you can set fan speed in lite too.
main differences are that you cant have disks mounted from network, you dont have localized (non-english) interface on lite (unless you recompile from sources by yourself, tehehehe), video recording (which i suspect records in awful quality anyway) and screenshot functions with hotkeys.

If you want to check which one you installed, got to webman mod settings and at the bottom it should have information on version type. Lite says "webMAN - Simple Web Server [Lite]"

you can look for main differences yourself here:
https://github.com/aldostools/webMAN-MOD/blob/master/flags/flags_full.h
https://github.com/aldostools/webMAN-MOD/blob/master/flags/flags_lite.h

**Comment by Kanononon** [comment]
@korn3r Ah okay, thank you a lot for the help.
