### ISSUE TITLE
Have an option to toggle between different DNS profiles for many PS3 private servers

### ISSUE THREAD

**Issue by IAmNadaman** [aldostools/webMAN-MOD#1105]
LuanTeles' [PS3 4K Pro](https://ps3-4k-pro.github.io/home/) has this feature, but I would personally appreciate if something like this was integrated in webMAN MOD, as 4K Pro has many features I don't need.

**Comment by aldostools** [comment]
Please request @LuanTeles an standalone version of this feature. I don't use PS3 4K Pro. I know he's using webMAN MOD as platform to implement some features, but I don't have idea of what exactly he did.

**Comment by IAmNadaman** [comment]
> Please request @LuanTeles an standalone version of this feature. I don't use PS3 4K Pro. I know he's using webMAN MOD as platform to implement some features, but I don't have idea of what exactly he did.

Alright, that's fair. I will see what I can do to contact him. Closing.
