### ISSUE TITLE
[A feature request for EvilNat] Restore Factory EEPROM

### ISSUE THREAD

**Issue by therevtanker2100** [aldostools/webMAN-MOD#1109]
Req /dev_hdd0/tmp/ <---- where your eeprom backups should be
Backup eeprom before QA Flagging to prevent loss of unique token

**Comment by aldostools** [comment]
Wrong place. You should request to @Evilnat in [github.com/Evilnat](https://github.com/Evilnat) or [x.com/xxEvilnatxx](https://x.com/xxEvilnatxx)

**Comment by therevtanker2100** [comment]
Ok

**Comment by therevtanker2100** [comment]
Done
