### ISSUE TITLE
No SND0.AT3 is requiered by some games

### ISSUE THREAD

**Issue by 444nonymous** [aldostools/webMAN-MOD#111]
Could it be possible to link "SND0.AT3" again to the right path after the game is launched? I found a few games that require to copy SND0.AT3 during install and hang if SND0.AT3  is not found.

This way the sound can be still muted when the game is mounted while not interfering with games that need to use the file when it's launched.

Thanks.

**Comment by aldostools** [comment]
Thank you for the feedback... I'll do it in the weekend.

**Comment by 444nonymous** [comment]
It was just a few games, noting important. I thought you stopped updating webman.

What plug-in does webman lite currently use as a proxy to launch games and where is it stored? I remember I was able to launch games in 1.46 directly without using the web browser, just replacing the webftp_server.sprx file that came with Rebug. If I just do that in the current version it uses the web browser again.

I know I just can install the whole packet, but I like to know so I can update single files from updated commits for testing reasons.

Thanks.

**Comment by aldostools** [comment]
Yes I stopped working on ps3 stuff... but this week I had some free time :)

About the issue with SND0, please test if this build re-enables SND0 in-game is running.
http://aldostools.org/temp/test/webftp_server_full.sprx

webMAN MOD uses eula_cddb_plugin.sprx as proxy to launch games,  and sMAN uses idle_plugin.sprx

**Comment by 444nonymous** [comment]
So what webMAN installs to use eula_cddb_plugin.sprx and  idle_plugin.sprx is "wm_proxy.sprx", right? 

What is the right path for "wm_proxy.sprx"? /dev_rebug/vsh/module or  /dev_hdd0/tmp/?

Thanks.

**Comment by aldostools** [comment]
webMAN MOD maps */dev_flash/vsh/module/eula_cddb_plugin.sprx* to **/dev_hdd0/tmp/wm_res/wm_proxy.sprx**

sMAN maps */dev_flash/vsh/module/idle_plugin.sprx* to **/dev_hdd0/tmp/res/sman.xmb**

**Comment by 444nonymous** [comment]
I think the SND0.AT3 fix works. I'm not 100% sure because it's just a few games that install that file and I don't remember them all.

**Comment by aldostools** [comment]
Well if you receive the error again just let me know... 😄

**Comment by 444nonymous** [comment]
By the way, if I do a full update from pkg, I loose the Eject Disc button that Rebug shows by default. I solve it by deleting the /game/XMBMANPLS folder, so it must be webMAN.xml not mapping it.

**Comment by aldostools** [comment]
The Eject Disc option is removed by webMAN MOD intentionally when webMAN.xml is detected.
The reason is that the option is already found inside the webMAN.xml sub-menu. Leaving it is redundant.

Also there are other ways to call that function: SELECT+O or using VSH Menu or sLaunch.
