### ISSUE TITLE
[FEATURE REQUEST] Auto-apply artemis code

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#1112]
Is there a way to force webMAN to apply an Artemis cheat without showing the notification and having to press start, etc.? I’m thinking about this because I plan to apply the 60 fps patches (if available) automatically without any user interaction.

**Comment by aldostools** [comment]
@LuanTeles I forgot to comment that I updated webMAN MOD to let apply Artemis cheats without user interaction.

You must copy the cheats to be applied in `/dev_hdd0/tmp/arts.txt` then execute `/artemis.ps3?attach`

Update online or re-download the full installer. If you have issue with the new build, let me know.

**Comment by LuanTeles** [comment]
Thank you, Aldo. What is the easiest way I can use it?
I'm thinking of adding in-game scripts that create the arts.txt with the 60FPS code and then execute the /artemis.ps3?attach command.

**Comment by aldostools** [comment]
One setup could be to have the per game batch script in `/dev_hdd0/tmp/wm_ingame` (one bat script per title id)

Put all the codelists in a folder. Use the web command `/artemis.ps3<ncl-file>` from the batch file to copy the ncl file corresponding to the game loaded to `/dev_hdd0/tmp/art.txt` and enable the artemis process.

You can wait a few seconds, then use `/artemis.ps3?attach` to apply the cheats to the game process automatically.
