### ISSUE TITLE
On-the-fly decryption from Ext. HDD Not working (Error 80010017)

### ISSUE THREAD

**Issue by voidnet-stack** [aldostools/webMAN-MOD#1121]
Environment:
webMAN MOD 1.47.46h
PS3 Slim 4.91.2 EVILNAT (Cobra 8.5) BETA10.
2TB External HDD. MBR Partition table. exFAT filesystem.

Observed behaviour:
ISO transferred to the external HDD PS3ISO folder along with corresponding key / dkey files. Run PrepISO and launch game with error 80010017.
Performing the same steps but transferring the data to the internal hdd does not produce this error.

Expected behaviour:
Transfer ISO to external HDD PS3ISO folder along with corresponding key / dkey. Run PrepISO and launch game without error.

**Comment by aldostools** [comment]
After check the new code implemented by @Evilnat in Cobra 8.5, I found that it isn't handling .ntfs[PS3ISO] without the .iso extension. I built the following version of prepISO that should work. Also contected Evilnat to fix the issue in Cobra.

[prepISO_1.33b.zip](https://github.com/user-attachments/files/16982909/prepISO_1.33b.zip)

Please make sure that you're doing the following:
1- Using the prepISO 1.33b linked aboved
2- The file name of the ISO and the key/dkey must have the same file name (different file extension)

After scan the games with prepISO, you can confirm if the key/dkey was copied along with the corresponding .ntfs[PS3ISO] to /dev_hdd0/tmp/wmtmp

**Comment by aldostools** [comment]
@Evilnat has fixed the issue in Cobra. You can test the fixed version installing [this PKG](https://github.com/aldostools/Resources/releases/download/MODS/4.91.2_Evilnat_PEX_BETA9_to_BETA10_req_dev_blind_enabled.pkg) (dev_blind must be enabled)

This version of Cobra should work with prepISO 1.33a

**Comment by voidnet-stack** [comment]
Tested and confirmed working for me.
Thank-you both for your amazing work!
