### ISSUE TITLE
[Feature Request] Web browser type

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#1126]
Also, is there any way to choose which web browser the /browser.ps3 web command will open? It uses WebKit (webrender_plugin.sprx) by default, but I need to open some URLs via Silk (webbrowser_plugin.sprx). Is there a way to select the web browser variant?

I'm needing to test a bunch of flash games and it only opens via Silk, it also streams movies unlike webkit.

**Comment by aldostools** [comment]
The web command `/browser.ps3` just calls this API: `vshmain_AE35CF2D`. The rest is done internally by GameOS. 

You can specify the module in the XML and use explore_plugin commands to open the correspoding browser. Or maybe select the browser through the xregistry, although I think you need to restart or logout.

You could try redirecting `webrender.sprx` to `webbrowser.sprx` to open URLs using Silk browser, but I haven't tested this if this hack works or not.

**Comment by LuanTeles** [comment]
Thank you, Aldo, but unfortunately, the system freezes if I remap webrender_plugin.sprx to webbrowser_plugin.sprx. Also, changing the browser via registry/debug settings doesn't make a difference; even when set to Silk, it still opens WebKit.

BTW I asked ChatGPT to create the XMBML for me. I only sent the file names (~500) and examples, and so far, the output it's giving me seems correct, so that's the way i'll have to test the swf files.
