### ISSUE TITLE
Saving button not working

### ISSUE THREAD

**Issue by SciLor** [aldostools/webMAN-MOD#1129]
With webman mod 1.47.46 and 1.47.47 I am unable to save my settings via ps3 or my phone. Pressing the "speichern" button at the button does nothing.

I tried to reset the settings with
/setup.ps3?

**Comment by aldostools** [comment]
Thank you for your feedback SciLor. That is due a bug in the latest build that caused that the button be hidden in the `Wait for USB` section. I will fix it in the next build. I'm currently testing the new build before release it.

**Comment by aldostools** [comment]
Meanwhile use 1.47.46h

**Comment by aldostools** [comment]
The build 1.47.47b fixed the issue with the save button. Thanks again for the bug report.
