### ISSUE TITLE
L1 & L2 to page up & down?

### ISSUE THREAD

**Issue by 444nonymous** [aldostools/webMAN-MOD#113]
I've tried the new slaunch and it does not really work for me, missing game pictures, when that webman and irisman always show them.

Irisman uses L1 & L2 buttons to jump from page to page making easier to navigate long lists. Could it be posible to do that with webman in the XMB list (webman -> ps3 -> list of games). So L1 scrolls down a page and L2 up.

Thanks!

**Comment by aldostools** [comment]
Maybe your covers are in a location or format not supported by sLaunch. webMAN and IRISMAN support many variations. I could have missed some of them.

Regarding the page up & down using L1 & L2 on XMB, I already tried to implement that feature months ago, but there was too much lag reading the buttons, making it faster scrolling in the regular way than using these buttons. There were also other issues, so I dropped the idea.

**Comment by Joonie86** [comment]
Closing old issues that have no further feedback. Please try the latest wMM and report back.
