### ISSUE TITLE
[Request] Lite version built with the flag AUTO_TOGGLE_ON_XMB

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#1130]
Aldo, can you please provide me the latest webMAN lite version built with the flag AUTO_TOGGLE_ON_XMB?

**Comment by aldostools** [comment]
[webftp_server_lite_1.47.47e_AUTO_TOGGLE_ON_XMB.zip](https://github.com/user-attachments/files/17405479/webftp_server_lite_1.47.47e_AUTO_TOGGLE_ON_XMB.zip)

**Comment by LuanTeles** [comment]
Thank you
