### ISSUE TITLE
1.47.47g Issue Tracker

### ISSUE THREAD

**Issue by drewdrew21b** [aldostools/webMAN-MOD#1132]
I am seeing the following issues when testing the new WebMAN MOD 1.47.47g:

**References**: 

- https://github.com/aldostools/webMAN-MOD/tree/master/_Projects_/updater/update/dev_hdd0/plugins <- Not working when updating manually.
- https://t.co/VJVNMqzU03 <- Working
- https://x.com/aldostools/status/1850641325713998224

PS3 Details:
 - Latest EvilNat 4.91.2 CFW
 - Cobra 8.5D (Debug Enabled)
 - IDPS: Original
 - TargetID: CEX
 - VSH: DEX
 - XMB Host: CEX
 - Debug Settings: DEX
 - Model: CECH-A
 - HDD: Modified with 1TB HDD
 - WebMAN MOD: 1.47.47g

Issues:

1. After scanning all my backups on PS3NetServ (several thousand) and locally (117 PS1, PS2, and PS3), Webman Games menu loads blank
   - ![screenshot_2024_10_28_22_18_24](https://github.com/user-attachments/assets/cbf493ff-2e53-4926-8520-47395c866a8b)
   A. Socat is displaying the following when accessing this screen over and over. Screen never loads: 
         - open_path /dev/hdd0/tmp/wm_request
         - Smoke03 : Reseted
         - LV1 Poke 0x800000000800a334 386000017be40620
   B. Hard Reset, Soft Reset not resolving issue.
   C. Clearing /dev_hdd0/tmp/wm_config.bin, restarting, and updating scan settings remotely via http://<IP>/setup.ps3 resolves this issue until scan is run again.
~~2. WebMAN Mod Portal > CPU / RSX Page > NAND Firmware Toggle > Clicking on text causes error in Dev Tools:
   A. Arrow also does not recollapse the text that is shown after clicking on it.
   B. Issues are present on both PS3 and external Browser (MS Edge)
   C. ![image](https://github.com/user-attachments/assets/483a891a-068b-46c8-9e81-0150f8e6d913)~~ <-- This is expected behavior, the output is just from my plugins.

**Comment by drewdrew21b** [comment]
Other Tests without issues:
 - Web Portal: (Developer Tools Opened remotely to scan for errors)
     - http://0/setup.ps3 & http://\<localIP\>/ - 
     - Setup: Scanning content, Fan Control, PS3NetServ settings
     - Coverflow working
     - Files working
     - PS3Mapi Working (Pretty neat stuff in here)
     - Refresh, Eject, Insert, Restart, Shutdown Working
     - Searching
 - Built-in FTP Service - Working
 - dev_bdvd for netserv PKGs working
 - PS2 Discs - Working - Limited Testing (Guitar Hero 3)
 - PS2 ISOs (Internal Drive) - Working - Limited Testing (FFX)
 - PS2 ISOs (OPL via PS2 ISO) - Working - Limited Testing (Kingdom Hearts)
 - PS1 ISO's (Internal Drive) - Working - Limited Testing (Crash Team Racing)
 - PS1 ISO's (PS3NetSrv) - Working - Limited Testing (Crash Team Racing)
 - PS3 ISO's - Working - Limited Testing (Skate 2)
 - PS3 GAME Folders (Internal Drive) - Working - Limited Testing (Little Big Planet)
 - PS3 Game Folders (PS3NetSrv) - Working - Limited Testing (Little Big Planet)
 - Features:
     - Randomized Theme installer - Working - Several themes
     - VSH working (Select)
     - Point in time info showing (Select + Start)
     - sLaunch Menu loading games

**Comment by drewdrew21b** [comment]
socat was not working originally when trying to update the plugins manually as originally asked on Twitter. Talking to other folks offline on discord, it seems the socat feature needs WebMAN Mod running in order to enable feature properly outside of other tools.

Unable to debug to see why plugins weren't working when installing them manually, however, I did verify all the paths in boot_plugins.txt and I didn't see any typo's or reasons why it wouldn't load.
[boot_plugins.txt](https://github.com/user-attachments/files/17551640/boot_plugins.txt)


Provided PKG installer worked without any issues.

**Comment by aldostools** [comment]
@drewdrew21b Thank you for your feedback. I will investigate the issue with ps3netsrv.

In regards to the manual installation, it could be some mistake in the procedure that you used. The sprx in the pkg that I provided is the same found the in the folder linked in X.

**Comment by drewdrew21b** [comment]
Can I provide any other logs or xml files from either service?

**Comment by aldostools** [comment]
For the moment I only need to identify if any module is not working correctly.
If I need more detailed information I will ask for it. Thank you very much for your feedback.

**Comment by drewdrew21b** [comment]
Looks like when I have it load scan for PSP games is where the issue lies. After generating the mygames.xml, it contains "<>910 PSP™ format games</>"

Is there any special characters that I should be on the lookout for that would break this? Maybe one of these has an odd title, or is 910 items breaking the system from displaying properly?

**Comment by aldostools** [comment]
I have been checking the issue with PS3Netsrv and 1.47.47g scanned my games fine.
It's possible that the issue could be caused by an excess of games or file names larger than the expected average.

For debugging it would help if you can upload a zip with `mygames.xml` found in /dev_hdd0/xmlhost/game_plugin
This file contains the XML used to display the game list on XMB.

**Comment by drewdrew21b** [comment]
Here are 2 files, one working, one broken with PSP games. Remove .txt extension.

[bad-mygames.xml.txt](https://github.com/user-attachments/files/17594360/bad-mygames.xml.txt)
[working-mygames.xml.txt](https://github.com/user-attachments/files/17594361/working-mygames.xml.txt)


Thank you for looking at this!

**Comment by aldostools** [comment]
Dear @drewdrew21b 
Thank you for your files. I confirmed that the issue was caused by an item added out of memory boundary.
In your case was that too many PSP games exceeded the amount of memory allocated to add the scanned PSP games.
The last entry overwrote the first PS2 xml entry, breaking completely the XML.

Please try using this new beta to verify if the issue was corrected.
https://ps3.aldostools.org/webMAN_MOD_1.47.47g_beta_20241031.pkg

Other possible solution -if the new beta doesn't fix the bug- is changing the memory profile to allow more PSP games and set [MC] to 4-bg in /setup.

**Comment by drewdrew21b** [comment]
@aldostools ,

Thank you for taking the time to review this issue!

> Other possible solution -if the new beta doesn't fix the bug- is changing the memory profile to allow more PSP games and set [MC] to 4-bg in /setup.

I checked, this is already enabled. The xml that was output now is different than before but still breaking the WebMAN Games option on my PS3. Here is the latest. If you prettify the xml, it shows some interesting characters on line 847:
_**Note**: Gamelist loads fine from MS Edge via /sman.ps3? endpoint_ 

- </V>/0/query?cond=AGL+Game:Game.titleId PSPC66820 PSPM66820"/>
- ![image](https://github.com/user-attachments/assets/a40868a3-8d04-4407-af2e-00bbfe524548)

XML: (_remove .txt extension_)
- [bad2-mygames.xml.txt](https://github.com/user-attachments/files/17601086/bad2-mygames.xml.txt)


If the answer is you can't have over # of games that this scans or it breaks things then that's probably fine, I just don't know what that exact threshold would be.

**Comment by aldostools** [comment]
The issue is still the same: the PSP code is exceeding the memory boundary and it's overwriting the PS2 section.

I'll try to fix it with another build. Thank you for your help and patience.

**Comment by aldostools** [comment]
I haven't had the time to test this build myself, but if you can, please try this build.
http://ps3.aldostools.org/webMAN_MOD_1.47.47g_beta_20241101.pkg

It should fix the remaining out of boundary.

**Comment by drewdrew21b** [comment]
Looks like that did it!
![screenshot_2024_11_01_17_52_27](https://github.com/user-attachments/assets/4d7acbb6-05d5-4b25-92b3-5fbf541301d2)

I tested a few games with it as well, all the games that were on the [compatibility list](https://www.psdevwiki.com/ps3/PSP_Emulator_Compatibility_List) that I tested were working through PS3NetSrv

**Comment by aldostools** [comment]
Excellent. Thank you for you help finding the bug & testing the bug fixes.

**Comment by drewdrew21b** [comment]
Resolved on public release: 1.47.47g
