### ISSUE TITLE
[Feature Request] PS2 WideScreen Patch

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#1137]
Hey Aldo :)

Could you add a toggle in setup.ps3 to enable or disable the widescreen patch for PS2 games, similar to what ManaGunZ does? I believe most users (myself included) are unaware of this ManaGunZ's option, so having it accessible via webMAN would be great, and ideally enabled by default.

I also hope Kozarov could add this feature to the PS2 emulator as well.

**Comment by aldostools** [comment]
The ps2 emulators with or without the widescreen patches require to be installed in /dev_flash/ps2emu

In webMAN MOD Setup > Update webMAN MOD > Custom Firmware MOD menu there are several PKGs that can be downloaded and installed in /dev_blind. The menu also have the option to enable /dev_blind which is required to install the emulators. Among these PKGs there are the default ps1 & ps2 emulators without the widescreen patches and sub-folders with different patched emulators for ps1 & ps2 (netemu, gxemu & ps2emu).

**Comment by LuanTeles** [comment]
Currently, there is no PS2 emulator patched with widescreen patches. I was thinking of something similar to what ManaGunZ does.

See here: [PS1 and PS2 Emulator Mods](https://www.psx-place.com/threads/release-ps1-and-ps2-emulator-mods.45083/page-3#post-401895).

If you enable the '16:9' option for PS2 games in ManaGunZ, you can mount PS2 games via webMAN, and it will have a widescreen patch applied.

But the ideal approach is to have the patch in the PS2 emulator itself. I hope kozarovv implements it.
