### ISSUE TITLE
Broken links in readme

### ISSUE THREAD

**Issue by oneohthree** [aldostools/webMAN-MOD#114]
These links in readme are broken:

https://github.com/NzV/PRX_Loader
https://github.com/NzV/MAMBA_PRX_Loader

**Comment by aldostools** [comment]
It seems that NvZ removed his repository.

The binaries for PRX Loader and MAMBA PRX Loader still can be found at:
http://store.brewology.com/ahomebrew.php?brewid=243
http://store.brewology.com/ahomebrew.php?brewid=287
