### ISSUE TITLE
Can't load ISO files from PS3ISO

### ISSUE THREAD

**Issue by cdprete** [aldostools/webMAN-MOD#1141]
Hello.

I've the CFW 4.91 BETA 14 CEX from https://www.psx-place.com/threads/cfw-beta-13-4-91-2-evilnat-w-cobra-v8-5-cex-dex-pex-d-pex.39743/ and I've installed the https://github.com/aldostools/webMAN-MOD/releases/tag/1.47.47h release in order to be able to use my external HDD with NTFS because the ISO game I want to play is bigger than 4GB.

So far so good.

Unfortunately, all my trials to try start such a game failed.
These are the steps I was doing:

1. run prepISO  -> in the webman folder now a folder appears listing the game
2. click on the game -> a notification about moving something under `/tmp` appears
3. after a minute or two, a notification appears saying that the game has been loaded
4. after that, an error notification appears

Can you please provide some help? Am I doing something wrong?

Kind regards and thanks.

**Comment by aldostools** [comment]
Since the game is being scanned and listed by webMAN MOD properly, I recommend that very if the issue is the game or the storage. The game should not take that long to start.

Some tests that you could perform are:
1- Test if the game loads with IRISMAN.
2- Test if the game can be copied to the internal HDD and loads from there
3- Try a different game. It can be a small one if you want to save some time.
4- Check that your game is not encrypted. If it encrypted, you need to provide also the dkey or key file along with the ISO.
5- Verify that the USB cable or external HDD enclosure are not damaged.
6- Scan the NTFS on Windows to repair any cross-linked files.

**Comment by cdprete** [comment]
> Since the game is being scanned and listed by webMAN MOD properly, I recommend that very if the issue is the game or the storage. The game should not take that long to start.
> 
> Some tests that you could perform are: 1- Test if the game loads with IRISMAN. 2- Test if the game can be copied to the internal HDD and loads from there 3- Try a different game. It can be a small one if you want to save some time. 4- Check that your game is not encrypted. If it encrypted, you need to provide also the dkey or key file along with the ISO. 5- Verify that the USB cable or external HDD enclosure are not damaged. 6- Scan the NTFS on Windows to repair any cross-linked files.

Hi.
Thanks for the fast reply.

> 2- Test if the game can be copied to the internal HDD and loads from there

How?

> 4- Check that your game is not encrypted. If it encrypted, you need to provide also the dkey or key file along with the ISO.

How? 
I was actually able to freely see the content of the ISO under Windows. Is it enough or it's there some other level of encryption?

> 5- Verify that the USB cable or external HDD enclosure are not damaged.

I was previously using multiman and I had no issues with it in FAT32.

> 6- Scan the NTFS on Windows to repair any cross-linked files.

I formatted the drive freshly to avoid any issue.

**Comment by aldostools** [comment]
2- Copy the ISO to the internal HDD with IRISMAN's File Manager
4- If you downloaded the game from Redump or if you copied your ISO on PC. It's likely to be encrypted. You can try dumping the ISO game from the disc.
5- Ok. The USB cable or the external HDD enclosure are common cause of errors. That's why I mentioned them.
6- Ok. You can recheck again. Cross linked files are very frequent on USB devices formatted in NTFS. Even after a fresh format.

**Comment by cdprete** [comment]
Hi.

> 4- If you downloaded the game from Redump or if you copied your ISO on PC. It's likely to be encrypted. You can try dumping the ISO game from the disc.

I actually downloaded the ISO and, inside, I can see PS3_GAME and an Update folder, which contains the .pkg for the DLCs, with as well a PS3_DISC.SFB file.

**Comment by aldostools** [comment]
If you downloaded the ISO, it's likely to be still encrypted. PS3 ISOs usually have 3 or 5 regions with 1 or 2 regions encrypted.
Normally the ICON0.PNG, PARAM.SFO and PS3UPDAT.PUP are non-encrypted, while USRDIR and other files are in the encrypted region.

I recommend you that test NTFS dumping one of your disc games with multiMAN or IRISMAN.

**Comment by cdprete** [comment]
Hi.

> If you downloaded the ISO, it's likely to be still encrypted. PS3 ISOs usually have 3 or 5 regions with 1 or 2 regions encrypted.
Normally the ICON0.PNG, PARAM.SFO and PS3UPDAT.PUP are non-encrypted, while USRDIR and other files are in the encrypted region.

I've found a dkey for the game on https://ps3.aldostools.org/dkey.html, so how can I provide it to make it work?

**Comment by aldostools** [comment]
Put it in the same folder of the ISO and re-scan the games with prepISO.

If that doesn't work, try with a non pirated copy... I cannot provide you more support on pirated content.

**Comment by cdprete** [comment]
Are there any constraints or connections between the ISO and dkey files?

I don't know, for example they need to have the same name.

**Comment by aldostools** [comment]
The .key or .dkey need to be in the same folder of the ISO with the same file name. The file extension in lowercase.

**Comment by cdprete** [comment]
Hi.
Even with the dkey file I get the same result explained at the beginning of the issue.
Moreover, weird enough, if I copy the PS3_GAME folder out of the ISO and use with the same HDD but in FAT32, the game somehow starts (I get a view saying it's checking for trophies), but then it stucks.

**Comment by aldostools** [comment]
I will repeat it for the third and last time: try with the ISO of an ORIGINAL game. I will not waste more time supporting pirate content.

**Comment by cdprete** [comment]
Thank you anyway for your support.

Il sab 23 nov 2024, 13:42 Aldo Vargas ***@***.***> ha scritto:
