### ISSUE TITLE
[Improvement] Log in/out for Reload XMB

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#1148]
Aldo, I just reviewed your code, and it appears to count the folders inside the home directory. However, many users seem to use an installer for FIFA mods, and others use similar tools to "install" save data for users. Since they rely on the default XMBM+ TEAM installer, it ends up creating save folders for multiple "home" user directories. As a result, webMAN might mistakenly detect multiple users on the system, causing it to toggle log-in/log-out actions to reload the XMB.

To address this, I thought of also checking if there are multiple folders in the home directory and verifying if there’s more than one "localusername" file inside those folders. If that’s the case, it would indicate the presence of actual user accounts in the system.

**Comment by aldostools** [comment]
These "mods" should be fixed to create the saves in the proper paths.

I don't plan to fix that kind of bad implementation.

**Comment by LuanTeles** [comment]
Yeap, I was planning to create an installer for them to use, but I couldn't make it detect the actual user to ensure it only installs the save data for the current user due to my lack of skills. I'll keep researching and try to achieve this to create an installer for that kind of stuff.

I was able to make it detect the tittleID and install mods directly to game folder but for this kind of stuff i failed, the installer just hangs XD

**Comment by aldostools** [comment]
The python script for [custom packages](https://github.com/aldostools/webMAN-MOD/blob/master/_Projects_/pkglaunch/pypkg/pkg_custom.py) uses the content type 0x9 to make /dev_hdd0/theme the default folder and prefixPath "../../" to install from the root directory.

The following content types can be used to install files in the current user only:
#0xB		License					/dev_hdd0/home/<current user>/exdata
#0xD		PSN Avatar				/dev_hdd0/home/<current user>/psn_avatar

Use the prefixPath "../" to make the default folder in /dev_hdd0/home/<current user>

**Comment by LuanTeles** [comment]
@aldostools, I'm without my PC for now.

If you have time, could you create a PKG that installs for the current user as a placeholder, so I can add any content I want inside it?

> The python script for [custom packages](https://github.com/aldostools/webMAN-MOD/blob/master/_Projects_/pkglaunch/pypkg/pkg_custom.py) uses the content type 0x9 to make /dev_hdd0/theme the default folder and prefixPath "../../" to install from the root directory.
> 
> The following content types can be used to install files in the current user only: #0xB License /dev_hdd0/home//exdata #0xD PSN Avatar /dev_hdd0/home//psn_avatar
> 
> Use the prefixPath "../" to make the default folder in /dev_hdd0/home/

@aldostools, I'm without my PC for now.

If you don’t mind and have the time, could you create a PKG that installs content for the current user, so I can use it to add any content I want inside it?
