### ISSUE TITLE
Linux ps3netsrv - webman can't mount any games after read error

### ISSUE THREAD

**Issue by C0rn3j** [aldostools/webMAN-MOD#115]
Hiya, 
I'm using ps3netsrv on Arch Linux, compiled it myself from this repo (should be up to the latest commit).

    ps3netsrv build 20170310 (mod by aldostools)  

my PS3 is on Rebug 4.81.2(installed on a formatted HDD), enabled Webman and then updated it to 1.47.06.

Using multiMAN 04.81.02 I ripped my own games and saved them to network. I could then play just fine. My HDD then died, prompting me to reinstall on a newly formatted HDD as mentioned before.

The console is on DEX, although issue was still happening when it was CEX.

The actual issue:
```
[130] % ./ps3netsrv  /mnt/3tbRED/PS3/                                               
ps3netsrv build 20170310 (mod by aldostools)                                        
Path: /mnt/3tbRED/PS3                                                               
                                                                                    
Waiting for client...                                                               
Connection from 192.168.1.11                                                        
open error on "/GAMES/BCES00647-[Buzz Quiz World]/PS3_GAME/PARAM.SFO" (viso=0)      
Connection from 192.168.1.11                                                        
building virtual iso...                                                             
Cannot find /mnt/3tbRED/PS3/GAMES/BLES00928-[Tom Clancys HAWX 2]/PS3_GAME/PARAM.SFO 
open error on "/GAMES/BLES00928-[Tom Clancys HAWX 2]" (viso=1)                      
```

When I launch the PS3, I get an error about Buzz (which I didn't even try to launch) and when I try to launch Tom Clancys HAWX 2 I then get another error.

When I then try to launch God of War Ascension (which was not ripped by me) it does not work, there's no log in the terminal about it.

When I then restart the PS3 and try to launch GoW:Ascension, it works. 

```
Reconnection from 192.168.1.11                                                   
open error on "/GAMES/BCES00647-[Buzz Quiz World]/PS3_GAME/PARAM.SFO" (viso=0)   
Connection from 192.168.1.11                                                     
building virtual iso...                                                          
open /GAMES/BCES01741-[God of War Ascension EU]                                  
```

---

I actually figured out why I'm getting the read errors in the middle of making this issue:

```
(ssh) c0rn3j@c0rn3jDesktop : /mnt/3tbRED/PS3/GAMES/BCES00647-[Buzz Quiz World]/PS3_GAME   
[0] % file PARAM.SFO                                                                      
PARAM.SFO: sticky executable, regular file, no read permission                            
                                                                                          
(ssh) c0rn3j@c0rn3jDesktop : /mnt/3tbRED/PS3/GAMES/BCES00647-[Buzz Quiz World]/PS3_GAME   
[0] % ls -lah                                                                             
totalt 3,9M                                                                               
drwxr-xr-x 1 c0rn3j c0rn3j  234 nov.  26 11:06 .                                          
drwxr-xr-x 1 c0rn3j c0rn3j   60 nov.  26 11:01 ..                                         
---x-----t 1 c0rn3j c0rn3j  44K nov.  26 11:01 ICON0.PNG                                  
---x-----t 1 c0rn3j c0rn3j 222K nov.  26 11:01 ICON1.PAM                                  
drwxr-xr-x 1 c0rn3j c0rn3j   14 nov.  26 11:01 LICDIR                                     
---x-----t 1 c0rn3j c0rn3j 1,3K nov.  26 11:01 PARAM.SFO                                  
---x-----t 1 c0rn3j c0rn3j 2,2M nov.  26 11:01 PIC1.PNG                                   
---x-----t 1 c0rn3j c0rn3j  58K nov.  26 11:06 PS3GAME.BG0                                
---x-----t 1 c0rn3j c0rn3j 507K nov.  26 11:06 PS3GAME.BG1                                
---x-----t 1 c0rn3j c0rn3j    4 nov.  26 11:06 PS3GAME.CHK                                
---x-----t 1 c0rn3j c0rn3j   12 nov.  26 11:06 PS3GAME.INI                                
---x-----t 1 c0rn3j c0rn3j 5,0K nov.  26 11:01 PS3LOGO.DAT                                
---x-----t 1 c0rn3j c0rn3j 931K nov.  26 11:01 SND0.AT3                                   
drwxr-xr-x 1 c0rn3j c0rn3j   24 nov.  26 10:56 TROPDIR                                    
drwxr-xr-x 1 c0rn3j c0rn3j   64 nov.  26 11:06 USRDIR                                     
```

Simply executing the following fixed the issue.

    sudo chmod +r /mnt/3tbRED/PS3 -R

So the bug I see is that after not having read permissions (despite being the file owner), webman will refuse to load anything else until a restart.

Also I think ps3netsrv could warn about this in a better way than "can't find" error when the file is obviously there, there just isn't read permission. 

Perhaps even fix the permissions itself (or this may possibly be an issue for multiman which created the problematic files in the first place?).

**Comment by aldostools** [comment]
Try converting the games "Buzz Quiz World" or "Tom Clancys HAWX 2" to ISO.

Also check if these games have the same permissions as "God of War Ascension".

**Comment by C0rn3j** [comment]
@aldostools As I said - the files were there, after putting read permissions on Buzz and Tom clancys, they load alright.

The issues are:

1) File not found should not be the error when the file is actually there

2) When the permissions are wrong but ps3netsrv has the actual (owner/root) permissions, the issue could be autocorrected (or with permission) by ps3netsrv

3) After the error no other games can be mounted.

I tried with another game which is actually totally missing PARAM.SFO, and it gave me the same error, and afterwards I couldn't mount anything else again.

**Comment by aldostools** [comment]
Thanks for the feedback. However, these are user errors.

**Comment by C0rn3j** [comment]
There is a wrong error message + when I load a broken game I need to restart the console.

Bad error handling is not user error imo.
