### ISSUE TITLE
[Issue] /reloadxmb.ps3

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#1150]
Aldo, it seems like the /reloadxmb.ps3 command doesn't check if more than one user exists; it goes to the user column even with just one user. Could you make the command check for this before executing?

I'm planning to use it on HEN via boot_init.txt to reload the XMB, ensuring that my explorer_plugin.sprx automatically loads after enabling HEN, without the need for the user to manually reload.

**Comment by aldostools** [comment]
The function is checking the number of users. 

The old method that executes the RELOADXMB application is used if any of the following conditions occur:

1. If there is there only one user, or
2. If the Reload XMB method in /setup.ps3 is RELOADXMB, or
3. If you're using the Lite edition or a custom compilation without VIRTUAL_PAD.

![image](https://github.com/user-attachments/assets/5df7aeda-9da0-4602-8a25-e7d893cb3f66)

**Comment by LuanTeles** [comment]
Yes, i saw the code.


EDIT:

Oh, it seems that it's counting the files as well, not just the folders. I store a settings.xml (dev_hdd0/home/settings.xml) file there as a semaphore for the script to execute the initial settings and some others.

**Comment by LuanTeles** [comment]
Could it just counts the folders that starts with 00000XXX?  if not, i can make the script and my installer to read the xml from another path.

**Comment by aldostools** [comment]
You should move your xml to another path. /home is for user profiles only.

There are other paths that can be used to store settings. e.g. /tmp or /vm

The function counts the items in a folder until the limit specified (1 or 2). The items found that start with a dot '.' are ignored.
![image](https://github.com/user-attachments/assets/d8aab96e-265c-439d-807d-83cc7d369bb3)

**Comment by LuanTeles** [comment]
Thanks, i'll just move it then.

**Comment by LuanTeles** [comment]
Ah, today i found a guy complaning of webMAN and my mod always going to the user category and i found out that ReactPSN also store files in home folder hahaha

Reactsys.key

**Comment by aldostools** [comment]
Test if this build fixes the issue. It counts only the directory items that start with "0000" in /dev_hdd0/home
[webMAN-MOD.zip](https://github.com/user-attachments/files/18225255/webMAN-MOD.zip)

IMHO It's a bad practice to write homebrew files to dev_hdd0/home instead of create them in their own folder in /game or /tmp.

**Comment by LuanTeles** [comment]
I don’t store files there anymore. I just found it curious why he was experiencing this issue, so I asked if he had installed any savedata installer (those that create multiple home folders while trying to install savedata in the current user folder — a poor approach). He said no, so I asked for a screenshot and discovered the Reactsys.key there.

**Comment by LuanTeles** [comment]
> Test if this build fixes the issue. It counts only the directory items that start with "0000" in /dev_hdd0/home [webMAN-MOD.zip](https://github.com/user-attachments/files/18225255/webMAN-MOD.zip)
> 

I'll create a dummy file and report back

**Comment by LuanTeles** [comment]
> Test if this build fixes the issue. It counts only the directory items that start with "0000" in /dev_hdd0/home [webMAN-MOD.zip](https://github.com/user-attachments/files/18225255/webMAN-MOD.zip)
> 
> IMHO It's a bad practice to write homebrew files to dev_hdd0/home instead of create them in their own folder in /game or /tmp.

It is not going to the user category anymore, but it is hitting the accept button two times.

**Comment by LuanTeles** [comment]
BTW, Aldo, I could modify my installer to scan the home folders to check if they contain the localusername file, which indicates that the folder belongs to a real user and delete if the file is not present.

But how could I, for example, make the onxmb.bat script verify this? (to avoid users installing this after my installer and compains about it) Is it even possible? I’m just brainstorming because the installer that places files in home folders, rather than the actual user’s folder, is quite popular. I think it’s used for the Potato patch, targeting users who don’t want or don’t have USB drives. The installer works by creating multiple user folders and hoping it gets lucky in finding the correct user folder.

Sorry for bringing up this subject again :P

 I always try to consider every possible scenario that a regular user might encounter.

**Comment by LuanTeles** [comment]
Look at this curious case with another user, this one happens to be a friend of mine.

He has two folders on his PS3:
![image](https://github.com/user-attachments/assets/3ad20c13-e271-4762-9c85-e05068d7f710)


The 0002 folder is empty, containing only the exdata folder for some reason:
![image](https://github.com/user-attachments/assets/d04ef666-11a0-4bd7-b90d-492971c63610)


The 0005 folder is his real one:
![image](https://github.com/user-attachments/assets/fbebcee9-637c-483a-aeda-117fe56fd8b9)

The system, of course, only recognizes one user because of the localusername file and xregistry.

The funny thing is that his system allows him to log out from his single account, and look his user even have the auto-login icon active. , options that should only be possible when more than one user exists! 

LOL
![image](https://github.com/user-attachments/assets/171ef7fc-59b4-4a55-aee0-291f35fff931)

**Comment by LuanTeles** [comment]
Following the /reloadxmb.ps3 request, could you add a script command to check if there’s more than one user?

Here’s the deal: I use this to reload the XMB automatically so my SPRX remaps take effect on HEN.

It works fine most of the time (see the video)

https://github.com/user-attachments/assets/749e8457-02b6-48ef-8c3c-20a7074c6295


, as long as I use an 8 second delay before running the command. Without the delay, it goes to the "Do you want to log out?" screen and waits for a manual input. The problem is, the 8 second delay doesn’t work for everyone. A user of my mod showed me that, on their system, it only gets to the prompt screen unless the delay is set to 18 seconds, which feels way too long.

![image](https://github.com/user-attachments/assets/09aa1b08-3ef6-44e5-af5c-9a00adfba932)


I thought about adding extra pad confirmation commands to press the yes button on the prompt screen, but if there’s only one user logged in, it might end up pressing stuff on the XMB. That’s why having a way to check if there’s more than one user would really help

eg: if has one user , if has multiple users

**Comment by aldostools** [comment]
Try this build. I only added the command: `if singleUser`
[webftp_server.zip](https://github.com/user-attachments/files/18235278/webftp_server.zip)

**Comment by LuanTeles** [comment]
> Try this build. I only added the command: `if singleUser` [webftp_server.zip](https://github.com/user-attachments/files/18235278/webftp_server.zip)

Thank you, Aldo. I can only test it on the weekend as I'm traveling for Christmas. I'll check if RPCS3 can run plugins

**Comment by aldostools** [comment]
Take your time. I added only a single line. 😀

**Comment by nikolaevich23** [comment]
> I thought about adding extra pad confirmation commands to press the yes button on the prompt screen, but if there’s only one user logged in, it might end up pressing stuff on the XMB. That’s why having a way to check if there’s more than one user would really help
> 
Nothing unnecessary is pressed. [My version is here.](https://github.com/nikolaevich23/nikolaevich23.github.io/blob/a2db0cb54cdcb80eb9bf046f62d447902107f9fb/PS3HEN/henplugin/main.c#L509
)

**Comment by nikolaevich23** [comment]
> I thought about adding extra pad confirmation commands to press the yes button on the prompt screen, but if there’s only one user logged in, it might end up pressing stuff on the XMB. That’s why having a way to check if there’s more than one user would really help

Updating xml via relog will only work for several users, if there is 1 user then you cannot re-login

**Comment by LuanTeles** [comment]
> > I thought about adding extra pad confirmation commands to press the yes button on the prompt screen, but if there’s only one user logged in, it might end up pressing stuff on the XMB. That’s why having a way to check if there’s more than one user would really help
> 
> Updating xml via relog will only work for several users, if there is 1 user then you cannot re-login


Yeap, I know. The issue I'm facing is related to timing. webMAN might fail to press accept on the login screen prompt in time, preventing it from automatic logging in again. Adding some pad accept commands could help fix this.

**Comment by nikolaevich23** [comment]
> Yeap, I know. The issue I'm facing is related to timing. webMAN might fail to press accept on the login screen prompt in time, preventing it from automatic logging in again. Adding some pad accept commands could help fix this.

There is no need to use webman. I implemented [relogin in my version of hen](https://github.com/nikolaevich23/nikolaevich23.github.io/blob/00baa44fa86e03f26f5fbe9d8fd107d11a1d199e/PS3HEN/henplugin/main.c#L522). I also added a check for 1 user.

**Comment by LuanTeles** [comment]
> > Yeap, I know. The issue I'm facing is related to timing. webMAN might fail to press accept on the login screen prompt in time, preventing it from automatic logging in again. Adding some pad accept commands could help fix this.
> 
> There is no need to use webman. I implemented [relogin in my version of hen](https://github.com/nikolaevich23/nikolaevich23.github.io/blob/00baa44fa86e03f26f5fbe9d8fd107d11a1d199e/PS3HEN/henplugin/main.c#L522). I also added a check for 1 user.

That's nice, thanks

I was about to implement it in my HEN fork too, but since I’ll be using it in more places that uses webMAN commands I’ll still need the webMAN detection.

**Comment by LuanTeles** [comment]
> > Yeap, I know. The issue I'm facing is related to timing. webMAN might fail to press accept on the login screen prompt in time, preventing it from automatic logging in again. Adding some pad accept commands could help fix this.
> 
> There is no need to use webman. I implemented [relogin in my version of hen](https://github.com/nikolaevich23/nikolaevich23.github.io/blob/00baa44fa86e03f26f5fbe9d8fd107d11a1d199e/PS3HEN/henplugin/main.c#L522). I also added a check for 1 user.

It's off-topic, but may I ask you something? When explorer_plugin.sprx and game_ext.sprx are mapped in your fork, do you ever encounter a black screen?

I'm considering adding the patches via payload on the fly, similar to Cobra 8.5, instead of mapping the SPRX files, if they are the cause of the occasional black screens. It seems like 3/10 of hen enabling it might have black screen after booting a game, (IDK if it's normal on HEN or it's caused by mapping files, i never used hen vanilla)

**Comment by aldostools** [comment]
I don't have black screens very often on Cobra.

I suspect they could be related to the buggy code used for mappath.c

Have you tried compiling HEN with the mappath.c from Mamba or from early versions of HEN?

Anyway your idea about using module patches instead of mappath is good. 👍

**Comment by nikolaevich23** [comment]
> It's off-topic, but may I ask you something? When explorer_plugin.sprx and game_ext.sprx are mapped in your fork, do you ever encounter a black screen?

folder games give a black screen until you mount them once via multiman

**Comment by aldostools** [comment]
> folder games give a black screen until you mount them once via multiman

This statement increases my suspicions about the faulty mapping in `mappath.c`. multiMAN clears all the existing mapped paths when its launched in mmCM mode. In multiMAN mode it installs the mM payload that uses it own LV2 mapping system.

@LuanTeles you could try clearing all the existing mapped paths using the web command `/unmap.ps3`
or `sys_map_path(NULL, NULL);` in your source code.

**Comment by LuanTeles** [comment]
> > Yeap, I know. The issue I'm facing is related to timing. webMAN might fail to press accept on the login screen prompt in time, preventing it from automatic logging in again. Adding some pad accept commands could help fix this.
> 
> There is no need to use webman. I implemented [relogin in my version of hen](https://github.com/nikolaevich23/nikolaevich23.github.io/blob/00baa44fa86e03f26f5fbe9d8fd107d11a1d199e/PS3HEN/henplugin/main.c#L522). I also added a check for 1 user.

Your code is good, but I tested it here, and it worked when enabling HEN from my main user (00000008). Your code checked up to 20 users ahead, searching for folders until 00000028. My second user is 00000017, so it triggered the logoff/login. However, when I enabled HEN from my second user, it searched for folders up to 00000037, and 4 folders back from my current user until 00000013, so it didn't trigger the logoff/login.

See how i did on mine

```c
static int number_users(void)
{
    CellFsStat stat;
    char path1[64];
    int num = 0;
    int fd;
    uint64_t nread;
    CellFsDirent dirent;

    cellFsOpendir("/dev_hdd0/home", &fd);

    while (cellFsReaddir(fd, &dirent, &nread) == CELL_FS_SUCCEEDED && nread > 0)
    {
        if (strlen(dirent.d_name) == 8)
        {
            int is_valid = 1;

            for (int i = 0; i < 4; i++)
            {
                if (dirent.d_name[i] != '0')
                {
                    is_valid = 0;
                    break;
                }
            }

            for (int i = 4; i < 8 && is_valid; i++)
            {
                if (dirent.d_name[i] < '0' || dirent.d_name[i] > '9')
                {
                    is_valid = 0;
                    break;
                }
            }

            if (is_valid)
            {
                snprintf(path1, sizeof(path1), "/dev_hdd0/home/%s/localusername", dirent.d_name);

                if (cellFsStat(path1, &stat) == CELL_FS_SUCCEEDED)
                {
                    num++;

                    if (num >= 2)
                    {
                        break;
                    }
                }
            }
        }
    }

    cellFsClosedir(fd);

    return num;
}
```
It searches for valid folders with 8 digits, where the first four are zeros and the last four are numbers. If it finds two valid user folders (those containing 'localusername'), it stops, as we already know the system has multiple users


https://github.com/user-attachments/assets/9d6d0b8d-ffb3-48c5-8486-c40302559b17

**Comment by LuanTeles** [comment]
> I don't have black screens very often on Cobra.
> 
> I suspect they could be related to the buggy code used for mappath.c
> 
> Have you tried compiling HEN with the mappath.c from Mamba or from early versions of HEN?
> 
> Anyway your idea about using module patches instead of mappath is good. 👍

The earlier mappath.c also had occasional black screens and other issues. For example, when launching a game, sometimes the clock would spin, and the system would stay like that for a while before freezing. There were cases where, when exiting a game, the XMB wouldn't load, only displaying the wave without icons until the system froze.

When I reported these issues in the thread, bguerville created a new one that solved them and seems to handle the mappings better than the original.

**Comment by LuanTeles** [comment]
> > I don't have black screens very often on Cobra.
> > I suspect they could be related to the buggy code used for mappath.c
> > Have you tried compiling HEN with the mappath.c from Mamba or from early versions of HEN?
> > Anyway your idea about using module patches instead of mappath is good. 👍
> 
> The earlier mappath.c also had occasional black screens and other issues. For example, when launching a game, sometimes the clock would spin, and the system would stay like that for a while before freezing. There were cases where, when exiting a game, the XMB wouldn't load, only displaying the wave without icons until the system froze.
> 
> When I reported these issues in the thread, bguerville created a new one that solved them and seems to handle the mappings better than the original.


Well, I just remembered that later we found the issues were caused by webMAN's dynamic fan control. I just tested it here by setting my fan to dynamic, and voilà, the same old issues are back again.

So yeah, it's worth trying Mamba's mappath.c or the earlier versions of HEN, but if I recall correctly, I also had occasional black screens.

See here, i set my fan control to dynamic and tried to launch a game


https://github.com/user-attachments/assets/32024357-42b0-4bc5-8f93-d62ed95672a7

**Comment by LuanTeles** [comment]
@aldostools i'm trying to compare files to make a copy only if they are different, but my code is always returning that they are equal

```c

int compare_files(const char *file1, const char *file2)
{
    int fd1, fd2;
    char buffer1[0x1000], buffer2[0x1000];
    uint64_t nread1, nread2;

    if (cellFsOpen(file1, CELL_FS_O_RDONLY, &fd1, 0, 0) != CELL_FS_SUCCEEDED ||
        cellFsOpen(file2, CELL_FS_O_RDONLY, &fd2, 0, 0) != CELL_FS_SUCCEEDED)
    {
        if (fd1 >= 0) cellFsClose(fd1);
        if (fd2 >= 0) cellFsClose(fd2);
        return -1;
    }

    while (1)
    {
        int ret1 = cellFsRead(fd1, buffer1, sizeof(buffer1), &nread1);
        int ret2 = cellFsRead(fd2, buffer2, sizeof(buffer2), &nread2);

        if (ret1 != CELL_FS_SUCCEEDED || ret2 != CELL_FS_SUCCEEDED || nread1 != nread2)
        {
            cellFsClose(fd1);
            cellFsClose(fd2);
            return 1;
        }

        if (nread1 == 0) break;

        if (memcmp(buffer1, buffer2, nread1) != 0)
        {
            cellFsClose(fd1);
            cellFsClose(fd2);
            return 1;
        }
    }

    cellFsClose(fd1);
    cellFsClose(fd2);
    return 0;
}
```

```c
    if (cellFsStat("/dev_flash/vsh/etc/premium.txt", &stat) == 0)
    {
        const char* files_to_copy[] = {
            "/dev_hdd0/game/PS34KPROX/USRDIR/toolbox/patches/game_column_fix/hfw/category_friend.xml",
            "/dev_hdd0/game/PS34KPROX/USRDIR/toolbox/patches/game_column_fix/hfw/category_game.xml",
            "/dev_hdd0/game/PS34KPROX/USRDIR/toolbox/patches/game_column_fix/hfw/category_music.xml",
            "/dev_hdd0/game/PS34KPROX/USRDIR/toolbox/patches/game_column_fix/hfw/category_network.xml",
            "/dev_hdd0/game/PS34KPROX/USRDIR/toolbox/patches/game_column_fix/hfw/category_photo.xml",
            "/dev_hdd0/game/PS34KPROX/USRDIR/toolbox/patches/game_column_fix/hfw/category_psn.xml",
            "/dev_hdd0/game/PS34KPROX/USRDIR/toolbox/patches/game_column_fix/hfw/category_tv.xml",
            "/dev_hdd0/game/PS34KPROX/USRDIR/toolbox/patches/game_column_fix/hfw/category_user.xml",
            "/dev_hdd0/game/PS34KPROX/USRDIR/toolbox/patches/game_column_fix/hfw/category_user_login.xml",
            "/dev_hdd0/game/PS34KPROX/USRDIR/toolbox/patches/game_column_fix/hfw/category_video.xml"
        };

        const char* destination_paths[] = {
            "/dev_update/vsh/resource/explore/xmb/category_friend.xml",
            "/dev_update/vsh/resource/explore/xmb/category_game.xml",
            "/dev_update/vsh/resource/explore/xmb/category_music.xml",
            "/dev_update/vsh/resource/explore/xmb/category_network.xml",
            "/dev_update/vsh/resource/explore/xmb/category_photo.xml",
            "/dev_update/vsh/resource/explore/xmb/category_psn.xml",
            "/dev_update/vsh/resource/explore/xmb/category_tv.xml",
            "/dev_update/vsh/resource/explore/xmb/category_user.xml",
            "/dev_update/vsh/resource/explore/xmb/category_user_login.xml",
            "/dev_update/vsh/resource/explore/xmb/category_video.xml"
        };
        
        for (size_t i = 0; i < sizeof(files_to_copy) / sizeof(files_to_copy[0]); i++)
        {
            if (cellFsStat(files_to_copy[i], &stat) == 0 &&
                cellFsStat(destination_paths[i], &stat) == 0)
            {
                if (compare_files(files_to_copy[i], destination_paths[i]) != 0)
                {
                    char categories1_xml[0x80];
                    sprintf(categories1_xml, "Files don't match");
                    show_msg((char *)categories1_xml);
                }
                else
                {
                    char categories2_xml[0x80];
                    sprintf(categories2_xml, "Files are the same");
                    show_msg((char *)categories2_xml);
                    goto end;
                }
            }
            else
            {
                char categories3_xml[0x80];
                sprintf(categories3_xml, "One of them doesn't exists");
                show_msg((char *)categories3_xml);
            }
        }
    }
    
```
It is always returning me "Files are the same" even if i remove half of it's content, do you have any idea?

I'm implementing this to restore the xmb categories if the user install the so-called fixes to show unofficial stores.

**Comment by aldostools** [comment]
The problem seems to be the `goto end;` inside the loop.

You are comparing 2 lists of 10 files each. As soon as it finds one file identical, it exits the loop.

If you want to check if all files are the same, you need do something like this:

```C
        int same_files_count = 0;
        const int total_files = sizeof(files_to_copy)/sizeof(*files_to_copy);

        for (size_t i = 0; i < total_files; i++)
        {
            if (cellFsStat(files_to_copy[i], &stat) == 0 &&
                cellFsStat(destination_paths[i], &stat) == 0)
            {
                if (compare_files(files_to_copy[i], destination_paths[i]) != 0)
                      break;
                else
                      ++same_files_count;
            }
            else
            {
                same_files_count = -1;
                break;
            }
        }

        if(same_files_count == total_files)
        {
            show_msg((char *)"Files are the same");
            goto end;
        }
        else if(same_files_count == -1)
            show_msg((char *)"One of them doesn't exists");
        else
            show_msg((char *)"Files don't match");
```

**Comment by nikolaevich23** [comment]
> The earlier mappath.c also had occasional black screens and other issues. For example, when launching a game, sometimes the clock would spin, and the system would stay like that for a while before freezing. There were cases where, when exiting a game, the XMB wouldn't load, only displaying the wave without icons until the system froze.
> 
> When I reported these issues in the thread, bguerville created a new one that solved them and seems to handle the mappings better than the original.

I tried to launch games/software when mappath_disabled=1, there were no black screens. it will be interesting to see your idea of ​​​​replacing on the fly.

**Comment by LuanTeles** [comment]
> > The earlier mappath.c also had occasional black screens and other issues. For example, when launching a game, sometimes the clock would spin, and the system would stay like that for a while before freezing. There were cases where, when exiting a game, the XMB wouldn't load, only displaying the wave without icons until the system froze.
> > When I reported these issues in the thread, bguerville created a new one that solved them and seems to handle the mappings better than the original.
> 
> I tried to launch games/software when mappath_disabled=1, there were no black screens. it will be interesting to see your idea of ​​​​replacing on the fly.


It might take some time, as I haven’t had much time to work on it lately. You can find some opcodes in Cobra 8.5, at least for the gameboot patch we use via mappath.

Could you test the Mamba mappath to see if it resolves the black screen issue in the meantime?

**Comment by LuanTeles** [comment]
> Try this build. I only added the command: `if singleUser` [webftp_server.zip](https://github.com/user-attachments/files/18235278/webftp_server.zip)

I forgot to report, it's working good :), i tested in the newest version

Thanks aldo!
