### ISSUE TITLE
[Issue?] Calling Nas Plugin

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#1159]
Hey aldo, it seems like if i use /popup.ps3?msg_authorization_pls_wait&rco=nas_plugin for example, webMAN hangs

any idea?

**Comment by aldostools** [comment]
Hello Luan,
Yes, there was an issue if the plugin was not already loaded in memory.

webMAN now tries to load the plugin if it isn't loaded in memory.
