### ISSUE TITLE
Lost ISO

### ISSUE THREAD

**Issue by DStrifer** [aldostools/webMAN-MOD#116]
Hi
My cfw - "Rebug 4.81.2 – Cobra 7.5 – Toolbox 2.02.12 – Jan 10th. 2017"
Since that day i had no problems. But after webMAN_MOD_1.47.06_Updater, most of my games (ISO) on usb-hdd missing from menu ? Why? How to fix it?

**Comment by aldostools** [comment]
Try rescanning the content using Select+L3.

If the games still don't show verify in /setup.ps3 that the devices and all content type are selected, save the settings and rescan again.
note: click the scan content button to show these options.

**Comment by DStrifer** [comment]
ok, i will try it tomorrow. I delete WM for now, wanna try new sMan but it even worse, it scans only game on internal hdd, and absolutely no reaction on usb-hdd (ntfs) where all the games are.

**Comment by Joonie86** [comment]
Closing old issues that have no further feedback, Please try the latest wMM and report us.
