### ISSUE TITLE
JBFolder Doesn't Mount

### ISSUE THREAD

**Issue by B-Dem** [aldostools/webMAN-MOD#1161]
With the latest update of Webman Mod, there is a big problem with JB folders.
They just don’t mount anymore.

Here is a video to explain:

[https://www.youtube.com/watch?v=635-hux9L_k](https://www.youtube.com/watch?v=635-hux9L_k)
As you can see, games are mounted properly when I try with Multiman Mod.

(Don’t mind the doubled sound, I don’t know why it happens.)

**Comment by aldostools** [comment]
Hello dear Memz,
Thank you for your feedback and the video describing properly your issue.

I tested the games with the latest build 1.47.47i, which I updated using the online updater found in webMAN Setup menu.
The games in GAMES folder and PS3ISO were mounted properly on my system.

Please verify if Cobra is enabled. Cobra usually is disabled automatically if a system fault occurs or if you enter to recover menu.

multiMAN MOD uses 2 modes: one uses Cobra and the other uses the original payloads used before Cobra was commonly used.
The second mode only works for GAMES folder, which could be your case.

My recommendation is to uninstall webMAN MOD and reinstall the latest build again.

**Comment by B-Dem** [comment]
Hey,
Thanks for your answer !
I tried uninstalling Webman, then reinstalling it and the issue is still here.
I did tried the latest build so idk why it doesn't work...

**Comment by aldostools** [comment]
Could you test mounting a PS3ISO or PSXISO?

Also you can try mounting the game from the web interface.

**Comment by B-Dem** [comment]
Here with a PS3 ISO it work as it should be !

Here's another video :
[https://youtu.be/cKgcpN8cIw8](https://youtu.be/cKgcpN8cIw8)

**Comment by aldostools** [comment]
Are you using HEN? I think the issue could be a bug in mappath.c of the payload.
(If I recall correctly, Jason changed the original mappath.c and now he's using the new code by bguerville which I think is buggy)

I tested it using CFW Evilnat 4.91.2 BETA 16

**Comment by B-Dem** [comment]
Yep im on HEN

**Comment by B-Dem** [comment]
Im on the latest 3.3.1

**Comment by aldostools** [comment]
Could you try installing an older version of PS3HEN? I'm not sure if they are compatible with the latest version.

You can report the issue to @esc0rd3w if you confirm that the issue is HEN.

**Comment by B-Dem** [comment]
Ok i downgraded to HEN 3.3.0 and now it works so the issue is from WMM or HEN ?

**Comment by aldostools** [comment]
Then the issue is HEN 3.3.1, because you only changed HEN. You didn't change WMM.

**Comment by esc0rtd3w** [comment]
I had that issue while testing 3.3.1 and it was present only on debug version, which is the version you all have. It was fixed, or i thought it was a couple weeks ago, as the mounting works for me now on my 2501 slim.

This is the latest pkg currently on Open Beta thread 
http://ps3xploit.me/hen/openbeta/Latest_HEN_Installer_3.3.1_signed-491C--test31.pkg

I will post a new pkg with release (non-debug test) on the Open Beta thread soon
https://www.psx-place.com/threads/ps3hen-open-beta-testing-for-advanced-users-only.37363/

**Comment by B-Dem** [comment]
Ohh, I don't have the latest version at all!
I have version test12, LMAO. 
I think that's why x)
I will try the latest test version rn, I LYK

**Comment by esc0rtd3w** [comment]
here is new non-debug pkg, but i just tested both and they both work for me
http://ps3xploit.me/hen/openbeta/Latest_HEN_Installer_3.3.1_signed-491C--test31b-non-debug-test.pkg

**Comment by B-Dem** [comment]
Yep, it's fixed now!
Turns out the issue was with Beta 12.
Thanks for the help, @esc0rtd3w !
And thanks you too @aldostools for all your work (and for maintaining your fork of PPPwnUI. Maybe I'll update it someday...)

**Comment by eliekh05** [comment]
that is why use iso it is way better
