### ISSUE TITLE
PS3 net server and Windows 10 compact

### ISSUE THREAD

**Issue by ghost** [aldostools/webMAN-MOD#117]
Hello Aldo,

I wanted to contact you to mention the following. I am absolutely in love with the possibilities PS3 Net Server provides, especially for the long term storing of backups.

Today, as a test, I decided to try to use the Windows 10 "compact" function on one of my backups. Especifically, I used the XPRESS16K algorithm. (I used CompactGUI to do this).

While the PS3 was still able to access the game just fine, I did notice quite a hit in the loading times (it's like playing by mail!).

I was not sure if anyone else had attempted to do this before, but it seems to be a quite popular option, especially for compressing huge Steam libraries. 

Is this problem from the PS3 side? (a limitation, perhaps?).

Thanks again for the great tools.

**Comment by aldostools** [comment]
PS3 NET Server through wireless is not recommended.
Connect the PC directly to the PS3 using a crossover cable or through a traditional ethernet network.

Make sure that both devices are wired!

**Comment by ghost** [comment]
Hello Aldo! Thanks for your reply.

Indeed, both the PS3 and the PC are connected via ethernet through a gigabit-capable router. Games that haven't been compressed by Compact run great.

**Comment by aldostools** [comment]
Also avoid any compression of ISO or game folder... You won't get any significant reduction due PS3 files generally are already compressed. You only will impact the I/O performance.

**Comment by ghost** [comment]
Oh... I guess maybe it's the PS3 side then?

Compact managed to compress one of such games from 30 GB to 2 GB (the folder itself), it is a significant difference. On average, it produced 40% compression. Compact does not present any performance hits in regular PC gaming, which is why I believe it was worth checking for PS3 Net Server as well.

**Comment by aldostools** [comment]
The difference between PC gaming and PS3 NET Server is that PC reads the file and executes it.

PS3 NET Server emulates a bluray disc and read/transmit sectors over the network. If the game read a sector multiple times, you will get heavy traffic. Compressing the ISO only will add more overhead to the process.

**Comment by ghost** [comment]
I see! That makes a lot of sense.

Thank you for your quick replies Aldo!

Best wishes.
