### ISSUE TITLE
PS3 CECHL 80GB, Webman Fan ON, SUPER LOUD on startup! Any way to delay auto fan?

### ISSUE THREAD

**Issue by Nashismo** [aldostools/webMAN-MOD#119]
First, thank you Aldo for your awesome software!

I just got a PS3 with CFW, the problem is that when I use the Auto fan on Webman, the PS3 gets super crazy LOUD on startup, but just for a few seconds. It is ONLY at startup because the fans are normal while playing games, never going above 30% with a max temperature of 68c.

This happens even when turning the console while cold. Also, my temps are normal, I changed the thermal paste also on my PS3, so no problems there and like I said, no loud fans while playing for hours.

But again, it sounds SUPER loud on startup, I wake everyone in the house :) My question: Wouldn't be a way of "delaying" the auto fan utility by a few seconds? Because I can tell that it only happens on the first 4 seconds or so.

My system:
PS3 CECHL 80GB Fat (2008)
Rebug Cobra 4.82
WebMAN MOD 1.47.06

I have tried with other CFW, but the same thing happens, no matter what I do. I remember this USED to happen before on a PS3 Slim I had, but it was FIXED by trying different custom firmwares. Now NO CFW fixes this problem for me.

So... is it possible to delay to Auto Fan utility? I DO need it! Because Fatties can get a bit warm sometimes.

Thanks for your time and for reading, and thank you for all you have done.

(I obviously don't get this problem with SYSCON fan).

**Comment by aldostools** [comment]
Hello Nashismo,
That issue is a known problem with CECH**L** models when the dynamic fan control is enabled. In these models, the workaround to avoid that behavior is to shutdown the console using the combo **L3+R2+X** instead of using the PS menu or the power button in the front panel.

**Comment by Nashismo** [comment]
Thank you Aldo! Yes, I was thinking that it was probably something to do with the PS3 Model. I will try what you suggest.
Another workaround is to unplug the PS3 from the wall, THEN power it on and the loudness doesn't happen.

Thanks ;)

**Comment by aldostools** [comment]
To unplug the PS3 from the wall could damage the HDD or its content or maybe other components.

**Comment by Nashismo** [comment]
I meant I unplug it when is off of course, or turn the power switch off and then on (while the PS3 is off).

Thanks again and take care.

**Comment by Dockolm** [comment]
Hello there.

I would like to add some info on this, to inform those like me who searched about this problem.
I have this model, and since I installed webMAN on my console, the fan is also super loud on startup, ~~but also louder then normal on the menu and games~~ nevermind, wasn't aware about the fan control. Also, L3+R2+X didn't work for me.

**Comment by ghost** [comment]
it starts silent of you turn off ps3 from here http://your.ps3ip/index.ps3

**Comment by emirtb07** [comment]
did anyone found a solution yet? have the same problem please help
