### ISSUE TITLE
NETISO Support for PS1/PSP games

### ISSUE THREAD

**Issue by john-clark** [aldostools/webMAN-MOD#121]
> "NETISO support for network loading and browsing of PS3 games in ISO and folder format, DVD videos in ISO format, Blu-ray movies in ISO format, PS1 and PSP games"

**Question** Does NETISO mean that the above mentioned formats should load from /net0?

_**TESTING**_ I have created /net0/PSPISO and /net0/PSXISO but iso files do not appear to show up. If I copy to /dev_hdd0/PSPISO or /dev_hdd0/PSXISO they appear to show up. I also created /net0/PS3ISO but it does not appear as if this folder is parsed either. I did put a PS3 ISO in /net0/GAMES and it did show up but it would not mount, webpage just says ERROR! which links to dev_bdvd. I did try to put a psp/psx ISO in the GAMES folder but they did NOT show up.

_**Comments:** When I started using ps3netsrv I expected to /net0 to mirror /dev_hdd0 file structure and functionality. When it did not, I attempted to create a share mapped to each type of folder. When that didn't work, I finally read the features, and found the above line and tested some more.  Also both PLAYSTATION ( ps1_netemu) are checked in the scan for content setup. To me it appears ONLY the PS3 games out of the GAMES folder work from the network as of current._

**Comment by billysun76** [comment]
I met the same problem, I used FERROX 4.82 v1.01 COBRA 7.55.

**Comment by Joonie86** [comment]
PS1 games can be loaded fine via nethost. PSP isn't supported.

**Comment by john-clark** [comment]
What version is working? As I stated ps1 is not working.

**Comment by Joonie86** [comment]
All my games loaded / tested on the latest one 1.47.20, 

When using nethost, you're supposed to use the root path so it would detect PSXISO and other folders.

If you use PSXISO as root path webMAN won't see the list of games inside PSXISO.

if only a specific one isn't working then try this build

https://github.com/aldostools/webMAN-MOD/files/3189805/fix.zip

You also need to make sure that you have the latest version of ps3netserv

https://github.com/aldostools/webMAN-MOD/tree/master/_Projects_/ps3netsrv/bins/Windows
