### ISSUE TITLE
How to remove prepNTFS?

### ISSUE THREAD

**Issue by malrio** [aldostools/webMAN-MOD#122]
How to remove prepNTFS?

When I installed multiman 4.82 I put prepNTFS 1.17. Now the NTFS does not need it, I wanted to remove multiman and prepNTFS and install IrisMan.

I have removed the prepNTFS 1.17 from the XMB but if you open multiman 4.82 it keeps reading the ntfs cache and I think some process has been left in the execution forever and it will not be removed. I tried installing the version prepNTFS 1.18 to see if it removed when reloading it and it does not leave, the NTFS always comes out in multiman.

Does IrisMan need prepNTFS for an HDD on NTFS?

**Comment by aldostools** [comment]
To remove prepNTFS 1.17 press /\ over the app on XMB and delete it.

IRISMAN does not need prepNTFS. Indeed prepNTFS uses the same NTFS library used by IRISMAN.

multiMAN always runs an internal copy of prepntfs.self every time that you launch the application.
To get rid of it, delete the self from /dev_hdd0/game/BLES80608/USRDIR
