### ISSUE TITLE
Start with - manual removal of CFW syscalls - and activate with GamePad

### ISSUE THREAD

**Issue by NoTrace-Kai** [aldostools/webMAN-MOD#125]
Hi there ...
i an new on webMAN-MOD and hoping you can answer my question.
When my PS3 is booting the cfw syscalls are deakticated and the history will be deleted,
so i can use my PS3 like a "OFW" one ... 
When i now want to use the Homebrew software, i have to unmark that point in the settings
an have to boot the ps3 again ... 
Is there a way to do this by a combination on the gamepad?
The way from the CFW to the OWF workes with R2+/\ but how can i do it on the other direction?
I hope you can understand what i mean ;)
CU and thanks a lot No.Trace

**Comment by aldostools** [comment]
By default, once the CFW syscalls are disabled, the system is unable to make changes (poke) to restore these syscalls. This behavior is to make harder to detect the usage of a CFW while you're online.

There is an option in /setup.p3 that let you keep enabled ps3mapi (and let restore the CFW syscalls) when R2+/\ is activated. However that option has more risks of banning when you go online because the syscall 8 remains active in the syscall table (which is detectable because that info is sent to Sony everytime that you log into PSN/SEN),

If you configure this option (PS3MAPI = ENABLED in /setup.ps3 under the section XMB/In-Game PAD SHORTCUTS), you can restore the syscalls using the following custom combo:

GET /syscall.ps3mapi?sce=1

**Comment by NoTrace-Kai** [comment]
Good morning and thanks a lot for the fast answer.
Then I will use the save way and disable the settings manually when i want to use homebrew software.

Can you perhaps explain the 3 settings from the dropdown menü?
Deactivate syscalls and delete history on boot. Offline: - deactivated / lock PSN / Games
I already do not understand what is the right choice.

CU

**Comment by aldostools** [comment]
When the option "Disable CFW syscalls and delete history files at system startup" is checked, the options in the menu mean: 

DISABLED = remove syscalls & history when the system starts

Lock PSN = remove history & block PSN/SEN servers when the system starts
(This option is intended is you don't plan to play online, but have the console connected to Internet)

GAME = do **not** remove syscalls/history & auto-deactivate Internet access when a game is launched

If you plan to play online, use webMAN MOD with PSNpatch plugin, and let PSNpatch manage the syscalls.

**Comment by NoTrace-Kai** [comment]
Hi there ...
Thank you very much for this information ...
Mostly i am using my ps3 for Amazon Video and Netflix, for Netflix there is no login to the PSN necessary.
But when i want to use the Amazon Video App i have to login to the PSN.
So for me it is the best setting, that the syscalls/history will be disable at the system start.
But can i setup PSNPactch in that way? I tried but did not fiend the right way ... PSNPatch always disabled everything ... also the PSN Network, perhaps i did not find the right way ;)
CU

**Comment by aldostools** [comment]
There are NoPSN versions of Amazon Video and Netflix:
http://www.psx-place.com/threads/collection-of-apps-patched-for-nopsn-access-quick-download-list.14565/

**Comment by NoTrace-Kai** [comment]
I tried some NoPSN Versions and for Netflix it is not necessary to be in the PSN.
Amazon released the Version 4.03 a few days ago, the 4.02 App wants to update anytime.

**Comment by aldostools** [comment]
Try requesting for an updated version in that thread.

Or try to patch the app yourself... Usually these apps only require to change to False some string like LoginPSN=True in the decrypted EBOOT.BIN, resign the patched EBOOT, repack the PKG and install it.

You can check how version 4.02 was patched and do the same in 4.03.

**Comment by NoTrace-Kai** [comment]
Thanks ... i will take a look ;)

**Comment by Joonie86** [comment]
Closing old issues that have no further feedback, Please try the latest wMM and report us.
