### ISSUE TITLE
dev_sd not being scanned

### ISSUE THREAD

**Issue by kingknuts** [aldostools/webMAN-MOD#126]
Hello!
I've been using WebMAN MOD 1.41.33 for a very long time and I tought that today is a good day to update to the latest webMAN MOD 1.47.06.

The surprise is that the games that I used to have in the xmb in dev_sd disappeared. I resetted everything, from formatting and erasing my PS3 hdd and sd, to update to the latest fimware. My findings are:
When I clic on refresh XML, my usb hard disk blinks, the internal hdd blinks but my sd card slot is just on... (Is not even trying to access it)

I downgraded back to WebMAN MOD 1.41.33 and everything is working like before, could you check it out what happens with the latest version?

Relevant info:
PS3 80 GB Backwards compatible with 4.82-1 Rebug CEX.
MicroSD XC 128Gb

If you need anything else please let me know.

Thank you!

**Comment by aldostools** [comment]
Please check in /setup.ps3 that the settings are correct and that /dev_sd is checked.
The settings file changed sometime ago and it looks like 1.41.33 is using the old settings file.

**Comment by kingknuts** [comment]
Yes it's checked

**Comment by kingknuts** [comment]
I can mount them manually through the web browser going into files -> dev_sd -> PS3ISO -> name.iso and clicking in the size of the file. But in scan content is checked /dev_sd and /dev_usb000 and /dev_usb006. When I click save and the PS3 reboots I do a refresh xml and rebooted again with no luck, only the games on the USB are being listed. Removing the USB hdd does no effect.
Thanks for your quick answer!

**Comment by aldostools** [comment]
Yes, /dev_sd is probably checked in 1.41.33. 
But when you install 1.47.06, is /dev_sd still checked? If it isn't, check it, **save** the settings and re-scan (e.g. using prepNTFS).

**Comment by kingknuts** [comment]
Yes, it's still checked if I format the sd card in ntfs seems to not make any difference I also tried exFat but the PS3 reformat it again to Fat32...

**Comment by aldostools** [comment]
The sd card is only accepted in FAT32 or NTFS formats. To scan it in NTFS use the latest release of prepNTFS.

The games in NTFS must be ISO stored in /PS3ISO; GAMES folders are not detected. In FAT32, it can be ISO stored in /PS3ISO or GAMES folders.

**Comment by kingknuts** [comment]
Should I put the isos inside GAMES?

/dev_sd/GAMES/PS3ISO/name.iso?

**Comment by aldostools** [comment]
No.

If the SD is NTFS, the isos should be in /dev_sd/PS3ISO like this:

/dev_sd/PS3ISO/name.iso

If the SD is FAT32, the PS3 games can be in folders inside /dev_sd/GAMES or in isos inside /dev_sd/PS3ISO

**Comment by kingknuts** [comment]
Sorry for the delay I started all over again, I just wiped the PS3 hdd and the sdcard is formatted inside the PS3. There's nothing plugged in excepting the sdcard and the ps controller. I installed webman keeping L1 pressed until the PS3 rebooted, I head over webman mod settings and select /dev_sd only and saved settings, now it refreshes the xml file and then rebooted. No luck :(

**Comment by aldostools** [comment]
Thanks for the feedback. I will check the code again tonight when I return to my home. However, I cannot promise you any fix due I have 25xx console (which doesn't support dev_sd).

**Comment by kingknuts** [comment]
All right, take your time!! And of course, thank you!!

**Comment by kingknuts** [comment]
I installed all the webman versions to dig where it stops working. The Webman mod v1.43.18 is the latest webman mod working. When I update to webman 1.43.20 the dev_sd is unchecked when you check it and refresh the xml the things stop working. Hope that hint helps.
Cheers!

**Comment by aldostools** [comment]
Please try installing this 'test' build (it still says 1.47.06)
https://www.sendspace.com/file/g9qsyl

Go to /setup.ps3, check /dev_sd again, save and re-scan the content again.
I'll upload the changes if you confirm me that they fix your issue.

**Comment by kingknuts** [comment]
You did it!!! It's working again!!! Thank you very much!!!

**Comment by aldostools** [comment]
Thanks for your feedback.

**Comment by ZavEntNet** [comment]
can you fix it again? my 512gb SDXC microSD is not working on webman mod on my 60gb CECHA01 PS3

**Comment by ZavEntNet** [comment]
> Please check in /setup.ps3 that the settings are correct and that /dev_sd is checked.
> The settings file changed sometime ago and it looks like 1.41.33 is using the old settings file 

Can You help me with this in 2024?

**Comment by ZavEntNet** [comment]
> Please try installing this 'test' build (it still says 1.47.06)
> https://www.sendspace.com/file/g9qsyl
> 
> Go to /setup.ps3, check /dev_sd again, save and re-scan the content again.
> I'll upload the changes if you confirm me that they fix your issue.
> 

Can You upload it again please ?

**Comment by aldostools** [comment]
That version is too old and I don't have it available.

Use the latest version from [releases](https://github.com/aldostools/webMAN-MOD/releases), go to [/setup.ps3](https://github.com/aldostools/webMAN-MOD/wiki/Setup-Options) expand the section "Scan for Content", check the option /dev_sd  and save the settings. Then click on Refresh or use SELECT+L3 to re-scan the games.

Make sure that the SD card is inserted before go to /setup.ps3. If the SD card is not inserted, the option will not be shown.
MS and CF slots also need to be mounted for these option appear in /setup.ps3

**Comment by shnyaps** [comment]
Try to reformat sd card with ps3(in system settings). After this I copied games to se card and was able to scan games on sd

**Comment by aldostools** [comment]
Verify that dev_sd is checked in content scanning section of /setup.ps3

Also the SD card must be formatted in FAT32

**Comment by shnyaps** [comment]
> Verify that dev_sd is checked in content scanning section of /setup.ps3
> 
> Also the SD card must be formatted in FAT32

Sd card should be checked, yep. But I saw sd card games in list only after formatting by ps3

**Comment by aldostools** [comment]
> Sd card should be checked, yep. But I saw sd card games in list only after formatting by ps3

True. /dev_sd only appears in the list of devices in /setup.ps3 only if the SD card is inserted and formatted in FAT32.

Same for /dev_ms and /dev_cf

**Comment by shnyaps** [comment]
I have a question: webman mod starts ps1 games directly from sd card, but ps2 games instead of start begin to copy to hdd. Is it possibke to start ps2 games from sd?

**Comment by aldostools** [comment]
No. ps2_netemu was implemented by Sony to play specifically PS2 Classics from PSN Store.
As these games are installed only on the internal HDD, they removed the support for external storage devices in the emulator (probably to reduce the memory footprint of the emulator resulting in increased limitations to use other sources).

Although ps2emu and ps2_gxemu supports USB devices the Cobra payload that adds ISO support to PS2 emulators was coded with ps2_netemu in mind.

Maybe in the future the payload could be adapted to support USB, but this requires developers with PS3 phat consoles, the time and knowledge to implement it. The chances that this occurs is very low due the reduced number of users that could be benefited, the time that it may require and that PS3 already has reached the end of its lifecycle.

**Comment by ZavEntNet** [comment]
Will PS2ISOs work over USB 2.0 Speed on CECHA01 CECHB01 CECHE01 CECHC02 PS3 Models ???

**Comment by aldostools** [comment]
> Will PS2ISOs work over USB 2.0 Speed on CECHA01 CECHB01 CECHE01 CECHC02 PS3 Models ???

webMAN MOD scan the PS2ISOs stored on USB devices, but they are copied to /dev_hdd0/PS2ISO when they are mounted.

I don't have one of these phat models to confirm if the PS2ISO can be mounted directly from USB.
However there are reports that Open PS2 Loader (OPL) can launch PS2 games from USB on these PS3 models.

EDIT: Now I remember that Cobra has a check in common.c that only accepts PS2ISOs from /dev_hdd0
![image](https://github.com/user-attachments/assets/6b86507b-f295-4721-b393-fa44b3188897)

**Comment by ZavEntNet** [comment]
I would like some day webman mod and OPL Developers make CECHA CECHB enable The HDD Mode on OPL

**Comment by ZavEntNet** [comment]
I mean I need GSM 480p HDTV Options, PADEMU etc on PS3 with faster charging times
