### ISSUE TITLE
"No SND0.AT3" not working with "mount last played game"

### ISSUE THREAD

**Issue by 444nonymous** [aldostools/webMAN-MOD#127]
If webman auto-mounts last played game at boot, the SND0.AT3 file is playing.

**Comment by aldostools** [comment]
At this moment I don't have access to PS3, but can test if this build fixes the issue
https://www.sendspace.com/file/w1hbir

**Comment by 444nonymous** [comment]
I tested it and it does not fix it.

**Comment by aldostools** [comment]
Thank you for your feedback. Unfortunately after more than 3 hours testing I couldn't find the cause of this bug. The code is logically correct. So there should be some additional condition in the PS3 that is preventing the code to work properly.

**Comment by Joonie86** [comment]
Closing old issues that have no further feedback, Please try the latest wMM and report us.
