### ISSUE TITLE
Unable to connect via FTP on linux

### ISSUE THREAD

**Issue by fennectech** [aldostools/webMAN-MOD#129]
Filezilla works fine but when i connect with the ftp library i get a blank directory   
![image](https://user-images.githubusercontent.com/11953665/36087974-c513b498-0f9a-11e8-9c91-242df107afe2.png)

Here is the source tree for the application im using to connect if it helps

https://github.com/mate-desktop/caja

**Comment by m132** [comment]
FileZilla uses `MLSD` command to list files, and it works flawlessly. GVFS (used by Caja) on the other hand uses `LIST`, and when it detects an Unix server, adds an `-a` flag [to](https://github.com/GNOME/gvfs/blob/886f29d8ac5a97b39dbfaaffc579bbd5ca0dd2a2/daemon/gvfsbackendftp.c#L246) [it](https://github.com/GNOME/gvfs/blob/886f29d8ac5a97b39dbfaaffc579bbd5ca0dd2a2/daemon/gvfsftpdircache.c#L820).

webMAN's FTP daemon [pretends to run on Unix](https://github.com/aldostools/webMAN-MOD/blob/0ff0477e0606b9f74638362d662c475fdd9a18a0/include/ftp.h#L1030), but it's LIST implementation [is quite hackish and it doesn't expect -a flag to be used alone](https://github.com/aldostools/webMAN-MOD/blob/0ff0477e0606b9f74638362d662c475fdd9a18a0/include/ftp.h#L553), and so it mistakes it for a directory name. As there's no directory named `-a`, it silently fails, returning 150 OK along with empty file list.

The quickest and dirtiest fix would be to avoid using UNIX in `SYST` output, a properly done `LIST` implementation would be nice though...

EDIT: Actually some servers interpret `-a` just like `-la`, so a simple `|| IS(param, "-a")` would be enough

**Comment by barnaba** [comment]
It also doesn't seem to respond well to `LIST -aL` that gFTP uses.

My understanding is "UNIX Type: L8" isn't really promising any additional capabilities and it's something that people started using to stop clients from expecting system capabilities based on SYST response.

In case of gFTP they solve it in FAQ 2.1.:

> If the server is complaining about the -L option, go under FTP->Options->FTP and disable resolve remote symlinks. If it is complaining about the -a option, go to FTP->Options->General and disable show hidden files.

I've tested it and it makes gFTP compatible with webMAN's FTP.

Nautilus sends -a even if "Show Hidden Files" is disabled.

If you're experiencing those issues I recommend to look for equivalent options in your ftp client and see if disabling them helps.

**Comment by aldostools** [comment]
I have made a small change to address the issue above. Here is the SRC and the compiled packages.
https://www.sendspace.com/file/mrwt2x

**Comment by Joonie86** [comment]
no further feedback received
