### ISSUE TITLE
bugs in version 1.41.09

### ISSUE THREAD

**Issue by vobasf** [aldostools/webMAN-MOD#13]
Hi Aldo,

After updating webman mod to 1.41.09, all settings are blank. Could you fix this issue?

I find that you are an enthusiastic programmer, and update webman mod very frequently. Could you add an update feature in webman mod? You can add two options auto check update when ps3 start or manual check update. The update files can be hosted on github.

Thanks.

**Comment by vobasf** [comment]
update:

I installed version 1.41.08 and find the seetings are all unchecked and cannot be saved as well.

**Comment by aldostools** [comment]
I have been trying to replicate the about check boxes unchecked, but they
are working fine on my end.
Could you indicate the "edition" of webMAN MOD that you use (rebug,
noncobra, english, ps3mapi, etc.), the CFW, the web browser?

Also try deleting manually the settings file: /dev_hdd0/tmp/wmconfig.bin

Regarding the feature request: There are not plans to add auto-update. A
link to download the latest installer from Brewology is provided in
/setup.ps3




Aldo Vargas
http://www.aldostools.org

**Comment by vobasf** [comment]
Hi Aldo,

I'm using habib cobra 4.66 1.01, psnpatch 4.66.32, and webman mod 1.41.08/1.41.09. I have tried deleting "/dev_hdd0/tmp/wmconfig.bin", it doesn't work. Could you trying updating webman mod using the updater on "http://store.brewology.com/ahomebrew.php?brewid=257" and see if you can repeat the problem? 

I have tried uninstalling  and installing webman mod using psnpatch, the settings are fine and it's webman mod v 1.41.06. 

Thanks.

**Comment by aldostools** [comment]
I installed webMAN MOD completely (deleted all the related files) and installed with the updater 1.41.09 as you suggested, and still everything is working fine. Maybe I should be doing something wrong or my CFW 4.46 is really bad because it doesn't have issues.

**Comment by vobasf** [comment]
I think habib cobra 4.66 and psnpatch 4.66.32 May reproduce this issue and the previous webman mod versions are OK.

**Comment by aldostools** [comment]
Please try installing a different edition: webftp_server_lite.sprx or
webftp_server_ps3mapi.sprx.

I noticed in a picture of an user that /dev_usb000 is shown corrupted,
but that variable is not being modified in the code.. So I think it
could be that the sprx is corrupted or maybe the other plugins are
interferring the memory.

On 1/19/15, vobasf <notifications@github.com> wrote:
> I think habib cobra 4.66 and psnpatch 4.66.32 May reproduce this issue and
> the previous webman mod versions are OK.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/aldostools/webMAN-MOD/issues/13#issuecomment-70545086


-- 
Aldo Vargas
http://www.aldostools.org

**Comment by gunner007cd** [comment]
1. This happens upgrading for me from any version of webMAN mod < 1.41.09 (previously came from 1.41.06)
2. The big error is what you just noticed. (Under SCAN THESE DEVICES) I get the "plore/icon/icon_wm_eject.p" and "con._wn_eject.p" This is on an english version as well. 
3. Everything remains unchecked no matter how many times you check, save, and reboot/power the system.
4. If you downgrade (without deleting wmconfig) webMAN mod reverts and works properly and all check boxes come back.
5. It's almost like there's a parsing error somewhere. I'll try to delete everything and start fresh on 1.41.09

For reference:

PS3 on Habib 4.66 Cobra (happens on Rebug 4.65.2 as well) - no MAPI/TMAPI. Only program loaded is webmanmod. Note that downgrading to 1.41.08 and lower fixes the issue.

EDIT:

Used WEBFTP_SERVER.SPRX = FAILED
Used: WEBFTP_SERVER_ENGLISH.SPRX = FAIELED
Used: WEBFTP_SERVER_LITE.SPRX = FAILED

Deleted WMCONFIG.BIN -< Launch webMAN mod 1.41.09 -> The "icon corruption still appears" -> make changes -> reboot = Still have corruption is USB listing and any check boxes are gone- however any data in text boxes survived.

**Comment by aldostools** [comment]
Please try with this build and report back if the issue still persists:
http://aldostools.org/temp/test/webMAN_MOD_1.41.10_Updater.pkg


Aldo Vargas
http://www.aldostools.org

**Comment by gunner007cd** [comment]
Is this one still a rebug build? This one locks up the PS3 on boot (Habib 4.66)

**Comment by aldostools** [comment]
It seems that the issue is finally fixed. Thanks to Joonie that helped me to find the cause.

Please download the new PKG from:
http://store.brewology.com/ahomebrew.php?brewid=257

**Comment by gunner007cd** [comment]
Still having issues with the new .10 release.

.10 on upgrade from .08 - reboot freezes the system. Rebuilt database and remove traces of webman and plugins.

Installed .10 after deleting wmconfig and system booted okay first time. Make changes and save->restart. System boots okay but didn't detect network games. Refresh HTML/XML causes system to hard lock. Next reboot freezes.
