### ISSUE TITLE
XMB 

### ISSUE THREAD

**Issue by DEX357** [aldostools/webMAN-MOD#130]
Aldo the new update has broken xmb, the functions restart, disable, Vsh menu, unmount, and other functions from xmb do not work.

**Comment by aldostools** [comment]
Thanks for your feedback... I forgot to update the XMB proxy in webMAN.xml.

The packages are updated.. So please, download and install the PKG again.

**Comment by DEX357** [comment]
Aldo still something, they do not respond to switching on

**Comment by aldostools** [comment]
Which specific function is not responding? All the functions that I tested worked... BTW I also added a new option "Load sLaunch"... Make sure that you have it.

Try downloading and re-installing the latest PKG again just to be sure that you have the latest version (I uploaded 2-3 revisions of the updater with the same version).

**Comment by DEX357** [comment]
I found the reason, my Polish translation works on version 1.47.06 but on 07 no longer :(
even though the language files do not differ between .06 and .07

**Comment by aldostools** [comment]
Replace all occurrences of **eula_cddb_plugin** in your XML with **idle_plugin**

Like this:
https://github.com/aldostools/webMAN-MOD/commit/36ef007ed57c9a949c1bff52a69073a70a2ab892#diff-8a31415c7b6e329b6b11327d468de03a

**Comment by DEX357** [comment]
Thanks Aldo, I noticed and rewrote it.
