### ISSUE TITLE
CEXFERROX482_100.PUP

### ISSUE THREAD

**Issue by ilwsm** [aldostools/webMAN-MOD#131]
How install webMAN MOD 1.47.07 on this firmware CEXFERROX482_100.PUP/ is it possible?

**Comment by ilwsm** [comment]
please help

**Comment by aldostools** [comment]
To use webMAN MOD on CFW without Cobra payload, you must use MAMBA/PRX Loader.

However, my recommendation to you is to install a CFW __with Cobra__ payload included, like **[Rebug 4.82.2](https://rebug.me/official-rebug-4-82-2-cobra-7-55-lite-toolbox-2-02-15_rev1-mar-19th-2018/)** or  [CEXFERROX482COBRA755_101.PUP](https://mega.nz/#!n4UFDLwD!v-pymwI-LRCUEkyKlyFm12Y1BjOZ4Cc1fAnOnRTHVbc)

On these CFW, just install the PKG found in the release section.

**Comment by ilwsm** [comment]
Thanks
But your links:
https://github.com/NzV/PRX_Loader
https://github.com/NzV/MAMBA_PRX_Loader
doesn't work.

Can you give appropriate links, exactly for my 4.82 CFW?

**Comment by aldostools** [comment]
**NzV** removed his projects from github.

You can find the PKG of MAMBA/PRX Loader on brewology. But I insist you that you should use one of the CFW in the links that I already provided in my post above.

**Comment by ilwsm** [comment]
I can't install CFW with cobra support. Thats mean i cannot use webman on my firmware anyway?
Sorry for my insistence. 
I'm try this mamba loader (newest loader on brewology site)
http://store.brewology.com/ahomebrew.php?brewid=287
But is support  from CFW 4.46 to 4.81 only. My CFW is 4.82. 
After install, run this loader and restart ps3 - ps3 is freezes. 

I repeat my question:
I cannot use webman on my firmware anyway?
Or you can give me newest mamba loader?

**Comment by aldostools** [comment]
As I already explained you should use a CFW with Cobra or MAMBA/PSX Loader.
As MAMBA/PSX Loader is not updated for 4.82. You should wait until someone update it. That's why I insisted to install a CFW with Cobra.

You can try loading webMAN using IRISMAN. If I recall correcly I think I added the option to load webMAN automatically if it is found in /dev_hdd0/plugin/webftp_server.sprx
