### ISSUE TITLE
Loading games from External Hard Drive using webman mod

### ISSUE THREAD

**Issue by spotanjo3** [aldostools/webMAN-MOD#133]
All my games are in ISO's and there are 82 games.

When I used the latest version of WebMAN MOD and scanned it but I got only 55 games showing up.

I had old version of WebMAN MOD and scanned all games just fine. A newer version has a bug ? I am confused.

**Comment by aldostools** [comment]
The number of games that appear in the game list depends of the free memory available at the moment of the scan and the memory profile selected in /setup.ps3

1- Verify that your memory profile is set to standard or max in /setup.ps3
(If it is not properly set, make the change, save and restart the console)
2- Re-scan from XMB after a while after a restart (to make sure that all the starting processes have completed and the memory usage is low)
3- Also verify that the path of the games have not changed and that they can be accessed by the PS3.

If the list is still short, do a re-scan at least one more time.

**Comment by Joonie86** [comment]
Closing old issues that have no further feedback, Please try the latest wMM and report us.
