### ISSUE TITLE
prepNTFS 1.19

### ISSUE THREAD

**Issue by RandQalan** [aldostools/webMAN-MOD#134]
Has the wrong version # when installed or is the wrong version in pkg?

**Comment by aldostools** [comment]
Thank you for the report. 
When I updated the makefile with 1.19, I forgot to update the version in PARAM.SFO in pkgfiles

I've updated prepNTFS_1.19.pkg in the release section. I'll update the git later.

**Comment by RandQalan** [comment]
Ok figured you did not notice it.

**Comment by nsiai** [comment]
cool
