### ISSUE TITLE
option or shortcut to change between 60Hz and 50Hz

### ISSUE THREAD

**Issue by realfinder** [aldostools/webMAN-MOD#136]
in PAL consoles if you want to play some NTSC PS1 games especially with CRT TV it will be slower cuz it will play as 50hz PAL

if you use rebug dex to change console to USA you will note some PAL games will not work with 480 and 60Hz

I find this https://www.maxconsole.com/threads/enabling-60hz-output-on-pal-ps3-consoles.24695/

from the 2nd way in the link

>  2. Modify ONE setting in xRegistry. Set /setting/display/tvSystem to 0. Your console will be in NTSC mode but that's it. No region change, just a display mode. I don't remember if it works for Unreal Engine games.

can webMAN MOD do this by an option or shortcut combo?

**Comment by aldostools** [comment]
I understand that this issue is in [Cobra](https://github.com/Joonie86/COBRA-7.3). webMAN MOD only calls the apis to mount the game.

**Comment by realfinder** [comment]
it's in how PS3 work not in Cobra

http://www.psdevwiki.com/ps3/XRegistry.sys#xRegistry.sys_access_from_gameOS

**Comment by Joonie86** [comment]
The refresh rate swap is automatically done by COBRA payload. closing this issue since no further feedback was received.
