### ISSUE TITLE
XMB options hang console except browser menu

### ISSUE THREAD

**Issue by Haker120** [aldostools/webMAN-MOD#138]
I have the newest webMAN, my console is DEX on COK-001 with REBUG D-REX 4.82.1, mounting games and choosing options in xmb though games bookmark doesn't work, when I'm trying, my console hangs. In other aplications everything is fine.

**Comment by aldostools** [comment]
A possible cause of the freeze is when the version of webMAN MOD uses a proxy different to the proxy plugin specified in the XML.

Please try downloading the updater again from "releases" and re-install the PKG.
Alternatively you can install this test build https://www.sendspace.com/file/w6wduo

Use SELECT+L3 to scan the content and rebuild the XML.

**Comment by Haker120** [comment]
Thank you, I've tested test build and I've reinstaled the newest one, difference is one, console doesn't hang but I'm losing control while console tries to load a game from XMB and console tries to load something. From browser it loads correctly.

**Comment by Haker120** [comment]
I didn't manage to fix it but my DEX is an collectors item so not really a problem, however thank you for trying to help. I'm using webMAN to set up fan control but lately it just looks nice in my collection. :)

**Comment by Joonie86** [comment]
Closing old issues that have no further feedback, Please try the latest wMM and report us.
