### ISSUE TITLE
FTP server broken, lists folders as empty files

### ISSUE THREAD

**Issue by 444nonymous** [aldostools/webMAN-MOD#14]
I don't know if this related to https://github.com/aldostools/webMAN-MOD/issues/8 but this never happened to me before until webMAN MOD 1.43.35. I'm using latest Rebug.

The FTP server is broken for me. Even before setting offline option to Game in setup.ps3, so this could be unrelated. I can access the FTP server, but folders are listed as empty files. I cannot browse up or down any directory. Never happened this to me with any webman version.

![clipboard-1](https://cloud.githubusercontent.com/assets/20845683/18548421/de7fad66-7b48-11e6-9c05-938e8904707b.jpg)

Thanks!

**Comment by aldostools** [comment]
Thank you for your feedback.

Could you download & install the package currently available in github, just to be sure you're using the same version that I tested?
https://github.com/aldostools/webMAN-MOD/releases/tag/1.43.35

Also, please, try with a different FTP client, to check if it is an issue of the client not recognizing the file listing format returned by the server.

If the files are listed fine with an earlier version of webMAN MOD, please indicate me the version that you tested to compare the changes between the versions.

In my test the size of the files are listed properly using ftp.exe of Windows and ftp://ip-address from Windows Explorer.

If the problem persists, please let me know which FTP client you're using to test with that client.

**Comment by 444nonymous** [comment]
Yes, I'm using that version downloaded from here. I was using the default one that came with latest Rebug and updated to 1.43.35 directly. I tried some other versions before. Never had the problem.

From a web browser I can't connect, I get "425 error" https://support.microsoft.com/en-us/kb/129395
From an FTP client: active, pasive, auto, etc. Same problem, I can connect but I get empty files.

I have checked my firewall logs, everything is fine, no ports blocked, no alerts of blocking  connections on my side. Same PC, router and configuration as usual, I did not change anything.

> FTP client log:
> [19:04:54] Resolving address for ps3.lan
> [19:04:54] Resolved host as 10.20.30.107
> [19:04:54] Connecting to ps3.lan, port 21 (#1)
> [19:04:54] Connected to server, waiting for response...
> [19:04:54] 220-VSH ftpd
> [19:04:54] 220 webMAN ftpd 1.43.35 MOD
> [19:04:54] USER anonymous
> [19:04:54] 331 OK
> [19:04:54] PASS (hidden)
> [19:04:54] 230 OK
> [19:04:54] SYST
> [19:04:54] 215 UNIX Type: L8
> [19:04:54] FEAT
> [19:04:54] 211-Ext:
> [19:04:54]  SIZE
> [19:04:54]  MDTM
> [19:04:54]  PORT
> [19:04:54]  CDUP
> [19:04:54]  ABOR
> [19:04:54]  REST STREAM
> [19:04:54]  PASV
> [19:04:54]  LIST
> [19:04:54]  MLSD
> [19:04:54]  MLST type_;size_;modify_;UNIX.mode_;UNIX.uid_;UNIX.gid_;
> [19:04:54] 211 End
> [19:04:54] PWD
> [19:04:54] 257 "/"
> [19:04:54] TYPE A
> [19:04:54] 200 TYPE OK
> [19:04:54] PASV
> [19:04:54] 227 Entering Passive Mode (10,20,30,107,156,225)
> [19:04:54] LIST -la
> [19:04:54] 150 OK
> [19:04:55] 226 [/] [CPU: 69 °C | RSX: 73 °C]
> [19:04:55] Transfer: [346 bytes | 0,188 secs | 1,797 KB/s]

**Comment by aldostools** [comment]
I've made some corrections to the FTP server. Now the directory listing is show properly on the browsers: Chrome, Microsoft Edge and Internet Explorer. It also shows properly in the FTP client of Windows Explorer and ftp.exe of Windows 10.

On Mozilla Firefox you will receive an error 425 due the browser is trying to list the folder before setting the port for data transfer. Apparently it is a bug in the Firefox.

You can download the new build from
https://github.com/aldostools/webMAN-MOD/releases/edit/1.43.35

**Comment by 444nonymous** [comment]
Fixed, it works as usual now.

**Comment by aldostools** [comment]
Thank you for your confirmation.
