### ISSUE TITLE
psn lock

### ISSUE THREAD

**Issue by DEX357** [aldostools/webMAN-MOD#141]
I've already reported it on psx place but now I thought I would be reporting this problem more officially, but you probably already do it, PSN Lock corrupts savegame :( .

**Comment by aldostools** [comment]
I have insisted that users should use PSNpatch or SEN Enabler if plan to access PSN/SEN.

**Comment by DEX357** [comment]
I know, I understand you but it does not change the fact that such a function is working partially correctly, can you fix it? :) I prefer wmm than psnpatch/senenebler. I have not seen anywhere reported about this problem, users probably are not aware of it.

**Comment by alavry** [comment]
why allow the user to use unsupported features?

**Comment by aldostools** [comment]
Because some features that don't work for some users, they work for others.

Some users can contribute to the project fixing what they find wrong... unfortunately complains are more often than contributions.

**Comment by DEX357** [comment]
Aldo, but I do not know what is going on and why this function does not work well is wrong with PSN Lock, because manually locking psn from level lv1/lv2 with wmm makes it impossible to log in to psn and does not spoil save, manual work fine. This message can and help fix it.
This function work fine:
Query class="type:x-xmb/folder-pixmap" key="webman_block_psn_link" src="#seg_webman_block_psn"
When you try to log in to psn an error pops up, the same is in games, but save are ok and trophies also work, maybe something is psn lock wrong, but switching between syscalls of / on works, block psn / free psn works with enabled and syscalls disabled. Some games turn themselves off and save courappted on syscalls ON.

**Comment by alavry** [comment]
@aldostools i have no complaints, simply an observer

**Comment by DEX357** [comment]
Also this function blocks access to trophies even though I'm not logged in to psn, in a Dragon Ball Z: Battle of Z when game get trophies at startup, game get an error and it automatically turns off to xmb.

**Comment by ghost** [comment]
Error number?

**Comment by DEX357** [comment]
Without a error, game simply said that there is no access to the treofeas and it will be closed

**Comment by Joonie86** [comment]
Closing old issues that have no further feedback, Please try the latest wMM and report us.
