### ISSUE TITLE
PS3NetServ: Network shared games sometimes lag or crash

### ISSUE THREAD

**Issue by Syst3mSh0ck** [aldostools/webMAN-MOD#142]
Hi Aldo, there seems to be a problem with games shared over Gigabit Ethernet because FMVs and cutscenes are sometimes lagging or crashing forcing an lv2 reset. Games impacted are God of War 3, The Last of Us, Uncharted (all three), FFXIII (all three), Tekken Tag Tournament 2, and pretty much anything else that pushes the console hard. Temps are normal however PSN ports like Jak & Daxter HD Collection are impacted too. Putting the game on the local HDD eliminates the problem. No difference between FAT/NTFS with small/large cluster sizes either. Perhaps there is a thread/buffer scaling issue somewhere.

Rebug 4.82.2 REX / Toolbox 2.02.16 / Cobra 7.55 / webMAN MOD 1.47.08 / PS3NetServ 20170310 on Win8.1 x64

Thanks for all the hard work :+1:

**Comment by Syst3mSh0ck** [comment]
I root caused this to down to heavy LAN traffic and by extension bridge congestion so I setup some DSCP/QoS traffic rules for PS3NetServ in my Firewall and the performance/stability issues are now resolved. All PS3 folder rips are indexed and booting over network absolutely fine however where multiMAN shows all 50 games under the /GAMES directory - Multiman 04.82.00 only shows 1 game which is Wipeout HD. Nothing is mounted.

If I press triangle and check File Manager it shows the path as having /***PS3***/ where the root of my network share should be and the folder is empty. If I press Play the game is mounted and plays correctly. Network shares including the correct folders ie GAMES/PS2ISO/PSXISO etc are visible in mmCM and webMAN Mod just not Multiman.

Any idea why the other 49 games are not seen by Multiman? For what it's worth I have tried clearing the cache and rescanning but no dice. Any help would be appreciated even though webMAN Mod is working fine. Thanks.

**Comment by Syst3mSh0ck** [comment]
I've read that webMAN MOD and Multiman conflict with eachother. Can someone tell me what the "sMAN GUI" option in webMAN Mod setup page does please? I thought webMAN MOD and sMAN were two different plugins and that you had to remove webftp_server from the plugins file because you shouldn't run them side by side? Thanks.

**Comment by aldostools** [comment]
AFAIK webMAN MOD and Multiman do not have any known conflict. Indeed multiMAN can be a complement (e.g. for updating games, download covers, backup games, create ISOs, etc.)

However sMAN and webMAN MOD have conflict, because both plugins perform practically the same tasks in similar way (although internally both are completely different). Indeed webMAN MOD was based in sMAN (which is the new name of the original webMAN vanilla).

webMAN MOD by default uses the original black & white GUI from webMAN vanilla. The option "sMAN GUI" mimics the new GUI of sMAN, which is more colorful and looks more modern.

**Comment by Joonie86** [comment]
Closing old issues that have no further feedback, Please try the latest wMM and report us.
