### ISSUE TITLE
Fan speed for disc-based PS2 games

### ISSUE THREAD

**Issue by nonijod** [aldostools/webMAN-MOD#144]
If I play a disc-based PS2 game on my semi-BC PS3 the fan speed doesn't autoset and just stays at a value it was at launch, resulting in the PS3 overheating and ramping the fan speed to 100% during gameplay. Isos from HDD don't have this problem and the fan speed gets set correctly before launch. On a side note, could it be possible to switch to SYSCON for fan control before launching a PS2 game in order to still have automatic fan speed control instead of just having it set to a fixed value?

**Comment by aldostools** [comment]
When the PS2 emulator is launched, VSH and all VSH plugins are unloaded from memory. Therefore, the fan cannot be controlled dynamically by webMAN. So, to bypass this restriction, when a PS2 game is mounted by webMAN, a fixed fan speed is used (the value can be set to your preference in /setup.ps3). I recommend to use 40% or higher.

Currently only a fixed value is allowed for PS2 games, unless you set the fan controller to SYSCON manually. All other games (PS3, PSX, PSP, etc.) can be controlled dynamically.

**Comment by nonijod** [comment]
>when a PS2 game is mounted by webMAN, a fixed fan speed is used

That's the problem. While it works for games launched from HDD, it doesn't work for games launched from DVD. The fan speed isn't set and stays at whatever it is at launch until it overheats.

**Comment by aldostools** [comment]
That occurs because the game is mounted externally (not through the plugin). So the plugin doesn't have control of what's happening. 

Your current options are: disable the fan control manually (set to SYSCON) before launch your DVD game or convert your PS2 DVD games to ISO and mount them through webMAN.

**Comment by aldostools** [comment]
Currently I don't have a PS3 available. If you are able to compile webMAN MOD, you can test if this **fancontrol2.h** sets the fixed fan speed when a physical CD/DVD is inserted. 

https://pastebin.com/XbsZbby7

**Comment by aldostools** [comment]
I have compiled a test build that sets the PS2 mode when a physical PS2 disc is inserted.
https://www.sendspace.com/file/jdeas2

Your feedback is appreciated.

**Comment by nonijod** [comment]
Fan speed changes for original games but doesn't for burnt and the fan speed stays at the PS2 mode levels as long as the disc is inside. Bit of an inconvenience as it means that I have to eject the disc after quitting the game if I want auto fan control for PS3 games but certainly a step forward.

**Comment by aldostools** [comment]
Thank you for your feedback.
I have compiled a new test build. I hope it behaves better with burnt games. It also should restore the fan control to auto when a different media is mounted (e.g a PS3 game).
https://www.sendspace.com/file/dmnhhw

PS. I'm going to sleep now ;)

**Comment by nonijod** [comment]
Switching between DVD PS2 game and PS3 pkg game -> fan speed stays at PS2 level
Switching between original CD PS2 game and PS3 pkg game -> fan speed changes properly
Switching between burnt CD PS2 game and PS3 pkg game -> fan speed doesn't change to PS2 mode again after a PS3 game has been played
Also found out that burnt CD PS2 games don't seem to work and exit to XMB but that's another issue entirely.

**Comment by aldostools** [comment]
Thank you for your feedback. webMAN MOD currently only monitors BDVD games (ISO or JB). It doesn't detect when NPDRM games (PKG) are launched.

I think I could make it switch back from PS2 mode to auto fan speed if "in-game" is detected.
I'll try it tonight when I return to my home. If it works I'll post a new test pkg.

**Comment by LouisGarry** [comment]
Sorry aldostool if out of the topic, does it allow auto unmount (JB game) if NPDRM games are launched?
We can not play CFW2OFW games (blank/hang) if there is mounting JB game (JB game only, not happen in games ISO PS3, PS2 and PSP). Thank you.

**Comment by aldostools** [comment]
No. As I said, webMAN does not monitor if NPDRM games are being played.

A quick workaround is to press **SELECT+O** to unmount any game currently mounted before start any NPDRM game.

**Comment by aldostools** [comment]
Ok, this test build switches back from PS2 mode to auto fan speed when "in-game" is detected and switch back to PS2 mode if the PS2 disc remains inserted.

Link: https://www.sendspace.com/file/w17btx

**Comment by nonijod** [comment]
After launching an NPDRM game the fan goes Auto-PS2-Auto-PS2 before finally settling on Auto.

**Comment by aldostools** [comment]
Thank you for your feedback. I made a small change in the release version
https://github.com/aldostools/webMAN-MOD/releases/tag/1.47.09

I hope it fixes the auto-ps2-auto-ps2.. if not, then it will have to stay like that ;)

Closing.

**Comment by Nuck-TH** [comment]
For me it still shows "PS2 Mode: [speed of PS2 mode setting]%" just before rebooting into PS2 mode, even through i have fan control set on Auto(since webman can't work in BC mode - more logical that it should switch to SYSCON, because it is auto). Console is soft-EE BC - CECHC08.
Can there be choice to either select fixed speed or SYSCON(or follow logic i pointed to above)? Because i think that just fixed speed is either loud or dangerous.

**Comment by Nuck-TH** [comment]
also fan control seems to fall back to syscon with physical disc
