### ISSUE TITLE
Irisman fan control with webman installed

### ISSUE THREAD

**Issue by tirosala** [aldostools/webMAN-MOD#145]
When webman-mod 1.47.09 is installed (full or lite) the irisman 4.82.1 don't turn on the fan control.
I enable the irisman fan control but when i reboot the ps3, the fan control is always disabled in irisman, but if the webman is not installed the irisman works fine.
I also disabled the dynamic fan control in webman but the results are the same.
I have installed 4.82.2 Rebug DEX in my ps3.
Hope you can help me Aldo, Thanks

**Comment by aldostools** [comment]
If IRISMAN detects webMAN running, it doesn't enable its internal fan control, because it gives priority to webMAN's fan control to avoid conflict between 2 processes trying to control the fan.

**Comment by tirosala** [comment]
I understand now, how can i use the irisman fan control to give the priority and disable the webman fan control? 
I like a lot the irisman and webman two great tools, but thats the only thing that annoys me is the fan control.
It's possible to have the two tools installed and use the fan  control of irisman instead of webman? 
Because in 4.76 rebug dex with webman and irisman it works fine, the irisman controls the fan

**Comment by aldostools** [comment]
The fan control of IRISMAN is the plugin /dev_hdd0/game/IRISMAN00/sprx_sm

You can add it to boot_plugins.txt and set webMAN fan mode to syscon.

**Comment by tirosala** [comment]
I added "/dev_hdd0/game/IRISMAN00/sprx_sm" to the boot_plugins.txt and changed the webman fan mode to syscon, but it don't worked
The sprx_sm should it be sm.sprx?

**Comment by tirosala** [comment]
I tried so many things and the irisman sprx fan control dont work, can you help me?

**Comment by Joonie86** [comment]
IRISMAN is no longer supported. closing this issue.
