### ISSUE TITLE
1.47.09 -- will not play mounted DVD ISO at all (stays on XMB)

### ISSUE THREAD

**Issue by lordzardos** [aldostools/webMAN-MOD#150]
1.47.09 will mount a DVDISO image across the network fine and display the DVD icon on the XMB.  But when you try to press X (or select) the DVD icon under Video to play it, it will not do anything (stays on XMB like you aren't even pressing the button).   When I load 1.47.08 and load exact same DVDISO image, the Icon plays fine (loads the PS3 DVD player and plays!)  Note, 1.47.09 will mount and also load a PS3 ISO Game disc image -- only fails to play the mounted DVDISO image.

**Comment by aldostools** [comment]
Please **download** and install the latest build from the [release page](https://github.com/aldostools/webMAN-MOD/releases/latest) or from
http://store.brewology.com/ahomebrew.php?brewid=310

The version still reports 1.47.09 but the xmb proxy was changed back from "bdp_disccheck_plugin" to "idle_plugin" due issue with Bluray and DVD movies.
https://github.com/aldostools/webMAN-MOD/commit/8e5976de8281cad2cc2740c908f7365ad92d9637
