### ISSUE TITLE
net_host building iso

### ISSUE THREAD

**Issue by PIXELSTURM** [aldostools/webMAN-MOD#151]
Hi!

When i build an iso to net_host the png is corrupted and the iso zero bytes.
This happen with the windows and the linux ps3netsrv.
Created isos on hhd are okay.
Any ideas?

Greets

**Comment by db260179** [comment]
Hi Pixelstrum,
Yes had the same issue - its seems to be related to the firmware thats on your ps3

I've tested this issue on the REBUG 4.82.+ and FERROX 4.82 - FERROX with cobra works fine and doesn't exhibit this issue, but on the REBUG firmware all files from the ps3 to the ps3netsrv (doesnt matter what version) create 0 byte files.
So maybe notify the rebug team of this issue.

**Comment by PIXELSTURM** [comment]
Hey, thanks. Cool feedback!

Currently i'm making my first steps only on rebug 4.82.
If i remember correctly aldotools made some parts for the 4.8x rebug release(s)...

**Comment by Joonie86** [comment]
Please try the latest wMM and report back to us. closing this issue since no other feedback was reported.
