### ISSUE TITLE
webman fan control doesnt work in ps2classic game

### ISSUE THREAD

**Issue by N2022062** [aldostools/webMAN-MOD#152]
in ps2classic game fan is so quiet.
when quit the game,the temperature show 70 degree above.

**Comment by Masamune3210** [comment]
Not looking at it right now, but isn't there a setting for what percentage the fans should be at in ps2 mode? Don't think there is much webman can do since afaik the gameos isn't running in the background of ps2 games

**Comment by N2022062** [comment]
Ps2 iso work!
Official ps2 classic pkg not work- -

**Comment by Masamune3210** [comment]
Think its the same emulator, so im not sure what would be the issue

**Comment by Joonie86** [comment]
webMAN is a VSH plugin which doesn't work while PS2EMU is running. PS2EMU itself is its own LV2 and webMAN's dynamic control doesn't work. You can however manually set a static speed setting for PS2emu only.
