### ISSUE TITLE
Add RESTful API to WebMAN

### ISSUE THREAD

**Issue by ThisIsSet-L** [aldostools/webMAN-MOD#155]
Adding a RESTful API to WebMAN would allow external apps (iPhone, Android, Web Apps, etc) to manage and control WebMAN, making the overall experience nicer.

I'll take a look and see what I can cobble together, and make a pull request (may take a looong time).

**Comment by Joonie86** [comment]
Please send us PR whenever it's ready. So far webMAN can easily be accessed from both mobile and PC environment.

**Comment by ghost** [comment]
Any news on this? Currently writing a Python 3 wrapper for the web interface, and I'd rather not scrape everything off the page. As there's barely any identifiers, I would need to rely on a mix of Regex and BeautifulSoup.

**Comment by aldostools** [comment]
There are not plans to implement RESTful API or a SOAP API in webMAN MOD.

**Comment by ghost** [comment]
Alright, thanks for responding so quickly!
Is there any way to make scraping a bit easier by, eg, adding some identifiers like `temperature-rsx` instead of a plain `<a class="s">`?

If not, I'll just use a lot of regex

**Comment by aldostools** [comment]
You can use the raw output for notifications: /popup.ps3=@info9

There are 26 variables available (@info0 to @info25)

**Comment by ghost** [comment]
Never knew that, thanks!

**Comment by aldostools** [comment]
That command is documented in the wiki:
https://github.com/aldostools/webMAN-MOD/wiki/Web-Commands

`/popup.ps3=<text> - Returns text in raw mode (e.g. /popup.ps3=<H1 style=color:red>Hello)`

There is also a list of the @info tags with the meaning of each number

**Comment by ghost** [comment]
> That command is documented in the wiki: https://github.com/aldostools/webMAN-MOD/wiki/Web-Commands
> 
> `/popup.ps3=<text> - Returns text in raw mode (e.g. /popup.ps3=<H1 style=color:red>Hello)`
> 
> There is also a list of the @info tags with the meaning of each number

Just saw it, yeah. Is there any way to fetch that information without displaying a popup on the console?

**Comment by aldostools** [comment]
No. But you can customize the conditions in module edit_chat_popup.h (the lines 95 to 121) to skip `show_msg(msg);`

**Comment by ghost** [comment]
Alright, cheers! Well, i'll be on my way to figure out how to compile WebMAN.
Thanks for all the help
