### ISSUE TITLE
Starting application during XML refresh causes hardlock

### ISSUE THREAD

**Issue by nonijod** [aldostools/webMAN-MOD#156]
Starting an application (such a Movian) while the XML is being refreshed, indicated by the flickering green-yellow light, causes the console to get stuck on a black screen with the light flickering indefinitely and the only way to turn the console off being holding the power button for ~10 seconds. As the XML is being refreshed every reboot it's quite an annoyance as I have to wait a few seconds after boot in order to be able to use the console.

**Comment by aldostools** [comment]
If you don't change the attached USB drives frequently or don't add/remove games very often, it is recommended to "**Disable content scan on startup**" in /setup.ps3

Also it is a known issue that the console will freeze if you have enabled the option "3072KB [MC]" in "Plugin memory usage" and you start any game/application while the system is scanning. Please, uncheck that option if you have it selected, The option is only good when you refresh the content manually from XMB and wait until it complete before start any game/movie/application.

**Comment by nonijod** [comment]
Had some issues finding the content scan option as I didn't notice that I didn't have the category expanded. But that did indeed fix the issue I had so unless there are any plans to fix the lock itself I think this issue can be closed.
>The option is only good when you refresh the content manually from XMB

Is that from the VSH menu or webMAN setup submenu? I don't use the VSH menu that much as it's very unresponsive. What does the option affect anyways? Quicker scans, more games to list or something else?

**Comment by aldostools** [comment]
By refresh manually from XMB, I mean using the combo SELECT+L3 or using the web command /refresh.ps3 from an external browser (PC, tablet or smartphone) or using the VSH menu.

The [MC] option mainly allows to scan more games or list more files when the File Manager is browsed.

As your problem has been fixed, I'm closing the issue.
