### ISSUE TITLE
webMAN not ready

### ISSUE THREAD

**Issue by darkstowner** [aldostools/webMAN-MOD#157]
When starting the PS3, webMAN loads without any problems but after quitting the first emulated PS2 game and trying to launch another one, the message "webMAN not ready" appears and console needs reboot to be able to launch the game. Could launch the game through multiman but i really want to have everything done from the XMB...

Running 4.82 REBUG cobra and last version of webMAN MOD

**Comment by DarkStowner** [comment]
up

**Comment by Joonie86** [comment]
Closing old cases that have no further feedback. please use the latest version of wMM and report us

**Comment by jakdarklight** [comment]
this problem still here, every time i have to reinstall webmanmod
