### ISSUE TITLE
Ultimate issue so waiting 4.83

### ISSUE THREAD

**Issue by RandQalan** [aldostools/webMAN-MOD#159]
4.83 CFW support so it shows correct FW :)
Please and yes the version before works but without proper FW #

**Comment by ghost** [comment]
@aldostools Build date is 0x323031382F30392FULL if you want add support, and don't have 4.83. Nothing more changes afaik, at least sprx that i compiled for myself seems to work fine on 4.83.

**Comment by aldostools** [comment]
@kozarovv  @RandQalan 
Yes, the unique change needed in webMAN MOD is the addition of that timestamp for proper display of the FW as RandQalan suggested. The LV1/LV2 kernel of 4.83 is identical to 4.82, except for the timestamp.

ATM I cannot make any build due multiple issues (lack of time, broken TV, issues with my laptop, missing SDK configuration, etc.). So it would be good if another dev could continue maintaining the project.

**Comment by RandQalan** [comment]
I was wondering why you have not updated it now I know you usually do it soon after OFW comes out. Sorry about your problems and bugging you.

**Comment by ghost** [comment]
I am looking forward to a compiled version for cfw 4.83.
So I stay in 4.82 as webman mod is not officially updated.

**Comment by aldostools** [comment]
@Fedro64 You still can use the current versions of webMAN MOD / sMAN on CFW 4.83. Only a wrong FW version will be reported. The rest of the features should work fine.

If an "unofficial" version is released by the devs/moderators from **psx-place**, you can trust it...

**Comment by ghost** [comment]
thanks for the information @aldostools

**Comment by eNGinEm5** [comment]
Hi, 
I have recompiled the lastest version (with idle_plugin proxy) and added the 4.83 CEX build date to the firmware.h
https://www.sendspace.com/file/ifn3rb
**But I have NOT TESTED this yet.**

**Comment by ghost** [comment]
Good idea is to include at least firmware.h to your post, then devs/users can review it. Just in case.

**Comment by eNGinEm5** [comment]
Good point. I submitted the changes as pull request #162 

PS: I think I made a mistake in compiling the first pkg earlier today. (PS3SDK setup issue)
Here is the current build as of 2018-11-01: https://www.sendspace.com/file/juifw2
(Still not tested because i don't have 4.83 installed. Use it at your own risk.)

**Comment by Toetje585** [comment]
> Good point. I submitted the changes as pull request #162
> 
> PS: I think I made a mistake in compiling the first pkg earlier today. (PS3SDK setup issue)
> Here is the current build as of 2018-11-01: https://www.sendspace.com/file/juifw2
> (Still not tested because i don't have 4.83 installed. Use it at your own risk.)

Tested on 4.83 version info is correct.

**Comment by GravuTrad** [comment]
No version number update?

**Comment by GravuTrad** [comment]
> 
> 
> @kozarovv @RandQalan
> Yes, the unique change needed in webMAN MOD is the addition of that timestamp for proper display of the FW as RandQalan suggested. The LV1/LV2 kernel of 4.83 is identical to 4.82, except for the timestamp.
> 
> ATM I cannot make any build due multiple issues (lack of time, broken TV, issues with my laptop, missing SDK configuration, etc.). So it would be good if another dev could continue maintaining the project.

Aldo, same problem for irisman?

**Comment by GravuTrad** [comment]
> 
> 
> Good point. I submitted the changes as pull request #162
> 
> PS: I think I made a mistake in compiling the first pkg earlier today. (PS3SDK setup issue)
> Here is the current build as of 2018-11-01: https://www.sendspace.com/file/juifw2
> (Still not tested because i don't have 4.83 installed. Use it at your own risk.)

Could you compile too metalification and rebugification versions please? thanks for advance.

Is the compilation process known and ok?

**Comment by ghost** [comment]
@GravuTrad builds created using latest source available on aldo github. 


[webMAN_MOD_1.47.09_Updater.zip](https://github.com/aldostools/webMAN-MOD/files/2544739/webMAN_MOD_1.47.09_Updater.zip)
[webMAN_MOD_1.47.09_Updater_metalification_theme.zip](https://github.com/aldostools/webMAN-MOD/files/2544740/webMAN_MOD_1.47.09_Updater_metalification_theme.zip)
[webMAN_MOD_1.47.09_Updater_rebugification_theme.zip](https://github.com/aldostools/webMAN-MOD/files/2544741/webMAN_MOD_1.47.09_Updater_rebugification_theme.zip)

**Comment by GravuTrad** [comment]
ok for 4.83? (cause no version change)
Why no new version? (aldo only can maybe?)
Big thanks for all.

**Comment by TekZon01** [comment]
> 
> 
> @kozarovv @RandQalan
> Yes, the unique change needed in webMAN MOD is the addition of that timestamp for proper display of the FW as RandQalan suggested. The LV1/LV2 kernel of 4.83 is identical to 4.82, except for the timestamp.
> 
> ATM I cannot make any build due multiple issues (lack of time, broken TV, issues with my laptop, missing SDK configuration, etc.). So it would be good if another dev could continue maintaining the project.

many thanks to you, your successful project helps people all over the world

**Comment by TekZon01** [comment]
> 
> 
> @kozarovv @RandQalan
> Yes, the unique change needed in webMAN MOD is the addition of that timestamp for proper display of the FW as RandQalan suggested. The LV1/LV2 kernel of 4.83 is identical to 4.82, except for the timestamp.
> 
> ATM I cannot make any build due multiple issues (lack of time, broken TV, issues with my laptop, missing SDK configuration, etc.). So it would be good if another dev could continue maintaining the project.

many thanks to you, your successful project helps people all over the world

**Comment by TekZon01** [comment]
> 
> 
> @kozarovv @RandQalan
> Yes, the unique change needed in webMAN MOD is the addition of that timestamp for proper display of the FW as RandQalan suggested. The LV1/LV2 kernel of 4.83 is identical to 4.82, except for the timestamp.
> 
> ATM I cannot make any build due multiple issues (lack of time, broken TV, issues with my laptop, missing SDK configuration, etc.). So it would be good if another dev could continue maintaining the project.

many thanks to you, your successful project helps people all over the world

**Comment by TekZon01** [comment]
> 
> 
> @Fedro64 You still can use the current versions of webMAN MOD / sMAN on CFW 4.83. Only a wrong FW version will be reported. The rest of the features should work fine.
> 
> If an "unofficial" version is released by the devs/moderators from **psx-place**, you can trust it...

@aldostools 
many thanks to you, your successful project helps people all over the world

**Comment by TekZon01** [comment]
> 
> 
> @kozarovv @RandQalan
> Yes, the unique change needed in webMAN MOD is the addition of that timestamp for proper display of the FW as RandQalan suggested. The LV1/LV2 kernel of 4.83 is identical to 4.82, except for the timestamp.
> 
> ATM I cannot make any build due multiple issues (lack of time, broken TV, issues with my laptop, missing SDK configuration, etc.). So it would be good if another dev could continue maintaining the project.

@aldostools 
many thanks to you, your successful project helps people all over the world we appreciate your hard work

**Comment by GravuTrad** [comment]
> 
> 
> > ok for 4.83? (cause no version change)
> > Why no new version? (aldo only can maybe?)
> > Big thanks for all.
> 
> your picture very annoying like a shit

What's your problem

**Comment by GravuTrad** [comment]
no github project for irisman?

**Comment by aldostools** [comment]
Joonie86 -member of rebug team- has a fork of IRISMAN on his GitHub.

**Comment by GravuTrad** [comment]
but not yours? to see updates for 4.83?

**Comment by ghost** [comment]
Hello everyone,
Where are we with webman-mod for firmware version 4.83?
@kozarovv seems to have done the work but I have not seen much of a psx-place or other return test.
Thank you.

**Comment by Joonie86** [comment]
Closing old issues that have no further feedback. Please try the latest wMM and report back.
