### ISSUE TITLE
IRISMAN 4.83

### ISSUE THREAD

**Issue by Elvitek** [aldostools/webMAN-MOD#161]
Hello Aldo, I'm sorry if I ask here but there are no other places to write it. My question is: Will you release a version of IRISMAN compatible with cfw 4.83? Thank you.

**Comment by aldostools** [comment]
I don't think I will release an update... currently I have various issues: lack of time, problems with my laptop, lost PS3 SDK configuration, broken TV (to use PS3), etc.
