### ISSUE TITLE
Lovely webman issues with 4.83 firmware

### ISSUE THREAD

**Issue by TekZon01** [aldostools/webMAN-MOD#164]
My PS3 was on rebug 4.82 lite no issues with webman but I had to install another firmware which is 4.83 ferrox 7.55 to access PSN, the problem now with bthe thumbnails of PS1 games not loading all of them and Everytime is differenc and changeable to show difference and not showing another, icons are 512x512 png, why I upgrade the firmware because when I installed sen enabler webman became not able to run ps2 games unfortunately, please help us, millions of people would thank you for your successful helpful project, don't stop it we are looking forward to use it on PS4 later, thanks

**Comment by ghost** [comment]
Look here
https://github.com/aldostools/webMAN-MOD/issues/159

**Comment by Joonie86** [comment]
Please contact the author of Ferrox.
