### ISSUE TITLE
unmount iso mounted by multiman

### ISSUE THREAD

**Issue by houcembc** [aldostools/webMAN-MOD#166]
unmount iso mounted from multiman freezes xmb. cant restart console from web have to use power switch.

**Comment by Joonie86** [comment]
Please try the latest wMM and report back to us. closing this issue since no other feedback was reported.

**Comment by houcembc** [comment]
issue still present Rebug 4.86.1 LITE – Cobra 8.2 – Toolbox 2.03.04 latest webMAN MOD 1.47.27
