### ISSUE TITLE
Video Recording Feature Issue

### ISSUE THREAD

**Issue by rhobiusvoid** [aldostools/webMAN-MOD#169]
Hey, I'm having a slight problem.
With WebMAN enabled, and with the settings set to "MPEG4 368p AAC 64K" I would be imagining it'd work just fine.
Infact, it doesn't. At all.
I can start and end recordings completely fine, however, when i go back to check the recorded file, I find out it's 28 bytes and it doesn't actually work whatsoever.
I do not know what's causing this issue to arise. I have a PSN spoof and I also use ArtemisPS3 at times, but I tried it without using any of it.

**Comment by rhobiusvoid** [comment]
Bonus note: After testing it out, it seems it doesn't work on any quality above 240p. I'll try to test more as I go.

**Comment by Joonie86** [comment]
Please try the latest wMM and report back to us. closing this issue since no other feedback was reported.
