### ISSUE TITLE
Auto-play (Disc Auto-Start) does not work.

### ISSUE THREAD

**Issue by 444nonymous** [aldostools/webMAN-MOD#17]
I'm using latest rebug with webman lite 1.43.36. I have Disc Auto-Start activated in ps3 settings and auto-play in webman. I think this option is meant so when you select a game, the browser popups and closes, the game loads and it automatically starts like if a new game disc was physically inserted in the ps3.

But I never got it to work, I always have to select the game icon and manually start it. And the thing is I don't remember this feature ever working for me with the default webman that rebug packs, so maybe I'm doing something wrong or it does not work with emulated discs.

Thanks.

**Comment by aldostools** [comment]
The option Disc Auto-Start is a feature of OFW. It auto-starts the disc currently inserted when the system starts (or restarts).  If the option "Load last-played game on startup" is enabled, the game is mounted and the system will believe that it's a real disc and auto-start it.

On the other hand, the Auto-Play option in /setup.ps3 is used to auto-start a game when it is launched from the XMB or using the web command: /mount_ps3

The games mounted with /mount.ps3 do not use the auto-play option. They can be auto-started using /play.ps3

Take in count that webMAN Lite edition has the minimal features and many of the features available in the full edition (or the regular editions) are not available in the Lite edition, including the Auto-Play.

I just noticed that the Auto-Play option appears in /setup.ps3 of Lite edition but it shouldn't be there.
I will remove it from in the next update.

**Comment by 444nonymous** [comment]
I've tested the standard webman version and I can't get auto-play to work either.

**Comment by aldostools** [comment]
Thank you for your feedback. I'll have to check later if something is happening with the standard edition.

I normally test with the full edition, and auto-play is one of the features that I use more frequently.

My suggestion is that try using the full edition and you'll be getting all the available features in the plugin.

**Comment by 444nonymous** [comment]
Since it's one the most used basic features and the option is already there you could also make it work for the lite version instead of removing it.

Thanks.

**Comment by aldostools** [comment]
The purpose of the lite edition is to keep the memory footprint as low as possible. I want to keep it bellow 192KB. The margin that I have for extra features is too low, to keep that goal.

It's true that I can add any of the available features, but that would increase the memory footprint; making the "lite" as heavy as the standard edition.

Unless you have memory issues with specific games, I suggest you that use the full edition.

**Comment by 444nonymous** [comment]
That's true, but I think auto play is something basic you can always use. There is a lot of PAD shortcuts I'd never use. I don't know how much space PAD shortcuts need compared to autoplay, but a lot of the PAD things can be done in other menus, while autoplay is a unique feature.

**Comment by aldostools** [comment]
Ok, I don't promise it... but I'll evaluate how much space it would use... maybe I'll have to sacrifice other feature to add it.

**Comment by 444nonymous** [comment]
I think "slider" listing for games is not aviable in lite, but I can see the menu tab.
PAD to show IPDS, but lite has not spoof idps/psid change options.
PAD to refresh XML and Block servers, there are 2 more ways to do it (Setup and XMB)

**Comment by aldostools** [comment]
Please download the pkg of 1.43.36 again... It has a new build of Lite edition with support for Auto-Play.

"Show IDPS" was removed from Lite edition to gain some space in the memory footprint (currently it is 190KB, so it is still below 192KB or 3 pages of 64KB).

The other options remain unchanged.

**Comment by 444nonymous** [comment]
I've tested it and it does not work :(

And the slider tab shows the same as the game tab.

**Comment by aldostools** [comment]
I don't know what's wrong on your end... the features (auto-play, play disc combo, slider) are working fine on Rebug 4.80.1 with the Lite edition.

The slider requires some files in /dev_hdd0/xmlhost/game_plugin that are installed by the updater.

If you have modified category_game.xml it's possible that auto-play could not be finding the disc item in the xml.

**Comment by 444nonymous** [comment]
I've really tried my best to make this work, deleted and reinstalled lite from pkg. 

I'm getting a debug.txt file in the root of hdd0, I don't know it that's normal or related.

I have also noticed that you get the recording plugin installed with lite, but it has not recording features.

The slider works fine.

**Comment by aldostools** [comment]
Thank you for your feedback. I have removed the debug.txt, I left it by mistake while I was debugging droidMAN.

Regarding the auto-play I have added extra delays... maybe the plugin was not waiting enough.

You can try the new pkg **webMAN_MOD_1.43.36_Updater_20160925.pkg** available in the [release page](https://github.com/aldostools/webMAN-MOD/releases/tag/1.43.36)

The recording plugin is a standalone plugin that work independently from webMAN (any edition).
I include it for convenience of the users that need to record videos, due it's recommended to use the standalone plugin, instead of webMAN. If you don't need it, you can delete it.

**Comment by 444nonymous** [comment]
Now it's working! Thanks.

Just a cosmetic question: Why when you change to next / previous games using PAD short cuts you only get an info message over the XMB (or when last game is auto loaded at startup), but when you manually select the game icon a white web browser window popups for a few seconds (now more with the delay)?

**Comment by aldostools** [comment]
Thank you for your feedback.

The shortcut pads call the mount function internally. For XMB, the web browser is used to call the mount function.

I still have to check why that window is delaying a few seconds more... I think it's due an extra wait for /dev_bdvd added to the mount function. But that window really should not wait for /dev_bdvd too.

**Comment by aldostools** [comment]
I have updated the pkg again, now the browser closes faster after mounting a game from XMB.
Also changed the way Play Disc waits for the disc (due the browser returning faster to XMB).
Download: [Link](https://github.com/aldostools/webMAN-MOD/releases/1.43.36)

**Comment by 444nonymous** [comment]
Now it works much faster, but there is a problem.

When selecting a webman game, it loads, and the XMB selected item goes back from "webman ps3 folder listing games" to point to "webman Games folder icon in XMB Game root". And then you can see the game disc icon appearing below "webman Games" and the game auto-plays. But this only works when there is already a game loaded and you select another.

If there is no game loaded or if you unmount the current game disc before loading another, instead of auto-playing the game in the last step, the XMB selected item goes from "webman Games folder icon in XMB Game root" to entering the folder and pointing to "webman PS3 folder icon" and it stays there. You have to manually go back to XMB and select and click the game icon.

**Comment by aldostools** [comment]
Thank you for your feedback. The issue could be due some external disks enter in sleep mode and the delay may be longer the first time.

In the build [1.43.36 (20160926)](https://github.com/aldostools/webMAN-MOD/releases/download/1.43.36/webMAN_MOD_1.43.36_Updater_20160926.pkg) I changed the method used to detect when the disc icon appears.
The overall wait for the disc icon now is longer for PS3 games (up to 15 seconds) and shorter (3 seconds) for the the other types, instead of wait for 6 seconds for all the types.

**Comment by 444nonymous** [comment]
Now exactly the same problem always happens, with or without a loaded game. No auto-play no matter what I tried. The game icon in XMB below "Webman Games" never appears, and you enter the "Webman Games" folder instead.

I'm running games from the internal HDD, stock 320GB slim 25xx PS3 series. I turn on the PS3 and XMB loads and draws all icons very quickly. The only thing is that the HDD gets slower copying / installing when it's fuller, but I don't think it's an issue here. And it happens to all PS3s, maybe file system related. 

I think the problem is the disc emulator takes too much time to load the game. You can cut time making all the process before that as fast as possible and  just waiting more for the disc to appear.  But it does not take 15 seconds, more like 3 to 5 since I click the game selected until it fails by entering the folder.

**Comment by aldostools** [comment]
Please try with this file: **http://aldostools.org/temp/test/webftp_server.sprx**

The icon dectection is done in 2 stages:
- Detect when the icon is created (up to 15 seconds). It can less than 15 secs if the icon is detected earlier.
- And 3.75 additional seconds (fixed) waiting for the icon to be loaded on XMB (the build that you tested only waited 2.25 seconds). So this waits 1.5 seconds more before exec_push.

In this build I also changed the way the setup is stored in memory. So, also go to /setup.ps3 and check that Auto Play is checked and save the settings just to be sure.

I don't understand why it's not working on your console, I have a stock 160GB slim 2501 and all the games are loading fine. Maybe you should test with different games too, due some games take longer to load than others.

**Comment by 444nonymous** [comment]
In this new build it gets stuck at selecting a game. So in the folder where all my games are listed, I click on a game, it loads the game (info message is shown) but it does no move, I just can click X and select the game again and again (info message is shown too). I have to go back pressing "circle" to times to get to XMB "webman games" and below is the disc icon.

I have 15 games installed of all kinds, and I've tried now and before. There is something wrong that does not work for all.

**Comment by aldostools** [comment]
Please check again in /setup.ps3 that Auto Play is selected.

In this build the config is stored differently and some settings maybe not be stored correctly.

**Comment by 444nonymous** [comment]
This build disabled autoplay and had to enbale it again. Now autostart and autoplay is on for sure.

But I have the same problem with this build. I have 15 games installed of all kinds, and I've tried them all. There is something wrong that does not work. The icon is created in less than 15 seconds that's for sure. It takes like 5 seconds since I select a game from the menu. When it fails by entering the webman folder, I could see the icon being created just after this happened.

**Comment by aldostools** [comment]
Let me add 2 extra seconds.... to see what happens.

**Comment by aldostools** [comment]
Please re-download and install (162,656 bytes - md5: D02FAC71A9265B1C900CAAC745B58BE2)
http://aldostools.org/temp/test/webftp_server.sprx

**Comment by 444nonymous** [comment]
It works now but not always. Take into account It takes some time for the icon to appear depending on the game (I can count from 3 to 6 seconds once in the XBM Games root, after the game is loaded).

But this is the problem for sure, you can make all the loading process faster until this point and wait more for the icon. So you should add a lite more time to be sure.

Most games work now, but the same game sometimes fails to load and sometimes works fine. I reboot the ps3 every time to try to get similar results. I don't know why the icon creation takes so long.

**Comment by aldostools** [comment]
Maybe try changing the XMB sort mode to By Folder or By Format (using SQUARE).
If you have many icons on your Game column it may delay the loading due the VSH is still busy loading icons.

Also it would be good to test if ISO and JB folder make a difference. 
I have tested both formats from external and internal, and they don't take so long.

**Comment by 444nonymous** [comment]
I have 15 games (folders with files, not isos) I load using webman and another 15 "PSN only" ones (installed, folders with files) that are listed in the Game column. But when I turn on the PS3 the XBM loads really fast and all the icons are drawn in less that 2 seconds. 

Once XMB has loaded everything I load the webman game and that new icon seems to take a lot of time. I've tried the square grouping thing and it does not matter, the column icons are always drawn.

**Comment by aldostools** [comment]
Have you tried to rebuild the file system? Maybe your disk is too fragmented.

**Comment by 444nonymous** [comment]
Yes, database and file system, both. And again it is true that the HDD gets slower when fuller, it's very well known it happens to all PS3s and mine could be faster, but It's not that slow. Everything loads pretty fast, Webman list of games, PSN games too. 

It's just the loaded game icon. It's a pitty you can't detect when the XMB creates the icon, that would solve the issue and always load the game as soon as possible.

**Comment by aldostools** [comment]
Does the slow icon happen also with the official webMAN of deank?

**Comment by 444nonymous** [comment]
I've never tried, I used irisman before and then webman since it was packed with Rebug. And I don't think I can try it, it's not updated and I'm in 4.80.

**Comment by aldostools** [comment]
For now I'll leave the Auto-Play with 6 seconds delay after icon detection.
Maybe later -with more info- this could be improved.

**Comment by 444nonymous** [comment]
Since it seems to be HDD related and the fuller the slower, you could check the HDD % free space and have several delay times, more time fore less space. Just an idea, there has to be way to create the icon faster.

**Comment by aldostools** [comment]
The % of free space is not a good indicator... Indeed my HDD is full at 93% and the icon is created relatively fast.

The loading time varies by game and depends of Cobra and GameOS (not of webMAN). For instance:
- The Sims 3 takes me 12 seconds to load and 3 seconds for the icon to appear and be ready.
- AC Brotherhood takes 3 seconds to load and 2 for the icon to be ready.
- LEGO games take more or less the same as AC Brotherhood.

So the loading time seems to be relative to the number of files in the game.
Also it's a fact that a game in JB folder loads slower than an ISO.

You should try with different games and with ISO (if they are not already).

**Comment by 444nonymous** [comment]
The thing is when waiting for the icon to appear the XMB seems idle, the "watch icon" in the top right that means busy is gone, and the load process until then is really fast.  So the icon is created in the first step fast, but it's loaded slowly in the XMB.

I think the icon is loaded in the XMB by reading param.sfo and loading some media files to display, and that's why it takes some time. But you don't really need to load any media for autoplay, since you are not going to watch it anyway. Pic1, Icon1, Snd0, etc are several MB each in a lot of games. Maybe the bigger these files the longer it takes to create the icon.

So maybe with autoplay enabled you could disable the XMB icon media loading, or delay loading that media until only the generic disc icon is created, then autoplay, then let it load the rest. Or only load all the media (video, sound, background picture) when manually pointing over the disc icon in XMB, but loading the small static icon you see in the XMB when pressing the "ps button" during a game.

The CFW PSP had an option to show only the small icon (no video, sound, background) in game menu lists, because it was much faster.

**Comment by aldostools** [comment]
The "wait icon" is because the system is busy doing something.

All I can do to improve the speed is to reduce the frequency of sending commands to explore_plugin.
In this test build I reduced the frequency to 1/10 of the times... so your system should be less busy now (and have more time to mount the game)
.
Link: http://aldostools.org/temp/test/webftp_server.sprx

The rest of the mount process is done by GameOS and Cobra. So webMAN doesn't have control of what these processes do.

**Comment by 444nonymous** [comment]
I've tried and it does not make any difference to me. Thank you anyway.

Anyway, without autoplay enabled, the cursor remains over the game selected in the games list folder.
It could be better to automatically go back to Games root, so you don't have to press back several times until you get there to select the game icon. That would make easier to run games without autoplay.

**Comment by 444nonymous** [comment]
I've read again your last post, and what I meant before was that the "wait icon" disappears very quickly, almost as soon as the browser closes and the game is loaded. So I thik the XMB is idle at that point. And there was noting wrong to change in your last commit. 

It's once the XBM is idle at the Games root column, that it takes 5-10 seconds for the "disc game icon" to appear, but the "wait icon" never appears again.

And that's why I thought that what is taking too long is just reading and processing the "disc game icon" media files to display in the XMB, especially knowing that in the PSP XMB (CFW) these media files could be disabled and the result was a very fast game listing, especially when you had a lot of games installed.

You have also said that you think some games take more time than others to mount because they have more small files. That could be another big factor and harder to solve, unless there is a way to cache the mount process. The thing is I found faster to mount a new game when another was already mounted.

**Comment by aldostools** [comment]
If it mounts faster when a game is already loaded, maybe you should try enabling "Load last-played game on startup". That way always there will be a game already mounted when you try to mount a new game.

Regarding the media files, I don't think they would make a difference. I believe the long delay showing the disc icon is due some background process taking too long and not due webMAN.

**Comment by 444nonymous** [comment]
What about this? It fails to exec because the icon is not created yet, so it exec the webman folder. But there is another permanent short-cut in the Games root column. Its "/app_home/PS3_GAME/".

If you exec the permanent short-cut instead of waiting for the XMB icon to be created, you have it solved. If there is not anything mounted yet, you get an error, but you only have to press back and exec again. This can be automated very easily, so instead of waiting for a fixed amount of time, you can retry. That way all games will be auto-played as soon as they can no matter how long does it take for them to be mounted.

Just another idea.

**Comment by aldostools** [comment]
Thank you for the idea. I like it, but first I have to do some tests before implement it.

I remember having issues in the past with the saves not being recognized by some games when I started the games with /app_home/PS3_GAME instead of the Disc Icon. But that was in 3.55 kmeaw (years before Cobra).

**Comment by 444nonymous** [comment]
I've tried with a few games and savegames are loaded and saved as usual. Let me know what games give problems so I can check if I have them.

I've also noticed that If I'm fast enough I can go to " /app_home/PS3_GAME" and manually click and run the game even before the game icon is created in the XMB. So this could be a faster way to autoplay.

Sometimes a /ps2_game folder (I don't remeber the exactly the name) is mounted too in the root at the same level where /dev_flash 2, 3, etc are. It can't be unmounted and I'm only using PS3 games.

**Comment by aldostools** [comment]
I was testing your suggestion about /app_home/GAME and it only works for certain games.

The issues that I found was with some games in JB folder. But not all the games have the issue. Even if I remap app_home to the JB folder, the game returns an error when some games are started through /app_home.  I tried different ways to remap app_home without success. Some of the errors that I got were: 8002BF14 and 8001003A.

Here is the test build that I used if you want to try it (this one don't have these errors):
http://aldostools.org/temp/test/webMAN_MOD_1.43.36_Updater_test_app_home.pkg
There is a new option in /setup.ps3 next to the Auto-Play option. If checked, it will try to use app_home.

That option also remaps /dev_bdvd to /app_home. Before this build ISOs only mounted /dev_bdvd

The folder /ps2_disc is mounted by SingStar (and maybe other games). That device is mounted by the game to allow import data (e.g. songs) from PS2 discs owned by the user.

**Comment by 444nonymous** [comment]
The test build behaves like the old one, trying to run games from the XBM game icon and failing the same way if it's not created. I selected the new option.

I have also noticed that sometimes the errors seem random. I reboot and I can play a game from app_home, other times the game fails if another game gave some error first.

**Comment by aldostools** [comment]
Thank you for your tests & ideas. I have expended hours trying to make the Auto Play work with app_home, but unfortunately the results are bad (some games start while others return an error).

For the moment I'll discard the option of app_home due the results are not satisfactory...

**Comment by 444nonymous** [comment]
Fair enough, thank you for your work.

Just a few things.
1. Is the same remapping /dev_bdvd to /app_home, than /app_home to /dev_bdvd? The second option sounds better. You access bdvd trough app.
2. Forgetting about /app_home. In my experience the moment you detect "when the icon is created" you don't have to wait for "the icon to be loaded on XMB". You can run the game just after the first step. Why not create a new permanent shorcut inside the webman folder?. You can have an "unmount" icon and a new "start game" icon. A generic permanent shorcut with a plain icon, not the fancy one loaded on XMB. You always exec that.
3. Forgetting about any icons. Can you just run eboot.bin after the first step "when the icon is created", witch means the game is already mounted? Or just try to detect when "/dev_bdvd/PS3_GAME/USRDIR/EBOOT.BIN" is available instead of waiting for any icon in steps 1 & 2

**Comment by aldostools** [comment]
1- No. /app_home is a debug icon that works in a different way to bdvd icon. While /dev_bdvd access the game content from a single path, /app_home uses a different structure. /app_home/USRDIR and /app_home/ must be remapped to /PS3_GAME/USRDIR, /app_home/PS3_GAME is mapped to /PS3_GAME, but /app_home is mapped to the root of the game.

Some games work with only 1 or 2 of these mappings. I also tried mapping /app_home to /dev_bdvd, but only some games work from /app_home/PS3_GAME/. Also the ISOs should map /app_home to /dev_bdvd, since the folders only can be accessed through /dev_bdvd.

In my tests, the /app_home method is not accurate for launching ISOs and JB folders.

2- The icons in webMAN folders are shortcuts to the web browser plugin, which is used as interface to receive commands from XMB. The disc icon is different and it appears only when a "fake insert" is sent, even having /dev_bdvd mounted correctly.

The auto-play uses explore_plugin automation commands to simulate clicks on XMB. To start the game, the disc icon must be displayed to be able to click on it. If the timing is not correct, the focus could be in a different icon and a different option could be executed. Additionally, when I execute the explore_plugin command the plugin don't know if it was successful or not (I don't know how to get that info).

3- Unfortunately I can't execute EBOOT.BIN from the plugin. sysProcessExitSpawn2 can't be called from the sprx and I haven't found the proper way to call the VSH [apis ](http://www.psdevwiki.com/ps3/Game_plugin) that execute an EBOOT.BIN.

**Comment by 444nonymous** [comment]
I've noticed this: If the webman execs before the icon is created, it goes inside "webMAN games" folder. Then, if I just press back (circle) quickly while the icon is still being created, the game is launched. If you wait to long to press back (circle), and the icon is already created, nothing happens.

So maybe it could work to send exec+back almost at the same time, (maybe several times in a row very quickly) while the icon is being created. You can test this by artificially setting a low waiting time that makes all your games to fail because the icon is never created before exec.

**Comment by 444nonymous** [comment]
I've also noticed this works without auto-play enabled in Webman, just going back fast. That's because it uses the PS3's own auto-play feature, when it detects the game being mounted (disc inserted for the PS3), if you are in the Games root column, the icon is created and started.

So instead of waiting and delaying,  if you are able to go back as fast as possible, before the icon is created, maybe the PS3 could take care of the rest and auto-play by itself when ready. It's the opposite approach but it could work. 

It happened when manually trying to go back like in the second feature asked here -> https://github.com/aldostools/webMAN-MOD/issues/22

**Comment by nachog4** [comment]
the problem for me since Rebug 4.81 is that whatever I mount with Webman Mod auto plays, even if I dont want!

**Comment by Joonie86** [comment]
Closing old cases that have no further feedback. please use the latest version of wMM and report us
