### ISSUE TITLE
Issue playing most CoDs after disable syscall

### ISSUE THREAD

**Issue by GodlyEcstasy** [aldostools/webMAN-MOD#170]
When i use L2+Triangle (Disable Syscalls) after loading a HDD backup game, i cant load mw2, mw3, cod4, or ghosts. (it just goes to black screen, never to actually reach a loading screen) Other games tend to work fine, but this is an issue to me. However, when i use version "webMAN 1.45.09", everything is fine. Ive only tested this with version 1.45.09 (this lets the games work properly after disabled syscalls) and the latest version as of 10/10/18 (that didnt let games play after loading)
ive done lots of testing to confirm that this is a webman issue, rather that a debug setting/cfw version issue

**Comment by ghost** [comment]
Try create ISO backup from your disc, this should help.

**Comment by Joonie86** [comment]
Closing old issues that have no further feedback. Please try the latest wMM and report back.
