### ISSUE TITLE
Can webman mod spoof the firmware version?

### ISSUE THREAD

**Issue by ghost** [aldostools/webMAN-MOD#171]
I'm confused. I've seen some release notes in prior version where it mentioned changing the spoof version number, and in the options of the current version of webman mod I can find a setting for disable firmware version spoofing (which is checked by default). However unchecking it and saving/restarting doesn't do anything I can tell, my firmware stays at 4.82. I need 4.83 spoofed because I need to connect to psn briefly to download a game. Is webman mod supposed to be able to spoof the version number or not? I know I could just use SEN Enabler to do it and I will if webman mod can't do it.

**Comment by aldostools** [comment]
Cobra used to have a feature that allowed to spoof the firmware version and webMAN MOD included the option to enable/disable that feature. However, that feature was not working properly and if I recall correctly, Rebug Team decided to exclude that option from recent Cobra versions.

If you want to spoof the firmware version properly, please use SEN Enabler or any other tool dedicated for that purpose.
