### ISSUE TITLE
VSH freezes console

### ISSUE THREAD

**Issue by Cherbet** [aldostools/webMAN-MOD#174]
If i try to open VSH menu on last wmm build, the console freezing. What to do?

**Comment by aldostools** [comment]
To check the issue I need to know more info like firmware version, type, the exact version of webMAN and how exactly it happens (after mount a game, after start the console), if it freeze when it VSH menu opens or when you select an option, if you have other plugins loaded, etc.

Meanwhile you can disable the option going to /setup.ps3 and unchecking the shortcut for VSH menu.

If you're console is still frozen, press the power button for 15 seconds until it turns off. Avoid to unplug the power cord unless it is strictly necessary.

**Comment by Cherbet** [comment]
Rebug 4.84.2 Rex(Cobra 8.01) (On old firmware 4.82.2(Cobra 7.5) freezes too). Webman 1.47.13, if i try to open it from Games menu > settings > VSH menu on any cases, or maybe i need to install something?

**Comment by aldostools** [comment]
Ok, I'll check it when I return home. Meanwhile you can try re-downloading the pkg again or the prior version 1.47.12 and re-installing them, just in case you got the initial package of 1.47.13 that was corrupted.

**Comment by Cherbet** [comment]
I tried reinstall packages, old, new, firmware, it's still freezing, if i try to load it from boot_plugins(copy vsh sprsx's), it's first unloads and after try again freezes

**Comment by aldostools** [comment]
VSH Menu should not be listed in /boot_plugins.txt. That plugin is loaded dynamically from webftp_server.srpx

I'll reply back when I have checked the issue. It could take me some hours.

**Comment by Cherbet** [comment]
Yeah, maybe, but it's not working in any cases, very sadly

**Comment by aldostools** [comment]
I have tested VSH Menu and sLaunch from webMAN Setup menu on XMB and using the pad shortcuts (hold SELECT for 5 seconds)  and I couldn't get any freeze.

Try disabling any dynamic theme if you are using one... sometimes they cause issues with background plugins.

**Comment by Cherbet** [comment]
I'm using standard ps3 theme, all, what i installed, it's cfw rebug 4.84.2 and webman 1.47.14, what's wrong with vsh?

**Comment by J0hnTR** [comment]
Still the same with Webman 1.47.15 on clear REBUG 4.84.2.
Any news?

**Comment by Cherbet** [comment]
> 
> 
> Still the same with Webman 1.47.15 on clear REBUG 4.84.2.
> Any news?

No news, mine still freezing too, maybe aldo fix it, if is find this bug, but not fixed at this moment

**Comment by aldostools** [comment]
The last time I checked this bug I couldn't reproduce this error.

Please check if the VSH menu works if you use hold down SELECT button for 5 seconds on XMB.
If it freezes with the combo, then it tells me that the issue is in the wm_vsh_menu.sprx

If it only freezes when you access it from Games > Settings > VSH Menu, then it's possible that the issue is in your **webMAN_EN.xml** (or the xml corresponding to your language). 

The current version of webMAN uses the system module "idle_plugin" as proxy to send the web commands from the XMB to the plugin. webMAN redirects "idle_plugin"  to the file **/dev_hdd0/tmp/wm_res/wm_proxy.sprx**

If wm_proxy.sprx does not exist or if the XML (webMAN_**.xml) has a module_name different to idle_plugin, webrender_plugin or webbrowser_plugin, the XMB will freeze instantly.

So, please check if VSH Menu loads with the combo (pressing SELECT for 5 seconds), that **wm_proxy.sprx** exists in /dev_hdd0/tmp/wm_res, and that the webMAN_**.xml has idle_plugin in the module_name of &lt;Table key="wm_vsh_menu_load"&gt;

EDIT:
If you're using other plugins, please disable them. There are reports of conflicts with plugins like CCAPI.

**Comment by Cherbet** [comment]
Now, changed language of system and webman, after reinstalled it(To accept english everywhere, my home language is russian), and now vsh loads properly. So, now i try to change system language, but not webman(Left it as english) and try again, i think issue in russian language, it's cannot loading while you opening vsh, cuz maybe that issue of code, what pointed only for english locale.

**Comment by Cherbet** [comment]
After changing language of system to russian(not webman, language, it's left as english), console freezed again. I will try to find that piece of code, to check it, but that is issue, now you know where is problem

**Comment by aldostools** [comment]
Thank for you for your feedback. I guess the issue could be related to the use of cyrillic fonts (maybe other fonts have issues too).
https://github.com/aldostools/webMAN-MOD/blob/master/_Projects_/vsh_menu/blitting.c

For the moment try using english or a language with latin fonts, until the issue is fixed.

**Comment by Cherbet** [comment]
readed readme of vsh, and maybe here is:
v0.3:
    Added Firmware version info (spoofed if it is). Thanks @Zar.
    New layout, background and icons.
    #(Only one english version for the moment...)

**Comment by Cherbet** [comment]
Okay, wait, i try now

**Comment by Cherbet** [comment]
Changed character set to lating(us). Freezed, maybe try to change it in sources.

**Comment by aldostools** [comment]
I'm at work now. I'll try to check the issue when I get home or in the week.

**Comment by Cherbet** [comment]
Okay, now i know, problem in different languages than english, so, i waiting for updates, thank you!

**Comment by aldostools** [comment]
IIRC I tested other latin languages (spanish, french, italian)... Anyway I will test again later and update it if I find a fix.

**Comment by Cherbet** [comment]
okay, if you need testing, write me, i test it

**Comment by aldostools** [comment]
VSH Menu & sLaunch menu now show an error message and return to XMB if system language is Russian.
It seems that the VSH freeze only happens with Russian language. Other languages like Japanese, Korean and languages with latin alphabet like English, French, Italian, German, Spanish don't have the issue.

I tried different approaches to solve the issue. Unfortunately I couldn't prevent the freeze. For now, these plugins do not support Russian language. Choose a different system language if you need to use them.

The updated binary is available in the releases page.

**Comment by Cherbet** [comment]
> 
> 
> VSH Menu & sLaunch menu now show an error message and return to XMB if system language is Russian.
> It seems that the VSH freeze only happens with Russian language. Other languages like Japanese, Korean and languages with latin alphabet like English, French, Italian, German, Spanish don't have the issue.
> 
> I tried different approaches to solve the issue. Unfortunately I couldn't prevent the freeze. For now, these plugins do not support Russian language. Choose a different system language if you need to use them.
> 
> The updated binary is available in the releases page.

Okay, vsh rendering symbols different than system?

**Comment by aldostools** [comment]
Honestly I don't know what is the cause of the bug...

I suspect it could be related to the rendering of fonts, but it could be also memory related.
https://github.com/aldostools/webMAN-MOD/blob/master/_Projects_/vsh_menu/blitting.c

As the bug freezes the system, it requires constant reboots and that takes a lot of time.
This week I'll be busy with the family due Easter time.... Maybe some developer reading this could debug this error. For the moment, change the system language to other language if you need to use these plugins.

At least now it doesn't freeze if you try to access the plugins (intentionally or by mistake).

**Comment by Cherbet** [comment]
> 
> 
> Honestly I don't know what is the cause of the bug...
> 
> I suspect it could be related to the rendering of fonts, but it could be also memory related.
> https://github.com/aldostools/webMAN-MOD/blob/master/_Projects_/vsh_menu/blitting.c
> 
> As the bug freezes the system, it requires constant reboots and that takes a lot of time.
> This week I'll be busy with the family due Easter time.... Maybe some developer reading this could debug this error. For the moment, change the system language to other language if you need to use these plugins.
> 
> At least now it doesn't freeze if you try to access the plugins (intentionally or by mistake).

Okay, no problem, it's not hot) Thank you!
