### ISSUE TITLE
Neither web interface nor FTP accessible while ingame

### ISSUE THREAD

**Issue by LordBubblesDev** [aldostools/webMAN-MOD#175]
Hi there,

I recently needed to be able to swap PS2 ISOs while being ingame, so I tried to access webman from the browser on my computer in order to swap/mount another ISO. But the thing is (I have never checked before), neither the FTP server nor the web interface are accessible while I am ingame.

I have checked the IP address, this is the right one (both ftp and web interface come back online as soon as I leave the game). I have also tried to swap to next game with SELECT+L1 and SELECT+R1, but these shortcuts only seem to work only while I am on the XMB.

I have looked everywhere in webman's setup to see if there wasn't anything blocking there, but I was unable to find anything that could help.

If anyone has an idea, that would be greatly appreciated :)

**Comment by aldostools** [comment]
PS2 emulation is a process that uses a lot of memory and CPU power of the PS3 console.
When a PS2 game starts, VSH and all its processes (including webman) are unloaded to load the PS2 emulator (which is basically a dedicated VSH for PS2).

As webman is not present during PS2 emulation, the fan speed must be set to a fixed speed. Also none of webman services work (ftp, http, combos, etc.)

If you need to upload or download files from the PS3, or access some webman service, you must return to XMB. This only applies for PS2 games.

**Comment by LordBubblesDev** [comment]
Ok thanks for the answer. So there is no way to swap between PS2 ISOs while ingame (the same way we would swap discs), for example to load a game after selecting cheats on codebreaker, or for multiple cd games?

**Comment by aldostools** [comment]
AFAIK that is currently possible only with physical medias on B/C or semi-B/C consoles (phat models).

Non-B/C consoles rely on ps2_netemu which is the PS2 emulator used for PS2 Classics. That emu doesn't have support for physical media.

To be able to swap ISO, it would be necessary to hack the PS2 emulator to add that function like *3141card* did patching it to show the temperatures.
