### ISSUE TITLE
Cobra 8.1 in Rebug 4.84.2

### ISSUE THREAD

**Issue by DistractedYOBA** [aldostools/webMAN-MOD#177]
Hello, I'm use last Rebug and Webman-mod. When I'm disabling Cobra, webman stops working. Console freezes if i trying use vsh and etc. Also start+select now working in xbm only.

**Comment by aldostools** [comment]
It's normal that webMAN stop working if you disable Cobra, because /dev_hdd0/boot_plugins.txt is not loaded if Cobra is disabled.

In 4.84.2 now you can load webMAN adding the path of the nonCobra edition to   /dev_hdd0/boot_plugins_nocobra.txt if you console is CEX or to /dev_hdd0/boot_plugin_nocobra_dex.txt if you converted your console to DEX mode.

**Comment by DistractedYOBA** [comment]
Ok, thanks. But, what about start+select combination?

**Comment by aldostools** [comment]
To use START+SELECT in-game, you must press PS button first, then press START+SELECT.
If you keep pressing START+SELECT for 5 seconds you will hear a beep and the popup will persistently show even if you return to the game.

To disable the persistent popup, hold again START+SELECT for 5 seconds (if you're in-game, press PS first)

**Comment by DistractedYOBA** [comment]
Yes, I know. But popup doesn't appear for me (in game) on 4.84.2. Does it work for you? VSH Warning work btw.

**Comment by aldostools** [comment]
I would have to check again when I get back home. Meanwhile I suggest you that check in http://127.0.0.1/setup.ps3 that you have enabled the shortcut for "SHOW TEMP"

**Comment by DistractedYOBA** [comment]
Yes, it's on. But only works in xmb. Thanks for help, I will be waiting.

**Comment by DistractedYOBA** [comment]
Nothing changes with new version.

**Comment by aldostools** [comment]
I test the select+start in game and it works as expected.

My suggestion is that uninstall webman, delete boot_plugins.txt, uninstall any other plugin that you could be using, reinstall the cfw if possible and reinstall the full edition of webman mod with cobra enabled.

This seems to be an issue particular to your current configuration.

**Comment by DistractedYOBA** [comment]
Im reinstal webman, now it works. Thanks.

**Comment by DistractedYOBA** [comment]
It's look like everything ok with Lan. But when i connect wifi it stops working. What internet connection do you use?

**Comment by aldostools** [comment]
It could be a hardware issue with your WiFi card or router.. It would be good that you try to isolate the problem, maybe trying other apps like multiMAN, sMAN, webMAN vanilla, ManaGunZ or Movian to check they behave the same with LAN and WiFi.

Also neighbors interference or duplicated IP also cause a lot of issues when WiFi is used.

EDIT: Answering your question.
I use LAN for the PS3 and WiFi for the laptop that I use for development and for remote control of the PS3.

**Comment by DistractedYOBA** [comment]
Ok, with android hotpost it works in-game only. What can i do with it?

**Comment by aldostools** [comment]
TBH I don't have idea... I suggest you that discuss the subject in the forum of PSX-PLACE, since it seems to be a network configuration issue, not a webman bug...

**Comment by DistractedYOBA** [comment]
I'm set static ip in my router. Now it works in-game only. I will stop there.
