### ISSUE TITLE
PS2 ISO

### ISSUE THREAD

**Issue by MkCasper** [aldostools/webMAN-MOD#178]
Have several PS2 ISO’s loading in multiman, Trying to load from webMAN-MOD, Disc are showing up in WMM but system blacks screens and fails to restart into Game.

PS3 firmware: Rebug 4.84 DEX
LV2 Kernal & Target is DEX
XMB operation Mode REBUG
Cobra Enable 8.10
WebMAN-MOD 1.47.14
MultimanCM 04.82.00
PS3 system: Firmware 4.81 [SC-35 I PL3]

**Comment by Joonie86** [comment]
The compatibility could vary depending on the game. 

Please follow this thread 

https://www.psx-place.com/threads/compatibility-list-ps2-on-ps3.1306/
