### ISSUE TITLE
Maximum storage or folder limit

### ISSUE THREAD

**Issue by tsuihak** [aldostools/webMAN-MOD#179]
I have a HD ntfs of 8tb on ps3. It is doing tests to replace 2 of 3tb, but I have 437 in the ps3iso folder and it only appears 429. Even increasing the memory to 1024. Now it follows a few questions:
1 - Do you have any limit of games in webman per storage or folder of ISOs? It was all in ISO. Before I had more games, my collection reaches 540 PS3 games and more than 60 PSX and had no problems.

2 - My collection had folders and ISOS mixed in 2 HDs in FAT32. I put everything in ISO thinking it would improve the processing of files on ps3. What do you recommend?

**Comment by aldostools** [comment]
1- Yes the is a limit calculated based on the memory assigned divided by 420.
max_xmb_items = ((u16)(BUFFER_SIZE_ALL / AVG_ITEM_SIZE));

You can try to compare the results scanning the content with MC enabled and MC disabled in the memory profile. Also try using STANDARD.

Also make sure that you disable the content scanning at startup. As other processes are starting in background, the free memory available is reduced when the system is starting.

2- There should not be difference scanning the content for games in folders or ISO.
However, the game performance is improved when you use ISO.

**Comment by tsuihak** [comment]
Unfortunately I will stay away from my PS3 for 20 days but before leaving home I did the following tests.
1 - I tried to put the option MIN memory and the webman did not load anything and locked the PS3.
2 - I copied the games to another hd in 3TB NTFS format and all the games I put in the PS3ISO folder worked. I put 160 games, including one of them that I noticed that did not appear in the NTFS of 8TB with 429 games. This test was done to check if there was a problem with some of the ISOS that were not displayed on the 8TB HD.
3 - I added more games on the 8TB NTFS HD and the recognized amount of games increased from 429 to 444. It had probably 460 isos in the folder. I did this test to see if the amount displayed on the webman was locked at 429 and to check if it was a memory problem.

Tests 1 and 2 were done with memory in the following option: MAX 1280K for PS3 games and follow a few more questions:
1 - Where do you choose MC disable and enable?
2 - If you disable the content scanning at startup, when will it load the games?

It is showing that there is incompatibility with the 8TB HD. There are successive crashes with this HD. All ISOS were made using PS3-ISO-Rebuilder 1.0.4.1 to make sure there is no problem with ISOs. As soon as I have it at home I will be doing the tests requested by you but in parallel I am going back to the 2TB of 3TB also to do more tests. I wanted to put everything into an 8TB HD because sometimes one of them was not recognized, so some people I did not know could not solve the problem. I thought that using only a hard drive would not have that kind of problem anymore. And by chance running these tests, I discovered that a dock station for 2 HDs works perfectly on the PS3 and apparently I did not see problems recognizing 2 HDs of 3TB. This will be my second choice if the 8TB HD continues to do all that work.

Thank you very much for your help and sorry for my English. I'm using google translator because I know very little.

**Comment by klahjn** [comment]
In all fairness, it has been long suggested not to use external hard drives above 2tb as they CAN cause issues.  Those issues can be sporadic as well, they can include symptoms that you are currently experiencing.  The simple solution is to use multiple 2tb or less hard drives that are known to be fully functional (no issues) w/ the ps3.  

It's also noted that makeps3iso (estwald) is supposed to be the most compatible (supposedly 100%) and genps3iso 2.0/2.1 being very close (supposedly 99.9%).

Hope that helps :)

**Comment by tsuihak** [comment]
I was able to put my 8TB HD to work in FAT32. I have 494 PS3 games in ISO in HD. First of all I had to change the 8TB HD case. I unmounted the case of the 3TB HD and put the 8TB HD. So I was able to use MBR for HD larger than 2TB. I had to use the Seagate program to boot the disk and format in NTFS. Then I used the FAT32Format to format in FAT32.
