### ISSUE TITLE
All Games are shown twice.

### ISSUE THREAD

**Issue by shad00m** [aldostools/webMAN-MOD#18]
Running 1.43.36 on Rebug 4.80.1.

In XMB under (small text) "load games with webMAN" => PS1/PS2/PS3 => Every game is shown twice.

First I thought its shown twice because of bin+cue in psx but the PS3 isos don't have that.
It's also not because of split files as small 600mb ISOs are also shown twice.

**Comment by shad00m** [comment]
Nevermind - I restarted with Webman-Mod a couple of times and nothing changed.
A Cold reboot fixed this issue and games are only shown once now and the Bigger text that says "webMAN Games" in XMB above the small "load games with webMAN" is also now shown.
I don't know what the issue was but a shutdown fixed it - not a restart.

Can be closed

**Comment by aldostools** [comment]
Thank you for your feedback. I'm glad that it's fixed now.

With the latest build it is also recommended to go to /setup.ps3 and save the settings again.
