### ISSUE TITLE
Webman Setup Freezes

### ISSUE THREAD

**Issue by shae23** [aldostools/webMAN-MOD#181]
When trying to save changes via webman Setup, the PS3 freezes, this happens on 1.14.15 through to 1.14.17. Going back to 1.14.12 fixes the freezing, able to change options and save successfully

**Comment by aldostools** [comment]
Thank you for your feedback. Could you please try this?
1-Change the system language to English
2-Uninstall webMAN
3-Reinstall it.
(In that order please!)

If that doesn't work, please try changing VSH to rebug mode in Rebug Toolbox.

I will check this issue as soon as possible...
