### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by KhangTran476** [aldostools/webMAN-MOD#183]
I using WebMan Mod 1.47.15 and I play GTA 5. Sometime I was freeze my console. That issue from version of Webman?

**Comment by aldostools** [comment]
Please check if you get the issues with a different version (newer or older).

**Comment by KhangTran476** [comment]
So, how to uninstall webMAN Mod 1.47.15 ? I want to install NEW for clean :D

**Comment by aldostools** [comment]
There should  be an Uninstall option in webMAN menu in XMB.
If there isn't one, install the latest build. Then uninstall it and run the installer again.
