### ISSUE TITLE
007 - The World Is Not Enough [SLUS-01272] gives 80028f17 error when mounting from nethost

### ISSUE THREAD

**Issue by VRtinker** [aldostools/webMAN-MOD#185]
Hello,

I'm experiencing a series of issues on the last 2 releases: 1.47.16 and 1.47.17 (I couldn't test 1.47.15 since it's not available).

Whenever I try to mount an ISO through ps3netserver (both when serving from a windows machine as well as when running ps3netserver directly from the router) I get a "404 not found" error, despite the fact that the "refresh XML" picks up all my collection, and the links to the individual files seems to be formed correctly (i.e.: they actually point to the correct location/filenames). Even though, as far as the web interface is concerned, none of my titles are found, if I try to mount anything directly from the XMB, everything works fine (which I find really odd).

Another weird thing is that when I go the "Files" section on the web interface, the network share appears only as a white text string (instead of having a folder icon, while being an hyperlink that allows browsing it) with the "< dir >" tag next to it, which is clickable (pointing correctly at "http://192.168.1.10/mount.ps3/net0"), but still producing the same "404 Not found" error.

I get the same "404 Not found" error when manually trying to mount the PKG folder on my share.

I also noticed (though unrelated) that in the "Coverflow" section, it will "only" list 492 titles, while my collection is actually larger than that.

For the time being I will stay on 1.47.14 since it works perfectly fine and because I need to be able to mount from the web interface due to the size of my collection, but also in order to be able to swap PS1 NTSC games with PAL ones - a trick I discovered to play out-of-region PS1 games - and lastly because it's the only way to avoid getting the connection crash during Remote Play, which doesn't seem to survive mounting an ISO directly from XMB.

Nevertheless, I would still be interested in finding out why this is happening!

Cheers,

**Comment by aldostools** [comment]
Please try using this test version... it should resolve /net0 and maybe some of the other issues.
This version has not been released yet.

[webMAN_MOD_1.47.18_Installer.zip](https://github.com/aldostools/webMAN-MOD/files/3115268/webMAN_MOD_1.47.18_Installer.zip)

**Comment by VRtinker** [comment]
Hi Aldo,

Thanks for getting back to me! This new test version does indeed solve the mounting issue I was experiencing as well as restoring the ability to browse the network share from the "Files" section.

The 492 titles limit in the "Coverflow" section still persist though. I guess you can't have it all! :-p

Thanks again for your support, and your continuous efforts to improve an already great software!

Cheers,

**Comment by aldostools** [comment]
For the Coverflow issue, try using a different memory profile or enable the [MC]  option for the Application Memory Container that expands the available memory to 3MB. Then refresh XML and access /games.ps3

**Comment by VRtinker** [comment]
Hey! So I tried fiddling with the different memory profiles and once again you were right, it did the trick, the "Coverflow" section lists all my titles! My interpretation of the whole memory profiling etc, was that it was aimed at increasing the memory footprint during scanning, but virtually unnecessary once the scan was complete and the Games.xml was written (unless of course you needed to scan/refresh the library again). So I've always maxed it out whenever I needed to refresh the library, but then always reverted it to "min" to minimize memory usage. Now I see that if I set it to max to detect the entire collection, but than go back to min (without rescanning afterwards), the "Coverflow" section reverts to the usual 492 titles, all the while the "Games" section still lists everything I got anyway.

As I was testing, I came across something else that's odd (this is not specific to this version, as I tested on 1.47.14 and still get the same error), although maybe this is not even related to webman (or maybe it is, I don't know).
My very first title in my PSX collection is "007 - The World Is Not Enough [SLUS-01272]": when mounting it through ps3netserver a few seconds after launching it I get error 80028f17 which google tells me it should have something to do with the disc being corrupted or something, either way some kind of medium related issue. As I found out about this whilst testing all this other stuff I didn't make much of it and wrote it off to a bad or corrupted image, but then I tested it on a pc with an emulator and it booted fine, so I copied it to a USB stick and tried it on the PS3 and it worked fine as well. I also checked the ps3netserver process on my router while the PS3 throws the aforementioned error, but it doesn't spit out any errors whatsoever. I tried a few other random PSX titles but everything works so I would exclude a general issue between net serving and PSX images; I also tried both ps1_emu.self and ps1_netemu.self but both produce the same error. Is there perhaps a difference in compatibility between HDD, USB and NETHOST?

My testbed in this particular case is a CECHA, btw.

**Comment by Joonie86** [comment]
I was able to reproduce the issue and confirmed that this does not happen when multiMAN mounts the game from net_host. it appears that the current fork of webMAN calculates wrong size for this particular game.

when mounted from nethost with webMAN MOD
FAKING to    4872800000800
Faked size to 48728

when mounted from dev_hdd0 with webMAN MOD
FAKING to    4b67800000800
Faked size to 4b678

when mounted from nethost with multiMAN
FAKING to    4b67800000800
Faked size to 4b678

@aldostools maybe able to look at the issue when he is available.

**Comment by aldostools** [comment]
The size difference could be due webMAN MOD normally uses the external netiso plugin (netiso.sprx or sman.net) which normally support MODE2/2352 psx images .

Try adding the tag **[net]** to the file name of the psxiso, then re-scan the list with SELECT+L3.

The tag **[net]** in the file name will force the plugin to use the internal netiso client which has sector size auto-detection and support images with the following sector sizes: 2048, 2336, 2352 and 2448.

NTFS, dev_usb00x and dev_hdd0 support these non-standard sector sizes by default.

EDIT:
Checking the [source code of the netiso plugin](https://github.com/aldostools/webMAN-MOD/blob/master/_Projects_/netiso/main.c#L455),  I found that it uses a "lazy" sector size detection implemented originally by deank, which is buggy:

	cd_sec_size = 2352;

	if(!(discsize%2336)) cd_sec_size = 2336;
	else if(!(discsize%2448)) cd_sec_size = 2448;
	else if(!(discsize%2048)) cd_sec_size = 2048;

The problem here is that the disc size is 726,429,312 which is a multiple of both 2352 and 2448.
The code first assumes that the sector size is 2352, but as the size is a multiple of 2448 change the sector size to 2448, causing the error. 
 
This code needs to be updated to use the sector size that I implemented in Cobra and webMAN MOD.
https://github.com/aldostools/webMAN-MOD/blob/master/_Projects_/netiso/main.c#L452-L456

EDIT 2:
The following zip contains 2 sprx that I haven't tested yet. They intend to fix the issue... 
[fix.zip](https://github.com/aldostools/webMAN-MOD/files/3189805/fix.zip)

Copy the extracted files to the following locations: 
/dev_hdd0/plugins/webftp_server.sprx
/dev_hdd0/tmp/wm_res/netiso.sprx

**Comment by VRtinker** [comment]
@aldostools 
I just tested the fix.zip and, no surprise, the issue is completely gone. Total bug sniper! I'm glad you found the time to go back to this and identify the culprit. I had the feeling I had encountered a bug more than it being a misconfiguration or other kind of user error, otherwise I would have not brought it up in the first place!

@Joonie86 Thanks for the assist at confirming I wasn't just going crazy! :-)
What's with ALL the issues being closed (at once no less). I was gonna tell @bfoot in #168 to use the armv7 binaries found in this repository instead of the one found in entware (which carries a very old build) and check that he mounted correctly his shared drive since it didn't look like that from his log...but oh well, maybe he'll read that here.

**Comment by Joonie86** [comment]
@VRtinker I closed all the old issues (mostly from 2017~2018) that have no further feedback including ones that @aldostools's not supporting. Hope you guys understand this. 

Since your issue's resolved. I'm closing this one as well. Hope you have a good day!
