### ISSUE TITLE
Fan Settings

### ISSUE THREAD

**Issue by KhangTran476** [aldostools/webMAN-MOD#186]
The Manual Fan setting is slow down like Auto.
[ v1.47.19 ]

**Comment by aldostools** [comment]
If you're using PS3HEN, set the fan to SYSCON. The PS3HEN payload still has limitations.

If you're using CFW 4.84 (eg. Rebug), please provide more details about this issue: CFW used, PS3 model, a picture of the settings in /setup.ps3, the steps to reproduce the bug, the current result, the expected result.

**Comment by KhangTran476** [comment]
I using CFW Rebug 4.84.2 DEX - PS3 Slim (CECH-25xx). The version 1.47 18 FAN is work fine until I update to 1.47.19 the fan Manual is slow down look like Auto.

**Comment by KhangTran476** [comment]
https://www.upsieutoc.com/images/2019/04/30/248A0E46-4053-43DD-80BA-FE62F97294AC.jpg

**Comment by aldostools** [comment]
Thank you for the feedback. I will check it when I return home.
The code was changed trying to add proper support for PS3HEN, but I guess I will have to revert that code.

In Rebug 4.84.2 CEX using MAMBA 3.x it worked.

**Comment by KhangTran476** [comment]
Thanks for work hard. I love webMan MOD.

**Comment by aldostools** [comment]
Could you test if this version behaves the same?
https://www.sendspace.com/file/frr2jq

I haven't reverted the code yet, but I want to be sure that it's not working before I re-implement the old code.

I tested the fan on Rebug 4.84.2 CEX mode and it's working fine. I hope it works also on DEX.

**Comment by KhangTran476** [comment]
**It worked.**

**Comment by KhangTran476** [comment]
I want to ask some things:
- If I set up "**Plugin memory usage is Max (1280KB)**", how will it be different from Min? Also does it affect the game if the game is running somewhat?
- "**Disable CFW syscalls and delete history files at system startup + Offline (Disabled - Lock PSN - Games)**" What is the main function? Is it okay if I don't check the box? I am using **SEN Enabler**.

**Comment by aldostools** [comment]
Memory usage profile is mainly used during the content scanning and folder listing.
In MAX the ftp buffer is larger, although my experience is that a larger buffer not necessarily makes faster the transfers.

On normal operations it has almost no difference.

My suggestion is that use standard, unless you have tons of games.

It is not suggested the disable the CFW on startup. So keep that option unchecked.
