### ISSUE TITLE
webMAN stop works (PS3 HFW HEN2.0) was working fine before!

### ISSUE THREAD

**Issue by Redirr** [aldostools/webMAN-MOD#187]
MY PS3 (CFW 4.84) Working amazing!! The best tools i've ever seen. Thank you so much for webMAN!

But my PS3 (HFW HEN2.0 4.84) was working great to. But after reboot PS3 for 2 ou 3 times it's just stop working

webMAN MOD 1.47.19
1) First time, jut freeze my PS3 (Trying to mount game in webMAN/PS3 MENU)
2) Reinstalled PKG and run it again (webMAN icon it's there but empty)

Then i just installed webMAN MOD 1.47.18 and it's works again! but same problem. After 2 reboot all happen again!

Settings was not opening just blank page with error! 

Thank you so much!

**Comment by Joonie86** [comment]
1.47.19 is discontinued, try 1.47.20 and report further issues.
