### ISSUE TITLE
webMAN only works after launching IRISMAN (HEN 2.0)

### ISSUE THREAD

**Issue by NiHuShu** [aldostools/webMAN-MOD#188]
So yeah basically I've had HEN 1.0.2 installed + webMAN MOD 1.47.19 and it was working fine. After updating to HEN 2.0 webMAN stopped working so I reinstalled it. Now I have a folder with webMAN and everything inside is as it should be but webMAN doesn't work. It starts to work only when I launch IRISMAN, I've found one more person who has exactly the same problem so maybe IRISMAN has something to do with webMAN

**Comment by aldostools** [comment]
Do you have the boot_plugins.txt configured in USB000?
If you don't have it, webMAN is not started when you enable PS3HEN 2.0

webMAN starts working with IRISMAN because it auto starts the webMAN when IRISMAN is launched.

**Comment by NiHuShu** [comment]
I have boot_plugins_nocobra.txt and inside /dev_hdd0/plugins/webftp_server.sprx I have the same file on /dev_hdd0/ it was working fine with this file on 1.0.2

**Comment by aldostools** [comment]
Use /dev_usb000/boot_plugins.txt

I think /dev_usb000/boot_plugins_nocobra.txt was used by PS3HEN 1.0

**Comment by NiHuShu** [comment]
Oh I've missed that it was changed. Now it's working fine. Thanks
