### ISSUE TITLE
pshen 2.0 install: an error occurred during the install operation

### ISSUE THREAD

**Issue by firepol** [aldostools/webMAN-MOD#189]
Installed pshen 2.0.0 (first time). Installed v1.47.18, installation seems fine but I have no clue how to launch webman (sorry I'm a noob) I tried to ftp in my ps3 as anonymous and it doesn't connect (connection refused) so I think the ftp server doesn't work...

I tried to install 1.47.19. I get this error:

An error occurred during the install operation.
(80029567)

I tried the Debug PKG Enabler as shown in this video: https://www.youtube.com/watch?v=g0PiTfWnd4o
Then the installation works.

In my USB stick I have copied `boot_plugins_nocobra.txt` and `boot_plugins.txt`
Content of the file is just thie 1 line: `/dev_hdd0/plugins/webftp_server.sprx`

I did not install webman, just webman-mod. Did I miss something? Not sure which program is responsible to copy `webftp_server.sprx` to my ps3 hard disk. If you can clarify the installation a bit, it would be nice.

Thx & cheers

**Comment by aldostools** [comment]
Only the installer is launched manually from XMB

webMAN MOD is launched by PS3HEN 2.0 from the path specified in /dev_usb000/boot_plugins.txt
Or use IRISMAN to launch it.

**Comment by firepol** [comment]
Actually I found already a way to make it work, see my [reddit post](https://www.reddit.com/r/ps3hacks/comments/bkyvq8/ps3_package_problems_with_ps3hen_200_multiman/).

I had to install the "Toggle QA" package, then when browsing in Game > Toggle QA > inside the Toggle QA folder I could see all these packages I installed and could not see anywhere, including webman-mod.
See here: https://imgur.com/a/EzG1edX

After running webman-mod, the fan of my ps3 slim seems to spin a lot. Is webman-mod using so many resources that the fan must cool the system like if it was heavy game running?

Or is there a way to let it run normally (no need for fan if I don't copy stuff via ftp I guess?)

**Comment by aldostools** [comment]
You can change the fan speed settings in http://127.0.0.1/setup.ps3
(replace 127.0.0.1 with the ip of your PS3 if you're accessing it from PC, smartphone or tablet)

If you don't need the fan controller, just change the setting to SYSCON mode.

**Comment by aldostools** [comment]
BTW I asked Joonie about your issue, he said: 
"likely he didn't install HAN installer then"
"HAN installer adds Install pkg files (pkg manager)"
"then installing hen support pkg required"
"so he'd better start fresh"

**Comment by firepol** [comment]
Thanks for your answer. I changed to syscon, aaah nice, it stopped making a hell of a noise.

> BTW I asked Joonie about your issue, he said:
> "likely he didn't install HAN installer then"

Ok so how to install Han installer? I got the package manager, I thought that was it... something is missing. Is there a chat, telegram or discord I can join to get help from ps3 hackers?

**Comment by aldostools** [comment]
HAN Installer  http://ps3xploit.com/help/han.html

For answer from developers go to http://www.psx-place.com/forums
They have a discord channel too
