### ISSUE TITLE
webMAM Mod blocks internet/psn? (HEN v2)

### ISSUE THREAD

**Issue by DeltaDesigns** [aldostools/webMAN-MOD#190]
After enabling HEN and webMAN auto enables, im unable to sign into PSN (I know its not a good idea at all to sign in) and gives error 80028E01 but doing a internet connection test (on wifi) fails also, it gives error 80028EA8. Disabling webman or syscalls doesnt fix it either. Using version 1.47.19, 3001A PS3
![IMG_20190505_213413](https://user-images.githubusercontent.com/50308149/57203397-bd5b8e80-6f7d-11e9-856c-018a23e097c6.jpg)

**Comment by aldostools** [comment]
Try version 1.47.20

**Comment by DeltaDesigns** [comment]
Just tried the newest version, even tried a fresh install and it still isnt working

**Comment by DeltaDesigns** [comment]
> Try version 1.47.20

**Comment by aldostools** [comment]
Try doing a full reboot or turn off and restart.

Versions previous to .20 were blocking the fw update, which works in cfw but cause issues in hen. In .20 that patch is not applied if ps3hen is detected.

**Comment by DeltaDesigns** [comment]
> Try doing a full reboot or turn off and restart.
> 
> Versions previous to .20 were blocking the fw update, which works in cfw but cause issues in hen. In .20 that patch is not applied if ps3hen is detected.

Could it be because im using the Offline HEN+plugin installer? I remember seeing that the offline HEN enabler had its detection removed

**Comment by VenomzYT** [comment]
@aldostools  Heyy man just wanted to say thanks for v1.47.20.. the fan settings in PS3 webman setup work flawless on HEN with the 3 boxes enable dynamic fan control / manual / lowest checked off n the 3 fan speed boxes set to 40% even stays at the set speed before you enable HEN ..just like on cfw #YourThaMan lol

**Comment by DeltaDesigns** [comment]
> Try doing a full reboot or turn off and restart.
> 
> Versions previous to .20 were blocking the fw update, which works in cfw but cause issues in hen. In .20 that patch is not applied if ps3hen is detected.

I installed your version of the offline HDD installer and its working now, thank you for making it. :)
