### ISSUE TITLE
1.47.20 does not load with HEN 2.0

### ISSUE THREAD

**Issue by m00nyONE** [aldostools/webMAN-MOD#191]
1.47.20 does not load with HEN 2.0. version 1.47.19 worked fine. after i installed 1.47.20 it does not load when i enable HEN. boot_plugins is configured right and the the plugin is placed in the right place ( hdd0/plugins/ )

i checked all with the file manager in MM.

this problem came when i upgraded straight. so no uninstalling or anything else before

**Comment by aldostools** [comment]
Try installing this version of PS3HAN 2.0 (it's a fork of the official with my modifications + joonie's)
https://github.com/aldostools/MAMBA_PRX_Loader/tree/master/PS3HEN_2.0.x

Then re-install webMAN 1.47.20 (maybe this step is not necessary)

**Comment by glennvantorre** [comment]
Works for me, so it's not a bug in 1.47.20. Case closed
