### ISSUE TITLE
Bug webman mod 1.47.20

### ISSUE THREAD

**Issue by Croi100** [aldostools/webMAN-MOD#193]
when you reset your ps3 and you reinstall webman mod after the reset the webman mod configuration menu page is bug and i reset my ps3 fat and slim to do something the same bug on both
![Screenshot_20190511_174408_com android gallery3d](https://user-images.githubusercontent.com/50524375/57571933-86212d80-7414-11e9-83b2-8d3d1cf26cd2.jpg)

**Comment by Croi100** [comment]
same on pc browser

**Comment by aldostools** [comment]
Sorry, but I don't see bug in the picture... Could you describe it a little more, please?

**Comment by Croi100** [comment]
it's just not the original webman mod  page that's what i meant sry

**Comment by Croi100** [comment]
She's just not as usual and it's weird right?

**Comment by aldostools** [comment]
Uncheck the option sMAN GUI and SAVE! It should look as usual.

**Comment by Croi100** [comment]
I am gonna try 😊

**Comment by Croi100** [comment]
Thanks a lot and just to know it's normal that when I load a game on multiman and I unload it and then when I load the game on my webman my ps3 freeze

**Comment by aldostools** [comment]
No, it's not normal... This issue occurs because webMAN MOD redirects a system file to the plugin wm_proxy.sprx to be able to receive the command from XMB.

However multiMAN clears all the existing redirections, including the wm_proxy, which causes the freeze.

This issue should be resolved in webMAN MOD 1.47.20. It restore the redirections when it detects that you returned to XMB.

**Comment by Croi100** [comment]
My bad u fix it nice a other bug when u install like gta 5 in multiman and u go to XMB after that u load the game (gta5) with webman mod ps3 freeze

**Comment by Croi100** [comment]
But it's not serious

**Comment by Croi100** [comment]
Do I need to close this

**Comment by aldostools** [comment]
Close it when your issue is fixed.
Currently I cannot reproduce your bug with multiMAN. The issue that I could find so far was fixed.

**Comment by Croi100** [comment]
Is that normal when i disable sycall with triangle+r2 and after press select + start I cant see the fan real speed

**Comment by Croi100** [comment]
Is written 24% but sound like 60

**Comment by aldostools** [comment]
No, it's not normal. I first need to reproduce and confirm it, then investigate why it happens.

**Comment by Croi100** [comment]
Ok

**Comment by Croi100** [comment]
Do u have the bug too?

**Comment by aldostools** [comment]
I have been busy working in PS3HEN and MAMBA payloads.
I will work on webMAN when I have some free time. I'm at work right now.

**Comment by Croi100** [comment]
O sryy

**Comment by Croi100** [comment]
Just so you know the Bug fan I have it on 47.20 but not on 47.15

**Comment by Croi100** [comment]
If u want to fix this bug fan I think is only on 47.20

**Comment by Croi100** [comment]
It's on 19 too

**Comment by Croi100** [comment]
Hi my friend I have just install webman mod on my ps3 fat and at every start she make a fan noise like 100% fan

**Comment by Croi100** [comment]
?

**Comment by Joonie86** [comment]
> Hi my friend I have just install webman mod on my ps3 fat and at every start she make a fan noise like 100% fan

Delete wmconfig, and set your desired fan speed. closing this issue.

**Comment by Croi100** [comment]
Thx😊

**Comment by Croi100** [comment]
But why I have only this on my fat

**Comment by Joonie86** [comment]
If your PS3 model is CECH"L" then this is perfectly normal behavior, it goes 100% at start up but goes down shortly after

**Comment by Croi100** [comment]
Yep

**Comment by Croi100** [comment]
Because she freeze at shutdown or just the fan make noise for nothing

**Comment by Croi100** [comment]
?

**Comment by Croi100** [comment]
I just deleted the 2 wmconfig in tmp and the wmconfig.bin just keep reinstall and my fan still make noise

**Comment by Croi100** [comment]
I think I am not gonna use webman mod's fan  on my fat and use syscon mod xD

**Comment by Croi100** [comment]
I am sad
