### ISSUE TITLE
Automount After Restart

### ISSUE THREAD

**Issue by shae23** [aldostools/webMAN-MOD#194]
Not sure if this is an issue or not, but I can't find that option anymore in version 1.4.20, you know when you restart the last game you played gets auto mounted, that's gone, or is the option hidden somewhere?

**Comment by aldostools** [comment]
The option is is the first one in webMAN Settings section of /setup.ps3
If you have English language, it should appear as "Load last-played game on startup"

I'm not at home to test it, but it was working properly the last time that I tested this feature.

**Comment by shae23** [comment]
Decided to reinstall, comes up now, thanks
