### ISSUE TITLE
Consistent Freeze in 1.47.20 in HEN (super slim)

### ISSUE THREAD

**Issue by Raflos10** [aldostools/webMAN-MOD#195]
(On super slim) As long as I wait long enough to see the "webman loaded" notice, I don't get a freeze. But if I load a game before that, everything freezes. When I reboot it checks the hdd for corruption. 

Sorry if you're already aware of this bug, or if it's only me. 
Even with this bug it's still faster than multiman or other loaders, but I figured you might want to be aware of this bug. Maybe it's possible to make the webman gui appear after the "webman loaded" notice so it isn't possible to accidentally freeze the ps3.

**Comment by Joonie86** [comment]
That's not a bug, it's expected behavior, you're not supposed to mount a game before webman is loaded.

**Comment by Raflos10** [comment]
In my opinion it's too easy to accidentally freeze the PS3 right now, but it's up to you whether you want to call it a bug or just ignore it. Maybe I don't know what I'm talking about, but is it really out of the question to just put an if-statement in there that prevents it from trying to mount a game if webman isn't ready?

**Comment by aldostools** [comment]
> In my opinion it's too easy to accidentally freeze the PS3 right now, but it's up to you whether you want to call it a bug or just ignore it. Maybe I don't know what I'm talking about, but is it really out of the question to just put an if-statement in there that prevents it from trying to mount a game if webman isn't ready?

Go to /setup.ps3, disable the startup notification of WebMAN... and  be happy.

**Comment by Raflos10** [comment]
Nice, that fixed it. It looks like it just loads so fast now that it's impossible to select the game before it loads.
I did get another freeze (possibly from clicking the game again while it's still loading?) but I wasn't able to duplicate it. If there's a log you guys want to see, I'm happy to post it, whatever helps. 
Thanks for the awesome work.

**Comment by everyonesweird** [comment]
> 
> 
> > In my opinion it's too easy to accidentally freeze the PS3 right now, but it's up to you whether you want to call it a bug or just ignore it. Maybe I don't know what I'm talking about, but is it really out of the question to just put an if-statement in there that prevents it from trying to mount a game if webman isn't ready?
> 
> Go to /setup.ps3, disable the startup notification of WebMAN... and be happy.

Hi 
where can i find the setup.ps3?
and what line to edit?

**Comment by aldostools** [comment]
http://127.0.0.1/setup.ps3

![image](https://user-images.githubusercontent.com/974897/90466310-798f8880-e0df-11ea-9108-b13195b2d3eb.png)

**Comment by aldostools** [comment]
http://127.0.0.1/setup.ps3

Click on that option to expand the section and find the option.
![image](https://user-images.githubusercontent.com/974897/90466509-020e2900-e0e0-11ea-8d78-7b7d65bb8240.png)

**Comment by everyonesweird** [comment]
> 
> 
> http://127.0.0.1/setup.ps3
> 
> Click on that option to expand the section and find the option.
> ![image](https://user-images.githubusercontent.com/974897/90466509-020e2900-e0e0-11ea-8d78-7b7d65bb8240.png)

Thanks man.
Yes this worked.
