### ISSUE TITLE
webMAN MOD 1.47.12 isue witch launching game How to Train Your Dragon [BLES00798]

### ISSUE THREAD

**Issue by abcwers** [aldostools/webMAN-MOD#196]
game downloaded from
https://www.ps3jailbreakdownloadfree.com/train-your-dragon-ps3-iso/
firmware rebug 4.82 CEX

1. problem is, when trying launch game  Train Your Dragon [BLES00798] get eror about trophy (), and
using multiman is the same eror about trophy.
2. in internet i found solution, that if i rebuild database, it can help.

after rebuild database using ps3 recovery meniu.
1. if i try do some actions witch webMAN, like launch game, restart ps3, or some directly actions, PS3 will freeze.
webman not working!!! i get eror 8071053d, when trying some webman info in browser. (nothing show)
2. But if i mounting game How to Train Your Dragon [BLES00798] iso witch multiman and launch it's working good. no erors after launch game. 
3. if i renistall webMAN game not launching, using multiman, or webman, and get same about trophy when launching game. and after some launc try. game redirected to firmware recovery, and try fix some data.

in result:
1. if rebuild database THIS game will work using multiman, but webMAN freezing ps3, not working. 
2. If i fix (reinstal) webMAN, webman will work, but THIS game not work using webman or multiman.
this isue i see only using this game [BLES00798].

**Comment by aldostools** [comment]
The freeze that you get is because Rebuild Database also deletes the boot_plugins.txt.
Therefore, when you boot, webMAN is not loaded and if you try to mount a game the VSH will freeze due the wm_proxy is not being redirected.

Regarding your issue with BLES0078 it should be a PICNIC error.

**Comment by abcwers** [comment]
so if i backup boot_plugins.txt, -->  Rebuild Database -->  recover boot_plugins.txt, (it fix webman without renistall?)
do it can help help launch [BLES00798] directly from webman directly without launching erors?

**Comment by aldostools** [comment]
> so if i backup boot_plugins.txt, --> Rebuild Database --> recover boot_plugins.txt, (it fix webman without renistall?)

yes

> do it can help help launch [BLES00798] directly from webman directly without launching erors?

Check your backup... I have this game and it boots without errors.

**Comment by Joonie86** [comment]
@abcwers we do not support those rips obtained from unknown sources. The game works fine on the latest version of webMAN MOD (1.47.20), Please try the latest and rip your own game to report further issues.
