### ISSUE TITLE
Add CORS headers

### ISSUE THREAD

**Issue by xps3riments** [aldostools/webMAN-MOD#199]
Hi, 

First of all thanks for your great work... you know...

Would be possible to add this line to all of the returning http headers:

`Access-Control-Allow-Origin: *`

This will allow us from javascript to "read" the contents of a XML by example or image.. and transform it.

Actually without this, we have "view" access to this files, but we don't have "read" access to it.

Gracias

**Comment by aldostools** [comment]
The requested header has been added to the build 1.47.21
https://store.brewology.com/ahomebrew.php?brewid=310
