### ISSUE TITLE
Change http://127.0.0.1 for result of real IP

### ISSUE THREAD

**Issue by uNbAs** [aldostools/webMAN-MOD#2]
Hi!

This not a issue only a sugestion.

I have two ps3 one for me and other for my bro, but two ps3 are in same LAN when launch a game charles detect request of 127.0.0.1 but two ps3 have diferent real IP 127.0.0.1 is a loopback.

Please change on next version

**Comment by uNbAs** [comment]
Sorry, maybe I have not expressed well, to request a change.

In my house there are 2 ps3 one has an IP 192.168.1.100 and other 192.168.1.200

When loading from a game XMB joins http://127.0.0.1/mount_ps3 request ago

To play online, you need to use a proxy so that all connections go through proxy exe, if you load a game on both consoles the request to charles is always the same http://127.0.0.1/mount_ps3, but who does the request may be 192.168.1.100 or 192.168.1.200

My suggestion is to change the code of main.c used to mount the game, so that the IP address of the physical interface is used.

Using localhost or 127.0.0.1 is an effective solution, but can cause problems when on the same network there are more than a game console, no change would ask if the proxy could fix it or if I could solve otherwise.

**Comment by aldostools** [comment]
This change is already implemented.

Just edit the language file and set the IP address of  your console (look for IP_ADDRESS in the TXT). By default it has defined 127.0.0.1, but it can be modified to any other IP.

The mount/unmount on XMB will use that IP instead localhost/127.0.0.1 as in previous versions.

If demanded, in a future version I could move that setting to the wmconfig.bin file and configure it through /setup.ps3
