### ISSUE TITLE
Sman GUI. Bug Settings 

### ISSUE THREAD

**Issue by DEX357** [aldostools/webMAN-MOD#201]
Aldo i find some bug. When i click games category in Sman GUI and I wont go to the settings button, I need click twice to the box button to settings show up. Temp, Games and other button work normaly (in one click button) only settings need to click twice. One twice open GAMES category second click open settings.

**Comment by aldostools** [comment]
Please check if the sman.htm installed by the following pkg fixes your issue.
[wMM_update_sman_gui.zip](https://github.com/aldostools/webMAN-MOD/files/3244329/wMM_update_sman_gui.zip)

**Comment by DEX357** [comment]
> 
> 
> Please check if the sman.htm installed by the following pkg fixes your issue.
> [wMM_update_sman_gui.zip](https://github.com/aldostools/webMAN-MOD/files/3244329/wMM_update_sman_gui.zip)

Yes Is work. Now is fix. Thanks Aldo
