### ISSUE TITLE
Issue with .21

### ISSUE THREAD

**Issue by LuciByte** [aldostools/webMAN-MOD#202]
After installing the most recent version of webman (1.47.21) on HEN v2.1.1, I had massive issues.

The first issue was the overheating. The fans were running on full, constantly and the LED on the playstation was flashing orange and green.

Once this issue happened, I attempted to go to the webman setup (via XMB), but it didn't open. Instead, it left me on the XMB and the loading icon in the top right infinitely ran. Edit: also tried via the web browser on my computer, and the web browser on the PS3

Next issue was not being able to run any homebrew or game while hen was enabled, due to this version of webman.

In order to try and fix this, I placed a blank boot_plugins.txt onto the usb and installed .20 over .21. This, unfortunately, didn't work. It had the same issues as .21. 

To slightly fix this, I removed the sprx from the ps3's HDD (using the method of blank boot_plugins and using multiman to delete the files)

Now I can't use webman at all, and I was hoping you (or anyone else) could help in some way?

Thank you

**Comment by Joonie86** [comment]
> After installing the most recent version of webman (1.47.21) on HEN v2.1.1, I had massive issues.
> 
> The first issue was the overheating. The fans were running on full, constantly and the LED on the playstation was flashing orange and green.
> 
> Once this issue happened, I attempted to go to the webman setup (via XMB), but it didn't open. Instead, it left me on the XMB and the loading icon in the top right infinitely ran. Edit: also tried via the web browser on my computer, and the web browser on the PS3
> 
> Next issue was not being able to run any homebrew or game while hen was enabled, due to this version of webman.
> 
> In order to try and fix this, I placed a blank boot_plugins.txt onto the usb and installed .20 over .21. This, unfortunately, didn't work. It had the same issues as .21.
> 
> To slightly fix this, I removed the sprx from the ps3's HDD (using the method of blank boot_plugins and using multiman to delete the files)
> 
> Now I can't use webman at all, and I was hoping you (or anyone else) could help in some way?
> 
> Thank you

When you run the installer, hold L1 button to install FULL edition while launching the webMAN installer. This will create boot_plugins.txt and install sprx again

**Comment by LuciByte** [comment]
> > After installing the most recent version of webman (1.47.21) on HEN v2.1.1, I had massive issues.
> > The first issue was the overheating. The fans were running on full, constantly and the LED on the playstation was flashing orange and green.
> > Once this issue happened, I attempted to go to the webman setup (via XMB), but it didn't open. Instead, it left me on the XMB and the loading icon in the top right infinitely ran. Edit: also tried via the web browser on my computer, and the web browser on the PS3
> > Next issue was not being able to run any homebrew or game while hen was enabled, due to this version of webman.
> > In order to try and fix this, I placed a blank boot_plugins.txt onto the usb and installed .20 over .21. This, unfortunately, didn't work. It had the same issues as .21.
> > To slightly fix this, I removed the sprx from the ps3's HDD (using the method of blank boot_plugins and using multiman to delete the files)
> > Now I can't use webman at all, and I was hoping you (or anyone else) could help in some way?
> > Thank you
> 
> When you run the installer, hold L1 button to install FULL edition while launching the webMAN installer. This will create boot_plugins.txt and install sprx again

I'm aware, but like I said: it still doesn't work. Because as soon as .20 or .21 are enabled, the same issues start happening again.

**Comment by LuciByte** [comment]
Fixed by quick formatting the PS3 and installing .21 first. 

@aldostools you might wanna look into this issue, quite a few people are having it.

**Comment by Joonie86** [comment]
> Fixed by quick formatting the PS3 and installing .21 first.
> 
> @aldostools you might wanna look into this issue, quite a few people are having it.

Likely caused by corrupted wmconfig or wmtmp.. which were deleted by formatting HDD. You could have deleted them manually via FTP (there are several homebrews out there for FTP access)

**Comment by LuciByte** [comment]
> > Fixed by quick formatting the PS3 and installing .21 first.
> > @aldostools you might wanna look into this issue, quite a few people are having it.
> 
> Likely caused by corrupted wmconfig or wmtmp.. which were deleted by formatting HDD. You could have deleted them manually via FTP (there are several homebrews out there for FTP access)

I did delete them via ftp. I deleted everything that referenced webman. Devil is aware of this, since he's the one that told me where all of the files were. 

Plus, they would've been replaced when reinstalling webman anyway.

So, no. It's probably not corrupted wmconfig or wmtmp.

**Comment by Joonie86** [comment]
> > > Fixed by quick formatting the PS3 and installing .21 first.
> > > @aldostools you might wanna look into this issue, quite a few people are having it.
> > 
> > 
> > Likely caused by corrupted wmconfig or wmtmp.. which were deleted by formatting HDD. You could have deleted them manually via FTP (there are several homebrews out there for FTP access)
> 
> I did delete them via ftp. I deleted everything that referenced webman. Devil is aware of this, since he's the one that told me where all of the files were.
> 
> Plus, they would've been replaced when reinstalling webman anyway.
> 
> So, no. It's probably not corrupted wmconfig or wmtmp.

wmconfig doesn't get updated automatically, it just runs previous config until you save a new one, maybe the issue was caused by corrupted cobra.cfg or xml  (they are not in tmp folder) somehow... if you could tell me how to reproduce the issue then that would be helpful for us to debug.

**Comment by LuciByte** [comment]
> > > > Fixed by quick formatting the PS3 and installing .21 first.
> > > > @aldostools you might wanna look into this issue, quite a few people are having it.
> > > 
> > > 
> > > Likely caused by corrupted wmconfig or wmtmp.. which were deleted by formatting HDD. You could have deleted them manually via FTP (there are several homebrews out there for FTP access)
> > 
> > 
> > I did delete them via ftp. I deleted everything that referenced webman. Devil is aware of this, since he's the one that told me where all of the files were.
> > Plus, they would've been replaced when reinstalling webman anyway.
> > So, no. It's probably not corrupted wmconfig or wmtmp.
> 
> wmconfig doesn't get updated automatically, it just runs previous config until you save a new one, maybe the issue was caused by corrupted cobra.cfg or xml (they are not in tmp folder) somehow... if you could tell me how to reproduce the issue then that would be helpful for us to debug.

Wouldn't those two also be removed/updated when reinstalling ofw, hfw, han and then hen? I did remove the xml files that devil told me about.

I'm not entirely sure how to reproduce this. Only a few people are getting it. But my assumption is that you would have .20 installed.
Download .21 and put it on the hard drive.
Uninstall .20 via the XMB.
Install .21.
Run the application that's on the XMB while holding L1. 
That should reproduce the issue, but I'm not entirely sure.
