### ISSUE TITLE
Admin FTP Password 1.47.21 Dex 4.84

### ISSUE THREAD

**Issue by RegistryMan** [aldostools/webMAN-MOD#203]
Unable to see ftp ability in websetup on ps3 to set password or add whitelist, but can see ipds stuff fine when loaded in full mode. Using shortcut to access admin mode R2 L2 Triangle, message in top shows admin activated but settings menu doesnt change, still no ftp modification ability. Its a useful ability to have if it works since any user can rtm into an unsecure ps3 to steal your ccid, and then into your computer accessing it even worse. If not a fix, perhaps you can recommend that last most recent version that had it working, because the only one I saw was 1.45.09 Thanks

**Comment by aldostools** [comment]
Not sure if I understand your report.

FTP settings (including password, disable service, timeout, etc.) are available in /setup.ps3 under the collapsible section "webMAN MOD Setup". 

Click on "webMAN MOD Setup" and the section will show with several options.

![image](https://user-images.githubusercontent.com/974897/58839586-5ab6ea80-8630-11e9-9f08-4f9982b72738.png)

If you're using ADMIN mode, just press L2+R2+TRIANGLE to toggle to mode in the PS3.

For remote access use:
http://&lt;ps3-ip-address>/admin.ps3?enable&pwd=&lt;password> <- enter same password entered in the PWD box shown in the picture above

**Comment by RegistryMan** [comment]
Haha I am dumb, didnt know it was clickable, looked like it was describing the group of 6 items below it.

**Comment by cyberstudio10** [comment]
After filling in Pwd in the box shown, ftp server correctly rejects empty password. However, when the correct password is entered, it gives some "Syntax error". It is actually logged on just fine. However some apps won't connect to ftp server successfully with that "Syntax error", for instance Synology File Station has a feature to set up a FTP connection, but it won't connect.

```
ncftp> open -u anonymous -p xxxxxxxx 172.16.1.29
Connecting to xxx.xx.x.xx...                                                                                                  
webMANftpd 1.47.37 MOD [NTFS:0]
Logging in...                                                                                                                 
OK
Syntax error.                                                                                                                 
Logged in to xxx.xx.x.xx.                                                                                                     
```

Well... decades ago, before there was even the www, anonymous ftp no password lets you either upload or download, but never both. Otherwise, it would have become an easy vector to spread infected files.

Thanks for the wonderful work!

**Comment by aldostools** [comment]
Thank you for your feedback.  It looks like your FTP client is sending some of the following non implemented commands:
AUTH, ADAT, CCC, CLNT, CONF, ENC, EPRT, EPSV, LANG, LPRT, LPSV, MIC, OPTS, PBSZ, PROT, SMNT, STOU, XRCP, XSEN, XSEM, XRSQ, ACCT, ALLO, MODE, REIN, STAT, STRU

In the file below I changed the response for ACCT and ALLO which are RFC 5797 mandatory:
[webftp_server.zip](https://github.com/aldostools/webMAN-MOD/files/8373582/webftp_server.zip)

You could try extracting the zip and copying the file to /dev_hdd0/plugins
If the error persists, please let me know and I will build a debug version to check what you're ftp client is sending.

**Comment by cyberstudio10** [comment]
Sorry for not turning on debug mode sooner but will test your zip, too.

```
> open -u anonymous -p xxxxxxxx xxx.xx.x.xx

LibNcFTP 3.2.6 (November 12, 2016) compiled for macosx10.14                                  
Uname: Darwin|neustadt.local|19.6.0|Darwin Kernel Version 19.6.0: Tue Feb 15 21:39:11 PST 2022; root:xnu-6153.141.59~1/RELEASE_X86_64|x86_64
Sysinfo: Mac OS X 10.15.7 (Build 19H1824)

webMANftpd 1.47.37 MOD [NTFS:0]
220: webMANftpd 1.47.37 MOD [NTFS:0]                                                         
Connected to xxx.xx.x.xx.
Cmd: USER anonymous
331: OK
Cmd: PASS xxxxxxxx

OK
230: OK in...                                                                                
Cmd: PWD
257: "/"
Logged in to xxx.xx.x.xx as anonymous.
Cmd: FEAT
211: Ext:
      REST STREAM
      PASV
      PORT
      CDUP
      ABOR
      PWD
      TYPE
      SIZE
      SITE
      APPE
      LIST
      MLSD
      MDTM
      MLST type*;size*;modify*;UNIX.mode*;UNIX.uid*;UNIX.gid*;
     End
Cmd: HELP SITE
500: Syntax error
Syntax error
Logged in to xxx.xx.x.xx.                                                                    
Cmd: CLNT NcFTP 3.2.6 macosx10.14
500: Syntax error
ncftp / > 
```

Another error, having to do with MLST

```
ncftp / > get webftp_server.sprx
> get webftp_server.sprx

Cmd: OPTS MLST type;size;modify;UNIX.mode;UNIX.uid;UNIX.gid;
Remote host has closed the connection.
Remote host has closed the connection.
Passive mode refused.
Passive mode refused.
get webftp_server.sprx: not connected.
get webftp_server.sprx: not connected.
```

```
ncftp /dev_hdd0/plugins > put webftp_server.sprx
> put webftp_server.sprx

Cmd: MLST webftp_server.sprx
Remote host has closed the connection.
Remote host has closed the connection.
put webftp_server.sprx: not connected.
put webftp_server.sprx: not connected.
```

**Comment by aldostools** [comment]
Thank you for the debug output. Most the these errors are due the use of commands that are non-implemented like OPTS, HELP, CLNT, etc.

I uploaded a new build that returns an 202 OK code, but ignores these command.
