### ISSUE TITLE
HTML site resize bug

### ISSUE THREAD

**Issue by DEX357** [aldostools/webMAN-MOD#204]
https://ibb.co/7r3PXsN
https://ibb.co/4sMQ9pw
https://ibb.co/zPJHbCZ

**Comment by aldostools** [comment]
You can test copying this [sman.htm](https://github.com/aldostools/webMAN-MOD/blob/master/_Projects_/updater/custom/dev_hdd0/xmlhost/game_plugin/sman.htm
) to **/dev_hdd0/xmlhost/game_plugin**

And copying this [webftp_server.sprx](https://github.com/aldostools/webMAN-MOD/blob/master/_Projects_/updater/custom/dev_hdd0/plugins/webftp_server.sprx) to **/dev_hdd0/plugins/**

**Comment by DEX357** [comment]
Aldo almost but PS3MAPI still hide and cant switch on/off and CPU/RSX Temp now missing 
https://ibb.co/LdgQkbd
https://ibb.co/wNFkJkK

**Comment by aldostools** [comment]
It seems that you're using the wrong version of the sprx 1.47.22

In the latest build the labels (PS3 DISC, CCAPI, PS3MAPI) are listed in the line after REMOVE CFW SYSCALLS

As you can see in the current source code there is a &lt;BR> (line break) after R2+&#8710;:
https://github.com/aldostools/webMAN-MOD/blob/master/include/setup.h#L998
<pre>
add_check_box("psc", false, STR_DELCFWSYS2, " : &lt;b>R2+&#8710;&lt;/b>&lt;BR>&nbsp; ("         , !(webman_config->combo & DISABLESH),  buffer);
</pre>

**Comment by DEX357** [comment]
I am already checking it and I will let you know in a moment

**Comment by DEX357** [comment]
Im test it but i now have some language mix xml in xmb and html problem, scal size look ok. Probably bad compilation files

**Comment by aldostools** [comment]
The issues are solved in 1.47.22 see release section.
