### ISSUE TITLE
Tekken 1 (USA) CDDA playback issues

### ISSUE THREAD

**Issue by Catarax** [aldostools/webMAN-MOD#205]
Tekken 1 (USA) on webMAN-MOD can play some CDDA stage tracks well but some others are very glitchy.

There is not the problem when playing the original disc.

Version used: webMAN MOD 1.47.21

**Comment by aldostools** [comment]
Please elaborate your bug report...
Firmware version, type (HEN, CEX, DEX), edition (Rebug, Ferrox, Habib, etc)
Path of the game (USB, HDD, NTFS, net)
Format (ISO only, ISO+CUE, BIN+CUE, IMG+CUE). If using CUE, include an example of the CUE file.
Sector size 2048, 2336, 2448, etc.
Emulator type (ps1net, ps3emu)

I would like to have a magic ball to guess what users do, but my balls are not magic yet :smile:

**Comment by aldostools** [comment]
Closed due lack of feedback in 16 days.
