### ISSUE TITLE
Hate displays .SFO and PNG files.

### ISSUE THREAD

**Issue by spotanjo3** [aldostools/webMAN-MOD#207]
.SFO and .PNG now displays title id.. Is there a way I can disabled those displayed ? I don't liked them. I just want ISO displays on my external hard drive only. NO .SFO and .PNG at all. Is there ?

**Comment by aldostools** [comment]
In /setup.ps3, remove the check mark from the option PARAM.SFO and change Info to None or Path.

Or do you mean that .SFO and .PNG are being listing in XMB or HTML?
A picture of your issue would be useful... I can't guess if there is not enough details in the bug reports.

**Comment by spotanjo3** [comment]
> In /setup.ps3, remove the check mark from the option PARAM.SFO and change Info to None or Path.
> 
> Or do you mean that .SFO and .PNG are being listing in XMB or HTML?
> A picture of your issue would be useful... I can't guess if there is not enough details in the bug reports.

Hello. Thanks for the replying asap. Those appears in External hard Drive - PS3ISO folder.. For an example:

BLESXXXXXX.iso
BLESXXXXXX.SFO
BLESXXXXXX.PNG

Hope it helps. ;)

**Comment by aldostools** [comment]
These files appear on NTFS drives when you use prepNTFS. 
If you HATE the extracted SFO and PNG files, simply don't use prepNTFS and rely on the internal prepNTFS of webMAN MOD.

prepNTFS is only needed if you use lite edition, to install large PKG files or to play MP4 or AVI videos stored on NTFS without Movian.
