### ISSUE TITLE
Error 80010009 when loading ROM

### ISSUE THREAD

**Issue by CrewMdk** [aldostools/webMAN-MOD#208]
Hello, when loading a ROM from the internal hard drive of either Super Nintendo, Arcade or Nintendo I get the error 80010009. I have installed version v1.47.22 of webMAN with PKG/ROM Launcher installed and RetroArch v1.7.7 CEX.
System software version: 4.84.2 Rebug REX Cobra 8.1 CEX.

Español/Spanish:
Hola, al cargar un ROM desde el disco duro interno ya sea de Super Nintendo, Arcade o Nintendo me sale el error 80010009. Tengo instalada la version v1.47.22 de webMAN con PKG/ROM Launcher instalado y RetroArch v1.7.7 CEX.
Versión de software del sistema: 4.84.2 Rebug REX Cobra 8.1 CEX.

**Comment by aldostools** [comment]
Error 80010009 = Operation not permitted. An error occurred during the start operation.

Maybe something changed in RetroArch 1.7.7

Please check with a different version of RetroArch (e.g. v1.0.0.2 found in Brewology)

The ROMs were working the last time that I checked the feature on Rebug 4.84.2 Cobra 8.1, but I don't have the latest build of RetroArch. I don't recall if the version that I have is 1.7.5 or 1.7.6, you can try these ones too.

You can try also with the latest beta of webMAN (currently 1.47.22.4)...

**Comment by CrewMdk** [comment]
I have tried with version 1.0.0.2 of RetroArch and the error 80010009 is still coming out. If RetroArch is eliminated, it marks the same error.
I will try with the other versions 1.7.5 and 1.7.6 of RetroArch and comment the results.

Español/Spanish:
He intentado con la versión 1.0.0.2 de RetroArch y el error 80010009 todavía sigue saliendo.  Si se elimina RetroArch, marca el mismo error.
Intentaré con las otras versiones 1.7.5 y 1.7.6 de RetroArch y comentaré los resultados.

**Comment by aldostools** [comment]
Also re-install the PKG/ROM Launcher
https://github.com/aldostools/webMAN-MOD/blob/master/_Projects_/updater/pkgfiles/USRDIR/addons/ROMS_PKG_Launcher.pkg

**Comment by CrewMdk** [comment]
Install PKG/ROM Launcher from the link and the same error keeps appearing. Format the console, install only webMAN, PKG / ROM Launcher and RetroArch v1.0.0.2, but error 80010009 continues. Test with the RetroArch 1.7.5 and 1.7.6 versions and the error 80010009 still appears.

Español/Spanish:
Instale PKG/ROM Launcher desde el enlace y el mismo error sigue apareciendo. Formatee la consola, instale solo webMAN, PKG / ROM Launcher y RetroArch v1.0.0.2, pero el error 80010009 continúa. Probe con las versiones 1.7.5 y 1.7.6 de RetroArch y el error 80010009 sigue apareciendo.

**Comment by aldostools** [comment]
Let's start from begining... There should be some step that you're missing:

1- Make sure that you have [Rebug 4.84.2](https://rebug.me/official-rebug-4-84-2-rex-d-rex-cobra-8-1-toolbox-2-03-02-mar-29th-2019/) **with Cobra 8.1 enabled**

2- Install [RetroArch 1.7.7](https://xbins.org/libretro/stable/1.7.7/playstation/ps3/RetroArch.PS3.CEX.PS3.pkg)

3- Install [PKG/ROM Launcher](https://github.com/aldostools/webMAN-MOD/releases/download/1.47.22/ROMS_PKG_Launcher.pkg)

4- Copy your SNES roms in zip format to /dev_hdd0/ROMS/SNES

Each emu support certain file formats . The other supported folders are:
"2048", "MAME", "MAME078", "MAME2000", "MAME2003", "FBA", "FBA2012", "ATARI", "ATARI2600", "ATARI5200", "ATARI7800", "JAGUAR", "LYNX", "HANDY", "HATARI", "NXENGINE", "AMIGA", "VICE", "DOSBOX", "GW", "DOOM", "QUAKE", "LUA", "O2EM", "INTV", "BMSX", "FMSX", "PCE", "PCFX", "SGX", "NGP", "NES", "FCEUMM", "NESTOPIA", "QNES", "GB", "GBC", "GAMBATTE", "TGBDUAL", "GBA", "VBOY", "VBA", "MGBA", "POKEMINI", "GENESIS", "GEN", "MEGAD", "GG", "GEARBOY", "ZX81", "FUSE", "SNES", "MSNES", "SNES9X", "SNES9X2005", "SNES9X2010", "SNES9X_NEXT", "THEODORE", "VECX", "WSWAM" 

5- Uninstall webMAN MOD...
6- Install [webMAN MOD 1.47.22](https://github.com/aldostools/webMAN-MOD/releases/latest) FULL edition... Press L1 while you're installing webMAN

7- Go to http://127.0.0.1/setup.ps3 enable **Auto Play** and save your settings.

8- Return to XMB and scan for content (press SELECT+L3) then refresh XMB (reboot, enter to an app and exit or run Reload XMB app)

TIP: You can skip the reload XMB you didn't open webMAN Games icon press before press SELECT+L3

9- Go to webMAN Games (aka "Mis Juegos") > ROMS > SNES, select you ROM and press X to launch it

10- If the steps above were done properly, when you launch the ROM, you should see a blue disc mounted and in few seconds RetroArch should be started automatically with the selected game.

**Comment by Joonie86** [comment]
> Install PKG/ROM Launcher from the link and the same error keeps appearing. Format the console, install only webMAN, PKG / ROM Launcher and RetroArch v1.0.0.2, but error 80010009 continues. Test with the RetroArch 1.7.5 and 1.7.6 versions and the error 80010009 still appears.
> 
> Español/Spanish:
> Instale PKG/ROM Launcher desde el enlace y el mismo error sigue apareciendo. Formatee la consola, instale solo webMAN, PKG / ROM Launcher y RetroArch v1.0.0.2, pero el error 80010009 continúa. Probe con las versiones 1.7.5 y 1.7.6 de RetroArch y el error 80010009 sigue apareciendo.

1. Does your retroARCH even work ? (wihtout webMAN MOD)

2. Are all cores installed per each platform? RetroARCH is useless without cores.

**Comment by aldostools** [comment]
Apparently the issue was caused by the 3.55 keys used to sign the retail EBOOT.BIN in PKG/ROM Launcher

This PKG should work without issues. It uses keys 3.50. The PKG is also updated in 1.47.22b9
https://github.com/aldostools/webMAN-MOD/releases/download/1.47.22/ROMS_PKG_Launcher.pkg

**Comment by CrewMdk** [comment]
> 1. Does your retroARCH even work ? (wihtout webMAN MOD)
> 2. Are all cores installed per each platform? RetroARCH is useless without cores.

1. RetroArch works.
2. It has all the cores available for PS3 including snes9x2010 libretro ps3 that is used for roms in the /ROMS/SNES/ folder.


> Apparently the issue was caused by the 3.55 keys used to sign the retail EBOOT.BIN in PKG/ROM Launcher
> 
> This PKG should work without issues. It uses keys 3.50. The PKG is also updated in 1.47.22b9
> https://github.com/aldostools/webMAN-MOD/releases/download/1.47.22/ROMS_PKG_Launcher.pkg

Install ROMS/PKG Launcher of the link and I already worked with RetroArch v1.7.7.
