### ISSUE TITLE
1.47.22 FTP Connection error with transfer many small files

### ISSUE THREAD

**Issue by sin89rus** [aldostools/webMAN-MOD#209]
webman mod 1.47.22 beta 4/5 - ftp lost connect when transfer many small files
webman mod 1.47.21 - all OK

**Comment by aldostools** [comment]
Thank you for your feedback.

Please check latest beta of 1.47.22 fixes your issue.
https://github.com/aldostools/webMAN-MOD/releases/latest

**Comment by Joonie86** [comment]
I can confirm this is still an issue when transferring multiple files.. (1.47.23.3)

**Comment by aldostools** [comment]
Please try with 1.47.23.4 beta, increased the default RECV timeout to 86400 seconds.

If it still get errors, try setting a timeout of 240 minutes in /setup.ps3 and report back if possible.

**Comment by Joonie86** [comment]
> Please try with 1.47.23.4 beta, increased the default RECV timeout to 86400 seconds.
> 
> If it still get errors, try setting a timeout of 240 minutes in /setup.ps3 and report back if possible.

EDIT*

After I increased the number of files being transferred, now I can transfer 5 at a time without any issues.

![image](https://user-images.githubusercontent.com/8692743/59695380-fef77000-919e-11e9-89a4-e04060c0186d.png)

@sin89rus Please try the latest beta4

**Comment by Joonie86** [comment]
@aldostools However, I do not think the issue's 100% fixed. I tried some game with many small files and now a few files got stuck at the last transfer which never completed. (This doesn't happen on Openps3ftp)

![image](https://user-images.githubusercontent.com/8692743/59697811-5dbee880-91a3-11e9-9a2b-a644ab12fe43.png)

**Comment by aldostools** [comment]
Could you test changing the timeout in /setup.ps3 to 1 minute?

EDIT: Even if the download get stuck it would finish in 1 minute.

EDIT2: 1.47.23.**5 beta** is available with more improvements related to this issue.

**Comment by aldostools** [comment]
Tested 1.47.23 betas 6 to 8. All could transfer small files without errors on FileZilla.
Last 2-3 sessions timeout after 20 seconds. After that timeout, the ftp continue working as expected.

If I don't receive additional feedback, the issue will be closed soon.

**Comment by Joonie86** [comment]
> Tested 1.47.23 betas 6 to 8. All could transfer small files without errors on FileZilla.
> Last 2-3 sessions timeout after 20 seconds. After that timeout, the ftp continue working as expected.
> 
> If I don't receive additional feedback, the issue will be closed soon.

![image](https://user-images.githubusercontent.com/8692743/59933989-5bf16100-93ff-11e9-858d-38e60598277e.png)

Not sure why this is happening, these 4 files are stuck and don't complete.

![image](https://user-images.githubusercontent.com/8692743/59934037-7cb9b680-93ff-11e9-9bcc-1b9884fa2534.png)

**Comment by aldostools** [comment]
Ok, I will try change the "STOR" method... I'll make it return error if it stops to receive data .
Currently it returns error when the socket returns -1

BTW Are you writing to hdd0 or to ntfs? Or is it receiving data?

**Comment by Joonie86** [comment]
> Ok, I will try change the "STOR" method... I'll make it return error if it stops to receive data .
> Currently it returns error when the socket returns -1
> 
> BTW Are you writing to hdd0 or to ntfs? Or is it receiving data?

I was transferring from PC to dev_hdd0/GAMES

**Comment by aldostools** [comment]
Hmmm it actually sends FTP_OK_226 when it stops receiving data.

I added a timeout of 20 seconds to data socket, to prevent it to get stuck.
You can try compiling with this [ftp.zip](https://github.com/aldostools/webMAN-MOD/files/3315235/ftp.zip) or wait until I get home.

**Comment by Joonie86** [comment]
> Hmmm it actually sends FTP_OK_226 when it stops receiving data.
> 
> I added a timeout of 20 seconds to data socket, to prevent it to get stuck.
> You can try compiling with this [ftp.zip](https://github.com/aldostools/webMAN-MOD/files/3315235/ftp.zip) or wait until I get home.

![image](https://user-images.githubusercontent.com/8692743/59936999-2d2ab900-9406-11e9-965e-a5f32109e4ab.png)

Just tried your latest changes, and it seems a lot better but still two files (out of 900+ files) didn't complete.

**Comment by aldostools** [comment]
Maybe it's stuck receiving PASV data... this [ftp.zip](https://github.com/aldostools/webMAN-MOD/files/3315453/ftp.zip) sets a 20 seconds RECV timeout to PASV & RECV ports.

Also check that you have set FTP Timeout = 0 in /setup.ps3

**Comment by Joonie86** [comment]
> Maybe it's stuck receiving PASV data... this [ftp.zip](https://github.com/aldostools/webMAN-MOD/files/3315453/ftp.zip) sets a 20 seconds RECV timeout to PASV & RECV ports.
> 
> Also check that you have set FTP Timeout = 0 in /setup.ps3

![image](https://user-images.githubusercontent.com/8692743/59940084-a4644b00-940e-11e9-905c-643b35261126.png)

Yeah it's been set as 0 for the whole time.

**Comment by aldostools** [comment]
If it still gets stuck with the latest changes, only the main ftp connection is left for a timeout.

Currently the main ftp connection uses the default timeout of the socket. Only PASV and data connections get a specific timeout of 20 seconds (configurable using the SITE TIMEOUT secs or the timeout in /setup.ps3).

**Comment by Joonie86** [comment]
> If it still gets stuck with the latest changes, only the main ftp connection is left for a timeout.
> 
> Currently the main ftp connection uses the default timeout of the socket. Only PASV and data connections get a specific timeout of 20 seconds (configurable using the SITE TIMEOUT secs or the timeout in /setup.ps3).

![image](https://user-images.githubusercontent.com/8692743/59940812-84ce2200-9410-11e9-9310-d2b06611381a.png)

Yup it still does that for a few files. I'll try 1 minute.

**Comment by aldostools** [comment]
This [ftp.zip](https://github.com/aldostools/webMAN-MOD/files/3315520/ftp.zip) sets a 20 seconds RECV timeout to all connections (conn_s_ftp, data_s & pasv_s)

If it still gets stuck, I don't know where else I can set a timeout.

**Comment by Joonie86** [comment]
> > If it still gets stuck with the latest changes, only the main ftp connection is left for a timeout.
> > Currently the main ftp connection uses the default timeout of the socket. Only PASV and data connections get a specific timeout of 20 seconds (configurable using the SITE TIMEOUT secs or the timeout in /setup.ps3).
> 
> ![image](https://user-images.githubusercontent.com/8692743/59940812-84ce2200-9410-11e9-9310-d2b06611381a.png)
> 
> Yup it still does that for a few files. I'll try 1 minute.

after I set it to 1 minute, still stuck at these two files (they are random each time), I'll try the next change.

![image](https://user-images.githubusercontent.com/8692743/59941529-40438600-9412-11e9-9f86-28893caeeceb.png)

**Comment by Joonie86** [comment]
> This [ftp.zip](https://github.com/aldostools/webMAN-MOD/files/3315520/ftp.zip) sets a 20 seconds RECV timeout to all connections (conn_s_ftp, data_s & pasv_s)
> 
> If it still gets stuck, I don't know where else I can set a timeout.

*EDIT, Re-testing

**Comment by aldostools** [comment]
I think I will update beta 9 with the last ftp.h that you tested when I get home... I don't have idea what other changes I can do.

BTW Are you using the default settings in FileZilla? All my transfers completed fine after a few seconds.

**Comment by Joonie86** [comment]
> I think I will update beta 9 with the last ftp.h that you tested when I get home... I don't have idea what other changes I can do.
> 
> BTW Are you using the default settings in FileZilla? All my transfers completed fine after a few seconds.

Yes default  setting in Filezilla, the latest one seems a lot better. so far only one got stuck.

**Comment by aldostools** [comment]
I did my tests sending PS2CONFIG folder (+2000 files) several times and all transferred fine.

**Comment by Joonie86** [comment]
> I did my tests sending PS2CONFIG folder (+2000 files) several times and all transferred fine.

![image](https://user-images.githubusercontent.com/8692743/59942537-d2e52480-9414-11e9-8204-4c9d057f7071.png)

Only one file got stuck this time., retrying now works too (previously I had to reboot to complete the transfer). I think it's good now.

**Comment by aldostools** [comment]
:man_facepalming: LOL the heart is not for you... it's for the issue that seems solved :smile:

**Comment by sin89rus** [comment]
webman mod 1.47.24 - transfering many small files via FTP - OK.
Problem solved, good job
