### ISSUE TITLE
[Feature] Mute XMB sounds (startup, ¿selected game?)

### ISSUE THREAD

**Issue by 444nonymous** [aldostools/webMAN-MOD#21]
A. To mute the startup PS3 chime you just have to replace the files "coldboot_multi.ac3" and "coldboot_stereo.ac3" located in "dev_flash\vsh\resource\" with muted ones.

I did it myself because I find it really annoying. These are the files, same size and everything, just edited the volume to 0%. So muted. Rename to rar. You can include the option in webman if you feel it's worth it. 

[coldboot-muted.rar.pdf](https://github.com/aldostools/webMAN-MOD/files/519806/coldboot-muted.rar.pdf)

B. when the PS3 is turned on, the last XMB launched program is auto selected. If it was a game with music preview, it can't be muted. Maybe there could be an option to mute sounds in previews. Just an idea.

**Comment by aldostools** [comment]
A. Thank you for the muted sound files :) I was needing them. I also find the boot sound very annoying.

I don't plan to include them in webMAN, since it's a CFW mod. I think you can suggest it to DeViL303 to include it in his XMBPD store. If you prefer I can tell him.

B. Very good idea. I haven't tried but I think that redirecting /dev_bdvd/PS3_GAME/SND0.AT3 to a another location should solve the issue.

I'll do some tests. If I have success, I may include in /setup.ps3 the option to mute SND0.AT3 on startup.

**Comment by aldostools** [comment]
Now there is a "No SND0.AT3" option in /setup.ps3
http://aldostools.org/temp/test/webMAN_MOD_1.45.01_Updater.pkg

**Comment by 444nonymous** [comment]
Webman is broken in the test build.

No FTP and "the page cannot be accessed" in the web browser when you try to do anything.

**Comment by 444nonymous** [comment]
I've been able to test another buid, but it is very buggy, icons and "save / restart / etc" in webman options are missing.

The feature works fine for the current loaded game using webman, both autoloaded at start or manually loaded at any time. It also works after mounting / unmounting  successive games. So no problems.

It does not work if the last game played was a PSN installed game with it's own permanent launch icon in the Games root column. I'm not sure if webman can do anything to disable the SND0.AT3 when selecting games / apps loaded from different paths in the hdd instead of /dev_bdvd/

**Comment by 444nonymous** [comment]
Another idea. Maybe you can force "webman games" icon to be selected when turning the PS3 on, instead of the icon below (1st icon of APP / PSN game in Games Column root)

**Comment by 444nonymous** [comment]
Tested and working fine for the iso loaded in the final build https://github.com/aldostools/webMAN-MOD/commit/435f0056fa143cfee1465a06226beabe294497ab
