### ISSUE TITLE
Webman mod on ps3 with broken bt/wifi module

### ISSUE THREAD

**Issue by kot7k** [aldostools/webMAN-MOD#212]
Hi, just posted on psx-place but will leave you the report here.
Webman mod is not working (or is just partially working) on ps3 with broken bt/wifi modules.
It doesnt let you access configuration, nor cpu temp, nor any of the options, it always give you error 8071053d, you talked about it here https://www.psx-place.com/threads/webman-errors-8071053d-80130181-80130186.9758/ , but im just asking if you could take another look. The network work on my ps3, i have it connected by cable and i can download things, there must be some conflict for having a faulty bt/wifi module, but couldnt be possible to remove that check someway? 
Deank's Sman uses a similar configuration page (at least the file is called the same) and it works, doesnt give me any error. 

For more information, i used mfw to patch rebug 4.84.2 only removing bt module (cause otherwise it wouldnt let me install it). 
I said "partially working" cause when i tried to install webman mod, the fans started to work other way, like the dynamic fan control was working, but like i said when i tried to use configuration it gave me errors. I also tried to access configuration from pc but didnt show anything.

**Comment by aldostools** [comment]
Most of webMAN's services rely on network. ftp, http, netsrv, xmb proxy, setup, file manager, all use network.  If network interface is not working, you will have limited functionality. 

Maybe you can try accessing some of the functions using the combos and sLaunch GUI.
I don't know how sMAN could be working on your system. Both plugins use same methods.

**Comment by kot7k** [comment]
Like i said, i have network, just not wireless one, i have wired network. 
If you want to debug it i can make all the tests you want and provide you the info.
I didnt do anything special for sMan to work, just copied boot_plugins.txt and sman.sprx to my ps3 hdd. With webman i used the pkg here on github to install it.

Could it be possible to disable the checks for network if there are any? just to make a test.

**Comment by aldostools** [comment]
As I mentioned in my previous post, I don't know how sMAN is working, but webMAN MOD don't.
Both plugins work in a similar way...

My BT/Wifi are working, so it's hard for me to fix that kind of issues...
You should do the tests yourself and provide any info that you find relevant, like these functions work with "these" settings, these don't work with "those" settings... 

or simply repair the BT/Wife module :)
There are some videos in Youtube that claim that they help to fix it.

**Comment by kot7k** [comment]
I can't modify any of the settings cause it doesnt let me access the settings menu.
I know that would be too much for this... but i guess if you wanted, you could reproduce the issue using mfw to remove the bt module on the cfw you were using, but as you have a working bt module i dont know if it would work for you anyways.
I have a ps3 slim, bt module is in the motherboard and tbh i dont really wanna mess a lot with it, i would rather stick with sman (wich is still great) if i dont have a better option.
If you are still interested in this i will do some more test next week when i could get a little time. 

By the way, the guy on the post i mentioned before said this at that time: 


 Please find below my results from testing:

    Action : Result
    webMAN MOD setup : 8071053d error
    webMAN MOD temperature : 8071053d error
    PS3 browser "127.0.0.1" : 8071053d error
    FTP using mmCM server : works (no error)
    FTP using rebug toolbox server : works (no error)
    FTP using webMAN MOD server : ECONNREFUSED - Connection refused by server
    input PS3 IP address in PC browser : unable to connect
    deleted "wmconfig.bin" and "wmtmp" : all of the above now works temporarily until full shutdown (upon restart, need to delete again to before being able to access webMAN MOD setup)
     
I will make tests when i have time but i think they will be exactly the same as this guy.

**Comment by aldostools** [comment]
The error 8071053d is connection refused by server. So all errors are the same.

Try deleting /dev_hdd0/tmp/wmconfig.bin

If everything works after delete it, you can add the following line to /dev_hdd0/boot_init.txt
del /dev_hdd0/tmp/wmconfig.bin

**Comment by aldostools** [comment]
In [beta 1.47.23.3](https://github.com/aldostools/webMAN-MOD/releases/download/1.47.23/webMAN_MOD_1.47.23.3_beta_Installer.pkg) I added a the script command: nobind, it skips the remote ip check performed by ftp & http servers.

To use the feature, open notepad, enter the word "nobind" (do not include the quotes), press enter and save it to /dev_hdd0/boot_init.txt, then reboot the system.

**Comment by kot7k** [comment]
Hi, first of all thank you for trying to fix the problem.

First of all i formated my ps3 hdd to start from scratch.
I tried the steps you described but it keeps me giving error 8071053d . For additional info it gives me "webman not ready" when i try to use the options to uninstall webman, restart ps3 or shutdown ps3.
After this, i also tried to delete wmconfig.bin and wmtmp like the guy from the forum post said, but it didnt work for me neither (error 8071053d).
Edit: I tried multiman and it also works no problems, tried its ftp and i can connect from my pc. When i try the same thing with webman mod it gives me connection refused.
Edit2: another test... sman configuration and scaning works good but i get connection refused also with its integrated ftp. So far the only ftp working was multimans.

**Comment by aldostools** [comment]
Thank you for your feedback... for the moment I don't have a solution.

The message 'webMAN not ready' comes from the wm_proxy.sprx that cannot connect to the http server using the loopback address; http://127.0.0.1

The nobind command removed the unique check that I am aware could refuse the connection.
If it didn't work, you'll have to settle with sMAN & multiMAN, which are very good options.

**Comment by kot7k** [comment]
Well, yeah, thank you for your time and if you find out something on the future i will be happy to test

**Comment by aldostools** [comment]
Closed due it is not possible for me to reproduce the issue on a working system.

**Comment by AceCuba** [comment]
any solution to this issue in 2023

**Comment by Bliokatana** [comment]
hi guys i have a problem with webman i installed webman on my PS3 console with a bluetooth and wifi problem all the functions on webman don't work and i can't even uninstall the application on my console is there anyone who can help me

**Comment by aldostools** [comment]
Try installing 4.90 Evilnat CEX noBT. If you're using a non-CFW compatible console, you will have to fix the BT/Wifi module.

If you're looking to uninstall webMAN MOD, here is how you can delete the installed files manually.
https://github.com/aldostools/webMAN-MOD/wiki/~-Uninstalling-webMAN-MOD

**Comment by Bliokatana** [comment]
thank you very much for your answer I uninstalled webman In this city where I live, there is no one who fixes these problems. I will try to fix it. I think that there is no solution to this problem. There is no program that is compatible with devices that have this problem. Thank you very much, my friend, for your time and interest.

**Comment by iVirtualPlays** [comment]
> Most of webMAN's services rely on network. ftp, http, netsrv, xmb proxy, setup, file manager, all use network.  If network interface is not working, you will have limited functionality. 
> 
> Maybe you can try accessing some of the functions using the combos and sLaunch GUI.
> I don't know how sMAN could be working on your system. Both plugins use same methods.
> 

I have the same issue, has this issue been fixed? Or is Webman still DRM based?

**Comment by aldostools** [comment]
webMAN MOD is not DRM based. Indeed most of the content that is mounted through webMAN MOD are disc content (ISOs and games folders) which are DRM-less.

Since build 1.47.48m, wm_proxy allows to mount most of the game types with **webMAN MOD unloaded**.

While webMAN MOD uses a network interface (through the web server) to receive the web command, wm_proxy calls the Cobra API directly without call webMAN MOD.
