### ISSUE TITLE
Custom combo for PS button

### ISSUE THREAD

**Issue by ghost** [aldostools/webMAN-MOD#214]
Idea is to add combo that activate PS button push state when used. Just combo that "push PS button". Not sure is even possible, but hey, if you don't ask, you won't find out. 

Why? There are many users that don't own DS3, and their knock-off controllers don't have PS button, or have, but don't signalize ps3 that pad is capable to use it. 
This also apply to DS4 controller that is getting popular lately. 

Or maybe something like this is already doable with current version? But i just can't find it.
PS. I can't add labels, but enhancement / feature request fit here nice.

**Comment by aldostools** [comment]
The pad emulation service already does it.

/pad.ps3?psbtn

Also there is a virtual pad available @ http://pad.aldostools.org which can be used from a smartphone, tablet or PC. You can use it to press PS button too.
