### ISSUE TITLE
List of games is not ordered correctly

### ISSUE THREAD

**Issue by paulfschilling** [aldostools/webMAN-MOD#217]
I know it's not very important, but it bothers me lol. 

I deactivated to not show the titles of PARAM.SFO, so it shows me correctly the names of the folders of the games, but they are not shown alphabetically correct.

For example, for the Modern Warfare saga, I renamed them as: 
Modern Warfare
Modern Warfare2
Modern Warfare3

It should show that way, but it shows them in this way: 
Modern Warfare3
Modern Warfare2
Modern Warfare

Another example, with the saga of Motor Storm, it shows:
Motor Storm2
Motor Storm
Motor Storm3

I tried putting a space before the numbers but its the same. It happens for all games named like this, including PSX, PS2, PSP.

I hope you look at that, only if you have time. Thank you very much for your work.

**Comment by aldostools** [comment]
Due the limited memory available, the sort key only use the first 6 characters of the name.
There are some hacks used to improve the sort order, but not always is possible.

You can check if this [webftp_server_1.47.23.8.zip](https://github.com/aldostools/webMAN-MOD/files/3312444/webftp_server_1.47.23.8.zip) has better results... it searches for the last number in the name and include it as the 6th character of the sort key.

Extract webftp_server.sprx from the zip and use FTP to upload it to /dev_hdd0/plugins

**Comment by paulfschilling** [comment]
Tested. Fixed for the Motor Storm saga and others. Call Of Duty saga still weird:
Call Of Duty Ghosts
Call Of Duty Advanced Warfare
Call Of Duty Black Ops
Call Of Duty World At War
Call Of Duty Modern Warfare
Call Of Duty Black Ops2
Call Of Duty Modern Warfare2
Call Of Duty Modern Warfare3
I guess it's for the limit of the 6 characters

**Comment by aldostools** [comment]
As I mentioned earlier, the sort key is only 6 characters. It's hard to get a proper sort with that small amount  of characters. 

I think a possible workaround could be to add a number to the end of the name.

Call Of Duty Modern Warfare - 1
Call Of Duty World At War - 2
Call Of Duty Modern Warfare2 - 3
Call Of Duty Black Ops - 4
Call Of Duty Modern Warfare3  - 5
Call Of Duty Black Ops2 - 6
Call Of Duty Ghosts - 7
Call Of Duty Advanced Warfare - 8

or

Call Of Duty Advanced Warfare - 0
Call Of Duty Black Ops - 1
Call Of Duty Black Ops2 - 2
Call Of Duty Ghosts - 3
Call Of Duty Modern Warfare - 4
Call Of Duty Modern Warfare2 - 5
Call Of Duty Modern Warfare3  - 6
Call Of Duty World At War - 7

The important point here is the saga is at least grouped.

A third option is :
Call Of Duty 1 Modern Warfare
Call Of Duty 2 World At War
Call Of Duty 3 Modern Warfare II  <-- notice that I changed the 2 to the letters II
Call Of Duty 4 Black Ops
Call Of Duty 5 Modern Warfare III
Call Of Duty 6 Black Ops II
Call Of Duty 7 Ghosts
Call Of Duty 8 Advanced Warfare

**Comment by paulfschilling** [comment]
Call Of Duty Advanced Warfare - 0
Call Of Duty Black Ops - 1
Call Of Duty Black Ops2 - 2...
Doing this way is perfect. Of course, the important thing is that at least they are all together. Thanks for your time.
