### ISSUE TITLE
Prepare actual ps3netsrv builds for various platforms

### ISSUE THREAD

**Issue by memegauste** [aldostools/webMAN-MOD#218]
I saw there were changes in ps3netsrv code and still builds in bins are outdated. It's not hard to compile project but maybe we should prepare actual builds for Windows/Mac/Linux and ARM not only x86 platforms too?

**Comment by aldostools** [comment]
Make the builds, confirm they are working and add a pull request to the repository. 
I'll be glad to accept them.
