### ISSUE TITLE
[PS3HEN] Screenshot save is not working since 1.47.21

### ISSUE THREAD

**Issue by Joonie86** [aldostools/webMAN-MOD#220]
Currently tested on HEN 2.3.0, and screenshot feature is broken when wMM is loaded on HEN launch.

![image](https://user-images.githubusercontent.com/8692743/59968242-583b0880-94eb-11e9-80a2-dd75a021aacf.png)

*EDIT

it works fine on 1.47.20 but not since 1.47.21. do you have any clues?

Note : (this doesn't happen on CFW w/ VSH patched for screenshot)

**Comment by Joonie86** [comment]
@aldostools 

I did more testing and here's the result

https://github.com/aldostools/webMAN-MOD/commit/2aad059563cc426d8bbfbb61b79663b782c85760 // works
https://github.com/aldostools/webMAN-MOD/commit/45a74e5a113eca60e5426370b8eee49db8603ad5 // broken

Possible cause?

![image](https://user-images.githubusercontent.com/8692743/59968453-02685f80-94ef-11e9-9d92-836504cb02cd.png)

**Comment by aldostools** [comment]
It seems that the patch in this line conflicts with the patch applied by PS3HEN
https://github.com/aldostools/webMAN-MOD/blob/master/main.c#L4134

This [webftp_server.zip](https://github.com/aldostools/webMAN-MOD/files/3317244/webftp_server.zip) doesn't apply the patch on PS3HEN... it will be applied only on CFW

	if(!payload_ps3hen) { ENABLE_INGAME_SCREENSHOT }

**Comment by Joonie86** [comment]
> It seems that the patch in this line conflicts with the patch applied by PS3HEN
> https://github.com/aldostools/webMAN-MOD/blob/master/main.c#L4134
> 
> This [webftp_server.zip](https://github.com/aldostools/webMAN-MOD/files/3317244/webftp_server.zip) doesn't apply the patch on PS3HEN... it will be applied only on CFW
> 
> ```
> if(!payload_ps3hen) { ENABLE_INGAME_SCREENSHOT }
> ```

Yeah I commented that line earlier which fixed my issue and your fix also works.

![image](https://user-images.githubusercontent.com/8692743/59968556-4d36a700-94f0-11e9-86fd-792054dd43b1.png)
