### ISSUE TITLE
Scan for games on the stealth folder "/video" - This feature does not work

### ISSUE THREAD

**Issue by f41lbl0g** [aldostools/webMAN-MOD#221]
In the webman mod features it says Scan for games on the stealth folder "/video", yet isos put in the /video folder do not show up after rescanning. This feature is listed on the readme.

**Comment by aldostools** [comment]
It says "Scan for games on the stealth folder "/video". The  text doesn't specify ISO.
Did you try with JB folders in /dev_hdd0/video folder? 

This is one of the early features that Zar & Matsumot0 implemented when they started the project.
They only added support to JB folders... If I recall correctly I added support for ISO, but I could have reverted it due some issues that I don't recall right now (I have to check this feature again). Honestly I never liked this feature 😄

**Comment by aldostools** [comment]
I tested the feature again and the games in /dev_hdd0/video are being listed.

Closing the issue.
