### ISSUE TITLE
suggestion join split files

### ISSUE THREAD

**Issue by fantasmaxd** [aldostools/webMAN-MOD#222]
to add large file join function larger than 4gb in folder and pkg format games

**Comment by aldostools** [comment]
For large package files, copy them to /PKG folder in NTFS drive (or pendrive) and scan it with prepNTFS.
prepNTFS will create a fake ISO in BD & DVD section, and you will be able to install the pkg directly from NTFS drive.

Or create a split ISO containing the large PKG, if you need to use a FAT32 drive.

A third solution is to using the PKG Split of my PS3 Tools Collection. It will split the PKG in smaller packages, always that the original pkg don't containg files larger than 4GB.

A fourth solution is to rename the split files as .66600, .66601, etc. then use multiMAN or IRISMAN to join them into the internal HDD,

**Comment by fantasmaxd** [comment]
games with large files like the last of us and gran turismo 6, do not work in webman only in multiman, because in multiman has the function of joining the big file inside the backup

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by aldostools** [comment]
Ok, I see your point...

These games should be converted to ISO. The split *.666xx is the old method used prior we have ISO support.

It  requires to join the *.666xx in the internal HDD, then use lv2 map path to redirect the large file to hdd0. I don't like the idea of keep supporting these split files.

For Last of Us and Uncharted, if you extract the PSARC files, you can play these games directly from USB without split files.

**Comment by fantasmaxd** [comment]
OK thank you for the attention

**Comment by ghost** [comment]
Hello.
 With which tool can I extract psarc files?  Thank you.

**Comment by fantasmaxd** [comment]
aldostools, after it extracts I leave the extracted files in the same folder that was the psarc?

**Comment by aldostools** [comment]
IIRC the extracted files should be in a folder with the same name of the psarc.

**Comment by fantasmaxd** [comment]
ok, thank you
