### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by RandQalan** [aldostools/webMAN-MOD#223]
Just a suggestion add rip to ISO to stop all the hatters blaming webman mod for bsod.
The reason most complain about ISO rips some code in NTSC and other rips do not work properly with prepNTFS. EX. on MM you have to clear cache then on MM and then res-can with prepNTFS to work otherwise you get BSOD 

I know this is a major undertaking but would salve almost all problems people report at place with BSOD you could just tell them to rip it with your WWM

**Comment by aldostools** [comment]
Hello RandQalan. Thank you for your feedback.

I don't think rip to ISO is necessary in webMAN MOD.

We already can rip to ISO on PS3 with IRISMAN and mmCM...
Also it's possible to create ISO with webMAN MOD if ps3netsrv is used.

The recent BSOD reports were caused mostly by PS3HEN 2.2.2... PS3HEN 2.3 seems to have solved most of the BSOD issues.
