### ISSUE TITLE
Cannot build ps3netsrv 20190624

### ISSUE THREAD

**Issue by nl6720** [aldostools/webMAN-MOD#224]
ps3netsrv 20190624 doesn't build (using gcc 9.1.0).

```
$ chmod +x Make.sh
$ ./Make.sh
g++    -c -o main.o main.cpp
cc -Wall -I. -std=gnu99 -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64   -c -o compat.o compat.c
compat.c: In function ‘open_file’:
compat.c:352:10: error: ‘INVALID_HANDLE_VALUE’ undeclared (first use in this function)
  352 |   return INVALID_HANDLE_VALUE;
      |          ^~~~~~~~~~~~~~~~~~~~
compat.c:352:10: note: each undeclared identifier is reported only once for each function it appears in
make: *** [<builtin>: compat.o] Error 1
```

**Comment by aldostools** [comment]
Try changing the line 352 in **compat.c** from _return INVALID_HANDLE_VALUE;_ to:
<pre>
return INVALID_FD;
</pre>

I should had used INVALID_FD. This is how it is declared in **compat.h**:

For Win32:
<pre>
#define INVALID_FD	INVALID_HANDLE_VALUE
</pre>
For non Win32:
<pre>
#define INVALID_FD	-1
</pre>

I will commit this update later.

**Comment by nl6720** [comment]
It builds successfully when changing that line.
After you commit the fix, please also update the zip archive in [releases](https://github.com/aldostools/webMAN-MOD/releases).
