### ISSUE TITLE
Fan control settings odd

### ISSUE THREAD

**Issue by bert-w** [aldostools/webMAN-MOD#228]
I am disabling `Enable dynamic fan control`, but after save and reboot the option is still checked.

Also the UI is a bit weird, because when you disable that checkbox it automatically picks the `Auto #2` radio button.

What is the intended behaviour here? I just want the normal fan operation back because the custom one is going up and down a lot.

**Comment by aldostools** [comment]
Thank you for your feedback. I will check this issue in the weekend.

"Auto #2" is not intended to be a default option...

**Comment by aldostools** [comment]
Issue is fixed in build 1.47.24.4 beta.
