### ISSUE TITLE
How does one mount a BDMV folder with webman?

### ISSUE THREAD

**Issue by Gunzzo** [aldostools/webMAN-MOD#229]
First I want to thank you for the excellent work done to run BD / DVD iso and apologize if I'm not posting in the right place. I would like to know if it would be possible to make folders in BDMV have the same behavior as a BD.iso since most of these files come in folders and their conversion to .iso can take a long time when you have many of these files. 

Thank you so much for everything that has been done, and I am waiting for good news.

**Comment by aldostools** [comment]
AVCHD/BDMV are not supported directly by webMAN. I don't have experience with these formats either.

Maybe you want to look multiAVCHD by deank (the original author of webMAN)
https://multiavchd.deanbg.com/
https://forum.doom9.org/showthread.php?t=143744

If I recall correctly multiMAN also supports AVCHD (maybe BDMV too). 
https://www.maxconsole.com/threads/special-friendly-tutorial-blu-ray-movie-backup-playback-on-a-cfw-ps3-via-multiman.26938/

Not sure if MOVIAN support AVCHD/BDMV. But, if you rip these files as movies (e.g. MKV, MP4, MTS, M2TS, etc.) you can use MOVIAN too.
