### ISSUE TITLE
PS2 games won't be listed

### ISSUE THREAD

**Issue by illua0** [aldostools/webMAN-MOD#23]
Eventually ps2iso wont get any entries in the xml - hence I have to load them in mmcm - even then it won't get refreshed unlike ps3games.

**Comment by aldostools** [comment]
Please provide an example of the directory not listed.

Screenshots of /setup.ps3 and the resulting list on XMB could be helpful too to identify the issue.

I suggest you try also with this pre-release build:
http://aldostools.org/temp/test/webMAN_MOD_1.45.01_Updater.pkg

Note: /PS2ISO is supported only on hdd0
The plugin is capable of listing the /PS2ISO on ntfs, ps3netsrv and USBx drives. However, mounting these files will make a copy on /dev_hdd0/PS2ISO then mount the copied ISO.
