### ISSUE TITLE
Error compile when uncommented #define ENGLISH_ONLY

### ISSUE THREAD

**Issue by LouisGarry** [aldostools/webMAN-MOD#235]
Hallo Aldo, 
Report
Error compile when uncommented #define ENGLISH_ONLY
Thanks.

**Comment by aldostools** [comment]
Thank you for your feedback. I was using the flag **LITE_EDITION** instead of **ENGLISH_ONLY** in the code recently added to games_xml.h for scanning ROMS  in subfolders 

Fixed in commit 1.47.24.9 60f4eba3858068222bd950220680f560b1b8f3f0
