### ISSUE TITLE
Blank checks in /setup.ps3

### ISSUE THREAD

**Issue by LouisGarry** [aldostools/webMAN-MOD#236]
Aldo, I found another bug:
Try opening localhost/cpursx.ps3 then clicking [Setup], it has no tick at all (plain), different from pressing combo L1+L2+R1+R2+O.
But it is normal to open using a smartphone/PC.

Thank you.

**Comment by aldostools** [comment]
Please include some pictures of the issues, if possible.

**Comment by LouisGarry** [comment]
Aldo, this "setup" is opened from "localhost/cpursx.ps3", there is no check mark at all.
![screenshot_2019_07_08_12_22_56](https://user-images.githubusercontent.com/41161876/60785008-7eafa380-a17b-11e9-80f5-95f58129984b.jpg)

**Comment by aldostools** [comment]
Ok now I understand the issue. I will investigate it. Thank you for the bug report.

**Comment by aldostools** [comment]
Fixed in webMAN MOD 1.47.25. 

The bug happened using Sylk engine in PS3 Internet Browser. It didn't happen with webkit engine.
Sylk engine does not allow attribute minimization in input tag. XHTML syntax is required.
