### ISSUE TITLE
vsh_menu / slaunch and Russian

### ISSUE THREAD

**Issue by nikolaevich23** [aldostools/webMAN-MOD#237]
In the latest versions you can enable vsh_menu / slaunch with the Russian language.
It is enough to edit LANG_RU.TXT and do so:
STR_LOADGAMES [Управление играми]

I can attach screenshots that in this case everything works fine.
PS3 SS + HEN

**Comment by aldostools** [comment]
Thank you for your feedback. I will test your fix soon..

**Comment by aldostools** [comment]
The VSH Menu / sLaunch Menu were restored for Russian language in commit b5f79d3293a42585c12cb96c4e9e6e25f866b709

Honestly I don't have idea what happened, but whatever that caused the freeze of VSH now is fixed :smile:

The package for 1.47.25 have been updated in the release page and in brewology.
(you can download it again)
