### ISSUE TITLE
psp game does not mount

### ISSUE THREAD

**Issue by gosseux** [aldostools/webMAN-MOD#24]
I have this issue:
When I choose a game iso using the folder MY GAMES a notification appears and the PS3/PS2/PS1 games mount properly and I see the disc icon to start the game.
When I choose a PSP game, I see the notification but the psp game does not show in the PSP Launcher.

Note: If I use Multiman everything is fine, the game show in the PSP Launcher and I can start the game.

I tested with different versions of the PSP Launcher and with webMAN built in Rebug.
I enabled cobra and webman features with Rebug toolbox.

my setup:
rebug rex 4.80.1 cobra 7.3
webMAN MOD 1.45 Full
Multiman 4.80
PSP Remasters.

Can I do something to fix this ?

**Comment by aldostools** [comment]
Thank you for the bug report.

Please test if this pkg fixes your issue.
http://aldostools.org/temp/test/webMAN_MOD_1.45.01_Updater.pkg

(if you already downloaded the pkg, please re-download it again to be sure that you have the latest version. I have updated multiple times with different md5)

**Comment by gosseux** [comment]
Thank you very much for your fast reply.  

Yes the update fixed the psp issue.  Not it works !

**Comment by keeno1982** [comment]
I faced the same issue.
'When I choose a PSP game, I see the notification but the psp game does not show in the PSP Launcher.'

Rebug 4.86.1 cobra 8.2
webMAN MOD 1.47.37 Full

Can you help to fix it?

**Comment by aldostools** [comment]
Install both PSP launchers available in the release page
https://github.com/aldostools/webMAN-MOD/releases

I also recommend to check the option "Show PSP Launcher" found in the "Scan for content" section of /setup.ps3

Once the game is mounted it should be displayed in a sub-menu inside "PLAYSTATION® PORTABLE" category.

**Comment by keeno1982** [comment]
OK now, thanks!
