### ISSUE TITLE
update portuguese language "webMAN_PT.xml"

### ISSUE THREAD

**Issue by fantasmaxd** [aldostools/webMAN-MOD#241]
follows in attached file translated and updated to Portuguese

[webMAN_PT.zip](https://github.com/aldostools/webMAN-MOD/files/3407391/webMAN_PT.zip)

**Comment by aldostools** [comment]
Muito obrigado!
+
The xml have been added to the repo in this commit 8fa1f7d55877be4a16746fc12f2b2b6c76aaceb0
