### ISSUE TITLE
PS3netserv PSPISO Not Loading

### ISSUE THREAD

**Issue by Dracrius** [aldostools/webMAN-MOD#242]
The description seems to say psp games should be supported "NETISO support for network loading and browsing of PS3 games in ISO and folder format, DVD videos in ISO format, Blu-ray movies in ISO format, PS1 and PSP games" yet my psp games will not show in Webman. They show in Multiman but multiman cant seem to mount them as it gives an error.

**Comment by aldostools** [comment]
You read it wrong... PSPISO games are **not supported** by NETISO / ps3netsrv... 

That line should be read like this:
- NETISO support for network loading and browsing of PS3 games in ISO and folder format,
- DVD videos in ISO format, 
- Blu-ray movies in ISO format,
- PS1 and PSP games

Not like: "NETISO support for ... blah blah ... PS1 and PSP games"

Anyway I will remove the "PSP" from that line to avoid confusion. Thank you for the notice.

**Comment by Dracrius** [comment]
Well thats really to bad I hope you can add support for it in the future! Thanks
