### ISSUE TITLE
Unfortunatly PSX Detection Issues with PS3Netserv Still Presist post 1.47.25.4

### ISSUE THREAD

**Issue by Dracrius** [aldostools/webMAN-MOD#244]
Currently I had it once load 21 out of 27 single bin psone games. This was after something like 6 reboots while both trying to refresh the list and giving up and just testing games as it usually shows Zero. Immediately after seeing the 21 I checked and mounting Spider-Man having it launch perfectly I unmounted the disc and the list dropped to 11. After another reboot it was back to zero all while listing the list of Ps3 games perfectly from PS3Netserv so the server is running fine as well. I've tried as many things as I could to find a rim or reason.
 
_Originally posted by @Dracrius in https://github.com/aldostools/webMAN-MOD/issues/243#issuecomment-513072174_

**Comment by aldostools** [comment]
The amount of games will vary depending of the memory available at the moment of the refresh XML.
Also the network connection can be unstable during the startup of the plugin. Try scanning manually.

For the memory, select the option [MC] -> "4 bg" in http://127.0.0.1/setup.ps3
This option should help if the issue there is not enough VSH memory during the refresh XML.

Also disable the scan for content at startup and perform the scanning manually using SELECT+L3
This option should also help to not have different amount of games on each reboot.

**Comment by Dracrius** [comment]
Awesome thank you thats perfect. All psx games that should work show as expected now. Interesting surprise though PSP games suddenly showed up as well so you do have partial support. They save to local hard drive if you try to play them and will mount if you try to click them a second time (if they had enough time to download) you dont even need to refresh the xml and choose the local copy its kinda nice.
