### ISSUE TITLE
Partial PSP Netserv support  Question?

### ISSUE THREAD

**Issue by Dracrius** [aldostools/webMAN-MOD#245]
Awesome thank you thats perfect. All psx games that should work show as expected now. Interesting surprise though PSP games suddenly showed up as well so you do have partial support. They save to local hard drive if you try to play them and will mount if you try to click them a second time (if they had enough time to download) you dont even need to refresh the xml and choose the local copy its kinda nice.

_Originally posted by @Dracrius in https://github.com/aldostools/webMAN-MOD/issues/244#issuecomment-513513669_

Could you handle that pause when it downloads a PSP Netserv ISO and mount the local copy automatically when its done? Also any chance you could flag that download to be erased when it is unmounted so as not to take up extra HD Id have to remember to have enough for a game but I'm trying to use the stock 80gb on my Phat.

**Comment by aldostools** [comment]
It is not possible to pause a download. You can abort it using R2+O (R2+X on japanese consoles).

The PSP/PS2 files copied to the PS3 remain on the hdd to avoid the download the next time that you mount the game. You should delete them manually if you need the hdd space.

**Comment by Dracrius** [comment]
Excuse the misunderstanding I didnt want the download to pause. When I said "handle the pause" I meant do something with that half a minute while it downloads giving some sort of Notifications. I think it notifies you that it is copying it to local but it would be nice if it told you when it was done with another notification clarifying it can be mounted now and or auto mounting it post download. Also the main reason for the question was the copy that stays locally. I was wondering if a setting could be added to give the option to auto delete after you unmount them? While I assumed speed of later loading was the reasoning and I understand the convenience and use case but I personally would enjoy not having to worry about them taking up my hard drive over time as I'm fighting to keep 5 gb free haha so I'd basically only want one or two locally. Thanks for the quick responses though nice seeing someone so active!

**Comment by aldostools** [comment]
Feature added to 1.47.25.7

**Comment by Dracrius** [comment]
Wow awesome you're on top of this thanks! Never expected such good support for the PS3 by this point
