### ISSUE TITLE
Little update in italian translation

### ISSUE THREAD

**Issue by usb88** [aldostools/webMAN-MOD#247]
This is just a little character replacement in the following lines:
STR_RXVID
STR_VIDLG

I've changed Vidéo to Video (replaced the "é" because it's wrong). 
It should be at least vìdeo but nobody will write that word with accent.

[LANG_IT.TXT](https://github.com/aldostools/webMAN-MOD/files/3421613/LANG_IT.TXT)

**Comment by aldostools** [comment]
Grazie mille, amico!
