### ISSUE TITLE
vsh menu

### ISSUE THREAD

**Issue by gosseux** [aldostools/webMAN-MOD#25]
I find out I can use the vsh menu to install pkg.  Very cool feature.
The problem I find is after the pkg installation, holding the select button does not call the vsh menu again. I have to reboot to get it back.

I use webMAN MOD only since few day so maybe the problem is only because I don't know how to use it.
If so, can you tell me how to fix this ?

Thanks.

**Comment by aldostools** [comment]
Please try with this _test_ build:
http://aldostools.org/temp/test/webMAN_MOD_1.45.01_Updater.pkg

**Comment by gosseux** [comment]
I downloaded the latest build available (md5 a8e3fc9c602b4a94b920c1f545e147b3)

Still not working.

edit: I also try Load VSH Menu (in config). I see 2 popup: vsh menu unloaded then vsh menu loaded, but the select button still not work.

**Comment by aldostools** [comment]
Does your VSH Menu show version **1.11** ?

Version 1.10 had the issue that you reported. But it should be fixed in 1.11.

**Comment by gosseux** [comment]
Version 1.11

This is what I do to install a pkg. (maybe you can reproduce the issue)
I hold Select to open vsh menu
I press L1 to until I can select dev_usb000
I choose the folder then the pkg
The pkg loads. But after select doesn't work

**Comment by aldostools** [comment]
For some reason the install page was breaking the pad reading of VSH menu.

I have solved it changing the method used to read the pad.

The issue must be fixed in the VSH Menu 1.12 included in the current pkg availble in
https://github.com/aldostools/webMAN-MOD/releases/latest

**Comment by gosseux** [comment]
Yes, the latest release fixed the issue.

Thanks a lot !
