### ISSUE TITLE
DECR firmware no longer properly detected

### ISSUE THREAD

**Issue by nowarin** [aldostools/webMAN-MOD#251]
In the version of wMM that comes packaged with the latest Rebug for DECR, the firmware is detected as 4.84 DECR.  With the latest here, it shows up as "4.xx DEX".  It seems DECR/DEH firmware is no longer properly detected.

**Comment by aldostools** [comment]
The binaries were built with the flag LAST_FIRMWARE_ONLY. This option removes support for decr and old versions.

Build the plugin with that flag commented to support decr again.

**Comment by nowarin** [comment]
Hmm okay.  I had assumed there was some kind of detection for the firmware that should work regardless; I guess not.

Does it actually matter, though?  Are there any features broken by having that flag on DECR?  I haven't tested much but it at least boots and doesn't seem to cause any problems, just the firmware is displayed like that.  If it's just a visual thing it doesn't matter really, just thought you might want to know about it if you didn't already.

**Comment by aldostools** [comment]
Yes, there are some broken features due the memory addresses in DECR are different to DEX.

e.g. IDPS/PSID, SYSCALL_TABLE and a few more. 

You probably didn't notice because the pokes are not frequent, and the most used (fan control) have the same address in DECR and DEX.

**Comment by nowarin** [comment]
Just curious, what's the reason the release packages aren't built with that?

Anyway, thanks for the responses.  I'll probably try to build it eventually for DECR when I have some time, if another build for it doesn't come out before then.

**Comment by aldostools** [comment]
After a quick of review of firmware.h it seems that I re-added the support to DECR, but I don't remember when :)

I suggest you try installing the full edition of build 1.47.25.8

**Comment by nowarin** [comment]
Just installed 1.47.25.8 full edition, the firmware still shows up as "4.xx DEX"

If you need me to test anything else, let me know.

**Comment by aldostools** [comment]
> Just installed 1.47.25.8 full edition, the firmware still shows up as "4.xx DEX"
> 
> If you need me to test anything else, let me know.

Try the sprx inside this zip
[webftp_server.zip](https://github.com/aldostools/webMAN-MOD/files/3465464/webftp_server.zip)

**Comment by nowarin** [comment]
I replaced the sprx with that one, and now it's properly detected as "4.84 DECR"

Did you fix something in the normal build or is this compiled specifically for DECR?

Really appreciate the help!
