### ISSUE TITLE
ps3netsrv compilation problem

### ISSUE THREAD

**Issue by The-MAD-Virus** [aldostools/webMAN-MOD#252]
Hi !
I can't compile the linux version of ps3netsrv. I get the following error:

```shell
g++  -Wall -I. -I./polarssl-1.3.2/include -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -static -O3 -s -DNDEBUG  -c -o main.o main.cpp
cc -Wall -I. -I./polarssl-1.3.2/include -std=gnu99 -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -static -O3 -s -DNDEBUG -Wall -I. -I./polarssl-1.3.2/include -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -static -O3 -s -DNDEBUG  -c -o compat.o compat.c
g++  -Wall -I. -I./polarssl-1.3.2/include -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -static -O3 -s -DNDEBUG  -c -o File.o File.cpp
File.cpp: In member function ‘virtual int File::open(const char*, int)’:
File.cpp:110:37: warning: passing argument 1 to restrict-qualified parameter aliases with argument 3 [-Wrestrict]
     filepath[flen + 4] = 0; sprintf(filepath, "%s.%i", filepath, i);
                                     ^~~~~~~~           ~~~~~~~~
File.cpp: In member function ‘virtual ssize_t File::read(void*, size_t)’:
File.cpp:318:13: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 2 has type ‘size_t’ {aka ‘long unsigned int’} [-Wformat=]
      printf("ERROR: encryption assumptions were not met, code needs to be updated, your game is probably about to crash: nbyte 0x%x, ret 0x%x, read_position 0x%I64x.\n", nbyte, ret, read_position);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~~
File.cpp:318:13: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 3 has type ‘ssize_t’ {aka ‘long int’} [-Wformat=]
File.cpp:318:13: warning: 'I' flag used with ‘%x’ gnu_printf format [-Wformat=]
File.cpp:318:13: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 4 has type ‘int64_t’ {aka ‘long int’} [-Wformat=]
File.cpp:325:10: warning: 'I' flag used with ‘%x’ gnu_printf format [-Wformat=]
   printf("ERROR: LBA request wasn't in the region_info_ for an encrypted iso? RP: 0x%I64x, RC: 0x%x, LR (0x%I64x-0x%I64x).\n", read_position, region_count_, region_count_ > 0 ? region_info_[region_count_ - 1].regions_first_addr : 0LL, region_count_ > 0 ? region_info_[region_count_ - 1].regions_last_addr : 0LL);
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
File.cpp:325:10: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 2 has type ‘int64_t’ {aka ‘long int’} [-Wformat=]
File.cpp:325:10: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 3 has type ‘size_t’ {aka ‘long unsigned int’} [-Wformat=]
File.cpp:325:10: warning: 'I' flag used with ‘%x’ gnu_printf format [-Wformat=]
File.cpp:325:10: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 4 has type ‘long long int’ [-Wformat=]
File.cpp:325:10: warning: 'I' flag used with ‘%x’ gnu_printf format [-Wformat=]
File.cpp:325:10: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 5 has type ‘long long int’ [-Wformat=]
g++  -Wall -I. -I./polarssl-1.3.2/include -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -static -O3 -s -DNDEBUG  -c -o VIsoFile.o VIsoFile.cpp
VIsoFile.cpp: In member function ‘virtual ssize_t VIsoFile::read(void*, size_t)’:
VIsoFile.cpp:1480:15: warning: comparison of integer expressions of different signedness: ‘off64_t’ {aka ‘long int’} and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
  if (vFilePtr < fsBufSize)
      ~~~~~~~~~^~~~~~~~~~~
In function ‘size_t strncpy_upper(char*, const char*, size_t)’,
    inlined from ‘uint8_t* VIsoFile::buildPathTable(bool, bool, size_t*)’ at VIsoFile.cpp:629:34:
VIsoFile.cpp:56:9: warning: ‘char* strncpy(char*, const char*, size_t)’ writing 254 bytes into a region of size 1 overflows the destination [-Wstringop-overflow=]
  strncpy(s1, s2, n);
  ~~~~~~~^~~~~~~~~~~
In function ‘size_t strncpy_upper(char*, const char*, size_t)’,
    inlined from ‘void VIsoFile::write(const char*, const char*)’ at VIsoFile.cpp:1231:38:
VIsoFile.cpp:56:9: warning: ‘char* strncpy(char*, const char*, size_t)’ specified bound 32 equals destination size [-Wstringop-truncation]
  strncpy(s1, s2, n);
  ~~~~~~~^~~~~~~~~~~
cc -Wall -I. -I./polarssl-1.3.2/include -std=gnu99 -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -static -O3 -s -DNDEBUG -Wall -I. -I./polarssl-1.3.2/include -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -static -O3 -s -DNDEBUG -L. -L./polarssl-1.3.2/library  -L. -L./polarssl-1.3.2/library -o ps3netsrv main.o compat.o File.o VIsoFile.o -lstdc++ -lpolarssl -lpthread
/usr/bin/ld : cannot find -lpolarssl
collect2: error: ld returned 1 exit status
```

I don't know if it's related to this issues #230 

```shell
uname -a
Linux debian 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5+deb10u1 (2019-07-19) x86_64 GNU/Linux
```

**Comment by aldostools** [comment]
Try to compile the following version. It is previous the changes suggested in issue #230
https://github.com/aldostools/webMAN-MOD/tree/8a2a6ec0812b578d1cb3d45e88636e0ea7e79956/_Projects_/ps3netsrv

If it still doesn't work, try to build a commit before than 27 Jun 2019 or try the old binaries for linux:
https://github.com/aldostools/webMAN-MOD/tree/master/_Projects_/ps3netsrv/bins/old/linux

**Comment by mkroening** [comment]
I am able to compile on Arch Linux. Perhaps you forgot to build `polarssl`?

```bash
$ cd _Projects_/ps3netsrv
$ make -C polarssl-1.3.2/library && make -f Makefile.linux
```

**Comment by The-MAD-Virus** [comment]
I forgot to mention that i'm cross compiling it for a nas.

**Comment by mkroening** [comment]
The error message still says, that PolarSSL can not be found. It must be compiled as well.

I need additional information to be able to reproduce this. What exactly did you do starting from a clean repository?

**Comment by aldostools** [comment]
FYI In the folder ./_Projects_/ps3netsrv/polarssl-1.3.2/bin there are 3 versions of polarssl for different platforms already compiled.

The **libpolarssl.a** found in ./_Projects_/ps3netsrv/polarssl-1.3.2/library is the binary for Win32, not for linux.

If polarssl is not compiled in linux or replaced with the proper binary, the project will not compile.

The switch -Wall shows all warnings. Try removing it or change it to -w for a less strict compilation.

**Comment by The-MAD-Virus** [comment]
So i'm using a fresh new virtual machine and i'm using the last release 1.47.25
also to cross compil i use a framework from SynoCommunity.
moreover there was no problem with the 1.47.15 release.

**Comment by mkroening** [comment]
Which [pkgsrc package](https://github.com/SynoCommunity/spksrc/wiki/Developers-HOW-TO) are you using? I guess it's [this one](https://github.com/SynoCommunity/spksrc/tree/master/spk/ps3netsrv), right? You seem to be a maintainer of this package. Which commands are required to reproduce this problem? Try to see it from my perspective: You are not giving relevant information by yourself but you have to be asked again and again. We told you, that PolarSSL can't be found from your error message. If you can't resolve it from there on by yourself, then you need to provide information on how to reproduce this. I don't want to deep dive into pkgsrc by myself. You need to cooperate!

Now that I found the package by myself, you need to figure out how to incorporate the PolarSSL sub-project into that package.

**Comment by The-MAD-Virus** [comment]
^_^ yes it's a bit messy sorry and the framework doen't help.
So i did recompile polarssl from source and it seams to work.

thank you for pointing me to the right path.

**Comment by aldostools** [comment]
> moreover there was no problem with the 1.47.15 release.

The commit 1.47.15 of ps3netsrv doesn't use use polarssl, which is used to support encrypted ps3 isos (3k3y / redump). This feature was added in the commit 1.47.24

Anyway I'm glad that your issue is solved. Thanks to Martin @mwkroening for his contribution.

**Comment by hgy59** [comment]
@aldostools is there any reason to use an outdated ssl library as polarssl is?
the final polarssl version is 1.3.9 of 2014-10-20 (and you use version 1.3.2 of 2013-11-04 in 2019?)

The polarssl library was rebranded to mbed TLS and is available as mbedtls-1.3.22 (of 2018-02-03)

Maybe the newer mbedtls-2.x is not compatible to polarssl anymore as mbedtls-1.3.x is.

For security reasons please use mbed TLS and not polarSSL anymore.
- first choice:   mbedtls-2.16.2 (2019-06-11)
- if it is not easy to integrate at least use: mbedtls-1.3.22 (2018-02-03)

All source code available at: https://tls.mbed.org/code/releases/

I am asking, because I kicked off polarssl from the synocommunity/spksrc repo since it was not referenced and rebranded (renamed) to mbedTLS (see https://github.com/SynoCommunity/spksrc/pull/3672).
This was integrated two weeks ago, and now an update of ps3netsrv by @The-MAD-Virus gets this outdated package back.

**Comment by aldostools** [comment]
There is not a special reason. I simply merged the source code of @NvrBrst that adds support for encrypted ISOs, and it includes that version of polarssl. As that version works, there is a real need to upgrade it to a more recent version.

The latest commit uses the most recent library if you compile it with Meson build system.

**Comment by hgy59** [comment]
thanks for clarifying this
