### ISSUE TITLE
Webman Mod (recent version) slows down PS3 (verified on my system read below)

### ISSUE THREAD

**Issue by spacedout5000** [aldostools/webMAN-MOD#258]
- PS3 - Model 2004A - Slim - 500GB HDD (Hybrid Seagate Momentus 7mm)
- CFW = Rebug CEX V. 4.84.2
- Webman Mod V. 1.47.25
- Problem - Initial PS3 full System Slowdown Issue, in game lag/freeze during startup/loading, XMB menu slow, other apps when launched all slow due to this app.
- USB PORTS = none attached.
- Network = OFFLINE (all the time, never ever online since purchase of console, no PSN account attached to the PS3)
-----------------------------------------------------------------------------------

Hey,

I found this out to be a major problem on my PS3.

I had Webman mod running perfectly fine over the past 2 months since applying the recent Rebug CFW on my PS3, however out of the blue my system went from super fast to really slow and sluggish. 

I checked around google, and many persist this to be a HDD failure, but in my case this is not the problem, I had a newly installed hybrid HDD, and I checked it on my PC after a rigorous format, that Crystal Disk and other Seagate tools, determines that my HDD has no problems, and has passed its SMART test (checked this on 3 different PC's to be sure, and its been verified my drive does work, and has no signs of sector or any other issues)

Now after re-installing the CFW and what I required on my PS3, including the Webman mod, everything runs fine (fast as per normal).

But as soon as the system is turned off/and or restarted, the PS3 goes slow, not normal loading slow, but everything goes slow (all process, loading etc).

After doing some tests, I figured out that Webman Mod is the culprit behind this, I don't know whats actually causing it to slow down, but maybe you can have a look around, and determine this.

What I did to come to my point that Webman Mod is the problem, was by doing the following:

1) re- installed CFW (did this after checking my HDD for issue, as per above, no issues found regardless)

2) re-installed Webman mod (FULL VERSION), Fan Control, Multiman, Managunz, File browser

3) re-installed 3 PSN games

4) after reboot, launched a PS3 game, system running fine, exited game, browsed around XMB, again no slowdowns, launched file managers above, used some various options like check system, transferred data etc, the usual stuff, again no slowdown on PS3.

5) re-booted PS3, waited for system to load, and I'm now hit with a influx of system slowdowns, and lag, launched a game, and it froze on the loading screen logo, in this case Bioshock 3 (where the 2K logo comes on then goes like the matrix, whereby it slows downs to a point where it freezes the whole PS3, and I'm forced to reboot from the power button)

5) after reboot, again system is still slow, decided to remove/uninstall apps one by one until I found the culprit, how I did this was the following way:  

i) uninstall (one by one) multiman,

ii) reboot PS3

iia) if system still starts up slow, go back to (i) above, and start again with another app (one by one, then follow suite, reboot system, and check.

6) after taking an hour doing this, I ran the game after every app was removed, one by one, and then checking if the system froze and stalled/slowed down. It did, but when I got to the last app, and this was the Webman mod, I removed it, and restarted the system, after a successful reboot, the system loaded up fast, launched a game, loaded perfectly, rebooted without the Webman mod, again loaded up perfectly fine.

7) this is where I determined it was this app (Webman mod) causing the slowdown issues on my system, I did the following to determine this:  

i) start PS3 without Webman installed 

ii) PS3 persists to load up perfectly without the Webman mod installed.

iii) re-install FULL version of Webman mod

iv) after reboot, system works fine (this is when the app auto reboots the console after installation), PS3 runs fast, but when I shutdown/reboot the PS3, the system then starts to load up slow and sluggish to a point where it freezes the game etc.

v) reboot PS3, remove full version of Webman mod (a new problem determined here - when I go to see the Webman settings, I get an error screen, can't remember error code sorry), I try to go to remove Webman option, but there is an error indication when selected on the top right corner which shows me that "Webman is still loading", I am forced to do a full install again to overwrite the current Webman files, this is the only way that I am able to remove/view Webman settings on the PS3, after a reboot, I am then able to remove the full version of Webman mod).

vi) when full version of Webman mod is removed, the PS3 runs fine, I then do this 2 more times, to determine the fault, and yes this does persist, the same outlined problems as per above.

vii) I decide to install the light version of Webman mod, with the same problems as per above, I keep getting the same results, regardless of which version I am installing.

viii) I then noticed something, on my previous time, I had CCAPI installed, I re-installed this, and then further re-installed the Webman mod FULL version, after a 5 time reboot, and testing, I detrmined that the PS3 is running fine, and fast as per normal (touchwood it stays this way for me), as I now know this is indeed a problem with the Webman mod itself.

This should not be slowing the PS3 down, regardless if I have the CCPAI app installed or not, I am unsure as to even if this is require dofr the PS3, since many users are saying that its not required, only Webman mod is.

So I leave this to you to figure out, would love a synopsis and even better a solution to this problem, 

If you require, I can take a video to outline the above for you, but am hesitant, since I got the PS3 now running back to normal again.

My apologies for the long write up, but this was thoroughly tested by me, and I concluded it is this app thats causing the PS3 to slowdown, possibly due to the amount of things that the app is forcing in the background to run???

anyhow, please do kindly let me know what you think, and how further this can be determined, and or resolved.
I know that many users over the time of this have had slowdowns, but all have proceeded to determine its a HDD, even though in my case this is not the sole answer, I have seen on google people with new installed HDD's also having this issue, even with a HDD change many are still faced with the PS3 slowdown, users can not factor a HDD failure, if the app is at fault here.

With Regards,

Byron

Quick Edit:

for reference, as I don't mess with the settings, I wanted to mention that the only setting I change on Webman mod is the fan control, thats it, the rest of the PS3 settings, etc are all default, I just want to it to play my backup games from HDD, I dont use network settings, nor do I connect to PSN at all, the system has been offline for about 6 years, never once has been activated online, as there is no reason to, past 2 months, the CFW has been really nice, setup perfectly thanks to the mods over at PSX place (Thank you MetalVelco - aka atreyu187), so am completely baffled as to why now my PS3 is slowing down due to the use of this app.

To reproduce I have the following installed when I first installed CFW on my PS3: 

*) Webman mod, multiman, managunz, file manager, PSN react, PSNPatch, irisman, CFW toolbox (rebug one), iris manager, movian, prep NTFS, ps2 launcher/classics placeholder/manager,psp launcher, tempmon, (all latest version from Brewology using USB from PC to PS3)

Also I don;t know why I installed the PSN patch etc, but I dont use them, the only things I use are the file managers multiman, and managunz.

*) HDD storage used = 425GB (remaining about 27GB)

**Comment by aldostools** [comment]
LOL it seems that you have plenty of time to write :)

webMAN by default scans for content at startup for all the selected drives specified in /setup.ps3
The scan for content is a process that may take from a few seconds to a few minutes, depending of the amount of files and devices that it has to discover.

The scan process is launched in a background thread with high priority in order of complete it as soon as possible, And this could be the cause of your slow downs, specially after reboot.

The scan option is enabled by default just for convenience of noobs (to ensure that on each boot the game list is updated). However, it is highly recommended to always **Disable content scan on startup** in /setup.ps3 and scan manually using **SELECT+L3**.

Also check in /dev_hdd0/boot_plugins.txt that you don't have multiple instances of the plugin installed. It can make the system behave slow too.

I hope that this help you!

**Comment by spacedout5000** [comment]
Hey Aldos, 

Thank you for getting back to me, I really appreciate that you have taken time to find a working solution in regards to this.

No problems, I always tend to outline as much as possible if any problems arise, this way the more detailed the better for the problem to have a viable outcome :).

~~Regarding the " Disable content scan on startup", I am in the menu now, but I see a lot of check boxes ticked (all the ones below in the menu on the Setup tab, under sub menu Scan for content):~~ 

~~- /dev_usb000~~
~~- /dev_usb001~~
~~- /dev_usb007~~
~~- PLAYSTATION 3 (PKG launcher & ROMS)~~
~~- PLAYSTATION 2 (show PS2 classics launcher, Auto CO...?? (could not see the rest of this sorry)~~
~~- PLAYSTATION~~
~~- PLAYSTATION PORTABLE (Show PSP launher)~~
~~- Blu Ray~~
~~- DVD VIdeo~~

~~All of the ones above mentioned are ticked in boxes, and the ones in the brackets are also ticked too, do I un-check all the boxes in that menu? or is there only supposed to be one box un-check?~~

Please ignore the above, I failed to see the exact option listed below, oh dear I am a noob :/. (sorry my mistake completely here for not being obvious in the sight department)

Okay I have now selected the box, and restarted the PS3. (will I have to run the Select+L3 option on every boot, or can I do this say one every few start ups?)

I know I sadly fall in that "noob" category here :/, so I apologize for all this, ~~but if you could kindly help me out with what to un-check, then this will be greatly appreciated.~~

Once this has been completed, I will report back on how things are and hopefully that this has indeed worked out just fine for me.

Please do kindly let me know with regards to the above, I honestly do not want to mess anything up, thus why its better to confirm with you first, instead of making another mess  ;).

Thank you

Byron :)

**Comment by aldostools** [comment]
The options that you mention are related to the content scanning.

They are grouped in 2 columns: Devices to be scanned (Left group) and Content type to scan (Right).

For the devices, the default options are generally the recommended. If you have disks attached to the unticked devices, you will need to select them.

For the content type (PS3, PS2, PSP, etc.) it is recommended to tick all the options, unless you want to  ignore some folders.

For the options in the brackets, it depends of what you want. The default options are the recommended settings.

**Comment by spacedout5000** [comment]
Ahh, I see, okay no worries. hehe, I have left the boxes above, and just un checked the one box listed below the settings with which you mentioned prior, I just failed to see that in the setup, sorry.

I have now un-checked that box exactly, and restarted the PS3, everything now loads fine. no slowdowns, and I am able to quickly launch my game without the freeze effect mentioned before.

Just one more thing, will I need to run the scan manfully on every startup, or just once every now and then?

touch-wood it stays like this.

Honestly you have been a charm Aldos, I would not have been able to figure this out myself, but again my hats off to you, thank you for the very kind help, and for getting back to me, I apologize for wasting any of your time regarding this though.

You can close this ticket, I am very happy that this is now fully working :).

Thank you Aldos :)

Kindest Regards, 

Byron :)

**Comment by aldostools** [comment]
You need to scan manually only when you have added new content to your disks or if you think you need to refresh the list.

**Comment by spacedout5000** [comment]
Hey Aldos, 

As an update, I've been successfully using the PS3 with the change you mentioned me to make, and your are a legend, its been perfectly fine and fully running :), I am indeed very happy with this.

Thank you once again Aldos :), much appreciated, also with the above reply, no probs, I'll do this when I add any new content to the PS3, thanks again.

Regards,

Byron :)
