### ISSUE TITLE
Issue with mounting PSX/PS2 on NTFS.

### ISSUE THREAD

**Issue by Beatskiller** [aldostools/webMAN-MOD#259]
Webman mod 1.47.25.8 (Full) don't mount PSX/PS2 that are on a ntfs partition.
I have Harvest Moon Back to Nature (USA) on a ntfs partition and when I try to mount it it trow me error, in previous version of webman it mount it without problems.

With PS2 games is the same, when mounted it throws an error and is not copied to the internal hard drive.
Only works if the games are on the internal HDD or in a external fat32 device.

**Comment by aldostools** [comment]
Please try cleaning /dev_hdd0/tmp/wmtmp then re-scan the content on NTFS with the "FULL VERSION" of webMAN MOD. 

If that doesn't work, try re-scanning the content with prepNTFS.

If after try both methods PSX games still don't load from NTFS, please report back.

PS2ISO only works from /dev_hdd0/PS2ISO. PS2ISO stored on NTFS are copied first to the internal HDD (if there is enough free space) then launched.

Please make sure that you're using the "FULL VERSION" of webMAN MOD and that you have Cobra or PS3HEN  enabled.

Also check that you don't have cross linked files in your NTFS drive.

**Comment by Beatskiller** [comment]
First yes I am using full version of webman mod.
Yes I already tried that, I cleaned wmtmp folder and scan NTFS with prepNTFS but don't work.

Yes but the PS2 games are not copied to the HDD, webman tried to mount without copied to the HDD, I need to manually copy the game to the HDD

Some games work on the NTFS, but for example Harvest Moon Back to Nature work before on NTFS and with the latest version of webman mod don't.

**Comment by aldostools** [comment]
You can try connecting the HDD to a different USB port and re-scanning with prepNTFS.

Check if the games are working with IRISMAN, to discard that the issue is not your game.
If it works, check if an older version of webMAN MOD works (just in case something was broken in the latest build).

Also try starting the game with a different PSX emulator. webMAN MOD allows to use ps1emu and ps1netemu which you can select through /setup.ps3  Some games has issues with one emulator or the other.

BTW You didn't mention if you checked the cross linked files in your NTFS drive.

**Comment by Beatskiller** [comment]
I tried connecting the devices in other port and use a different PSX emulator don't work.

I tried with multiman it doesn't work either, but I don't cleaned the wmtmp folder, then i cleaned the wmtmp and use the built-in scan NTFS that have multiman and the games work.

Then I full uninstall webman mod and installed a different versions and the games are mounted successfully, then I update and the issue continue.

Webman mod 1.47.22 don't have the problem.

**Comment by aldostools** [comment]
So, the issue is gone... Enjoy your PS3!

**Comment by Beatskiller** [comment]
It's look that the issue is gone, but I tried other games and the issue continue, the games that initially have the problem are fixed but now other games have the problem.

I thinked that the issue is gone, but no.

**Comment by aldostools** [comment]
As I mentioned earlier, some PSX games have issues with one emulator or the other. 

You can keep pressing one of the following buttons when mounting the game to switch the emulator easily without having to go to /setup.ps3:

L2 = select ps1_emu.self
R2 = select ps1_netemu.self
R1 = switch the currently selected emu.

**Comment by Beatskiller** [comment]
Yes, but games that worked before I post this issue without matter with PSX emulator I use now have the problem, I tried switching between emulators and don't worked, with the PS2 games is the same.

Something I noticed is I don't cleaned the wmtmp folder and tried mounting the games with multiman the issue continue, but if I cleaned the wmtmp folder and then rescan the NTFS with multiman, multiman mounted the games successfully, it seems that problem is with the files that webman mod create when scan game on NTFS partitions.

**Comment by Beatskiller** [comment]
I make some test and it seems that the problem are the files that webman/prepNTFS create when a NTFS is scanned.

This are the steps that I make.
I installed a previous version of webman, cleaned wmtmp and rescaned the NTFS partition then i make a copy of wmtmp folder.
Then I installed the latest version of Webman Mod, cleaned wmtmp and rescaned the NTFS, don't work the games.
Then I cleaned again wmtmp and now a restore the backup folder that I made and now the games work, but if a rescan the NTFS the issue is back.

**Comment by aldostools** [comment]
It's weird that it works with multiMAN's prepNTFS, but not with the standalone prepNTFS.
Both use the same ntfs library.

In the case of webMAN, it uses a different version of the ntfs library (built for PS3 SDK).

My suggestion is that try older versions of webMAN MOD. Maybe there is one that would work.
In that case, you could try the latest build compiled with the version of the ntfs library of the older webMAN.

All this week and the next I will be traveling to Central America. So I cannot dedicate time to this.

**Comment by Beatskiller** [comment]
Yeah, with webman mod 1.147.22 I don't have the problem, if I backup the .iso.iso and .iso.ntfs[PS2ISO] and the PSX tmp files in wmtmp that this version create and then restored with having the latest build, the games are mounting and copied in the case of PS2 games without problems.
I need to manually restore the wmtmp with the files that previously I backup when I rescan the NTFS.

I test something, if I use prepNTFS 1.19 built-in webman mod 1.147.22 with the latest version of webman, all PSX/PS2 games are mounted and copied.
But if I use the prepNTFS 1.20 built-in in the latest version some games trow an error when are tried to mounted or copied.
 I put some files on a hex view and found this.
PS2 iso.iso in wmtmp created by prepNTFS 1.20:
![Screenshot_2019-08-23-11-41-01-046_com android chrome](https://user-images.githubusercontent.com/49370959/63612464-8eecd800-c59b-11e9-90fb-15727dbc7fb8.png)

PS2 iso.iso in wmtmp created by prepNTFS 1.19:
![Screenshot_2019-08-23-11-41-08-356_com android chrome](https://user-images.githubusercontent.com/49370959/63612569-c491c100-c59b-11e9-8aff-8dee8b569ab9.png)
If use the created by prepNTFS 1.19 the games works.

**Comment by aldostools** [comment]
Thank you for your feedback. I'll make a build of the latest code with the ntfs libraries used in 1.47.22 when I get home... I'll let you know later (probably tomorrow).

**Comment by aldostools** [comment]
Hmmm libntfs_ext.a of the latest build and the one from 1.47.22 are the same binary.

Anyway I recompiled the project of prepNTFS... if it works, I can re-compile also webftp_server.sprx
[prepNTFS.zip](https://github.com/aldostools/webMAN-MOD/files/3536674/prepNTFS.zip)

**Comment by Beatskiller** [comment]
Weird, I tested the recompiled prepNTFS and the problem continue, somes work other aren't mounted or copied.

I let you the files that have the problems, this I backup from the recompiled prepNTFS and the 1.19 built-in Webman mod 1.147.22.
[wmtmp.zip](https://github.com/aldostools/webMAN-MOD/files/3536701/wmtmp.zip)

**Comment by aldostools** [comment]
In this binary I have reverted the code of fake_iso.h and fake_iso_data.h. I hope it's fixed now.
[prepNTFS.zip](https://github.com/aldostools/webMAN-MOD/files/3536755/prepNTFS.zip)

**Comment by Beatskiller** [comment]
It's fixed with this build of prepNTFS, it seems that that was the problem.

**Comment by Beatskiller** [comment]
I checked all my PS2 library just to be ensure and all worked now.

**Comment by aldostools** [comment]
Thank you for your feedback and assistance solving this issue.

**Comment by Darksound9** [comment]
Gotta love a happy ending.
