### ISSUE TITLE
webMAN MOD icon exists, but doesn't do anything.

### ISSUE THREAD

**Issue by Vixima** [aldostools/webMAN-MOD#261]
I'm using HFW on Version 4.84 with HEN, and for some reason when I went to install webMAN, the installation worked, but the icon on the XMB doesn't. I installed the Full Edition, should I have used the Lite Edition? I'll try to get some pictures or videos if needed.

**Comment by RandQalan** [comment]
reboot scan for installed games restart HEN should show a listing

**Comment by RandQalan** [comment]
Proper steps
Han enabled
Install webMAN scan after
reboot 
re enable HEN
should show listing

**Comment by Vixima** [comment]
It shows in the XMB, but clicking X on it does basically nothing. It opens as if it's a folder, then nothing loads inside.

**Comment by Vixima** [comment]
Plus if I run the installer without enabling HEN, it doesn't run, just boots me out with the message 'An error occurred during the start operation. (80010017)', meaning I can't run the installer by only enabling HAN.

**Comment by Vixima** [comment]
bump

**Comment by Vixima** [comment]
After a while, I was able to fix the issue myself, thanks for the help although it wasn't that useful.
