### ISSUE TITLE
Ram Dump doesn't work correctly

### ISSUE THREAD

**Issue by MarieRose1301** [aldostools/webMAN-MOD#262]
Hello, not sure if it's a problem with webman (most likely i did something wrong), but when i do a full dump of a game, i get a 256 mb .bin file which is completely made of that kind of lines:
![Capture](https://user-images.githubusercontent.com/20154978/64061156-2aef9280-cbdf-11e9-84f9-46baba9df248.PNG)

**Comment by aldostools** [comment]
Dump ram uses peek lv1... Cfw supports it, ps3hen doesn't.

**Comment by MarieRose1301** [comment]
Ah, I see, thank you so much!

**Comment by MarieRose1301** [comment]
Accidently closed before I could ask one more thing, is there no other way of getting ram on hen?

**Comment by aldostools** [comment]
Use ps3xploit.com there you will find the tools.

**Comment by MarieRose1301** [comment]
Looking through the options and can't even begin to imagine which ones I'd need ;_;

**Comment by aldostools** [comment]
It is one of the han tools...go to the forum of psx-place and you will get support about it.

At this moment I'm at the airport and my flight is departing. I cannot provide further help about han/HEN.

**Comment by MarieRose1301** [comment]
Oh okay thank you so much, and I'm sorry for the bad timing >_<
