### ISSUE TITLE
Webman setup entries don't show up on the XMB when "Disable grouping of content in webMAN Games" is enabled

### ISSUE THREAD

**Issue by f41lbl0g** [aldostools/webMAN-MOD#263]
When clicking webman setup on the xmb with the option enabled, the menu is blank. If i use vsh menu to open the setup and untick disable grouping, the xmb entries come back (PS3 webMan Setup, Unmount Disk, etc). However the games are grouped into PS3, PS2 folders. Webman otherwise works perfectly fine (mounting games, VSH menu etc with the grouping enabled and disabled)
Using HEN 2.3.1, 1.47.25.8 webman mod, 4.85.1 HFW

**Comment by aldostools** [comment]
Thank you for the bug report.

This bug has been fixed in webMAN MOD 1.47.25.9
