### ISSUE TITLE
ps3netsrv not updated for 0803 release

### ISSUE THREAD

**Issue by Nimrod-002** [aldostools/webMAN-MOD#265]
ps3netsrv has bee updated on the commits page on Aug 03 but the assets page has the 0701 version.

**Comment by aldostools** [comment]
That commit of August 03 is mainly an update to the source code structure. I doesn't affect the project functionally.

Anyway here are the compiled files for that commit
[ps3netsrv.zip](https://github.com/aldostools/webMAN-MOD/files/3598174/ps3netsrv.zip)

**Comment by Nimrod-002** [comment]
thanks for the reply and build.
