### ISSUE TITLE
FTP connection drop

### ISSUE THREAD

**Issue by DrDaveone** [aldostools/webMAN-MOD#266]
WinSCP 5.15.3, webMAN 1.47.25.9, FAT cechh08 4.84 REBUG, LAN.
FTP connection drops every 20 sec when idle. while sending or grabbing connection is stable.
i guess, 2 or 3 versions ago, there wasnt such issue

**Comment by aldostools** [comment]
By default, webMAN MOD drops the connection after 20 seconds of innactivity.

In /setup.ps3 you can change the wait time from 1 to 255 minutes.

Or use the command: SITE TIMEOUT `secs`

Take in count that if you increase the timeout too much, some transfers could stay connected for long time and eventually won't be able to receive files. At least that was the behavior obtained with Filezilla. That's the reason why in recent versions the default timeout was reduced to 20 seconds.

**Comment by DrDaveone** [comment]
it was a bit hard to find, but thanks, it works!
