### ISSUE TITLE
Stream my game from Google Drive (Team Drive)

### ISSUE THREAD

**Issue by RobertusIT** [aldostools/webMAN-MOD#267]
Hi,

i wish to know if is possible, stream my game from my google drive ( team drive ).

I mount my Google Drive with Rclone, so **/home/pi/mnt/gdrive** i have my files.
In this folder i have my .iso **/home/pi/mnt/gdrive/GAME/PS3ISO**

I put /home/pi/ps3netsrv-pi and i compiled it, i guess is fine because when i launch **./ps3netsrv** i can see:

> ps3netsrv build 20160826.1 (mod by aldostools)
> Usage: ./ps3netsrv rootdirectory [port] [whitelist]
> Default port: 38008
> Whitelist: x.x.x.x, where x is 0-255 or *
> (e.g 192.168.1.* to allow only connections from 192.168.1.0-192.168.1.255)

There isn't a gui, I guess, anyway i'm a newbie.

Is possible use ps3netsrv that get .iso from my Google Team Drive, mounted in my rpi ?

Should be possible, but i didn't know how, maybe with a symbolic link, i didn't know how to.

Thanks for reading and thanks to aldo for your amazing work!

**Comment by aldostools** [comment]
ps3netsrv is able to stream the ISO files stored locally in the "shared folder" of your system device (pc, laptop, pi, tablet, etc.)

The main requisite is that the file should allow **random access** using the standard file I/O.
If the file only can be accessed sequentially, it will not work.

In the case of gdrive, I haven't tried it. But if the ISO is replicated locally and can be read randomly (and you have read permissions on that file/folder), I don't see any limitation.

**Comment by RobertusIT** [comment]
> ps3netsrv è in grado di eseguire lo streaming dei file ISO memorizzati localmente nella "cartella condivisa" del dispositivo di sistema (pc, laptop, pi, tablet, ecc.)
> 
> Il requisito principale è che il file dovrebbe consentire **l'accesso casuale** usando l'I / O standard del file.
> Se è possibile accedere solo al file in sequenza, non funzionerà.
> 
> Nel caso di gdrive, non l'ho provato. Ma se l'ISO viene replicato localmente e può essere letto in modo casuale (e hai i permessi di lettura su quel file / cartella), non vedo alcuna limitazione.

Hi aldo,

in first thanks to reply me.

I have tried with my pc ( i7 and 32gb ram, so very high ), and ps3netsrv on windows.

With expandrive, to mount as a local drive, a google drive account, i can use my iso from my google drive, but game load very very slowly, and this part is very very strange, because i have gbit and i see from my fritz box, that download @ 50MB/s, so very high speed, but for every loading, seems needed full iso loaded.

So in xmb you play game, and 50MB/s for a while, i guess when complete 5GB of iso ( the game that i tried was 5GB. ), Then loading, for the first screen of the game, i press play, and again, 2nd round of download, etc.

Is normal? Or maybe google drive doesn't have random access, so works in this way?

If google drive doesn't have random access, should works in this way ? Or can't see iso from ps3?

Thanks for reading

**Comment by RobertusIT** [comment]
> ps3netsrv is able to stream the ISO files stored locally in the "shared folder" of your system device (pc, laptop, pi, tablet, etc.)
> 
> The main requisite is that the file should allow **random access** using the standard file I/O.
> If the file only can be accessed sequentially, it will not work.
> 
> In the case of gdrive, I haven't tried it. But if the ISO is replicated locally and can be read randomly (and you have read permissions on that file/folder), I don't see any limitation.

Hi aldo,

in first thanks to reply me.

I have tried with my pc ( i7 and 32gb ram, so very high ), and ps3netsrv on windows.

With expandrive, to mount as a local drive, a google drive account, i can use my iso from my google drive, but game load very very slowly, and this part is very very strange, because i have gbit and i see from my fritz box, that download @ 50MB/s, so very high speed, but for every loading, seems needed full iso loaded.

So in xmb you play game, and 50MB/s for a while, i guess when complete 5GB of iso ( the game that i tried was 5GB. ), Then loading, for the first screen of the game, i press play, and again, 2nd round of download, etc.

Is normal? Or maybe google drive doesn't have random access, so works in this way?

If google drive doesn't have random access, should works in this way ? Or can't see iso from ps3?

Thanks for reading

ps. sorry i close thread, can you open it? thanks

**Comment by Masamune3210** [comment]
The only time I have seen Google drive have random access was with Drive File Stream but I'm pretty sure you have to have a G Suite account

**Comment by aldostools** [comment]
The performance on PS3 varies on the game tested and the network configuration.

The fastest network configuration is a direct wire connection PC-to-PS3 using a gigabit ethernet card.

If the PC or the PS3 are in a wireless network, the streaming will be very laggy, specially on FMV.

If you use a gigabit router, the lags will depend of the network traffic.

The ISO streaming basically emulates a local bluray controller, so the data transfer is not optimized.
The cache in ps3netsrv is small, so there is a big chance of several re-reads of sectors.

The ISO streaming is not possible on a sequential basis, because the ps3 demands data to the bluiray controller from random sectors. 

HOW ISO STREAMING WORKS
Cobra acts as a proxy intercepting the requests for data to /dev_bdvd (sectors on the "bluray disc") from the PS3 game; Cobra passes the request to netiso plugin; the netiso plugin sends the request over the network to ps3netsrv; ps3netsrv reads the requested sectors from the ISO and return the data that was read; netiso receives over the network the returned data (sectors) and sends it to Cobra and it finally responds to the original requests of the PS3 game. This process is repeated continuously several times.

**Comment by RobertusIT** [comment]
Thanks a lot aldo, i guess isn't possible do that.
Re-reads sectors in my opinion, anyway is too slow, maybe when request a sector, read full iso and send sector requested. 

I wish to do that, because ps3 doesn't support more than 2TB, so i have 2 hdds, use a drive or a clean solution, was very nice, but is impossible.

**Comment by aldostools** [comment]
If HDD space is your issue, you can use an USB hub and connect serveral external HDDs formatted in NTFS or FAT32, plus the internal HDD.

**Comment by RobertusIT** [comment]
> If HDD space is your issue, you can use an USB hub and connect serveral external HDDs formatted in NTFS or FAT32, plus the internal HDD.

And ps3 recognize all hdds ? I didn't know that. 2 hdds usb -> usb hub -> ps3 usb port, and recognize 2 hdds or 3 etc.. ? very nice, i need to try.

Thanks

**Comment by aldostools** [comment]
If the HDD is FAT32, make sure that you go to /setup.ps3 and have checked the ports where you have the drives attached. By default USB0, USB1 and USB6 are checked. If you use an USB hub the ports can have other names.

For NTFS, all attached devices (up to 10) are scanned by prepNTFS.

**Comment by RobertusIT** [comment]
Thanks aldo, i'll try with an hub usb and 2 usb box case!
