### ISSUE TITLE
Set PS3 IP not working (PS3 NET Server for Windows)

### ISSUE THREAD

**Issue by carl0sjt** [aldostools/webMAN-MOD#269]
When you right click in PS3 NET Server taskbar icon > Remote PS3 > Set IP Address for PS3 nothing happens, no popup to set the IP, nor nothing.

**Comment by aldostools** [comment]
Please try the build 20190924
https://github.com/aldostools/webMAN-MOD/releases/download/1.47.25/ps3netsrv_20190924.zip
.

**Comment by carl0sjt** [comment]
Its working nice. Thanks :)
