### ISSUE TITLE
issue with ROMS_PKG_Launcher install

### ISSUE THREAD

**Issue by gosseux** [aldostools/webMAN-MOD#270]
I have 4.85 spy cfw with webman-mod 1.47.25.10 full version.
The issue is when I try to install ROMS_PKG_Launcher using the addon link the ps3 freeze.
Same issue if I use the pc to install it, the ps3 freeze.

I downloaded the pkg seperately and was able to install it without issue.

I don't know where the installer put the pkg files, but maybe if you change the location to hdd0/packages it could be easier to install or remove pkg

**Comment by aldostools** [comment]
The addons are stored in /dev_hdd0/tmp/wm_res

I don't know if it's an issue with SPY 4.85, but I just tested the installation of PKG Launcher using the Addons menu from /setup.ps3 in Rebug 4.84.2 REX the file installed fine.

**Comment by gosseux** [comment]
I don't know what could cause the issue. I made other tests. 

I installed standard edition  and the issue is the same. but when booting the message shows Rebug/Ps3mapi is this normal ?
I reinstalled full edition and tried to install other pkg. Same issue.

I used the file browser in Multiman 4.85 and all the pkg are in the folder you told me. I was able to install it from there using Multiman.

**Comment by aldostools** [comment]
Yes, it's normal . The standard edition is the version with support for Rebug/PS3MAPI.

I couldn't reproduce your bug on Rebug 4.84.2...  If you managed to install the PKG, then there is no issue...

**Comment by gosseux** [comment]
imo there is an issue, but I used a workaround.  I think I will not be the only person to use this cfw as there is no other  4.85 cfw atm.
thanks anyway for your time.

**Comment by gosseux** [comment]
Hi Aldo,
I tried with rebug 4.85.1 lite with the same freezing issue. It seems to be something different in 4.85 because with 4.84 no issue

**Comment by aldostools** [comment]
> I tried with rebug 4.85.1 lite with the same freezing issue. It seems to be something different in 4.85 because with 4.84 no issue

Thank you for your feedback. This seems to be an issue with the Cobra payload, since the issue is in rebug 4.85.1, but not in 4.84. I suggest you to report it to **habib** and @Joonie86 in the forum @ psx-place.com

You could try disabling Cobra in Rebug Toolbox, reboot and launch IRISMAN to load MAMBA and check if the console freezes installing the addons with that payload too.

**Comment by gosseux** [comment]
Istarbuged  4.84.3 cobra 8.1 - works properly
spy 4.85 cobra 8.1 - not working
rebug lite 4.85 cobra 8.2 - not working
I think it's not a payload issue because the first two firmwares I tested  have cobra 8.1
you also told me rebug 4.84.2 is working and it also has cobra 8.1.  Maybe joonie or habib can tell you if something has changed in 4.85

**Comment by Joonie86** [comment]
If this fails in Spy 4.85 then I don't think this is cobra issue

**Comment by aldostools** [comment]
Fixed in 1.47.27

**Comment by gosseux** [comment]
Thanks for the release.
Btw the issue fixed is not a gamepad combo issue (as in 1.47.27 description) but a pkg install issue. ;-)
