### ISSUE TITLE
[Question] Auto-connect to PSN

### ISSUE THREAD

**Issue by nandolawson** [aldostools/webMAN-MOD#271]
Sorry for asking here on GitHub, but I have a question that no one can give a definitve answer to.
webMAN MOD has the feature to disable cfw syscalls and clear the history when the console boots up. My hope is that it gives me the ability to auto-connect to PSN. This pf course depends on the time when cfw syscalls get disabled, and I think no one else as the developer is able to give me a better answer to this.

I would be very happy if I could get a definitve answer to my question. But if it is too bold to ask here, then I am very sorry for this and agree to close this issue.

Edit: If it is important, I am using the newest Rebug REX cfw.

**Comment by aldostools** [comment]
webMAN MOD uses a similar method to the one used by PSNpatch to disable the syscalls.
So both do the same in that area...

However, PSNpatch has a good safety feature not found in webMAN: it prevents the access to PSN untili the syscalls have been disabled. So I recommend you to use both plugins if you want to access PSN.

In webMAN you can disable the syscalls at startup, but you won't be able to mount any game. Only play disc games and PSN games. If you enable the PS3MAPI option, you can partially disable the syscalls allowing to mount the games while the syscalls are disabled, but this is not very safe due the syscall table is sent to PSN servers and eventually your console could be detected and banned.

**Comment by nandolawson** [comment]
My plan is to have syscalls always disabled. I never mount games as I have most of my games as legit PSN versions. And when I would need the syscalls, I'd just disable wifi and activate them. I use the PS3 very often online, which is why I am asking if it would be okay to autoconnect to PSN when syscalls are disabled at boot with webman.

**Comment by aldostools** [comment]
If you check the option "Disable CFW syscalls and delete history files at system startup" in /setup.ps3 the syscalls will be disabled approximately 5 seconds after the system starts.

IIRC the system connects to PSN when XMB is loaded, which happens some seconds later. In this case, the CFW syscalls should be already disabled.

*** MY RECOMMENDATION ***
In CFW it is a good practice that the default account used on boot don't auto-connect to PSN.
Even better is that the default account don't have PSN and that you switch to a second account whenever you need PSN. This allows you to be sure that the CFW syscalls are disabled. 

If you don't do this, one scenario where you would auto-connect to PSN with CFW syscalls enabled is: when you rebuild the database, all the plugins are disabled (boot_plugins.txt is removed), the CFW would boot and auto-connect to PSN with the CFW syscalls enabled and your console could be potentially banned.

**Comment by nandolawson** [comment]
Sorry for the late answer. Thank you very much for your answers. You've helped me a lot.
