### ISSUE TITLE
PS3 shutdowns with 3 beeps

### ISSUE THREAD

**Issue by mirokiro5** [aldostools/webMAN-MOD#272]
My PS3 shutdowns with 3 beeps. But if i unload webman it shutdowns normally. So, webman causes that problem. No game loaded, fan control disabled(syscon)

**Comment by aldostools** [comment]
Probably the PS3 is turning off due overheat...

My suggestion is that turn ON the fan control, it can be manual (e.g. 40%) or dynamic (e.g. 68C).
Also disable the scan for content at startup... This process can add extra stress to the CPU and increase the heat when the system boots, specially because other processes are also starting.

**Comment by mirokiro5** [comment]
Oops, i meant i turn it off myself

**Comment by aldostools** [comment]
You can turn off the beeps in /setup.ps3 if that's the problem.

**Comment by mirokiro5** [comment]
With webman unloaded(L3+R2+R3) i press power button and my ps3 turns off normally(without beeps) but if I don't unload webman and then press power button my PS3 turns off with 3 beeps(as if it freezed). Something in webman don't let PS3 turn off normally

**Comment by aldostools** [comment]
Last night I tested shutting down my PS3 with the power button and I didn't get the 3 beeps that you mentioned. I'm on Rebug 4.84.2 CEX cobra 8.1. I guess your issue could be some other plugin running along with webMAN or maybe an issue with your CFW or payload.

**Comment by mirokiro5** [comment]
i have just realized that the Sen Enabler plugin was causing my problem, deleted it from boot_plugins.txt and now my PS3 turns off normally. Thanks for the help

**Comment by rjmxtechnology** [comment]
> You can turn off the beeps in /setup.ps3 if that's the problem.

Is it possible to do this with PS3HEN?
