### ISSUE TITLE
Dynamic fan control

### ISSUE THREAD

**Issue by gosseux** [aldostools/webMAN-MOD#28]
I noticed the dynamic fan control does not work while playing ps2.

**Comment by aldostools** [comment]
That is normal. As the PS3 has very limited memory (256MB), Sony implemented the ps2emu as a VSH that temporarily replaces the regular VSH. As ps2emu VSH cannot load vsh plugins, it isn't possible to control the fan dynamically.

As a workaround webMAN sets temporarily the manual fan speed indicated in /setup.ps3 for PS2 emulator. The fan speed restored when the PS2 game is unmounted.

**Comment by gosseux** [comment]
Good thing to know. Thank you
