### ISSUE TITLE
Ps3netsrv ISO not listed

### ISSUE THREAD

**Issue by DisasteR** [aldostools/webMAN-MOD#281]
Hi,

I just installed Webman Mod and i builded ps3netsrv from sources to run it on my nas with docker [DisasteR/docker-ps3netsrv](https://github.com/DisasteR/docker-ps3netsrv)

Games in JB format are in `GAMES` folder and are correctly listed and playable.
ISO in `PS3ISO` folder are not listed.

I have tryed to refresh list renaming ISO files but nothing can made them showing.

If i browse NetHost file from setup.ps3 i Can see the two folders `GAMES` and `PS3ISO` and ISO files are listed here.

How to made them appear in XMB ?

**Comment by aldostools** [comment]
If you browse http://127.0.0.1/net0 on the PS3 you should see the folders `GAMES` and `PS3ISO` 

Inside the folder `PS3ISO` the files should have the file extension *.iso or *.ISO

If they don't show, try uninstalling webMAN MOD and configure it again. 
Also check if multiMAN can see the files.

**Comment by DisasteR** [comment]
Like i said previously i can browse the two folders from the net0 file manager and can see the ISO files from here.

I have removed and installed webman again. Same problem.

Why installing multiman ? Don't have it.

I'm running CFW Rebug 4.84-2 REX Cobra 8.1
Only packages i have installed are :
- Rebug Toolbox 2.03.02
- Webman MOD 1.47.25.10
- Multiman Covers Pack 7.0
- Habib-QA_Toggle-4.21+(standalone)

**Comment by DisasteR** [comment]
Hi,

Not sure if it is a clue but net0 file browser (http://127.0.0.1/net0) report Bad file size.

10Mo instead of 10G
20Mo instead of 20G
...

**Comment by mlody95pl** [comment]
Hi!, problem still exist
I shared some folders with games from my PC:
![image](https://user-images.githubusercontent.com/4082647/73136194-44402200-404b-11ea-9408-65fc3abe23ca.png)

GAMES folder contains unpacked games
![image](https://user-images.githubusercontent.com/4082647/73136247-b9abf280-404b-11ea-9751-5493eaac2372.png)

PS3ISO folder contains ISO games
![image](https://user-images.githubusercontent.com/4082647/73136251-c3355a80-404b-11ea-8673-6dfaf6a3395d.png)

Console finds only games from this source: (refreshed library and restarted xmb)
![image](https://user-images.githubusercontent.com/4082647/73136277-1e674d00-404c-11ea-8c73-629173a50ef0.png)

But net0/PS3ISO folder is visible from web:
![image](https://user-images.githubusercontent.com/4082647/73136333-c1b86200-404c-11ea-8f7f-a378fd1ae2b2.png)

I also attached my configuration:
![image](https://user-images.githubusercontent.com/4082647/73136338-d1d04180-404c-11ea-8dd5-c2403d962bd0.png)

Restarting PC, router and console fixes problem. I can provide more data to reproduce problem if you want. Please help fix me this.

**Comment by aldostools** [comment]
Please make sure that you're using static IP addresses on the PC and PS3.

**Comment by mlody95pl** [comment]
I'm 100% sure. I set static IP for PC and PS3 on router (by MAC address). My PC is 192.168.1.2 and PS3 is 192.168.1.5

**Comment by aldostools** [comment]
Everything in your settings looks good. 
If it works after reboot, the problem should be a network configuration.

Please configure the PC and PS3 with static IP. Do not use the DHCP of the router to assign the IPs.

Or try a different version of PS3netsrv (maybe an older one). Also check that your firewall or antivirus is not blocking the port.

If possible test connecting the PS3 directly to PC without the router to reduce the variables.
https://www.psx-place.com/threads/very-simple-way-to-direct-connect-ps3-to-pc.17052/

**Comment by mlody95pl** [comment]
I've tried method from link. Also tried on 2 last versions, same result. Firewall disabled, don't use Anti Virus.

**Comment by aldostools** [comment]
As I mentioned earlier, your settings look good.

I suggest you to disable the scan for content during the startup, and do it manually using SELECT+R3.

Sometimes the PS3 starts too fast and the network is not scanned at the right time.

Also try renaming the folder GAMES to IGNOREME, and test only with PS3ISO. wMM can scan a number of games (depending of the memory configuration selected in /setup.ps3). Maybe GAMES is using all the allowed slots.

If these suggestions don't work, maybe other users could help with other ideas.

**Comment by mlody95pl** [comment]
After renaming GAMES folder to IGNOREME and scan content, games from PS3ISO was found.

![image](https://user-images.githubusercontent.com/4082647/73138544-12878500-4064-11ea-9dc7-b749f9437c70.png)

What do you mean "all allowed slots" ? I use standard memory profile (448K). Is not enough for about 120 games (40 on HDD and 80 from netsrv) ? Is there a limit for amount of games in netsrv ? I have only 5 in GAMES folder and ~120 in PS3ISO

**Comment by aldostools** [comment]
In that case the issue was the number of games in GAMES folder exceeded the limit permitted by your current memory settings. The scanning stopped in GAMES and didn't continue  scanning the rest of your folders.

Try renaming the folder back to GAMES and change the Plugin memory usage to Standard (896KB), Max (1280KB) or Max PS3+ (1088K PS3) in /setup.ps3

Additionally you can set the [MC] option to "4 - bg".

**Comment by mlody95pl** [comment]
Renamed folder back to changed memory profile to Max PS3+. After scan for content can't find games from PS3ISO again...

[MC] option to "4 - bg" also did nothing.

Maybe it's bug in webman ?

**Comment by aldostools** [comment]
In that case it could be some bad name in some of your games.

The XML is very problematic with some symbols like quote characters (' and "), ampersand (&), greater than/less than characters.

You can try moving some of your games out of the GAMES folder, scan multiple times -including games more games each time- until you find the one that is causing the bug.

**Comment by mlody95pl** [comment]
Max (1280KB) seems to work.

![image](https://user-images.githubusercontent.com/4082647/73138720-3f3c9c00-4066-11ea-9d20-edbbb01a3bd6.png)

Only difference I see is in FTP section. Can you explain to me what it is about ?

**Comment by aldostools** [comment]
The table is a summary of the internal behavior. There are details not included in the table.

At least now it's working 😄

**Comment by mlody95pl** [comment]
Last question:
What is this "[MC]" option ? I can't find anything about it in internet.

**Comment by mlody95pl** [comment]
I think that you can close this issue. Thanks for help

**Comment by aldostools** [comment]
"[MC]" stands for "**M**emory **C**ontainer" (1-Application, 2-debug, 3-foreground, 4-background)
https://www.psdevwiki.com/ps3/VSH#Memory_Containers

When [MC] is disabled, the plugin allocates the memory from the VSH memory container which is limited to 2MB or less. When [MC] is selected, 3MB or 3072KB is allocated for different tasks like content scanning, file listing, etc.

**Comment by Anonym-tsk** [comment]
Same issue on latest version. Memory changes not help

**Comment by IllMethods** [comment]
Did you check the file names on your games?

**Comment by Anonym-tsk** [comment]
I moved all games from GAMES and PS3ISO to other location. Then i moved them back one by one with refresh after each game. No it works. But very strange behaviour.
