### ISSUE TITLE
Gamepad feature request

### ISSUE THREAD

**Issue by TekuSP** [aldostools/webMAN-MOD#282]
Hi,

Please make` 0x046D, 0xC24F, G29 Driving Force Racing Wheel, PTYPE_PS4` visible for PS3 as `0x046D, 0xC29B, G27 Racing Wheel, PTYPE_PS3`

Gran Turismo 6 does not support shifter on G29, but does support shifter on G27.

It would be great to make GT6 think so G29 is G27 to make game support it.

**Comment by lemmingDev** [comment]
Seconded

**Comment by aldostools** [comment]
This requested feature is outside the scope of webMAN MOD goals.

Please check ps3xpad plugin
https://www.psx-place.com/resources/ps3xpad.22/

**Comment by lemmingDev** [comment]
Thanks for the response

I'll check it out
