### ISSUE TITLE
webMAN MOD 1.45.01 trouble with ftp with filezilla

### ISSUE THREAD

**Issue by RandQalan** [aldostools/webMAN-MOD#29]
I am having transfer problems since this version please check

Yes I am using admin mode 

I rolled back to 1.45 because I ftp most things to my PS3 and since 1.45.01 has this issue
I hope you find out why it happening because I like the new stuff on 1.45.01 :)

**Comment by aldostools** [comment]
Thank you for your feedback. 

I have reverted the usage of large buffers in FTP server.

Please download the current package from
https://github.com/aldostools/webMAN-MOD/releases/latest

**Comment by RandQalan** [comment]
Thanks that fixed it
