### ISSUE TITLE
How aggressive is the new "AUTO" fan speed?

### ISSUE THREAD

**Issue by StaticVapour** [aldostools/webMAN-MOD#293]
I read the code a bit and saw something about 40 degrees. I do not know much about the code itself but i know how it works in the console. I'd just like to know what "if" policy the new fan control algorithm follows? Where does it exactly ramp up and so on, just tested the new feature and it kept my PS3 pretty cool and it handled the fan control far better than before. Now it does not wait until certain temperature and then slowly ramp it up until it's around 50% and then go back and continue that waving as long as the console is on. Sorry if this is not the right place to post this but i could not find you (the author) from anywhere else.

**Comment by Asgardsurfer** [comment]
Working well here...thanks a ton Aldo!

**Comment by aldostools** [comment]
The normal operating temperature of the PS3 is around 65 to 70 degrees celcius. Cooler is better.

However if you set the target temperature of the dynamic fan controller too low (e.g. 40 degrees) the fans will be operating at 100% trying to down the temp 25 to 30 degrees. Something that will never happen.

 If you use manual fan speed, 40% is generally good, but it can be too noisy for some users or too hot for some consoles.

**Comment by StaticVapour** [comment]
> The normal operating temperature of the PS3 is around 65 to 70 degrees celcius. Cooler is better.
So looks like the AUTO fan speed is following that. Thanks
