### ISSUE TITLE
PS1 games stutter when played from internal HDD

### ISSUE THREAD

**Issue by fwannmacher** [aldostools/webMAN-MOD#295]
I'm using Rebug 4.85.1 with webMAN MOD 1.47.25 and PS1 games stutter when played from internal HDD. The issue will not occur neither when the games are mounted with IRISMAN or when mounted with webMAN but from external HDD.

My system is a NTSC CECHA01 and the games I tried are NTSC as well. Bellow some games I tested:
- Oddworld Abe's Oddysee
- Marvel vs Capcom
- X-Men Children of the Atom

**Comment by aldostools** [comment]
Try switching the ps1 emulator from ps1_emu to ps1_netemu or viceversa.

Hold R2 or L2 while mounting the game on XMB or change the default emulator in /setup.ps3

Other factors that may affect the performance are: the health of your internal disc (e.g. bad sectors); the physical location of the ISO in the disk (it may require the HDD heads move from one extreme to the other if the disk is too fragmented); other background processes reading/writing to HDD.

**Comment by fwannmacher** [comment]
I've already tried changing the emulator and nothing changed. And regarding the HDD stuff like I said no stutter happens when mounting and playing through IRSMAN.

**Comment by aldostools** [comment]
Does the issue happen with multiMAN in mmCM mode?

If it also happens in mmCM, then the issue could be related Cobra payload. webMAN basically calls the API of Cobra to mount the game and the rest of the work is done by Cobra/Mamba/PS3HEN.

Unlike webMAN, IRISMAN starts the game calling the ps1 emulator directly without Cobra intervention. It only uses Cobra for PSX stored in NTFS. IIRC also multiMAN does the same in standard mode.

**Comment by fwannmacher** [comment]
I've tested mmCM and it has the same issue so it has to be Cobra.

**Comment by fwannmacher** [comment]
It is a Cobra issue

**Comment by ghost** [comment]
> It is a Cobra issue

Did you reported this to Joonie?

**Comment by fwannmacher** [comment]
> > It is a Cobra issue
> 
> Did you reported this to Joonie?

Yes and they didn't give a shit about it https://github.com/Joonie86/COBRA-7.3/issues/20
