### ISSUE TITLE
mygame not  ejecte Disc  help me 

### ISSUE THREAD

**Issue by tokyo7600** [aldostools/webMAN-MOD#302]
hello，mygames game list not ejecte disc icon, Owned before uninstalling older versions。

iuse Disable grouping of content in "webMAN Games" and Disable webMAN Setup entry in "webMAN Games"

**Comment by aldostools** [comment]
The option "Eject Disc" appears only on "mygames.xml" list (using Disable grouping of content) when the folder /dev_hdd0/game/XMBMANPLS is not installed.

This occurs only when webMAN MOD is installed without the PKG installer (e.g. Rebug came with webMAN pre-installed).

The "Eject Disc" is found in the menu "webMAN Setup" (the first option of the game list).
However it is named "Unmount Disc", which is the correct name. The name was changed to avoid confusion with the function "/eject.ps3" that is used to eject the physical discs.

So, if you want to show "Eject Disc" as in previous builds, remove  the folder /dev_hdd0/game/XMBMANPLS then re-scan.
