### ISSUE TITLE
Any way to show if the system is installing a PKG?

### ISSUE THREAD

**Issue by Masamune3210** [aldostools/webMAN-MOD#306]
Its a long shot I have a feeling, but I was wondering if it would be possible to add a section in the CPU Temp part of the control panel? I find myself waiting a lot for packages to install, and usually will switch over to my computer and have the status page on my second window, so having the ability to see when the packages are done would be cool

**Comment by aldostools** [comment]
Try this test build... the info is shown in /cpursx.ps3
[webftp_server.zip](https://github.com/aldostools/webMAN-MOD/files/4263601/webftp_server.zip)

It now shows FTP send/receive status and download status too ;)

**Comment by Masamune3210** [comment]
Thanks! Just a quick look before heading out before work, but it seems to be working wonderfully! Will test more later after I get off work
