### ISSUE TITLE
[Feature Request] Blueray vids decrypter 

### ISSUE THREAD

**Issue by cualquiercosa327** [aldostools/webMAN-MOD#308]
Hello, I would suggest if you could add the option of decrypt the Blueray vid when create a dump of it.

With this proyects should work:

https://www.videolan.org/developers/libbdplus.html

https://www.videolan.org/developers/libaacs.html

For avoid legal problems, the keys could be downloaded from the user and paste on a folder

Thanks

**Comment by aldostools** [comment]
Thanks for the suggestion. However, this feature is out of the scope of this project.
