### ISSUE TITLE
Boot Script Problem

### ISSUE THREAD

**Issue by ghost** [aldostools/webMAN-MOD#322]
Hey aldo

I'm made a boot_init.txt

with the following

/remap.ps3/dev_flash/vsh/resource/explore/xmb/category_game.xml&to=/dev_flash/hen/xmb/category_game.xml
wait 6
popup PS3™ 4K Pro
beep2
wait 2
/remap.ps3/dev_flash/vsh/module/custom_render_plugin.sprx&to=/dev_flash/hen/module/custom_render_plugin.sprx
/remap.ps3/dev_flash/vsh/module/game_ext_plugin.sprx&to=/dev_flash/hen/module/game_ext_plugin.sprx

Via Scrip:
The pop ups and beeps are working but remaps doesn't.

So i tried via web command on the web browser

The ones that remaps sprx files are working but remamping the category_game.xml doesn't make any effect

**Comment by ghost** [comment]
And OFC i'm reloading the xmb to changes take effects

I tagged you in the psx-place seems like i can't use a boot_init.txt to make remap working

**Comment by aldostools** [comment]
If one of the remaps is working, then issue is not the command or a bug the script engine.
It should be something wrong in the script, like the sequence of commands or the timing.

Try changing the order of the lines or time to wait. The XMB uses to cache the XML and the changes may not be recognized.

Also try remapping the XML linked to a query (like fb.xml), instead of remap category_game.xml
IIRC I tried to do it when I was researching with Joonie the implementation of a dynamic menu for HEN.

BTW I have disabled the notifications in psx-place. I don't receive any message or alerts.

**Comment by ghost** [comment]
You get me wrong

Let me reorder the things

------SCRIPT PART-----------------------

I meant in the  script NONE of the remap commands works, just the basic funcions as beep and pop up

this is the boot_init.txt, please see if this is how it works, in the web commands thread it is said that it support web commands scripts, so i used the same way as i did in the browser, ofc without the IP address

/remap.ps3/dev_flash/vsh/resource/explore/xmb/category_game.xml&to=/dev_flash/hen/xmb/category_game.xml
wait 3
popup PS3™ 4K Pro
wait 2
beep2
wait 2
popup Boost Mode
wait 2
beep3
wait 5
/remap.ps3/dev_flash/vsh/module/custom_render_plugin.sprx&to=/dev_flash/hen/module/custom_render_plugin.sprx
/remap.ps3/dev_flash/vsh/module/game_ext_plugin.sprx&to=/dev_flash/hen/module/game_ext_plugin.sprx

Only the Pop up and Beep will work, the remap command is beeing ignored.

-------------BROWSER COMMAND via PC Web Browser  ---------------------------------------

WORKS:
/remap.ps3/dev_flash/vsh/module/game_ext_plugin.sprx&to=/dev_flash/hen/module/game_ext_plugin.sprx

Works:

/remap.ps3/dev_flash/vsh/module/custom_render_plugin.sprx&to=/dev_flash/hen/module/custom_render_plugin.sprx

Does not Work

/remap.ps3/dev_flash/vsh/resource/explore/xmb/category_game.xml&to=/dev_flash/hen/xmb/category_game.xml
 

Tried multiple locations but the category_game xml is not beeing remaped, yeap i'm trying to swap it to remove the enable hen and change it to hen enabled

**Comment by ghost** [comment]
I just made some more tests now with remap in the script

tried wait times, tried multiple lines with remaps, no success

i think webman is ignoring the remap via script

**Comment by aldostools** [comment]
I already told you: The issue is not the remap command. The proof is that the remap of the sprx works.
The issue is category_game.xml that is cached in memory. Try using a query like the one for fb.xml

**Comment by DeViL303** [comment]
Sorry to bother you Aldo, I think there is an issue here. I could never get ANY custom remap to work from the boot_init.txt **except for your ac3 remap example..** 

This does work:
map /dev_flash/vsh/resource/coldboot_stereo.ac3=/dev_flash/vsh/resource/AAA
map /dev_flash/vsh/resource/coldboot_multi.ac3=/dev_flash/vsh/resource/AAA

AND it seems that ANY ac3 remaps do work... its strange.

But if we try to remap something simple like yourchannels.png it does NOT work. We have tried dev_flash to dev_flash remap, dev_flash to dev_hdd0 etc with no luck.

NOTE:  These png remaps DO work via the web browser. So I don't know why xmls and pngs wont remap when using the boot_init.txt, Any ideas?

**Comment by aldostools** [comment]
If you detail what exactly you want to do, I could try to trace if there is an issue (which I don't think exist).

I'm very busy at the moment (working at home), so it could take me a some days.

**Comment by DeViL303** [comment]
Thanks for reply. 

For now I would just like to be able to do this : 

map /dev_flash/vsh/resource/explore/icon/yourchannels.png=/dev_hdd0/remap/yourchannels.png

OR even :

map /dev_flash/vsh/resource/explore/icon/yourchannels.png=/dev_flash/vsh/resource/explore/icon/yourchannels2.png

I did have some more complicated plans with xmls, but I know they will need the XMB reloaded so just want to keep it simple for now and get png remaps working.

**Comment by DeViL303** [comment]
well, actually xmls might not need the XMB reloaded if its done at boot time. But I want to stay away from xmls for now until pngs work,  as xmls have that dodgy "%flash" variable in their path that complicates things.

**Comment by aldostools** [comment]
Today I found time to test this issue.

I tried to use only the web command /remap.ps3 to check if the command works alone (without involve the script). These were my findings:

1. If I remap a file on HDD to one on dev_flash, the /remap.ps3 works as expected.
2. If I remap an image on dev_flash to one on HDD, the command is ignored.
3. If I remap an image on dev_blind to one on HDD, the command is ignored.
4. If I remap a folder on dev_flash to a folder on HDD, the path lists the files on HDD, but the files in the HDD folder are not found in the dev_flash path. However, the original files in dev_flash still can be loaded.

My conclusions are:
1. The web command /remap.ps3 in webMAN is working properly.
2. It is a Cobra issue or GameOS is preventing the redirection of /dev_flash files.
This could be to prevent corruption of system files or maybe the redirection is entering in conflict with some internal functions. Here I'm speculating.

**Comment by ghost** [comment]
Thats is fine, it is all i need, to remap the hen sprx files to custom ones in other path, it works just fine but only via **WEB COMMAND**


but when implementing it on **BOOT_INIT.TXT** it does **NOT** work (.ac3 works fine, but SPRX doesn't)


We tried the /remap.ps3  and map

but it simple **DOES NOT WORK**

Can you please check this too?

What i'm trying to archive is when the Webman STARTS it remaps the files in **HEN**

I created a folder with sprxs to Enable Custom Particles Effects, Gameboot Sound and etc, that is only possible when hen is active, it works fine using the **WEB** COMMANDS Via Web Browser.

 **BUT** what i'm trying is to add the remap via the **BOOT_INIT** that is **NOT** working

**Comment by DeViL303** [comment]
Hmm, thanks. We had no issues with the browser remap commands really, we also had different results in our tests, the remap commands seemed to work fine from the browser. I had no issues with remapping files from dev_flash to dev_hdd0 when using the browser. 

For example I can remap qrc files like earth.qrc or canyon.qrc, or I can remap pngs like yourchannels.png no problem WITH THE BROWSER.

BUT these same remaps do NOT work with boo_init.txt for some reason.

**Comment by ghost** [comment]
One example:

This completly **WORKS** via BOOT_INIT

map /dev_flash/vsh/resource/coldboot_stereo.ac3=/dev_flash/vsh/resource/AAA


-----------------------------------------------------------------------------------------------------------
But it **DOESN'T**


map /dev_flash/vsh/module/custom_render_plugin.sprx=/dev_flash/vsh/remap/custom_render_plugin.sprx

or

map /dev_flash/vsh/module/custom_render_pluginsprx=/dev_hdd0/remap/custom_render_plugin.sprx

**Comment by aldostools** [comment]
The ones that don't work are because the source path is a file in /dev_flash, like in the examples 2 & 3 that I tried. 

In the example that works, you are redirecting to a folder. Maybe it has a different condition that maybe is not checked by GameOS.

My point is that there isn't any special code in webMAN MOD to allow only certain paths.
I also checked the code of Cobra and I couldn't find any special code there either. 
Maybe we should ask to Ken Kutaragi, he must know why dev_flash can't be remapped :)

**Comment by DeViL303** [comment]
You seem to be missing the point that all these remaps we are trying, DO WORK FINE via web browser, its only via boot_init.txt that we have any issue.

**Comment by ghost** [comment]
Look here https://i.imgur.com/M8RFvb6.png

The same paths that we are adding in the BOOT_INIT works just fine in the WEB BROWSER and it works because  the EFFECTS ARE BEEING ENABLED JUST FINE


BUT when adding it to be remapped in the BOOT_INIT.txt it does not work.

So the GAMEOS is not blocking it, as it works via web browser it should work in the same way with the boot_init.txt right?

**Comment by aldostools** [comment]
Only some paths are working or none of the remaps work?
If none is working then I will check it tomorrow. But if some paths remapped and others not, the issue is something else (timing, Cobra, GameOS, etc.)

Are you using the "map" or /remap.ps3? "map" executes sys_map_path directly. /remap.ps3 has more checks.

Also try inverting the parameters, I could have confused the order in the syntax.

Have you tried autoexec.bat? The difference is the moment in which they are executed.
boot_init.txt is executed almost immediately the plugin is loaded, while the autoexec.bat after the start of the services (www, ftp, etc.)

**Comment by ghost** [comment]
Also seems i found something interresting 


/remap.ps3

the same  /remap.ps3 used in the Web Browser does NOT work in the BOOT_INIT

but /remap.ps3 commands WORKS with CUSTOM PATHS via Web Browser


so i just followed your working example with the folder AAA and it got WORKING NOW

the custom_render.sprx loads to early so only when reloading the xmb it will work.

**Comment by DeViL303** [comment]
"Only some paths are working or none of the remaps work?" 

Seems it has issues with some files and folders.  If we put an sprx in the AAA folder then it works. weird. More testing needed, seems that browser is a lot more reliable for remaps, i will try out the autoexec.bat, and I will try swapping commands etc etc.
