### ISSUE TITLE
webMAN-MOD adds only 3 cover from webfolder per rescan 

### ISSUE THREAD

**Issue by Andre1632** [aldostools/webMAN-MOD#324]
webMAN-MOD adds only 3 cover from webfolder per rescan, so a lot of rescans have to be done to get all covers displayed.
Can this be fixed, at the moment i copy the covers manually to the wmtmp folder as workaround.

**Comment by aldostools** [comment]
Try enabling the [MC] option or change the plugin memory profile to MAX in /setup.ps3

**Comment by Andre1632** [comment]
Thank you for your quick reply°
I tried this, but it did not help.
I have to note, that i am running 3 server at the moment, so only 1 cover per server is added per rescan. Some behaviour if i am running only one server, then only 1 cover is added.

**Comment by Andre1632** [comment]
I also noticed, that webMAN-MOD have to add all covers before the games of the next folder are found.
For example i have two folders: BDISO with 5 isos and covers and PS2ISO with one ISO and one cover, then i have to do five rescans before the PS2 ISO is found!

**Comment by Andre1632** [comment]
The same problem is also when the covers are in the mmCM cover folder

**Comment by aldostools** [comment]
Fixed in commit eebafd8
