### ISSUE TITLE
webMAN-MOD does not start, when selecting restart_ps3 from web interface.

### ISSUE THREAD

**Issue by Andre1632** [aldostools/webMAN-MOD#325]
webMAN-MOD does not start, when selecting restart_ps3 from web interface.

**Comment by aldostools** [comment]
**/restart_ps3** is not a web command. Use **/restart.ps3**

https://www.psx-place.com/threads/webman-mod-web-commands.1508/

**Comment by Andre1632** [comment]
sorry for my wrong explanation, i ment it is not working, when i click on
it in the web-browser


Am Fr., 10. Apr. 2020 um 21:39 Uhr schrieb aldostools <
notifications@github.com>:
