### ISSUE TITLE
Install PKG Freeze

### ISSUE THREAD

**Issue by ghost** [aldostools/webMAN-MOD#329]
Hey aldo

I make a boot_init.txt that install a pkg

/install.ps3/dev_hdd0/game/PROTOOLBX/USRDIR/TOOLBOX/packages/Resources.pkg

the problem is wherever the pkg i choose it will freeze the console ( probably due to amount of files inside the pkg).

but it is not what i want to talk about

Seeing how the HEN finds an update and instantly opens the INSTALLING PKG system prompt

i wonder if it can be implemented in the Webman too, so i think it will be a nice implementation to install a pkg too, and avoid any kind of issues.

What do you think?

Explanation:

If i add all the files inside my mod it will not install, the XMBM+ installer will freeze, wo i removed about 3500 files and packed in another pkg, worked fine =)

So i made a boot_init.pkg to install the remanining files after the first time the console boots after the mod has been installed, so in the package it will have another boot_init that does not have the installation lines, so next boot it will not prompt to install anything

**Comment by aldostools** [comment]
PS3HEN plugin uses the same installPKG functions implemented in webMAN MOD by bguerville
https://github.com/PS3Xploit/PS3HEN/blob/master/henplugin/main.c#L335

The main difference that I noticed is the way PS3HEN plugin waits for the thread complete.
I could try using a flag variable like in PS3HEN plugin to see if it fixes the issue, but I have to find some time to test it.

**Comment by ghost** [comment]
The PS3HEN it shows the screen just like  the user hits the INSTALL PACKAGE with the progress bar and so on, i think it avoids errors specially when installing a pkg with a lot of files or the user immediately goes to another operation that i believe will get some issues.

Thanks in advance, take your time =)

**Comment by aldostools** [comment]
I've installed rebug 4.86,1 LITE and the pkg installation also worked fine. 
Maybe the issue is PS3HEN. Anyway I made a test build that uses an internal memory flag to detect when the installation is completed, instead of check for: (View_Find("game_plugin") != 0)

Try with this build:
[webftp_server.zip](https://github.com/aldostools/webMAN-MOD/files/4478128/webftp_server.zip)

**Comment by gosseux** [comment]
Hi Aldo,
I tried this test build with Rebug 4.86.1 Lite and it solved the issue #270 and possibly #299 (same issue I think)

**Comment by aldostools** [comment]
Thank you @gosseux  for your feedback  👍

**Comment by aldostools** [comment]
Fixed in 1.47.27
