### ISSUE TITLE
Sign in problem when using webman

### ISSUE THREAD

**Issue by ghost** [aldostools/webMAN-MOD#33]
Okay when ever i'm on ferrox firmware and webman loads. i'm unable to sign in to psn in general. I have no clue why this is happening but i think its something due to the ip that webman uses. I thought you should know about this issue http://imgur.com/gallery/uZ60D

**Comment by masterzorag** [comment]
Did you noticed something on third line of your screenshot, the notes line? "SSL Proxying non enabled..."

**Comment by Javier-Fuentes** [comment]
Yea you can block most urls accept fus01.ps3.update.playstation. its suppose to be  fus01.ps3.update.playstation.net/update/ps3/list/us/ps3-updatelist.txt its like a ticket for you being able to log into psn
