### ISSUE TITLE
Error while updating webMAN 1.47.26

### ISSUE THREAD

**Issue by Knocks83** [aldostools/webMAN-MOD#335]

**Comment by Knocks83** [comment]
I'm trying to update webman to the 1.47.27 version but it says "An error occurred during the download operation (80029567)".

**Comment by aldostools** [comment]
Download it from
https://github.com/aldostools/webMAN-MOD/releases
or from
https://store.brewology.com/whatsnew.php

**Comment by Knocks83** [comment]
So I shouldn't use the "update" button from the mod setup?

**Comment by aldostools** [comment]
The file could be unavailable due high traffic. I'll check it later.

**Comment by Knocks83** [comment]
Thanks, updating via pkg worked flawlessly, closing the issue.
