### ISSUE TITLE
cross compiling for ARM for Qnap NAS issue with dirent

### ISSUE THREAD

**Issue by nephaste** [aldostools/webMAN-MOD#34]
Hi 

i am trying to crosscompile for Qnap users ps3netsrv 1.45.02 getting issue with dirent.h from main.cpp

have any idea fora fix ?

root@ubuntu:/SRC/webMAN-MOD-1.45.02/ps3netsrv# make
g++    -c -o main.o main.cpp
main.cpp: In function 'int64_t calculate_directory_size(char*)':
main.cpp:320: error: 'struct dirent' has no member named 'd_namlen'
main.cpp: In function 'int process_read_dir_entry_cmd(client_t*, netiso_read_dir_entry_cmd*, int)':
main.cpp:990: error: 'struct dirent' has no member named 'd_namlen'
main.cpp: In function 'int process_read_dir_cmd(client_t*, netiso_read_dir_entry_cmd*)':
main.cpp:1144: error: 'struct dirent' has no member named 'd_namlen'
make: *** [main.o] Error 1

**Comment by masterzorag** [comment]
according to GNU libc, there should be
http://www.gnu.org/software/libc/manual/html_node/Directory-Entries.html

also, just calling make from an ubuntu box I can assume you are not cross-compiling yet...

**Comment by masterzorag** [comment]
@nephaste, help me to help you.
give me details of your model, firmware, or cat /proc/cpuinfo

**Comment by masterzorag** [comment]
@nephaste, close this one

**Comment by masterzorag** [comment]
@aldostools close this useless one, or add/assign me and I'll close it
