### ISSUE TITLE
/delete.ps3?uninstall 404

### ISSUE THREAD

**Issue by ParzivalWolfram** [aldostools/webMAN-MOD#346]
I can't remove WebMAN MOD 1.47.27 Lite as the URL provided online 404s and the button on XMB doesn't work (does literally nothing, I don't even get a toast popup.)

**Comment by aldostools** [comment]
/delete.ps3 is not a web command available in Lite edition. 
The Lite edition has a reduced number of web commands.

You can reinstall webMAN MOD standard or full edition, then uninstall it.
If you are looking to upgrade to a newer version, it is not required to uninstall it first.

A second option is to delete the files manually. I explained how in this post:
https://www.psx-place.com/threads/how-to-uninstall-webman-mod.28521/

**Comment by ParzivalWolfram** [comment]
I see. Thank you.
