### ISSUE TITLE
PSX split isos not being ordered correctly

### ISSUE THREAD

**Issue by KatsutoKiyojin** [aldostools/webMAN-MOD#348]
So I had webman on my old PS3 and kept the installer installed. If something went wrong ran the installer again. Simple. My PSX split isos were ordered fine. Sadly that system had died. I now have a new system and again the latest webman which has a whole bunch more features that are really nice and a brand new web ui. The issue is that my split isos aren't ordered anymore how they should be.
example: I have two final fantasy. 7 and 8 named accordingly Final Fantasy VII (Disc X) Final Fantasy VIII(Disc X)
For some reason, they are ordered by discs. So both games with the first disc are in order and so on. I would like it to be ordered Final Fantasy 7 Disc 1 and the next two down the list be the second te third disc and the 4th down the list be the start of final fantasy 8. I have pictures linked for reference what I am talking about. This isn't so much of a bug but more so a feature request. Thank you for the great work on webman
How it should be ordered: [https://cdn.discordapp.com/attachments/481265085335994370/710936405294973079/Capture.PNG](url)

How it is ordered: [https://cdn.discordapp.com/attachments/481265085335994370/710936468465385533/20200515_152717.jpg](url)

**Comment by aldostools** [comment]
Due memory limitation, games are sorted using only the first 3-6 letters.

webMAN tries to sort the best it can when it detects numbers, but it's not perfect.

**Comment by aldostools** [comment]
Please check if this build sorts better these games.
[webftp_server.zip](https://github.com/aldostools/webMAN-MOD/files/4672120/webftp_server.zip)

It uses a hack to sort by 2 numbers in the name into a single byte. 

You'll have to copy the sprx manually to /dev_hdd0/plugins

**Comment by KatsutoKiyojin** [comment]
thanks, man I appreciate taking your time to make this for me. Will move it later and let you know later on today
