### ISSUE TITLE
Not showing notification at startup + unable to launch VSH menu.

### ISSUE THREAD

**Issue by J013k** [aldostools/webMAN-MOD#349]
I have a problem with notification when I boot-up my console.

- When I do not have any USB device notification **is not** showing up.

- When I connect USB device to the 1st port from left:
![https://i.postimg.cc/28shVKKV/1st-port.png](https://i.postimg.cc/28shVKKV/1st-port.png)
Notification **is showing** (it works):
![https://i.postimg.cc/d04hmH4R/web-may.png](https://i.postimg.cc/d04hmH4R/web-may.png)

- When I connect USB device to the 2nd port from left notification **is not showing** up.

Tried webMAN MOD 1.47.27 from 17\05\2020 on Rebug 4.86.1 Lite.

**Comment by aldostools** [comment]
The popup should appear 6 seconds after the start up.

Probably VSH is taking longer than 6 seconds to start in certain conditions, and the popup is sent before the VSH can process it. You could try changing the line `sys_ppu_thread_sleep(6);` in `include\www_client.h`

Also try checking the settings for "Wait for any USB device to be ready" and "Wait additionally for each selected USB device to be ready". Maybe it could make a difference.

**Comment by J013k** [comment]
As for VSH menu...
When I press SELECT button for 5 sec, PS3 will freeze.

I can only press power off button on console to power it off.

As for USB setting, I have try few possibilities:
![https://i.postimg.cc/fL7ft5Rz/web-USB.png](https://i.postimg.cc/fL7ft5Rz/web-USB.png)
But none of them seems to help.
I have also this problem without any USB device.

As for "www_client.h"...
You mean this file:
[https://github.com/aldostools/webMAN-MOD/blob/master/include/www_client.h](https://github.com/aldostools/webMAN-MOD/blob/master/include/www_client.h).
Or it is located somewhere after installing webMAN MOD on PS3?

**Comment by aldostools** [comment]
Do you have your console in non-English language or changed the default system fonts?
VSH had an issue with Russian some time ago.

Yes that is the path of include/www_client.h

If you don't want or can compile the project to change the  `sys_ppu_thread_sleep(6);`, you could disable the start up popup and use `/dev_hdd0/autoexec.bat` to show a custom notification.

`wait 9`
`/popup.ps3Hello j013k`

**Comment by gosseux** [comment]
Is there a way to check if VSH is already started ?  So wait for VSH instead of wait 6 sec. would solve this issue.

**Comment by J013k** [comment]
> Do you have your console in non-English language or changed the default system fonts?
> VSH had an issue with Russian some time ago.
 
My console language was Polish, after changing it into English (US) VSH menu will be shown
and PS3 will not freeze:
![https://i.postimg.cc/7Z31pk3b/VSH.png](https://i.postimg.cc/7Z31pk3b/VSH.png)

I also replaced SCE-PS3-DH-R-CGB.TTF to have Polish font:
[https://www.psx-place.com/threads/4-86-1-rebug-lite-edition-rebug-toolbox-2-03-04-multi-released.28809/page-4#post-238500](https://www.psx-place.com/threads/4-86-1-rebug-lite-edition-rebug-toolbox-2-03-04-multi-released.28809/page-4#post-238500),
[https://www.psx-place.com/threads/4-86-1-rebug-lite-edition-rebug-toolbox-2-03-04-multi-released.28809/page-5#post-239542](https://www.psx-place.com/threads/4-86-1-rebug-lite-edition-rebug-toolbox-2-03-04-multi-released.28809/page-5#post-239542).


> Yes that is the path of include/www_client.h
> 
> If you don't want or can compile the project to change the `sys_ppu_thread_sleep(6);`, you could disable the start up popup and use `/dev_hdd0/autoexec.bat` to show a custom notification.
> 
> `wait 9`
> `/popup.ps3Hello j013k`

I disable startup notification of WebMAN on the XMB.
Created `autoexec.bat`, add:
`wait 9`
`/popup.ps3Hello j013k`

I will get `ello j013k`:
![https://i.postimg.cc/pTCR7pTk/ello.png](https://i.postimg.cc/pTCR7pTk/ello.png)

This message is showing every time I boot my PS3,
no matter if I have any USB device connected\not connected.

**Comment by aldostools** [comment]
To fix the message use

wait 9
/popup.ps3?Hello j013k

**Comment by aldostools** [comment]
> Is there a way to check if VSH is already started ? So wait for VSH instead of wait 6 sec. would solve this issue.

There should be a way... It's easier to increase the delay to 9. I wanted to use the minimum wait time.

**Comment by J013k** [comment]
>To fix the message use

>wait 9
>/popup.ps3?Hello j013k

Also adding additional space (" ") will fix this "issue": ![https://s22.postimg.cc/7vng6kdnl/zeby.gif](https://s22.postimg.cc/7vng6kdnl/zeby.gif)
`wait 9`
`/popup.ps3 Hello j013k`

But I guess:
`wait 9`
`/popup.ps3?Hello j013k`
Is the proper way to do it.

So theoretically as workaround I can add:
`wait 9`
`/popup.ps3?webMAN 1.47.27 MOD`
`/popup.ps3?4.86.1 Rebug CEX Cobra 8.2 (NTFS) [Full]`

EDIT: It will show one message after another:
![https://i.postimg.cc/T3hrkDk2/pup1.png](https://i.postimg.cc/T3hrkDk2/pup1.png)
![https://i.postimg.cc/W1K0x1KG/pup2.png](https://i.postimg.cc/W1K0x1KG/pup2.png)

`wait 9`
`/popup.ps3?webMAN 1.47.27 MOD`
`4.86.1 Rebug CEX Cobra 8.2 (NTFS) [Full]`

Will only show:
![https://i.postimg.cc/T3hrkDk2/pup1.png](https://i.postimg.cc/T3hrkDk2/pup1.png)

**Comment by aldostools** [comment]
You could try this:
`wait 9`
`/popup.ps3?webMAN 1.47.27 MOD%0A4.86.1 Rebug CEX Cobra 8.2 (NTFS) [Full]`

Or you can check if this sprx works without the workaround.
[webftp_server.zip](https://github.com/aldostools/webMAN-MOD/files/4672037/webftp_server.zip)

**Comment by J013k** [comment]
I deleted `autoexec.bat`, copied `webftp_server.sprx` into `/dev_hdd0/plugins`.

Now I'm getting notification at startup no natter if USB device is connect\not connect:
![https://i.postimg.cc/d04hmH4R/web-may.png](https://i.postimg.cc/d04hmH4R/web-may.png)

@aldostools If you want I or You can close this issue...
however I still have a problem with entering VSH menu when I'm using Polish (console) language.

**Comment by aldostools** [comment]
Try restoring the original system fonts. Maybe the custom font has some bug or condition that is breaking VSH Menu.

You can also check if switching between "original", "rounded" or "pop" fonts make a difference:
Settings > Theme settings ->Font

**Comment by J013k** [comment]
I don't know if it is a Rebug 4.86.1 Lite bug, but I do not have this option while I'm using Polish language:
![https://i.postimg.cc/bvwspGbh/XMB1.png](https://i.postimg.cc/bvwspGbh/XMB1.png)

When I change system language into English (US) I can switch between fonts:
![https://i.postimg.cc/d0ftF5w2/XMB2.png](https://i.postimg.cc/d0ftF5w2/XMB2.png)

Anyway switching between "Pop" to "Original" seems to fix breaking VSH Menu:
![https://i.postimg.cc/MHv7TPQz/XMB3.png](https://i.postimg.cc/MHv7TPQz/XMB3.png)
Now no matter if I select Polish or English (US) system language everything is fine.

**Comment by J013k** [comment]
The same thing is on OFW, there is no Font to select from Theme settings,
at least not while using Polish language.
With English (US) language this option is available.

Only "Original" font seems to work while using Polish language to enter VSH menu.
"Rounded" or "Pop" seems to freeze console.

**Comment by aldostools** [comment]
[vsh_menu.zip](https://github.com/aldostools/webMAN-MOD/files/4672739/vsh_menu.zip)

You can try using these versions of sLaunch & VSH Menu.

Now I force to use the "original" font if russian or polish language is used.

The sprx files in the zip should be uploaded to in /dev_hdd0/tmp/wm_res

**Comment by Danick1015** [comment]
I try to unsubscribe from these boards all of the time with no success. Help?


-------- Original message --------

**Comment by aldostools** [comment]
There is an unsubscribe link at the bottom of the email message sent by github.

If that doesn't work, try making a spam rule in email account that delete the unwanted email.

Or try to contact github support... the github notifications are out of my control.

**Comment by Danick1015** [comment]
Yes. I know. I have gone through the process multiple times and I still get every message


-------- Original message --------

**Comment by Danick1015** [comment]
Thanks for the ideas


-------- Original message --------

**Comment by J013k** [comment]
> [vsh_menu.zip](https://github.com/aldostools/webMAN-MOD/files/4672739/vsh_menu.zip)
> 
> You can try using these versions of sLaunch & VSH Menu.
> 
> Now I force to use the "original" font if russian or polish language is used.
> 
> The sprx files in the zip should be uploaded to in /dev_hdd0/tmp/wm_res

I'm not entirely sure if I'm doing this right...
- I have copy `slaunch.sprx` & `wm_vsh_menu.sprx` into `/dev_hdd0/tmp/wm_res`
- Turn off console.
- Change Font from "Original" to "Pop"
- Pressed Select to launch VSH menu and the console is freezing

Should I update some setting?

**Comment by aldostools** [comment]
The fonts array seems to change depending on the selected language & selected font type.

Please try this build... I tested it with almost all languages.
[wm_vsh_menu.zip](https://github.com/aldostools/webMAN-MOD/files/4674056/wm_vsh_menu.zip)

**Comment by J013k** [comment]
After coping new `wm_vsh_menu.sprx`, reboot PS3...
Everything seems to be fine with VSH menu.
Now no matter what font I will choose, menu will appear.

Unfortunately sLaunch MOD with "Pop" or "Rounded" font will not have any text and it will freeze console:
![https://i.postimg.cc/pTmFSsYC/sman.png](https://i.postimg.cc/pTmFSsYC/sman.png)

**Comment by aldostools** [comment]
The same fix was applied to sLaunch
[slaunch.zip](https://github.com/aldostools/webMAN-MOD/files/4674118/slaunch.zip)

**Comment by J013k** [comment]
Thank you very much.
Worked like a charm.

Best regards.
Case closed. ![https://i.postimg.cc/RhtM16Yd/hurra.gif](https://i.postimg.cc/RhtM16Yd/hurra.gif)
