### ISSUE TITLE
Don't reissue releases

### ISSUE THREAD

**Issue by nl6720** [aldostools/webMAN-MOD#350]
On 2020-05-05 https://github.com/aldostools/webMAN-MOD/releases had `ps3netsrv_20200505.zip` with sha512sum
```
15064137a57679be163da9f198d005044650f93ba004fe4754f44617e665977fbdd620b8e88638510cb3c058818f3605d23725ebd7e738c5c9120ba66cdd6013
```
On 2020-05-17, the sha512sum is
```
27003c406f9847d8d89f5056b6a19412a6c1315290991488d815352eed74987cc2912d30eaa39108c3ad3f444aeb923100dfd3ed36b78599bde96fef2b45407d
```
The file was changed but the version number did not increment.
This causes issues for Linux package builds. **Please do not reissue releases!** Update the archive's filename when updating it: `ps3netsrv_20200517.zip`.

**Comment by aldostools** [comment]
You would understand if you were still coding at 2:00AM a weekend !!!

The file has been renamed. I suggest you that use the binaries found in the repo instead of the ones in the release section.

**Comment by nl6720** [comment]
Don't overwork yourself @aldostools !
