### ISSUE TITLE
: put the dates of the directory instead of this fixed value.

### ISSUE THREAD

**Issue by raverman72unreal** [aldostools/webMAN-MOD#351]
https://github.com/aldostools/webMAN-MOD/blob/8e69256289e986dbf561767501e4a1f64fddf63e/_Projects_/ps3netsrv/src/VIsoFile.cpp#L1729-L1729

**Comment by aldostools** [comment]
Fixed in commit 0feb8d19eed5e2fc5b5dcbc0f69b01b48dfc2dd0
