### ISSUE TITLE
Black screen after installing 1.47.27

### ISSUE THREAD

**Issue by TonyPuryer** [aldostools/webMAN-MOD#354]
I installed Rebug 4.86.1 Lite over 4.85.1 Lite and slightly older (not sure of version, under 1 year old) webMAN mod was black screening after attempting to load it.

Updated webMAN mod to 1.47.27 and now PS3 is black screening at boot with nothing ever displayed on the screen during the boot process. It boots, hard drive activity LED lights for ~10 seconds, controllers sync, but no display is output.

**Comment by aldostools** [comment]
You can disable the loading of webMAN MOD going to Recovery Menu of PS3 and executing the rebuild database.
https://www.youtube.com/watch?v=3wxwwt97_8c

If webman is running during the black screen, you can try using **SELECT+L3+L2+R2** to delete the boot_plugins.txt and reboot.

**Comment by TonyPuryer** [comment]
Thanks for your reply aldo. I'm currently reinstalling the Rebug Lite 4.86.1 firmware from recovery. When it boots, would you recommend removing webman and reinstalling it? I'm trying to avoid a database rebuild as I have 75 pkg games installed in a folder called Games and would like to keep them there if possible. Rebuilding the database forgets the folder location and puts them all on their own on the xmb. Can you advise the best way to remove webman (if removing/reinstalling it is a viable option).

**Comment by TonyPuryer** [comment]
Edit: All good now. The CFW reinstall has fixed the boot issue. Can now open webman with no issues.

**Comment by aldostools** [comment]
If webMAN MOD is running, you can use the uninstall option in the webMAN Setup menu on XMB.

If you need to completely reinstall it, there is a long list of files that need to be deleted:
https://www.psx-place.com/threads/how-to-uninstall-webman-mod.28521/ 

It should be enough if you only delete the config file /dev_hdd0/tmp/wm_config.bin and the folder /dev_hdd0/tmp/wmtmp

**Comment by aldostools** [comment]
To avoid issues, I suggest to disconnect all the USB devices from the console, run the installer and install the full edition, although the standard edition should be ok for most of the users.

After restart, go to http://127.0.0.1/setup.ps3 and disable the content scanning at startup.
Then use prepISO or SELECT+L3 to scan the content manually.
