### ISSUE TITLE
Typo error in ps3netsrv include/VIsoFile.h

### ISSUE THREAD

**Issue by duduke** [aldostools/webMAN-MOD#356]
May 21 ps3netsrv does not compile in linux due to typo error in **include/VIsoFile.h**:
line 5 reads
**typedef long long off64_t;**

And I believe it should be:
**typedef long off64_t;**

**Comment by aldostools** [comment]
It is not a typo. It depends of the data model used by your Operarting System.

Windows platform a long integer is 32 bit and a long long integer is 64 bit.

While on most of linux platforms the long and long long integers are the same (64 bit).

https://en.m.wikipedia.org/wiki/64-bit_computing#64-bit_data_models

I added that line recently to make easier the compilation of the project on linux / cygwin.
Define it as any integer of 64-bit if it cause compilation errors on your system.

**Comment by duduke** [comment]
Sorry, I thought it was a typo :)
Compile fails on my 64bit debian until I change it to "long". 
For what it's worth, here are the errors generated during compilation with "long long":

c++ -Ips3netsrv@exe -I. -I.. -I../include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++11 -O3 -pthread -MD -MQ 'ps3netsrv@exe/src_main.cpp.o' -MF 'ps3netsrv@exe/src_main.cpp.o.d' -o 'ps3netsrv@exe/src_main.cpp.o' -c ../src/main.cpp
In file included from ../src/main.cpp:24:
../include/VIsoFile.h:5:19: error: conflicting declaration ‘typedef long long int off64_t’
    5 | typedef long long off64_t;
      |                   ^~~~~~~
In file included from /usr/include/stdlib.h:394,
                 from /usr/include/c++/9/cstdlib:75,
                 from /usr/include/c++/9/stdlib.h:36,
                 from ../src/main.cpp:1:
/usr/include/x86_64-linux-gnu/sys/types.h:92:19: note: previous declaration as ‘typedef __off64_t off64_t’
   92 | typedef __off64_t off64_t;
      |                   ^~~~~~~
../src/main.cpp: In function ‘int64_t calculate_directory_size(char*)’:
../src/main.cpp:377:7: warning: ISO C++ forbids variable length array ‘newpath’ [-Wvla]
  377 |  char newpath[path_len + MAX_FILE_LEN + 2];
      |       ^~~~~~~
[4/5] Compiling C++ object 'ps3netsrv@exe/src_File.cpp.o'
../src/File.cpp: In member function ‘virtual int File::open(const char*, int)’:
../src/File.cpp:116:67: warning: passing argument 1 to restrict-qualified parameter aliases with argument 3 [-Wrestrict]
  116 |     filepath[flen + 4] = 0; sprintf(filepath, "%s.%i", filepath, i);
      |                                                                   ^
../src/File.cpp:136:7: warning: ISO C++ forbids variable length array ‘key_path’ [-Wvla]
  136 |  char key_path[path_ext_loc - path + 5 + 1];
      |       ^~~~~~~~

**Comment by aldostools** [comment]
Please check if this version compiles better
[ps3netsrv_20200523.zip](https://github.com/aldostools/webMAN-MOD/files/4672013/ps3netsrv_20200523.zip)

**Comment by nl6720** [comment]
` ps3netsrv_20200523.zip`:
```
[2/5] Compiling C++ object 'ps3netsrv@exe/src_VIsoFile.cpp.o'
FAILED: ps3netsrv@exe/src_VIsoFile.cpp.o 
c++ -Ips3netsrv@exe -I. -I.. -I../include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -std=c++11 -march=x86-64 -mtune=generic -O2 -fno-plt -D_FORTIFY_SOURCE=2 -pthread -MD -MQ 'ps3netsrv@exe/src_VIsoFile.cpp.o' -MF 'ps3netsrv@exe/src_VIsoFile.cpp.o.d' -o 'ps3netsrv@exe/src_VIsoFile.cpp.o' -c ../src/VIsoFile.cpp
In file included from ../src/VIsoFile.cpp:8:
../include/VIsoFile.h:17:23: error: conflicting declaration ‘typedef long long int off64_t’
   17 | typedef long long int off64_t;
      |                       ^~~~~~~
In file included from /usr/include/stdlib.h:394,
                 from /usr/include/c++/10.1.0/cstdlib:75,
                 from /usr/include/c++/10.1.0/stdlib.h:36,
                 from ../src/VIsoFile.cpp:1:
/usr/include/sys/types.h:92:19: note: previous declaration as ‘typedef __off64_t off64_t’
   92 | typedef __off64_t off64_t;
      |                   ^~~~~~~
[3/5] Compiling C++ object 'ps3netsrv@exe/src_main.cpp.o'
FAILED: ps3netsrv@exe/src_main.cpp.o
c++ -Ips3netsrv@exe -I. -I.. -I../include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -std=c++11 -march=x86-64 -mtune=generic -O2 -fno-plt -D_FORTIFY_SOURCE=2 -pthread -MD -MQ 'ps3netsrv@exe/src_main.cpp.o' -MF 'ps3netsrv@exe/src_main.cpp.o.d' -o 'ps3netsrv@exe/src_main.cpp.o' -c ../src/main.cpp
In file included from ../src/main.cpp:24:
../include/VIsoFile.h:17:23: error: conflicting declaration ‘typedef long long int off64_t’
   17 | typedef long long int off64_t;
      |                       ^~~~~~~
In file included from /usr/include/stdlib.h:394,
                 from /usr/include/c++/10.1.0/cstdlib:75,
                 from /usr/include/c++/10.1.0/stdlib.h:36,
                 from ../src/main.cpp:1:
/usr/include/sys/types.h:92:19: note: previous declaration as ‘typedef __off64_t off64_t’
   92 | typedef __off64_t off64_t;
      |                   ^~~~~~~
[4/5] Compiling C++ object 'ps3netsrv@exe/src_File.cpp.o'
ninja: build stopped: subcommand failed.
```

**Comment by aldostools** [comment]
Thank you for your feedback. In this case remove the typedef block added recently to VisoFile.h and it should compile fine

**Comment by miketweaver** [comment]
I have the same issue compiling in WSL on Windows

**Comment by aldostools** [comment]
The line is now commented. Uncomment the line if needed it.

https://github.com/aldostools/webMAN-MOD/blob/master/_Projects_/ps3netsrv/include/VIsoFile.h#L12
