### ISSUE TITLE
PS3NetSrv MIPS version

### ISSUE THREAD

**Issue by Xa6ep** [aldostools/webMAN-MOD#36]
Hi, i try to use [OLD version of ps3netsrv for MIPS](https://github.com/aldostools/webMAN-MOD/blob/master/ps3netsrv/bins/old/Linkstations%20(arms_mips_ppc)/ps3netsrv_mips), but it is don't work on my NAS (MIPS32 24KEc Little Endian). Can you compile compatible version, please?
Also [i asked update ps3netsrv in Entware-NG repository to your version](https://github.com/Entware-ng/Entware-ng/issues/455), but they answered this source optimized for Windows and doesn't compatible with Entware toolchain. Entware use [old version by dirkvdb](https://github.com/dirkvdb/ps3netsrv--). 
It can't install pkg's and sometimes lose some ISO's.

**Comment by masterzorag** [comment]
you can run it on linux, with glibc

it's not a static executable, so it must found needed shared libraries

     ps3netsrv: ELF 32-bit LSB executable, MIPS, MIPS-I version 1 (SYSV), dynamically linked, interpreter /lib/ld.so.1, for GNU/Linux 2.6.18, BuildID[sha1]=69f1249462d2d2002b638e52179c06a252cbb578, not stripped

    Dynamic section at offset 0x1c0 contains 23 entries:
    Tag        Type             Name/Value
    0x00000001 (NEEDED)         Shared library: [libpthread.so.0]
    0x00000001 (NEEDED)         Shared library: [libc.so.6]

    Version References:
    required from libc.so.6:
    0x0d696912 0x00 05 GLIBC_2.2
    0x0d696917 0x00 04 GLIBC_2.7
    0x0d696910 0x00 03 GLIBC_2.0
    required from libpthread.so.0:
    0x0d696912 0x00 06 GLIBC_2.2
    0x0d696910 0x00 02 GLIBC_2.0

also, on your NAS I can assume is running an uClibc implementation, not a full glibc

* https://github.com/Entware-ng/Entware-ng/blob/c98b7edc3c7119fce9bd225c1775bee62af4c151/configs/mipselsf.config#L170

 can you check and spot some more info of your TARGET (mips) system?

**Comment by Xa6ep** [comment]
Yes, you are absolutely right! It use uClibc instead glibc. I searched on the web, and found one solution for install Glibc libraries on my NAS. It recommended to change Entware-NG to Entware-NG-3X. I'll write about results later.
Some more info about my system:
>Linux version 3.4.113
>ldconfig -v | grep -E "libc.so|libpthread.so"
        libc.so.0 => libuClibc-1.0.16.so
        libpthread.so.0 => libpthread-1.0.16.so
        ld-uClibc.so.1 => ld-uClibc-1.0.16.so

**Comment by Xa6ep** [comment]
I changed Entware, but nothing changes. Working ps3netsrv from dirkvdb and don't working aldostools.

> #file ps3netsrv
ps3netsrv: ELF 32-bit LSB executable, MIPS, MIPS32 rel2 version 1 (SYSV), dynamically linked, interpreter /opt/lib/ld.so.1, for GNU/Linux 2.6.32, stripped

> #file ps3netsrv_mips_aldostools
ps3netsrv_mips_aldostools: ELF 32-bit LSB executable, MIPS, MIPS-I version 1 (SYSV), dynamically linked, interpreter /lib/ld.so.1, for GNU/Linux 2.6.18, 
BuildID[sha1]=69f1249462d2d2002b638e52179c06a252cbb578, not stripped

**Comment by masterzorag** [comment]
[try this one](https://github.com/aldostools/webMAN-MOD/files/674218/ps3netsrv_MIPS32_r2_static.zip)

Toolchain from https://github.com/Entware-ng/Entware-ng/commit/80b982e7f71327de6a09eaccb0d54ee9a3915281, built on ppc64 HOST
* GNU C++ (OpenWrt GCC 5.4.0 unknown) version 5.4.0 (mipsel-openwrt-linux-uclibc)
        compiled by GNU C version 6.2.1 20160916 (Red Hat 6.2.1-2), GMP version 6.1.1, MPFR version 3.1.5, MPC version 1.0.3
* GNU assembler version 2.26.1 (mipsel-openwrt-linux-uclibc) using BFD version (GNU Binutils) 2.26.1
* GNU ld (GNU Binutils) 2.26.1
  Supported emulations:
   elf32ltsmip
   elf32btsmip
   elf32ltsmipn32
   elf64ltsmip
   elf32btsmipn32
   elf64btsmip

**Comment by Xa6ep** [comment]
This one runs, but still doesn't work.

> ps3netsrv_MIPS32_r2_static
> ps3netsrv build 20161211 (mod by aldostools)
> ps3netsrv_MIPS32_r2_static /media/Main/
> ps3netsrv build 20161211 (mod by aldostools)
> ps3netsrv_MIPS32_r2_static --help
> ps3netsrv build 20161211 (mod by aldostools)

**Comment by masterzorag** [comment]
./ps3netsrv_MIPS32_r2_static /path 38008

**Comment by Xa6ep** [comment]
Same result...
> ./ps3netsrv_MIPS32_r2_static /media/Main 38008
> ps3netsrv build 20161211 (mod by aldostools)

**Comment by uNbAs** [comment]
Hi guys what is the source used for compiling?

Im using and compiling old ps3netsrv of deank, and working OK. what is the diff on diferent sources?
http://www.ps3hax.net/showthread.php?t=64811

**Comment by masterzorag** [comment]
[this one](https://github.com/aldostools/webMAN-MOD/files/677884/try2.zip) is built with buildroot toolchain:

* GNU C++14 (Buildroot 2016.11) version 6.2.0 (mipsel-buildroot-linux-uclibc)
        compiled by GNU C version 6.2.1 20160916 (Red Hat 6.2.1-2), GMP version 6.1.1, MPFR version 3.1.5, MPC version 1.0.3, isl version none
* GNU assembler version 2.26.1 (mipsel-buildroot-linux-uclibc) using BFD version (GNU Binutils) 2.26.1
* GNU ld (GNU Binutils) 2.26.1

sadly, my router is BE and can't do native test
qemu-mipsel at least runs included mipsel-test

**Comment by masterzorag** [comment]
just to do some test on my hardware router, ps3netsrv exits...

![shot](https://cloud.githubusercontent.com/assets/8250079/21662122/676b6cf0-d2d8-11e6-928d-ee159564aa87.png)

**Comment by Xa6ep** [comment]
Try2 result

>./mipsel-test
> Hello world!
>./ps3netsrv /media/Main 38008
> ps3netsrv build 20161211 (mod by aldostools)
> off_t too small!
>

**Comment by masterzorag** [comment]
![shot](https://cloud.githubusercontent.com/assets/8250079/21695343/af59d630-d389-11e6-9ac3-aea79739f5b1.png)
[here](https://github.com/aldostools/webMAN-MOD/blob/master/ps3netsrv/main.cpp#L1512) we exit(-1) fine, we have to patch some code to go on...
mips 32bits uses 32bits (4byte) data, all is fine

**Comment by masterzorag** [comment]
@Xa6ep check #39

**Comment by Xa6ep** [comment]
@masterzorag yes! This version works. Thanks a lot!

**Comment by masterzorag** [comment]
@Xa6ep, check #40, testing is required

**Comment by Xa6ep** [comment]
webMAN-MOD/ps3netsrv/bins/mips32/ps3netsrv_mipsel is works. 
I can't test ps3netsrv_mipseb.

**Comment by masterzorag** [comment]
Thanks for testing and feedback,
I'll keep updating mips32 builds when required...

**Comment by masterzorag** [comment]
@aldostools, this one can be closed

**Comment by Kamillux** [comment]
Hi, I have a openwrt on a TL-Wr1043ND v2 router which is a mips32 according to [https://wiki.openwrt.org/toh/tp-link/tl-wr1043nd#info](url) but when I try every ps3netsrv from MIPS32 folder i get:
`root@OpenWrt:/mnt/usb# ls
mipsel-test                 ps3netsrv_MIPS32_r2_static
ps3netsrv
root@OpenWrt:/mnt/usb# /mnt/usb/ps3netsrv
/mnt/usb/ps3netsrv: line 1: syntax error: unexpected "("
root@OpenWrt:/mnt/usb# /mnt/usb/mipsel-test
/mnt/usb/mipsel-test: line 1: syntax error: unexpected "("
root@OpenWrt:/mnt/usb# /mnt/usb/ps3netsrv_MIPS32_r2_static
/mnt/usb/ps3netsrv_MIPS32_r2_static: line 1: syntax error: unexpected "("`

**Comment by masterzorag** [comment]
@Kamillux I was getting that kind of error due endianess, on your link we can have 2 different chips for the product:  
24Kc or 74Kc makes difference, also, you are trying an old ps3netsrv build, last one is  at PR #40:  
for [little](https://github.com/masterzorag/webMAN-MOD/blob/4e876a05f3b27098cdfc44e3980b13024399274b/ps3netsrv/bins/mips32/ps3netsrv_mipsel) or [big](https://github.com/masterzorag/webMAN-MOD/blob/4e876a05f3b27098cdfc44e3980b13024399274b/ps3netsrv/bins/mips32/ps3netsrv_mipseb) endian, try them and report back.
To get sure, take an executable out from your router and pass it to file program under linux: MSB or LSB executable tells you the endianess.

**Comment by Kamillux** [comment]
After testing i can tell that i have big endian. ps3netsrv_mipseb works kind of.

'root@OpenWrt:~# /mnt/usb/ps3netsrv_mipseb /mnt/usb/playstation3 38008
ps3netsrv build 20170106 (mod by aldostools)
Path: /mnt/usb/playstation3

Waiting for client...
Connection from 192.168.1.144`

It connects but doesn't show games on playstation3 webMAN-MOD. I tried ps3netsrv64 1.43.28 on my linux machine and that also did not work (same result as in OpenWrt)  but version 1.43.27 works great on desktop linux.

`Waiting for client...

Connection from 192.168.1.144

Connection from 192.168.1.144

Connection from 192.168.1.144

open /PS3ISO/Blur [BLUS30295].iso`

**Comment by masterzorag** [comment]
To get games shown on webman coloumn you have to refresh xml file (once) or do something asking for connection...
I'm used load/unmount/test by using the **Web**(MAN) interface from pc, refreshing ps3netsrv connection by using NET button in GAMES panel  
Did NET games appears in web interface?

**Comment by Kamillux** [comment]
**What I did:**
**load ps3netsrv_mipseb on my router:**
`_root@OpenWrt:~# /mnt/usb/ps3netsrv_mipseb /mnt/usb/playstation3 38008
ps3netsrv build 20170106 (mod by aldostools)
Path: /mnt/usb/playstation3_

_Waiting for client...`_

**and the on webman interface i click "refresh xml", then i see on router:**
_`root@OpenWrt:~# /mnt/usb/ps3netsrv_mipseb /mnt/usb/playstation3 38008
ps3netsrv build 20170106 (mod by aldostools)
Path: /mnt/usb/playstation3_

_Waiting for client...
Connection from 192.168.1.144`_ **<-- my playstation 3**

**It seems there is a connection but there are no NET games in web interface, list is empty but should be one game.**

**The same behaviour I get when I try ps3netsrv64 version 1.43.28 on my linux desktop but ps3netsrv64 version 1.43.27 works, there is 1 game in NET folder on WebMan. Maybe some difference between versions**

**Comment by masterzorag** [comment]
@Kamillux at least we have same endianess, we can test on 2 different hardware.
I'll take in account, I'll build a debug one for our tests, stay tuned
Diff between versions are small, we can track down the issue just adding some debugging messages...

**Comment by Kamillux** [comment]
@masterzorag ok, I love debugging :)

**Comment by masterzorag** [comment]
@Kamillux mipseb_debug_static: check commit f6af958d29c31a79dd35efd4e67c9c10edb53a4c
It's upx compressed, but not stripped, it includes GDB debugging informations!  
Since you love debugging and you running OpenWRT, maybe you can install the GNU Debugger and use it directly on the target...

**Comment by Kamillux** [comment]
**Did initial test without GDB:**
_root@OpenWrt:~# /mnt/usb/ps3netsrv_mipseb_debug /mnt/usb/playstation3 38008
ps3netsrv build 20170106 (mod by aldostools)
off_t too small! (4)
Path: /mnt/usb/playstation3_

_Waiting for client...
Connection from 192.168.1.144
client_thread(), client @0x7719f644
command received: 2A12
Unknown command received: 2A12
finalize_client()_

**I'll update when I compile GDB**

**Comment by masterzorag** [comment]
I'm assuming endianess problems, seems that we have to reverse multibyte types just on LE targets...

**Comment by masterzorag** [comment]
@Kamillux try [this](https://github.com/masterzorag/webMAN-MOD/raw/9c9ce22445ac0ad162c388f79683093b1d74de44/ps3netsrv/bins/mips32/ps3netsrv_mipseb_debug)

**Comment by Kamillux** [comment]
**Still no-go:**
_root@OpenWrt:~# /mnt/usb/ps3netsrv_mipseb_debug /mnt/usb/playstation3 38008
ps3netsrv build 20170106 (mod by aldostools)
off_t too small! (4)
Path: /mnt/usb/playstation3_

_Waiting for client...
Connection from 192.168.1.144
client_thread(), client @0x77530644
command received: 2A12
Unknown command received: 2A12
finalize_client()_

**Comment by masterzorag** [comment]
@Kamillux not tested yet? Any good news?
I have updated the binary, check that commit!

**Comment by Kamillux** [comment]
**Sorry for the delay. [Yes it lives :D](http://pastebin.com/3TaPjvum)**
Thank You

**Comment by masterzorag** [comment]
@Xa6ep can you close this one?
No more reason...
