### ISSUE TITLE
.BIN.ENC with ps3netsrv

### ISSUE THREAD

**Issue by PeterVicent** [aldostools/webMAN-MOD#360]
Is it possible to use .BIN.ENC with a network? I have a PS3 HEN, and for some reason it crashes when I put an internal hard drive. So I would need to use it over the network.

**Comment by aldostools** [comment]
PS2 games only work when the .BIN.ENC or .ISO are stored in /dev_hdd0

Over network the PS2 game file must be copied locally to the internal HDD before launch it
