### ISSUE TITLE
limit the maximum fan speed don't work

### ISSUE THREAD

**Issue by GameGearZero** [aldostools/webMAN-MOD#362]
hi i can't set the maximum fan speed below 50% 
i want to set it like this:  min29% - max34%
but after save settings the maximum  jumps back to 50%. 

my setting: PS Slim CECH 2104
Rebug 4.86.1

**Comment by aldostools** [comment]
If you want to use that low fan speed use manual or SYSCON. The maximum fan speed can be any value between 50 and 99.

Or you can compile a custom version removing that limit in include/setup.h

The limit of 50 is intended to prevent the console get damaged because the fan cannot increase when needed.

**Comment by GameGearZero** [comment]
i dont know how do do that. i can not compile a version by myself.  is there noy way to remove the limit in other ways?  i have a ps3 slim with delided ihs  (Cell and RSX) if i play the last of us with 34% fan speed it doesnt pass the 65 degrees after hour of gameplay. the idea is to to have the maximum at 34% and the minumum at 29% thats super quit and i dont hear the fan raising up and down.

**Comment by aldostools** [comment]
Sorry but I do not plan to reduce the limit.

Configure the fan speed to manual 34% and you're set.

**Comment by GameGearZero** [comment]
i have set it already manual to 34% but if i watch youtube or play some retroarch i dont need that 34% i can't undertand that you don't want to reduce the limit? why users can't manual set they own maximum fanspeed if they know what they doing ?

**Comment by aldostools** [comment]
My dear friend, webMAN MOD is used by a large number of users.
Not all users have your luck. Allowing to reduce the limit too low could be a cause of failure.

The source code is open for everyone that want to modify it.
Only the 50 in the following lines need to be changed.
https://github.com/aldostools/webMAN-MOD/blob/master/include/setup.h#L227
https://github.com/aldostools/webMAN-MOD/blob/master/include/setup.h#L597
https://github.com/aldostools/webMAN-MOD/blob/master/include/setup.h#L1316
https://github.com/aldostools/webMAN-MOD/blob/master/include/setup.h#L1320
