### ISSUE TITLE
problem with the covers with 1.47.27

### ISSUE THREAD

**Issue by shikata6** [aldostools/webMAN-MOD#363]
Hello! Great app thank you!
With the latest version I have a problem in the covers loaded from the directory of multiMAN.
I use an external hard drive with ps3iso games. With the new version, it doesn't want to load the covers of these games. I went back to the previous version and they showed up right away.  I use Rebug 4.86.1 LITE
Greetings!

**Comment by aldostools** [comment]
Please provide an example of the full path of the iso that are not showing and the name of the cover files.

**Comment by shikata6** [comment]
Hello! All games (about 50) do not have a cover. Only the game icons appear. Whatever I do doesn't want to load them. After returning from work, I will write you the exact path to the directory of covers and games on the external hard drive (which are in iso). Going back to the previous version 1.47.26 with one reload and all are displayed.
Greetings!

**Comment by aldostools** [comment]
Ok. The paths will be helpful to try to reproduce your scenario.

**Comment by shikata6** [comment]
![IMG_20200530_224703](https://user-images.githubusercontent.com/3618602/83337879-a776e500-a2c7-11ea-9399-fc947fddd5b7.jpg)
![IMG_20200530_224618](https://user-images.githubusercontent.com/3618602/83337880-a940a880-a2c7-11ea-846c-784c4a35c137.jpg)

Here are the directories I took from the built-in webman mod file manager.
Covers    /dev_hdd0/game/BLES80608/USRDIR/covers:

Games directory.    /dev_ntfs0:/PS3ISO

I'm with this version now webMAN MOD 1.47.26.
Just to add that a few days ago I changed the hard drive to ps3 and everything is clean, the first version that I installed clean was this webMAN MOD 1.47.27. I don't know if it has anything to do with the problem. It may be useful to you.

**Comment by aldostools** [comment]
If the game file in /dev_hdd0/tmp/wmtmp has an image associated, webMAN will use it instead of use the covers from other sources like multiMAN covers, online, etc.

The images found in /dev_hdd0/tmp/wmtmp are generally extracted by prepISO or prepNTFS.

**Comment by shikata6** [comment]
Hello! Yes, this is exactly what happens with the new versions, even if it is set in the settings, the covers should have priority. The program always loads the icons extracted with  prepISO or prepNTFS.

**Comment by aldostools** [comment]
For the moment delete the images in wmtmp and it should show l lthe images as usual. I should find a work around to show other images when it already found one in wmtmp.

**Comment by shikata6** [comment]
By the way, the program you are developing is unique with so many features. Thank you so much for the things you do!

**Comment by aldostools** [comment]
Please try with the PKG available in [Releases](https://github.com/aldostools/webMAN-MOD/releases) or update from XMB

**Comment by shikata6** [comment]
Yes! Problem solved! Thanks again!
