### ISSUE TITLE
ROMS stopped showing up

### ISSUE THREAD

**Issue by floppyD** [aldostools/webMAN-MOD#364]
After rescanning content, webMAN stopped showing up the ROMS folder under My Games. I haven't changed anything, they are still located on USB001 and can still be loaded through Retroarch just fine, but I can't figure out how to make webMAN recognize them. I'm using the file you provided on #358, maybe it's related?

**Comment by floppyD** [comment]
Just to add, I have PSX games on the same device and they are still being recognized just fine.

**Comment by aldostools** [comment]
Try re-downloading and installing webMAN + PKG/ROM Launcher from 
https://github.com/aldostools/webMAN-MOD/releases
Just to make sure that you're using the latest build that I have here.

If the problem persists, try re-configuring the settings in /setup.ps3 specially make sure that /dev_usb001 and ROMS are selected in the section "Scan for content"

Verify that the memory profile in /setup.ps3 is standard or max+. 
Also check if marking the option 3072KB [MC] helps.

One last thing, check that the ROMS folder exists in /dev_usb001 and that it has the games inside.

**Comment by floppyD** [comment]
I tried some of what you recommend but it wasn't working, so I ended up reinstalling webMAN and it's fine again. Weird. Thanks anyway.
