### ISSUE TITLE
request

### ISSUE THREAD

**Issue by gosseux** [aldostools/webMAN-MOD#365]
Hi Aldo,
Thanks for the new update !  You made a lot of commits, but  I don't know if I need to update any of the addon PKG.
Can you add a version number to all PKG like you did with PS2CONFIG ?  It will be easier to know if something has changed and should be updated in the PS3.

**Comment by aldostools** [comment]
I recommend to update all the add-ons found in the release page (that's why they're listed there). It will take only a couple of minutes.

The add-ons have a date yyyymmdd as version  next to the name.

**Comment by gosseux** [comment]
Not all the add-ons found in the release page have a date.  For example, all the Launcher does not have one.

**Comment by aldostools** [comment]
They don't have a date because they were not updated.
