### ISSUE TITLE
slowdown on momba 8.3 cfw rebug 4.86 for dlc

### ISSUE THREAD

**Issue by RandQalan** [aldostools/webMAN-MOD#367]
this is having same issues that PS3HEN_2.2.1 had was fixed in recent versions
Otherwise like mamba better then cobra
Thank for all your hard work

**Comment by aldostools** [comment]
Please provide more detail about the issue... e.g. how to reproduce? video of the issue?

Does the same issue happen on Cobra? PS3HEN?

**Comment by RandQalan** [comment]
No on cobra works fine for dlc
run a game with a lot of dlc like tales of graces f 
it shows dlc check at start of game
cobra 8.2 2 seconds load most dlc
mamba 12 plus for dlc

but exdata must always be present for cobra while mamba it can be deleted once recognize

i hopefully u can reproduce this now and fix this good luck and happy coding master

**Comment by aldostools** [comment]
do you have /exdata in hdd0 or usb?

does the error happen if you **rename** or delete **/exdata** folder?

I compared the code used in Cobra 8.2 and made a small change, I hope it helps.
This zip contains the payload for 4.86 CEX if you want to test it [mamba_486C.zip](https://github.com/aldostools/webMAN-MOD/files/4777680/mamba_486C.zip)

You can place it in /dev_hdd0/game/IRISMAN00/USRDIR/mamba/
or in /dev_hdd0/plugins/kernel/ if you have /dev_hdd0/boot_plugins_kernel_nocobra.txt

**Comment by RandQalan** [comment]
No still same problem.

**Comment by RandQalan** [comment]
kernel version used your webman mod

**Comment by aldostools** [comment]
Thank you for your feedback... I don't know what could be causing the slowdown...

I don't have that game to test it myself... In theory it should be slightly faster than Cobra.

Please try without the exdata folder with the raps.

**Comment by RandQalan** [comment]
done that before bug reported.
Thanks anyway FYI maybe constant new HEn how they fixed it :)

**Comment by aldostools** [comment]
Thank you for your feedback.... I made a couple of changes:
1- Now the RIF is created in a single write like in Cobra
2- If the RIF already exists, it is not re-created like in Cobra. It should improve the speed, at least after the first run. However, if the RAP is invalid, the RIF should be removed. This is unlikely to happen if the user don't use RAP downloaded from Internet.

EDIT: This implement a simple workaround for the corrupted RAP.
Entering to the Update option in XMB will enable the option of recreate RIF until the next boot.
[mamba_486C_20200614_v4.zip](https://github.com/aldostools/webMAN-MOD/files/4778129/mamba_486C_20200614_v4.zip)

**Comment by RandQalan** [comment]
is a little faster now thank

**Comment by aldostools** [comment]
How much compared with Cobra?

**Comment by RandQalan** [comment]
still takes 2 sec for mamba for each dlc
while cobra modes .5 sec or less for each
was around 3 to 4 before

**Comment by aldostools** [comment]
Thank you for the info. I will check if there is something else I could find.

The code is quite similar... so I don't understand why it's slower.

**Comment by aldostools** [comment]
I think the slowdown issue was caused by reActPSN.h module by habib.
I just noticed that habib removed it in latest PS3HEN and Cobra does not include it.

[mamba_486C_20200615.zip](https://github.com/aldostools/webMAN-MOD/files/4783115/mamba_486C_20200615.zip) As a plus, the payload is now 8KB smaller 🚀

**Comment by RandQalan** [comment]
That fixed it ;)
just to let u know found another problem sman mod is not loading on mamba

**Comment by aldostools** [comment]
How do you load it? using /boot_plugins_kernel_nocobra.txt?

In my tests I'm loading MAMBA through IRISMAN and webMAN MOD loads fine.
I guess sMAN should work the same way.

**Comment by RandQalan** [comment]
it keeps saying webMan not loaded and refresh

**Comment by RandQalan** [comment]
your webMan with your installer

**Comment by RandQalan** [comment]
try combo with webman loaded

**Comment by aldostools** [comment]
I don't understand... how sMAN is sayin that webMAN is not loaded?

**Comment by RandQalan** [comment]
no clue why works with cobra

**Comment by aldostools** [comment]
Please if you have time, write a step by step of how to reproduce the error

**Comment by RandQalan** [comment]
did this before your fix so the fix is good

**Comment by RandQalan** [comment]
ok load mamba
use webman
conbo l2 r2
says webman is not loaded
and refreshes list
after refresh still the same

**Comment by aldostools** [comment]
Aaah you mean sLaunch :) ok I will check that.. thank you

**Comment by RandQalan** [comment]
yea sorry

**Comment by aldostools** [comment]
This is the fix for slaunch.sprx
[slaunch.zip](https://github.com/aldostools/webMAN-MOD/files/4783337/slaunch.zip)

The file goes in /dev_hdd0/tmp/wm_res or wait until I release the fix

**Comment by RandQalan** [comment]
it did after

**Comment by RandQalan** [comment]
i know i am a pain did u know your fix for mamba is causing mamba fan control to run at 90% speed

**Comment by RandQalan** [comment]
webman control is fine

**Comment by aldostools** [comment]
How do you get the 90%? Not running webMAN?

**Comment by RandQalan** [comment]
on system con control mamba pushes it at 90% always now

**Comment by aldostools** [comment]
The payload is not doing anything extra than before... all the opposite, it does less now.

**Comment by RandQalan** [comment]
o well i figured let u know with webman all works fine if it controls it

**Comment by aldostools** [comment]
Thanks...  I'm currently using webMAN and the temp is 68C.

I don't know how you got that 90%

**Comment by RandQalan** [comment]
just let system control it with mamba do a reboot see

**Comment by RandQalan** [comment]
your new on btw

**Comment by aldostools** [comment]
I  changed the fan curve to reach a maximum of 80%... the dynamic fan controller in webMAN is too complex to implement it in the payload

// 60°C=31%, 61°C=33%, 62°C=35%, 63°C=37%, 64°C=39%,
//  65°C=41%, 66°C=43%, 67°C=45%, 68°C=47%, 69°C=49%
// 70°C=50%, 71°C=53%, 72°C=56%, 73°C=59%, 74°C=62%,
// 75°C=65%, 76°C=68%, 77°C=71%, 78°C=74%,+79°C=80%

[mamba_486C.zip](https://github.com/aldostools/webMAN-MOD/files/4783545/mamba_486C.zip)

**Comment by RandQalan** [comment]
that one is not even loading for me

**Comment by RandQalan** [comment]
tried download update it did not install new mamba with add on fyi

**Comment by aldostools** [comment]
webMAN installer only updates /dev_hdd0/tmp/wm_res/boot_mamba.pkg

The user needs to install the pkg manually. Or am I missing something?

**Comment by aldostools** [comment]
The update from XMB does not update Mamba either.

**Comment by RandQalan** [comment]
yea that the one

**Comment by RandQalan** [comment]
on update did not try pkg
