### ISSUE TITLE
Possible new issue Mamba for rebug

### ISSUE THREAD

**Issue by RandQalan** [aldostools/webMAN-MOD#368]
just had major problem
fresh install of webman and mamba play PSN game for some time
leave system off for a while turn system on BSOD
only fix was to either check for problems or rebuild database on boot

from look of it maybe a rebug problem not completely disabled cobra like both cores are loading same time causing BSOD

**Comment by aldostools** [comment]
I doubt Cobra and Mamba could be loading concurrently due Rebug only loads Mamba on boot when Cobra is disabled.

**Comment by RandQalan** [comment]
i don't know what is causing it only happens when i turn off system 3 min or longer

**Comment by RandQalan** [comment]
FYI did u know that psn loading with rap can still be done on rebug even with cobra off

**Comment by aldostools** [comment]
Try re-downloading and installing the payload again... if it is recurrent, please let me know.

**Comment by aldostools** [comment]
> FYI did u know that psn loading with rap can still be done on rebug even with cobra off

Yes I know... Mamba/Cobra only creates the RIF. Once the RIF exists, the PSN game is decrypted without Cobra intervention.

**Comment by RandQalan** [comment]
@aldostools nope still same BSOD on boot

**Comment by aldostools** [comment]
I'm going to test... I'll return to you after I check it.

**Comment by RandQalan** [comment]
k

**Comment by aldostools** [comment]
Please try installing this build...
[mamba_486C.zip](https://github.com/aldostools/webMAN-MOD/files/4789329/mamba_486C.zip)

I couldn't reproduce the BSOD issue, but I think I fixed the issue with the 90% fan speed and maybe this issue too.

**Comment by RandQalan** [comment]
fan control working fin but still BSOD on boot if turned off for some time

**Comment by aldostools** [comment]
I suggest that reinstall you CFW... I rebooted my console like 20 times in different ways and I never got the BSOD using this build.

**Comment by RandQalan** [comment]
You were correct think somehow ps3 browser got corrupted reinstall of cfw fixed it.
