### ISSUE TITLE
parental control after installing .pkg

### ISSUE THREAD

**Issue by dudasx9** [aldostools/webMAN-MOD#369]
when i install the latest version of webman, it creates an icon of parental control content but i dont have any parental control enabled. Im on hen (4.86).

**Comment by aldostools** [comment]
Where did you get webman? I don't use parental in anything related to webman.

Could you post a picture of the issue?

**Comment by dudasx9** [comment]
nvm got it to work by doing a hard reboot, my fan is going crazy tho! xD
