### ISSUE TITLE
ps3netsrv not loading ISO images anymore (Windows & Linux)

### ISSUE THREAD

**Issue by cannondale0815** [aldostools/webMAN-MOD#370]
ps3netsrv from webMAN MOD 1.47.28 does not appear to load ISO images anymore, only expanded folders. I tried both the Windows version (20200611) as well as the Linux version (20200529), the latter of which I compiled from source on Ubuntu 18.04.

Symptoms: ps3netsrv says 'open "/PS3ISO/NAME_OF_TITLE.iso"', but then nothing happens on console, not even after waiting for 15 minutes.

Switching back to earlier versions of ps3netsrv for both platforms resolves this issue and ISO images load find in those (i.e. Linux build 20170310 and Windows build 20190630).

**Comment by aldostools** [comment]
Thank you for your feedback.  I just mounted an ISO using the ps3netsrv 20200611 found in the release page. Here is the screen of the ISO mounted remotely:
![image](https://user-images.githubusercontent.com/974897/85187909-5b3d1600-b271-11ea-8558-43588c2a172c.png)

![image](https://user-images.githubusercontent.com/974897/85188868-d7d2f300-b277-11ea-8f49-b8df58bb9d75.png)

Other users also have confirmed that it's working on linux.

I suggest that try disabling your firewall and restart the PS3 if you notice a slow connection.

**Comment by cannondale0815** [comment]
Thanks @aldostools! Firewall is not the issue. But all my ISOs are createed with PS3 ISO Tools 2.2 -- could that be part of the issue? 100% reproducible and only happens with newer versions of ps3netsrv (see details I gave at top).

Are there any more detailed logs I can look into or is there a debug mode that would give me more information that I could pass on?

Thanks for these great tools btw, I've used your software for quite some time now.

**Comment by cannondale0815** [comment]
@aldostools, so I ran another series of tests with the Windows build 20200611. I launched five non-ISO titles, and all of them worked fine. I can see how it's building virtual ISOs just fine and then starts the titles.

I then also tested five ISOs that I had made in the past using PS3 ISO Tools 2.2. None of them worked, they all get stuck on "open XYZ.iso" and then nothing further. 

I then tested the same five ISOs with the older 20190630 build (again on Windows), and they all work just fine.

So to me it's clear: For whatever reason, my ISOs that were created with PS3 ISO Tools 2.2 work fine on build 20190630 but don't work anymore on build 20200611.

I don't know which build introduced the incompatibility, but it's definitely a reproducible issue.

Happy to share any further details with you. Or if the guidance is to stay away from PS3 ISO Tools, happy to listen to any suggestions as to which tool I should be using to re-create my ISOs. For reference, in PS3 ISO Tools I always choose "makeps3iso".

Lastly, the primary reason of why I chose to create ISOs for some games, rather than just using a folder structure, is because some games load faster that way. So any game that in the past took a long time on the "building virtual iso" step, I converted to ISO, which resulted in faster load times.

Thanks!

**Comment by kam821** [comment]
@cannondale0815 @aldostools 
Isn't it related to https://github.com/aldostools/webMAN-MOD/issues/366 ?
It's known, that several ps3netsrv releases (newer than 20200520A) had problem in the past, but 20200609+ Linux work fine.
I dont use Windows release, but if is not working, maybe it is caused by seek optimization that produced problem in the Linux version and is still in the source code and Windows binaries? (#ifdef WIN32)
https://github.com/aldostools/webMAN-MOD/commit/c7fd3a13ad7631ed8c5ce6ec3f7c5c22c459ce62

**Comment by aldostools** [comment]
Thank @kam821  for your feedback. I also guessed the same, but in my tests the version with seek optimization worked perfectly (as I posted above).

Anyway @cannondale0815 you can test this Windows version that uses the original file seek.
[ps3netsrv_20200620_win32_original_file_seek.zip](https://github.com/aldostools/webMAN-MOD/files/4808205/ps3netsrv_20200620_win32_original_file_seek.zip)

If build 20200620 a doesn't work, I suggest you that test creating a new ISO with another tool (e.g. [Cobra_GenPS3iso_v2.0.zip](https://github.com/aldostools/webMAN-MOD/files/4808210/Cobra_GenPS3iso_v2.0.zip))

**Comment by cannondale0815** [comment]
> Thank @kam821 for your feedback. I also guessed the same, but in my tests the version with seek optimization worked perfectly (I as posted above).
> 
> Anyway @cannondale0815 you can test this Windows version that uses the original file seek.
> [ps3netsrv_20200620_win32_original_file_seek.zip](https://github.com/aldostools/webMAN-MOD/files/4808205/ps3netsrv_20200620_win32_original_file_seek.zip)
> 
> If build 20200620 a doesn't work, I suggest you that test creating a new ISO with another tool (e.g. [Cobra_GenPS3iso_v2.0.zip](https://github.com/aldostools/webMAN-MOD/files/4808210/Cobra_GenPS3iso_v2.0.zip))

Hey @aldostools, I tried that custom version and indeed my ISOs work fine now. I tested the same five that previously wouldn't load, but now they load just fine. Thanks a bunch!

I'm seeing that @kam821 is saying that more recent versions of the Linux build (he says 2020609+) also have the seek optimizations issue fixed. Is that the one in the master branch? I'll try that one next.

Thank you both for your active assistance!

EDIT: I now also tried Linux build 20200611 (from master) and can confirm that my ISOs load fine in that build, too. So the hunch @kam821 had was indeed correct. So both the custom Windows build you gave me above, as well as the latest Linux build from the master branch are both working fine for my ISO images now.

**Comment by aldostools** [comment]
Published [ps3netsrv 20200620 ](https://github.com/aldostools/webMAN-MOD/releases/download/1.47.28/ps3netsrv_20200620.zip) - Disabled file seek optimization (now available as a compilation flag)

Same file as above + src is included
