### ISSUE TITLE
No PSP Covers if game is on NTFS

### ISSUE THREAD

**Issue by lmipsum** [aldostools/webMAN-MOD#373]
Please extend the title ID check for PSP IDs like: UCAS*, UCKS*, UCUS*, ULJM*, ULJS*, ULES*, ULUS*.

If a PSP game is on NTFS drive and it's title ID doesn't start with NP*, then the webMAN-MOD is unable to find cover for it from defined CUSTOM_PATH nor from the same folder if the image file is stored next to the ISO backup with the same file name even if the backup is named in TITLEID-[NAME].

I'm storing my PSP backups in NAME [TITLEID] format on NTFS, and the covers appears just fine from the defined CUSTOM_PATH if the backup's title ID starts with NP*, but most of the title IDs starts with ULUS*.

The only workaround at the moment is if I'm adding fake title IDs starting with NP* to the name of the backups and storing the covers with the fake IDs.

**Comment by aldostools** [comment]
You can try this test build...
https://www.sendspace.com/file/9adqrk

**Comment by lmipsum** [comment]
I tried with both TITLEID-[NAME] and NAME [TITLEID] formats, and also with having the cover images directly next to the files with the same name, but didn't change anything. The covers are still missing, if i'm not using fake IDs, except for the NP* games.
- Had full install with the attached pkg
- I've set the CUSTOM_PATH
- Launched prepNTFS without keeping the previous cache
- Then scanned the XML and HTML

**Comment by aldostools** [comment]
It seems I uploaded the wrong file :-(

Here is the file that I intended to share.
[webftp_server.zip](https://github.com/aldostools/webMAN-MOD/files/4864310/webftp_server.zip)

Upload with sprx with ftp to /dev_hdd0/plugins then reboot.

**Comment by lmipsum** [comment]
That one worked, I just refreshed the XML and HTML after the reboot and the covers appeared. Thank you very much!

**Comment by aldostools** [comment]
Thank you for your feedback.
