### ISSUE TITLE
Folder mapping only works for ROMS

### ISSUE THREAD

**Issue by Dvvarf** [aldostools/webMAN-MOD#374]
Hello!

A month ago I updated webMAN-MOD to 1.47.27 and was really happy to know that it now supported folder mapping through INI files. I setup the mapping (had to try some way to do this) and discovered that it is working only for ROMS. So I can put ROMS.INI into ps3netsrv directory and it would work, but no PS3ISO.INI or anything else... The directories were available through manual address entry (in web file browser), but were not visible anywhere else and would appear empty.

The problem:
After some time I figured that the problem was in paths that webMAN-MOD is scanning through. When scanning through ROMS, paths "ROMS/GBC", "ROMS/GBA" are being scanned. And ps3netsrv is looking for INI file based on the "/" delimiter... When scanning PS3ISO, the actual path is "PS3ISO", so there is no delimeter. I'd fix the scan function to also look at path "as as" first and only after that start looking for delimiter.

Sorry if this explanation was not clear enough, I'm not sure how to describe it better...

**Comment by Dvvarf** [comment]
Submitted pull request with a couple of changes to allow this:
```
ps3netsrv
    PS3ISO.INI
    PSXISO.INI
    ROMS.INI
```
With every ini file pointing to corresponding directory somewhere else.

**Comment by aldostools** [comment]
(I think this comment should be posted here. It's also in the pull request #375)
I think you're doing the mapping in the wrong way.

This is the structure that I used:
1- My shared folder is C:\DATA\SHARE
2- It contains various sub folders: GAMES, PS3ISO, PSPISO, PSXISO, DVDISO, ROMS, etc.
Example: C:\DATA\SHARE\PS3ISO contains 1 file: Angry Birds [BLUS31273].iso (see the picture below)
3- ps3netsrv is in C:\DATA\SHARE\ps3netsrv.exe
4- PS3ISO.INI is next to the folders listed in number 2,  i.e.  C:\DATA\SHARE\PS3ISO.INI
5- PS3ISO.INI is adding the content of X:\Soft\ps3\mapping test\_PS3ISO_ to C:\DATA\SHARE\PS3ISO (see picture)
6- As ps3netsrv is in the same folder of PS3ISO, I simply run it without parameters: C:\DATA\SHARE\ps3netsrv.exe

![image](https://user-images.githubusercontent.com/974897/86417546-5168d900-bc9b-11ea-8df9-ec3aad54ea79.png)

VERY IMPORTANT: The sub folders in the SHARE folder must be named like number 2, NOT like you did: `_PSPISO_`

The paths listed inside PS3ISO.INI, PSPISO.INI, etc. can have any name.
