### ISSUE TITLE
Extended wm_ignore.txt

### ISSUE THREAD

**Issue by lmipsum** [aldostools/webMAN-MOD#377]
I would like to request a feature to ignore even full paths in the wm_ignore.txt file (not just in ROMS folder) and have a button in the webMAN MOD settings to enable/disable the ignore file on scan if it's possible.
I think it would be a nice a feature for custom parental filtering without storing the games on separate drives or relying on the content rating.

There could be even flags in the ignore file, like if the line starts with * then it won't be affected by the button, and the line will be excluded from the scan always.

**Comment by aldostools** [comment]
Try downloading the latest binaries in the release section:
https://github.com/aldostools/webMAN-MOD/releases

The `wm_ignore.txt` has been extended to all content when the flag is enabled in /setup.ps3. 
However, the wildcard feature is not implemented. I may consider to add it later, depending of the popularity of this feature.

The option for `wm_ignore.txt` can be enabled or edited under the section `Scan for content` in /setup.ps3.

If the `ADMIN/USER MODE` is enabled (requires to activate the combo `L2+R2+∆` in /setup.ps3) the option `wm_ignore.txt` is auto-enabled for `USER MODE` (need to refresh XML and XMB to see the changes).

The ignore filter works by file name (without path) or by TITLE ID. Add one entry per line in `wm_ignore.txt`.
The ignore check is case sensitive and limited to a list of up to 2KB.
<hr>
💡 TIP:
You can consider also the option Content Profile (e.g. PS3ISO_1, GAMES_1, BDISO_1, etc.) to show certain content only when the selected profile is enabled in /setup.ps3. You can have up to 4 different profiles to classify the hidden content.
<p>
Note: The content in the folders GAMES, PS3ISO, etc. (without the sufix "_1", "_2", "_3" or "_4") is listed in all profiles.

**Comment by lmipsum** [comment]
I have issues accessing the setup after activating the ADMIN/USER MODE because I cannot deactivate it with the L2+R2+TRIANGLE combo, and I can no longer access the PS3 via FTP either.

**Comment by lmipsum** [comment]
You given so many options, I'm still testing it, I will give you detailed report once I've finished it.

**Comment by aldostools** [comment]
Thanks for the feedback..  I have found a bug where it was not filtering content by title_id on USER mode.

It's fixed in the latest installer in https://github.com/aldostools/webMAN-MOD/releases

**Comment by lmipsum** [comment]
I've added nearly a hundred title IDs to the wm_ignore.txt, left the checkbox unchecked next to it and enabled the L3+R2+O combo for the admin/user mode.
I've also added a custom combo to refresh xml+xmb (GET /refresh.ps3?xmb), because the L3+L1+SELECT+R1 didn't work for me for whatever reason.
Now I can just enable the admin mode and do a full refresh to show the hidden games or vica versa. I had difficulties with the earlier build getting it to work, but this last one works like a charm, especially with the combos.

I love that I can organize and store my games on whatever drive I would like to and filter the content without excluding a whole drive from scan. Even more now I can even hide PS2 titles which are restricted to the internal HDD.

For note: When we turn on the console, the FTP connection won't be established until the admin mode is enabled. Don't know if it was intended, but while it is giving an extra layer of security, the problem with it is if the user is unable to press the combo to enable the admin mode, then it can be difficult for some to restore things at first sight without FTP.

Great work!

**Comment by aldostools** [comment]
Thank you for your feedback.  The FTP access is disabled intentionally in USER mode as a security layer.

If you configure a password in /setup.ps3, you can re-enable the ADMIN mode remotely using:
`http://<ip-address-of-ps3>/admin.ps3?enable&pwd=<password>`

Only the remote access to /setup.ps3 or FTP is disabled. They can be re-enabled if you have physical access to the PS3 or use the web command mentioned above. 

About the combo for the refresh XML + reload, try this: hold R1+L1 then without release them, hold SELECT and press L3.
You may need to keep them pressed for up to 5 seconds until you see the notification.

**Comment by lmipsum** [comment]
I will test those too by tomorrow! Thank you!

**Comment by lmipsum** [comment]
The password thing works and it's great!
I still couldn't get the default reload combo get to work, but the custom combo works just fine.
I'm pretty sure this advanced filter feature will get popular. Thank you!
