### ISSUE TITLE
Cannot see configuration opcion

### ISSUE THREAD

**Issue by facurazer23** [aldostools/webMAN-MOD#378]
Hi, I got a PS3 Slim cfw Rebug 4.86 cex, and when install webman with L1, I cannot see option menu or configuration of the webman carpet, (my games) I can only see the games I have. Thanks.
![IMG_20200706_223959](https://user-images.githubusercontent.com/67244934/86685697-1851a100-bfda-11ea-9ae3-47d28cd0474c.jpg)

![IMG_20200706_223901](https://user-images.githubusercontent.com/67244934/86685960-55b62e80-bfda-11ea-901b-888a8df6e32e.jpg)

**Comment by aldostools** [comment]
Delete /dev_hdd0/tmp/wm_config.bin
Refresh the XML using SELECT+L3
Then refresh the XMB or run prepISO

Deleting wm_config.bin will reset the settings to the default values.

**Comment by facurazer23** [comment]
> Delete /dev_hdd0/tmp/wm_config.bin
> Refresh the XML using SELECT+L3
> Then refresh the XMB or run prepISO
> 
> Deleting wm_config.bin will reset the settings to the default values.

Yes it works, thank you!!
