### ISSUE TITLE
sMAN GUI

### ISSUE THREAD

**Issue by floppyD** [aldostools/webMAN-MOD#379]
What do "sMAN GUI" on the web interface really does? I thought it was related to that menu that can be called by holding START or L2+R2, but disabling it doesn't disable the combos.

**Comment by aldostools** [comment]
Expand the section for the Combo Shortcuts that appears a the bottom of /setup.ps3 and uncheck the option GAME MENU.

sMAN GUI is the blue & gray theme used in web.
The original webMAN theme is black & white.
.

**Comment by floppyD** [comment]
Ah, so that's what got me confused, it's not disabling the GAME MENU combo, just changing the web theme as far I noticed.

**Comment by aldostools** [comment]
I just noticed that there was a conflict with the name of another setting, that prevented to disable the GAME MENU.

It's fixed in the latest build available in:
https://github.com/aldostools/webMAN-MOD/releases

**Comment by floppyD** [comment]
Nice, thank you.
