### ISSUE TITLE
Sorry this a question about ROMS

### ISSUE THREAD

**Issue by uNbAs** [aldostools/webMAN-MOD#38]
Hi, Sorry my english but I hate write using a translator

Its posible run ROMS over network using ps3netsrv? Im using ps3netsrv for PS3ISO and work OK but ROMS not see on XMB

**Comment by aldostools** [comment]
ROMS are listed only for local devices: /dev_hdd0, /dev_usb*** (fat32), etc.

They cannot be mounted from NTFS or over network using ps3netsrv.
