### ISSUE TITLE
ps3netsrv 20200707 broke support for paths with non-ASCII characters

### ISSUE THREAD

**Issue by nl6720** [aldostools/webMAN-MOD#380]
ps3netsrv 20200707 doesn't support unicode characters in paths. The folder path gets truncated until the first non-ASCII character.
E.g. using a `/data/testµ1/PS3` path:

`ps3netsrv /data/testµ1/PS3 38008`
```
ps3netsrv build 20200707 (mod by aldostools)
Path: /data/test
```

With ps3netsrv 20200620 it works just fine:

`ps3netsrv /data/testµ1/PS3 38008`
```
ps3netsrv build 20200620 (mod by aldostools)
Path: /data/testµ1/PS3
```

**Comment by aldostools** [comment]
Thank you for your feedback. Please test if this version fixes the issue (it now only checks for CR character at the end of the line).
https://github.com/aldostools/webMAN-MOD/releases/download/1.47.28/ps3netsrv_20200708.zip

**Comment by nl6720** [comment]
20200708 works.
