### ISSUE TITLE
(1.47.28) Installing PKG from external NTFS hdd, scanned with prepISO (1.27), freezes PS3

### ISSUE THREAD

**Issue by chinchan54** [aldostools/webMAN-MOD#383]
I have my PKG files in a folder called "PKG" on an external NTFS HDD.
I run prepISO 1.27 and it finds the PKGs like it should.
But when I select any PKG to install, it freezes after mounting.
But on 1.47.27 it doesn't freeze. 
So my conclusion is that it freezes because of the auto installing feature that is new in 1.47.28.

I tried it on Rebug 4.85.1 Lite and 4.86.1 Lite and it is the same.

**Comment by aldostools** [comment]
Please try the latest commit available in releases page:
https://github.com/aldostools/webMAN-MOD/releases

The option "Auto Install PKG" now can be disabled from /setup.ps3
(Find the option expanding the section "webMAN MOD Setup")

**Comment by chinchan54** [comment]
I disabled "Auto Install PKG" and now it doesn't freeze. Thank you for the option!
Will there be a fix (in the future) for the Auto Install?

**Comment by aldostools** [comment]
I'll fix it if I find the cause of the freeze, but as I don't have that issue on my system it's difficult to fix.

**Comment by aldostools** [comment]
@chinchan54 I uploaded a moment ago a new build with a new fix that attempts to fix the random freeze.

You can download the new build from:
https://github.com/aldostools/webMAN-MOD/releases
