### ISSUE TITLE
Instant screenshot over WWW?

### ISSUE THREAD

**Issue by b-** [aldostools/webMAN-MOD#385]
It'd be really useful for me if I could click a link in WebMAN that would take a screenshot to a temporary location and then display it in the browser.

As far as I understand, WebMAN can take a screenshot one way or another already, so being able to simply send it to a temp folder and then serve it to a browser upon going to a specific URI would be really useful. Even better would be if I could refresh the page to get a new screenshot.

**Comment by aldostools** [comment]
webMAN MOD already allows to take the screenshot of XMB using:
**/browser.ps3$screenshot_xmb/**&lt;path+filename>

Also it allows to execute a sequence of commands in 2 ways:
1. Separating the web commands in an URL with a semicolon (;)
2. Creating a .bat script and executing it through the /mount.ps3 command

Note: You may need to add a **/wait.ps3?**&lt;secs> before try to display the captured image.

However, webMAN cannot take screenshots of in-game screens. At least I don't know how to do it.
webMAN enables an official option on in-game XMB and the use must take the screenshot manually.

**Comment by b-** [comment]
Thanks for the quick reply! I really appreciate it!

So should something like, `/browser.ps3$screenshot_xmb/dev_hdd0/tmp/1.png;/wait.ps3?1;/dev_hdd0/tmp/1.png` work? (I'm going to try this right now, but I suspect I got something wrong.)

**Comment by b-** [comment]
That seemed to _almost_ work (`/browser.ps3$screenshot_xmb/dev_hdd0/tmp/1.png;/wait.ps3?1;/dev_hdd0/tmp/1.png`) except I got a 404 on the 1.png. Is there a safe, writable location?

**Comment by aldostools** [comment]
In theory it should work (obviously you should include the http://ip-address)

Unlike the in-game screenshot, the web command only captures the XMB screen in BMP format.

Try increasing the wait to 3 or wait for the file name. The /tmp path should be fine or if you prefer write to the root of /dev_hdd0.

BTW I'm currently busy at work... so I cannot test this myself.

**Comment by b-** [comment]
I'm currently using the URI `http://xxxxxxxx/browser.ps3$screenshot_xmb/dev_hdd0/tmp/1.bmp;/wait.ps3?1;/dev_hdd0/tmp/1.bmp`. My local DNS server has an A record for xxxxxxx pointing to the PS3.

I still get a 404, leading me to think there's something wrong with my path to save the screenshot/the syntax. I see a notification on the PS3 saying that a screenshot is being taken, but it doesn't seem to get saved, even if I manually browse the location afterwards.

Obviously this isn't as important as your work, so please don't feel as though I'm asking you to investigate that right now! 😁

Thanks!

**Comment by aldostools** [comment]
I redacted your IP address... this is a public forum and anyone could access your console and cause damages if you are not behind a firewall.

If I'm correct, after the screenshot is taken there is an URL that you just need to click.

If you cannot find a workaround I could add an option to automatically show the screenshot after the capture, but it should wait for the next release/update.

**Comment by b-** [comment]
That hostname only resolves under my local network (private, local DNS zone), and to a private (192.168) IP address. Don't worry, I'm a network guy. 😁 

Aside, http://ps3.xx/browser.ps3$screenshot_xmb doesn't seem to work either, returning just `screenshot_xmb` and a back button, but showing `screenshot_xmb` on the TV as an alert.

**Comment by aldostools** [comment]
I will check it later and will come back to you after I review it.

**Comment by b-** [comment]
Thank you! Appreciated immensely!

**Comment by aldostools** [comment]
As promised, I added the option to show the XMB after capture:
/browser.ps3$screenshot_xmb?show

As bonus, I added another option to reduce the image size to 25% (but image quality is lower)
/browser.ps3$screenshot_xmb?show?fast

Download the updated build from https://github.com/aldostools/webMAN-MOD/releases

**Comment by b-** [comment]
Thank you! This is awesome!

**Comment by aldostools** [comment]
Want to see something cool?

Save the following code to /dev_hdd0/xmb.html then open that URL on the PC browser 😄 

```
<body bgcolor="#000">
<center>
<img id="xmb" src="/browser.ps3$screenshot_xmb?show?fast">
</center>
<iframe id="pad" src="http://pad.aldostools.org/pad2.html" height=600 width=100%></iframe>
<script>

var xmb = document.getElementById('xmb');
xmb.src = '/browser.ps3$screenshot_xmb?show?fast?rand=' + Math.random();

setInterval(function() {
    var xmb = document.getElementById('xmb');
    xmb.src = '/browser.ps3$screenshot_xmb?show?fast?rand=' + Math.random();
}, 1500);

var width  = document.body.scrollWidth;
var height = document.body.scrollHeight;
if(width > height) document.getElementById("pad").height=400; 
</script>
````

**Comment by b-** [comment]
Wow, that's awesome! I wanted this for the sake of monitoring installing and updating stuff, and that html is so useful!

I changed the last line to `<iframe src="http://pad.aldostools.org" height=200 width=100%></iframe>` because I was having trouble setting the IP without the full pad page being shown, but it's working now. Thanks so much!

**Comment by aldostools** [comment]
I used 600, to show the complete virtual pad in the smartphone ;) 

To monitor the installation I suggest to increase the interval from 1500ms to a higher number.
As the screenshot pauses the PS3, your installation would take longer.
