### ISSUE TITLE
Gamepad input problems in XMB

### ISSUE THREAD

**Issue by eshoy18** [aldostools/webMAN-MOD#387]
-Using Firmware 4.85 CEX PS3HEN 3.01
-webMAN-MOD ver 1.47.29

While using Mayflash's MAGIC-NS controller adapter, there are frequent input problems: sometimes a button press isn't registered, while other times it is registered multiple times (for example, pressing the d-pad once will cause the XMB to quickly scroll).

-This only happens while webMAN-MOD is loaded. Unloading it from memory stops the issue.
-This only happens in XMB
-This doesn't happen while using other input methods I've tested (third party DS3, DS4 over USB, DS4 over Bluetooth)
-This doesn't happen when using the MAGIC-NS on other devices (PC and Nintendo Switch)

**Comment by aldostools** [comment]
Thank you for your feedback. Unfortunately this is an issue that I cannot verify due I only use original SIXAXIS and DS3 controllers.

webMAN MOD provides a web interface for game pad emulation. There should not be any conflict with your existing controllers, unless your are using the ps3xpad plugin developed by OsirisX (both plugins share the same libraries).

My suggestion is that use a first party controller (DS3, DS4, SIXAXIS) while you use webMAN MOD.
