### ISSUE TITLE
MGS2 Trial demo turns ps3 off

### ISSUE THREAD

**Issue by LanceVGoss** [aldostools/webMAN-MOD#389]
Metal gear solid 2 trial demo doesn't won't load Eu version Ntsc will load bur when leaving main menu ps3 will abruptly turn off this has been test on 3 ps3s iso format can a config be made please. Would be grateful 

SLED-50117 won't boot

https://www.romsuniverse.com/download/playstation-2/metal-gear-solid-2-sons-of-liberty-trial-edition-rom160546

**Comment by aldostools** [comment]
This game have been ported to PS3 as Metal Gear Solid: HD Collection, try that game

Or try asking to the experts in the forum of PSX-PLACE, maybe they could check if some of the current CONFIG files could be converted for your game.
https://www.psx-place.com/threads/compatibility-list-ps2-on-ps3.1306/
