### ISSUE TITLE
webMan MOD 1.47.30 stoped working after change IDPS

### ISSUE THREAD

**Issue by jhonathanc** [aldostools/webMAN-MOD#390]
I have installed webMan MOD on a fresh PS3 hard drive installation. As usual, I got the latest version of webMan MOD and tried to change my IDPS from sMan on PS3, but the first field not allowed to include all numbers. So, I tried to change it from PC, also on sMan. From Chrome, the field let me put all characters, but after save and restart the PS3, the webMan failed to start (no errors appears, but the plugin didn't load, as I can't access ftp/sMan).

I'm using Rebug 4.86.

**Comment by jhonathanc** [comment]
The issue is probably fixed, since I was not able to reproduce it anymore.

**Comment by aldostools** [comment]
I think this issue is related to the bug reported about only accepting 14 characters for the IP address.
https://www.psx-place.com/threads/webman-ps3netsrv-ip-address-limited-to-14-characters.34157/#post-297015

I commented in that post:

> This is a bug of the PS3 Web Browser inline keyboard prediction feature. This doesn't happen if you use a browser on PC or tablet.
> 
> BUG: If you enter 192.168.100.123 then press Start to close the inline keyboard, it removes the last character: 192.168.100.12
> 
> **SOLUTION: if you change to URL mode (SELECT) or press R1 (to clear the prediction box), the value is accepted complete.**
>
