### ISSUE TITLE
WebMAN keeps crashing

### ISSUE THREAD

**Issue by LanceVGoss** [aldostools/webMAN-MOD#397]
Webman keep's crashing then going to Recovery Menu seems to be caused by CCAPI 2.80 Rev 7 once uninstalled everything's ok this didn't use to happen.
Mount ISO in WebMan / Load Game screen go's blank looks like its going to load Then reboots into Recovery Mode.

PS3 Firmware is Rebug 4.84 Rex running in CEX haven't tested DEX
CCAPI Console Manager for PS3 2.80 REV7

Hope this gets fixed if not then no worries

**Comment by aldostools** [comment]
Please report the issue to CCAPI developer... that project is not open source, so it's impossible to verify what's happening.

webMAN MOD alone is an open source alternative to that software for RTM.
