### ISSUE TITLE
Metal Gear Solid 4 [BLES00246] (not iso) not work after update, always return to XMB

### ISSUE THREAD

**Issue by NeptuneScarlet** [aldostools/webMAN-MOD#403]
Metal Gear Solid 4 with merge demo.dat files (necessary for the control to work in the menu) not work in 1.47.30, it was working perfect before updating.

**Comment by aldostools** [comment]
Install a previous version of webMAN MOD and play the game with it to verify that it works.
Then report the exact commit that you installed.

**Comment by NeptuneScarlet** [comment]
Problem solved, I had to uninstall and then install webman through the PKG, apparently the option to update within the configuration broke my webman.
