### ISSUE TITLE
ps3netsrv possible to add auto-startup?

### ISSUE THREAD

**Issue by sp0ok3r** [aldostools/webMAN-MOD#404]
Possible to add auto start up with windows and auto-start server?

**Comment by aldostools** [comment]
The GUI has the option of start with Windows and minimize the server to system tray.

However you need to be logged as an user. To start without logging you need to run the server as a service.

If you don't want to use the GUI to start with Windows, you can put the ps3netsrv.exe in the Startup folder.

**Comment by sp0ok3r** [comment]
ok, but using the ps3netsrv.exe i cant close to system tray

**Comment by aldostools** [comment]
No, ps3netsrv.exe can't. The GUI can minimize to the system.

Run **PS3_NET_Server.exe**. It starts ps3netsrv.exe inside its window.
https://github.com/aldostools/webMAN-MOD/tree/master/_Projects_/ps3netsrv/bins/Windows

**Comment by john-clark** [comment]
Step 1: Download & Unzip https://nssm.cc/ci/nssm-2.24-101-g897c7ad.zip

Step 2: From administrator command line type: C:\> nssm.exe install ps3netsrv

it will open GUI, then simply browse it to: ps3netsrv.exe Change Log on tab as needed.  Dependencies on MpsSvc

make sure permissions are correct
