### ISSUE TITLE
(question) how do I dump my current idps and use an alternate one with Webman?

### ISSUE THREAD

**Issue by Lion4K** [aldostools/webMAN-MOD#405]
I decided to try venturing online after a year or so and I got an alternate cid in case I get banned I don't smoke my console's original.

How do I use the feature?
I'm a lil dumb when comes to finding instructions, I'm sorry to bother.

Thanks in advance!

**Comment by aldostools** [comment]
Go to http://127.0.0.1/setup.ps3

Expand the section IDPS & MEM Setup, then enter your new IDPS in the corresponding fields (click buttons at the right side to see what you type)
![image](https://user-images.githubusercontent.com/974897/90544537-3d970a80-e155-11ea-8985-043c40632e6d.png)

**Comment by Lion4K** [comment]
Yeah, but the I'd I bought is like one single long string and there seems to be 2 strings to each.
And I don't need to copy that down to get it back? Or it kinda doesn't write to the console system?

**Comment by Lion4K** [comment]
It's HEN btw, disabling cfw syscalls doesn't bring hen down too? Will it affect the functionality of fan controller? I kinda want that on at all times.

**Comment by aldostools** [comment]
The IDPS is a value of 16 hex digits (128bit) that is split in 2 variables of 64bit (8 digits each).

The CFW syscalls are specific syscalls that are not present on OFW. Some games and PSN can detect them and flag your account or console or both. Disabling the CFW syscalls does not affect the HEN payload or the fan controller.

Do not execute homebrews, cheat or login with CFW syscalls enabled when you login to PSN

**Comment by Lion4K** [comment]
Oh I see so if I split the string it will work.
I counted the digits and the number checked.

**Comment by Lion4K** [comment]
I think I got it right, but still r2 circle combo shows the  original one, same for bg toolset, how can I test if it it's spoofing correctly?

**Comment by aldostools** [comment]
http://127.0.0.1/cpursx.ps3 should show the new and the original IDPS
(The values are collapsed at the bottom of the screen, press the link near the FW version to show the IDPS/PSID)

If only show the original twice, you probably didn't save the settings in /setup.ps3

**Comment by Lion4K** [comment]
I see, I'll check it as soon as I get home tomorrow

**Comment by Lion4K** [comment]
It worked, even Apollo was fooled by it.

Thanks again for your time and help!!
