### ISSUE TITLE
(question) how does the decrypt save game feature works?

### ISSUE THREAD

**Issue by Lion4K** [aldostools/webMAN-MOD#406]
I tried finding some information on it but I didn't found.
Can I use if to transfer my saved games from one account to another on the same system?

I'll be changing accounts to preserve my main account and don't wanna lose my progress, like unlocked stuff in Worms U. Mayhem.
But I tried just copying to usb and restoring it it won't cut it.

I know there's some windows tools available to re-sign saves but I don't have access to windows. Or a powerful enough machine to virtualize it. (I only have a raspberry pi 3b+).

Thanks in advance!

**Comment by aldostools** [comment]
webMAN MOD is only capable of "unlock" saves modifying the attribute in PARAM.SFO of the savedata.

webMAN MOD does NOT decrypt the saves!!

That feature is available in Apollo Save Tool
https://store.brewology.com/ahomebrew.php?brewid=321

Or on the PC using Bruteforce Save Data
https://bruteforcesavedata.forumms.net/

**Comment by Lion4K** [comment]
What do you mean by unlocking saves? 
Does it make it compatible to any other profile and or psn accounts?

**Comment by aldostools** [comment]
It just unlocks "copy protected" saves allowing them to be copied to USB... nothing more.

For saves management use Apollo Save Tool or Bruteforce Save Data on PC. I already told you.

**Comment by Lion4K** [comment]
Oh no, I'm gonna use the solutions you provided, I'm just asking the functionality of that thing.
It's a rather interesting thing to leave turned on.

Thanks!!
