### ISSUE TITLE
Release of latest PS3XPAD source code from OsirisX?

### ISSUE THREAD

**Issue by rbreaves** [aldostools/webMAN-MOD#411]
I noticed that only v0.4 appears to be available in online forums and that this project credits OsirisX for his code on ps3xpad and gamepad emulation. Is there any possibility of seeing the source code for v0.8 of his project released? I am not sure of the best way to get a hold of him and would like to contribute to the project and add support for the latest PS4 DS4 controllers (PID 09cc).

**Comment by aldostools** [comment]
You should ask it to OsirixX. I don't have any connection with that author.

The virtual pad implemented in webMAN MOD was based on the open source code of ps3xpad 0.4 released to the public.
