### ISSUE TITLE
webman scan and show PSN titles in webman folder on XMB [Feature Request]

### ISSUE THREAD

**Issue by KatsutoKiyojin** [aldostools/webMAN-MOD#412]
Hey, so I like to have all my games in one spot which is easy to access and in alphabetical order. Which is why I love web man so much. The issue I have is some games only have PSN titles. It would be awesome if there was a way to make Webman scan and show PSN titles in the web man folders. So I can have all my games in one place again. I understand if there is a technical limitation that stops this from being a reality, but it would be pretty cool if you could get it to work.

**Comment by aldostools** [comment]
webMAN MOD already has the option to show (or not) the games with the game Title from PARAM.SFO
Also you have the option include Title ID as part of the title or the path and/or the title id in the "info" about the game.
![image](https://user-images.githubusercontent.com/974897/93004526-c8311680-f515-11ea-8592-6fe42d878998.png)

It looks like this:
![image](https://user-images.githubusercontent.com/974897/93004384-602e0080-f514-11ea-8f8c-1f8d6120694c.png)
