### ISSUE TITLE
FTP write rights

### ISSUE THREAD

**Issue by Arelav** [aldostools/webMAN-MOD#413]
After upgrading to the latest (webMAN 1.47.30 MOD - Simple Web Server (NTFS) [Full]) version. When I try to upload any file through FTP server I get an error 451. It doesn't matter which FTP client I use.
When downgraded to 1.47.28 FTP works just fine.
![image](https://user-images.githubusercontent.com/1059539/93539501-fc924180-f91e-11ea-82e6-f8bef90e1299.png)

**Comment by Arelav** [comment]
P.S. I can connect and navigate into the file system. Just during the upload, I have an error.

**Comment by aldostools** [comment]
Could you try 1.47.30 with the option "Unlock savedata" unchecked in /setup.ps3 ?

**Comment by Arelav** [comment]
In my case, it was unchecked by default. I tried to check this and reboot. The behaviour was the same. And then I unchecked and after reboot behaviour was as above.
Please let me know if I can get any useful information I'll try my best.

**Comment by aldostools** [comment]
Thank you for your feedback. The main change in ftp module was related to that setting.

I compiled this test version of 1.47.30 using the ftp.h from 1.47.28 20200627
[webftp_server.zip](https://github.com/aldostools/webMAN-MOD/files/5245362/webftp_server.zip)

Extract the zip and replace webftp_server.sprx in /dev_hdd0/plugins

**Comment by Arelav** [comment]
Thank you for your support and for your software in general.
It was very quick.
The old FTP plugin version works fine.

**Comment by dotstal** [comment]
I have a similar problem, after the update, I use Debian 9, and ftp in it does not want to connect in any way, through Windows 10 everything is ok. your file helped fix the situation.

**Comment by Arelav** [comment]
I think the issue can be closed since it fixed in later versions.
