### ISSUE TITLE
Freezes on Enabling Hen screen

### ISSUE THREAD

**Issue by NookumBumble** [aldostools/webMAN-MOD#415]
I'm running Hen on 4.86 HFW and WebmanMod freezes my ps3 on Enabling Hen screen so i have to reboot manually and sometimes it doesn't even boot to xmb and gives me a "Storage system not found" message, i have to reboot until system starts normally. If i uninstall Webman Mod everything is running normally.

**Comment by aldostools** [comment]
Check if the issue happens with webMAN vanilla or sMAN. Many HEN users use webMAN MOD without issues.

**Comment by NookumBumble** [comment]
Thank you so much for responding, PS3's hdd just died so i had to replace it with another one, now Hen and WebMan Mod works perfectly so the problem was the hdd.
