### ISSUE TITLE
Not really a issue but add back Confirm browser close when changing games

### ISSUE THREAD

**Issue by james1233777** [aldostools/webMAN-MOD#416]
plz would love that thx

**Comment by aldostools** [comment]
webMAN MOD doesn't touch that setting at all.

It is the user who must change that setting manually.

**Comment by james1233777** [comment]
And how would I go about doing this i like how it looked and would it work on hen

**Comment by aldostools** [comment]
webMAN MOD uses wm_proxy.sprx to accept commands from XMB. The web browser interface is rarely used by wMM.

**Comment by james1233777** [comment]
I found that file just abit ago and not sure how I make it do that where I change my games and it asked me to confirm browser close

**Comment by Masamune3210** [comment]
Confirm browser close is an option in the Internet Browser settings....

**Comment by james1233777** [comment]
Ah ok lol my dumbass
