### ISSUE TITLE
"Webman Games" suddenly disappeared. Webman Mod works fine othetwise.

### ISSUE THREAD

**Issue by Adamanimus** [aldostools/webMAN-MOD#417]
@aldostools Hi. I am on 4.86. PS3 HEN 3.0.1.
I have been using webman mod for a while and it worked fine. I copied backup to my internal HDD and refreshed my games and reloaded XMB. It stuck on reload part and I had to shut it down manually.
After reboot, Webman Games folder disappeared completely.
I can access VSH and access webman setup from there.
Can load backups from html. Fan control etc. Everything except Webman Games folder work.

I reinstalled HFW and HEN several times, I did both database rebuild and file system recovery, i believe. 
I reinstalled and uninstalled webman several times.
Manually deleted all the files from HDD. 
Yet can't have Webman Games folder.

What could be the issue? Please help me.

**Comment by aldostools** [comment]
webMAN Games menu that appears on XMB is a set of XML files generated automatically by webMAN MOD when you perform the Refresh XML (SELECT+L3) or run prepISO or open /refresh.ps3 (via XMB or browser)

These XML files are linked to XMB through an entry in **category_game.xml** stored on /dev_flash (or /dev_blind if you need read/write permissions). If that entry is not present or the files **/dev_hdd0/xmlhost/game_plugin/fb.xml** and **/dev_hdd0/xmlhost/game_plugin/mygames.xml** do not exist, then webMAN Games menu is not shown.

This is a list of things that you must check:
1- /dev_blind/vsh/resource/explore/xmb/category_game.xml has the the entry that links to **fb.xml**

You can try replacing your current file with this one.
https://github.com/aldostools/webMAN-MOD/blob/master/_Projects_/updater/pkgfiles/USRDIR/xmb/HEN/category_game.xml

This file is a modded version of the one installed by PS3HEN. If you reinstalled HEN (and nothing else) this step is not necessary.

2- Check that HEN is really enabled.

3- Check that webMAN MOD is really running. Press SELECT+START and you should see a popup with system information.

Verify that you don't have a blank boot_plugins.txt on USB drives.

4- Remove all USB devices and perform a manual refresh of XML running prepISO or pressing SELECT+L3 then reload XMB.

After XMB returns webMAN Games should appear on XMB. If it doesn't wait a couple of minutes, reboot and repeat the steps.

5- If the above doesn't work, uninstall webMAN MOD. Then try reinstalling HFW 4.86, then PS3HEN and webMAN MOD.

DO NOT INSTALL ANYTHING ELSE (like other homebrews or plugins).

**Comment by Adamanimus** [comment]
**"dev_hdd0/xmlhost/game_plugin/fb.xml and /dev_hdd0/xmlhost/game_plugin/mygames.xml**"

These files do not exist. 
I replaced category_game.xml with the one you linked above. It added app_home icon but didn't solve the issue. So I installed HFW and HEN again. Made sure to delete all the homebrews I had installed on. I made a backup of category_game.xml by renaming it before I copied over one you linked. 
But when I installed HFW and HEN again. It must have been deleted. After this I tried again and nothing. Same.

**Comment by aldostools** [comment]
Did you confirm that webMAN is running?

Did you try refreshing XML manually?
You should see a popup when the scan for content starts and another saying OK when the scan finished. After that both XML files must exist.

**Comment by Adamanimus** [comment]
Yes, I did all those steps. Very strange this webman games folder to suddenly disappear. I can mount backups fine in html. Playing some ps2 games and having fully functioning webman mad is essential for me since by mounting through webman mod i can have higher fan speed. 

Do you need anything from me to solve this issue?

**Comment by aldostools** [comment]
Try installing webMAN vanilla or sMAN.

They use the same menu in XML. Maybe you get better results with them.

**Comment by Adamanimus** [comment]
I really like Webman Mod though.
Is there anyway maybe to put those missing fb.xml and mygames.xml files in place and then do refresh xml?

**Comment by aldostools** [comment]
Well, I suggested sMAN or webMAN because they also create the XML menu. But if you don't want to try them, then mount the games using sLaunch GUI or the browser.

**Comment by Adamanimus** [comment]
I tried using sMAN but it soft-bricked my PS3. Had to reinstall HEN. As soon as Hen is enabled and plugin is loaded it froze. Had to use Managunz file manager to revert boot_plugins.txt back to its former state.
Very strange that I can somewhat use webman mod but not sMAN.

**Comment by aldostools** [comment]
The last suggestion that I can offer is try installing older versions of webMAN MOD or re-download the latest build.

It seems to be an issue particular to your system. AFAIK No other user have reported a similar issue.

**Comment by Adamanimus** [comment]
Attempted to restore file system. Gave error midway and won't let me access the OS. Had to format the HDD and lose all my save files. But after that webman is working again just as intended. Definitely seems to be problem with my system.

Thanks for this awesome tools. :)
