### ISSUE TITLE
1.47.30 freeze

### ISSUE THREAD

**Issue by N2022062** [aldostools/webMAN-MOD#419]
when press select or start to VSH MENU or GAME MENU
cant figure why.....

**Comment by aldostools** [comment]
Try setting the system language to English and check again. If you changed the system fonts, try selecting the original fonts.

There was a bug related with fonts in VSH Menu and sLaunch GUI (Game Menu), but it was fixed months ago.

**Comment by N2022062** [comment]
Yeah.yesterday I changed sys language to jap.
Back to english,fine.
I installed newest webman,anyway to fix it?

**Comment by aldostools** [comment]
IIRC there are 2 or 3 fonts for Japanese, I'm almost sure that I tested them.

Try selecting a different font. If they don't work, then you can disable these menus in /setup.ps3 or revert to English language.
