### ISSUE TITLE
ROMS over net do not select correct emulator based on path (only by extension)

### ISSUE THREAD

**Issue by rjsg42** [aldostools/webMAN-MOD#420]
When a ROM is loaded in webMAN-MOD over NET, the ROM is mounted as followed:
/dev_bdvd/MAME/xxxxxx.zip

That is the path written in the launch.txt file for the PKG/ROM launcher as well.

The emulator selection based on path found in _Projects_/wm_url_launcher/main.c expects the path to be like ROMS/MAME, causing the PKG/ROM Launcher to select the SNES emulator based on the zip extension.

If I manually change the launch.txt file to "/dev_bdvd/ROMS/MAME/xxxxxx.zip"  and mount the ROMS folder manually using a parent folder the PKG/ROM launcher works as expected selecting the emulator correctly.

I've tried to fix the issue in include/mount_cobra.h by saving the launch.txt correctly and trying to mount /ROMS content in "/***DVD***/ROMS/%s" with no success. Any hints?

Thanks a lot

**Comment by aldostools** [comment]
Currently I don't have access to my PS3 to verify this PKG. You could check if it fixes the issue:
[UP0001-PKGLAUNCH_00-0000000000000000.zip](https://github.com/aldostools/webMAN-MOD/files/5359599/UP0001-PKGLAUNCH_00-0000000000000000.zip)

(extract the PKG in the zip)

**Comment by rjsg42** [comment]
Yeah! It works perfectly! Much appreciated.

**Comment by aldostools** [comment]
Thank you for your feedback.

Updated the PKG in the release page & brewology.
