### ISSUE TITLE
Error playing GAMEI after playing ROM

### ISSUE THREAD

**Issue by LouisGarry** [aldostools/webMAN-MOD#429]
Master Aldo, after playing the game rom, playing a game from GAMEI will get an error because when loading a game from GAMEI it is not automatically unmounted.

Sorry off topic.
I have tried ps2 enc games as recommended (/dev_hdd0/PS2ISO/SLUS-20909.BIN.ENC), but the auto config doesn't work. Already installed ps2config.pkg, check auto config in wMM setup. Will master Aldo check it out?

If I copy the configuration file manually (/dev_hdd0/PS2ISO/SLUS-20909.BIN.ENC.CONFIG) it works.

Thank you.

**Comment by aldostools** [comment]
Thank you for your feedback. Both issues have been addressed in this build. Please test and report back.
[webMAN_MOD_1.47.31_Installer.zip](https://github.com/aldostools/webMAN-MOD/files/5432860/webMAN_MOD_1.47.31_Installer.zip)

**Comment by LouisGarry** [comment]
It's fixed master, thank you very much.  GBU
