### ISSUE TITLE
System freeze on FTP transfers

### ISSUE THREAD

**Issue by bdandy** [aldostools/webMAN-MOD#43]
webMAN 1.45.10 MOD 

There is a problem in FTP server, if I upload few files simultaneously - system completely freezes and even long pressing power button will not power off.

I've tried Irisman - it can successfully handle 10 simultaneously transfers without freezes.

[WORKAROUND]
Set maximum 1 file upload in ftp client settings

**Comment by ghost** [comment]
Yea same thing happens to me when i try to transfer files on my ps3 system

**Comment by aldostools** [comment]
IRISMAN is a standalone application that has all the memory available for its processes.
webMAN is a background service that uses limited resources to avoid conflicts with the application running in foreground.

10 simultaneous threads is too much for the system, considering that each thread uses 192KB or 320KB (64KB for the stack and 128KB or 256KB depending on the selected profile for the plugin memory usage). If you go to cpursx.ps3 on XMB, you will notice that the free memory available is near 2MB or less..

Try limiting the simultaneous transfers to 2 or 3.
