### ISSUE TITLE
can no longer load game folder, only iso and other images work (ps3netsrv) 

### ISSUE THREAD

**Issue by gigabyte-1000** [aldostools/webMAN-MOD#431]
using the latest webman mod 1.47.31 / rebug / ps3netsrv - I can no longer load folder images, its been years since I used my ps3 so Im a bit rusty, I just remember being able to load folders instead of images...
 
ps3netsrv says , building virtual iso... ., I can see files under /dev_bdvd but its not showing a game icon on xmb I tried building ps3netsrv and same result...

anyideas would be great.

**Comment by aldostools** [comment]
Try an older version of ps3netsrv
https://github.com/aldostools/webMAN-MOD/releases/download/1.47.25/ps3netsrv_20190924.zip
or
https://github.com/aldostools/webMAN-MOD/releases/download/1.47.23/ps3netsrv_20170310.zip

If you're using linux, use the docker version
https://hub.docker.com/r/shawly/ps3netsrv/dockerfile

or compile the project replacing the VisoFile.cpp & VisoFile.h with the .ok files
https://github.com/aldostools/webMAN-MOD/releases/download/1.47.31/ps3netsrv_20200708.zip

Please report back your results.

**Comment by gigabyte-1000** [comment]
I tried the older version and also compiling with using the .ok files but same result.

I am thinking maybe it has something to do with the latest rebug (I am using REBUG_4.86.1_LITE), I forget maybe I need to use the non lite version ?, before upgrading webman and ps3netsrv I used the old ones I had pre-installed (from years ago), and it still didnt work, the only update I did was rebug.

**Comment by aldostools** [comment]
The lite edition doesn't support ps3netsrv.

Also you need to configure the ps3netsrv server ip address in /setup.ps3

**Comment by gigabyte-1000** [comment]
yeah I have ip configured properly, it finds all my iso's I can see them in the webpage, mounting/loading isos work fine.

It's just when trying to mount folders is where it fails (ie I in the webpage I click http://192.168.1.x/mount.ps3/net0/Games/BLJM6132X ) where BLJM6132X is a folder of a extracted game image, I liked using this since it was a quick way to test mods, without having to remake a ISO.

I will try to downgrade rebug to the last rex/dex build later tonight and see what happens, I just saw this page and it seems fakeiso support is only supported by the FULL rebug version like you were saying.
https://www.psx-place.com/threads/webman-mod-web-commands.1508/

Edit:
So I tried to downgrade to REBUG_4.84.2_REX , and it unfortunately still didn't work, no idea why the game icon doesn't show, it appears to read the game since one of them pops up a notification saying minimum firmware 4.80 required (though game icon doesn't show), it says data cd under video and other category, webman mod is running in full mode (used L1 button when installing), not sure what else to try....

perhaps it has something to do with the filesystem on linux (xfs), I guess I will try moving some stuff over to windows and see it it helps.

**Comment by gigabyte-1000** [comment]
ok after trying everything I can think of I have no clue what the problem is, but when I mount the unpacked game folder (viso), it shows up in XMB as a DATA DVD, on FTP the game files are listed under /dev_bdvd/PS3_GAME (it's just not being detected as a PS3 Game I guess?) is this a viso problem or a ps3 cfw issue, I tried several windows 10, ps3netsrv cmd and the gui and they all have the same result, I also tried a bunch of linux ps3netsrv including a very old (20170310) one which I'm pretty sure used to work.

PS2ISO - work fine - copy's files to system
PS3ISO - work fine
Games / NET0 folder loading
mounting the unpacked game appears to work, but it's not being detected as a PS3 game on the ps3.
![Capture](https://user-images.githubusercontent.com/7568213/97641262-bb05b380-19ff-11eb-9996-d7fc1644a3c4.JPG)
![Capture2](https://user-images.githubusercontent.com/7568213/97641377-f7d1aa80-19ff-11eb-8d8b-63dc19514191.JPG)

The games are stored on a linux hard drive formatted using the XFS filesystem, but I also tried to put them on a windows hard drive that uses NTFS so I don't think the filesystem is a issue? , I might try a fat32 drive tonight just to make sure.

This PS3 is a CECHG model, everything still works (bluray drive, usbports, harddrive ...etc), the only thing I can think of is maybe something got toggled /changed in the CFW debug menu on the XMB but I'm not sure.

**Comment by aldostools** [comment]
I suggest you that try a different game (if possible extract a non modified game). 
Also try deleting the game update (the game may appear as corrupted if the update files in hdd0 are damaged).

Also check the files/folders read privileges on your linux hard drive.

**Comment by gigabyte-1000** [comment]
OK I made some progress, using windows ps3netsrv_20200708 with a samba share mapped drive to the Linux files (x:\ps3\) it shows the game in xmb and webinterface (so I think it works)
![Capturxxxe](https://user-images.githubusercontent.com/7568213/97662538-9d067600-1a34-11eb-839a-c90c136326de.JPG)

However using the Linux ps3netsrv (compiled from same 20200708 zip), it doesn't list games in web interface like the windows version, it appears to ignore the Games folder?, I can access and see the Games folder if I click on Files -NET0/Games/<game> but mounting them from here doesn't work either it attempts to mount but comes back as data DVD (like I was doing in above posts)
 
![xxxxxxxxxx](https://user-images.githubusercontent.com/7568213/97662530-97109500-1a34-11eb-961d-bc307a1ce5ab.JPG)

Edit: I also tried the docker Linux ps3netsrv and same problem, it seems only windows build can read unpacked games and create working viso...

I guess I will use the windows version for now with a drive mapped to linux samba share, hopefully eventually the linux server will get fixed, ofc I am happy to test anything

**Comment by aldostools** [comment]
Try compiling this version in your linux. It's the latest code refactored by @kam821 (except for VisoFile module that is from an older version)
[ps3netsrv_20201030.zip](https://github.com/aldostools/webMAN-MOD/files/5465222/ps3netsrv_20201030.zip)

**Comment by gigabyte-1000** [comment]
Thanks, I tried it but same issue, after refreshing xml / html it shows all the games except the ones in the games folder, and manually selecting the game from the net0/games path results in the data cd issue again..

```
 ps3netsrv_20201030# ./Make.sh
 g++ -Wall -Wno-format -I./include -std=c++0x -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DPOLARSSL -Doff64_t=off_t -static -O3 -DNDEBUG   -c -o src/main.o src/main.cpp
 cc -Wall -Wno-format -I./include -std=gnu99 -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DPOLARSSL -Doff64_t=off_t -static -O3 -DNDEBUG   -c -o src/padlock.o src/padlock.c
 cc -Wall -Wno-format -I./include -std=gnu99 -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DPOLARSSL -Doff64_t=off_t -static -O3 -DNDEBUG   -c -o src/aes.o src/aes.c
 cc -Wall -Wno-format -I./include -std=gnu99 -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DPOLARSSL -Doff64_t=off_t -static -O3 -DNDEBUG   -c -o src/compat.o src/compat.c
 g++ -Wall -Wno-format -I./include -std=c++0x -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DPOLARSSL -Doff64_t=off_t -static -O3 -DNDEBUG   -c -o src/Console.o src/Console.cpp
 g++ -Wall -Wno-format -I./include -std=c++0x -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DPOLARSSL -Doff64_t=off_t -static -O3 -DNDEBUG   -c -o src/File.o src/File.cpp
 g++ -Wall -Wno-format -I./include -std=c++0x -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DPOLARSSL -Doff64_t=off_t -static -O3 -DNDEBUG   -c -o src/VIsoFile.o src/VIsoFile.cpp
 src/VIsoFile.cpp: In member function ‘virtual ssize_t VIsoFile::read(void*, size_t)’:
 src/VIsoFile.cpp:1480:15: warning: comparison of integer expressions of different signedness: ‘off_t’ {aka ‘long int’} and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
  1480 |  if (vFilePtr < fsBufSize)
       |      ~~~~~~~~~^~~~~~~~~~~
 In function ‘size_t strncpy_upper(char*, const char*, size_t)’,
     inlined from ‘uint8_t* VIsoFile::buildPathTable(bool, bool, size_t*)’ at src/VIsoFile.cpp:629:34:
 src/VIsoFile.cpp:56:9: warning: ‘char* strncpy(char*, const char*, size_t)’ writing 254 bytes into a region of size 1 overflows the destination [-Wstringop-overflow=]
    56 |  strncpy(s1, s2, n);
       |  ~~~~~~~^~~~~~~~~~~
 In function ‘size_t strncpy_upper(char*, const char*, size_t)’,
     inlined from ‘void VIsoFile::write(const char*, const char*)’ at src/VIsoFile.cpp:1231:38:
 src/VIsoFile.cpp:56:9: warning: ‘char* strncpy(char*, const char*, size_t)’ specified bound 32 equals destination size [-Wstringop-truncation]
    56 |  strncpy(s1, s2, n);
       |  ~~~~~~~^~~~~~~~~~~
 cc -Wall -Wno-format -I./include -std=gnu99 -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DPOLARSSL -Doff64_t=off_t -static -O3 -DNDEBUG  -L.  -L. -o ps3netsrv src/main.o src/padlock.o src/aes.o src/compat.o src/Console.o src/File.o srcd
 rm -f src/*.o 2>/dev/null
 
 ps3netsrv_20201030# ./ps3netsrv /PS3
 ps3netsrv build 20201030 (mod by aldostools)
 Path: /PS3
 
 Host IP #1: 10.0.0.x:38008
 Host IP #2: 192.168.1.x:38008
 Waiting for client...
 [0] Connection from 10.0.0.xx
 open dir /PS3ISO
 open dir /PS2ISO
 open dir /PSXISO
 open dir /PSPISO
 open dir /PS2ISO
 open dir /PSXISO
 open dir /PSPISO
 ^from xml scan
 open dir
 open dir /Games <manually browsing through NET0 path
 open dir /Games/BLJM61325
 building virtual iso...
 open /Games/BLJM61325
 
```

**Comment by aldostools** [comment]
The name of the folder GAMES must be all upper case. It's "GAMES", not "Games".

**Comment by gigabyte-1000** [comment]
ahhhh ok that was the problem! it's working now, I never would of guessed since Windows was fine with Games , and awhile back I moved the folder over from Windows to the Linux drive, it never even occurred to me to rename it, feels like such a stupid mistake now since I know Linux is case sensitive about everything..

Anyways it seems to be working great now!, finds and mounts game ok, game icon shows on xmb

Thanks again for the help and keeping the ps3 going 👍 .
