### ISSUE TITLE
PS2 Emulator fan config setting issue (HEN 3.02 wMM 1.47.33 non CFW compatible PS3)

### ISSUE THREAD

**Issue by Don-Keballs** [aldostools/webMAN-MOD#433]
Hi Aldo, 

Firstly I would like to thank you and your fellow contributors for the effort that is put into webMAN and your various projects.
Im truly impressed by what has been achieved with this project.

**The issue**

PS2 Classic games not running with increased fan speed as selected in settings.

Upon launching a ISO.BIN.ENC (from dev_hdd0/PS2ISO) with webman games via the PS2 Classics placeholder.pkg the fan initially spools to the selected speed (45%) but once loaded (after 2-5 seconds or so) it returns to its original setting (35%)
Proceeding to launch the game via the PS2 Classics placeholder does not increase the fan speed either.

I have tried this on three separate consoles, all non CFW compatible. 2x CECH-4xxx 1x CECH-300x
I am running the latest webman mod version 1.47.31 and HEN 3.0.1

Fan settings - Manual 35% - PS2 Emulator 45%
I have also tried auto 1 and 2 fan settings with no joy

Not sure if i'm doing something wrong, but I have tried searching google to try and resolve this issue and had no luck finding a solution.

Many thanks, 

Don

**Comment by aldostools** [comment]
Try using dynamic fan control instead of manual fan settings.

**Comment by Don-Keballs** [comment]
Thanks for the quick reply. Just tried what you suggested. Applied dynamic fan control (auto @65) same thing happened, fan spooled up to 45% then gradually stepped back down to 25%

Restarted console twice and still the same unfortunately.
