### ISSUE TITLE
can't rename file in FTP

### ISSUE THREAD

**Issue by Mr-Beacon00** [aldostools/webMAN-MOD#436]
CECH-3012A
HEN 3.0.1
webMAN MOD 1.47.31

can't rename file in FTP
it says "File unavailable"
in command
RNFR /dev_hdd0/PS3ISO/1.ISO
350 RNFR OK

RNTO is not working
RNTO /dev_hdd0/PS3ISO/2.ISO
550 File unavailable

but without path is working
RNTO 2.ISO
250 OK

webMAN MOD 1.47.30 is working fine

my English is bad sorry

**Comment by aldostools** [comment]
Please try downloading the latest installer of 1.47.31 again (the binary have been updated with a fix)

**Comment by Mr-Beacon00** [comment]
ok. is working now.
