### ISSUE TITLE
PS2 games freezing if webman is installed cecha

### ISSUE THREAD

**Issue by DennisDelitsso** [aldostools/webMAN-MOD#437]
Hello, 

Having CECHA00 console, latest rebug 4.86.1 lite and webman 1.47.31 installed.
When playing PS2 games, they will randomly freeze (while audio would still play),  you're free to quit the game via PSN button as usual, so it's not hard lock.
Seems like deleting webman did the trick, and games would no longer freeze.

Please confirm, I can send any log if there's any, but I'm really new to github and homebrew gaming.
Thanks!

**Comment by DennisDelitsso** [comment]
After further testing, It looks like this issue is happening due to something else.

**Comment by DennisDelitsso** [comment]
Actually, can you look into this? I think deleting webman fully eliminates the problem (I know I said it earlier but after further testing it seems to be true somewhat)

Maybe if log will be provided there would be a way to confirm it?

Just to explain it: I have plenty of original ps2 games, gta vc example. When it's used without webman installed - no problems cobra mode picks up and I can launch the game flawlessly via xmb and play it. But if I'll try to play it same but when webman installed - it will freeze randomly at gameplay for no apparent reason.
Same with tekken tag tournament iso - it works fine via multiman without webman installed, but if its launched when webman installed (or through webman menu) it will freeze

**Comment by aldostools** [comment]
webMAN has an option to use ps2_netemu on B/C models like CECHA. verify if you have that option checked in /setup.ps3 (if so, uncheck that option, save the settings and reboot).

I don't think the issue is related to the fan controller, but also you could test setting the fan mode to SYSCON (i.e. disable fan controller)

Also try pressing SELECT+O to ensure  that any mounted game is unmounted before launch a physical PS2 disc.

**Comment by DennisDelitsso** [comment]
Just to follow up on an issue:

I uninstalled everything again, formatted HDD, went back to 3.55 ofw via Rogero downgrader, then installed rebug latest, tried the ps2 disc - works without any freezing. 

Before that if I tried to mount the iso via multiman or webman - the game would freeze, then I could close it, put ps2 disc again, launch through XMB - and the ps2 disc will freeze as well.
What's funny is that when I reboot the console and start operation from fresh, launch the ps2 disc again via xmb - it will work fine, and then I can successfully mount iso on multiman (or webman) without any issue. So the working order - play the PS2 game via disc first, then I can play them successfully via mounting ISO.
Seems like there's conflict in the configuration on a software level with the emulator at multiman/webman.

I'll try your advice a bit later and install webman fresh (since I reformatted the system from the last try), I'll let you know the result.


Also, can you send me an image, where to find ps2_netemu option? I could only find it under "scan new content", it had auto config checked.

**Comment by DennisDelitsso** [comment]
So I installed the latest Webman unto fresh latest rebug CFW, played with auto-config a little bit (disabling it would introduce the graphical glitches so I left it enabled), and played with SYSCON and my personal FAN profile (which is 40 - 80% fan speed all the time, depending on the temperature, starting from 64C on CPU) and it looks like SYSCON let the PS2 game running stable with zero issues, meanwhile my aggressive cooling makes them freeze.

Update:
Yep, looks like SYSCON is definitely a way to make the PS2 operation stable, I'm not sure how hot PS3 is while it's running on SYSCON mode but PS2 operation is smooth as can be, meanwhile changing the fan speed to custom would instantly make PS2 games freeze.
I wonder how you can finetune it, knowing that PS2 chp doesn't like being all that cool : )

I left the setting on default, which is 25 minimal fan speed, and 68C is cpu target temp, before I was using 40 minimal fan, this probably made ps2 operation unstable, as the temperatures were too low, or PSU couldn't keep up with the energy that system draws.
What's interesting is that PS2 emulator fan is set to 40, but when I'm playing a game i can't hear it, I don't think fan is at 40 at all, it's very silent, as if it was running on 20 speed at best (update: I tried the iso and the 40 fan speed works only for iso, not for the ps2 discs)
Thank you for the suggestion 👍  I can play the games with web man too now, awesome

Keeping PS2 emulator fan at 30 seems to be somewhat stable (not for all games, for all games 25 is the most stable setting that I found), when I put it on default 40 it will freeze regardless of game
Do you think it could be indeed related to PSU failing?
The issue can be closed now.

**Comment by DennisDelitsso** [comment]
What's weird is that I can run PS3 games on 40% fan speed with zero problems, but PS2 games will instantly freeze with same fan speed

**Comment by DennisDelitsso** [comment]
Yeah, this is due to the temperature issue. Ps2 games will freeze if temperature of the cpu is below 61 for some reason. Don't know why but it just does that. Going to see what I can do but I don't think I can do much 🤠

Thanks for your assistance.
