### ISSUE TITLE
Same issue certain games black screen 

### ISSUE THREAD

**Issue by james1233777** [aldostools/webMAN-MOD#439]
I just tried putting assassins creed into iso form updated it then loaded it and it was a black screen, and this was tried on a cfw ps3

**Comment by aldostools** [comment]
Assassins Creed games normally get a black screen, They require the empty folder USRDIR/ASSASSIN_ISO

Some games like Call of Duty also tend to get a black screen. These games are fixed converting them to ISO or enabling the BD-Mirror option in the backup managers.

**Comment by james1233777** [comment]
Can u explain that more the assassins_iso usrdir folder being empty

**Comment by aldostools** [comment]
check if there is a folder called ASSASSIN_ISO in USRDIR of the game if isn't then you must create it manually

**Comment by james1233777** [comment]
Ok let me do that and see if it works sorry im abit slow so go into ps3iso and make a folder called ASSASSINS_ISO

**Comment by aldostools** [comment]
Read again what i wrote... I didn't mention ps3iso

**Comment by james1233777** [comment]
Oh my bad sorry I see u said the usrdir folder of the assassins creed game but I'm confused so in the game update or in Games sorry for being abit slow
