### ISSUE TITLE
Problem loading PSX isos/bin with NTFS Disc.

### ISSUE THREAD

**Issue by LordSaga** [aldostools/webMAN-MOD#440]
Hi I have a problem loading/searching PSX games.

I have an external 500GB disk with FAT32 format, I lend it to a friend during the week because I needed to make some backups and this one by mistake eliminates all its content :(.

As it had to begin to install everything again, this time I decided to format it in "NTFS", to pass the things that had much but fast and not to have to lose time doing it by FTP since it is very annoying.

I pass the games of PS3 and there is no problem, when I scan with webman finds them and I can load them.

The problem I have is with the **PSX/PS1** games, when I copy them and put to scan from webman, at first it says scanning, but it never warns me that I can restart the XMB (there are not many to delay).

After waiting a while, I restart the XMB menu anyway and the PS1 games still do not appear, another curious fact that when this happens I can not make another scan, when I give the option to search games does not do anything, and if I want to play a PS3 game, makes as if it loads it, but the game does not appear in the xmb menu. In order that it returns to work I must restart the console.

I have tried to solve it either formatting several times the disk with different clusters and I obtain the same result.

**-** I have the psx games in BIN/CUE format, both with the same name (I even check the .cue with notepad to see if it has the correct name).
**-** Both PS3/PSX games are in their respective folders (PSXISO and PS3ISO).
**-** I have the latest version of Webman MOD.

I hope there is a solution, I would be sorry to go back to FAT32 and have to pass everything through FTP.

Thank you.

**PS:** Sorry, if you don't understand much, I had to use a translator.

**Comment by aldostools** [comment]
Please try this:
1- Check the option "Disable content scan on startup" found in /setup.ps3
2- Uncheck the option /dev_ntfs found in the section "Scan for content" of /setup.ps3 
(You first need to expand the section to see the option)
3- Make sure that you have checked all the content types that you need (PS3, PS1, PS2, etc).
4- Save the settings.

Download prepISO, install the PKG, attach the USB (NTFS) to the PS3, then launch prepISO.
(You will see a black screen for a few seconds, then it will return to XMB)
Your PSX games should appear listed in "webMAN Games" menu.

If they don't appear listed check that your NTFS partition is marked as MBR.
If the drive is 2TB or larger you may need to resize the cluster to 4KB, 8KB or larger size.
More info: https://www.psx-place.com/threads/ntfs-external-drive-setup.22259/

**Comment by LordSaga** [comment]
Thank you! Now if you find the PSX games and the menu appears and they work!

I just have some doubts.

**-** Now I always have to start the PrepISO or only when I add new content?

**-** You don't need to search for games from webman anymore?

Thanks again for your help! :D

**Comment by aldostools** [comment]
You only run prepISO when you add new content or when you need to re-scan the content..

**Comment by LordSaga** [comment]
Perfect, thank you very much for your help!
