### ISSUE TITLE
Webman soft-locking console after exiting applications via XMB.

### ISSUE THREAD

**Issue by codeonthesun** [aldostools/webMAN-MOD#441]
Essentially after exiting a mounted game via XMB,  webman soft-locks my PS3 by constantly displaying "Webman Games" notification and opening the default webman page in browser. It does this non-stop, spamming the notification and forcing the browser webpage to open. Restarting my PS3 seems to be the only way to fix this / avoid it happening at all. I was able to isolate the problem to Webman, I've tried reinstalling with not much success. It's only happens occasionally when exiting PS3 games, however launching ROMs via Webman games XMB always seems to cause the problem (I have tried different mounters and backup managers and if webman IS installed it still happens . I would appreciate any help as I quite enjoy using webman and it' features thank you!

PS3: Slim, CFW: Rebug 4.86.1

**Comment by aldostools** [comment]
Please try using a different DualShock3, It seems that some buttons are getting stuck.

**Comment by codeonthesun** [comment]
That actually makes sense! I use primarily a DS4 controller as my DS3 is half broken, but the home button doesn't work on the DS4 so I have to plug in the junk DS3 to close games. I will avoid doing this from now on. Thank you.
