### ISSUE TITLE
Ftp "data" folder

### ISSUE THREAD

**Issue by Odrowaz** [aldostools/webMAN-MOD#442]
hi, i can't literally create or copy a folder named "data" with the ftp it give a "550 File unavailable" error

**Comment by aldostools** [comment]
Thank you for your feedback. Indeed the latest commit didn't fix the rename completely.

I have uploaded a new PKG that should fix this issue.
https://github.com/aldostools/webMAN-MOD/releases

**Comment by Odrowaz** [comment]
ok, it's working properly now
