### ISSUE TITLE
I tired the assassin_iso it did not work 

### ISSUE THREAD

**Issue by james1233777** [aldostools/webMAN-MOD#444]
Hey I put the ASSASSIN_ISO in the usrdir folder of my game update and it now gives me a error

**Comment by Masamune3210** [comment]
"gives me a error" isn't very descriptive..

**Comment by james1233777** [comment]
Allright ill explain i make a folder called ASSASSIN_ISO for my ASSASSINS creed 2 into the games update folder then it give me a error now it does not anymore my games in iso format it loads the game makes a noice like a message popped up but its just a black screen

**Comment by james1233777** [comment]
Yea the error is this operation is not allowed  
Iso type:32
Iso path(1): [/dev_hdd0/ps3iso/assassins creed2.iso
Iso path (0): [/dev_hdd0/ps3iso/assassins creed2.iso
Iso segs:1 
Error: encrypted/invalid iso any help

**Comment by james1233777** [comment]
That's the error I get in mmcm

**Comment by Masamune3210** [comment]
1. Extract ISO
2. Create ASSASSIN_ISO folder in PS3_GAME
3. Recreate ISO

**Comment by james1233777** [comment]
Ok do I just make that folder in Game or put it inside the assassins creed game

**Comment by Masamune3210** [comment]
I give up

**Comment by james1233777** [comment]
Lol sorry I get it now but when I extracted the iso it already had the assass_iso folder into it and I'm still getting a black screen
