### ISSUE TITLE
PS3 crashes when I try to refresh game list

### ISSUE THREAD

**Issue by sapfel93** [aldostools/webMAN-MOD#448]
When I try to refresh my game list, when the notification says "Refresh XML", the PS3 crashes. I tried rebuilding the database and fixing the file system, but nothing works.

**Comment by aldostools** [comment]
Disconnect all usb devices.
Delete /dev_hdd0/tmp/wm_config.bin
Reboot. The next time webMAN MOD is loaded, it will scan the content in hdd0.

If the console still freeze, the issue is a game in your hdd0. If it works, the issue is an external game. 

It is recommended to disable the content scanning at startup in /setup.ps3 after reboot.

The next step is to find out what game causes the bug by removing all the games again and adding the games in small groups.

**Comment by sapfel93** [comment]
Are you sure? It was working perfectly fine with the games in my HDD until I updated to the latest version. Then after I updated it wouldn't update my game list (was using the same games I've always been using) and so I reinstalled it and now it crashes when I try to do it. I'm sorry if it seems like I'm refusing to follow your directions, but it's like 600GB of PS3 games and I would rather not spend a hundred hours transferring them.

**Comment by aldostools** [comment]
Renaming the folders would be equivalent to remove them

**Comment by sapfel93** [comment]
They're in ISO format so would I move them to another folder?

**Comment by aldostools** [comment]
I mean rename the folders PS3ISO, GAMES, PS2ISO, PSXISO, PSPISO, etc. to xPS3ISO, xGAMES, xPS2ISO, xPSXISO, xPSPISO, etc.

**Comment by sapfel93** [comment]
Okay. I found out it was something in the PSXISO folder. Going to try to find out what the bad iso is.

**Comment by sapfel93** [comment]
Okay. Something weird is happening. When I have more than one bin/cue in the PSXISO folder, it crashes when I refresh. When I have one, it loads fine.

**Comment by aldostools** [comment]
Check the file name of the games. You csn put tbem in subfolders if you want.

Also create increase the memory allocation if you have many games. I suggest to select [MC]-4bg to allocate 3MB

**Comment by sapfel93** [comment]
I increased MC but for some reason it bugs out on PSXISO. When I put more than 1 bin/cue on it, it crashes (when I put 1 in it reloads fine), but for some reason it doesn't affect PS3ISO.

EDIT: Hold on. I'm putting everything in folders and shortening their names.

**Comment by sapfel93** [comment]
Okay I got it working, but what I had to do was put each disc in its own folder. (If it had multiple discs, I had to put each of them in their own folder). That got the games loading, but I wonder why I had to take that extra step.
