### ISSUE TITLE
Issue on "Unmount Disc" on 1.46.00

### ISSUE THREAD

**Issue by jonaaa20** [aldostools/webMAN-MOD#45]
Nice update, but there's a problem, when you select the "Unmount Disc" button, it just stays on a "blank" screen, i can't press any button, but the PS3 isn't froze, just like he's trying to do something else but there isn't anything to do... you should check it.

EDIT:

I made a video: https://sendvid.com/fp26surm

Yeah i know, my camera sucks, my phone sucks too xD

**Comment by RandQalan** [comment]
Same here as well unmount stuck an Background have to turn off to get out

**Comment by aldostools** [comment]
The issue has been fixed in this commit:
https://github.com/aldostools/webMAN-MOD/commit/98ec58079a62c0d753cf1cfaf4624f19e26162aa

Please re-download the latest PKG.
