### ISSUE TITLE
PS1 multi-track CD ISO won't play any music

### ISSUE THREAD

**Issue by AnthonyRyuki** [aldostools/webMAN-MOD#452]
I tried playing a Ridge Racer 1 ISO thru webMAN, after merging all .bin files into one (track 1 contains the game data, the other tracks are Audio CD data). However, it looks like only track 1 is taken into consideration by webMAN, so no music will play at all. Is there any way to get that working? Thanks in advance.

**Comment by aldostools** [comment]
The merged ISO also needs the CUESheet file (CUE). It provides the information about the audio tracks of the image.

The recommended format for PS1 is CUE/BIN or CUE/ISO.

**Comment by AnthonyRyuki** [comment]
OK, that fixed it. Thanks.
