### ISSUE TITLE
PS3_NET_Server GUI Doesn't Launch on Windows 10

### ISSUE THREAD

**Issue by tbhova** [aldostools/webMAN-MOD#46]
On 2 clean Windows 10 installs with MSvbvm50.exe installed, the GUI will not launch (command line tools still work).
There are no error messages, the window simply never appears.

**Comment by aldostools** [comment]
On some systems you have to turn off DEP (Data Execution Prevention) or add the application to the exception list.

http://www.thewindowsclub.com/turn-off-data-execution-prevention-dep
http://www.online-tech-tips.com/windows-xp/disable-turn-off-dep-windows/

Also it is required to have registered (with regsvr32.exe) the ActiveX component MSCOMCTL.OCX
https://www.microsoft.com/en-us/download/details.aspx?id=10019

**Comment by tbhova** [comment]
Thanks so much @aldostools! Adding the MSCOMCTL.OCX did the trick! Changing DEP wasn't necessary.

However, the VB 6.0 Common Controls download from Microsoft didn't appear to do anything, I just grabbed a MSCOMCTL.OCX from the internet and put it in C:\Windows\SysWOW64\.

Thank you so much and keep up the good work!!!
