### ISSUE TITLE
ps3netsrv not showing any folders on ps3

### ISSUE THREAD

**Issue by NextDev65** [aldostools/webMAN-MOD#463]
I've tried this a few times but no folders show up in either webMAN-MOD (full) files tab or multiMAN OS file manager.
On mmOS I select the folder, it loads, then show an empty dir.
On webman i select the folder, it loads infinitely or says Error.
I think I'm using the correct ip but I could be wrong. 
On the latest rebug rex, allowed ps3netsrv.exe through firewall, but still no luck.
Help is appreciated and I can give more info if needed.
Thanks.

**Comment by aldostools** [comment]
On the PC:
1-Make sure that ps3netsrv is running with the port 38008 open (or the firewall disabled)

2-The folders are case sensitive (GAMES, PS3ISO, PSXISO, PSPISO, BDISO, DVDISO, etc.)

On the PS3:
3-Go to http://127.0.0.1/setup.ps3 expand the section "Scan for Content"

3a) Check the first entry for ps3netsrv and enter the IP address of the PC running the ps3netsrv.

3b) Save the settings.

4-Go to http://127.0.0.1/ and browse the folder /net0 

5-If you see the remote files/folders, refresh the XML or run prepISO.

**Comment by NextDev65** [comment]
Thanks for the quick response; the problem persists.
To be clear, I have previously tried a different port that I used to host files to other devices in my local network but encountered the same problem. I also created the firewall rules to open port 38008 with no avail. My folders are GAMES, PS3ISO, and PSXISO. Again trying to open net0 causes the ps3 to load for a while then "This page cannot be displayed" (80710723). Using my PC and browsing to my ps3 ip then files>net0 gives an error on the webman gui. On multiMAN the dir is empty.

**Comment by aldostools** [comment]
Check that you're using the full edition. The lite edition doesn't support remote connection

**Comment by NextDev65** [comment]
I mean webman shows (NTFS) (full) after boot in the notif buble in upper right, ~~but is there a solid way of checking?~~
nvm, just realized I can take screenshots so that means I'm on full

**Comment by aldostools** [comment]
Yes, you're running the full version.

From the PC: Try accessing http://ip-address-of-your-ps3/net0

If you cannot see the folders, then something is blocking the communication between the PC and the PS3 in the port 38008

**Comment by NextDev65** [comment]
Well I guess something is blocking the connection
![Screenshot 2021-01-08 151352](https://user-images.githubusercontent.com/12612637/104064898-5bc4dc00-51c4-11eb-838c-99d1872e9c8a.png)

**Comment by aldostools** [comment]
Please show your ps3netsrv configuration in /setup.ps3

**Comment by NextDev65** [comment]
![setup ps3](https://user-images.githubusercontent.com/12612637/104065687-c9253c80-51c5-11eb-9c70-6c1a16544390.png)

**Comment by aldostools** [comment]
Your settings are correct.

There must be something in your router or PC that is blocking the port 38008.

Try changing the port to a different port. Maybe 8080 (normally used for proxy)

**Comment by aldostools** [comment]
Also try copying ps3netsrv.exe to your shared folder, and run it directly instead of the GUI
![image](https://user-images.githubusercontent.com/974897/104067781-2dea9200-51da-11eb-9a60-a2a59d9b0cfb.png)

![image](https://user-images.githubusercontent.com/974897/104067803-36db6380-51da-11eb-823d-d0ef0876bf36.png)

This is my setting:
![image](https://user-images.githubusercontent.com/974897/104068020-933e8300-51da-11eb-9a94-720ed7fad2c5.png)

**Comment by NextDev65** [comment]
port 8080 doesnt work; trying the exe method now

**Comment by NextDev65** [comment]
no luck, trying random ports :|
it just says waiting for client btw

**Comment by NextDev65** [comment]
YAY success Thanks aldo
ok so port 38008 with the exe method works great
yea tried the gui again and it didnt work

**Comment by NextDev65** [comment]
Where can I find more info on ini files for each folder?

**Comment by aldostools** [comment]
The INI is a text file named with the same name of the folder + .INI

I contains a list of the full paths that should be added to the content of the folder.
The paths can be a local path (including driver letter) or UNC (local or remote path) 
The paths can be physical folders or symbolic links.
Each path must be listed in a line.
You can have 1 or more path per file.
The linked folder can have any name (e.g. PS3ISO can be linked to X:\ISO or \\\MyPC\SharedGames)

![image](https://user-images.githubusercontent.com/974897/104072286-532ece80-51e1-11eb-895b-0cbd4e77e5ab.png)
