### ISSUE TITLE
Max fan speed immediately after quitting game. Started appearing after updating to 1.47.32 from 1.47.31

### ISSUE THREAD

**Issue by Adamanimus** [aldostools/webMAN-MOD#464]
I was using 1.47.31 and updated to 1.47.32.
The issue goes like this:

- I have set dynamic fan settings at 68C and Min fan speed at 30% and Max at 80%
- When I am playing in game the fan works as intended. Meaning it is running at consistent speed not ramping up and down. 
- My PS3 Slim 3K doesn't heat that much. It has clean inside and Arctic Cooler MX-4. Temperature is around 65C most of the time.
- When playing games and I check temperature ingame, I noticed it showing 70C RSX temperature and Fan speed is at 80%.
- If I keep playing, fan speed doesn't seem to change and when I touch back vent, it is not hot, just lukewarm.

As soon as I leave the game, Fan speed ramps up to max 80% speed and gradually slows down to normal 30% over the duration of a minute.

I have attached a couple of photos.
https://ibb.co/g6vp0xM
https://ibb.co/WghjBZD

**Comment by Dee-san** [comment]
Try applying the manual fan setting (like 30%).
Con: constant fan volume
Pro: no side effects like homebrew crashing

**Comment by Lewissek** [comment]
I noticed it too. It seems that during the game WebMAN is only showing fan speed which should be used at this moment, but it is not really affecting the real fan speed. Immediately after game is closed the real fan speed is increasing to this values which is shown by WebMAN and then in XMB auto fan speed is working fine.

**Comment by aldostools** [comment]
The release 1.47.33 has been updated 0ad6f7409fbae854c9cc6f93d5feaa6e12a04a43 to fix this issue.


Please download and install AGAIN the package or update via XMB
https://github.com/aldostools/webMAN-MOD/releases

**Comment by Adamanimus** [comment]
Thank you, aldostools. I have update webman mod. I will close this issue.
