### ISSUE TITLE
Is possible run PS2ISO with SMB?

### ISSUE THREAD

**Issue by keeno1982** [aldostools/webMAN-MOD#465]
As we know, PS2ISO only run on internal HDD. If possible, a plugin can mount SMB folder as internal HDD folder and let it read from remote disk?

**Comment by aldostools** [comment]
No. When the PS2 emulator is loaded, the LV2 kernel and VSH are replaced with the emulator.
So anything mapped in LV2 memory is unloaded from memory when the PS2 emulator starts.

**Comment by keeno1982** [comment]
OK, got it.
