### ISSUE TITLE
[Questions] Would it be possible to run the ps3netsvr on RouterOS or OpenWRT?

### ISSUE THREAD

**Issue by Lion4K** [aldostools/webMAN-MOD#470]
I was thinking this because I used to use the smb feature of RouterOS with an USB HDD and stream games straight to OPL on PS2 over the network cable.
So I was thinking something similar to this.
But I know SBM alone wouldn't cut it, or would it?

**Comment by aldostools** [comment]
In the binaries folder there is an old version for OpenWRT. Maybe you can compile it.
https://github.com/aldostools/webMAN-MOD/tree/master/_Projects_/ps3netsrv/bins/OpenWRT

**Comment by Lion4K** [comment]
Ok, about the RouterOS, do you think I can compile as well? I'd like to try it first and if all fails flash OpenWRT on another router I have.
With usb support.
The router I used is a mikrotik.

**Comment by aldostools** [comment]
I haven't tested it on RouterOS. The binary for OpenWRT was compiled by another developer using the source code in this repository.

Maybe you should check the docker version maintained by shawly
https://hub.docker.com/r/shawly/ps3netsrv/dockerfile

**Comment by Lion4K** [comment]
Thanks, I'll see what I can do.
