### ISSUE TITLE
web man Doesn't show any folders 

### ISSUE THREAD

**Issue by NansessOnHBO** [aldostools/webMAN-MOD#471]
if any more than 1 game is located in the folder it doesn't show any folders in web man or web man settings. I reinstalled CFW and Webman more than the once same issue I have to load my games by using package manager plus since it has the web man settings folder and links to the games in the browser. Rebug 4.84 this issue occurred after I refreshed my game's HTML through web man settings so my recently installed game would show.

**Comment by NansessOnHBO** [comment]
![IMG_20210123_185710](https://user-images.githubusercontent.com/77904343/105617564-e30d7480-5dac-11eb-9e87-2e47fb17da11.jpg)
sorry for bad quality i had to use my laptop camrea

**Comment by aldostools** [comment]
Try this:
1- Delete /dev_hdd0/tmp/wm_config.bin
2- Disconnect all the USB devices
3- Install latest prepISO
4- Install latest webMAN MOD.
5- After Reboot, wait until the scan is completed. webMAN Games should show at least various subfolders.
6- Open /setup.ps3 disable scan at startup, save and close the browser.
7- Connect the USB devices and run prepISO.

NOTE: The PS3 ISO images should be copied in /PS3ISO (all uppercase).
The PS3 games in folder format should be stored in /GAMES

**Comment by NansessOnHBO** [comment]
It dint work folder is still empty it’s only empty if their GAMES inside the GAMEZ AND GAMES Folder

https://user-images.githubusercontent.com/77904343/105618060-49949180-5db1-11eb-8efb-8105a5d8693e.MOV

**Comment by aldostools** [comment]
Did you follow each step (specially delete the config file and remove the USB drives before reinstall)?
If you have many games in /dev_hdd0, the scanning may take several minutes.

**Comment by NansessOnHBO** [comment]
how do i know when the scan is complete?

**Comment by aldostools** [comment]
It shows a notification saying "Refresh XML: OK".

**Comment by NansessOnHBO** [comment]
it dint work the only things that works is having 1 game only inside the games folder anthing us none of webman folders show

**Comment by NansessOnHBO** [comment]
https://user-images.githubusercontent.com/77904343/105618294-99745800-5db3-11eb-9fc1-9723916266dd.MOV
It only works correctly with one game in the games folder

**Comment by aldostools** [comment]
You are not providing enough information about your configuration. It is impossible to help if you don't tell:
1- Where the games are stored (internal, fat32, ntfs, exfat, ext, sd, ps3netsrv),. Only one or multiple sources.
2- Type of games (PS3ISO, PSXISO, PS3 JB folders, ROMS).. Only one or multiple types.
3- The name of the folders. Some non-unicode characters may break the XML.
4- The amount of games. There are different memory profiles depending the content to be scanned.
5- Your current settings in /setup.ps3
6- The method used to scan (prepISO, XMB menu, VSH menu, auto-refresh on startup, combo SELECT+L3)

**Comment by NansessOnHBO** [comment]
PS3 GAMES only this only happens one more then 1 PS3 GAME is in the GAMES FOLDER their are 13 games I want in the folder but if their more then 1 game In The Games folder webman whole xmb doesn’t load. I tried VSH scan and prepISO.

**Comment by aldostools** [comment]
You're answering only part of the questions.

Try sMAN or an older version of the plugin. You can ask in PSX-PLACE forums too,

**Comment by NansessOnHBO** [comment]
It was cause by some files in MY GTA 5 Game It can be caused by Parma.sfo editing and re-editing a fresh copy fixed it just so everyone knows.
