### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by SerdarSaglam** [aldostools/webMAN-MOD#476]
Hello, where do we translate language files from?

Translations need to be edited quite old, but I could not find the file.

**Comment by aldostools** [comment]
The files are found in /dev_hdd0/tmp/wm_lang

These files are replaced on every update. If you have some changes I suggest that post the file here and I will include it in the distribution package, so you don't get the files replaced every time you update.

**Comment by SerdarSaglam** [comment]
Thanks
I started translating
