### ISSUE TITLE
Auto-play not working

### ISSUE THREAD

**Issue by fapapucs** [aldostools/webMAN-MOD#48]
I am using the latest version webMAN MOD 1.46.01 but the auto-play feature is not working in this release.
In the previous version it functioned well.

Thanks,

**Comment by fapapucs** [comment]
Sorry, It was my mistake. Really I can see it is working for me in version 1.46.01.
Pease close this issue.

Thanks,

**Comment by Joonie86** [comment]
Closing old cases that have no further feedback. please use the latest version of wMM and report us
