### ISSUE TITLE
1.47.33 setting on ps3 doesn't works

### ISSUE THREAD

**Issue by N2022062** [aldostools/webMAN-MOD#483]
it said "cant show web (80710101)"

**Comment by aldostools** [comment]
80710101 = CELL_HTTP_ERROR_NET_RESOLVER_HOST_NOT_FOUND:

DNS Error; No DNS server available. / IP conflict, PS3 Cannot connect to the router with current IP information. Try rebooting your router. Use static IP address on PS3.

**Comment by N2022062** [comment]
ok fix it.
I add a proxy to ps3.and I didn't play a long time.
I forgot it.
del the proxy, setting works!
