### ISSUE TITLE
(null) instead of temperature info in-game with SELECT+START+R2

### ISSUE THREAD

**Issue by Adamanimus** [aldostools/webMAN-MOD#485]
I updated to latest release 1.47.34.
It stopped showing temperature info while in-game with shortcut press.
Just pressing Select+start shows temperature without issue. 
I attached a picture of said issue.
![20210204_121305](https://user-images.githubusercontent.com/71977245/106844191-d78e4780-66e2-11eb-889f-ea8e4625563b.jpg)

**Comment by aldostools** [comment]
Thank you for your feedback. The regression was fixed.

**Comment by Adamanimus** [comment]
Thanks, aldostools. Do i close it now or when update with fix is released?

**Comment by aldostools** [comment]
The binaries are already updated in the release page and in the online update option. Closing the issue.
