### ISSUE TITLE
umount combo problem

### ISSUE THREAD

**Issue by fapapucs** [aldostools/webMAN-MOD#49]
I am using the latest version webMAN MOD 1.46.01, but the umount combo (select+o) can not be controlled by the connected (UMOUNT) checkbox.
Very strange, because as I see instead of the "UMOUNT", the "SET MAX TEMP" checkbox has effect for this feature.

Thanks,

**Comment by Joonie86** [comment]
Closing old cases that have no further feedback. please use the latest version of wMM and report us
