### ISSUE TITLE
CHD files

### ISSUE THREAD

**Issue by kashkash18** [aldostools/webMAN-MOD#491]
Is it possible to add support for CHD game images?

**Comment by aldostools** [comment]
I don't know how works exactly the format CHD. I suppose It uses some compression by sector or block of sectors.

The decompressed ISO should be handled by Cobra payload. As the payload size is very limited and it is almost reaching it, the decompression would require to be handled by a proxy plugin, like rawseciso or netiso.

In summary, it is a feasible feature but requires a lot of development that I cannot assume.
