### ISSUE TITLE
Web interface shows Megabytes instead of Gigabytes (MB when it should be GB) on storage devices

### ISSUE THREAD

**Issue by DMNerd** [aldostools/webMAN-MOD#492]
![Screenshot 2021-02-23 at 0 55 27](https://user-images.githubusercontent.com/7889445/108785532-e6de1380-7571-11eb-8c63-fa6f25cb82ee.png)

**Comment by Masamune3210** [comment]
Technecially, its correct, unless you have a 361 TB drive. I'm assuming you mean you want a option to change the number so that it says 361GB instead of counting past 1,000 MB?

Edit - Ignore the fact that my autocorrect apparently thinks that data size categories is a religion

**Comment by aldostools** [comment]
> Technecially, its correct, unless you have a 361 TB drive. I'm assuming you mean you want a option to change the number so that it says 361GB instead of counting past 1,000 MB?
> 
> Edit - Ignore the fact that my autocorrect apparently thinks that data size categories is a religion

361,296 MB is the free space of the disk of 480GB. That is 352.8GiB (361,296 MB / 1024) not 361TB.

BTW I use MB for [mebibytes ](https://en.wikipedia.org/wiki/Mebibyte). The correct label is MiB but nobody use it.

The latest commit now shows the sizes in GB. Use the built-in updater or download the updated installer from "releases"

**Comment by Masamune3210** [comment]
Ignore me, sorry, don't attempt to help with issues when half awake lol

**Comment by DMNerd** [comment]
@aldostools Yes, I see it now but in my head the "," in the interface became decimal, thus it was not apparent imidately to me. Ignore me, or just may you could just use space instead of "," character. Just a suggestion

Anyway thank you for Webman.

**Comment by aldostools** [comment]
Period "." is used as decimal separator.
![image](https://user-images.githubusercontent.com/974897/108879669-deb8bf00-75d7-11eb-8654-443aabe1a8ef.png)
