### ISSUE TITLE
Install issue hen 4.85 for 1.47.34

### ISSUE THREAD

**Issue by tonebiclas** [aldostools/webMAN-MOD#494]
Hello aldo
I have hfw 4.85,  i updated hen to 3.0.2 few days ago when i booted for first time in long time.
Everything worked fine.
Today i installed WebMAN Mod latest version currently, for that i uninstalled the version
1.47.26 via xmb in webman setup and installed the newest via package manager.
When it install it show on notification "4xx noncobra" and in webserver at bottom too
now if i install again (like overwriting) 2nd time it show 4.85 CEX HEN 3.0.2 and works as expected its weird... if i remove it and install again the noncobra thing happens.
I dont have folders for ps1 iso and bd/dvd in "my games", only ps3 and ps2

I reinstalled hfw 4.85.1 and it happened again!

Also noticed Chart button in new tempc.html is going to link cpursx.html, the file cpursx.html is not found in tmp folder. Is it supossed to be /cpursx.ps3 instead?

**Comment by tonebiclas** [comment]
Got it working deleting everything in hdd0 related to wm, folders, config file, etc
this helped https://www.psx-place.com/threads/how-to-uninstall-webman-mod.28521/

**Comment by aldostools** [comment]
webMAN MOD must be installed with HEN enabled. Otherwise it will not be able to detect the FW type.

The /cpursx.html is an HTML file created when the "CPU/RSX/FAN Chart" is marked in /setup.ps3
It shows a chart with the temperature measured every few seconds since the start of the plugin.
