### ISSUE TITLE
NTFS not read after update

### ISSUE THREAD

**Issue by The-Exterminator** [aldostools/webMAN-MOD#497]
My NTFS folder does not load after updating, but IrisMan can :-(
Jeg har prøvet at slette tmp osv
I have tried running "prepISO_1.28.pkg" but without success

**Comment by aldostools** [comment]
If your NTFS only have PSXISO, PS3ISO and/or BDISO/DVDISO you can scan the content without have to use prepISO.

prepISO is mainly needed to scan PSPISO, PS2ISO, PKG, MOVIES and exFAT devices.

When using prepISO make use that /dev_ntfs is unchecked in /setup.ps3 settings. That option allows to scan the NTFS using the built-in prepNTFS. If it's  enabled it could conflict with the external prepISO.

**Comment by dm2912** [comment]
I am having the same issue all of a sudden. Everything was fine but tonight but then I ripped a couple more discs and now webman has decided to flat out ignore any iso's on my external drive. 

Tried using PrepISO as webman alone was not finding things. That has resulted in it finding a total of 5 games (from 96) and populating their data to /dev_hdd0/tmp/wmtmp


> When using prepISO make use that /dev_ntfs is unchecked in /setup.ps3 settings.

What do you mean by this? In Webman setup? In a file? What is the exact description of the option?

**Comment by aldostools** [comment]
Go to http://0/setup.ps3 click on "**Scan for content**" to expand the section.
There should be an option "/dev_ntfs" on the left side, after /dev_usb000, /dev_usb001, etc.

When the option is marked, webMAN MOD will scan the NTFS devices attached to the PS3 using the internal prepNTFS.
prepNTFS only scans PS3ISO, PSXISO, BDISO and DVDISO. Therefore is more limited than prepISO, but has the advantage that don't require to run prepISO. However, if prepISO is used with that option checked, there could be conflicts.

**Comment by dm2912** [comment]
Ok, will do that.

At the moment running PrepISO on its own is scanning everything (the first time round took 6 scans to get the entire HD content scanned - 80 games, 1tb). 

If I run the update gamelist option from inside Webman its removing every single ISO  on the ntfs drive from the list and only showing internal (folder) games.

**Comment by dm2912** [comment]
ok, this is interesting. 

Things appear to be backwards.

I UNCHECKED the /dev_ntfs button in settings so that webman no longer scans ntfs and that is left to PrepISO

Then I did a refresh gamelist in Webman to test it was doing things properly

There is now TWO instances of every single ISO game on the NTFS drive :')

So with it unchecked it seems to have in fact scanned the NTFS drive, when with it checked it wasnt :S

**Comment by aldostools** [comment]
It looks like you understood it backwards:
- If the option /dev_ntfs is checked, wMM scans the NTFS devices using the internal functions. Therefore there is no need to run the external application prepISO.
- If the option /dev_ntfs is unchecked, prepISO must be used to scan the NTFS devices.

If you clean the folder /dev_hdd0/tmp/wmtmp then run prepISO (with /dev_ntfs unchecked), it should work as expected.

**Comment by dm2912** [comment]
> It looks you understood it backwards:
> 
> * If the option /dev_ntfs is checked, wMM scans the NTFS devices using the internal functions. Therefore there is no need to run the external application prepISO.
> * If the option /dev_ntfs is unchecked, prepISO must be used to scan the NTFS devices.
> 
> If you clean the folder /dev_hdd0/tmp/wmtmp then run prepISO (with /dev_ntfs unchecked), it should work as expected.

Yes, it was doing the opposite for me.

/dev_ntfs was checked. But, when i did a gamelist refresh with Webman it was not detecting any of the games on the NTFS drive. So i used PrepISO 

I just **unchecked** /dev_ntfs, rebooted, and then did a refresh games with Webman, and suddenly everything was now there twice. 

I have now, cleared the /wmptmp folder, done a few reboot cycles to get an empty gamelist

With /dev_ntfs **checked** it is not finding any of the iso's on the external ntfs

but its fine, just using PrepISO now, I dont know why everything suddenly doubled up despite the box being unchecked :')

Thanks for the pointer to the setting though. I couldnt find it as was auto collapsed. :D
