### ISSUE TITLE
[Full offline mode] Disable internet access when playing games and allow only private network connections

### ISSUE THREAD

**Issue by 444nonymous** [aldostools/webMAN-MOD#5]
If you have a banned ps3 or you don't want to log in to the PSN network while using a CFW, you are prompted time after time during a game to log in. This happens every time you load a game, when you change menus, etc.

One option is to disconnect the cable or disable WIFI. Another is to select the ps3 offline mode in the XBM settings. The problem is that you also loose the local network connection, you can't stream movies using the media player or games using webman, or access to the FTP, etc.

The best solution would be to create a full internet offline mode only when playing games, but allowing private network connections. The IP range is: ( https://en.wikipedia.org/wiki/Private_network )
10.0.0.0 - 10.255.255.255
172.16.0.0 - 172.31.255.255
192.168.0.0 - 192.168.255.255

Please also keep allowing dns resolution as usual. IE if you have a local domain "home" and you name your devices, you will have "ps3.home" pointing to 192.168.0.10; "pc.home" to 192.168.0.11, "router.home" to 192.168.0.1, etc.

Thanks!

**Comment by aldostools** [comment]
This is not an issue of webMAN... Almost all games require PSN and they try to force the player to login.

If you have technical information about how to implement what you suggest, please provide it.

For the moment, your options are: disable the network access through XMB, or filter the IPs in your router, or use the offline option found in /setup.ps3 of webMAN to block the PSN servers. However, I don't guarantee that with the offline option the games will stop prompting to login to PSN.
