### ISSUE TITLE
webMAN MOD 1.46.01 another bug 

### ISSUE THREAD

**Issue by RandQalan** [aldostools/webMAN-MOD#50]
can not switch game ISO with xmb select and L1 R1 

Hope this fixed soon had to role back to version webMAN MOD 1.46.01 2 of this because dynasty Warriors XL and DW 8 will not allow import with most recent of this version
checked the first that allowed auto play works hope you find out why L1 select to change ISO work with first revision and later versions do not work
works 48fda68
broken 599d1d6

**Comment by aldostools** [comment]
Please test with the latest commit of 1.47.00
https://github.com/aldostools/webMAN-MOD/blob/master/_Projects_/updater/pkgfiles/USRDIR/webftp_server_full.sprx

There was a bug caused by the stack size was too small in 2 threads and that crashed the plugin.

**Comment by RandQalan** [comment]
was this not inside of pkg on your test version

http://www.psx-place.com/threads/update-webman-mod-1-46-00-games-mounted-from-xmb-without-webbrowser_plugin-using-idle_plugin.12542/page-6#post-72478

or was their another bug as well
