### ISSUE TITLE
ROMS won't loading

### ISSUE THREAD

**Issue by heloisatech** [aldostools/webMAN-MOD#502]
PKG/Rom Launcher giving me Black Screen after loading Roms.
When I disable autoplay in config, it returns to XMB.
 
Rebug 4.84.2
RetroArch 1.9.0
webMAN-MOD 1.47.35

**Comment by aldostools** [comment]
Please try updating using the built-in updater (recommended), then reboot after installation.

Or try installing this build of the pkg:
https://github.com/aldostools/webMAN-MOD/releases/download/1.47.35/ROMS_PKG_Launcher.pkg

**Comment by heloisatech** [comment]
I tried both options and it doesn't work

**Comment by aldostools** [comment]
Try installing an older version... it's working fine here. I'm on Rebug 4.86.1

**Comment by heloisatech** [comment]
Doesn't work. I have tested in older versios 34, 32, 31...

**Comment by sin89rus** [comment]
confirm the issue, older ver. - first one for 4.87 - same

**Comment by heloisatech** [comment]
Doesn't work. REBUG 4.84.2 / 4.86.1 LITE / FERROX COBRA 4.87
Versions 1.47.28 to 1.47.35

**Comment by deadpahn** [comment]
I'm having the same issue. Trying to run some nes games from the menu. When I boot into Retroarch and manually start the games it works. I tried different folder naming conventions (NESTOPIA, NES, FCEUMM). What appears to be happening is some error with the command itself. I wonder if a new version of retro arch changed parameters or something. I tried using games with one word titles thinking perhaps it was a white space issue. 

Question: Is there a log output I can check somewhere that would help me figure out this issue? It could help me debug it better for the devs.

ALSO, semi related, my art files won't show up in the PS3 menu. I thought perhaps they were too big so I shrunk them down to 20k jpgs but the PS3 menu still seems to beach ball them.

I'll start poking around to see if I can find the log output to find out why the .nes files won't launch.


UPDATE: I think my theory was right. After poking around the code I saw this:

`			if(not_exists(path))
			{
				char *retroArch = strstr(path,  "/game/SSNE10000");
				if(retroArch) memcpy(retroArch, "/game/RETROARCH", 15);
				if(not_exists(path))
				{
					char *retroArch = strstr(path,  "/game/RETROARCH");
					if(retroArch) memcpy(retroArch, "/game/SSNE10001", 15);
				}
			}`

When I check the PS3, I do see that /game/PKGLAUNCH/USRDIR/launch.txt exists, and it has the CORRECT path to the game. However, when I check the /dev_hdd0/game there is no RETROARCH folder. It seems like at this point retroarch is hiding somewhere else on /dev_hdd0/

This is just a quick guess, I'm not sure if this is really the problem or not.

**Comment by aldostools** [comment]
It's working fine on my system. Try this:
1. Download & install RetroArch Community Edition from
https://github.com/crystalct/RetroArch_PSX_CE/releases/download/v0.3-beta/RetroArch_Psx-Place_Community_Edition_beta03-20210104.pkg

2. Update to the latest build downloading & installing again this package
https://github.com/aldostools/webMAN-MOD/releases/download/1.47.36/webMAN_MOD_1.47.36_Installer.pkg

Or use the online update in Game > webMAN Games > webMAN Setup > Update webMAN MOD

3. Reboot after the installation

4. Configure your ROMS like this:
![image](https://user-images.githubusercontent.com/974897/128643506-3e621b26-5f27-43b2-83b6-de8af5aab9f5.png)

The folders ROMS and NES should be all caps. It doesn't detect /Roms or /roms or /Nes or /nes
The PNG images in the folder are optional.

5. Scan your games and launch the ROM from webMAN Games menu.

6. Launch the game from the disc icon or from ★ app_home/PS3_GAME or ★ PlayStation (if you use Evilnat 4.88.2)

**Comment by heloisatech** [comment]
Tks, It worked. @aldostools 

But in the version 1.47.36 after the notification webman message, user login disappeared. 

![IMG_20210820_193540640](https://user-images.githubusercontent.com/6962212/130300081-e716ff73-9ebe-42ea-9cb9-00fcf55c492b.jpg)

**Comment by aldostools** [comment]
Use the PC or tablet/phone to connect through FTP and delete /dev_hdd0/tmp/npsignin_plugin.rco

It looks like you have one of the initial versions that included the stripped version of that file. 
It is used for DeViL303's method to block the "Sign In to PSN" screen.

**Comment by heloisatech** [comment]
@aldostools don't have this file

**Comment by aldostools** [comment]
Enter to Recovery Menu to remove /dev_hdd0/boot_plugins.txt
Then just exit to return to XMB. The console should boot without webMAN.

If the problem persists, then there is some system file corrupted and it is recommended to reinstall your CFW from Recovery Menu.

If the issue is solved, you can try updating webMAN to the latest build from breowlogy:
https://store.brewology.com/ahomebrew.php?brewid=310
or from https://github.com/aldostools/webMAN-MOD/releases

**Comment by heloisatech** [comment]
@aldostools  Didn't work. But in version 1.47.34 it's ok

**Comment by heloisatech** [comment]
@aldostools Thank you so much for the support. 😊

Just one more thing. Retroarch has this error when running roms. 

![IMG_20210821_124724875.jpg](https://user-images.githubusercontent.com/6962212/130328395-2575914b-58cb-4f9a-b3a2-b544c4d2b1da.jpg)

**Comment by aldostools** [comment]
You can press L3+R3 to access the RetroArch menu, then use the Online Updater.

If the ROMs are working, you can ignore that message.

**Comment by heloisatech** [comment]
@aldostools  The default directory path is **dev_bdvd/PS3_GAME/USRDIR**

for that reason the error. I changed the Path and it's worked the online updater

**Comment by sin89rus** [comment]
Yep. Comunity edition RetroARCH - all ok. Regular edition was the issue. After install RetroArch make sure you reinstall webman mod, cause i had a black screen (maybe it was just a one-time bug, dont know).
