### ISSUE TITLE
Very slow loading from ISO game

### ISSUE THREAD

**Issue by megapro17** [aldostools/webMAN-MOD#503]
I have such a problem, it takes a very long time to load iso games from the internal hard drive. Files are copied without errors, md5 matched. HDD smart is okay. ps3 superslim, webman 1.47.35, ps3hen 3.0.2. 
I checked it on several games, after pressing a new game, it takes about 10 minutes to load. 
Both games are for Cobra ODE / E3 ODE PRO ISO IRD 100%
I tried a checking fs and rebuilding database
The same iso from usb-hdd is even slower
Games from blu-ray disk are working properly

**Comment by gosseux** [comment]
Make an ISO of a game you currently own to check if you have an issue with webman or not.
