### ISSUE TITLE
Wrong units in free space bars of File Browser

### ISSUE THREAD

**Issue by J0hnTR** [aldostools/webMAN-MOD#507]
Greetings!

Just a quick note - there are wrong units in free space bars of File Browser.

There are Mb where Gb should really be, at least in Russian language:
![Rus](https://user-images.githubusercontent.com/1292549/113589771-762f1a00-963a-11eb-9228-bd3c30bd17af.png)
Also popup message is a mess of Russian and English units (see "Gb", but "Мб", strange).

As for Russian language, according to the English: "Gb" is "Гб", "Mb" is "Мб", "Kb" is "Кб", "b" is "б".
Russian lang file is OK - there are "Гб", not "Мб", in it (checked).

If English translation is set - everything is fine:
![Eng](https://user-images.githubusercontent.com/1292549/113589797-7f1feb80-963a-11eb-9965-e9bcfedf51e2.png)

Thinking a little - may it be something about [THIS](https://github.com/aldostools/webMAN-MOD/blob/master/include/file_manager.h#L229)?
`if(devSize >= _1GB_)
					{
						replace_char(fsize, 'M', 'G');
					}`
Buuuuuuut English "M" differs from Russian one, can it be the cause of all troubles?..)

Maybe (just maybe, I'm almost not a programmer!) not the chars should be replaced?
But STR_MEGABYTE with STR_GIGABYTE, of already localized text?

Thank you!

**Comment by aldostools** [comment]
Check if it's fixed in the latest build... update using the built-in updater or download the PKG from the release page

**Comment by J0hnTR** [comment]
> Check if it's fixed in the latest build... update using the built-in updater or download the PKG from the release page

Everything is fine now, thank you!
