### ISSUE TITLE
PS2 fan speed reverts back after a second or so when mounting bin.enc.

### ISSUE THREAD

**Issue by Adamanimus** [aldostools/webMAN-MOD#513]
Hi, aldostools.

I have an issue. I am using HEN on 4.87 and have webman mod 1.47.35.

I have manual fan speed at 30% and PS2 fan speed at 40%. 

When i mount PS2 Bin.enc, fan speeds up and then returns back to 30% after a couple of seconds. 
It used to be just fine. What could be the issue?

**Comment by Adamanimus** [comment]
Webman PS2 Fan Speed Lowering - https://www.reddit.com/r/ps3hacks/comments/l3vxpa/webman_ps2_fan_speed_lowering/

This here describes exact same issue.

**Comment by Don-Keballs** [comment]
I also have this issue and raised it last year.

https://github.com/aldostools/webMAN-MOD/issues/433

**Comment by aldostools** [comment]
A new build has been uploaded to address this issue.

**Comment by Don-Keballs** [comment]
Confirmed working (PS3 SS CECH4XXX HEN 3.0.2 HFW 4.87).

(Note* this only works for BIN.ENC games launched via PS2 Classics. Doesn't work on .pkg type PS2 games).

Thanks Aldo!

**Comment by aldostools** [comment]
Thank you for the confirmation. 

Package games (including PS2 Classics) work directly without assistance of webMAN MOD.
Therefore webMAN MOD doesn't know when these games are launched.
As the fan speed must be set prior to launch the game, it's impossible to handle these games through wMM.

**Comment by Adamanimus** [comment]
Thanks, aldostools.
