### ISSUE TITLE
Manual fan speed percentage notification and temperature monitor fan speed discrepancy.

### ISSUE THREAD

**Issue by Adamanimus** [aldostools/webMAN-MOD#523]
Hi, aldostools.

I have noticed a bug i presume.
I am using manual fan control at 30%.
If I press 'SELECT+UP/DOWN' to increase fan speed by 1% and see the fan increase notification and then check temperature by pressing SELECT+START or SELECT+START+R2 it shows 1% less fan speed than "Fan Setting Changed: FAN SPEED: X%"

For example: my initial speed is at 30%. I increase to 31% and then bring it down to 30% again and then check temperature. It will show 29% for fan speed. After that it will always show 1% less than what manual fan.speed increase and decrease said.

I have attached 2 pics showing the difference.
![20210420_120108](https://user-images.githubusercontent.com/71977245/115336590-173cd980-a1d2-11eb-944e-dd667d89fb8d.jpg)
![20210420_120115](https://user-images.githubusercontent.com/71977245/115336607-1e63e780-a1d2-11eb-8f7e-61eaf3e39403.jpg)

Which number is the correct one?
My ear is used to 30% fan speed. So i am guessing 'Fan setting changed: FAN SPEED 30%" is right one and SELECT+START FAN: 29% is wrong. But i was ingame without ingame save when i noticed this problem. Would be willing to test more if you need tests.

Edit: Fan speed shown in Select+Start is the right one it seems after testing.

**Comment by Adamanimus** [comment]
I did some further testing. 
Here is what I can confirm:

1. After setting manual speed to 35% for example and after restart, pressing SELECT+UP/DOWN immediately makes SELECT+START temperature to be 1% less than Fan setting changed FAN SPEED notification and % shown in Webman Setup. Both will show 1% higher speed than SELECT+START.
2. After setting manual fan speed in webman setup to let's say 35% and after restart. Pressing SELECT+UP will show it changed to 36% but Fan speed noise won't change and stays 35% and will be shown thus in SELECT+START. In webman setup, now it will be 36%. If I change it to 35%, there won't be any fan noise change meaning it stayed 35%. If I just press save without changing 36% typed in, now fan will increase by 1% and prompt me to restart.

**Comment by aldostools** [comment]
Thank you for your feedback. I made a change to always read the current fan speed in SELECT+START.

Please update and report if it's fixed or not.

**Comment by Adamanimus** [comment]
Thanks,  aldostools.
Now it appears correct.
