### ISSUE TITLE
Feature request: external pkg database rebuild and external pkg symlink

### ISSUE THREAD

**Issue by cuesta4** [aldostools/webMAN-MOD#526]
First of all, thank you very much for all of your work @aldostools .

I wanted to suggest the possibility to index externally installed PKGs through a rebuild database, something like this (https://github.com/Zer0xFF/PS4_db_rebuilder), because as it stands rebuilding turns those PKGs inaccessible. 

Also, being able to symlink these PKGs to the internal HDD so that enabling gameDATA isn't necessary to run them.

**Comment by aldostools** [comment]
Sorry but there is not much that I can do about the db rebuilding... if the installed application is removed, it can be restored simply reinstalling a PKG containing the PARAM.SFO and ICON0.PNG. It is not required to install the full package again. Additionally webMAN MOD can start directly the games found in GAMEI without have them indexed in the database.

In regards to the symlink, the PS3 only allows to create symlinks in the internal HDD (or at least I haven't found a way to create them for files or folders on an external HDD).

**Comment by cuesta4** [comment]
To start the games in GAMEI should I use the file manager? Because I tried updating XML/XMB and Webman wouldn't see any games.

**Comment by aldostools** [comment]
ROMS/PKG Launcher must be installed and the icon ★ app_home/PS3_GAME must be present on Game column of XMB.

**Comment by cuesta4** [comment]
Amazing. Thank you very much!
