### ISSUE TITLE
External ISO + external gameDATA causes duplicated games 

### ISSUE THREAD

**Issue by cuesta4** [aldostools/webMAN-MOD#527]
Enabling content search in the GAMEI directory (so that WebmanMOD sees external PKGs) causes any ISO game with external gameDATA to be listed twice.

**Comment by aldostools** [comment]
Thank you for your feedback. Please try updating to the latest build. https://github.com/aldostools/webMAN-MOD/commit/eb417883ee8bf1c195f6300927b40cae3d908356

You can use the online updater or download the update from the release page

**Comment by cuesta4** [comment]
Thanks, that seem to fix it. 

BTW, my mom just saw the WebmanMOD icon and loved it.
