### ISSUE TITLE
WEBMANMOD won't build (Windows 10, PS3 SDK 4.x, MSYS2 as CYGWIN with GCC) 

### ISSUE THREAD

**Issue by ChrisNonyminus** [aldostools/webMAN-MOD#529]
As the title says I have all the requirements but it won't build. I tried running the bat and instead of building the sprxs, it kept scrolling through countless errors in both the repo and the sdk.
Here's an example.
![cmd_IJL2WBBCFK](https://user-images.githubusercontent.com/50080567/117547906-5602ca00-afef-11eb-9905-41b47d055461.png)

**Comment by aldostools** [comment]
What version of gcc are you using? I use gcc 4.6.2. Try compiling this simple code:
```c
// main.c
int main()
{
	return 0;
}

**Comment by ChrisNonyminus** [comment]
Ignore this issue, turns out the errors were because of edits I made, I'm an idiot.
