### ISSUE TITLE
Odd mounting behavior

### ISSUE THREAD

**Issue by ghost** [aldostools/webMAN-MOD#531]
In Webman-MOD 1.47.35 (latest binary, I assume), mounting a disc in XMB after a disc has already been mounted (with Webman) will cause the disc to automatically start (while the first one does not). Occurs even when auto-start is turned off in XMB.

This may be related to the bug: I noticed that mounting a game no longer focuses XMB on the game mounted, like it did in previous releases. This may just be a change to the default behavior of Webman, so for now I assume that it isn't a bug, but may related to the described behavior above.

Tested in Rebug 4.86.1 (Lite)
w/ Webman 1.47.35 (Normal/Regug install)

**Comment by aldostools** [comment]
Thank you for your feedback. It looks like your issue is related to the new feature that allows to autoplay a game when it is mounted keeping X button pressed for a few seconds.

Try to repeat the procedure but pressing X button briefly when mounting a game.

**Comment by ghost** [comment]
Alright, I've done a few more tests and it seems that the time you need to hold the x button for auto-starting gets reduced once you mount the first disc using webman. The first disc I mounted would almost never auto-starts unless I held the x button for at least a second or two. However, the second (and I believe subsequent) discs I mounted would auto-start if pressed the button normally, and would only not auto-start if pressed the x-button in the lightest way possible.

Granted, the results I got are somewhat inconsistent, with the first disc occasionally auto-starting, and with the subsequent discs also occasionally not auto-starting. But, it seems that the behavior I described is the most prevalent one. It may also be a controller issue, so I'll test this when I get my hands on another controller. But, if anyone can replicate the behavior, that would be great.

If in the end this isn't a bug, perhaps there could be an option to disable auto-start in webman setup for the next release. Or maybe and option to increase the time needed to hold the x button for this to occur.

**Comment by Masamune3210** [comment]
It almost sounds like the timer to found how long the button is being held isn't being reset each mount, and is instead being carried over, so it thinks that you pushing the button to mount the second disk is still the first press

**Comment by aldostools** [comment]
It could be a controller issue (button X staying pressed after release). I have a similar issue with L2 staying pressed on one of my controllers.

I made a test build that will **NOT** perfom the temporary auto-play (holding X button) if  the combo "PLAY DISC" is unchecked.

Download: [webftp_server.zip](https://github.com/aldostools/webMAN-MOD/files/6502178/webftp_server.zip)

**Comment by ghost** [comment]
I tested the bug with another controller. Still the same sort of behavior, with the second disc seeming to have a much less forgiving "hold-down x" time window. Maybe it's still the controller's fault, but I've run out of controllers to test on. 

BTW, thanks for the new build Aldo. I haven't had the time/will to try it out yet (might just wait to see how this bug plays out).

**Comment by ghost** [comment]
Sorry for the delay in testing, I forgot about this bug until now. With the latest build of wMM (not the test build) leaving "PLAY DISC" unchecked skips auto-mount of games by holding x, so my issue is fixed. 

I personally always leave most combos unchecked since I rarely use them, but there might be someone out there with the same problem who would like to have L2+START play discs, while holding x not doing so. Or maybe someone wants to hold x to plays discs but disable the L2+START combo for whatever reason. In any case, my issue is fixed, so thinking of these cases might be for fixes to future inconveniences/bugs (up to you, of course). Closing issue now.
