### ISSUE TITLE
1.46.02 freeze problem

### ISSUE THREAD

**Issue by PetrusZ** [aldostools/webMAN-MOD#54]
Select refresh XML at XMB interface and freezing. After entering the multiMAN, don't know whether there is an association.

Combo SELECT+L1 and freezing.

Use combo SELECT+START to see the temperature, but don't know why getting into the slaunch, and freezing at the second time.

**Comment by Haker120** [comment]
I had the same problem, at least in quick menu, I didn't check combo, and reinstalling helped me, only my CECHC catched this issue but reinstalling helped.

**Comment by PetrusZ** [comment]
@Haker120 You mean after entering the multiMAN, then use WebMan function freezing problem?

**Comment by Haker120** [comment]
Well, this is an issue for me too, no matter which version, quick menu freezes when I quit app, no matter which one, only after fresh boot/reboot it works unfortunately.

**Comment by PetrusZ** [comment]
@Haker120 Reinstalling can fix the problem? Incredible. Uninstall the WebMan first, then install webMAN_MOD_Updater.pkg?

**Comment by Haker120** [comment]
Just install 1.47.01, it fixed the most problems.

**Comment by PetrusZ** [comment]
Not freezing any more, just not working……
