### ISSUE TITLE
Power LED alternating between green and yellow

### ISSUE THREAD

**Issue by NefariousTechSupport** [aldostools/webMAN-MOD#544]
So I recently got WMM (just yesterday) on my PS3 slim CECH2003A (rebug d-rex 4.84 + dex kernel) and had no issues until this morning, I turned on the PS3 the power LED flashes green and yellow, then stays green, there is no output to my TV screen at all, however I can still control the ps3 using my controller (I can turn off the system using it) and WMM still accepts commands (done through pad.aldostools.org).

I read this was an issue of WMM scanning for games, so I created a folder called "games" in dev_hdd0, and no change. I then disabled the scanning of games, no change. I read that it's an issue of an option for the plugin memory usage (3 thousand something kb [MC]), and found it was already disabled. Worryingly, after removing the internal HDD, there's still no output, what's expected is an error message saying "Cannot start. The appropriate system storage was not found." Resetting the video output by holding the power button doesn't help either, I've tried both HDMI and component cables.

At this rate I'd delete WMM as a troubleshooting step but doing that would mean that I'd no longer be able to control the system.

If anyone has any idea for how I can temporarily uninstall WMM, find more info on the issue, or just simply fix the issue, please let me know :)

**Comment by aldostools** [comment]
The power LED flashing yellow/green is normal when webMAN is scanning for games.

If webMAN is responding, you can enter to http://ip-address-of-your-ps3/setup.ps3, disable the option for scanning on startup and save.

If you enter to Recovery Menu and exit, boot_plugins.txt is deleted and you can boot without webMAN if it is causing issues.

**Comment by NefariousTechSupport** [comment]
Yeah so it turns out I was wrong, WMM wasn't causing the issue, it was something else, My component output went to my capture card and from there it went to my TV, and the HDMI output just went straight to the TV, neither of these worked, but using component directly to the TV works for some unknown reason, I'll keep looking into it, but WMM isn't the issue, sorry for bothering you
