### ISSUE TITLE
frozen screen in Supersonic Acrobatic Rocket Powered Battle-Cars (NPEB and NPUB versions)

### ISSUE THREAD

**Issue by Onnurb** [aldostools/webMAN-MOD#552]
I'm not sure if I'm doing this right, but I'm here reporting an incompatibility of wMM with the game: Supersonic Acrobatic Rocket Powered Battle-Cars (NPEB and NPUB versions) downloaded from pkgi. With wMM installed, I couldn't start any game, I could only navigate the game to the game selection modes, but when selecting the start of the game, the screen froze.

I uninstalled wMM and the game worked normally, unfortunately =( because I didn't want to do this

is there a way out of this?

**Comment by aldostools** [comment]
Sorry, but I cannot provide support for games that are not obtained legally.

Maybe unload wMM before start your pirate game.
