### ISSUE TITLE
Unable to uninstall/reinstall both the PSP Minis and Remasters Launcher

### ISSUE THREAD

**Issue by lmipsum** [aldostools/webMAN-MOD#553]
Both appears as **Corrupted Data** in the XMB, so I'm unable to uninstall them, giving me the **An error occured during the delete operation (80010026)** message for both.
On the file system they have empty folders (**PSPM66820** and **PSPC66820**), that cannot be renamed or removed. If i manually extract the PKGs and try to copy the content into the folders, I get **550 File unavailable** message through FTP.
When I'm trying to reinstall the PKGs from **internal** or external drives, it always says **The USB device cannot be accessed.**, while I'm able to install/uninstall any other packages on the system from both internal or external drives.
I've tried both repairing the file system and rebuilding the database, but didn't solve the issue.
I have the latest webMAN-MOD with REBUG 4.84.2 REX CFW & 4.85 spoof on CECH-2004B.

**Comment by aldostools** [comment]
In the latest webMAN MOD, the PSP launchers (Minis & Remasters) are locked until the user mounts a PSP ISO.
This is done to prevent that the system hangs with a black screen. If the user tries to start the launchers without a game mounted an error message is displayed.

To fix your issue you can do one of the following steps:
1- Mount a PSP ISO from webMAN Games menu. Then you will be able to delete, reinstall, launch, etc.
2- Or execute http://0/remap.ps3 on the PS3 browser to disable all the current redirected paths and unlock the launchers.

**Comment by lmipsum** [comment]
Mounting a PSP ISO solved the issue, I'm able to uninstall and reinstall both this way! Thank you!

**Comment by NerdyWanKenobi** [comment]
I know this is an old thread but I have the same exact issue with EVILNAT 4.89 on my Fat CECHE01 but mounting PSP isos and going to [http://0/remap.ps3](http://0.0.0.0/remap.ps3) aren't working.  What should I do?

**Comment by aldostools** [comment]
> mounting

/remap.ps3 or /unmap.ps3 (without parameters) are used only for unlock PSP launchers if you don't mount a PSPISO.
Therefore you don't need to use them unless you want to delete or reinstall the launchers without mount a PSP game.

If you mounted a PSPISO with webMAN MOD, the PSP launchers are unlocked automatically and you should be able to launch them without extra steps.

Make sure that you have a PSN account activated or a fake account activated. You can use Apollo Save Tool for that.
