### ISSUE TITLE
How to disable the Automatic Sign-In Block on PSN

### ISSUE THREAD

**Issue by avze** [aldostools/webMAN-MOD#554]
I was wondering if there was a way to disable the Sign-In Block on the latest version of webman?

**Comment by aldostools** [comment]
Yes. Delete /dev_hdd0/tmp/wm_res/npsignin_plugin.rco

The Sign-In to PSN is also blocked in CFW Evilnat 4.88.2
To disable it delete /dev_blind/vsh/resource/npsignin_plugin.lck
