### ISSUE TITLE
SingStar swap not working with mount.ps2

### ISSUE THREAD

**Issue by BanCrash** [aldostools/webMAN-MOD#56]
Hello, I tried to use the swap disc function with WebMan Mod but I can't with mount.ps2.

I mount the game with the computer navigator, and then in the bottom of the page appear the games that I have with [PS2 label. But if I use this links it mounts the game with the command mount.ps2, and the PS3 (after swap the discs) shows a warning that says "this is not a compatible singstar game".

However, if I copy the link and change the . for _ (I mean, using the command mount_ps2 instead of mount.ps2), I do the same thing (swap the discs) and it works without any trouble. So, Is there anyway that I can change the link of the games from using mount.ps2 to mount_ps2, or the only way is to copy the link and change the . for _?

Thanks you.

**Comment by aldostools** [comment]
Thank you for your report... in the next release (1.47.00) mount.ps2 will be swapped.

mount.ps2 will unmount the current disc then mount /dev_ps2disc
mount_ps2 will mount /dev_ps2disc without unmounting the current disc

Currently 1.47.00 is still in test... and I haven't commited this change yet.

**Comment by BanCrash** [comment]
Perfect, thank you so much!!

**Comment by BanCrash** [comment]
Other thing related, I see that the new form of mounting games no longer uses the web browser. With that, there is the chance to do this swap without using a computer? Or it is impossible even with that?

I know that even if its possible maybe never be worked on that, but I want to know if at least there is the possibility of that.

Thanks again!

**Comment by BanCrash** [comment]
A quick review, with the last release it works perfectly with mount.ps2.

Thanks you!!!
