### ISSUE TITLE
Automatically add transparency to covers

### ISSUE THREAD

**Issue by Derp0** [aldostools/webMAN-MOD#560]
I'd like request an option to add transparency to covers automatically. i.e. 320x176  -> 320x320 with transparency.

**Comment by aldostools** [comment]
webMAN MOD has limited memory resources. That kind of feature would require a lot of processing and probably a good amount of code.

I recommend that pre-process your covers using this tool. It already adds the transparency on the sides.
https://www.psx-place.com/threads/pscoverbox-1-0-coverbox-generator-for-webman.3186/

**Comment by Derp0** [comment]
Gotcha.
Does Webman mod have a priority when looking for covers in different places?
If not can you add an option for it so that one may define a specific order in which it loads covers? This way if a cover is found in location one it doesn't look for another cover in the other locations.

**Comment by aldostools** [comment]
webMAN MOD has a specific search order. When the first cover is found it stops searching.
Indeed the internal search algorithm is very complex because it tries many things to get a cover.

In simple terms the search order is:
1- Check if the ISO has an image in the same folder.
2- Check if game ID has an image in multiMAN's cover repository. 
3- Also check in IRISMAN and ManaGunZ cover repositories.
4- If the game is a JB folder, ICON0.PNG is used if the cover is not found.

There are more variations, but that is the simplest way to explain how it works.

**Comment by Derp0** [comment]
Thanks for the explanation.
Is there currently any way to change this order? If possible I'd like ISO image to be the last in that list.
Also should I create a new feature request for this here?

**Comment by aldostools** [comment]
Remove the covers from the ISO folders. Just leave there the ones that you really need.

**Comment by Derp0** [comment]
Well, I need the covers in ISO folders because other softwares use them too. They're not just for Webman mod.

**Comment by aldostools** [comment]
Then use the the same image in both places.

As I mentioned earlier, the algorithm that searches the covers is too complex to implement a change of order.

**Comment by Derp0** [comment]
What do you mean in both places? I only put covers in ISO folders.
I understand.

**Comment by Derp0** [comment]
> webMAN MOD has a specific search order. When the first cover is found it stops searching.
> Indeed the internal search algorithm is very complex because it tries many things to get a cover.
> 
> In simple terms the search order is:
> 1- Check if the ISO has an image in the same folder.
> 2- Check if game ID has an image in multiMAN's cover repository.
> 3- Also check in IRISMAN and ManaGunZ cover repositories.
> 4- If the game is a JB folder, ICON0.PNG is used if the cover is not found.
> 
> There are more variations, but that is the simplest way to explain how it works.

That search order doesn't seem to be correct, at least not on the latest version, because I put the cover intended for Webman mod in game ISO folder and MM's cover folder, but instead the cover in Managunz's cover folder was used regardless.

P.S. I was only able to kinda force Webman mod to show the cover I wanted by transferring it to `hdd0/tmp/game_repo/main/covers`

**Comment by aldostools** [comment]
As I mentioned earlier, the search algorithm is very complex and many places are searched in different ways (by file name, by title id in the file name, in PARAM.SFO, etc).

The order mentioned above was only to give you an idea.

Good if using that path for covers works for you.

Honestly, my recommendation is that delete the covers from all the places, and install these covers:
https://github.com/aldostools/resources/#readme

Or put your custom covers in the same folder of the ISO.
