### ISSUE TITLE
Issue with PSN game detection in webman

### ISSUE THREAD

**Issue by NinFanBoyFTW** [aldostools/webMAN-MOD#562]
Hi I had 1 other issue that I wanted to resolve. When I was able to add PSN games to the webman folder, it also brought in every PSN installed title including homebrew and things that I would never want in webman. Is there a way to blacklist these, or can there be a feature to press the triangle button for an example and give you the option to blacklist a title. Thank you for your time and I hope this issue can be resolved. I saw someone online asking about this exact issue and they never got a resolution

**Comment by aldostools** [comment]
As I mentioned in your issue #561 the Albums let you classify the PSN games in multiple categories (e.g. Backup Managers, Tools, Shooters, Casual, Retro, Demos, etc.)

Also webMAN MOD allows to blacklist the games listed in wm_ignore.txt. You can add the file name or the title id.
