### ISSUE TITLE
Issue with ISO names including the folder name

### ISSUE THREAD

**Issue by Derp0** [aldostools/webMAN-MOD#563]
I use this format inside game ISO folders:

`hdd0/PSXISO/gamename [TITLEID]/gamename [TITLEID].bin`

It was working fine up to version 1.47.35, i.e. only the ISO (or BIN) name was shown in Webman mod menu provided that they were exactly the same, but in the latest version (1.47.36) the folder name is also included in this format:
`[gamename [TITLEID]] gamename [TITLEID]`

Screenshot of the issue:

https://i.imgur.com/VNZKFne.png

I'm not sure whether this is a bug or not, but changing the Info field to ID and saving automatically becomes ID + Version after restarting.

**Comment by aldostools** [comment]
Thank you for your feedback. Both issues should be fixed in the latest build.

Please update to the latest build using the online updater or re-download the installer from the release page

**Comment by Derp0** [comment]
Can confirm it works correctly now. Thank you for the fix.
