### ISSUE TITLE
showing game path on Webman

### ISSUE THREAD

**Issue by NinFanBoyFTW** [aldostools/webMAN-MOD#564]
Hi I wanted to ask a question and see if this was possible or if this would be something to possibly add, but I wanted to know if it is possible to hide the game path information that is shown below any game title on webman. This is honestly just an eyesore for many games, PS1 especially where the game title is in the path and it just looks like a mess. Thanks again.

**Comment by aldostools** [comment]
In http://0/setup.ps3 you can Info to Path + ID + Version + Tags (or any combination). For instance change it to None.

**Comment by NinFanBoyFTW** [comment]
Ok I have seen this in the settings but that is not what I am looking for (or at least it is not doing what I am trying to). for every game I have in webman there is the top line which is the game title. Then there is the bottom line which shows the path of the game. How do I get rid of the second line completely?

**Comment by aldostools** [comment]
I already told you. Select Info: None. Save the settings. Perform a new scan for content. Then reload XMB or restart.
