### ISSUE TITLE
Error XMB

### ISSUE THREAD

**Issue by heloisatech** [aldostools/webMAN-MOD#569]
![IMG_20211018_193316018.jpg](https://user-images.githubusercontent.com/6962212/137815563-69d939ce-6aca-4531-9a8d-cb74dff82df2.jpg)

![IMG_20211018_192926242.jpg](https://user-images.githubusercontent.com/6962212/137815197-a26caf56-82d9-4f3c-beff-732fdb6b570c.jpg)

Webman 1.47.36
Evilnat 4.88

Users disappears after message balloon

v1.47.34  It works

**Comment by aldostools** [comment]
Thank you for your bug report.

I tested the latest build with Evilnat 4.88.2 and that issue doesn't happen on my system (Slim 2001A).

I suggest you that update to the latest build using the XMB updater in webMAN menu.
Also try setting the auto-login to one of your users.

Finally, these using my current settings if the above doesn't help.
![image](https://user-images.githubusercontent.com/974897/137816893-46cf36c1-64cc-430a-96bb-92f4f0136206.png)

**Comment by heloisatech** [comment]
I used 4.88.2 too

Slim 2501A

I did the update and the error continues.
Auto login It works.

Thanks. I'll try use your config and i give feedback

**Comment by heloisatech** [comment]
@aldostools  didn't work. Maybe in an upcoming update? Thanks

**Comment by aldostools** [comment]
If  I cannot reproduce the issue, it is difficult to fix.

Maybe other users could suggest other things to try. It looks something particular to your configuration.
