### ISSUE TITLE
Webman is listing games as demo's

### ISSUE THREAD

**Issue by OldGnashburg** [aldostools/webMAN-MOD#571]
Certain games that I've installed were initially Trial version, but have since become the full games after I launch them. For example Castle Crasher's was listed as Castle Crashers Trial, or Limbo was listed as Limbo Trial, until I launched them once and then on the regular XMB they become Castle Crashers and Limbo, however in the Webman Mod PS3 Folder it the names are still Trials and it gives the artwork for trials? How do I get it to recognize that they are no longer trials and list them properly.

**Comment by aldostools** [comment]
webMAN MOD read the title of these games from /dev_hdd0/game/{GAMEID}/PARAM.SFO
However it doesn't know if the game was unlocked or not. Try re-scanning the games.

If that doesn't help, you can replace the PARAM.SFO of the game with the one found in the "C00" folder .

**Comment by OldGnashburg** [comment]
This works, thank you very much! Copied the games PARAM.SFO from their C00 folders to their main game folders and WebMan no longer displays the game as a "Trial" or "Demo"
