### ISSUE TITLE
How can I hide system apps from Webman Mod

### ISSUE THREAD

**Issue by OldGnashburg** [aldostools/webMAN-MOD#572]
I've notice that some apps like the PlayStation Store, Amazon Prime Video, Netflix, and some homebrews are being listed in the Webman game PS3 Folder, how do I hide them?

**Comment by aldostools** [comment]
Uncheck the option /dev_hdd0/game in /setup.ps3

Or add their TITLE_ID to the ignore list /dev_hdd0/tmp/wm_res/wm_ignore.txt

**Comment by OldGnashburg** [comment]
My big issue was I wasn't aware of a database with all the game ID's. Found this though https://www.psdevwiki.com/ps3/Productcode seems to be accurate.
