### ISSUE TITLE
[Enhancement] Homebrew Webman Games Folder

### ISSUE THREAD

**Issue by OldGnashburg** [aldostools/webMAN-MOD#573]
In my Webman games folder, I have some homebrew mixed in with my PS3 ISO's and games, would it possible in the next release to have a separate folder for homebrew?

**Comment by aldostools** [comment]
The PSN games are listed separately by default. You can use SQUARE on XMB to group these in folder.

To customize the folder name for each game or homebrew press TRIANGLE on the game, go Information, then enter a folder name in Album. Press Start and CIRCLE. Repeat for all your games.

Here is a video tutorial https://www.youtube.com/watch?v=SovS4R-Q_OE

**Comment by OldGnashburg** [comment]
Didn't know this was a thing, thank you!
