### ISSUE TITLE
ROM icons have issues displaying.

### ISSUE THREAD

**Issue by OldGnashburg** [aldostools/webMAN-MOD#574]
So I got ROM's working with this plugin, got every single ROM has a nice fancy cover that I stole straight from Retroarch (the have zips with most covers in their resources. They work nicely (for the most part), however, I've noticed for systems with a lot of ROM's, they can't all display at once, the images themselves are fine, but I've noticed when you scroll down, one or two have a permanent circle as if it's trying to load but it never does, what's weird however is that if you scroll past them so they are no longer on the screen, and then scroll back up, the ones that were stuck "loading" have appeared, but a couple of different ones are now stuck "loading" and again if your scroll away and then come back, it'll be different again. I'm only noticing this issue with systems with more than 20 or so games. Not sure if this a Webman issue or something else.

**Comment by aldostools** [comment]
An animated GIF or video (or at least screenshots) of your issue would describe better your issue.
You don't specify if the issue is in the XMB or when you launch RetroArch.

**Comment by OldGnashburg** [comment]
https://user-images.githubusercontent.com/75548597/139742182-9be43fb5-5f36-4e1a-9c8e-cf706025b31a.mp4

**Comment by aldostools** [comment]
Thank you for the video. I see that some games are showing the covers but others not.

There are 4 possible causes:
1- That the name of the cover doesn't match exactly the name of the rom.
2- That the image is not present or cannot be reached.
3- That you have a very large number of roms and the VSH memory does not allow to cache more images
4- That the images are too large to be loaded by XMB or the dimensions of the image are not multiple of 4 (width/height)

You can open the XML stored in /dev_hdd0/xmlhost/game_plugin to verify the path used by webMAN MOD and to check if the image exists in the path referenced in the XML.

Also check the size of the image and dimensions. If the image is something like 400x400 or larger or 257x256, you need to change the image. Try something like 160x160.

If the problem persists, upload your XMLs in a zip to check your configuration.

**Comment by OldGnashburg** [comment]
Images are named exactly the same as the ROM, I an confirm this. Every ROM has a corresponding image. So 1 & 2 are out.

The interesting thing is in the video that when I initially scroll down, Kirby and the Amazing Mirror and Kingdom Hearts are stuck "loading" but scrolling back up the render but Golden Sun and Final Fantasy I & II are stuck "loading" they were fine before.

What exactly constitutes a large number of ROM's? At most I have 60 ROM's per category. And does the amount of PS1, PS2, PS3, and PSP games affect the available VSH memory? I have 128 PS1, 241 PS2, 163 PS3, and 168 PSP images on the system.

If it is a memory issue, would shrinking the dimensions and lowering the quality of the images with a tool like GIMP free up memory?

**Comment by aldostools** [comment]
There is not a specific number to define "large" because it depends of the size of the images used.
Above 600 games is a quite large collection, considering that all the icons are cached in memory by XMB.

Try resizing the icons to 160x160 or 80x80 or smaller and check if that fixes your issue.

Also take in count that the other icons in XMB (like stores, PSN games, etc.) are also cached in memory.

**Comment by PS3-Pro** [comment]
> Images are named exactly the same as the ROM, I an confirm this. Every ROM has a corresponding image. So 1 & 2 are out.
> 
> The interesting thing is in the video that when I initially scroll down, Kirby and the Amazing Mirror and Kingdom Hearts are stuck "loading" but scrolling back up the render but Golden Sun and Final Fantasy I & II are stuck "loading" they were fine before.
> 
> What exactly constitutes a large number of ROM's? At most I have 60 ROM's per category. And does the amount of PS1, PS2, PS3, and PSP games affect the available VSH memory? I have 128 PS1, 241 PS2, 163 PS3, and 168 PSP images on the system.
> 
> If it is a memory issue, would shrinking the dimensions and lowering the quality of the images with a tool like GIMP free up memory?



> Images are named exactly the same as the ROM, I an confirm this. Every ROM has a corresponding image. So 1 & 2 are out.
> 
> The interesting thing is in the video that when I initially scroll down, Kirby and the Amazing Mirror and Kingdom Hearts are stuck "loading" but scrolling back up the render but Golden Sun and Final Fantasy I & II are stuck "loading" they were fine before.
> 
> What exactly constitutes a large number of ROM's? At most I have 60 ROM's per category. And does the amount of PS1, PS2, PS3, and PSP games affect the available VSH memory? I have 128 PS1, 241 PS2, 163 PS3, and 168 PSP images on the system.
> 
> If it is a memory issue, would shrinking the dimensions and lowering the quality of the images with a tool like GIMP free up memory?

You can try

1- Rename the other folders e.g PS3ISO to PS3ISOX, PS2ISO to PS2ISOX and scan again to really see if the problem is the vsh memory
2- If no, Try to open those images on photoshop and save them again ( it fixed some icons of mine)

The way the webMAN xml is made when you open the my games foldee it caches a lot of items on vsh memory even if you don't open the folders.

So if you have a lot of PS3,PS2,PS1,PSP games they will be already using vsh memory, roms are made different and only got cached when you open each folder

**Comment by OldGnashburg** [comment]
Used a tool to shrink the file size of every image in bulk. Everything is displaying properly now. Thank you for your help. Closing the issue.
