### ISSUE TITLE
DVDISOs from ps3netsrv are not scanned

### ISSUE THREAD

**Issue by vinhtq115** [aldostools/webMAN-MOD#577]
I run a ps3netsrv on an external machine with some BDISOs and DVDISOs. However, only BDISOs are shown, not DVDISOs. I can manually mount them from the file browser without any issues and they also run fine too.

**Comment by aldostools** [comment]
It looks like you have many BDISOs and they are filling the BD & DVD category before the DVDISO is scanned.

You can try changing the plugin memory usage to "Max BLU+ ( 368K PS3 + 768K BLU)" in /setup.ps3
Save the settings and scan the content again.

If the problem persists, try reducing the number of items in the folder BDISO to check if the DVDISOs are listed.

**Comment by vinhtq115** [comment]
> 
> 
> It looks like you have many BDISOs and they are filling the BD & DVD category before the DVDISO is scanned.
> 
> You can try changing the plugin memory usage to "Max BLU+ ( 368K PS3 + 768K BLU)" in /setup.ps3 Save the settings and scan the content again.
> 
> If the problem persists, try reducing the number of items in the folder BDISO to check if the DVDISOs are listed.

I only have 4 BDISO and 10 DVDISO so it shouldn't be the issue. Will try your suggestion tho.

**Comment by vinhtq115** [comment]
It doesn't work. Still only 4 BDISOs are shown.

I will try reinstall webman and also try previous version and see if it works.

**Comment by aldostools** [comment]
Check that the folder is named DVDISO (all letters in upper case).

Also verify that the contents for Blu-ray and DVD are check marked in /setup.ps3
(These options are collapsed by default, so you have to expand the section to see the options)

I'll try to make a setup to try to reproduce your issue.

**Comment by vinhtq115** [comment]
> 
> 
> Check that the folder is named DVDISO (all letters in upper case).
> 
> Also verify that the contents for Blu-ray and DVD are check marked in /setup.ps3 (These options are collapsed by default, so you have to expand the section to see the options)
> 
> I'll try to make a setup to try to reproduce your issue.

Here is my folder tree:
```
Z:\PS3\ISO>tree /F
Folder PATH listing for volume seagate_data
Volume serial number is 69FF-B679
Z:.
├───BDISO
│       Hitman (2007).iso
│       John Wick (2014).iso
│       John Wick 3 Parabellum (2019).iso
│       John Wick Chapter 2 (2017).iso
│
└───DVDISO
        Akira Phan - Dung Day Vuon Vai (Vol. 1) (2008) [NTSC].iso
        H2T Hits (Vol. 1) (2010) [PAL].iso
        H2T Hits (Vol. 2) (2010) [PAL].iso
        High School Musical The Concert [NTSC].iso
        Khac Viet - Mat Cam Giac Yeu... Anh Khac Hay Em Khac (Vol. 2) (2011) [PAL].iso
        Minh Hang - Co Nang Dang Yeu (Vol. 2) (2010) [PAL].iso
        Minh Hang - Mot Vong Trai Dat (Vol. 1) (2008) [PAL].iso
        Mr.T, Yanbi & HaBi - Nothing In Your Eyes (Single) [PAL].iso
        Taylor Swift - Fearless (Platinum Edition) [NTSC].iso
        Wanbi Tuan Anh - Thang [NTSC].iso
```

Blu-ray and DVD are check marked in /setup.ps3 (I didn't change anything).

Seems like downgrading version does not work.

About my PS3, I restored the backup I had made earlier this morning when I was trying to downgrade to 2.80. Current FW is 4.88.3 and I formatted the drive before restoring the backup. I also reinstalled every PKGs (including webMAN-MOD) too.

**Comment by aldostools** [comment]
i just tested your issue and it working on my side:
![image](https://user-images.githubusercontent.com/974897/140615204-b3a46ed8-a62b-4958-8a70-83ad977bb256.png)

These are my current settings:
![image](https://user-images.githubusercontent.com/974897/140615231-a156e4f8-b74e-44e4-b530-9c5dab7120ad.png)

**Comment by vinhtq115** [comment]
Here is mine:
![image](https://user-images.githubusercontent.com/34190240/140615357-18ab26ab-3b99-457c-b47a-5f55f23e6499.png)
![image](https://user-images.githubusercontent.com/34190240/140615473-75d7c130-f6e2-4fd9-b196-1c53efac335f.png)

![image](https://user-images.githubusercontent.com/34190240/140615490-401915e7-3782-4929-924e-286ee07dad8c.png)

**Comment by vinhtq115** [comment]
So I tried new location for ps3netsrv and it seems that DVDISO are showing too.

Also, those BDISOs and DVDISOs were created with hardlink (I put them in another directory on same HDD). Could that be the reason?

**Comment by aldostools** [comment]
Yes that's the issue. The hardlinks are treated as a different file type.

You can create an empty DVDISO and use DVDISO.INI to list the files from other paths.

**Comment by vinhtq115** [comment]
> 
> 
> Yes that's the issue. The hardlinks are treated as a different file type.

That's odd since it works fine with BDISO but not DVDISO. I can play them normally on both my PC and PS3.

> 
> You can create an empty DVDISO and use DVDISO.INI to list the files from other paths.

Do you have any sample INI file?

**Comment by aldostools** [comment]
Here is an example redirecting PS3ISO to other paths using PS3ISO.INI
![image](https://user-images.githubusercontent.com/974897/140615953-d7d1a4db-04f2-4b3c-a7a2-5491bdcb37d9.png)

The same can be done with BDISO.INI,  DVDISO.INI, PSXISO.INI, etc.

The .INI should be in the same path of the redirected folder
![image](https://user-images.githubusercontent.com/974897/140616035-185e485e-6491-455b-9727-0ee4fcb0cfc7.png)

**Comment by vinhtq115** [comment]
> 
> 
> Here is an example redirecting PS3ISO to other paths using PS3ISO.INI ![image](https://user-images.githubusercontent.com/974897/140615953-d7d1a4db-04f2-4b3c-a7a2-5491bdcb37d9.png)
> 
> The same can be done with BDISO.INI, DVDISO.INI, PSXISO.INI, etc.
> 
> The .INI should be in the same path of the redirected folder ![image](https://user-images.githubusercontent.com/974897/140616035-185e485e-6491-455b-9727-0ee4fcb0cfc7.png)

So I tried this INI method and it still not showing DVDISO inside Blu-ray and DVD. File browser shows that the location is correct and I can mount the DVDISO manually.

Maybe the [docker image ](https://hub.docker.com/r/shawly/ps3netsrv) I'm using is bugged. I will try compiling an ARM64 version and use it instead.

Update: I copied a DVDISO inside the folder (no more hardlink) and it still not showing up. File browser shows it fine. Maybe the issue was not the hardlink but the docker image.

**Comment by aldostools** [comment]
Try creating an empty DVDISO folder and putting the ISOs inside (not hardlinks or softlinks).

The INI is working fine here, but the folder should be a real folder not a link.

**Comment by vinhtq115** [comment]
> 
> 
> Try creating an empty DVDISO folder and putting the ISOs inside (not hardlinks or softlinks).
> 
> The INI is working fine here, but the folder should be a real folder not a link.

That's what I did. I put a real ISO into the DVDISO and refreshed webMAN but it didn't show up.

I compiled a binary and this one works fine (both real and hardlink are shown on webMAN) so the docker image I used was the issue.
