### ISSUE TITLE
Use http requests to control PS3 via webMAN-MOD

### ISSUE THREAD

**Issue by fauwzk** [aldostools/webMAN-MOD#578]
Is it possible to use GET or POST requests to control webMAN-MOD. I tried using the web commands listed here : [https://www.psx-place.com/threads/webman-mod-web-commands.1508/](url) and postman (to test) and got "_Error! Javascript disabled_". I want to create a "Remote" app for my phone and this would be helpful.

**Comment by aldostools** [comment]
Only GET method is supported.

If the web command says /mount.ps3&lt;path>

You should add http:// + IP-address-of-PS3. 
example: http://192.168.1.123/mount.ps3/dev_hdd0/GAMES/My+Game+[BLES12345]

In the PS3 Internet Browser you can replace the IP address with 0
0/mount.ps3/dev_hdd0/GAMES/My+Game+[BLES12345]
or
http://0/mount.ps3/dev_hdd0/GAMES/My+Game+[BLES12345]

**Comment by fauwzk** [comment]
Thanks ! And also, what is a path for a exFAT prepISO HDD for mounting games ?

**Comment by aldostools** [comment]
exFAT cannot be accessed directly from webMAN MOD.

These files are cached by prepISO into /dev_hdd0/tmp/wmtmp as *.ntfs[PS3ISO]

The sufix is .ntfs[***ISO] is used for both exFAT and NTFS.

**Comment by fauwzk** [comment]
So if I use the mount.ps3 command with the _wmtmp_ path, I should be able to mount games from my phone ?

**Comment by aldostools** [comment]
Yes. Indeed you can mount your games from your phone/pc/tablet just accessing:

http://IP-Address-of-PS3/index.ps3    <= Grid style

or

http://IP-Address-of-PS3/games.ps3  <= Coverflow style

**Comment by fauwzk** [comment]
Cool ! I will try that.
