### ISSUE TITLE
webMAN 1.47.00 Chinese language translate missing

### ISSUE THREAD

**Issue by PetrusZ** [aldostools/webMAN-MOD#58]
Some of the text become English at setup page.

Detail please see the attach.

![webman mod](https://cloud.githubusercontent.com/assets/4990592/23066542/23e0fa86-f556-11e6-9050-535d8351c9a1.png)

**Comment by jonaaa20** [comment]
This happens with Portuguese (Brazil) language too.

**Comment by jonaaa20** [comment]
This issue is fixed on the latest build...
