### ISSUE TITLE
Might be an error at 1.47.37

### ISSUE THREAD

**Issue by ghost** [aldostools/webMAN-MOD#580]
My Super Slim (CECH-4004A) device can not set offset values after disabling CFW Syscalls. Have to do reboot the device or not disabling CFW Syscalls and because of it I can't go online. Can you do something on it? Or, what can i do for that?

**Comment by aldostools** [comment]
I'm not sure what you mean with "can not set offset values".

When you disable CFW syscalls, you are removing all HEN features called through syscall 8. The only way to restore them is restarting the console.

If you enable the option PS3MAPI in the Shortcuts section of /setup.ps3, the syscall 8 remains partially enabled when you disable the CFW syscalls. This option allows to perform limited CFW functions while the CFW syscalls are disabled.

**Comment by ghost** [comment]
> I'm not sure what you mean with "can not set offset values".
> 
> When you disable CFW syscalls, you are removing all HEN features called through syscall 8. The only way to restore them is restarting the console.
> 
> If you enable the option PS3MAPI in the Shortcuts section of /setup.ps3, the syscall 8 remains partially enabled when you disable the CFW syscalls. This option allows to perform limited CFW functions while the CFW syscalls are disabled.

I will try it. Thank you.
