### ISSUE TITLE
ftp chmod issue

### ISSUE THREAD

**Issue by sunnyqeen** [aldostools/webMAN-MOD#581]
Current lite vision disabled some common ftp command like chmod
But the command should be OK to use in any version.
I also tried normal version, but chmod seems doing nothing, no error, but the mod is never changed.

The environment is hen 3.0.3 with fw 4.88

**Comment by aldostools** [comment]
Thank you for the bug report. I reviewed the code and the mode parameter was not being parsed properly.

The fixed build can be downloaded through the online XMB updater or downloading the current package availble in the release page

**Comment by sunnyqeen** [comment]
Thanks for the fix. 
Could you also move the function out of LITE_EDITION  define. This function should work with lite version.
