### ISSUE TITLE
PS3 shutdowns itself when uploading files via FTP

### ISSUE THREAD

**Issue by ghost** [aldostools/webMAN-MOD#586]
Yesterday, I was trying to install Dark Souls to my PS3 via FTP. After a while, PS3 shutdowns itself suddenly and in FileZilla, I saw this error.
Error:	File transfer failed
Status:	Connecting to 192.168.1.56:21...
Status:	Connection attempt failed with "ECONNREFUSED - Connection refused by server".
#EDIT: While uploading Dark Souls to my PS3, mmCM was open in PS3.

**Comment by aldostools** [comment]
The shutdown may happen if the memory usage is configured to use 3072KB [MC]: 1 - app.

If this is the case, I suggest to select 4 - bg or disable the [MC] option.

It may happen also if the memory profile "Max (1280KB)" is selected. This option uses 256KB instead of 128KB when [MC] is disabled. If the VSH memory is low, the system may become unstable.

**Comment by ghost** [comment]
> The shutdown may happen if the memory usage is configured to use 3072KB [MC]: 1 - app.
> 
> If this is the case, I suggest to select 4 - bg or disable the [MC] option.
> 
> It may happen also if the memory profile "Max (1280KB)" is selected. This option uses 256KB instead of 128KB when [MC] is disabled. If the VSH memory is low, the system may become unstable.

This might be a weird question but, where can I change these settings? mmCM or WebMAN?
> memory usage is configured to use 3072KB [MC]: 1 - app.
> memory profile "Max (1280KB)" is selected

**Comment by aldostools** [comment]
Open PS3 Internet Browser, then go to http://0/setup.ps3

These options appear in the section IDPS & MEM Setup. You need to expand that section to show the options.

**Comment by mtkcnl** [comment]
> Open PS3 Internet Browser, then go to http://0/setup.ps3
> 
> These options appear in the section IDPS & MEM Setup. You need to expand that section to show the options.

Hey, same guy again. I opened this issue for a long time ago but finally checked the settings today. These are settings for my PS3 (Never changed the default settings):
![image](https://user-images.githubusercontent.com/96322566/152576324-4fd47d37-810f-45d4-9c93-8f6fdf65f6cb.png)
What should I do?

**Comment by aldostools** [comment]
Yes, the settings are the default. My comment above was if the 2 settings in the second line were changed. That is not your case.

If the PS3 continue shutting down when FTP is used, try limiting the number of simultaneous FTP transfers to 1 in the FTP client. The recommended FTP client is FileZilla.
![image](https://user-images.githubusercontent.com/974897/152578247-f6a8becc-4f2c-4a93-8edf-714c931ed446.png)

If you're using HEN, the shutdown could be related to the use of dynamic fan. Try changing the fan to manual mode in /setup.ps3
