### ISSUE TITLE
PS2CONFIG - does it do anything for BC PS2's or it works only for the .BIN.ENC format?

### ISSUE THREAD

**Issue by olokos** [aldostools/webMAN-MOD#589]
So I have the CEHC04 PS3 with semi-hardware emulation built in, without the need to use the PS2 launcher to launch .bin.enc encrypted games.

If I play the games by loading PS2 ISO's by mounting them with CFW am I actually using any of the PS2CONFIG patches through webmanmod?

Can I somehow start using those PS2CONFIG patches on my console or possibly even toggle them on or off?

Or those PS2CONFIG patches are actually useless for my device in general?

BTW Thank you very much for your awesome tool!

**Comment by aldostools** [comment]
As far as I know, all ps2 emulators (net, gx, soft) use internal CONFIG files. Only CECHA and CECHB models don't require the configs due the PS2 mode is done by hardware.

In general the PS2CONFIG can be useful not only to make a game playable, but also to improve the performance or fix glitches, stuttering, etc.

If the file name of the PS2 ISO contains the game id enclosed in brackets, webMAN MOD will search the PS2CONFIG database copied locally in your system and copy it to the PS2ISO folder, if the ISO already don't have one. e.g.

/dev_hdd0/PS2ISO/My Game 1 (SLES-12345).ISO
/dev_hdd0/PS2ISO/My Game 2 [SLUS_123.45].ISO

You can disable this feature unchecking the option "Auto CONFIG" in /setup.ps3

You can setup the CONFIG manually downloading the file from [https://ps3.aldostools.org/ps2config.html](https://ps3.aldostools.org/ps2config.html) and copying it to the same folder of the ISO with the same file name + .CONFIG. e.g.
/dev_hdd0/PS2ISO/My Game.ISO
/dev_hdd0/PS2ISO/My Game.ISO.CONFIG

I recommend to test the game with the CONFIG. If you experience issues, try disabling the Auto CONFIG and remove the CONFIG file. 

You can try creating your own custom configuration files using the PS2 CONFIG editor included in ManaGunZ.

**Comment by gosseux** [comment]
Is it possible for webman to find the correct CONFIG without adding the game id to the filename?

**Comment by aldostools** [comment]
If the game id is not included in the file name of the ISO, webMAN MOD will try to detect the game id reading the root of the PS2 disc, but it is not guaranteed that it will do it correctly. That's why I recommend to include the game id in the ISO.

Also that works only for decrypted ISOs. For PS2 Classics the game id in the file name is required for the auto CONFIG.

**Comment by olokos** [comment]
Thank you very much for such detailed info on this, I think it might be worth to include it somewhere in the docs or readme as I haven't seen this information anywhere else!

Also which format of the name would be the best?
[]
()
with dots/without dots?
with dash or underscores?

I also heard about the R2+something keycombos to boot using no patches, to boot using ps2configs and to boot using the bin.enc loader, could you shed some light on this please?

and lastly, what is the default behavior, if I start the game by just pressing X?

Thank you so much for your work!

**Comment by aldostools** [comment]
Use the format that you prefer. All they are supported.

The CONFIG is always used if they are present in the PS2ISO folder. If the "Auto CONFIG" setting is checked, it will be loaded from the database and copied to PS2ISO.

There are a lot of combos using R2, you can find them in:
https://github.com/aldostools/webMAN-MOD/wiki/PAD-shortcuts-or-Combos

The default behavior is go to the disc icon. 
If the option "Auto-Play" is checked or if you keep pressing X until you see the mount notification message, webMAN will try to launch the game after the mount is completed.

The information was added to the wiki as you suggested:
https://github.com/aldostools/webMAN-MOD/wiki/Game-Paths-&-Covers#ps2-config

**Comment by olokos** [comment]
I've decided to add brackets with game ID to all of my PS2 games, thank you so much for your work and support, you're awesome!

There's only this one game, which I have a lot of sentiment for (first good ps2 game I played):
Stuart Little 3 Big Photo Adventure PAL [SCES_534.22]

A lot of the times loading or starting a game (after selecting a language upon loading the game) will result in a black screen, I've thought I might fiddle around with configs, but there isn't one.

When I open the ISO I can see as per usual SCES_534.22 file and SYSEM.CNF file.

SYSTEM.CNF contents are:
`BOOT2 = cdrom0:\SCES_534.22;1 
VER = 1.02 
VMODE = PAL 
`

looks normal, just as any other PS2 games, but when I tried the R2+Circle combo to confirm it, I'm getting this on PS3:
`BOOT2 = cdrom0:\SCEX_534.22;1 
VER = 1.02 
VMODE = PAL 
`

Basically the PS3 says it's ID starts from SCEX, while the ISO contains SCES_534.22.

This is a multilanguage game, so possibly the ID is chosen based on language selected ingame?

Available languages which I can select upon first launch of the game:
English, French, Deutsch, Espanol, Italian, Suomi, Portuges, Polish, Nederlands

This is really weird, but I really want to get this game working, I'll try to download ManagunZ in a moment and make a config myself.

I could probably try the USA version, but then I won't get the nostalgia moments hearing the same dialogs I've heard ~10 years ago.

The weirdest thing about that game is that the first run works and the game runs perfectly, but now I cannot load or start a new game as I end up in a black screen.

Sorry for going into details about the particular game, but I think figuring this out could potentially fix even more games having this issue.

EDIT:
I've tried multiple times with [SCES_534.22] in iso name, but it would never load into the game (after selecting start new game or loading a save). Creating a config with managunz with that name also did nothing.

Then I've tried now with [SCE**X**_534.22] in the iso name without any config and the game just loaded the first intro video, then black screen again after the video.

I've exited the game using XMB, mounted it again and loaded savegame and now the game works, despite no configs, just using the correct ISO name, this is so weird.

None of those gameIDs have configs available online, but I did install the latest PS2Config package.

I saved the game, tried to go to ingame main menu and it froze again.
Then I went back to XMB, tried to load the game again - black screen again after trying to load game.

I'm not really sure how to go about this or even if that's the right place to discuss this.

**Comment by aldostools** [comment]
It looks like the game id was patched with X by webMAN MOD.
That patch is applied to SCED_***.** games and some SCUS game ids blacklisted in game_ext_plugin.

However, the game id of your game doesn't meet any of these condition.

I suggest to dump the ISO again or restore the original game ID in the ISO using HxD.
You should search and replace all occurrences of SCEX_534.22 in the ISO with SCES_534.22

Anyway I don't see that game listed in the compatibility list and there is not any custom CONFIG created for it.
https://www.psdevwiki.com/ps3/PS2_Classics_Emulator_Compatibility_List

**Comment by olokos** [comment]
That's exactly what happened, now inside the ISO there's SCEX_534.22 and SYSTEM.CNF reads SCEX also.

While tinkering around I also tried to ADD LIMG and Remove LIMG with managunz, maybe this could be the reason?

I've tried ManagunZ Enable480P + FMV Skip in Game options, but it seems to do nothing.
I've also went into ManagunZ game Configuration and enabled ALL of the simple toggles, but it doesn't seem to change anything.

I'll dump the game again I guess and report back.

**Comment by aldostools** [comment]
The LIMG is required to convert the ISO to .BIN.ENC (PS2 Classics). If you play the game as ISO, the LIMG is ignored.

I recommend that you post your results in this thread and ask for help from advanced PS2 users like mrjaredbeta or Agrippa
https://www.psx-place.com/threads/compatibility-list-ps2-on-ps3.1306/

**Comment by olokos** [comment]
I do have a clean ISO game copy.
PS2 ISO MD5 Calculator v2.24 by Chook confirms that

So I just copied the game to PS3 again and mounted it using webman mod, but still it gets renamed to SCEX, probably during mounting?
I'll post that on the forums aswell, but this is so weird.

**Comment by olokos** [comment]
Here's the post I've made on the forums:
https://www.psx-place.com/threads/compatibility-list-ps2-on-ps3.1306/page-256#post-319415

If you feel like this isn't webman mod related issue, feel free to close this issue as I'm not sure myself.

**Comment by aldostools** [comment]
To discard that the issue is caused by webMAN, I compiled a version without the function patch_ps2_demo().
You would need to restore the original ISO to test that now it is not being patched with X.

[webftp_server.zip](https://github.com/aldostools/webMAN-MOD/files/7834182/webftp_server.zip)

**Comment by olokos** [comment]
I can confirm, now the file is not renamed with an X!
First start of the game didn't work, froze as usual before loading.
The second start of the game did work and I was able to load into the game! albeit the loading screen was half black it loaded the game!
Third time the game also loaded, half of the loading screen was black, the same as second run, but the game loads great.

Seems like that might've been the issue here. 
I can do some more testing but it might've been the problem here!

**Comment by aldostools** [comment]
You can try downloading the latest build from the online updater and check if the file is renamed again.

As @Agrippa commented in psx-place forums, the bug was fixed in August 2021. It's possible that you were still using an old build.

If the issue re-appears, you can use the test plugin.

**Comment by olokos** [comment]
1.47.36 was the version I was using, I could've sworn I did update, but I in fact did not.

I've updated to 1.47.37 via the online updater and the game doesn't get renamed anymore, yet the issue with black screen during loading persists.

So it's not webmanmod, but the game itself, thank you so much for your efforts! ❤️ 

I'll post that also in psx-place thread.
