### ISSUE TITLE
(q) Custom game list sorting / custom subfolders in webMAN folders?

### ISSUE THREAD

**Issue by J0hnTR** [aldostools/webMAN-MOD#590]
Greetings from Ukraine!

> Commits on Nov 21, 2021
> webMAN MOD 1.47.37 +XML formatter …
> - Fixed reload link in /cpursx.ps3
> - **Added tool that formats mygames.xml for manual edition**

Saw an interesting thing at [`webMAN-MOD/_Projects_/tools/FormatXML.zip`](https://github.com/aldostools/webMAN-MOD/blob/master/_Projects_/tools/FormatXML.zip) recently.
As I could understand - it is an assist tool to manually sort records in `/dev_hdd0/xmlhost/game_plugin/mygames.xml` file.
Haven't tested it yet by myself - my gamelist is being changed quite often, so the situation with "changes made will be lost upon rescanning the content" is making me sad =)

I just thought about how to sort the list of ISOs, since webMAN is not able (as far as I know) put games in a custom user subfolders in XMB menu.
So far, I'm just sorting ISOs in "Games/PS3" folder by file name, but I'm tired of putting the three-letter prefixes "ACT_" (action), "ADV_" (adventure), "RAC_" (racing), "RPG_" and so on everywhere..
Moreover, they eat out four of the six characters set aside by default for sorting the list alphabetically.

This is what I mean - is there any option that manual changes of `mygames.xml` were somehow fixed on content rescan?
There was a wonderful tool run directly on PSP, "HomeBrew Sorter" - maybe something like that could be done on PS3.

Thanks for your hard work!
Alex

**Comment by aldostools** [comment]
You can save your customized XML as /dev_hdd0/wm_custom.xml

There is a template in /dev_hdd0/game/UPDWEBMOD/USRDIR/xmb/wm_custom.xml
that you can use a guide. This file is not modified after re-scan.

Also to avoid lost your changes in mygames.xml you should make the file read only using chmod.ps3
and disable the content scanning at startup

In regards to the HomeBrew Sorter, yes it is feasible. I have seen some XMBML editors in the past.
Here is one that I found doing a quick search. Probably not the best, but it gives you the idea.
https://www.psx-place.com/resources/phoenixarc-xml-generator-toolkit.888/

**Comment by J0hnTR** [comment]
So fast, so precise.
Thanks!
