### ISSUE TITLE
Missing /app_home entry HEN

### ISSUE THREAD

**Issue by remlei** [aldostools/webMAN-MOD#594]
Im trying to use the GAMEI scheme to load the digital games over my PS3netsrv running on my NAS.

im using the v1.47.37, all it did is pop-up a message that it loaded the game over my NAS and then nothing, the only difference is if I moved to data Video or Music Category in XMB, it shows up a Data Disc in Blue Disc Icon.

![IMG_20211213_124057](https://user-images.githubusercontent.com/9265995/145754779-dfed68bc-1b59-4d86-84ca-89645f121069.jpg)
![IMG_20211213_124122](https://user-images.githubusercontent.com/9265995/145754835-071e7712-782c-4968-9a55-6287d07eb7f7.jpg)
![IMG_20211213_130050](https://user-images.githubusercontent.com/9265995/145755141-3e72f31c-a971-47be-be96-d5147e2f7d28.jpg)
![IMG_20211213_130618](https://user-images.githubusercontent.com/9265995/145755880-07e4cc1f-8aa1-459c-a7f8-1eba45ba351a.jpg)

**Comment by aldostools** [comment]
You need to refresh XML (SELECT+L3) and reload XMB. 
If the option /app_home is checked (like shown in your picture) the debug icon (★ app_home/PS3_GAME) should appear after the "webMAN Games" icon.

If the option still doesn't show, you will need to edit manually category_games.xml or install [Ultimate Toolbox](https://store.brewology.com/ahomebrew.php?brewid=326) by DeViL303 to add the app_home icon with a few clicks in the menu.

**Comment by remlei** [comment]
Already did this seceral time, either by that button combination or through
webman menu with refresh games and xmb option.

**Comment by aldostools** [comment]
If the option still doesn't show, you will need to edit manually category_games.xml or install [Ultimate Toolbox](https://store.brewology.com/ahomebrew.php?brewid=326) by DeViL303 to add the app_home icon with a few clicks in the menu.

**Comment by remlei** [comment]
Ok will try this..

**Comment by remlei** [comment]
I tried the toolbox and it works. the app_home finally appeared in XMB, I wish that webman-mod have this option to override for it to show up.
