### ISSUE TITLE
Getting black screen and console freezing trying to install webMAN

### ISSUE THREAD

**Issue by i-am-nut** [aldostools/webMAN-MOD#596]
guys, i'm having issue to install webMAN, when attempting to install i get a black screen and the console freezes, only able to restart by holding power button for a few seconds. Any ideas what might be the issue? I'm using HEN 3.0.3, HFW 4.88 and SSD

**Comment by aldostools** [comment]
Try disconnecting all USB devices (including the controller).
Enable HEN, then execute the webMAN MOD 1.47.37 installer (press L1 for Full Edition).

If the problem persists, there could be an issue in your HEN or internal HDD. You could try reinstalling HFW or restoring factory defaults then re-install HEN.

If you get to load webMAN MOD, go to webMAN Setup menu and check the option "Disable content scan on startup" and save.

**Comment by i-am-nut** [comment]
Thank you very much @aldostools  
by removing all USB devices the installation completed succesfully
