### ISSUE TITLE
PS2 Config file issue

### ISSUE THREAD

**Issue by iTzSweetTooth** [aldostools/webMAN-MOD#598]
Hello, This is the first time Im using config file to fix freezing issue but It just wont apply

any idea what im doing wrong ?! 

The game I’m trying to fix is crash twinsanity 

the game is impossible to play without config file 

Im using ps3 BC pal version 

![84702456-85B2-40E7-86A5-9F6676B2B8B6](https://user-images.githubusercontent.com/96267619/146457377-fc9189df-97fd-4c9d-a2d0-c2a9455ebe4e.jpeg)

here is a picture showing the file 

Thx

**Comment by gosseux** [comment]
According to the picture you posted the file name is not right. Check carefully all 3 files should be named with .ISO but 2 of them are named with .IOS
You also have the same error with true crime

**Comment by iTzSweetTooth** [comment]
> According to the picture you posted the file name is not right. Check carefully all 3 files should be named with .ISO but 2 of them are named with .IOS
> You also have the same error with true crime

![C3103235-450D-4215-B047-6E3083343655](https://user-images.githubusercontent.com/96267619/146515596-8992f578-997a-4df8-be32-ebc1491faad4.jpeg)

I tried but still it wont apply 

like I said Im new to this config thing so I probably missing something 

I try 2 version of the game. The disc ( creat ISO) and the one from the internet 

both of them are us version 

the config file I’m using is the CUSTOM one 

I’m using this CECHC03 model ( backwards compatible pal ) < maybe config file doesn’t apply to BC PS3 ?! 

I just want to know what Im doing wrong 

thx for your help

**Comment by aldostools** [comment]
The config looks named correctly. You could try using the ps2_netemu. You can choose it choose it in /setup.ps3 or pressing R2 when the game is mounted.

**Comment by iTzSweetTooth** [comment]
> The config looks named correctly. You could try using the ps2_netemu. You can choose it choose it in /setup.ps3 or pressing R2 when the game is mounted.

Sorry Im too new to this, Where exactly can I download the ps2_netemu ?! From multiMan?! But where 

I'm using this version of CFW 

![26C5DC58-C805-415E-AB7E-7D06E77CCFC3](https://user-images.githubusercontent.com/96267619/146637514-a26106ae-bf86-41d7-aa81-d648adb0a3d1.jpeg)


will the extension even work with my current CFW

also Im not using ManaGunz maybe thats the reason why ?! 

thx

**Comment by iTzSweetTooth** [comment]
> The config looks named correctly. You could try using the ps2_netemu. You can choose it choose it in /setup.ps3 or pressing R2 when the game is mounted.

I just found a link from the internet and unfortunately it does not support my current version 

![1772D321-C1B7-4FD3-983A-82E544DEE97B](https://user-images.githubusercontent.com/96267619/146638039-ea7af143-04cc-43fe-93de-aa8e0eee2566.jpeg)

**Comment by aldostools** [comment]
ps2_netemu is the emulator used on slims and super slims. It's included in all CFW with other 2 PS2 emulators. The emulator is selected by default based on the model of the PS3. The option that I mentioned allows to use ps2_netemu on backward compatible models. 

ManaGunZ and multiMAN are optional.

**Comment by iTzSweetTooth** [comment]
> ps2_netemu is the emulator used on slims and super slims. It's included in all CFW with other 2 PS2 emulators. The emulator is selected by default based on the model of the PS3. The option that I mentioned allows to use ps2_netemu on backward compatible models.
> 
> ManaGunZ and multiMAN are optional.

Umm I guess you mean this right 

![43675AA9-B3B5-4F02-86A8-8A4B3BE4DB60](https://user-images.githubusercontent.com/96267619/146638856-a1a70532-9411-44fe-b385-2f1cab8e8587.jpeg)

Im kinda lost honestly because I just started to use CFW this week for the first time 

I believe this doesn’t apply to my console because the game is running using BC and not software but I could be wrong 

thx for your help anyway

**Comment by aldostools** [comment]
I mean that try forcing Cobra to use ps2_netemu.self

That option is found in webMAN Setup, You have to expand the section Scan for content, check the option for ps2_netemu and save the settings.

**Comment by iTzSweetTooth** [comment]
> I mean that try forcing Cobra to use ps2_netemu.self
> 
> That option is found in webMAN Setup, You have to expand the section Scan for content, check the option for ps2_netemu and save the settings.

Is it here ?? 
![5248F86B-8E54-48A9-9C33-45C4739A4213](https://user-images.githubusercontent.com/96267619/146646363-da225183-9bd4-4acf-ae7c-87aa88a13825.jpeg)


If yes which one 

sorry if i being annoying lol but im just lost

**Comment by aldostools** [comment]
No. It is in the section "Scan for content" (the first one in that page).
You must expand that section. The option appears next to "PLAYSTATION©2" (right side of the screen)

The option "ps2_netemu" only shows for the following model:
0x01 = CECH-A*, 0x02 = CECH-B, 0x03 = CECH-C, 0x04 = CECH-E

**Comment by iTzSweetTooth** [comment]
> No. It is in the section "Scan for content" (the first one in that page). You must expand that section. The option appears next to "PLAYSTATION©2" (right side of the screen)
> 
> The option "ps2_netemu" only shows for the following model: 0x01 = CECH-A*, 0x02 = CECH-B, 0x03 = CECH-C, 0x04 = CECH-E

Omg its actually work perfectly. Thx a looooot
