### ISSUE TITLE
Button combo

### ISSUE THREAD

**Issue by 4everm3** [aldostools/webMAN-MOD#599]
Button combos in vsh / in Game only work for me sometimes. I press the combo several times and only one of them works for me. The combos in game do not work for me

**Comment by aldostools** [comment]
The combos are processed in a very low priority. 
You must keep the buttons pressed for a few seconds until the action is performed.

If you press and release the buttons quickly, the combo may not be detected even if you do it repeatedly.

**Comment by 4everm3** [comment]
I understand. Still I expect many improvements in later versions
