### ISSUE TITLE
1.47.00 freeze on ps3 game mout and uninstall issue

### ISSUE THREAD

**Issue by gosseux** [aldostools/webMAN-MOD#60]
the ps3 freeze on ps3 game mount using slaunch or xbm

I removed webman mod using /delete.ps3?uninstall then installed 1.46.01 and slaunch still there !!

**Comment by jonaaa20** [comment]
Re-download the PKG again, aldostools fixed it.

**Comment by gosseux** [comment]
Thanks for the info
