### ISSUE TITLE
MW2 Crashing - 4.88 Evilnat

### ISSUE THREAD

**Issue by NO-ob** [aldostools/webMAN-MOD#605]
I've observed crashing on 4.88 evilnat with webman mod. Only seems to happen with modern warfare 2 so far I haven't tested many games but black ops and black ops 2 worked okay.

It's not the iso or console because I tried both a us and and pal version of the game and experienced the same crashing it will cause black screen within minutes of launching and the console needs to be force powered off. I confirmed this crashing on two different consoles too. 

I went out and bought a mw2 disc yesterday and that runs fine

**Comment by aldostools** [comment]
Please make sure that you have installed Evilnat 4.88.2. It fixed various bugs in the release 4.88

If the console continues freezing, try Rebug 4.86 or mounting the game with multiMAN, to verify if the issue is webMAN MOD or Evilnat 4.88

**Comment by NO-ob** [comment]
I dumped my disc copy to iso with multiman and then played that through webman mod and it worked fine so maybe I just got unlucky and the two releases I got were both bad
