### ISSUE TITLE
Mounted PSX games from NTFS not showing in XMB

### ISSUE THREAD

**Issue by southoz** [aldostools/webMAN-MOD#606]
Hi Aldo

Thanks for all the hard work.

I have noticed an issue when mounting PSX IOS or BIN/CUE from external NTFS when selecting them through webMAN-MOD. They are mounting but at the end of the process an error message is shown and the mounted image is not shown in the XMB. If you restart the XMB (eg. through a scan and restart XMB) the mounted image is shown normally and can be started. If you use IRISMAN to mount the image it appears in the XMB as expected.

Links have been created in wm_tmp with both the internal scanner for both LITE and FULL versions of 1.47.37 and additionally PrepISO version 1.28. CFW is Evilnat 4.88 CEX Cobra 8.3

The Path on the external NTFS does not affect the issue for example

PSXISO/Gamename.cue
PSXISO/[GameID].cue (Matches Cover from the PS2/PSX covers package)
PSXISO/Gamename/Gamename.cue
PSXISO/Gamename/[GameID].cue (Matches Cover from the PS2/PSX covers package)
PSXISO/Gamename.iso
PSXISO/[GameID].iso (Matches Cover from the PS2/PSX covers package)
PSXISO/Gamename/Gamename.iso
PSXISO/Gamename/[GameID].iso (Matches Cover from the PS2/PSX covers package)

PS.

If you get a chance on the next release can you please add a SEGACD folder mapped to genesis_plus_gx_libretro_ps3.SELF and include iso as the file format. As long as the SegaCD bios is copied into the Retroarch System folder Sega CD works quite well.

What is the purpose of hardcoding the prepending [PSPISO] in the PrepISO code? If you delete the prepend of the PSP generated files in wm_tmp they functional normally and the game icon is shown.

**Comment by aldostools** [comment]
Thank you for your feedback. I tried to reproduce your issue, but every time that I executed prepISO the PSXISO games were listed fine on XMB and they could be mounted without errors.

In regards to SegaCD support, I added ISO to the ROMS extensions and added scan for ROMS/SEGACD mapped to genesis_plus_gx_libretro_ps3.SELF

The extensions .ntfs[PS3ISO], .ntfs[PSXISO], .ntfs[PSPISO] are used in the cache files stored in /dev_hd0/tmp/wmtmp to identify the type of ISO scanned by prepNTFS or prepISO. That is the nomenclature originally used by deank.

**Comment by aldostools** [comment]
Here is the updated package with support for SEGACD.
[webMAN_MOD_latest.zip](https://github.com/aldostools/webMAN-MOD/files/7914720/webMAN_MOD_latest.zip)

I haven't tested it myself because I don't have SegaCD isos. It would be helpful if you could test and give your feedback before I release it.

**Comment by southoz** [comment]
Thanks for your response, I will definitely test SEGACD and upload a video showing the results. I want to delete both Retroarch and the ROM Launcher first to show the steps I need to go through from start to finish. I believe I will need to fix the bad directories in the ROM Launcher Retroarch.cfg required to correctly point at the Sega CD BIOS files. in /game/RETROARCH/system folder

What firmware did you test the PSX from NTFS? I feel this may be related to EVILNAT CFW.  I have uploaded the testing I did showing initial Basic Test, the .ntfs file include hex (looks good) and then the extended test using multiple filename option with the XMB reload to show the ISO is actually mounted. It does work with IRISMAN 4.88 which makes me think its a problem with Evilnat rather than WebMAN-MOD
[PSX on NTFS](https://youtu.be/cUBNAXC93zA)

With the PSPISO Prepend I was looking at the code in PrepISO that adds [PSPISO] to the front of the filename rather than the end.
[PrepISO  Code](https://github.com/aldostools/webMAN-MOD/blob/f2cf5ddb3690727d0bc94cc060c793f00ebe49cd/_Projects_/prepISO/source/main.c#L237)

If you manually edit the filenames to remove the prepend the Icons will then load and the XMB music will play.
[PSP Prepend](https://youtu.be/MxX9fYQUdhg)

**Comment by aldostools** [comment]
I tested the PSX from NTFS on Evilnat 4.88.2 using a pendrive attached to dev_usb000
In my test I copied 2 files to the folder /dev_ntfs0:/PSXISO
![image](https://user-images.githubusercontent.com/974897/150615116-06bd508b-88f4-44d9-b3f6-c0a5b22d6394.png)

In regards to the prepend [PSPISO], I made a change to the code to remove it from the title in the game list.
However the file name in /dev_hdd0/tmp/wmtmp preserves the prepend to avoid conflict with existing versions.
I know I added that label for some reason that I don't recall now.

You can test the new build without the PSP prepend installing the package in the following zip
[webMAN_MOD_latest.zip](https://github.com/aldostools/webMAN-MOD/files/7917203/webMAN_MOD_latest.zip)

**Comment by southoz** [comment]
Sega CD Testing - Looks Good, CHD is not found as the scanner is not looking for CHD files.

File Formats: Bin/Cue, ISO and CHD

Corrected the ROM Launcher Retroarch.cfg by copying the generated version from Retroarch CE over the ROM Launcher version. Uploaded the Sega CD BIOS files in the Retroarch System folder. The Bin/Cue and ISO versions on the internal HDD were found by the internal scanner after a reboot and launched from webMAN-MOD.

[00:09](https://www.youtube.com/watch?v=fGn63f-hwfI&t=9s) Uninstall Retroarch and delete ROM Launcher.
[01:39](https://www.youtube.com/watch?v=fGn63f-hwfI&t=99s) Copy Sega CD Files.
[03:13](https://www.youtube.com/watch?v=fGn63f-hwfI&t=193s) Install Retroarch, ROM Launcher and webMAN-MOD update. 
[04:54](https://www.youtube.com/watch?v=fGn63f-hwfI&t=294s) Run Retroarch to generate Retroarch.cfg.
[05:28](https://www.youtube.com/watch?v=fGn63f-hwfI&t=328s) Inspect ROM Launcher Retroarch.cfg for invalid folders.
[07:13](https://www.youtube.com/watch?v=fGn63f-hwfI&t=433s) Copy Retroarch.cfg over ROM Launcher version.
[08:20](https://www.youtube.com/watch?v=fGn63f-hwfI&t=500s) Copy Sega CD BIOS files to System Folder.
[09:28](https://www.youtube.com/watch?v=fGn63f-hwfI&t=568s) Retroarch Client Testing of three formats.
[11:01](https://www.youtube.com/watch?v=fGn63f-hwfI&t=661s) webMAN-MOD Scan and XMB.
[12:31](https://www.youtube.com/watch?v=fGn63f-hwfI&t=751s) Testing of Bin/Cue and ISO.

**Comment by southoz** [comment]
Thanks for the update, have confirmed that a 32GB Stick works without an issue. It may be related to the change of sector size from 512b to 4K to support MBR with capacity greater than 2TB. The drive was formatted with WD Quick Formatter with WinXP compatibility option
![HDD-Properties](https://user-images.githubusercontent.com/20381196/150629157-66967d99-f047-4b98-91d8-4cbc23bb8a2f.png)
.

It does work well with PS3 ISO on the NTFS drive which is why it looked a bit strange when webMAN-MOD threw the error in the video.

**Comment by southoz** [comment]
PSP from NTFS Display Name - Looks Good, Covers are the default PSP Icon which can be manually fixed using the format [PSPISO] Gamename.iso.png and copying to wmtmp

Games mount and display in XMB from the 4K Sector External 4TB without any issues.

[PSP from NTFS](https://youtu.be/dhghqJCJ7dE) - See 4:38 onwards for Displayed Output, Testing and Fixing Covers manually

**Comment by aldostools** [comment]
Thank you again for your feedback. A new build is available with support for .CHD and other file extensions.

You can use the online updater on XMB or download the installer from the [release page](https://github.com/aldostools/webMAN-MOD/releases)

**Comment by southoz** [comment]
Thanks for the help with the mounting issue and adding Sega CD Support. Now I can see your changes if I find anything else of value with Retroarch I will raise a suggestion ticket with the changes.

Had a look at both the IRISMAN and webMAN-MOD code for supporting Cobra Mode PSX mounting in XMB. Outside of supporting Multidisk there was nothing that stood out to explain why the image was mounted but not showing in the XMB.

Keep up the great work.
