### ISSUE TITLE
The "Update webMAN MOD" option will only install the Full Version instead of the Standard or Lite Versions

### ISSUE THREAD

**Issue by DAMNED117** [aldostools/webMAN-MOD#609]
Say for example I have webMAN MOD Lite or Standard Edition installed, and on the XMB, when you enter webMAN Games > webMAN Setup and then the option "Update webMAN MOD", after the update finishes and you restart your console, webMAN MOD will show up as the Full Version instead of Lite or Standard (depending on what version you installed in the first place). So basically it replaces the previous Version/Edition you had installed before updating webMAN MOD to the Full Version.

I'm looking forward for a fix to update and install the correct version of webMAN MOD, that is, if this is a real issue.

**Comment by aldostools** [comment]
The online updater only installs the full version.

To update to the latest lite or standard version you need to download and re-install the package manually from
https://github.com/aldostools/webMAN-MOD/releases

**Comment by DAMNED117** [comment]
> To update to the latest lite or standard version you need to download and re-install the package manually from https://github.com/aldostools/webMAN-MOD/releases

Yeah I know, that's what I'm currently doing. I'm just asking if there's going to be an online updater (just like the full version) but for lite or standard versions. Because it's kinda annoying to manually update as I don't use my pc that often.

**Comment by aldostools** [comment]
For the moment there are not plans for an online updater for lite/standard version.

The full version includes all the features in lite/standard version, except the smaller memory footprint.

**Comment by DAMNED117** [comment]
> For the moment there are not plans for an online updater for lite/standard version.

I hope there will be in the near future, it’ll be a huge update… at least for me.

> The full version includes all the features in lite/standard version, except the smaller memory footprint.

Yep. Currently I’m using the lite version to reduce the stress put on the console, because when I used to do recoveries (level up, unlock all etc.) on GTA:O when the servers were still online, my console freezes. 

I tried looking for a workaround and thought why not giving the lite version a shot? And surprisingly it helped a lot, I might switch to standard or full version now since the servers are gone.

Plus, currently I’m not interested in the additional features standard and full versions offer aside from the in-game recording and XMB screenshot, but last time I used full version the in-game recording was not working for some reason (I haven’t tried the XMB screenshot feature yet), that’s why I’m not planning to upgrade right now.

I’m not an advanced user when it comes to webMAN MOD, but still, might upgrade from lite soon.

**Comment by aldostools** [comment]
I understand your need, and that's why there are 4 flavors of the plugin (full, standard, lite, non-cobra).

Although I update frequently, there is no need to keep updating the plugin every time that I commit a new build.

If it is too annoying to use the installer and the full version is not an option, I suggest that perform one update once a month or when I release a new version.

**Comment by DAMNED117** [comment]
Alright thanks for the advice, I’ll update like monthly or so, or if the new version has something that I want/an issue fixed that I have been facing and it’s urgent to update. I’ll close this ticket now. Thank you so much for looking into my post.
