### ISSUE TITLE
Not loaded after reboot

### ISSUE THREAD

**Issue by xswqaz** [aldostools/webMAN-MOD#61]
My enviroment is HABIB 4.81 and nobt ( only wired connection )
Right after system restore from recovery mode, and install update pkg, webMAN was loaded
But, After machine reboot, webMAN not loaded anymore until system restore

I tried also rebug cfw, and same problem

**Comment by aldostools** [comment]
Please try with 1.47.01... If the issue persists, please report back. If not, please close the issue.

**Comment by RandQalan** [comment]
FYI have the same problem after clean
it shows but still problems like no config posible

**Comment by iHaired** [comment]
Same here. Rebug 4.81.2. webMAN MOD 1.46.01 working fine. 1.47.01 or 1.47.00 doesn't load at all.

**Comment by Joonie86** [comment]
Closing old cases that have no further feedback. please use the latest version of wMM and report us
