### ISSUE TITLE
webMAN MOD 1.47.37, not allow access to the PSN network

### ISSUE THREAD

**Issue by Ang3l42** [aldostools/webMAN-MOD#612]
Hello. In the latest version of the webMAN MOD 1.47.37, a bug was found that did not allow access to the PSN network. When i try to go online (before that, I cleared the custom syscalls and deleted the history), error 80028E01 appears on the screen.
https://i1.imageban.ru/out/2022/02/03/b1e559b4ae90a6833c25f0de22b56473.jpg
I installed version 1.47.36, PSN login works with it.

**Comment by aldostools** [comment]
It could be a coincidence that using 1.47.37, PSN login was not working and it worked again later but you had 1.47.36.

According to psdevwiki, the error 0x80028E01 (Issue connecting online) has this remark:
HTTP status error was returned from the server // Reboot console and try connecting again (PSN may be down for maintenance), if this fails, try connecting later; if setting up a network connection, settings may be incorrect; if issues continue then check internet connection

**Comment by Ang3l42** [comment]
No. The problem is with the latest webman mod. Everything works with previous versions. 1.47.37 of December 30 also works. But the latest version is blocking psn

**Comment by aldostools** [comment]
Check if you have `/dev_hdd0/ps3-updatelist.txt`
If you have it, delete that file, reboot and test again.

The only change related to PSN between current build and the build of December 28th is that the update URL redirection of `ps3-updatelist.txt` was not working on CFW, and it was fixed on Jan 27th.

If that file exists, it would not have any effect in the build prior Jan 27th.

That file is used by PS3 to check online the latest firmware version available. When the local file exists, webMAN MOD use it to spoof the latest firmware version and redirect the update PUP.

**Comment by Z0rD4n0v1ch** [comment]
Join the problem.

**Comment by Z0rD4n0v1ch** [comment]
Join the problem.

I'm using PS3 with CFW 4.88.2, and I confirm that there is an issue with PSN login on latest webMAN MOD 1.47.37 as described by @Ang3l42.
Proof: [https://i1.imageban.ru/out/2022/02/04/a2d073832aa06085443f8f134a7d8b0f.jpg](https://i1.imageban.ru/out/2022/02/04/a2d073832aa06085443f8f134a7d8b0f.jpg)

The problem with error 80028E01 is solved only by uninstalling the latest version of webMAN MOD 1.47.37 and installing a later version of webMAN MOD.

**Comment by aldostools** [comment]
> The problem with error 80028E01 is solved only by uninstalling the latest version of webMAN MOD 1.47.37 and installing a later version of webMAN MOD.

Thank you for your feedback. 1.47.37 is the latest version (there are different commits with the same label). Do you mean a previous version or the latest build?

Another setting that could be blocking PSN is the "Offline [Lock PSN]" option next to "Disable CFW syscalls and delete history files at system startup" in /setup.ps3.
However **that feature haven't been touched lately** and it is disabled by default, except if the user changed the option manually.

**Comment by pulsemod** [comment]
I just updated to 1.47.37 and am having the same issue. I was confused as well, because "Disable CFW syscalls and delete history files at system startup" is unchecked and the combo box to the side of it is set to disabled rather than lock PSN, but I'm seeing a PSN locked screen whenever I try signing in (I typically used PSNpatch to block access). After enabling the "DEL CFW SYSCALLS" hotkey and using it instead of PSNpatch's hotkey, I receive the same error code when attempting to sign in.

I haven't tried the previous version (unsure of the version I was running previous), but considering this build is months old I'm skeptical about the build itself being an issue. the PSN lock feature being enabled when it doesn't seem to be in settings is definitely concerning, though.

**Comment by aldostools** [comment]
@pulsemod it is required to press R2+TRIANGLE to discable CFW syscalls and enable the PSN screen.

webMAN MOD will prevent the access to PSN while the CFW syscalls are enabled.
Same occurs with CFW Evilnat 4.88.2.

To disable this check remove the file /dev_hdd0/tmp/wm_res/npsignin_plugin.rco
If CFW Evilnat 4.88.2 need to remove also /dev_blind/vsh/resource/npsignin_plugin.lck

**Comment by Z0rD4n0v1ch** [comment]
> Thank you for your feedback. 1.47.37 is the latest version (there are different commits with the same label). Do you mean a previous version or the latest build?
> 
@aldostools I'm currently using a build [(7c740d3)](https://github.com/aldostools/webMAN-MOD/commit/7c740d3f7bf1d804962d704068bc6c4700a8145b) that has a problem with PSN login on CFW 4.88.2

But for example, on the build [(a377343)](https://github.com/aldostools/webMAN-MOD/commit/a3773430b39922a2572fd40cf3fa23670b54f4e5) there are no problems with entering PSN on CFW 4.88.2

I also noticed if you use the build [(7c740d3)](https://github.com/aldostools/webMAN-MOD/commit/7c740d3f7bf1d804962d704068bc6c4700a8145b), then there is a problem with connecting the PS3 to the network on CFW 4.88.2. Proof: [Screenshot](https://i1.imageban.ru/out/2022/02/05/2f74d0c18eac172d7c65d9cd7446a1fe.jpg). But if you use the build [(a377343)](https://github.com/aldostools/webMAN-MOD/commit/a3773430b39922a2572fd40cf3fa23670b54f4e5), then there are no problems with connecting to the network on CFW 4.88.2.

At the moment, these errors are resolved if you remove webMAN MOD 1.47.37 [(build 7c740d3)](https://github.com/aldostools/webMAN-MOD/commit/7c740d3f7bf1d804962d704068bc6c4700a8145b) itself or install webMAN MOD 1.47.37 [(build a377343)](https://github.com/aldostools/webMAN-MOD/commit/a3773430b39922a2572fd40cf3fa23670b54f4e5)

**Comment by aldostools** [comment]
@Z0rD4n0v1ch Thank you for your detailed feedback. Indeed it helped me to identify the issue and reproduce the error. The installer currently available in the online updater, in the release page and in brewology should bypass the Internet Connection error.

https://github.com/aldostools/webMAN-MOD/releases

Commit: c220a301f9313b35daf584c4e33d3d54ab36bcf1

**Comment by Z0rD4n0v1ch** [comment]
> @Z0rD4n0v1ch Thank you for your detailed feedback. Indeed it helped me to identify the issue and reproduce the error. The installer currently available in the online updater, in the release page and in brewology should bypass the Internet Connection error.
> 
> https://github.com/aldostools/webMAN-MOD/releases
> 
> Commit: [c220a30](https://github.com/aldostools/webMAN-MOD/commit/c220a301f9313b35daf584c4e33d3d54ab36bcf1)

@aldostools Just downloaded the update and confirm build [(c220a30)](https://github.com/aldostools/webMAN-MOD/commit/c220a301f9313b35daf584c4e33d3d54ab36bcf1) fixes PSN login issues on CFW 4.88.2

Aldo, thank you for quickly and timely correcting the error.

**Comment by CSPG305** [comment]
> @pulsemod it is required to press R2+TRIANGLE to discable CFW syscalls and enable the PSN screen.
> 
> webMAN MOD will prevent the access to PSN while the CFW syscalls are enabled. Same occurs with CFW Evilnat 4.88.2.
> 
> To disable this check remove the file /dev_hdd0/tmp/wm_res/npsignin_plugin.rco If CFW Evilnat 4.88.2 need to remove also /dev_blind/vsh/resource/npsignin_plugin.lck

Why is that required? its rather annoying, im using 1.47.37 removing this file 
"To disable this check remove the file /dev_hdd0/tmp/wm_res/npsignin_plugin.rco"

Causes me to have to re-install my cfw...

**Comment by CSPG305** [comment]
@aldostools 

webMAN MOD will prevent the access to PSN while the CFW syscalls are enabled. Same occurs with CFW Evilnat 4.88.2.

To disable this check remove the file /dev_hdd0/tmp/wm_res/npsignin_plugin.rco If CFW Evilnat 4.88.2 need to remove also /dev_blind/vsh/resource/npsignin_plugin.lck

Why is that required? its rather annoying, im using webman mod full 1.47.37 and im in rebug 4.84 DEX
removing removing the file you suggested " /dev_hdd0/tmp/wm_res/npsignin_plugin.rco"

Causes me to have to re-install my cfw...

**Comment by aldostools** [comment]
If you access PSN with CFW syscalls enabled your system can be flagged for banning by Sony.
Few weeks later you may receive a message telling that your account or console was banned.
In some cases it can be an instant banning.

That is a measure to protect the users from banning and lose the access to PSN or their account (with all the purchased game$$$).

That's why webMAN MOD and Evilnat CFW enforces the user to disable the syscalls.
It's as simple as press R2+TRIANGLE for a couple of seconds.

**Comment by CSPG305** [comment]
> If you access PSN with CFW syscalls enabled your system can be flagged for banning by Sony. Few weeks later you may receive a message telling that your account or console was banned. In some cases it can be an instant banning.
> 
> That is a measure to protect the users from banning and lose the access to PSN or their account (with all the purchased game$$$).
> 
> That's why webMAN MOD and Evilnat CFW enforces the user to disable the syscalls. It's as simple as press R2+TRIANGLE for a couple of seconds.

i attempted to remove the file you suggested and it crashed my ps3...  ive had a dex ps3 since at least 2013, i prefer not to disable system calls. ive only ever been banned twice.. is ther anyway to remove the check without having the ps3 crash and ask to reinstall the firmware?

**Comment by aldostools** [comment]
You need to delete the file and reboot immediately.
The file is mapped to /dev_flash. If you continue using the console it will be interpreted as you deleted a system file.

**Comment by CSPG305** [comment]
> You need to delete the file and reboot immediately. The file is mapped to /dev_flash. If you continue using the console it will be interpreted as you deleted a system file.

i went into filezilla and went to the following path, /dev_hdd0/tmp/wm_res/npsignin_plugin.rco it crashed my ps3 and asked me to reinstall the system software
