### ISSUE TITLE
webMAN not listing games hosted via ps3netsrv, but mounting via the file browser is still possible

### ISSUE THREAD

**Issue by DerpyChap** [aldostools/webMAN-MOD#614]
webMAN version: webMAN 1.47.37 MOD (Full)

So, I've been having this issue ever since recently updating webMAN to the latest available version: webMAN simply refuses to list any games hosted remotely, even though the remote server itself is accessible to the PS3 and games can be mounted manually by using webMAN's file browser. This issue appears to impact games of all types (PS1, PS3, etc.). Games stored locally on the hard drive appear without issue.

Some things I've tried:
 - Uninstalling and reinstalling webMAN and using default settings (outside of adding the server as a scan option, of course)
 - Reinstalling/updating ps3netsrv to the latest version
 - Different hosts running ps3netsrv
 - Testing without games stored on the hard drive (by renaming PS3ISO to something else)
 - Testing with just a single PS3 game stored on the server and nothing else
 - Adjusting the plugin memory usage and [MC] settings in webMAN

Nothing seems to change, however downgrading back to 1.47.36 resolves the issue. Both host machines are running Windows.

**Comment by aldostools** [comment]
A very recent build now validates that the remote file exists before list the content on the XML.

You can try installing one of the recent commits before that change.
https://github.com/aldostools/webMAN-MOD/tree/29bbf641a6749549e5a0c2e77ba0a1c1b5ece7c0/_Projects_/updater/update/dev_hdd0/plugins
https://github.com/aldostools/webMAN-MOD/tree/a3773430b39922a2572fd40cf3fa23670b54f4e5/_Projects_/updater/update/dev_hdd0/plugins

**Comment by DerpyChap** [comment]
Tested with 29bbf641a6749549e5a0c2e77ba0a1c1b5ece7c0 and everything seems to now be working as expected. 👍

**Comment by aldostools** [comment]
@DerpyChap Thank you for your feedback. I uploaded a new build removing the check added recently.

You can download the latest build using the online updater or re-download the installer from:
https://github.com/aldostools/webMAN-MOD/releases
or https://store.brewology.com/ahomebrew.php?brewid=310

**Comment by DerpyChap** [comment]
Downloaded the new build and everything seems good, thanks for the help!
