### ISSUE TITLE
Retroarch 1.10 (Retroarch CE beta 4) 

### ISSUE THREAD

**Issue by southoz** [aldostools/webMAN-MOD#615]
@aldostools @crystalct
In general, the integration and performance is a lot better than 1.9.14 and most of the issues I encountered were not with the webman launcher.

Observation:
- Pico Core crashes when attempting to run 32x either in ZIP or 32x format both through the native interface and webman mod the last debug before the crash is a geometry message and there is nothing else in the logs to suggest what the issue is.

[PICO32X-Crash.txt](https://github.com/aldostools/webMAN-MOD/files/8040232/PICO32X-Crash.txt)

- DOSBOX core is significantly faster (Gods now runs at 60fps) than DOSBOX_SVN but I am having an issue with .conf files where the core enters the configuration file at the DOS prompt. In general DOSBOX makes a mess of the the XMB in webman with every single EXE shown.
- FUSE core is now working and can be launched from XMB
- HATARI still won't load a rom to either of the ATARI floppy drives and the internal HATARI (triangle) menu won't bring up a file browser. I created the folder referenced in the default disk location but it made no difference. 
-  Sinclair ZX81 is not showing in XMB I believe this is as my ROMS have a .p extension. The info file is missing for this core so I can not test in the native interface.
- I gave up trying to control the directories so by default webman launcher dumps the per core / content directory /game config files in /dev_hdd0/game/PKGLAUNCH/PS3_GAME/USRDIR so they are not accessible from within the native Retroarch Interface.

Cores with webman integration not tested:

- GME
- JAVAME
- PALM
- QUAKE
- XPET

**Comment by crystalct** [comment]
32x can't works because is missing the development of dynarec for PS3.

**Comment by FaberfoX** [comment]
I've just started using my (formerly stored) PS3 with a NTSC only CRT via component. After setting resolution in Retroarch CE Beta 4 to 720x480, the few Megadrive games I tried work when launched from it. 
Trying to launch from the ROMS section gives me a totally scrambled display (much worse than when it tries to display 50Hz-PAL content) and trying to blindly quit crashes the PS3 (I can still restart it from the web but get first 2, and then 3 beeps). 
PS3 is a slim running 4.88.2 evilnat with latest webMAN MOD (1.47.37). This happens with and without PKG/ROM Launcher installed. 
Over HDMI, everything works, so my guess is that Retroarch is ignoring the config set when launched from webMAN MOD.
Am I doing something wrong, or is there anything else needed to get this to work?

**Comment by aldostools** [comment]
Try starting RetroArch CE directly (not mounting a ROM through webMAN MOD).

If the scrambled screen still shows, try deleting /dev_hdd0/game/RETROARCH/USRDIR/retroarch.cfg through FTP or using the web interface. Then launch RetroArch CE again.

Alternatively you can try installing the official RetroArch 1.9.0 from Brewology. Both versions can be installed because they use different paths. However if you need to mount the official RetroArch through webMAN MOD, you have to delete RetroArch CE.

**Comment by aldostools** [comment]
webMAN MOD uses the config file in this path when it launches RetroArch CE.
/dev_hdd0/game/PKGLAUNCH/PS3_GAME/USRDIR/retroarch.cce

Download that file, edit it with notepad and upload it back to PS3.
Try changing the video_refresh_rate to "50.000000" for 50hz (PAL)
