### ISSUE TITLE
Retroarch Quake Core XMB issue with webMAN-MOD

### ISSUE THREAD

**Issue by southoz** [aldostools/webMAN-MOD#616]
Hi @aldostools 

When using the directory structure for Tyrquake https://docs.libretro.com/library/tyrquake/the shareware PAK0.PAK and retail PAK1.PAK Quake are not shown in the XMB. 

https://youtu.be/WXEPpsJ8epg

Video shows the issue, Mission Pack 1 & 2 working in XMB, the file structure in the PS3 and Quake PAK1.PAK working through Retroarch CE

Note:
- retail PAK1.PAK assets are needed for Quake Mission Pack 1 and Mission Pack 2 which is why the directory structure is important
- webMAN-MOD was uninstalled and the PKGLAUNCH directory was manually deleted then a reinstall of the FULL version with the latest update.

**Comment by aldostools** [comment]
Thank you for your feedback. There was a bug processing sub-folder names of 3 characters (e.g. id1).
You can try updating to the latest binaries using the online updater or re-downloading the installer from the release page.

**Comment by southoz** [comment]
@aldostools confirmed fixed, thanks again!
