### ISSUE TITLE
The problem with XMB with a large number of games

### ISSUE THREAD

**Issue by KoRn0509** [aldostools/webMAN-MOD#617]
Hi.
I currently have 464 PS3 and 688 PS1 games
With so many games in XMB, the contents of the webman folder are not displayed 
At 464 + 600 is fine 
How can this be corrected? 
But it's worth going to Irisman everything is displayed 
https://imgur.com/iApEmOu

**Comment by aldostools** [comment]
The XMB memory is very limited. Try reducing the size  of the covers. Use images 192x192 or smaller.

It is also possible that the file name of some game is breaking the XML. Try moving out some PS1 games, then add them back in small amounts until you find the limit.

**Comment by KoRn0509** [comment]
Without covers it is displayed normally. Even 120x120 did not help
But why after you go into irisMan and go out, everything works fine ?

**Comment by aldostools** [comment]
If it works after exit from IRISMAN, then the issue is that there is not enough memory to load the XML and all the images when you access the menu. When you return to XMB probably some processes have stopped and there is more memory available.

I suggest that first disable the scan for content on startup. That consumes a lot of memory when the system boots.

Also check if exiting from other application has the same result than exiting from IRISMAN.

With 120x120, try reducing the amount of games. There should be a point where they  are listed.

**Comment by KoRn0509** [comment]
> I suggest that first disable the scan for content on startup. That consumes a lot of memory when the system boots.
>
Has already been disabled 

> Also check if exiting from other application has the same result than exiting from IRISMAN.
>
Apollo Save Tool, RetroArch, PKGi does not work, only IRISMAN 100% Managanz 50 to 50

> With 120x120, try reducing the amount of games. There should be a point where they are listed.
>
Approximately 1100 games work well 



A little off topic. psp games only work in .iso? And in which folder in BLES80608 do you need to put the covers? What should be the path?

**Comment by aldostools** [comment]
It's weird that only after exit IRISMAN works.

If 1100 games work well, then that seems is your limit. Not bad, considering that's only 52 games less.

PSP games only work as ISO. CSO is not supported.
There is experimental support for zipped ISO (ISO inside a zip).

If the PSP covers are detected by title id, then you should put them in /dev_hdd0/game/BLES80608/USRDIR/covers
If the PSP covers are detected by file name of the ISO, put the cover in the same folder of the ISO or in:
/dev_hdd0/tmp/wmtmp or /dev_hdd0/tmp/wmtmp/covers

**Comment by KoRn0509** [comment]
Thank you very much.
Well, it won't be difficult for me to get in and out of IRISMAN. I'll try to find the limit by adding more games)

**Comment by KoRn0509** [comment]
I also wanted to know about subfolders 

> You can save your customized XML as /dev_hdd0/wm_custom.xml
> 
> There is a template in /dev_hdd0/game/UPDWEBMOD/USRDIR/xmb/wm_custom.xml
> that you can use a guide. This file is not modified after re-scan.
> 
does it still work? I don't have UPDWEBMOD folder

**Comment by aldostools** [comment]
Check if there is a special character in the file name of the 52 games that your excluded.
Sometimes characters like & < > " * + can break the XML.

UPDWEBMOD is the installer. You normally delete that folder manually after installation.
The template is also found here:
https://raw.githubusercontent.com/aldostools/webMAN-MOD/master/_Projects_/updater/pkgfiles/USRDIR/xmb/wm_custom.xml
