### ISSUE TITLE
1.47.00 PSX games freeze PS3 system

### ISSUE THREAD

**Issue by shawly** [aldostools/webMAN-MOD#62]
So I've been trying to get Silent Hill (NTSC-U) version to work on my PS3 with Rebug 4.81.2 but the game just won't load, I just get a black screen, but the PS3 won't freeze though.

Any other game loads fine, the webMAN version was 1.45.09, so I upgraded to 1.47.00 and now all of my PSX games cause the PS3 to freeze completely.
When downgrading back to 1.45.11 they work again, but Silent Hill still won't work.

The only way to get Silent Hill to work on my system is to disable cobra mode via Rebug Toolbox and then load the game via MultiMan, then it'll work, but since the fan is blowing louder than a fighter plane I can't really play the game..

I can't figure out the issue, but it seems to be related to webMAN, even tough other people have confirmed that Silent Hill works with the latest Rebug CFW and webMAN 1.45.09, so I seem to be the only one with this problem. 
I can't say for sure that the freeze bug with PSX games on 1.47.00 is a common issue though.

**Edit**: Just tried the PAL version and it's working perfectly fine.. But various NTSC-U dumps won't work via webMAN, they work only with the MultiMan workaround described above..

**Comment by aldostools** [comment]
The issue with PSXISO has been fixed in 1.47.01

**Comment by shawly** [comment]
Thanks aldostools! Since my PS3 died this weekend I can test it with the new one when it arrives on Wednessday. Maybe I'll get the NTSC version of Silent Hill to work too then!

**Comment by shawly** [comment]
Nope Silent Hill NTSC-U won't start with WebMAN 1.47.xx either

**Comment by hanswurst31** [comment]
i have that same exaxt problem. i was on webman 1.4x and the game just wouldnt load from webman. only blackscreen. with the latest webman 1.47.05 the whole system freezes. i canr turn off the ps3 via power button. it just beeps. so i have to unplug the power cord.


system and game are like OT

**Comment by hanswurst31** [comment]
i was in cex. with dex it seems to work

**Comment by hanswurst31** [comment]
after playing to times it stoped working. playstaion just freezes

**Comment by shawly** [comment]
I gave up on trying to get the NTSC version of Silent Hill to work, I got a completely fresh PS3 system and it still won't start, different dumps, same result, blackscreen and nothing happens. The PAL version works perfectly fine, but it still bothers me since the PAL version got censored and AFAIK PAL doesn't run at 60Hz on my CRT..

**Comment by hanswurst31** [comment]
thx for your answer. this issue is very annoying. i got it working on dex mode but after playing two times.it agin wont load and freez.
