### ISSUE TITLE
"Starting Video... Press O to abort" message - how to disable?

### ISSUE THREAD

**Issue by DarjanKrijan** [aldostools/webMAN-MOD#625]
By accident I hit the install wMM icon, w/o holding L1, and ever since this message pops up after boot and messes up the XMB, at times my controller is mapped to player 2 even.

How do I disable this? I looked in issues and wiki for info but found nothing.

**Comment by aldostools** [comment]
Go to http://0/setup.ps3 and disable XMB Media option if it says Video or Music. Save and reboot to check.

Another option is to reset to default settings deleting /dev_hdd0/tmp/wm_config.bin and reboot.

**Comment by DarjanKrijan** [comment]
That sort of works, but it also disables auto play on mounting stuff off of slaunch.

Is there a way to completely disable that video recording thing? Tried renaming/deleting video_rec.sprx before but it still pops up annoyingly.

**Comment by aldostools** [comment]
"XMB Media" is a script that start Video or Music when the system starts.

"Auto-Play" is the option that enables the auto-play when a game is mounted.

If button X is keep pressed when a game is mounting, it enables the auto-play temporarily, but that doesn't work on slaunch.

I could add support for that feature later today in the week.

**Comment by DarjanKrijan** [comment]
Actually nvm, only the first mount doesn't auto-play for me, consecutive ones do with the tick on auto-play and XMB Media = Disabled.

Made me think I have to set the Video thingy for it to auto-play Video (DVD), hence activating the video recording feature.

**Comment by aldostools** [comment]
No, there is not any option for auto video recording. I don't think I will add that feature either.

**Comment by DarjanKrijan** [comment]
Well, it's what pops up when you set XMB Media = Video and reboot:
![screenshot_2022_03_07_16_19_33](https://user-images.githubusercontent.com/45214548/157062920-1a446852-9df6-419b-a1c9-e290a60e066d.png)
(think reinstalling wMM didn't have anything to do with it after all)

I in this case don't have any videos stored on the PS3.

**Comment by DarjanKrijan** [comment]
In any way, is that feature meant for infinitely looping/auto playing all video (or music) content that is on the PS3?

**Comment by aldostools** [comment]
The feature basically is an explore_plugin XMB automation script that changes the focus to Music or Video column, jumps to the last item in the bottom of the column, press Triangle and waits a few seconds seconds and click "Play".

This is a tricky way to make the system play music or a video when it starts.

Try adding some videos or music then test the feature.

**Comment by DarjanKrijan** [comment]
Alright ty.
