### ISSUE TITLE
Issue updating for Disk games over ps3netsrv

### ISSUE THREAD

**Issue by parwana89** [aldostools/webMAN-MOD#628]
Hello ,

thanks for this tool, it's really neat. However I seem to have issues, if I want to play my Backups over network, which need/want a update. I can download and Install the update, but it's stuck in a loop, where it keeps asking for the update and installing it, even though it's already installed.

Is there a solution for this issue? Maybe I can integrate the update into my ripped directory?

Thanks for any assistancce.

**Comment by aldostools** [comment]
You can integrate the update into the ripped directory, but you must sign the EBOOT/SELF/SPRX/EDAT as retail.
It may not work if these files contain hardcoded path pointing to /dev_hdd0/game/<GAMEID>

I suggest to delete the game data, install the update manually, then start the game after the update.

You can hex edit the PARAM.SFO in the update folder of /dev_hdd0/game/<GAMEID> to make the version match the latest version to avoid the game prompt for update.

Or simply unplug the network cable before start the game or just cancel when you get the prompt for update.

**Comment by parwana89** [comment]
thank you for the information. I will try this.
