### ISSUE TITLE
Realistic Memory Expectations for Large Collections/Libraries

### ISSUE THREAD

**Issue by ghost** [aldostools/webMAN-MOD#631]
Hi and thanks for the excellent webMAN-MOD. I am reasonably new to using software on consoles so bear with me if I don't quite grasp the limitations.

I have rather large libraries (full ROM sets) for PS1 through PS3, as well as full No Intro ROM collections for most other gaming platforms. So the number of files for each collection of ROM/BIN numbers in the thousands+. Last night I managed to set webMAN memory to Max and WM to 4 (bg) and that worked fine for 50 PS3 + approximately 100 PSXISO entries. Excellent, I now know how to properly scan my libraries 👍. I have disabled content scan on startup as recommended.

I have just finished converting all my CHD back to BIN/CUE for my PS1SO entries (CHD was for RetroArch running on a laptop, so core support which benefits me so I can save storage), which now total 1767 titles. A fair bit of reading tells me there are just only so many bytes that wMM can hold in memory **while scanning**.

What are the realistic expectations for scanning or listing these large collections? Are you able to provide an estimated "bytes per title" so that people like me can fine-tune what is in the locations that wMM scans? Is there a better way to get these libraries listed in wMM? Is there the capability to manually create the list by modifying a db for example?

Could wMM be more memory efficient, or trade processing speed, by reading and writing either per title, per memory-limit, e.t.c? I am assuming wMM runs out of memory during the scan because it's trying to process the entire list without releasing memory for processed titles?

OR

Is there a way to directly load PS1ISO from a file list/browser without scanning, i.e direct load? I think NETISO is this but I am not 100% on how it works and how I'd use it.

Thanks 😊

**Comment by aldostools** [comment]
The memory limitation indeed due VSH. If you press SELECT+START you will see that the free memory is usually under 2MB.

Even if you manage to scan thousands of games, the XMB will start to cache the XML files and images. At some point it will start having issues due the lack of free memory. The exact number of items supported cannot be predicted accurately due it depends of various factors. Three of them are:
- The free memory available at the moment of cache the XML (that amount goes up/down depending the processes running in background)
- The size of the covers/images (large covers result in less games that can be listed)
- The size of the XML file cached in memory.

All the games (PS1, PS2, PS3, PSP, ROMS, etc.) can be mounted from the web file manager.
You just need to click on the size of the game. The value is highlighted when you hover the mouse cursor.

An option is to create various custom pages in HTML (e.g. one per game type) with the name of the game, a link to the path to mount, and an image with the cover.

If you mount the game from a PC or smartphone, you could configure these values in /dev_hdd0/xmlhost/game_plugin/gamelist.js and use the slider GUI to select the game.

Depending the memory profile selected, I estimate that the maximum number of games is around 1500 or less for PS3 if "Max PS3+" is selected and 1100 or less for PSX if you choose "Max PSX+".
https://github.com/aldostools/webMAN-MOD/wiki/~-Plugin-Memory-Usage

**Comment by ghost** [comment]
Mounting via web file manager might be the immediate solution for me, thanks :)

As for creating a custom page in HTML, I assume wMM's webserver handles standard HTML code. Is there any example code I can use as a starting point? If I know the code structure for pages to list and load roms, I can automate it from there.

Thanks for the speedy reply and info 👍

**Comment by aldostools** [comment]
Yes, the PS3 browser handles standard HTML and HTML5.

A basic HTML example is like this:

&lt;table>

&lt;tr>
&lt;td>&lt;img src="/dev_hdd0/covers/image.png">
&lt;td>&lt;a href="/mount.ps3/dev_hdd0/PS3ISO/filename.ISO">Name of Game&lt;/a>
&lt;/tr>

&lt;tr>
&lt;td>&lt;img src="/dev_hdd0/covers/image.png">
&lt;td>&lt;a href="/mount.ps3/dev_hdd0/PSXISO/filename.bin">Name of Game&lt;/a>
&lt;/tr>

&lt;/table>

**Comment by ghost** [comment]
Absolute legend, thanks very much for the explanation of memory usage and the html for me to start with. You're a gem ☺️

**Comment by ghost** [comment]
For those playing at home, here's a quick bit of code to generate a HTML file to load PSXISO from. Simply create a file with the output of this script, place it in a web-accessible location and load through your browser.

https://gist.github.com/clontarfx/bd6830726350f48add0d861cb8bc081d

Tested and confirmed working perfectly, thanks again @aldostools for the example code. I now have full access to my library of BIN/CUE and don't need to stress the PS3's memory 👌
