### ISSUE TITLE
Error webMAN MOD Help Page

### ISSUE THREAD

**Issue by ozapft** [aldostools/webMAN-MOD#633]
Hello Aldo,

currently I have found the following errors in the new online help:

![photostudio_1647871352395](https://user-images.githubusercontent.com/72347490/159277794-c4540d7d-b3a1-4d2b-b511-ed968203ba20.png)
**webMAN MOD Editions:**
webMAN MOD includes 4 editions of the plugin
. Rebug/Cobra/PS3Mapi ...  
. Rebug/Cobra/PS3Mapi ... **this point is duplicated --->  **Full edition - Includes all the standard features, plus advanced features. The online updater installs this****

![photostudio_1647871376610](https://user-images.githubusercontent.com/72347490/159280149-b79cec64-c66f-42c9-a5f9-13b684838607.png)

**Plugin Memory Usage:**
STANDARD Total Allocated **128k is wrong** **---> **896k****

![photostudio_1647871101555](https://user-images.githubusercontent.com/72347490/159280814-19adaead-2f3b-4570-b86c-27e164ea1c9d.png)

The character **°** (degrees) is displayed incorrectly. (German language set for the PS3)

**Comment by aldostools** [comment]
Thank you for your feedback. The changes were included in 1.47.38
