### ISSUE TITLE
NTFS HDisk wrong free size is shown

### ISSUE THREAD

**Issue by ozapft** [aldostools/webMAN-MOD#635]
Hello Aldo, with the latest version webMAN MOD 1.47.38 the shown free size for NTFS Drives is wrong.

![photostudio_1647895828967](https://user-images.githubusercontent.com/72347490/159362704-fa114d6a-e533-42af-81a1-4929e2308520.png)
New Version 1.47.38

![photostudio_1647895795751](https://user-images.githubusercontent.com/72347490/159362753-2f47ef1e-412f-47c4-b150-a07d39b44489.png)
Old Version 1.47.37 from 2022.03.17

**Comment by aldostools** [comment]
Thank you for your feedback... LOL I don't know how I didn't noticed it.

It's now fixed 😄
