### ISSUE TITLE
webMAN MOD 1.47.00 hangs consoles

### ISSUE THREAD

**Issue by Haker120** [aldostools/webMAN-MOD#64]
I have CECHA, CECHC and two CECH2504B consoles, this version of webMAN freezes permanently all of my consoles, quick menu freezes permanently all of those no matter what I'll choose (example - refreshing games list), only main menu of this version works well. Also when loading ps1 games, it freezes on black screen, I tried a lot, PALs and NTSCs. From the newest multiMAN loading ps1 games work. As for now this version is unfortunatelly useless. Please fix it, I love this program after all. :)  On version 1.46.02 everything works well on my consoles.

**Comment by jonaaa20** [comment]
Did you tried the latest version? i mean, the latest version with the latest commit? the only issue that i'm having is the PSX Games...

**Comment by Haker120** [comment]
Yes, I did, that's why I report and I'm still on 1.46.02

**Comment by CokeCookie** [comment]
I can't confirm the problems with ps1 games (didn't do tests on them) but the quick menu on the XMB freezes my console regardless of what option I've tried (haven't tried them all, I gave up after 3 full freezes). I first noticed this on some version after the webbrowser-less mounting got implemented and I've gone back to 1.45.11 as a solution for now.

**Comment by aldostools** [comment]
webMAN MOD 1.46.xx and 1.47.00 had several issues caused from the transition to the new added features (XMB proxy) and changes in the way the memory is used.

The version **1.47.01** should fix most of the issues reported here.

**Comment by Haker120** [comment]
Thanks, I'm testing and I'll get to know if it'll work. I hope so, this app is great! :)

Ok, everything works as it should. Great job! However, this is small and not problematic issue - Auto Play stopped work. xD
