### ISSUE TITLE
All psp related packages have become corrupted data and cannot be removed or re installed

### ISSUE THREAD

**Issue by Ntemis** [aldostools/webMAN-MOD#643]
As the title says , freshly formatted hdd and latest version of webman-mod 
PSP_Remasters_Launcher.pkg
PSP_Minis_Launcher.pkg 
Are now corrupted data error 80010026 comes up when i try to delete them and cant find package on usb when i try to reinstall them

**Comment by PS3-Pro** [comment]
You need to mount a psp game to be able to delete them.

Or you can use /unmap.ps3

**Comment by aldostools** [comment]
PSP Launchers are blocked until a PSP game is mounted.
This is done to prevent that the system freeze if the user tries to launch a non-existing game.

As LuanTeles mentioned, they are unlocked if you mount a PSP game or execute the /unmap.ps3

Or use the XMB menu: webMAN Games > webMAN Setup > Redirect USB000 > Unmap PS3
