### ISSUE TITLE
ROMs not loading over ps3netsrv

### ISSUE THREAD

**Issue by noisenstatic** [aldostools/webMAN-MOD#644]
PSX, PS3 and ROMS games are showing up just fine but only the usb stored roms actually load up on retroarch community version.
It recognizes it as a network drive on the listing, starts to load up and then fails with an error (red cross on the top right of the screen).

Is there anything missing that is preventing the roms to load up?

I've been using the latest webman mod, pkg launcher.

PS1/PS3 games are loading up just fine.

One interesting thing is that on the shared folder it misses one ROM/ISO in webman but it shows all games in multiman.

**Comment by aldostools** [comment]
Thank you for your feedback. I will check the issue and let you know.

You can test a 1.47.36 just in case the feature was broken after the massive changes in 1.47.38

**Comment by noisenstatic** [comment]
That was fast, thanks! Actually same results the ROM doesn't load up, but it doesn't provide the "error" as the latest version does.
I thought it could be some write permissions on the share, since the roms were zipped and tried some unzipped roms, same results.

Thanks for the amazing tool!!

**Comment by aldostools** [comment]
A new build has been released fixing this regression on /ROMS folder. Thanks again for your feedback.

Use the online updater available on XMB or update manually downloading the current installer found in brewology or on the release page.
