### ISSUE TITLE
Webman inside parental control folder after installing pkg

### ISSUE THREAD

**Issue by lartsick74** [aldostools/webMAN-MOD#645]
Hello,
I'm on CFW 4.88.
When I install webman on my ps3, a folder named "Restricted content by parental control" appears in my game folder.
Parental control is not enabled on my ps3.
I have tried to open it with the code 0000 but it does not work.
I have downloaded the latest version of webman pkg from the brewology store.
Did I miss something ?
I'm a newbie in the ps3 jailbreak subjects
Best Regards,

Lucas

**Comment by aldostools** [comment]
It should be something wrong in your system's configuration or in the game PARAM.SFO

Try restoring the system default settings in Recovery menu.
Then reinstall webMAN MOD because entering to Recovery menu deletes /dev_hdd0/boot_plugins.txt

**Comment by lartsick74** [comment]
Thank you, it worked perfectly.
I'm gonna do a donation to support your work.
