### ISSUE TITLE
#646 update webMAN_DE.xml issue 

### ISSUE THREAD

**Issue by ozapft** [aldostools/webMAN-MOD#648]
I think something went wrong with my commit.

![Screenshot from 2022-03-28 21-23-51](https://user-images.githubusercontent.com/72347490/160489816-36b2ffc0-33c6-4b9c-9eed-59eceb782847.png)

**Comment by aldostools** [comment]
I see, but don't worry. I'm working in the uninstall submenu and it has your commit included.
[webMAN_DE.zip](https://github.com/aldostools/webMAN-MOD/files/8366517/webMAN_DE.zip)

**Comment by ozapft** [comment]
Thank you so much!
Perfect!
