### ISSUE TITLE
Accessibility for mounting PS3 Games

### ISSUE THREAD

**Issue by Avpq** [aldostools/webMAN-MOD#649]
I have a huge collection of PS3 games (100<) so can you add a "**search**" feature through which we can easily search for a game and mount it. As continuous scrolling in the list of such a huge games to find it is annoying.

**Comment by Masamune3210** [comment]
Would imagine it would probably be hard to get that added to the xmb, but maybe to slaunch or to the website?

**Comment by PS3-Pro** [comment]
You can use the search feature on the web GUI.

Just type <your-ps3-ip-adress>/ in any web browser connected in the same network as your PS3 and use the search bar.

You can also use it on the ps3 web browser http://0/

![image](https://user-images.githubusercontent.com/74815634/160557911-248d0e36-7178-4065-8b38-c8b9534a42cd.png)

**Comment by aldostools** [comment]
To type text on the PS3 using the gamepad is harder than scroll a sorted list.

Use the search function mentioned by LuanTeles or add your favorites games to sLaunch list pressing START. The list will be shorter. Also switch the grid to 10x4 using R3 to see more games on the screen and browse faster using L1 or R1.

**Comment by Avpq** [comment]
Thank you devs !!!
