### ISSUE TITLE
WebmanMod with ps3netsrv

### ISSUE THREAD

**Issue by s3anami** [aldostools/webMAN-MOD#653]
Hi,

You closed my previous issue and I cannot reopen it.
The folder support seems to be somewhat broken still.
For me this quote from the wiki does not seem to be true:
"Subfolders are now permitted using ps3netsrv 20220326 or later. Older versions require single letter subfolders (A, B, C, etc.) or sub-folders with the same name of the ISO."

For me, only one letter folders with no special characters are working.

For one of the people contributing to the retronas project, the routine still does not function properly as he commented here:
https://github.com/aldostools/webMAN-MOD/issues/642#issuecomment-1082409163

Thanks,

**Comment by aldostools** [comment]
I reopened issue #642. Please continue the discussion there.
