### ISSUE TITLE
Some xmb.ps3$xregistry are not working in latest updates

### ISSUE THREAD

**Issue by PS3-Pro** [aldostools/webMAN-MOD#654]
I noticed that some xregistry settings were not being applied on my system after updating webMAN.

The following commands no longer work on my side, infinite loading:

/xmb.ps3$xregistry(/setting/system/nickname)=Something
/xmb.ps3$xregistry(/setting/user/$USERID$/wboard/enable)=0
/xmb.ps3$xregistry(/setting/user/$USERID$/browser/exitConfirmation)=0

Also when it was working I realized that /xmb.ps3$xregistry(/setting/system/nickname)=Something 
does not support special characters eg : ™

**Comment by aldostools** [comment]
Thanks for your feedback. Try updating to the latest build.

**Comment by PS3-Pro** [comment]
Working after i deleted mine xRegistry,sys, maybe it got corrupted.

Special caracters are working now, thanks, but i notice something strange

/xmb.ps3$xregistry(/setting/system/nickname)=Something will set the console nickname to Somethi

and/xmb.ps3$xregistry(/setting/system/nickname)=PS3™ 4K Pro to PS3™ 

but it doesn't have characters limit if this is the case.

Edit: If i change the nickname through the XMB after setting it with web command, it will not work anymore

**Comment by PS3-Pro** [comment]
found the problem, seems like it cannot create but only replace?

If I manually set via XMB a 5 character long nickname then the web command will only set 5 characters and if I set later via web command a 3 character long nickname, only the first 3 characters will be replaced and the previous 2 remaning will be kept

![image](https://user-images.githubusercontent.com/74815634/160965492-ce08438c-ef7c-4dfd-9c12-5e5df69d4e04.png)
![image](https://user-images.githubusercontent.com/74815634/160965510-2ed844a6-c814-4e83-aebc-9b1e5631b20e.png)

**Comment by aldostools** [comment]
The xmb.ps3$registry() function using the key path only can replace the keys with the same length or smaller. It cannot create new keys or make the string values larger.

If you use the key id instead of the key path as a parameter, it will use the API and but the key ids can change from fw version. Not sure if the key id can change from consoles in the same version.

**Comment by LuanTeles** [comment]
> The xmb.ps3$registry() function using the key path only can replace the keys with the same length or smaller. It cannot create new keys or make the string values larger.
> 
> If you use the key id instead of the key path as a parameter, it will use the API and but the key ids can change from fw version. Not sure if the key id can change from consoles in the same version.

Aldo where can I get the xregistry key IDs and can you provide me an example using it instead of key path?

**Comment by aldostools** [comment]
> Aldo where can I get the xregistry key IDs and can you provide me an example using it instead of key path?

In this file you will find some ids and the equivalent key path. Some may have changed in current FW version.
https://github.com/aldostools/webMAN-MOD/blob/master/vsh/xregistry.h#L621-L750

**Comment by LuanTeles** [comment]
Thank you, I'll make some tests to see if they have changed between 4.88 and 4.89

**Comment by LuanTeles** [comment]
The systemNickname and account/avatarurl that i'm looking for are missing on it :P

I'm testing retriving DNS values but no success

  char primaryDns[0x10];               //0x3AC:
  char secondaryDns[0x10];             //0x3BC:

Key ID
![image](https://user-images.githubusercontent.com/110236244/189037847-272a1156-487e-492d-9cea-c366644c62ed.png)

Key Path
![image](https://user-images.githubusercontent.com/110236244/189037912-49069762-57c3-48fc-99cf-8127d7c95dd7.png)

or maybe it's id has changed on newer firmwares

**Comment by LuanTeles** [comment]
I was using keypaths to change DNS between multiple custom servers, but going back to PSN it breaks DNS while I was setting it for cloudflare and it replaced the previous custom values with 1.1.1.1 leaving the remaining values of the older DNS still there.

So i'm now using 

/netstatus.ps3?dns1=135.148.144.253;/netstatus.ps3?dns2=1.1.1.1 and it works as it should. This I think is using key IDs, so it can properly add the new values instead of replacing characters.

This is what sparked my interest in Key IDs as I need the SystemNickname and AvatarURL values to be applied correctly

**Comment by LuanTeles** [comment]
Aldo can the notifications of

	/netstatus.ps3?dns1=
	/netstatus.ps3?dns2=

be changed, both of them displays Network: Enabled, maybe Primary/Secundary DNS Set or something similar, i dunno.

**Comment by aldostools** [comment]
> Aldo can the notifications of `/netstatus.ps3` be changed, both of them displays Network: Enabled, maybe Primary/Secundary DNS Set or something similar, i dunno.

Yes, it can be changed. But why? to what message? That notification is used also by other subcommands of /netstatus.ps3

**Comment by LuanTeles** [comment]
> > Aldo can the notifications of `/netstatus.ps3` be changed, both of them displays Network: Enabled, maybe Primary/Secundary DNS Set or something similar, i dunno.
> 
> Yes, it can be changed. But why? to what message? That notification is used also by other subcommands of /netstatus.ps3

To be honest, there isn't really a reason lol, i just think (Network: Enabled) for those commands are way too generic as it is also used by other /netstatus.ps3 commands, so having specific notification for those would be better

/netstatus.ps3?dns1= could show Primary DNS address set
/netstatus.ps3?dns2= could show Secundary DNS address set

But not important :P

About those two commands, are they using the API right? How can i set it using xmb.ps3$registry()? just to get rid of the notifications (i'm using via script, so i need it to be silent), as using the ID 0x3AC returned me 0x0

**Comment by aldostools** [comment]
These commands don't change the registry directly. They call these API from xsetting_F48C0548:
xnet()->SetSettingNet_primaryDns(&ip_address1);
xnet()->SetSettingNet_secondaryDns(&ip_address2);
