### ISSUE TITLE
webMan games not showing anything but the webman setup

### ISSUE THREAD

**Issue by SaiSamarth-1** [aldostools/webMAN-MOD#655]
So today as i went to use prepISO on my ps3(Hfw 4.88) i went to check the Bluray and DVD folder only to find that inside webMAN games, none of the icons except for webMAN setup show up. I have spent the past few hours to find a solution to this but nothing. anyone have any idea why this might be happening? i've tried restarting my ps3, resintalling webMAN and prepISO with also nothing changed(Yes, i am using the latest version of prepISO and webMAN)

**Comment by aldostools** [comment]
Please use webMAN Games > webMAN Setup > Update webMAN MOD > Install and reboot after update.

It probably will fix your issue. Yesterday a broken build was released for a few hours until I found the error and fixed it.

**Comment by SaiSamarth-1** [comment]
I tried that and sadly it does not work

**Comment by aldostools** [comment]
It's weird because I tested 1.47.38 last night and it worked fine on my system after the fix. Try installing 1.47.37 or 1.47.36.

**Comment by SaiSamarth-1** [comment]
same problem with 1.47.37 and 36

**Comment by aldostools** [comment]
Then the problem is not the build since .37 and .36 were working fine.

It should be some configuration issue. Try uninstalling webMAN MOD and do a fresh install.

Alternatively you can remove /dev_hdd0/tmp/wm_config.bin manually then reboot.

Also check if prepISO 1.28 works better for you.

**Comment by SaiSamarth-1** [comment]
Once again sadly, none of those solutions work for me. Thank your trying to help, do let me know if you still have any idea on what the issue might just be.

**Comment by aldostools** [comment]
You can try asking in PSX-PLACE forums if someone had your same issue.

**Comment by SaiSamarth-1** [comment]
Will do, thanks for the help once again
