### ISSUE TITLE
ps3netsrv source fails to mount PSXISO bin/cue

### ISSUE THREAD

**Issue by sairuk** [aldostools/webMAN-MOD#656]
every bin/cue i've thrown at webmanmod locks up the ps3 when mounted from a ps3netsrv source.

If i copy them to /dev_hdd0/PSXISO and mount them with webmanmod they work fine.

- HFW 4.88.1
- HEN 3.03
- webMAN-MOD 1.47.38
- ps3netsrv 20220330

```
ps3netsrv build 20220330 (mod by aldostools)
Path: /data/retronas/ps3/ps3netsrv

Host IP #1: 192.168.200.1:38008
Host IP #2: 192.168.0.176:38008
Waiting for client...
[0] Connection from 192.168.0.134
open /PSXISO/THPS3-Preview-Build.cue
```

![image](https://user-images.githubusercontent.com/526372/161266480-10f0cadc-260d-46f4-84af-34dee6b3c5eb.png)

I let this sit for about 25m to see if it'd eventually process, nothing. 

bin is only 74M so more than enough time for any data transfer that needed to happen
```
-rwxrwxr-x 1 pi pi 74M Nov 30  2017 /data/retronas/ps3/ps3netsrv/PSXISO/THPS3-Preview-Build.bin
-rwxrwxr-x 1 pi pi  74 Dec  2  2017 /data/retronas/ps3/ps3netsrv/PSXISO/THPS3-Preview-Build.cue
```

ps3 still responds to ping, ftp/httpd ports are open but queries timeout. green power light sits there blinking

happy to pull more data if you can point in the right direction. I do not however have a ps3 sdk setup here to build custom webman to debug further.

**Comment by aldostools** [comment]
Try updating to the latest build using webMAN Games > webMAN Setup > Update webMAN MOD > Install, then reboot after update.

Yesterday I worked on a fix about that issue on these commits: https://github.com/aldostools/webMAN-MOD/commit/8ce7985f613fbf7f586ec7fdbaa57706ffad78a3 https://github.com/aldostools/webMAN-MOD/commit/3eb81ef71c277305e6fa0c47cc8881e8018ade5b

**Comment by sairuk** [comment]
yep confirmed working, thanks for your work on this.
