### ISSUE TITLE
Error 8001003A when disabling CFW

### ISSUE THREAD

**Issue by LouisGarry** [aldostools/webMAN-MOD#661]
Hello master Aldo, there is a report from my community, "Disable CFW" using wMM causes the mounting game to not work (error 8001003A).

They tried to disable it using the PSNPatch plugin, the game can be played.

Using EVILNAT 4.88.2 Cobra 8.3

Thanks.

**Comment by aldostools** [comment]
Is the game mounted before or after "Disable CFW syscalls" the game?
The CFW syscalls are supposed to be disabled *after* mounting the game.

The games can be mounted with CFW syscalls disabled only if PS3MAPI option is enabled in /setup.ps3
![image](https://user-images.githubusercontent.com/974897/162199187-c8aade59-c5cd-439e-83dc-f3e2c38a29d7.png)

Please provide more information about how to reproduce the error step-by-step.

**Comment by LouisGarry** [comment]
The game mounted before "Disable CFW syscalls", after "Disable CFW syscalls" the game can't be played (8001003A error)

**Comment by aldostools** [comment]
As I mentioned I would need more information.

I tested on my CFW Evilnat 4.88.2 and the game launched fine with the syscalls disabled (and PS3MAPI disabled too)

However if the FPS counter plugin is loaded, the system hanged with the CFW syscalls disabled.
That probably is an issue with the new FPS plugin by @TheRouletteBoi which now is calling peek/poke syscalls for the display of progress messages.

Does this happen only with 1.47.39? You or your friend need to do more tests so I can reproduce the exact error.
