### ISSUE TITLE
Wrong additional information displayed under game name in XMB

### ISSUE THREAD

**Issue by ozapft** [aldostools/webMAN-MOD#662]
Hello Aldo,

I've found the following bug.

In /setup.ps3
we can select the one of the following information which is additionally displayed in XMB under the game name.

None; ID; ID+Version; Path; Path+ID; Path+ID+Version

Result with ext. USB NTFS HDD and latest Webman MOD version:

None 		        **OK**
ID		               **NOK**   	BLES1784 | v01.06 | ntfs
ID+Version	       **NOK**	        BLES1784 | v01.06 | ntfs
Path		        **OK** 	        ntfs/PS3ISO
Path+ID		       **NOK** 	        ntfs/PS3ISO | BLES1784 | v01.06
Path+ID+Version	**OK**	        ntfs/PS3ISO | BLES1784 | v01.06

**Comment by aldostools** [comment]
Thank you for your feedback. A fix has been uploaded. Please update to check if it solves this issue.

**Comment by ozapft** [comment]
The issue is solved!
Thank you!
