### ISSUE TITLE
Retroarch 5200 Core 

### ISSUE THREAD

**Issue by southoz** [aldostools/webMAN-MOD#667]
Hi, @aldostools I am seeing some performance issues with the a5200 core vs the original Atari800 Core when configured for the Atari5200. When a game starts the core performance drops down to 1 to 2 fps.

https://www.youtube.com/watch?v=4MmdiWxDApE

Currently, ATARI800 directory is used for the Atari 800 Micro and maps to Atari800 roms, now that ATARI5200 is mapped to a5200 instead of Atari800 core there is no alternative for 5200 ROMs from within webMAN mod.

if(strcasestr(path, "/ROMS/ATARI5200/"))sprintf(path, "%s/a5200%s",			RETROARCH, sufix[i]);  else

Are you able to confirm that you see the same performance issue to confirm if there is a need for a second Atari 5200 path for mapping to the Atari800 core.

Thanks

**Comment by aldostools** [comment]
Thank you for your feedback. I read a report that a5200 core has some performance issues.

I updated PKGLAUNCH with a fallback to use atari800 core if a5200 core doesn't exists.
https://store.brewology.com/get/homebrew.php?id=310&fid=2183

As an alternative you can duplicate the atari800 core and rename it as a5200_libretro_ps3.SELF

**Comment by southoz** [comment]
Thanks, Aldo

Confirming deleting the a5200 core will result in:

ATARI800 and ATARI5200 will use the atari800 core and content directory settings will allow for both devices to be supported based on their directory.

If both cores are installed ATARI800 will use atari800 core and ATARI5200 will use a5200 core

```
			{
									 sprintf(path, "%s/atari800%s", RETROARCH, sufix[i]);
				if(not_exists(path)) sprintf(path, "%s/a5200%s",	RETROARCH, sufix[i]);
			}
			else
			if(strcasestr(path, "/ROMS/ATARI5200/"))
			{
									 sprintf(path, "%s/a5200%s",	RETROARCH, sufix[i]);
				if(not_exists(path)) sprintf(path, "%s/atari800%s", RETROARCH, sufix[i]);
			}
```

**Comment by southoz** [comment]
There is something not quite right with the flow, when launching the mounted Atari 5200 image after deleting the a5200 core webMAN mod is unable to launch retroarch with the provided values (no logging is started for level 0 on core and frontend).
I did a reinstall of webMAN and deleted the PKGLAUNCH folder and Atari800 core over rides to ensure it was not creating the issue. Loading the Core and Rom via the Retroarch Frontend is successful (after changing the core options to 5200)

**Comment by aldostools** [comment]
Try updating using the online updater on XMB and restart the system.

It looks like in the previous update I forgot to update one of the EBOOTs.
