### ISSUE TITLE
Check if FPS Counter is enabled via Boot_plugins

### ISSUE THREAD

**Issue by PS3-Pro** [aldostools/webMAN-MOD#668]
If the user already have the FPS counter plugin enabled via boot_plugins.txt and use the webMAN combo to enable it, it will have two instances of the same plugin.

Would be possible to webman check if other instance is running?

![image](https://user-images.githubusercontent.com/74815634/162589372-36c726c0-0869-4cb1-96ee-a130f0c0ee9b.png)

**Comment by PS3-Pro** [comment]
I Also noticed if tHe plugin is loaded by boot_plugins, when performing a XML scan will freeze the system ( not entirely) the fps counter will still work, but will show 0% FAN Speed and the others overlays still works. After mounting a game without launching it and going back to webman games all custom xmls will not show.

![image](https://user-images.githubusercontent.com/74815634/162589714-a8c54984-ff53-4915-9c94-458da3584bf7.png)

**Comment by PS3-Pro** [comment]
Just installed the new build and now Refreshing XMB and Mounting a game does not freezes anything when loaded via boot_plugins, but no webMAN notification will be passed to the plugin and it still freezes after using the combo R3 + L3 (e.g refresh xml).

Try this in your end, enable the plugin via boot_plugins, use the R3 + L3 combo and then refresh the XML ( i just tried this)

**Comment by aldostools** [comment]
Remove the VshFpsPlugin from boot_plugins. webMAN loads the plugin dynamically when the R3+L3 is pressed.

The progress messages are passed to the plugin only when it is activated through R3+L3.
There is an internal check that enable the message when webMAN detects that the plugin was loaded through the combo. This check is to prevent writing to LV2 without a purpose.

**Comment by PS3-Pro** [comment]
I'm just testing this way on my plugin manager XMBML menu to make it work if the user uninstall the webman or want it permanently enabled.

Anyway, there is no point to the user to use the combo if it is already enabled, it was just a test.

**Comment by aldostools** [comment]
I understand, but that's not the way the FPS was implemented in webMAN MOD.

The user can use the plugin from boot_plugins.txt but the progress notifications via LV2 are sent only when the plugin is enabled through the combo.
