### ISSUE TITLE
Trying to load VSH Menu, Unload webMAN or sLaunch Menu freezes console.

### ISSUE THREAD

**Issue by illusionalDEX** [aldostools/webMAN-MOD#669]
Lite edition works perfectly fine with the VSH Menu

**Comment by aldostools** [comment]
Thank you for the report. I will investigate. It looks it's related to the recent changes.

**Comment by aldostools** [comment]
Please use the XMB updater to install the fixed version.

The error was due a strstr function receiving a NULL variable without being verified.

**Comment by illusionalDEX** [comment]
> Please use the XMB updater to install the fixed version.
> 
> The error was due a strstr function receiving a NULL variable without being verified.

works good now

**Comment by aldostools** [comment]
Thank you again for your report 👍
