### ISSUE TITLE
PS3 Freezes mounting net0 games with Webman 1.47.39

### ISSUE THREAD

**Issue by Mrpink200** [aldostools/webMAN-MOD#670]
Hi guys.
I spent quite a bit of time troubleshooting my pb. With latest webman 1.47.39 and ps3netserv 20220330 on docker on synology nas, every single game i try to launch freezes the ps3 while mouting
Downgrading only webman to 1.47.38 solves the issue with same ps3netserv version ... 

Any idea ?
My games folders have no subfolders, 
![Capture](https://user-images.githubusercontent.com/7417251/162715570-e122306b-0261-41de-b057-67583a111d22.PNG)

**Comment by aldostools** [comment]
Please use the online updater in webMAN Games > webMAN Setup > Update webMAN MOD > Install, then reboot and report back if the issue was solved.

**Comment by aldostools** [comment]
Ok. I found the issue. Please update again using the method mentioned above or downloading the current package in [releases](https://github.com/aldostools/webMAN-MOD/releases) or [brewology](https://store.brewology.com/ahomebrew.php?brewid=310)

**Comment by Mrpink200** [comment]
I confirm the issue is solved making the liove update with your fix !!
manyt thx !!
