### ISSUE TITLE
PS3 Isos not showing in ps3 games 

### ISSUE THREAD

**Issue by jhonnyn5** [aldostools/webMAN-MOD#673]
Hi Aldostools
I have a problem with the latest version of webman.  It turns out that webman does not recognize ps3 games in ISO format on my external hard drive in NTFS.  
I've already tried everything, reinstall Webman and set everything to default, but nothing works.  Before you ask me: 
- My hard drive is a Toshiba 2tb with a 1.5 TB NTFS partition for the ps3 isos 
- Other apps like multiman and iris manager recognize the games perfectly.  
- In the webman file manager the games do not appear in the PS3ISO folder.  Please help me.

**Comment by aldostools** [comment]
The libntfs used in webMAN MOD is a fork from the one used in IRISMAN. It uses a reduced amount of memory due the limitations in VSH.

If I recall correctly, bguerville commented that a work around is to increase the cluster size.

Try using prepISO to scan the games. It uses the same libntfs used in IRISMAN. That tool provides additional features like support scanning packages in PKG folder or scan games in exFAT devices.

**Comment by jhonnyn5** [comment]
> The libntfs used in webMAN MOD is a fork from the one used in IRISMAN. It uses a reduced amount of memory due the limitations in VSH.
> 
> If I recall correctly, bguerville commented that a work around is to increase the cluster size.
> 
> Try using prepISO to scan the games. It uses the same libntfs used in IRISMAN. That tool provides additional features like support scanning packages in PKG folder or scan games in exFAT devices.

I did it, I tried with prepiso, but it's the same. in previous versions I had no problems with this.
I can't think of anything else to do to fix it.

**Comment by aldostools** [comment]
Try updating to the latest build using the online updater in webMAN Games > webMAN Setup > Update webMAN MOD > Install.

If that doesn't work, try with 1 or 2 previous versions of prepISO and webMAN MOD. And report back your results.

The idea is to isolate where is the issue. prepISO and IRISMAN should have the same NTFS compatibility.

**Comment by jhonnyn5** [comment]
> Try updating to the latest build using the online updater in webMAN Games > webMAN Setup > Update webMAN MOD > Install.
> 
> If that doesn't work, try with 1 or 2 previous versions of prepISO and webMAN MOD. And report back your results.
> 
> The idea is to isolate where is the issue. prepISO and IRISMAN should have the same NTFS compatibility.

Thanks 
Well after testing a bit with PrepISO.  I have been able to confirm that when I run it several times the games appear little by little, that is, I have about 50 games and they appear little by little about 10 when I run it 2 times and the list of games increases, it is very rare.  I already tried to update the list of games and the xmb with webman but this does not work.  The only way I can load the games is with the PrepISO running multiple times.  Is it normal for PrepISO to work like this?  Can't have all the games at once?

**Comment by aldostools** [comment]
No, it is not the normal behavior.

Could you test switching to Lite edition and scanning with prepISO?
Or go to /setup.ps3 and uncheck the option /dev_ntfs in the full edition, then save and scan.

If the behavior is the same. Try using an older version like [prepISO 1.26](https://github.com/aldostools/webMAN-MOD/releases/download/1.47.27/prepISO_1.26.pkg)

**Comment by jhonnyn5** [comment]
Well friend after a couple of tests, I think the fault is in the PrepISO.  Well, it turns out that I have 100 games on my hard drive and I don't know why PrepISO doesn't create the SFO and PNG files of all the games at once (That's why the games added up little by little after running it several times). times. And I think with this the error is solved. But what I didn't like is that this duplicates the game list in multiman and Iris manager because they both read the iso and the sfo file. There will be some way that webman read the ISO directly without needing the SFO file? Before webman could do it without using PrepISO. Or another solution would be to make multiman or iris manager stop showing duplicates and only read the SFOs.
Never needed prepISO cause evilant CFW cobra always read ps3 isos with no other plugin or app.

**Comment by aldostools** [comment]
@jhonnyn5 This is a pre-release of prepISO 1.30 which has removed the creation of SFO and PNG on the NTFS disk and uses the libntfs_ext.a taken from IRISMAN. Give your feedback.
[prepISO.zip](https://github.com/aldostools/webMAN-MOD/files/8485391/prepISO.zip)

**Comment by jhonnyn5** [comment]
> @jhonnyn5 This is a pre-release of prepISO 1.30 which has removed the creation of SFO and PNG on the NTFS disk and uses the libntfs_ext.a taken from IRISMAN. Give your feedback. Congratulations, friend!  This is exactly what I was looking for.  With this new PrepISO all 100 games are displayed right away.  I also don't see interference with multiman and Iris manager, you were right.  At the moment I can only thank you and if I see any problem I will let you know.  On the other hand I see that webman has a bug when using the game menu (L2 + R2) that makes the console freeze, but that has nothing to do with this new PrepISO and I guess it's another very separate bug.  Thank you aldostools

**Comment by jhonnyn5** [comment]
> > @jhonnyn5 This is a pre-release of prepISO 1.30 which has removed the creation of SFO and PNG on the NTFS disk and uses the libntfs_ext.a taken from IRISMAN. Give your feedback. Congratulations, friend!  

Congratulations, friend!  This is exactly what I was looking for.  With this new PrepISO all 100 games are displayed right away.  I also don't see interference with multiman and Iris manager, you were right.  At the moment I can only thank you and if I see any problem I will let you know.  On the other hand I see that webman has a bug when using the game menu (L2 + R2) that makes the console freeze, but that has nothing to do with this new PrepISO and I guess it's another very separate bug.  Thank you aldostools
