### ISSUE TITLE
FPS Counter Info does not work in game.

### ISSUE THREAD

**Issue by sandrojr1991** [aldostools/webMAN-MOD#674]
When launching a game the FPS counter information does not update, only when pressing PS Button.
The memory, fan speed, ram usage, system temperature are fixed. Only the FPS are working dynamically.
If the FPS Counter is enabled while already in-game Fan Speed and Sytem temperature is show as 0.

AFAIK akari works good in those situations.

**Comment by aldostools** [comment]
Thank you for your feedback. As this is a bug in FPS counter, maybe @TheRouletteBoi could check this bug.

**Comment by TheRouletteBoi** [comment]
> Thank you for your feedback. As this is a bug in FPS counter, maybe @TheRouletteBoi could check this bug.
> 
> BTW this issue happens also with the LV2 text overlay displayed at the right of the screen.

Aldo this issue and issue #665 has been resolved with the latest commits in the fps-counter branch. Are you able to build the project? If not I'll gladly do it for you.

**Comment by aldostools** [comment]
Thank you very much my dear friend! 😀👍

**Comment by aldostools** [comment]
@TheRouletteBoi I just tested the plugin and confirm that most of the issues have been resolved.

A couple of suggestions:
- I shows 4.88 CEX Cobra 0.00 when the syscalls are removed. Maybe you can make it show only "4.88 CEX" since Cobra is removed.
- The labels "Firmware:" and "App:" are redundant and can be removed. I already did it using an hex editor 😄 So this is not very important.

**Comment by sandrojr1991** [comment]
Glad that it's fixed, is there a way to disable some overlays, for example the firmware information and RAM usage?

**Comment by TheRouletteBoi** [comment]
> @TheRouletteBoi I just tested the plugin and confirm that most of the issues have been resolved.
> 
> A couple of cosmetic suggestions:
> 
> * It shows 4.88 CEX Cobra 0.00 when the syscalls are removed. Maybe you can make it show only "4.88 CEX" since Cobra is disabled.
> * The labels "Firmware:" and "App:" are redundant and can be removed. I already did it using an hex editor 😄 So this is not very important.

I can remove both of those labels but wouldn't it be good to have if a new user just came to the PS3 scene and it wondering what infomation that means?

**Comment by sandrojr1991** [comment]
I have a question, why the RAM usage is so low or is it the VSH memory? if so, why not show the current XDR ram and VRAM ?

**Comment by aldostools** [comment]
> I can remove both of those labels but wouldn't it be good to have if a new user just came to the PS3 scene and it wondering what infomation that means?

Remember that the users are already in HEN or CFW. It's pretty obvious that "4.84 DEX Cobra 8.20" or "4.88 CEX HEN 3.30" is the firmware version. Even if it is a new user, he/she will learn it shortly.

Same for "App:" it's also obvious that it the name of the game that is playing. The other need a label to explain the meaning.

Cobra 0.00 has no meaning unless it's explained in a documentation. Removing "Cobra 0.00" only when the CFW syscalls are  disabled would help to make the screen cleaner.

> I have a question, why the RAM usage is so low or is it the VSH memory? if so, why not show the current XDR ram and VRAM ?

That is the user memory. That is the information returned by the [LV2 syscall](https://www.psdevwiki.com/ps3/LV2_Functions_and_Syscalls) `sys_memory_get_user_memory_size` (352)
