### ISSUE TITLE
Special Charactes doesn't show on FPS Counter

### ISSUE THREAD

**Issue by PS3-Pro** [aldostools/webMAN-MOD#675]
Looks like special characters does not work with FPS counter eg: /popup.ps3@info9

![image](https://user-images.githubusercontent.com/74815634/163343563-e0a5d80a-838e-446f-a960-57743e4f8323.png)
![image](https://user-images.githubusercontent.com/74815634/163343928-a434fce2-7e24-4bc7-9435-dec3c93376b1.png)

**Comment by aldostools** [comment]
Thank you for your feedback. This seems to be an issue with the font used by FPS Counter.

As a workaround now I'm patching the message with proper characters. You can update with the online updater or redownload the installers from the release page or from breowlogy.
