### ISSUE TITLE
Console freezes after unloading webMAN

### ISSUE THREAD

**Issue by marsrp1** [aldostools/webMAN-MOD#676]
Hello
Today, I finally updated my PS3. It had 4.82.1 Rebug and webMAN MOD 1.47.06 and also PSN Patch
After update I'm on Evilnat 4.88.2, I installed webMAN MOD 1.47.39 and PSN Patch again.
Now, if I press R2+Triangle, syscalls get disabled, I get a popup from PSN Patch that PSN is enabled and I can log into PSN.
However, I remember back on 4.82 that people recommended to unload webMAN as well with R2+L3+R3 after disabling syscalls for more ban safety. And that did work flawlessly on 4.82. But after updating, when I try to do that, I see "Webman unloaded!" popup, the fan slows down and... the console freezes. Completely. I have to hold the power button for a bit so it shuts down.
I tried uninstalling and installing webMAN again, I removed PSN Patch plugin, but every single time I try to unload webman, it freezes. Aside from that everything is working fine, I can mount games and play them, go on PSN after disabling syscalls, etc. But unloading webman just, crashes.

Edit: Note, I have disabled the L3+R3 combo to load the FPS counter.

**Comment by aldostools** [comment]
Please try updating to 1.47.40 and report back if the issue is still present.
https://github.com/aldostools/webMAN-MOD/releases/tag/1.47.40

The unload of webMAN MOD was a requirement of PSN patch. 
It used the unload combo of webMAN to enable the PSN login.

The latest versions of webMAN MOD don't require PSN patch.
It unlocks the PSN login when the syscalls are disabled.

So far webMAN MOD is not a known source of banning. This could change at any moment if Sony decides it.
Playing games with at least syscalls 6/7 is risky, specially on CoD, GTAV games among others.

**Comment by marsrp1** [comment]
Huh, weird, I could've sworn I downloaded the latest release of webMAN. Oh well. I installed 1.47.40 but trying to unload still causes a freeze.
And well, if just for PSN webMAN is safe, then that's ok. But I wanted to play around with Artemis for some SP games and supposedly it needs to unload webMAN first.

**Comment by aldostools** [comment]
I'm also using Evilnat 4.88.2 and I can unload webMAN MOD without issues.

Please check your /dev_hdd0/boot_plugins.txt and make sure that only webMAN MOD is loaded.
Other plugins could be causing issues. Also make sure that "Disable scan for content at startup" is checked in /setup.ps3

The issue that you mention should be due the large memory footprint of wMM full/standard editions.
You can try loading Artemis with wMM Lite edition using L1+R1+△ or installing the lite edition directy with the installer.


<br class="Apple-interchange-newline">

**Comment by marsrp1** [comment]
I checked the plugins file, only webMAN MOD is there (at least I assume that's webMAN, /dev_hdd0/plugins/webftp_server.sprx)
I also went into settings and disabled the content scan at startup. Sadly, it's still freezing right after unloading webMAN.
Also, I did actually install the lite version.

EDIT: I just tried L1+R1+Triangle and the console froze, with the power LED flashing between green and yellow

**Comment by aldostools** [comment]
There should be something different in your system that is causing the freeze.

My console is also in Evilnat 4.88.2 with wMM 1.47.40 and it doesn't suffer the reported issues.

I wrote an troubleshooting article. I have a few suggestions including the ones that I already mentioned and others like try CFW reinstallation, try a clean reinstallation, try older versions, etc.
https://github.com/aldostools/webMAN-MOD/wiki#troubleshooting

**Comment by marsrp1** [comment]
Alright, I will try these steps tomorrow and report again if I find any of them fixing the issue.

**Comment by marsrp1** [comment]
Alright, I tried steps 1 and 3 (2 already tried, 4 is not my case, not using anything external), sadly they didn't do anything. The console still freezes.
I did however try one last thing. I uninstalled webMAN MOD, then installed 1.47.06 that I had on my previous CFW. Now this one works flawlessly, unloading without an issue.

**Comment by jhonnyn5** [comment]
It's true man. The new version 1.47.40 causes freezes as soon as it loads. Version 1.47.39 didn't have this problem. I also have CFW evilnat 4.88.2.
At the moment I returned to version 1.47.39

**Comment by aldostools** [comment]
@jhonnyn5 @marsrp1 I found a timing issue in the unload function. I made some changes to solve it.

Could you verify if the freeze still occurs? I made various tests and it is not freezing my console.
Use the online updater in webMAN Games > webMAN Setup > webMAN MOD Updater > Install

**Comment by marsrp1** [comment]
Sorry for the late reply, due to holidays was very busy.
I installed 1.47.40 pkg, installed webMAN MOD from it, then went to the updater and let it update. Sadly, the issue persists. Both on unload (with key combo, or from webMAN Setup) and when switching between full and lite (L1+R1+Triangle) the popup that webMAN is unloaded pops up and console freezes.

**Comment by aldostools** [comment]
@marsrp1 Thank you for your feedback. I wonder why it doesn't freeze on my console but it does on yours.

It's supposed that you have Evilnat 4.88.2 like I do.

Checking in the socat log of Cobra debug I notice that an exception generated in VSH, but my console continues running. If I remove the syscall SC_UNLOAD_PRX_MODULE it doesn't crash but the plugin remains in memory and eventually freezes after 2 or 3 switches.
````
# Lv-2 detected an interrupt(exception) in a user PPU Thread.
# Interrupt(exception) Info.
#   Type : Instruction Storage
#   SRR0 : 0x0000000000c6e570
#   SRR1 : 0x800000004000c032
#   DSISR: 0x0000000000200000
#   DAR  : 0x0000000060300400
#   TB   : 0x0000000159e9ffb6
#   HW Thread #: 1
# Continue... (Lv-2 is still running.)
````
I will continue investigating... I suspect of NTFS library but I need to check.

**Comment by jhonnyn5** [comment]
> @jhonnyn5 @marsrp1 I found a timing issue in the unload function. I made some changes to solve it.
> 
> Could you verify if the freeze still occurs? I made various tests and it is not freezing my console. Use the online updater in webMAN Games > webMAN Setup > webMAN MOD Updater > Install

Sorry for the late reply I've been a bit busy plus I went back to the previous version of webman and had to reinstall it.  I can confirm that the error is still there.

**Comment by aldostools** [comment]
Thank you @jhonnyn5 for your feedback. I'll post back if I find a solution.

**Comment by aldostools** [comment]
I have uploaded a new build that does not call the syscall SC_UNLOAD_MODULE_PRX unloading with R2+L3+R3.
All other unload methods use that syscall. It seems to be the cause of the freezes on your system.

For some reason my console does not freeze unloading with that syscall. I suppose you're testing with CFW syscall disabled or doing something different

I hope that the new build help to improve your experience with 1.47.40.

**Comment by marsrp1** [comment]
Alright, this now works on my side to unload webMAN. Not to switch between full and lite mode however, still freezes in that case.
I don't know why it could possibly freeze on my specific console. I am also on Evilnat 4.88.2 and I tried unloading it both with and without disabling syscalls beforehand (on .06 both worked) and it was freezing.
Currently, my test procedure is as follows: (re)boot console, when in XMB press R2+L3+R3 OR L1+R1+Triangle. That's it. I don't unload syscalls beforehand or anything.
I guess the one last thing to try, which I will do tomorrow, I will download every version of webMAN between .06 and .40 and see on which one this breaks.

Edit: One more small thing, I know that by then webMAN is unloaded so of course it doesn't work, but once it's gone, the webMAN Games menu is still in XMB. Going into it and trying to load a game ends with a console freeze. I think previous versions just threw an error there.

**Comment by aldostools** [comment]
Don't need to download all versions. The freeze is due the SC_UNLOAD_MODULE_PRX added recently to free the memory used by the plugin when it unloads.

Do you have QA flags enabled? If not, maybe that could be a difference. I have mine enabled.
I have tested on 2 PS3 slim models CECH-200x and CECH-210x. None of them freeze.

**Comment by aldostools** [comment]
I uploaded new build to solve the freeze when the webMAN menu is accessed with the plugin unloaded.

**Comment by marsrp1** [comment]
I'm fairly sure I do not have QA flags enabled. How do I enable them and are there any downsides? (like losing profiles/saves or inability to go on PSN)
As for the console itself, I am on a FAT PS3, sticker says CECHG03

**Comment by aldostools** [comment]
QA flags are safe to enable and indeed they are recommended due it allows to upgrade/downgrade to any version.
It also allows to install PUP from internal HDD /dev_hdd0/updater/01 or use the QA Flag Menu (check the link below)
https://www.psdevwiki.com/ps3/Button_Combos#QA

To enable QA flag is simple: There is an option in CFW Tools menu under the Network column of Evilnat 4.88.2
Also Rebug Toolbox allows to enable QA flags if you prefer it.

**Comment by marsrp1** [comment]
Well what do you know, apparently I had QA flags enabled, so that wasn't it. However, since now I know that it's active, is there any way for me to get a dump from when the console freezes? Perhaps that would be helpful to you to pinpoint what exactly causes it?
Currently unloading works, but the L1+R1+Triangle still freezes.

**Comment by aldostools** [comment]
For L1+R1+△, I could skip the call of SC_UNLOAD_PRX_MODULE (483). The plugin will switch but the previous plugin will stay in memory consuming resources. If you switch back again to full ediion the free VSH memory will be minimal and the system will crash anyway.

Here is a test build that don't call SC_UNLOAD_PRX_MODULE (483) when you quit with any method.
[webMAN_MOD_latest.zip](https://github.com/aldostools/webMAN-MOD/files/8506527/webMAN_MOD_latest.zip)

To catch the error you need to enable Cobra debug mode in Network column > Custom Firmware Tools > Cobra Tools > Toggle Cobra Version

You need to use [socat](https://sourceforge.net/projects/unix-utils/files/socat/1.7.3.2/) from a batch file or command prompt to capture the output.

`socat -lu stdout udp-recv:18194,reuseaddr |tee stdout.txt`

Here is the socat folder that I use [socat_win.zip](https://github.com/aldostools/webMAN-MOD/files/8506655/socat_win.zip)

**Comment by marsrp1** [comment]
Alright, I ran it, then tried to switch between Lite and Full versions, this is the debug log:
https://pastebin.com/tGeCqnfR

EDIT: Also, I checked, sadly /dev_hdd0/crash_report/vsh/ps3crash-vsh.dat does not exist after rebooting the console

**Comment by aldostools** [comment]
In the log there is a `# Lv-2 detected an interrupt(exception) in a user PPU Thread.` caused by poll_thread.
That is the thread that read the combos.

The error is caused by SC_UNLOAD_MODULE_PRX which was added to force that the free memory when the plugin is unloaded. I'm investigating other alternatives, but I'm almost running out of options. I expended almost all the weekend trying to fix issue,

Try the test build that I posted above. It should not cause the crash in VSH.

**Comment by marsrp1** [comment]
It's interesting that it causes a crash on some consoles (on the forums I saw someone else say that it was crashing on unload) and on others it works. I'm not sure if the one you uploaded just above is necessary, unloading works and that was what I needed the most, while switching without freeing memory will eventually just, not do what intended. If I end up using Artemis I can just install the lite version instead.

**Comment by aldostools** [comment]
I managed to unload webMAN using SC_UNLOAD_MODULE_PRX  without the crash.
You can update using the online updater and test this [new build](https://github.com/aldostools/webMAN-MOD/releases/download/1.47.40/webMAN_MOD_1.47.40_Installer.pkg).

**Comment by marsrp1** [comment]
Well, if the FPS plugin is to be believed with RAM usage, this is now working perfectly! Switching between Lite and Full doesn't crash the console and memory usage changes accordingly. Unloading webMAN just as well decreases memory usage, showing that it is indeed unloaded.
As far as I am concerned, this issue can absolutely be closed.

**Comment by aldostools** [comment]
@marsrp1 Thank you for your feedback. I'm closing the case.
