### ISSUE TITLE
Small White line in XMB Screenshots

### ISSUE THREAD

**Issue by PS3-Pro** [aldostools/webMAN-MOD#677]
There is a small white line at the top of the screenshots

![image](https://user-images.githubusercontent.com/74815634/163668610-ccc514f9-3af9-400a-88b1-196c10e4f825.png)

**Comment by aldostools** [comment]
Which plugin are you using to capture the screen? vsh menu or webftp_server?
Are you using an older version? This issue was fixed weeks ago.

Please try using the online updater to install the latest build and report if the issue is fixed.

**Comment by aldostools** [comment]
I captured this screen using wMM 1.47.40. As you can see, it doesn't have the white line.

I used this command http://10.0.0.8/xmb.ps3$screenshot?show  (10.0.0.8 is the IP of my PS3)
![image](https://user-images.githubusercontent.com/974897/163670448-3c1752e0-8dee-45d0-893b-783977c39b24.png)

**Comment by PS3-Pro** [comment]
My bad Aldo 😝  , seems like i ftp'd my old plugins backup when installing the VshFpsCounter v3 😶‍🌫️ .

Maybe i should go to sleep :P
It's 8 am here and I still haven't slept.
