### ISSUE TITLE
Extended Content Profiles - ROMS

### ISSUE THREAD

**Issue by lmipsum** [aldostools/webMAN-MOD#678]
The Content Profile scans ignores the default ROMS folder, they are scanning fine the ROMS folder associated to the active content profile, e.g. scan 3 is scanning everything in ROMS_3, but exclude the content of the ROMS completely.
Expected behavior:
Scan(3) is scanning everything in ROMS and ROMS_3 folders, Scan(2) is scanning everything in ROMS and ROMS_2 folders, and so on. So we can have shared games on multiple profiles without creating duplicates of files.
What happens right now:
Scan(3) is scanning everything in ROMS_3 folder, Scan(2) is scanning everything in ROMS_2 folders, and so on, but the ROMS folder is ignored.

**Comment by lmipsum** [comment]
also i think it would be better if the default scan would serve as a master profile, that lists all contents of each content profiles too.
lets say i want to share X (GAMES) and Y (GAMES_1) games with profile 1, and X (GAMES) and Z (GAMES_2) games with profile 2.
i dont want profile 1 see Z games, and i dont want profile 2 see Y games.
but the i want the default profile see X (GAMES), Y (GAMES_1), and Z (GAMES_2) games too.
currently the default profile see only the GAMES folder.

**Comment by aldostools** [comment]
The profiles works like this:
default profile = shows GAMES, PS3ISO, etc. (common to all profiles)
profile 1 = shows (GAMES_1 + GAMES), (PS3ISO_1 + PS3ISO)
profile 2 = shows (GAMES_2 + GAMES), (PS3ISO_2 + PS3ISO)

The idea is to hide certain content from other profiles. I could add an option to list the content of all the profiles too.
I would have to add this to my long to-do list.

The case of the ROMS is more difficult, because currently PKGLAUNCH searches for "/ROMS/". It would require big changes too.

**Comment by aldostools** [comment]
A new build has been submitted with the requested changes included. You can use the online updater or download the installer from the release page or brewology.

**Comment by lmipsum** [comment]
Thank you!

**Comment by lmipsum** [comment]
I've reinstalled webman mod with the latest release.
I can confirm the default ROMS folder is also scanned for each profiles, and ROMS_1, ROMS_2, etc is also scanned with the associated profile. SELECT+L3 scans only the default ROMS. So it's working with the ROMS now just like any other content scans was working before!

I'm using the default folders (GAMES,PS3ISO,PSP,PSXISO,ROMS), I have also contents for profile 1 and profile 2, no folders for profile 3 and 4. This is what's happening:

**SELECT+L3, SELECT+L3+L1+R1** (default scan)
Expectation:
Scans the default folders only OR Scans default folders + all contents of each profiles.
Result:
Scans the default folders + PS3ISO_1 (from NTFS only, excludes PS3ISO_1 from FAT32)

**SELECT+L3+R2** (profile 1)
Expectation:
Scans default folders + all contents of profile 1
Result:
Scans default folders + all contents of profile 1

**SELECT+L3+L2** (profile 2)
Expectation:
Scans default folders + all contents of profile 2
Result:
Scans default folders + all contents of profile 2 + PS3ISO_1 (from NTFS only, excludes PS3ISO_1 from FAT32)

I don't have PS3ISO_2 on NTFS, maybe that would be added to the default folders too, didn't test that. **If I didn't have content profile on NTFS, probably it would give the expected results tho**, so it isn't a big deal, I can just reorganize the folders a bit.

**I couldn't test the "master profile"** to scan the contents of all profiles with \*. I've tried to switch with /index.ps3?\*, /index.ps3?usr=\*, /index.ps3?5, /index.ps3?usr=5 on the web interface, none of them worked. not sure about the controller button press combo either for it.

**Comment by aldostools** [comment]
Thank you for your feedback. The parameter ?usr=5  or ?5 was not supported until now. 
A new build is available online with the fix.

I tested the user profile selecting it in /setup.ps3 then saving the settings.

The master profile '*' is not supported through combos.

**Comment by aldostools** [comment]
BTW exFAT/NTFS games are cached to /dev_hdd0/tmp/wmtmp it looks like the content filter is not considering that folder or the file does not have enough information to identify the profile. I'll have to investigate. Not a priority now.

**Comment by lmipsum** [comment]
Thank you, the profile 5 is now working perfectly, listing everything!
