### ISSUE TITLE
Limited Fan Control

### ISSUE THREAD

**Issue by ferrari00234** [aldostools/webMAN-MOD#682]
CECHA01 running Evilnat 4.88.2.

It appears that there is something interfering/overwriting webMAN's fan control. I have my dynamic fan control set to 65. While idling in XMB it usually achieves this at around 25%-27%. However recently, usually around 10 min or so after booting up, the fan will kick up to 30%. Temps will drop into the 50's but no change in fan speed. 

You can kind of hear the fan starting to ramp down, but then it picks back up again, like something is forcing it to maintain 30%.

Not sure where to start. First noticed this after exiting a PS2 game and the fan would not ramp down. Ever since it's been an ongoing/intermittent issue.

**Comment by aldostools** [comment]
Check Evilnat's fan settings... Cobra 8.3 has an integrated fan control. If it is enabled it can interfere with webMAN's fan control in manual mode like PS2.

**Comment by ferrari00234** [comment]
> Check Evilnat's fan settings... Cobra 8.3 has an integrated fan control. If it is enabled it can interfere with webMAN's fan control in manual mode like PS2.

Appreciate the response!

Even if I go in and manually disable Cobra's fan control it doesn't seem to affect the fan speed. Still stuck at 30% despite temps being in the mid 50's.

Reboot doesn't fix it, but disconnecting the power supply will fix it temporarily. I'm thinking it may be connected to SYSCON somehow.

**Comment by aldostools** [comment]
Just in case, verify that boot_plugins.txt only have once instance of webftp_server.sprx

It's not likely but it could be another source of conflicts. Also try setting the manual fan speed to 50% in /setup.ps3
You should hear the fan speed increase even before launch PS2.

**Comment by ferrari00234** [comment]
> Just in case, verify that boot_plugins.txt only have once instance of webftp_server.sprx
> 
> It's not likely but it could be another source of conflicts. Also try setting the manual fan speed to 50% in /setup.ps3 You should hear the fan speed increase even before launch PS2.

Just checked and there is only one instance of webftp in boot plugins.

I have no issue setting a manual fan speed that is over 28% (Sometimes 30%), only under. For example if I set the manual fan speed to 25% it will show 25% in the CPU/RSX screen on the web server but it’s actually at 28%
![B822D523-A5F3-4F8A-AD6A-0C3709FFC04E](https://user-images.githubusercontent.com/67337016/164734543-d23a955c-2e84-4029-bc7a-5479363bb4f5.jpeg)

**Comment by aldostools** [comment]
Try setting both fan speeds (manual & ps2 to 50% or 60% & 30% respectively) and boot a PS2 game.

That is to verify if manual fan speed is taking precedence over PS2 fan speed.

**Comment by ferrari00234** [comment]
> Try setting both fan speeds (manual & ps2 to 50% or 60% & 30% respectively) and boot a PS2 game.
> 
> That is to verify if manual fan speed is taking precedence over PS2 fan speed.

I can confirm that if the manual fan setting is 50% and the ps2 fan setting is 30%, when I boot up a ps2 game from webman the fan changes to 30%. 

however if I set the ps2 fan speed to 20%, when I boot up a ps2 game the fan goes from 50% to 28%. It’s like there’s something external preventing the fan speed from going that low.

**Comment by aldostools** [comment]
If it is something external, then unfortunately I cannot help much since it doesn't look like a webMAN MOD's issue.

**Comment by ferrari00234** [comment]
> If it is something external, then unfortunately I cannot help much since it doesn't look like a webMAN MOD's issue.

Ok thank you, I think I may have an idea as to the cause, I think the south bridge chip may be getting too hot and causing the system to heat up and up the fan speeds. This may be due to the cooling holes I drilled in the case. It cools the cpu and rsx very well but the south bridge may be getting insufficient cooling due to the different airflow. If I cover up the cooling holes, set the fan manually to 60% for 10 min and allow the system to cool, I can get the fan down to 20%. Looks like it is thermal related and not software related!

Im assuming webman doesn’t account for the south bridge chip temp in calculating dynamic fan curves?
![CCA4DA66-5B14-46E0-AFD7-E6C6BA796F85](https://user-images.githubusercontent.com/67337016/164778851-c540004f-936d-4915-bda0-190c506e6fcf.jpeg)

**Comment by aldostools** [comment]
webMAN only uses CPU / RSX temperatures to manage the dynamic fan control.
For manual speed mode or PS2 mode the fan speed are set to a constant value each mode.
