### ISSUE TITLE
[1.47.40] Settings don't save

### ISSUE THREAD

**Issue by FPSUsername** [aldostools/webMAN-MOD#685]
I just updated from 1.47.37 to 1.47.40 and wanted to change the fan settings.
Pressing on the save button does nothing, not on the ps3 nor in the browser.

In my browser I see these errors once I press on the save button:
```
sman.ps3:1 Uncaught (in promise) Error: The message port closed before a response was received.
sman.ps3:80 Uncaught ReferenceError: fc is not defined
    at HTMLInputElement.onchange (sman.ps3:80:5244)
    onchange | @ | sman.ps3:80
```

And some others when I click on refresh:
```
Uncaught TypeError: Cannot set properties of null (setting 'value')
    at refresh.ps3?xmb;/sman.ps3:80:432
    (anonymous) | @ | refresh.ps3?xmb;/sman.ps3:80
```

**Comment by aldostools** [comment]
Try using the online updater. Reboot and try again. If the error persists, please report the error message.

**Comment by FPSUsername** [comment]
That seems to work. I updated it by package first, will use the online updater from now on.
