### ISSUE TITLE
Request some notification

### ISSUE THREAD

**Issue by LouisGarry** [aldostools/webMAN-MOD#687]
Hi Aldo, thanks for your hard work.

If you have time, maybe you can add a notification for PS3 HEN when loading a ISO PS3, a notification will appear "HEN does not support ISO PS2, please encrypted" and wMM cancels mounting.

The second one is for DEX CFW, when it loads encrypt PS2 a notification will appear "DEX does not support encrypt PS2" and wMM cancels mounting.

Thank you.

**Comment by PS3-Pro** [comment]
AFAIK DEX supports encrypted ISO but it needs to be DEX signed, but i like the HEN idea

**Comment by aldostools** [comment]
Joonie posted [in this this thread at PSX-PLACE](https://www.psx-place.com/threads/ps2-classic-why-get-a-black-screen-in-the-dex.3242/#post-25674)
>I had no success on running PS2 classic [ENC] while on DEX mode, even with dex's meta/data keys for the conversion.
>
>However, I patched sb_iso_spu_module.self inside CoreOS of REBUG 4.75.X to allow CEX's VME while on DEX mode due to the compatibility concern for the launcher method for PS2ISO, so using DEX's key for conversion won't really solve the problem.
>
>Basically I swapped all three DEX keys with CEX ones, so CEX's encrypted files would work with DEX mode.

From that post, I understand that Rebug in DEX mode can play PS2 classics encrypted with CEX keys.
The PS2 disc images encrypted with DEX keys don't work on DEX mode.

**Comment by LouisGarry** [comment]
Thanks Aldo
