### ISSUE TITLE
webMAN 1.47.01 small issue

### ISSUE THREAD

**Issue by Haker120** [aldostools/webMAN-MOD#69]
Now at last almost everything works very well, just I found small issue. Auto-Play doesn't work. This is a small issue but I had to report. :)

**Comment by aldostools** [comment]
Thank you for your report... I have tested the feature again, and it's working on my system.

Please make sure that you have Auto-Play enabled on /setup.ps3 and save the settings.

By the way, 1.47.01 has a new behavior for Auto-Play:
- If Auto-Play is checked, the disc icon is selected & launched if the game is mounted from XMB
- If Auto-Play is unchecked and PLAY DISC is checked, the disc icon gets the focus but not launched.
- If Auto-Play and PLAY DISC are unchecked, the disc is mounted without additional steps.

**Comment by Haker120** [comment]
Thanks! :D
