### ISSUE TITLE
webMAN doesn't show PS3 Games

### ISSUE THREAD

**Issue by imdambrosio** [aldostools/webMAN-MOD#690]
PS3 Info: evilnat 4.88.2 cobra 8.3
webMAN: Latest version, updated via integrated updater

Hi, I'm using a RPi with psx-pi-smbshare image and a 300GB FAT32 HDD.
I have a PS3 game in Folder format, another in splitted iso format and a PSX game.
WebMAN doesn't show any PS3 Game and only shows the last two discs images of the PSX games.
MultiMAN shows all the games except the splitted one. I'm saying this only to clearify that the PS3 connects to the RPi succesfully.
PS3 Folder Game is in GAMES folder (F:\GAMES\BLESXXXX)
PS3 splited iso is in PS3ISO folder (F:\PS3ISO\XXXXX.iso.0-XXXXX.iso.1-etc.)
PSX BIN/CUE are in PSXISO folder.

Thank you for all your work,

Kevin S. D'Ambrosio

**Comment by aldostools** [comment]
Thank you for your comments. Please update again using the online updater and refresh the XML & reload XMB.
NOTE: The pkg is updated frequently. Sometimes up to 4-5 times a day.

if the error persists, please check in /setup.ps3 that you have enabled the content scanning for PS3.
Or try deleting /dev_hdd0/tmp/wm_config.bin, reboot and re-scan the content.

Report back if that doesn't fix the issue.

**Comment by imdambrosio** [comment]
Hi, thank you for your answer. Unfortunately that didn't work.

I've done everything you have said and it still the same. I have tried also a 32GB NTFS with the same games and the result is the same. It's strange, because if I go to the file manager, access to net server files, webMAN doesn't show the first disk image of the PSX Game neither the GAMES folder.

Thanks for your time,

Kevin S. D'Ambrosio

EDIT: A PS3 ISO works fine. It seems the problem are with splitted isos and folder format.

**Comment by aldostools** [comment]
If you're using ps3netsrv to access the games, try using [ps3netsrv_20220421.zip](https://github.com/aldostools/webMAN-MOD/releases/download/1.47.40/ps3netsrv_20220421.zip)
You will need to compile the program for your OS.

This binary is already compiled for linux, just in case your linux is compatible with ubuntu 20.04.4 LTS (64bit)
https://github.com/aldostools/webMAN-MOD/tree/master/_Projects_/ps3netsrv/bins/Linux

If the games still don't show, check if they can show attaching the USB drive to the PS3 or copying it to the internal HDD.

**Comment by imdambrosio** [comment]
Both drives (the HDD and USB) aren't being detected by webMAN fi they're plugged. The first one is in FAT32 and the second one in NTFS, but all the games display with the last version of ps3netsrv. So I suppose that the image I've got in my RPi is outdated and that's the problem.

Thank you very much.
