### ISSUE TITLE
[IDEA] Notification while the same operation is still in progress

### ISSUE THREAD

**Issue by PS3-Pro** [aldostools/webMAN-MOD#691]
Aldo, I twice clicked on the Refresh XML icon and I didn't notice the notification because I was distracted, so i clicked repeatedly and nothing happened because it is already being executed, the notification only appeared when the process was done.

Can webman show a notification when the action is being performed and the user tries to execute it again? Something like, The operation is already in progress.

Other thing is, what is the (3) on the Refresh XML notification?

![image](https://user-images.githubusercontent.com/74815634/166146932-65b3d501-a6bd-4138-a623-79dc78cf8773.png)

**Comment by aldostools** [comment]
The new build 1.47.41 now shows a count of how many games have been scanned when SELECT+L3 is pressed again.

The total count of games found is shown in the popup notification when the scan is done.
