### ISSUE TITLE
[Lack of memory?] Write command on big documents

### ISSUE THREAD

**Issue by PS3-Pro** [aldostools/webMAN-MOD#693]
Aldo, i'm using the /write.ps3 web command just fine, but only on category_psn.xml it doest work past line#2

Works: /write.ps3/dev_blind/vsh/resource/explore/xmb/category_psn.xml&t=test&line=1
Don't work : /write.ps3/dev_blind/vsh/resource/explore/xmb/category_psn.xml&t=test2&line=2

could it be due to this xml having more than 1000 lines?

**Comment by LuanTeles** [comment]
Seems like rename.ps3 is not working

/rename.ps3/dev_hdd0/game/PS34KPROX/USRDIR/toolbox/extras/unofficial_stores.xml&to=/rename.ps3/dev_hdd0/game/PS34KPROX/USRDIR/toolbox/extras/unofficial_stores.off

and the web page does not show anything

![image](https://user-images.githubusercontent.com/74815634/166393188-b3eaac05-c45b-443e-bb45-fbf97cdc0ea3.png)

**Comment by aldostools** [comment]
The first issue seems to be that your system is unable to allocate 128KB. I'm updating the code to use 64KB if the file size is smaller than 64KB.

~~About the 2nd issue, remove the second /rename.ps3 from &to=~~

**Comment by aldostools** [comment]
The fix for /write.ps3 is now available in the online updater.

**Comment by PS3-Pro** [comment]
Thank you, it fixed my problem.
