### ISSUE TITLE
[Question] /pad.ps3? on japonese consoles

### ISSUE THREAD

**Issue by PS3-Pro** [aldostools/webMAN-MOD#697]
Aldo, is there a way to use /pad.ps3? to perform enter/back action regardless of PS3 button layout?

Let's say you create a shortcut/script to run /pad.ps3?cross and it works perfectly on non-Asian consoles but not on Asian consoles as the cross is not "enter", it is "back" on these models.

can a command  like /pad.ps3?enter/confirm and  /pad.ps3?back be created? so it first checks the console layout on xRegistry.sys and determines if it will emulate the cross or circle button

**Comment by aldostools** [comment]
The following commands were added:
/pad.ps3?accept
/pad.ps3?cancel
