### ISSUE TITLE
[Feature Request] Download Folder in the Context Menu

### ISSUE THREAD

**Issue by PS3-Pro** [aldostools/webMAN-MOD#699]
Aldo, I know files can be downloaded, but how about to download a entire folder ? can a download folder be added from the context menu ?

![image](https://user-images.githubusercontent.com/74815634/166867545-0ced7a1d-2d3e-4677-81aa-fb735b968e1c.png)

**Comment by aldostools** [comment]
'Open' already downloads the file or open the folder. Also the default link outside the context menu does that.

The browser only can download files, not folder structures.
To download a complete folder, it would require a process that backup the whole folder in a single file (e.g. a zip or iso)
