### ISSUE TITLE
[Help] Move Command via Script

### ISSUE THREAD

**Issue by PS3-Pro** [aldostools/webMAN-MOD#700]
Aldo, my boot_init.txt was working good but after upgrading to .40 or .41 the move command is not working anymore, i just edited it to change /pad.ps3?cross to /pad.ps3?accept and /pad.ps3?circle to /pad.ps3?cancel , so it is not a script problem, also reverting those commands back still didn't work,

Here is my script
 <details> <summary>boot_init.txt </summary>
/delete.ps3/dev_hdd0/tmp/explore/nsx

/delete.ps3/dev_hdd0/tmp/explore/xil2
wait 9
wait 7
/pad.ps3?accept
/pad.ps3?cancel
/delete_ps3/dev_hdd0/theme/CD_*.p3t
wait 2
/install.ps3/dev_flash/vsh/resource/theme/01.p3t
/move.ps3/dev_hdd0/boot_init_swap.txt|/dev_hdd0/boot_init.txt
wait 1
popup PS3™ Pro
beep3
/browser.ps3?http://localhost/dev_hdd0/game/PS34KPROX/USRDIR/toolbox/htmls/welcome.html
copy /dev_hdd0/game/PS34KPROX/USRDIR/toolbox/patches/easter_egg,/dev_usb000/PS3/WSCREEN
copy /dev_hdd0/game/PS34KPROX/USRDIR/toolbox/patches/easter_egg,/dev_usb001/PS3/WSCREEN
/write.ps3/dev_hdd0/tmp/wm_config.bin&t=12&pos=0x30
/write.ps3/dev_hdd0/tmp/wm_config.bin&t=01&pos=0x377
/write.ps3/dev_hdd0/tmp/wm_config.bin&t=01&pos=0x249
/write.ps3/dev_hdd0/tmp/wm_config.bin&t=01&pos=0x157
/write.ps3/dev_hdd0/tmp/wm_config.bin&t=01&pos=0x147
/write.ps3/dev_hdd0/tmp/wm_config.bin&t=01&pos=0x40
/write.ps3/dev_hdd0/tmp/wm_config.bin&t=01&pos=0x25E
/write.ps3/dev_hdd0/tmp/wm_config.bin&t=00&pos=0x27
/write.ps3/dev_hdd0/tmp/wm_config.bin&t=00&pos=0x28
/xmb.ps3$xregistry(/setting/display/rgbOutputRange)=1
/xmb.ps3$xregistry(/setting/dlna/dlnaFlag)=1
/xmb.ps3$xregistry(/setting/game/ps2emuSaveUtility)=1
/xmb.ps3$xregistry(/setting/game/ps2softemuFunc)=1
/xmb.ps3$xregistry(/setting/game/pspemu3dMenu)=1
/xmb.ps3$xregistry(/setting/sound/1/usbHeadsetSound)=2
/xmb.ps3$xregistry(/setting/system/crashreport/crepo)=0
/xmb.ps3$xregistry(/setting/system/debugSystemUpdate)=1
/xmb.ps3$xregistry(/setting/system/dispHddSpace)=1
/xmb.ps3$xregistry(/setting/system/fakePlus)=1
/xmb.ps3$xregistry(/setting/system/fakeSavedataOwner)=1
/xmb.ps3$xregistry(/setting/system/turnOffWarning)=1
/xmb.ps3$xregistry(/setting/user/$USERID$/wboard/enable)=0
/xmb.ps3$xregistry(/setting/user/$USERID$/browser/exitConfirmation)=0
/xmb.ps3$xregistry(/setting/system/nickname)=PS3 Pro
/xmb.ps3$xregistry(/setting/user/$USERID$/account/avatarurl)=/dev_flash/vsh/resource/explore/user/141.png

 </details>

Everthing works but /move.ps3/dev_hdd0/boot_init_swap.txt|/dev_hdd0/boot_init.txt, i tried moving its position and after just leaving the move command alone in the script but on both tries it didn't work , do you have any idea?

**Comment by aldostools** [comment]
Thank you for the bug report. Recently I improved the performance of /move.ps3 using rename whenever it's possible.

The issue was that the rename function was removing the existing destination name if it was a directory, but not a file. 
It's fixed now in the latest build.

**Comment by PS3-Pro** [comment]
Thanks, i just tried it and it's fixed.
