### ISSUE TITLE
[Information] How to use IF in script

### ISSUE THREAD

**Issue by PS3-Pro** [aldostools/webMAN-MOD#701]
Aldo, can you give some examples about how to use the IF command?

Is it right?
![image](https://user-images.githubusercontent.com/74815634/167235507-49f85fdb-2462-4b51-82f3-3ecd71c44b34.png)

**Comment by aldostools** [comment]
It is like the code above, but the commands to be executed if the condition is true go in the next lines . It can be one or more lines.

I didn't test the following example. But it should give you the idea.
````
if exists /dev_usb000
  /copy. ps3/dev_hdd0/xxx|/dev_usb000/yyy
  beep1
elseif exists /dev_usb001
  /copy. ps3/dev_hdd0/xxx|/dev_usb001/yyy
  beep2
else
  beep3
end if

**Comment by PS3-Pro** [comment]
Thank you Aldo, i got it working
