### ISSUE TITLE
Temperature Chart Bug?

### ISSUE THREAD

**Issue by robastala** [aldostools/webMAN-MOD#704]
I just updated to 1.47.41 and the temp chart accessed via the configuration does not work anymore. The result from the page (cpursx.html) is: 15">

At the moment it was my main concern so this is the only thing I check after updating. I went back to 1.47.37 for now.

PS3 Slim
CFW Rebug v486.1 LITE

**Comment by aldostools** [comment]
Thank you for the bug report. The issue has been fixed in the build currently online.
