### ISSUE TITLE
[Command Bug] Downloader/Installer

### ISSUE THREAD

**Issue by PS3-Pro** [aldostools/webMAN-MOD#707]
Aldo, i already reported you this bug last year, but it still bothers me :P

My theme downloader uses this command

/download.ps3?to=/dev_hdd0/downloads/theme&url=https://raw.githubusercontent.com/LuanTeles/Themes/main/files/Okami_Dynamic_Theme_..p3t;/popup.ps3?The theme will be automatically applied, please wait...&snd=1;/wait.ps3?10;/install.ps3/dev_hdd0/downloads/theme/Okami_Dynamic_Theme_..p3t

It works as intended, but only as long as the XMB is not reloaded, I can use several of these commands in the session, but if I reload the xmb, it no longer works and requires me to restart the system.

**Comment by aldostools** [comment]
This issue is fixed in the latest build.
