### ISSUE TITLE
[Bug] Move Operation Deleting file if Source does not exists

### ISSUE THREAD

**Issue by PS3-Pro** [aldostools/webMAN-MOD#709]
Aldo i found a bug in the move operation

Here is my command:

/xmb.ps3$close_list;/xmb.ps3$close_list;/xmb.ps3$close_list;/xmb.ps3$open_list;/copy.ps3/dev_hdd0/game/PS34KPROX/USRDIR/toolbox/icons/on.png&to=/dev_hdd0/game/PS34KPROX/USRDIR/toolbox/icons/plugins_icons/plugin_12.png;/move.ps3/dev_hdd0/plugins/fps_counter.off&to=/dev_hdd0/plugins/fps_counter.sprx;/loadprx.ps3/dev_hdd0/plugins/fps_counter.sprx

This option is to enable the plugin, as it is already enabled in my end, the .off file does not exists, but the move operation is now deleting the destination file, as the off is null.

**Comment by aldostools** [comment]
Thank you fro the bug report. Please try with the latest build 4c59cd0d0ed28903b4123ac71f13ac57ded999a7 available online.

**Comment by PS3-Pro** [comment]
Thanks Aldo, it's fixed now.

Aldo i noticed now, that if the plugin is already loaded and the loadprx.ps3 is performanced again, it will act like a unloadprx.ps3, is it intentional? (isn't better to do nothing??

Other thing, can you please add silent copy/move operations ?

See here

https://www.youtube.com/watch?v=NTpaEQTYL0s

It shows a lot of notifications and if I enable another feature one after another, the notifications became annoying,

**Comment by aldostools** [comment]
Check again with the latest build... now the popup messages appear only on single commands.

Multi-commands (URLs separated by semi-colon) now work in silent mode.

/loadprx.ps3 was changed to work as a toggle some weeks ago.

**Comment by PS3-Pro** [comment]
Sorry Aldo, but still the same

here is one of the commands i'm using

/xmb.ps3$close_list;/xmb.ps3$close_list;/xmb.ps3$open_list;/copy.ps3/dev_hdd0/game/PS34KPROX/USRDIR/toolbox/icons/off.png&to=/dev_hdd0/game/PS34KPROX/USRDIR/toolbox/icons/plugins_icons/fps_counter/position/top_left.png;/copy.ps3/dev_hdd0/game/PS34KPROX/USRDIR/toolbox/icons/on.png&to=/dev_hdd0/game/PS34KPROX/USRDIR/toolbox/icons/plugins_icons/fps_counter/position/top_right.png;/copy.ps3/dev_hdd0/game/PS34KPROX/USRDIR/toolbox/icons/off.png&to=/dev_hdd0/game/PS34KPROX/USRDIR/toolbox/icons/plugins_icons/fps_counter/position/bottom_left.png;/copy.ps3/dev_hdd0/game/PS34KPROX/USRDIR/toolbox/icons/off.png&to=/dev_hdd0/game/PS34KPROX/USRDIR/toolbox/icons/plugins_icons/fps_counter/position/bottom_right.png;/write.ps3/dev_hdd0/plugins/fps_counter.yaml&t=   position: TOP_RIGHT&line=4;/unloadprx.ps3/dev_hdd0/plugins/fps_counter.sprx;/loadprx.ps3/dev_hdd0/plugins/fps_counter.sprx

maybe is better to create something like scopy.ps3/ and scopy_ps3/ ?  where S means silent

**Comment by PS3-Pro** [comment]
@aldostools the notifications of the copy paths are gone, but the copy finished notifications keeps poping up one after another (in the case of muti-commands), can this popup appear only after all commands were executed?

**Comment by aldostools** [comment]
Now it should be completely silent (except when the copy is aborted).
That notification was using a different function.
I renamed it to find all popup notifications easier in the future.
