### ISSUE TITLE
Auto-Play doesn't work

### ISSUE THREAD

**Issue by Haker120** [aldostools/webMAN-MOD#71]
Auto-Play is checked, PLAY DISC is checked and it goes back to main XMB game page but it is focused on webMAN icon and doesn't want to focus on mounted game and turn it on. On 1.47.00 and earlier it worked but the problem was with black screen.

**Comment by C0rn3j** [comment]
Still an issue when using Rebug 4.81.2 and webMAN 1.47.06.

However webMAN correctly focuses on the mounted game, it just won't launch, so I guess that part was fixed since OP posted the issue.

**Comment by wahlmanj** [comment]
Rebug 4.82.1 lite works via sman for autoplay, give it a try might work for webman too.

**Comment by Joonie86** [comment]
Closing old cases that have no further feedback. please use the latest version of wMM and report us
