### ISSUE TITLE
Other homebrew apps and Games not launching (Black screen + Console freeze) after updating wMM 

### ISSUE THREAD

**Issue by Don-Keballs** [aldostools/webMAN-MOD#712]
Hi Aldo,

As above, after updating webMAN MOD 1.47.41 (Full edition), I found homebrew apps and Games not launching (Black screen + Console freeze).

All was working fine when I updated a week or so ago (also webMAN MOD 1.47.41), then I updated today because I wanted to try out this new Artemis cheat feature and update the FPS plugin I now have these issues.

I know its wMM causing this issue because when I uninstall it I can open other homebrew and games via managunz.

Things I've tried so far;

Reinstall wMM
Rebuild database
Check file system
Reinstall HEN

I'm running wMM on a PS3 SS CECH-43xx Firmware 4.87 HEN 3.0.3

I would really appreciate some help on where I'm going wrong.
Thanks in advance.

**Comment by Diogoffs** [comment]
The same is happening with me.

**Comment by aldostools** [comment]
@Don-Keballs  @DiogoSilva48 Could you use the online updater again and update to the latest build?

Does the freeze happen only with FPS counter running?

**Comment by Diogoffs** [comment]
I updated again, it's still freezing, even using a Bluray game, I am not using the fps counter and I actually updated Webman Mod today after like 2-3 months on my PS3 with HEN.

**Comment by aldostools** [comment]
Does the black screen freeze happen after mounting a game? Or after loading webMAN MOD?

Does it happen with 1.47.40 or 1.47.38?

**Comment by Diogoffs** [comment]
After loading WebMAN Mod. I'm going to try to install those two and see if it happens as well.

**Comment by aldostools** [comment]
Check if changing the option 3072KB [MC] to default in /setup.ps3 & saving, makes a difference.

![image](https://user-images.githubusercontent.com/974897/168863108-10a8cdd9-fc7c-4ce3-938d-2d2d75a92a23.png)

**Comment by aldostools** [comment]
I just made a new compilation adding a sanity check to a code added recently

**Comment by Diogoffs** [comment]
Changing the option on 1.47.41 to Default didn't fix it. Isn't happening on 1.47.40. Can I update directly to that new compilation from .40 update menu?

**Comment by Don-Keballs** [comment]
> Does the black screen freeze happen after mounting a game? Or after loading webMAN MOD?
> 
> Does it happen with 1.47.40 or 1.47.38?

It happens after loading a game or homebrew app. only happens on 1.47.41

**Comment by Don-Keballs** [comment]
> Check if changing the option 3072KB [MC] to default in /setup.ps3 & saving, makes a difference.
> 
> ![image](https://user-images.githubusercontent.com/974897/168863108-10a8cdd9-fc7c-4ce3-938d-2d2d75a92a23.png)

This did not make a difference.

**Comment by aldostools** [comment]
Could you try updating one more time?
I made a fix that could be related to this issue.

**Comment by Don-Keballs** [comment]
> I just made a new compilation adding a sanity check to a code added recently

Just carried out a update via wMM. I presume this would have included what you mentioned above. The Issue is still present unfortunately.

**Comment by Diogoffs** [comment]
> > I just made a new compilation adding a sanity check to a code added recently
> 
> Just carried out a update via wMM. I presume this would have included what you mentioned above. The Issue is still present unfortunately.

yeah, same

**Comment by aldostools** [comment]
Here are the full edition from previous days. It would be good to know if some of these work.
That would help to identify from what commit started the bug. For some reason it doesn't happen on my Evilnat 4.88.2
[webftp_server.sprx](https://github.com/aldostools/webMAN-MOD/raw/72c260a509ba665b9ea50c78925e5b36f4a0bc61/_Projects_/updater/update/dev_hdd0/plugins/webftp_server.sprx) Latest commit today: 72c260a509ba665b9ea50c78925e5b36f4a0bc61
[webftp_server.sprx](https://github.com/aldostools/webMAN-MOD/raw/6a2f8f8cee7c73198ba98dc21f689df7d7b5968a/_Projects_/updater/update/dev_hdd0/plugins/webftp_server.sprx) Commit: 05/16 6a2f8f8cee7c73198ba98dc21f689df7d7b5968a
[webftp_server.sprx](https://github.com/aldostools/webMAN-MOD/raw/ffccea87b2ddb7d8b9cadb2321196791c978e8ff/_Projects_/updater/update/dev_hdd0/plugins/webftp_server.sprx) Commit: 05/14 ffccea87b2ddb7d8b9cadb2321196791c978e8ff
[webftp_server.sprx](https://github.com/aldostools/webMAN-MOD/raw/a6bc5fb3e19071477f6553f851595365b5f96473/_Projects_/updater/update/dev_hdd0/plugins/webftp_server.sprx) Commit: 05/13 a6bc5fb3e19071477f6553f851595365b5f96473
[webftp_server.sprx](https://github.com/aldostools/webMAN-MOD/raw/c0115b52cfa28a3c2933fbfdbe726bf83aee8056/_Projects_/updater/update/dev_hdd0/plugins/webftp_server.sprx) Commit: 05/12 c0115b52cfa28a3c2933fbfdbe726bf83aee8056
[webftp_server.sprx](https://github.com/aldostools/webMAN-MOD/raw/582afc3a48650537553ecc7221f04b75f9451cc5/_Projects_/updater/update/dev_hdd0/plugins/webftp_server.sprx) Commit: 05/11 582afc3a48650537553ecc7221f04b75f9451cc5
[webftp_server.sprx](https://github.com/aldostools/webMAN-MOD/raw/c64aca94d6d3dcc5c30a0c1fc5d5a836088860d1/_Projects_/updater/update/dev_hdd0/plugins/webftp_server.sprx) Commit: 05/10 582afc3a48650537553ecc7221f04b75f9451cc5

It would require to FTP the file `webftp_server.sprx` to `/dev_hdd0/plugins` and reboot.

**Comment by Don-Keballs** [comment]
> Here are the full edition from previous days. It would be good to know if some of these work. That would help to identify from what commit started the bug. For some reason it doesn't happen on my Evilnat 4.88.2 [webftp_server.sprx](https://github.com/aldostools/webMAN-MOD/raw/72c260a509ba665b9ea50c78925e5b36f4a0bc61/_Projects_/updater/update/dev_hdd0/plugins/webftp_server.sprx) Latest commit today: [72c260a](https://github.com/aldostools/webMAN-MOD/commit/72c260a509ba665b9ea50c78925e5b36f4a0bc61) [webftp_server.sprx](https://github.com/aldostools/webMAN-MOD/raw/6a2f8f8cee7c73198ba98dc21f689df7d7b5968a/_Projects_/updater/update/dev_hdd0/plugins/webftp_server.sprx) Commit: 05/16 [6a2f8f8](https://github.com/aldostools/webMAN-MOD/commit/6a2f8f8cee7c73198ba98dc21f689df7d7b5968a) [webftp_server.sprx](https://github.com/aldostools/webMAN-MOD/raw/ffccea87b2ddb7d8b9cadb2321196791c978e8ff/_Projects_/updater/update/dev_hdd0/plugins/webftp_server.sprx) Commit: 05/14 [ffccea8](https://github.com/aldostools/webMAN-MOD/commit/ffccea87b2ddb7d8b9cadb2321196791c978e8ff) [webftp_server.sprx](https://github.com/aldostools/webMAN-MOD/raw/a6bc5fb3e19071477f6553f851595365b5f96473/_Projects_/updater/update/dev_hdd0/plugins/webftp_server.sprx) Commit: 05/13 [a6bc5fb](https://github.com/aldostools/webMAN-MOD/commit/a6bc5fb3e19071477f6553f851595365b5f96473) [webftp_server.sprx](https://github.com/aldostools/webMAN-MOD/raw/c0115b52cfa28a3c2933fbfdbe726bf83aee8056/_Projects_/updater/update/dev_hdd0/plugins/webftp_server.sprx) Commit: 05/12 [c0115b5](https://github.com/aldostools/webMAN-MOD/commit/c0115b52cfa28a3c2933fbfdbe726bf83aee8056) [webftp_server.sprx](https://github.com/aldostools/webMAN-MOD/raw/582afc3a48650537553ecc7221f04b75f9451cc5/_Projects_/updater/update/dev_hdd0/plugins/webftp_server.sprx) Commit: 05/11 [582afc3](https://github.com/aldostools/webMAN-MOD/commit/582afc3a48650537553ecc7221f04b75f9451cc5) [webftp_server.sprx](https://github.com/aldostools/webMAN-MOD/raw/c64aca94d6d3dcc5c30a0c1fc5d5a836088860d1/_Projects_/updater/update/dev_hdd0/plugins/webftp_server.sprx) Commit: 05/10 [582afc3](https://github.com/aldostools/webMAN-MOD/commit/582afc3a48650537553ecc7221f04b75f9451cc5)
> 
> It would require to FTP the file `webftp_server.sprx` to /dev_hdd0/plugins and reboot.

Thanks, I'll start checking them out.

**Comment by Don-Keballs** [comment]
> [webftp_server.sprx](https://github.com/aldostools/webMAN-MOD/raw/6a2f8f8cee7c73198ba98dc21f689df7d7b5968a/_Projects_/updater/update/dev_hdd0/plugins/webftp_server.sprx) Commit: 05/16 [6a2f8f8](https://github.com/aldostools/webMAN-MOD/commit/6a2f8f8cee7c73198ba98dc21f689df7d7b5968a)

This one works ok.

**Comment by aldostools** [comment]
Great. Thank you. I will try to upload a new fix after I review the code.
If not I will revert the code to that commit.

**Comment by Don-Keballs** [comment]
That's great. Thanks Aldo!

**Comment by lucazandrade** [comment]
Just to report, I'm having the same problems, it only went back to normal after I uninstalled and reinstalled the previous version...

**Comment by aldostools** [comment]
Thank you @lucazandrade

With the help of @Don-Keballs  and @DiogoSilva48  I think i finally found the issue.
It was caused by an array overflow in the parent of the function where I made the modification.

So it was bug caused by an indirect change. You can update once again using the XMB updater or re-downloading the installer from releases or from brewology

Here is the direct link to the online updater https://ps3.aldostools.org/webMAN_MOD_latest.pkg

**Comment by Diogoffs** [comment]
> Thank you @lucazandrade
> 
> With the help of @Don-Keballs and @DiogoSilva48 I think i finally found the issue. It was caused by an array overflow in the parent of the function where I made the modification.
> 
> So it was bug caused by an indirect change. You can update once again using the XMB updater or re-downloading the installer from releases or from brewology
> 
> Here is the direct link to the online updater https://ps3.aldostools.org/webMAN_MOD_latest.pkg

I just tried, thank you very much, it's working perfectly now.

**Comment by aldostools** [comment]
Closing...
