### ISSUE TITLE
sLauncher GUI rebooting PS3

### ISSUE THREAD

**Issue by eliedsonsmg** [aldostools/webMAN-MOD#719]
If I open the sLauncher GUI holding start on xmb and I don't select any game, the ps3 reboots after a few seconds.
If I quickly select the game or if I go back to xmb by pressing the O button, the console does not reboot.
When I use R2 + L2 everything is fine.

PS3 Super slim
HFW oficial 4.89
Hen 3.1.1
webman 1.47.41

**Comment by aldostools** [comment]
I tried to reproduce the bug that you described, but I couldn't. 

Try using the online updater, reboot and check again.

I'm on CFW 4.88.

**Comment by eliedsonsmg** [comment]
Is there any difference in the code between the shortcuts for sLauncher (start and L2+R2).
Sorry if I wasn't clear, I'm using google translate.

**Comment by aldostools** [comment]
No, there isn't any difference, it's the same. It's an OR condition.
https://github.com/aldostools/webMAN-MOD/blob/master/include/poll/combos.h#L119-L135

**Comment by eliedsonsmg** [comment]
It could be an infinite loop causing the reboot after the if (line 119) condition is true.
On line 123 #ifdef WM_CUSTOM_COMBO has a treatment if L2+R2 is true (line 124).
I didn't find the same thing if the START button is true.

**Comment by aldostools** [comment]
You can try this test build to check if it behaves better:
[webMAN_MOD_latest.zip](https://github.com/aldostools/webMAN-MOD/files/8782122/webMAN_MOD_latest.zip)

I changed the code slightly to wait until the buttons are released before call sLaunch / VSH Menu.
So the plugin doesn't read the buttons being pressed when they start.

**Comment by eliedsonsmg** [comment]
It worked out.
I noticed that now the sLauncher GUI is only activated after releasing the shortcut button ( start or L2+R2).
While holding down the shortcut button it will not execute the sLauncher GUI function.
Thanks.

**Comment by aldostools** [comment]
Ok. I will move the wait for release to slaunch GUI, so the user don't have to guess when to release the buttons.

**Comment by eliedsonsmg** [comment]
OK.
I will close the issue.
Thanks.

**Comment by eliedsonsmg** [comment]
Can you send the file with the changes for me to test.

**Comment by aldostools** [comment]
Ok, I will post it when I'm done with the update.

**Comment by eliedsonsmg** [comment]
> Ok. I will move the wait for release to slaunch GUI, so the user don't have to guess when to release the buttons.



> 

Ok.
Awaiting.

**Comment by aldostools** [comment]
A new build has been uploaded. You can use the online updater.

**Comment by eliedsonsmg** [comment]
Good work.
I did the online update and tested it.
Everything is working fine.
Thanks.
