### ISSUE TITLE
webMAN MOD 1.47.01 as of commit 32b8174c696696bf002c01a643c972e4617e62ee

### ISSUE THREAD

**Issue by RandQalan** [aldostools/webMAN-MOD#72]
Still not setup entry

I tried even remote and yes I can get into setup but will not show on XMB 
setting is to show it on setup

**Comment by aldostools** [comment]
Missing webMAN_EN.xml has been added. Please check if the issue is solved.

**Comment by RandQalan** [comment]
Working Now thanks
