### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by LouisGarry** [aldostools/webMAN-MOD#721]
Hi Aldo, can you add a feature, when exiting the game/application wMM automatically deletes art.txt except quitting from Artemis (ARTPS3001)?

Thanks.

**Comment by aldostools** [comment]
Try this test build [webMAN_MOD_latest.zip](https://github.com/aldostools/webMAN-MOD/files/8778751/webMAN_MOD_latest.zip)

**Comment by LouisGarry** [comment]
Thanks Aldo, I just tried it, exiting Artemis art.txt was also deleted.

**Comment by LouisGarry** [comment]
Aldo, I moved is_artemis_app = IS(_game_TitleID, "ARTPS3001"); from line 103 in poll.h to line above if(!is_artemis_app) it worked as expected.

**Comment by aldostools** [comment]
Thank you for your feedback. Your fix looks wrong, due the variable requires a call to get_game_info().
I uploaded a new update. I tested it and now it's working a expected. You can use the online updater to get the latest build.

**Comment by LouisGarry** [comment]
Working properly, thank you
