### ISSUE TITLE
Exfat Support

### ISSUE THREAD

**Issue by ghost** [aldostools/webMAN-MOD#724]
Can we have Native Exfat Support on webman like NTFS 
And also if y'all gonna do that make it support external gameDATA
I'm asking because I have a PS3 and PS4 and I want to use the same drive for both of them

Kind regards.

**Comment by aldostools** [comment]
exFAT library is not compatible with the SDK used by webMAN MOD. It needs to be ported to allow use it in plugins.

For the moment you'll need to rely on prepISO and IRISMAN's file manager to use exFAT devices on PS3.
