### ISSUE TITLE
disable syscall to sign in is bypassed completely after updating 8.3 cobra mode 4.84.2 D-REX

### ISSUE THREAD

**Issue by illusionalDEX** [aldostools/webMAN-MOD#728]
i replaced stage2.cex & stage2.dex

**Comment by aldostools** [comment]
The security check can be bypassed under the following conditions:
1. If /dev_hdd0/tmp/wm_res/npsignin_plugin.rco does not exist
2. If Cobra payload is disabled or stage2 did not load
3. If all map paths slots are already in use
4. If CFW syscalls are already disabled
5. If webMAN MOD did not load
6. If /dev_flash/vsh/resource/npsignin_plugin.lck does not exist (this is handled by Cobra 8.3)

Check if your system has some of these conditions.
