### ISSUE TITLE
Bug doble icon 

### ISSUE THREAD

**Issue by dan83m** [aldostools/webMAN-MOD#73]
I find a bug where you can see double icon of the game, for example : Diablo 3 Diablo 3, Resident Evil 5 Resident Evil 5, and so... This problems don't occur on web mod 1.43.xx only on recent updates

**Comment by aldostools** [comment]
If you have the full edition installed, please check if ps3 net server enabled and that the net clients ip in /setup.ps3 are not pointing to 127.0.0.1, local host or the IP of the PS3 console.

If the problem persist, please provide additional information, where the games are stored, a picture of the duplicate games, etc.

**Comment by dan83m** [comment]
Thx seem I resolved the problem, I did like you said and it's fixed now!

**Comment by dan83m** [comment]
Thx seem I resolved the problem, I did like you said and it's fixed now!

**Comment by dan83m** [comment]
Thx seem I resolved the problem, I did like you said and it's fixed now!
