### ISSUE TITLE
webMAN-MOD not showing System Storage or other information

### ISSUE THREAD

**Issue by pirsir76** [aldostools/webMAN-MOD#730]
PS3 Model = CECHA01
Firmware = 4.88 CEX Cobra 8.3
webMAN-MOD = Latest ver.1.47.41

Greetings Aldo (psy1 from PSX-Place here)

Today I installed webMAN-MOD onto a new CECHA01 PS3 and I noticed a few differences:

When I hit start and select to display additional information it is always displaying "System Storage" as 0 MB free.
It should be displaying the remaining system storage; not 0 MB.

Also, when I copy a PS2 ISO temporarily to the PS2ISO folder, in the top right hand corner it used to display the amount of MB copied so far. For some reason it is no longer displaying this useful information.

I copied Kingdom Hearts (PS2) through ps3netserver just then and the game did not auto load. I had to back out of webMAN-MOD and manually click on the game and there's no good indication that the game has finished copying. I have noticed this does not happen when copying smaller games.

So there's 3 issues in total.

Could be a checkbox I have not ticked? Or a bug.

**Comment by aldostools** [comment]
Hello psy1!!
Thank you for your feedback.

Unless your HDD is really full, it should show the remaining free storage.
![image](https://user-images.githubusercontent.com/974897/173058127-cf13d825-aa37-4862-82ba-10c517000e3a.png)

In regards to the copy from ps3netsrv, I found a bug during the remote file copy that happened when the remote directory is listed while the remote file is being copied.

To prevent this issue, now the remote file listing is not allow until the remote file copy is finished.
A progress of the file copy is displayed instead.

A new build is found in the release page or use the online updater found in:
webMAN Games > webMAN Setup > Update webMAN MOD > Install

**Comment by pirsir76** [comment]
Hey Aldo,

"Unless your HDD is really full, it should show the remaining free storage."
Strange because my SSD is about 99% empty.
Here's some pics: 
![DSC00803](https://user-images.githubusercontent.com/57454066/173874179-8fc59b9d-ee4c-41d8-b821-11ede9f05b4e.JPG)
![DSC00804](https://user-images.githubusercontent.com/57454066/173874199-be902b6c-1f0f-4ba4-9a62-8f678c196e5d.JPG)

It is displaying the correct system storage on this display:

![DSC00807](https://user-images.githubusercontent.com/57454066/173879249-6bfb9e14-1ecd-41b3-98ed-be957a2e8046.JPG)

The only differences from when it was displaying the storage from last is now my PS3 has Cobra 8.3 installed for custom firmware instead of Rebug. (Could be the issue? Not sure.)

"A progress of the file copy is displayed instead."
Ah yes, I see it now, what I wasn't doing was pressing start+ select.
Here's what I'm seeing:

![DSC00811](https://user-images.githubusercontent.com/57454066/173883965-2b11994b-03c9-4561-bbdb-6ddf8dcc1d60.JPG)

**Comment by pirsir76** [comment]
Just to make it clear; I still have no response as to why it's not displaying the system storage correclty.

**Comment by aldostools** [comment]
@pirsir76 Unfortunately I cannot reproduce your bug. As I posted in my previous post, the system storage is showing the proper free space.

I suggest that try using sMAN or maybe installing an older version. If some of them work, I could compare what is different to make a fix.

**Comment by aldostools** [comment]
@pirsir76 I think I found a possible cause of the issue in a boundary check.

**Comment by pirsir76** [comment]
> @pirsir76 I think I found a possible cause of the issue in a boundary check.

Worked thanks again Aldo!!

Before this issue gets closed, can I make a suggestion?
In regards to the copy from ps3netsrv, when it's copying games which are over 1GB it displays the progress in GB.
e.g. 1/4 GB. When it's copying games that are less than GB it displays in MB.
It would be better if it displayed in MB at all times because MB is more precise and a better indicator of how much is copied over.
