### ISSUE TITLE
webMAN MOD freezes my PS3

### ISSUE THREAD

**Issue by Windows10User2** [aldostools/webMAN-MOD#731]
No matter what I do, webMAN MOD freezes my PS3. I formatted the HDD, reinstalled CFW, reinstalled webMAN MOD and changed webMAN MOD's memory usage settings to no avail.

**Comment by aldostools** [comment]
Please try the following:
1- Unplug all USB devices and rename the content folders (PS3ISO, GAMES, PSXISO, PS2ISO, etc.) in /dev_hdd0
The idea is that the initial scanning do not find the games.

2- Uninstall webMAN MOD using the uninstaller option in the menu or deleting at least these files & folders:
/dev_hdd0/tmp/boot_plugins.txt
/dev_hdd0/tmp/plugins
/dev_hdd0/tmp/wm_config.bin
/dev_hdd0/tmp/wm_res
/dev_hdd0/tmp/wm_lang
/dev_hdd0/tmp/wmtmp
/dev_hdd0/xmlhost

3- Make sure that Cobra is enabled.

4- Re-download and install the lastest package from [releases](https://github.com/aldostools/webMAN-MOD/releases)
It is important that re-download the package to make sure that you are using the latest build.
NOTE: After install the package, execute the installer and wait until it reboot.

5- If the console starts fine, rename gradually the content folders to their original name and refresh the XML each time until you find the folder that could be causing the freeze.

6- If the console freezes after the installation, go to Recovery Menu and exit to delete /dev_hdd0/boot_plugins.txt


If the problem persists, I recommend that use Cobra debug with socat to check why it is freezing or uninstall again webMAN MOD and use [sman](https://store.brewology.com/ahomebrew.php?brewid=309)

**Comment by Scr34mik** [comment]
i have hard freeze when enabling FPS+temps overlay. 
there was an occasion when i tried to enable FPS counter and instead it shown notification that webman is disabled.

im running "_REBUG_4.84.2_REX_" on CECH-2508A

**Comment by aldostools** [comment]
The plugin is running fine on my setup. If it's crashing your system, I recommend that stop using it to prevent damages on your system caused by increment of the temperature during the freeze.

**Comment by Windows10User2** [comment]
> Please try the following: 1- Unplug all USB devices and rename the content folders (PS3ISO, GAMES, PSXISO, PS2ISO, etc.) in /dev_hdd0 The idea is that the initial scanning do not find the games.
> 
> 2- Uninstall webMAN MOD using the uninstaller option in the menu or deleting at least these files & folders: /dev_hdd0/tmp/boot_plugins.txt /dev_hdd0/tmp/plugins /dev_hdd0/tmp/wm_config.bin /dev_hdd0/tmp/wm_res /dev_hdd0/tmp/wm_lang /dev_hdd0/tmp/wmtmp /dev_hdd0/xmlhost
> 
> 3- Make sure that Cobra is enabled.
> 
> 4- Re-download and install the lastest package from [releases](https://github.com/aldostools/webMAN-MOD/releases) It is important that re-download the package to make sure that you are using the latest build. NOTE: After install the package, execute the installer and wait until it reboot.
> 
> 5- If the console starts fine, rename gradually the content folders to their original name and refresh the XML each time until you find the folder that could be causing the freeze.
> 
> 6- If the console freezes after the installation, go to Recovery Menu and exit to delete /dev_hdd0/boot_plugins.txt
> 
> If the problem persists, I recommend that use Cobra debug with socat to check why it is freezing or uninstall again webMAN MOD and use [sman](https://store.brewology.com/ahomebrew.php?brewid=309)

Unfortunately, webMAN MOD still freezes after following all the 6 steps. sMAN also freezes my PS3 and I have another problem. My PS3 sometimes beeps 3 times and restarts after exiting an app or game (this also occurred in the previous PS3). At least multiMAN, ManaGunZ and IRISMAN don't freeze my PS3. I removed webMAN MOD, sMAN, ManaGunZ and multiMAN and I've been only using IRISMAN. I wanted to use webMAN MOD because it's said to be the most complete.

Anyway, what's Cobra debug and socat and how can I use the latter? I'm on Evilnat 4.89 and these freezing issues also occurred with different Ferrox and Rebug releases and in the previous Evilnat releases in the previous PS3.

I know it's OT but if one has Evilnat 4.89 installed and a 4.90 OFW is released should he use SEN Enabler and manual spoof to 4.90 and then disable syscalls in Evilnat to be able to access PSN or will he be able to access PSN without having spoofed to 4.90 and just after only disabling syscalls in Evilnat?

**Comment by aldostools** [comment]
If you use webMAN MOD or sMAN, avoid using multiMAN. Use it only when needed (e.g. to dump a game from disc, build an ISO, etc). 

multiMAN erases all mapped paths when it starts and that may freeze the system when you try to mount a game in sMAN or webMAN Games menu.

Also the latest multiMAN auto scans NTFS and causes a conflict with the games scanned by webMAN MOD.

Cobra debug is a version of the payload that sends network messages to socat (client that you install on the PC).
To use it you go to CFW Tools menu > Cobra > Toggle Cobra Version. webMAN will show the version as 4.89D

You need to use [socat](https://sourceforge.net/projects/unix-utils/files/socat/1.7.3.2/) from a batch file or command prompt to capture the output.

`socat -lu stdout udp-recv:18194,reuseaddr |tee stdout.txt`

SEN Enabler should not be used to spoof the version. Many validations have changed on PSN servers side.

If you need to access PSN, the following method works with any version (but it is unknown how safe is to use it)
https://github.com/aldostools/webMAN-MOD/wiki/PSN-access-with-webMAN-MOD

**Comment by Windows10User2** [comment]
> If you use webMAN MOD or sMAN, avoid using multiMAN. Use it only when needed (e.g. to dump a game from disc, build an ISO, etc).
> 
> multiMAN erases all mapped paths when it starts and that may freeze the system when you try to mount a game in sMAN or webMAN Games menu.
> 
> Also the latest multiMAN auto scans NTFS and causes a conflict with the games scanned by webMAN MOD.
> 
> Cobra debug is a version of the payload that sends network messages to socat (client that you install on the PC). To use it you go to CFW Tools menu > Cobra > Toggle Cobra Version. webMAN will show the version as 4.89D
> 
> You need to use [socat](https://sourceforge.net/projects/unix-utils/files/socat/1.7.3.2/) from a batch file or command prompt to capture the output.
> 
> `socat -lu stdout udp-recv:18194,reuseaddr |tee stdout.txt`
> 
> SEN Enabler should not be used to spoof the version. Many validations have changed on PSN servers side.
> 
> If you need to access PSN, the following method works with any version (but it is unknown how safe is to use it) https://github.com/aldostools/webMAN-MOD/wiki/PSN-access-with-webMAN-MOD

I only use IRISMAN and removed all the other. 

Sorry, but I don't understand how to run socat.

So, to be able to access PSN while having an outdated FW, I'd have to download the ps3-updatelist.txt file, copy it to /dev_hdd0/ps3-updatelist.txt and then disable CFW syscalls since only disabling CFW syscalls wouldn't be enough?

**Comment by aldostools** [comment]
If everything is working as expected, then you're fine.

Forget about socat if you don't understand it. It's intended for developers and people that need to debug the system.

You're correct about how to access PSN. Just be aware that with that method is unknown how safe it is, and potentially you could end being banned. I'm making it clear, because I don't want to be blamed for any ban that could result from this method.

**Comment by Windows10User2** [comment]
> If everything is working as expected, then you're fine.
> 
> Forget about socat if you don't understand it. It's intended for developers and people that need to debug the system.
> 
> You're correct about how to access PSN. Just be aware that with that method is unknown how safe it is, and potentially you could end being banned. I'm making it clear, because I don't want to be blamed for any ban that could result from this method.

Well, I wanted to be able to use webMAN MOD and so there's no possible solution for me? What are the most useful webMAN MOD features I'll miss if I keep using IRISMAN?

Oh, thanks for the explanation, but I'm pretty sure I was able to access PSN after manually spoofing to 4.89 using SEN Enabler while having Evilnat 4.88 installed (and after disabling CFW syscalls). Anyway, doing what we told before is less likely of getting me banned?

**Comment by aldostools** [comment]
SEN Enabler development was suspended by Evilnat, because himself said that it was not safe to continue using it.
That's why he focused in CFW Evilnat 4.88 and later 4.89. You can use it at your own risk. Same as the ps3-updatelist.txt method.

The main features that you will miss using IRISMAN is to be able to use FTP at any moment, mount games directly from XMB without start an application or remote games using ps3netsrv (IRISMAN relies on webMAN MOD for that feature).

**Comment by Windows10User2** [comment]
> SEN Enabler development was suspended by Evilnat, because himself said that it was not safe to continue using it. That's why he focused in CFW Evilnat 4.88 and later 4.89. You can use it at your own risk. Same as the ps3-updatelist.txt method.
> 
> The main features that you will miss using IRISMAN is to be able to use FTP at any moment, mount games directly from XMB without start an application or remote games using ps3netsrv (IRISMAN relies on webMAN MOD for that feature).

In that case it should be removed from Brewology to not confuse users. Ok, but the question isn't if it's risky or not because apparently both are but if it still works. I suppose the new (I guess) method works but does SEN Enabler still work?

Isn't there a plugin that lets the user use FTP at any moment?

What about the 3 beep behavior? I think a lot of users complain about this beep problem and even PS3s which were never jailbroken also had it (IIRC, my previous PS3 also had it before I jailbroke it for the first time) now and then so is it a normal behavior and the PS3 isn't broken? Anyway, I think it became more frequent after jailbreaking the PS3s.

**Comment by aldostools** [comment]
Brewology is a repository of homebrews, now & old. SEN Enabler clearly says that was updated up to 4.87 and says in red:
** A NO BAN IS NOT GUARANTEED, USE WITH CAUTION **

Yes there is a plugin for FTP only:
https://store.brewology.com/ahomebrew.php?brewid=79

About the 3 beeps, it cannot be fixed until it's determined the exact cause.
webMAN MOD is open source, so anyone can fix, improve or remove any feature that find problematic.

**Comment by Windows10User2** [comment]
> Brewology is a repository of homebrews, now & old. SEN Enabler clearly says that was updated up to 4.87 and says in red: ** A NO BAN IS NOT GUARANTEED, USE WITH CAUTION **
> 
> Yes there is a plugin for FTP only: https://store.brewology.com/ahomebrew.php?brewid=79
> 
> About the 3 beeps, it cannot be fixed until it's determined the exact cause. webMAN MOD is open source, so anyone can fix, improve or remove any feature that find problematic.

Should I download homebrew from another sorce, then? There is some which I can only find in Brewology IIRC.

So, could I use FTP while gaming with that plugin and would it have the same speed as if I was using FTP in IRISMAN?

Anyway, if connecting to PSN, should I use the method we mentioned previously even though that page has the title "PSN access with webMAN MOD" and I don't have webMAN MOD?

But do you know if it also occurs in PS3s that were never jailbroken and if it's a relatively normal behavior for both unjailbroken and jailbroken PS3s?

**Comment by aldostools** [comment]
I am who maintain Brewology's PS3 homebrew. I don't know of any other place.

You should be able to FTP while gaming using that plugin. I don't use it, so I cannot provide much information.

The PSN method with webMAN MOD requires webMAN MOD. I don't know of any other homebrew that redirect the update URL.

I have been using jailbroken PS3 for over 10 years, so I don't remember how unjailbroken consoles behave.

I suggest that open a thread on PSX-PLACE and ask these questions. There you will find HEN users that can help.

I'll have to go... I have to work tomorrow and I need to sleep. Bye.

**Comment by Windows10User2** [comment]
> I am who maintain Brewology's PS3 homebrew. I don't know of any other place.
> 
> You should be able to FTP while gaming using that plugin. I don't use it, so I cannot provide much information.
> 
> The PSN method with webMAN MOD requires webMAN MOD. I don't know of any other homebrew that redirect the update URL.
> 
> I have been using jailbroken PS3 for over 10 years, so I don't remember how unjailbroken consoles behave.
> 
> I suggest that open a thread on PSX-PLACE and ask these questions. There you will find HEN users that can help.
> 
> I'll have to go... I have to work tomorrow and I need to sleep. Bye.

In that case I guess I should wait until a CFW that supports the latest OFW is released since I can't make webMAN MOD to work.

Thank you. Bye.

**Comment by Windows10User2** [comment]
I bought an used PS3 since the previous stopped reading Blu-ray discs, installed webMAN MOD's latest version and it hasn't been freezing the PS3 so maybe it was the previous PS3's HDD's fault.
