### ISSUE TITLE
wm_request special symbols

### ISSUE THREAD

**Issue by PS3-Pro** [aldostools/webMAN-MOD#732]
Aldo, is there any way to use special symbols via wm_request? i'm using

/popup.ps3?PS3™ 4K Pro resources installed%0AYou can now launch the installer...&icon=29;/beep.ps3?1

but it only shows PS3 if the ™ symbol is included, using /popup.ps3? with special symbols works via webcommands and script but wm_request.

**Comment by aldostools** [comment]
Try using %99 to encode the character. In URLs, any ASCII character above 127 or below 32 should use escape character %

**Comment by PS3-Pro** [comment]
> %99

It completely broke the notification, only the beep plays

**Comment by aldostools** [comment]
Ok the character must be UTF-8 encoded like: %E2%84%A2

**Comment by PS3-Pro** [comment]
> %E2%84%A2


Thank you Aldo, it worked.
