### ISSUE TITLE
Artemis Centralized Database

### ISSUE THREAD

**Issue by PS3-Pro** [aldostools/webMAN-MOD#733]

**Comment by aldostools** [comment]
You can copy the netcheat list files (*.ncl) to /dev_hdd0/tmp/artemis

Name them as BLES12345.ncl or NPEB12345.ncl. Also (Titleid)_l2.ncl and (Titleid)_r2.ncl

Or put the ncl in the same folder of the game:
For ISO: 
/dev_hdd0/PS3ISO/name.iso
/dev_hdd0/PS3ISO/name.ncl
/dev_hdd0/PS3ISO/name_l2.ncl
/dev_hdd0/PS3ISO/name_r2.ncl

For PKG:
/dev_hdd0/game/NPXX99999/artemis.ncl (where NPXX99999 the real title id of the game)

IMPORTANT: All cheats in the default file will be activated when the game is started.

**Comment by PS3-Pro** [comment]
Sorry for the empty description :P

My laptop battery died while I was writing lol I was about to ask if it supports different game versions

eg: BLES12345_v1.00.ncl, BLES12345_v1.01.ncl

I want to make a pkg to install all the codes available to  /dev_hdd0/tmp/artemis so the user can have cheats in all games without the need to launch artemis.

**Comment by aldostools** [comment]
It doesn't check version. Only title id. I could add support for version in a next release.

**Comment by PS3-Pro** [comment]
> It doesn't check version. Only title id. I could add support for version in a next release.

Thanks, releasing it https://github.com/aldostools/webMAN-MOD/tree/master/_Projects_/codelists as a centralized database through pkg would be nice, users could use the web command to disable the ones they  don't want

**Comment by aldostools** [comment]
No. The user should configure the cheats that they want to use.

**Comment by aldostools** [comment]
@LuanTeles You can test this version that adds support for ncl files for specific versions.
*removed link*

The format for the centrializes files can be:
 /dev_hdd0/tmp/artemis/BLES12345.ncl
 /dev_hdd0/tmp/artemis/BLES12345_01.00.ncl

EDIT:
Use the online updater to get the new build.
