### ISSUE TITLE
User Login Detection

### ISSUE THREAD

**Issue by PS3-Pro** [aldostools/webMAN-MOD#734]
@aldostools is there any wait to use wait command to wait for the user to log in?

I'm using these commands via onxmb.bat

if exist /dev_flash/vsh/resource/explore/xmb/pro.xml
	copy /dev_hdd0/game/PS34KPROX/USRDIR/toolbox/patches/game_column_fix/cfw/category_friend.xml,/dev_blind/vsh/resource/explore/xmb/category_friend.xml
	copy /dev_hdd0/game/PS34KPROX/USRDIR/toolbox/patches/game_column_fix/cfw/category_game.xml,/dev_blind/vsh/resource/explore/xmb/category_game.xml
	copy /dev_hdd0/game/PS34KPROX/USRDIR/toolbox/patches/game_column_fix/cfw/category_game_tool2.xml,/dev_blind/vsh/resource/explore/xmb/category_game_tool2.xml
	copy /dev_hdd0/game/PS34KPROX/USRDIR/toolbox/patches/game_column_fix/cfw/category_music.xml,/dev_blind/vsh/resource/explore/xmb/category_music.xml
	copy /dev_hdd0/game/PS34KPROX/USRDIR/toolbox/patches/game_column_fix/cfw/category_network.xml,/dev_blind/vsh/resource/explore/xmb/category_network.xml
	copy /dev_hdd0/game/PS34KPROX/USRDIR/toolbox/patches/game_column_fix/cfw/category_network_tool2.xml,/dev_blind/vsh/resource/explore/xmb/category_network_tool2.xml
	copy /dev_hdd0/game/PS34KPROX/USRDIR/toolbox/patches/game_column_fix/cfw/category_photo.xml,/dev_blind/vsh/resource/explore/xmb/category_photo.xml
	copy /dev_hdd0/game/PS34KPROX/USRDIR/toolbox/patches/game_column_fix/cfw/category_psn.xml,/dev_blind/vsh/resource/explore/xmb/category_psn.xml
	copy /dev_hdd0/game/PS34KPROX/USRDIR/toolbox/patches/game_column_fix/cfw/category_tv.xml,/dev_blind/vsh/resource/explore/xmb/category_tv.xml
	copy /dev_hdd0/game/PS34KPROX/USRDIR/toolbox/patches/game_column_fix/cfw/category_user.xml,/dev_blind/vsh/resource/explore/xmb/category_user.xml
	copy /dev_hdd0/game/PS34KPROX/USRDIR/toolbox/patches/game_column_fix/cfw/category_user_login.xml,/dev_blind/vsh/resource/explore/xmb/category_user_login.xml
	copy /dev_hdd0/game/PS34KPROX/USRDIR/toolbox/patches/game_column_fix/cfw/category_video.xml,/dev_blind/vsh/resource/explore/xmb/category_video.xml
	copy /dev_hdd0/game/PS34KPROX/USRDIR/toolbox/patches/game_column_fix/cfw/category_network_service_mode_tools.xml,/dev_blind/vsh/resource/explore/xmb/category_network_service_mode_tools.xml
	/led.ps3mapi?color=1&mode=2
	/led.ps3mapi?color=0&mode=3
	
	**/xmb.ps3$focus_category game**
	**/xmb.ps3$focus_index 2**
	**/xmb.ps3$focus_index 2**
else
end if

but if the auto login is not enabled and the script runs in the multi user screen ( **/xmb.ps3$focus_category game**
	**/xmb.ps3$focus_index 2**
	**/xmb.ps3$focus_index 2** )  will break it as you can see in the images below

Multi user screen;

![image](https://user-images.githubusercontent.com/74815634/176261803-45ee4d6e-80af-4d18-82f8-68d2e5ba6d46.png)

Multi user screen after tHe onxmb.bat runs

![image](https://user-images.githubusercontent.com/74815634/176262254-76a50792-dd8f-43cb-b9d0-30a6c3ac504c.png)

**Comment by PS3-Pro** [comment]
Hm, maybe 

wait /dev_hdd0/home/$USERID$

i'll try it

Edit: Didn't work

**Comment by aldostools** [comment]
Try `wait xmb`. It has a timeout of 30 seconds.

If  you need to wait 2 minutes, you need to add the command 4 times.

You could use wait /dev_hdd0/home/$USERID$ if there a file that is created in that folder only when the user login.

**Comment by PS3-Pro** [comment]
Still the same	

        /wait xmb
	/xmb.ps3$focus_category game
	/xmb.ps3$focus_index 2
	/xmb.ps3$focus_index 2

i don't want to use timeouts because it should run immediately after exiting an application too and when the system boots

**Comment by aldostools** [comment]
A more simple workaround is to tell to the user that set a default login user.

In wMM there isn't any command that detect the user login.

**Comment by PS3-Pro** [comment]
> Try `wait xmb`. It has a timeout of 30 seconds.
> 
> If you need to wait 2 minutes, you need to add the command 4 times.
> 
> You could use wait /dev_hdd0/home/USERID if there a file that is created in that folder only when the user login.

i tried it too as webman returns me

404 Path not found
[/dev_hdd0](http://192.168.0.16/dev_hdd0/)/[home](http://192.168.0.16/dev_hdd0/home/)/-0000001

i thought it shoukd work , but not in this case lol

**Comment by aldostools** [comment]
I doubt that it would work even after fixing the bug. 

The command waits until a file or directory exists. The home directory for the user always exists.

**Comment by PS3-Pro** [comment]
> A more simple workaround is to tell to the user that set a default login user.
> 
> In wMM there isn't any command that detect the user login.

maybe i'll use  (not ideal)
/pad.ps3?accept 

i did it in my boot_init.txt to use with install.ps3, if install.ps3 runs in the multi user screen it doesn't work. so i used /pad.ps3?accept  to avoid that

**Comment by aldostools** [comment]
ok

**Comment by PS3-Pro** [comment]
> ok

Thanks

**Comment by PS3-Pro** [comment]
> > A more simple workaround is to tell to the user that set a default login user.
> > In wMM there isn't any command that detect the user login.
> 
> maybe i'll use (not ideal) /pad.ps3?accept
> 
> i did it in my boot_init.txt to use with install.ps3, if install.ps3 runs in the multi user screen it doesn't work. so i used /pad.ps3?accept to avoid that

Using /pad.ps3?accept is a bad idea, when it runs after exiting a game it will launch an app/icon depending on the app category hehe

i'm using 

/xmb.ps3$focus_category game
/xmb.ps3$focus_index 2
/xmb.ps3$focus_index 2

to always focus my custom what's new :P, but /pad.ps3?accept is performanced before it

**Comment by PS3-Pro** [comment]
Maybe the best option is using it when my installer is executed

/xmb.ps3$xregistry(/setting/user/defaultLoginUserId)=$USERID$

so it will enable the auto login for the user that launched my installer.

**Comment by aldostools** [comment]
Or just tell the user that needs to set a default login user... otherwise it will fail.

**Comment by PS3-Pro** [comment]
@aldostools I'm back at this, because if i force disable the auto-login (via scripts) it breaks my usb recovery tools on the multi user screen.

I'm tryinG this script for my tests. (now i'm using a file instead of path.)

```
if exist /dev_hdd0/home/$USERID$/localusername
	wait 9
	wait 7
	popup User Logged In
	beep2
else
	wait 9
	wait 7
	popup User NOT Logged In
	beep3
end if

```
it is always returning me User NOT Logged In, any ideal?

**Comment by aldostools** [comment]
$USERID$ only has a value when the user is logged in.

You can verify the value adding: `popup /dev_hdd0/home/$USERID$/localusername`

**Comment by PS3-Pro** [comment]
> USERID only has a value when the user is logged in.
> 
> You can verify the value adding: `popup /dev_hdd0/home/$USERID$/localusername`


I'll try later today thanks, but in my script even if i enable the auto-login it is returning the User NOT Logged In notification 😕 even though web commands are seeing this file with no problems

**Comment by aldostools** [comment]
The script commands were not replacing `$USERID$` with the corresponding value.

If fixed this issue in this test build [webftp_server.zip](https://github.com/aldostools/webMAN-MOD/files/9045919/webftp_server.zip)

**Comment by PS3-Pro** [comment]
> The script commands were not replacing `$USERID$` with the corresponding value.
> 
> If fixed this issue in this test build [webftp_server.zip](https://github.com/aldostools/webMAN-MOD/files/9045919/webftp_server.zip)

Thanks aldo, this one solved my issue :)

**Comment by PS3-Pro** [comment]
Is it implemented in the online updater?  I tried and same problem.

Only in test build it's fixed

**Comment by aldostools** [comment]
It is not deployed yet. It's currently only available in the test build above.

**Comment by PS3-Pro** [comment]
@aldostools just one question

How can i make the installed label to run only 
if exist /dev_flash/vsh/resource/explore/xmb/pro.xml ?

it is running it even without the pro.xml
```

       wait 9
	wait 5
	/delete.ps3/dev_hdd0/tmp/explore/nsx
	/delete.ps3/dev_hdd0/tmp/explore/xil2
	
if exist /dev_flash/vsh/resource/explore/xmb/pro.xml
	goto Installed
	
:Installed
if exist /dev_hdd0/home/$USERID$/localusername
	wait 2
	popup PS3™ Pro
	beep3
	/delete_ps3/dev_hdd0/theme/CD_*.p3t
	wait 2
	/install.ps3/dev_flash/vsh/resource/theme/01.p3t
	/move.ps3/dev_hdd0/boot_init_swap.txt|/dev_hdd0/boot_init.txt
	/browser.ps3?http://localhost/dev_hdd0/game/PS34KPROX/USRDIR/toolbox/htmls/welcome.html
	/write.ps3/dev_hdd0/tmp/wm_config.bin&t=32&pos=0x30
	/write.ps3/dev_hdd0/tmp/wm_config.bin&t=01&pos=0x377
	/write.ps3/dev_hdd0/tmp/wm_config.bin&t=01&pos=0x249
	/write.ps3/dev_hdd0/tmp/wm_config.bin&t=01&pos=0x157
	/write.ps3/dev_hdd0/tmp/wm_config.bin&t=01&pos=0x147
	/write.ps3/dev_hdd0/tmp/wm_config.bin&t=01&pos=0x40
	/write.ps3/dev_hdd0/tmp/wm_config.bin&t=01&pos=0x25E
	/write.ps3/dev_hdd0/tmp/wm_config.bin&t=00&pos=0x27
	/write.ps3/dev_hdd0/tmp/wm_config.bin&t=00&pos=0x28
	/write.ps3/dev_hdd0/tmp/wm_config.bin&t=01&pos=0x0E
	/xmb.ps3$xregistry(/setting/display/rgbOutputRange)=1
	/xmb.ps3$xregistry(/setting/dlna/dlnaFlag)=1
	/xmb.ps3$xregistry(/setting/game/ps2emuSaveUtility)=1
	/xmb.ps3$xregistry(/setting/game/ps2softemuFunc)=1
	/xmb.ps3$xregistry(/setting/game/pspemu3dMenu)=1
	/xmb.ps3$xregistry(/setting/sound/1/usbHeadsetSound)=2
	/xmb.ps3$xregistry(/setting/system/crashreport/crepo)=0
	/xmb.ps3$xregistry(/setting/system/debugSystemUpdate)=1
	/xmb.ps3$xregistry(/setting/system/dispHddSpace)=1
	/xmb.ps3$xregistry(/setting/system/fakePlus)=1
	/xmb.ps3$xregistry(/setting/system/fakeSavedataOwner)=1
	/xmb.ps3$xregistry(/setting/system/turnOffWarning)=1
	/xmb.ps3$xregistry(/setting/user/$USERID$/wboard/enable)=0
	/xmb.ps3$xregistry(/setting/user/$USERID$/browser/exitConfirmation)=0
	/xmb.ps3$xregistry(/setting/system/nickname)=PS3 Pro
else
	/pad.ps3?accept
	wait 4
	popup PS3™ Pro
	beep3
	/delete_ps3/dev_hdd0/theme/CD_*.p3t
	wait 2
	/install.ps3/dev_flash/vsh/resource/theme/01.p3t
	/move.ps3/dev_hdd0/boot_init_swap.txt|/dev_hdd0/boot_init.txt
	/browser.ps3?http://localhost/dev_hdd0/game/PS34KPROX/USRDIR/toolbox/htmls/welcome.html
	/write.ps3/dev_hdd0/tmp/wm_config.bin&t=32&pos=0x30
	/write.ps3/dev_hdd0/tmp/wm_config.bin&t=01&pos=0x377
	/write.ps3/dev_hdd0/tmp/wm_config.bin&t=01&pos=0x249
	/write.ps3/dev_hdd0/tmp/wm_config.bin&t=01&pos=0x157
	/write.ps3/dev_hdd0/tmp/wm_config.bin&t=01&pos=0x147
	/write.ps3/dev_hdd0/tmp/wm_config.bin&t=01&pos=0x40
	/write.ps3/dev_hdd0/tmp/wm_config.bin&t=01&pos=0x25E
	/write.ps3/dev_hdd0/tmp/wm_config.bin&t=00&pos=0x27
	/write.ps3/dev_hdd0/tmp/wm_config.bin&t=00&pos=0x28
	/write.ps3/dev_hdd0/tmp/wm_config.bin&t=01&pos=0x0E
	/xmb.ps3$xregistry(/setting/display/rgbOutputRange)=1
	/xmb.ps3$xregistry(/setting/dlna/dlnaFlag)=1
	/xmb.ps3$xregistry(/setting/game/ps2emuSaveUtility)=1
	/xmb.ps3$xregistry(/setting/game/ps2softemuFunc)=1
	/xmb.ps3$xregistry(/setting/game/pspemu3dMenu)=1
	/xmb.ps3$xregistry(/setting/sound/1/usbHeadsetSound)=2
	/xmb.ps3$xregistry(/setting/system/crashreport/crepo)=0
	/xmb.ps3$xregistry(/setting/system/debugSystemUpdate)=1
	/xmb.ps3$xregistry(/setting/system/dispHddSpace)=1
	/xmb.ps3$xregistry(/setting/system/fakePlus)=1
	/xmb.ps3$xregistry(/setting/system/fakeSavedataOwner)=1
	/xmb.ps3$xregistry(/setting/system/turnOffWarning)=1
	/xmb.ps3$xregistry(/setting/user/$USERID$/wboard/enable)=0
	/xmb.ps3$xregistry(/setting/user/$USERID$/browser/exitConfirmation)=0
	/xmb.ps3$xregistry(/setting/system/nickname)=PS3 Pro
end if

```

**Comment by aldostools** [comment]
Add an `:end` label at the bottom.  Put a `goto end`  before `:Installed`

**Comment by PS3-Pro** [comment]
Something like this? It didn't work :P

```

wait 9
	wait 5
	/delete.ps3/dev_hdd0/tmp/explore/nsx
	/delete.ps3/dev_hdd0/tmp/explore/xil2
	
if exist /dev_flash/vsh/resource/explore/xmb/pro.xml
	popup PS3™ Pro Installed
	goto Installed
end if	
goto end

:Installed
if exist /dev_hdd0/home/$USERID$/localusername
	wait 2
	popup PS3™ Pro Logged In
else
	/pad.ps3?accept
	wait 4
	popup PS3™ Pro NOT Logged In
	beep3
end if

:end
popup END



```

**Comment by aldostools** [comment]
You had a missing `end if` before `goto end`... I edited your post.
