### ISSUE TITLE
Webman mounting games randomly

### ISSUE THREAD

**Issue by Kamletue** [aldostools/webMAN-MOD#736]
So hey, I was looking at my photos on the ps3 but when I choose one, a number appears as a notification mostly saying "6" or 3" or just nothing, but some photos will mount iso games installed. It's weird. Any fix ?

**Comment by aldostools** [comment]
This is a feature called "PhotoGUI" that allows to mount games using the Photo column, instead of the game column.

It can be disabled in /setup.ps3 unchecking the option ""PhotoGUI (USB0/PICTURE) | Poll wm_request" and saving the settings.

**Comment by Kamletue** [comment]
I cant find the option..

**Comment by aldostools** [comment]
![image](https://user-images.githubusercontent.com/974897/178148837-9b793929-c0b2-472b-8ef6-1b99ba83ab39.png)

Remember to SAVE the settings.

**Comment by Kamletue** [comment]
Thanks!
