### ISSUE TITLE
psp launcher not unlocking /error 80010006 on 4.84 cobra 8.3

### ISSUE THREAD

**Issue by TheNikdo** [aldostools/webMAN-MOD#742]
Hello aldostools
 Firstly i would like to thank you for your work on webman and other things for ps3 community.
 
 
 I got this problem i updated firmware and webman.
 Everything works good ,but webman is not unlocking the psp lauchers it mounts the iso tells me to use the laucher but error 80010006.
I dont know if its webman error or the cfw but when i uninstal webman and mount iso thru file explorer it works normaly.

**Comment by TheNikdo** [comment]
Maybe i should specifi that i instaled rebug 4.84.2 cobra 8.3 mod + xai plugin and cfw tools menu.

Edit:Sorry i closed this submit by akcident,reopening Now

**Comment by aldostools** [comment]
Please re-install the PSP Launchers found in
https://github.com/aldostools/webMAN-MOD/releases

There are some versions of PSP Launchers in Brewology and published on other sites that are not compatible.

If the problem persists, unlock the launchers using http://0/unmap.ps3 or the menu option  webMAN Games > webMAN Setup > Redirect USB000 > Unmap PS3

**Comment by TheNikdo** [comment]
Thanks for reply but i reinstaled both launchers And webman And unmaped the usb000  but lunchers Are still blocked/locked.
![IMG20220716025244](https://user-images.githubusercontent.com/109368844/179328609-04e9bdd5-3ffd-4995-b760-6ceff6dc1610.jpg)

**Comment by aldostools** [comment]
Is Cobra enabled? If it isn't it may be the cause of your issue.

PSP Launchers are unlocked automatically as soon as you mount a PSP ISO.

If you mount something else, the PSP launchers will be locked again.

**Comment by TheNikdo** [comment]
Yes cobra Is enabled 
![IMG20220716033453](https://user-images.githubusercontent.com/109368844/179329741-cd82a926-6a23-4bd0-96dc-a2af41697e78.jpg)

**Comment by aldostools** [comment]
If you mount a PSP ISO with webMAN MOD, the PSP Launchers must be unlocked. 
Otherwise they will remain locked to prevent a system freeze if the user accidentally start them without a PSP ISO.

If you unmount the ISO or mount a ROM, DVD, BD, PS1, PS2 or PS3 game the PSP Launchers will be locked again.

**Comment by TheNikdo** [comment]
Yes i understand but the launchers dont unlock on my console i dont know why.
Do you have any other sugestion i could try ?

I know i am asking too much right Now but maybe just maybe would it ve possible for you to build me a test build of new webman without the locking function of course if you dont have time or its way to complicated i will simply give up and play it on my psp or emulate on pc

**Comment by aldostools** [comment]
An alternative is to disable webMAN MOD and use IRISMAN or mmCM to mount PSP games.

I know it's not ideal, but I don't know why it is not unlocking the PSP launchers on your system.
The PSP games that I tested unlocked the launchers.

**Comment by TheNikdo** [comment]
Ok ill try irisman or mmcm And when i got time maybe backup And full format my console.

Thank you for your time.

**Comment by meeeeeeeeeeeeeeee** [comment]
I have the same problem on my CEX CECHL01 with evilnat 4.89 and cobra 8.30, without webman installed the PSP remasters launcher and PSP minis launcher show up on the XMB like they are supposed to but multiman says I need to update them (I have the newest versions from here installed), if the newest version of webman mod is installed I get the 80010006 error when the launchers are first installed and used then after a reboot they turn into corrupted data that cannot be deleted until webman is uninstalled.

**Comment by aldostools** [comment]
PSP launchers must be unlocked before reinstall / update them (it is NOT necessary to update them after they are installed).

There are 3 methods to unlock PSP launchers:
1- If a PSP ISO is mounted
2- Using http://0/unmap.ps3 on PS3 Internet browser
3- Using the menu option: webMAN Games > webMAN Setup > Redirect USB000 > Unmap PS3
