### ISSUE TITLE
Error 403 forbidden when connecting over HTTP and 451 over FTP

### ISSUE THREAD

**Issue by webodan** [aldostools/webMAN-MOD#747]
I'm using the latest version of WebMAN-MOD, 1.47.42, and I'm getting this today. Some other time I had the same issue, rebooting made it go away, but now it just won't go away regardless of shutting down or rebooting. It's pretty annoying, might have to downgrade or somthing until it's fixed.

- I  was using the LITE version, tried switching to Full, didn't fix it.
- I tried deleting webMAN's settings using delete.ps3, then reboot.ps3, still didn't fix it.
- Gonna try downgrading... Went down to 1.47.34, and it's still happening. Guess i'll wait for some help, maybe try checking the filesystem on the ps3's hdd but at this point i'm legit confused...

**Comment by aldostools** [comment]
I suggest that verify if the PS3 Internet browser allows to navigate. If not, try to reconfigure your network settings.

If the issue persists,  do a clean install of webMAN MOD uninstalling it first. Also try to reinstall the firmware or restore default settings or restore system. 

Also test with wired and wireless network. 

If nothing works it could be a hardware issue or a network configuration issue outside the PS3.

**Comment by webodan** [comment]
i checked FS and rebuilt database, then it worked again, but it went back to 403 forbidden after shutting the console down, then booting up after an hour or so... then maybe it's the hard drive? bummer...

oh, yeah, it did work by browsing it thru the ps3, it's just connecting from other devices that it fails

**Comment by aldostools** [comment]
If your system is NOR, it could be related to the hard drive. If not it could be the wireless card or the Ethernet if you're using wired network. 

I would try reinstalling the CFW before format the HDD.

**Comment by webodan** [comment]
oh btw, on an older version after reinstalling the newest one, both FTP and web work again across reboots, but the web interface looks all weird, i prefer how it looked before downgrading. I installed 1.47.34

**Comment by aldostools** [comment]
It may be a coincidence. I don't remember that I made important changes in the web connection between these versions.

**Comment by webodan** [comment]
Yeah it was my issue, looks like having bad database/filesystem causes webman to throw forbidden over ftp and http for some reason. Been trying to get the error for a bunch of days but ever since I made sure everything was checked thoroughly it stopped doing it
