### ISSUE TITLE
[BUG] Write to Offset

### ISSUE THREAD

**Issue by PS3-Pro** [aldostools/webMAN-MOD#750]
Aldo something is not working here anymore

see, if i use /write.ps3/dev_hdd0/tmp/wm_config.bin&t=28&pos=0x154 for example

![image](https://user-images.githubusercontent.com/74815634/181456277-87ff3c5b-e43b-4377-8586-850dcd9a8672.png)

THe wrong value is written

![image](https://user-images.githubusercontent.com/74815634/181456422-b16a895d-fa1f-4a5b-976d-a310fb2d449f.png)

**Comment by PS3-Pro** [comment]
And about the text, does it have a meaning or not?

sometimes is 8write, Vwrite , Twrite and etc...



![image](https://user-images.githubusercontent.com/74815634/181457636-cd19d921-1802-4c03-8990-963e571ee28a.png)

**Comment by PS3-Pro** [comment]
One request is if the offset column identifier can be added, just like hex programs 00 01 02 03 and etc (i always need to count one by one to identify it while on webMAN)


![image](https://user-images.githubusercontent.com/74815634/181459857-82a6704f-04cf-4abd-a63f-9aec15f85050.png)

**Comment by aldostools** [comment]
The 2 bugs reported should be fixed in the latest commit 754bbcf13996f0b20353e3b91c2c590637dee83f

IMO The column identifier would make the hex viewer look too busy.
