### ISSUE TITLE
Junk Text in "My Games" XMB entry

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#753]
Aldo any idea why in my system it always have a (1) in the "my games" entry? I have this problem for months

![image](https://user-images.githubusercontent.com/110236244/182282741-8a20d57a-f7f4-4801-b3e9-28ba4c0598cb.png)

**Comment by aldostools** [comment]
That indicates the extended user profile currently selected. Go to /setup.ps3 then expand the section "MEM Setup" and set "Profile" to "Default". Save the settings and scan again the content.

You could have selected it by mistake pressing the combo SELECT+L3+R2

Other related combos are:
SELECT+L3+L2 = Refresh XML + Profile 2 
SELECT+L3+R1 = Refresh XML + Profile 3
SELECT+L3+L1 = Refresh XML + Profile 4
SELECT+L3+L1+R1 = Refresh XML + Reload XMB
SELECT+L3+L2+R2 = Fail Safe (deletes /dev_hdd0/tmp/wm_config.bin and reboot to use the default settings)

**Comment by LuanTeles** [comment]
> That indicates the extended user profile currently selected. Go to /setup.ps3 then expand the section "MEM Setup" and set "Profile" to "Default". Save the settings and scan again the content.
> 
> You could have selected it by mistake pressing the combo SELECT+L3+R2
> 
> Other related combos are: SELECT+L3+L2 = Refresh XML + Profile 2 SELECT+L3+R1 = Refresh XML + Profile 3 SELECT+L3+L1 = Refresh XML + Profile 4 SELECT+L3+L1+R1 = Refresh XML + Reload XMB SELECT+L3+L2+R2 = Fail Safe (deletes /dev_hdd0/tmp/wm_config.bin and reboot to use the default settings)

Hehe i was thinking about that but i didn't remember using those combos lol.

EDIT: :facepalm: I found out why i always have profile 1 selected, for some reason i always press select button while doing QA COMBO lol.
