### ISSUE TITLE
slaunch minor issues

### ISSUE THREAD

**Issue by gosseux** [aldostools/webMAN-MOD#77]
I am using wmm 1.47.03

slaunch appears if I press start button when entering text.

There is some distortion at the top of the screen of slaunch.
It is as if the text written at the bottom of the screen repeats itself at the top many times but very tiny.

**Comment by aldostools** [comment]
Thank you for the feedback. Could you be more specific where you enter the text (internet search, browser, settings, other)?

I press start a few times while entering text in the browser & internet search, and slaunch didn't activate. Are you holding start button for a long period? The button polling is done every 3 seconds, maybe it's coinciding with the moment that you press start.

Regarding the screen distortion, maybe one of your game icons is corrupting the buffer. I haven't been able to reproduce the issue yet.

**Comment by gosseux** [comment]
I was on xmb changing album name of games to group them by customized name.  After entering the text I press start. The issue is not everytime, for example it happened 3 times in a row, not for 2 other, then happened again a few times
![img_20170313_191902](https://cloud.githubusercontent.com/assets/22871032/23879305/93fc8a2c-0822-11e7-86eb-042578d16edb.jpg)
.The distortion changes when I press square and is smaller when I don't have a usb device attached.

**Comment by gosseux** [comment]
new bug: 
![img_20170313_195058](https://cloud.githubusercontent.com/assets/22871032/23879968/e3ad4274-0826-11e7-98de-cb8c7fe6344b.jpg)
why is def_flash in the game list ?

**Comment by gosseux** [comment]
Is it possible to prevent Start button from calling slaunch (maybe a new option) ?

**Comment by aldostools** [comment]
To disable calling the game menu (sLaunch MOD) using L2/R2 or START, you should uncheck the option "GAME MENU" found in "XMB/In-Game PAD SHORTCUTS" section  of /setup.ps3

**Comment by Joonie86** [comment]
Closing old cases that have no further feedback. please use the latest version of wMM and report us
