### ISSUE TITLE
[Question] Where can i find PS3Mapi features in Web Page

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#770]
Aldo, where can i find the shortcuts for /vshplugin.ps3mapi, /kernelplugin.ps3mapi, /gameplugin.ps3mapi and other ps3mapi features using the webman page?

![image](https://user-images.githubusercontent.com/110236244/188108115-e272f3dc-d583-4af1-825b-3ebe98c7c1d7.png)

I cannot find any link for 

![image](https://user-images.githubusercontent.com/110236244/188108293-0573411d-83ff-4e66-97c5-5751bdaba38c.png)

as example

**Comment by LuanTeles** [comment]
NVRM seems it only is displayed when cobra is enabled hehe

Finally my issue with /xmb.ps3$screenshot/ is solved, seems it requires cobra too.


[Feature Request] Can features that require COBRA shows a notification when it is not Enabled? Something like 'This feature requires Cobra, please enable it' , here the system just freezes.

BTW, i wonder why my COBRA always disables itself o.O

Edit: It looks like it's the failsafe feature introduced in Cobra 8.3, I wonder if it's really a good idea as just going into recovery mode disables it leading to a lot of issues for the user like webman features freezing the ststem or psp/ps2 playback issues

**Comment by aldostools** [comment]
> Edit: It looks like it's the failsafe feature introduced in Cobra 8.3, I wonder if it's really a good idea as just going into recovery mode disables it leading to a lot of issues for the user like webman features freezing the ststem or psp/ps2 playback issues

That feature that disables Cobra when the user goes to recovery menu has been there for many years.

The failsafe feature introduced in Cobra 8.3 disables Cobra only if the payload fails to load completely.
Anyway this new feature is going to be replaced with a new method suggested by haxxxen that allows to load a custom payload from USB.

In regards to the freezing issues that you mention, they should not happen in the recent builds due webMAN Games menu is not shown when Cobra is disabled.

I have suggested to Evilnat to use new icons to make more evident when Cobra is enabled or not. That feature is pending to be implemented for the next CFW release.

**Comment by aldostools** [comment]
> [Feature Request] Can features that require COBRA shows a notification when it is not Enabled? Something like 'This feature requires Cobra, please enable it' , here the system just freezes.

webMAN requires Cobra and CFW syscalls enabled for almost everything. this request would require to add a notification for almost all the features.

**Comment by LuanTeles** [comment]
> In regards to the freezing issues that you mention, they should not happen in the recent builds due webMAN Games menu is not shown when Cobra is disabled.
> 

I was using web commands and some custom XMBML items, but if cobra is disabled and the user try a web command that requires cobra, can it show a message to enable cobra for that feature or is it too much hassle?

EDIT2: Just saw you last comment, it's ok then as the method that disable cobra by entering into recovery mode will be changed


> I have suggested to Evilnat to use new icons to make more evident when Cobra is enabled or not. That feature is pending to be implemented for the next CFW release.

But if we enter in recovery mode the icon will not change if cobra is disabled, maybe a custom plugin could detect it and swap icons.

EDIT: Oh, with the USB method it won't be needed
