### ISSUE TITLE
Disable syscalls on startup : Lock PSN

### ISSUE THREAD

**Issue by illusionalDEX** [aldostools/webMAN-MOD#776]
once i enabled the options in webMAN setup and restarted the console i will instantly freeze on startup 

- i have CCAPI installed
- 4.84.2 D-REX Cobra Updated to 8.3

**Comment by aldostools** [comment]
Go to recovery menu to remove the boot_plugins.txt and prevent that any plugin is loaded.

Exit from recovery menu without perform any action. The system should reboot normally.

After return to XMB, run a File Manager like multiMAN or IRISMAN and delete /dev_hdd0/tmp/wm_config.bin

Reinstall webMAN MOD but don't select the option that disable the CFW syscalls on startup. CCAPI relies on these syscalls and disabling them may cause unexpected errors that are beyond my knowledge (CCAPI is closed code and I don't have idea of what it is doing).

**Comment by illusionalDEX** [comment]
> Go to recovery menu to remove the boot_plugins.txt and prevent that any plugin is loaded.
> 
> Exit from recovery menu without perform any action. The system should reboot normally.
> 
> After return to XMB, run a File Manager like multiMAN or IRISMAN and delete /dev_hdd0/tmp/wm_config.bin
> 
> Reinstall webMAN MOD but don't select the option that disable the CFW syscalls on startup. CCAPI relies on these syscalls and disabling them may cause unexpected errors that are beyond my knowledge (CCAPI is closed code and I don't have idea of what it is doing).

thanks for the reply i was able to disable the option with my web browser on computer just took several restarts
