### ISSUE TITLE
After Pressing most buttons on webMAN Mod makes my PS3 Slim CFW Evilnat Crashed

### ISSUE THREAD

**Issue by szymonszyszy** [aldostools/webMAN-MOD#779]
I don't know why it's making my PS3 crashed from pressing any button on webMAN for no reason, Please help me and fix the problem

Thank you.

- Szymon

**Comment by aldostools** [comment]
Maybe another plugin running in background could be causing the crash.

Try uninstalling webMAN MOD and delete /dev_hdd0/boot_plugins.txt

Then reinstall webMAN MOD, go to /setup.ps3 using the web browser, uncheck all combos, save the setting and restart.

If the problem persists you may need to check the health of your HDD and probably reinstall the CFW.

If you're on 4.89, I highly recommend you that enable QA flags and downgrade to 4.88 because the 4.89 has several system files (rco) broken, due a bug introduced by Sony in the latest firmware release.

**Comment by szymonszyszy** [comment]
It dosen't work kinda but maybe because of abusing it with plugins from trophies or just is it me or did i enabled something worse?

**Comment by szymonszyszy** [comment]
> Maybe another plugin running in background could be causing the crash.
> 
> Try uninstalling webMAN MOD and delete /dev_hdd0/boot_plugins.txt
> 
> Then reinstall webMAN MOD, go to /setup.ps3 using the web browser, uncheck all combos, save the setting and restart.
> 
> If the problem persists you may need to check the health of your HDD and probably reinstall the CFW.
> 
> If you're on 4.89, I highly recommend you that enable QA flags and downgrade to 4.88 because the 4.89 has several system files (rco) broken, due a bug introduced by Sony in the latest firmware release.
It dosen't work kinda but maybe because of abusing it with plugins from trophies or just is it me or did i enabled something worse?

**Comment by szymonszyszy** [comment]
> Maybe another plugin running in background could be causing the crash.
> 
> Try uninstalling webMAN MOD and delete /dev_hdd0/boot_plugins.txt
> 
> Then reinstall webMAN MOD, go to /setup.ps3 using the web browser, uncheck all combos, save the setting and restart.
> 
> If the problem persists you may need to check the health of your HDD and probably reinstall the CFW.
> 
> If you're on 4.89, I highly recommend you that enable QA flags and downgrade to 4.88 because the 4.89 has several system files (rco) broken, due a bug introduced by Sony in the latest firmware release.

But I will say trying uninstalling or reinstalling webMAN mod in 4.88 that was downgraded doesn't work but I maybe forgot to uncheck all combo but is it just me or did I just enabled something corrupted?

**Comment by aldostools** [comment]
You probably did something wrong. If you downgraded to CFW 4.88 and did a clean install the f webMAN MOD, it should work.

**Comment by szymonszyszy** [comment]
I found the solution to fix it. First, install again webMAN MOD again if you already install it and it will fix anything so include updated games and XMB refreshes start to work.

And now it works with 4.89 and 4.89 can be compatible but at least you can reinstall the Full version and Full Version is recommended for this issue and now it is fixed, by myself. Thank you for everything and now this issue was fixed from September 18 to 1 December.

Thank you and Goodbye. Szymon.

**Comment by Masamune3210** [comment]
> Maybe another plugin running in background could be causing the crash.
> 
> Try uninstalling webMAN MOD and delete /dev_hdd0/boot_plugins.txt
> 
> Then reinstall webMAN MOD, go to /setup.ps3 using the web browser, uncheck all combos, save the setting and restart.
> 
> If the problem persists you may need to check the health of your HDD and probably reinstall the CFW.
> 
> If you're on 4.89, I highly recommend you that enable QA flags and downgrade to 4.88 because the 4.89 has several system files (rco) broken, due a bug introduced by Sony in the latest firmware release.
> 

Sorry for the off topic, but is there anywhere I can find information on this bug? I'm just being curious and like reading about this kind of stuff so no big deal if not

**Comment by aldostools** [comment]
Yes, you can find information about it on PSX-PLACE forum.
Sandungas (one of the forum's moderator) created a fix, but it partially fixes the issue.

**Comment by Masamune3210** [comment]
Thanks!

**Comment by szymonszyszy** [comment]
> Thanks!

That was my long time issue that wasn't fixed but it was right now. and it was an issue with most buttons on webMAN Mod it got fixed by reinstalling the Full version if you already downloaded the Full version Well after you reinstalled it you will get it: Fixed XMB reloads and your games will be updated and most buttons start to work in 4.89 and this is now fixed and I found the solution by myself to fix this problem.

**Comment by aldostools** [comment]
Reinstalling is one of the first steps suggested in the troubleshooting guide:
https://github.com/aldostools/webMAN-MOD/wiki#troubleshooting

**Comment by szymonszyszy** [comment]
> Reinstalling is one of the first steps suggested in the troubleshooting guide: https://github.com/aldostools/webMAN-MOD/wiki#troubleshooting

Ok.
