### ISSUE TITLE
ps3netsrv daemon mode

### ISSUE THREAD

**Issue by xswqaz** [aldostools/webMAN-MOD#78]
Want to add daemon mode to ps3netsrv with -d option

Thank you

**Comment by aldostools** [comment]
Try deamonizing the process redirecting the output to null and using nohup.

$ nohup ps3netsrv /shared 38008 & &> /dev/null

**Comment by Joonie86** [comment]
Closing old issues that have no further feedback. Please try the latest wMM and report back.
