### ISSUE TITLE
Suggestion. Safety features removed

### ISSUE THREAD

**Issue by gosseux** [aldostools/webMAN-MOD#784]
You removed 2 features lately: PSN access and PSP launchers blockers.  As I understand, there is an issue with map path when using the  latest firmware.
Maybe you could simply rename or move the files or folders instead.  Or add options in setting to enable these features.

**Comment by aldostools** [comment]
These features are available in the source code, only commented.
They are also available in the version 1.47.41 if someone need them. 
PSNpatch is another alternative that everyone used before the PSN blocker was added.

The features removed are minor features that only caused complains.
