### ISSUE TITLE
freezer on hen activation screen

### ISSUE THREAD

**Issue by Viniciaao** [aldostools/webMAN-MOD#786]
I installed 3 themes in the tmp/themes folder and now I can't start hen, is there any way around this 

I'm using the latest version of the last pkg upload done

**Comment by aldostools** [comment]
Put an empty file `boot_plugins.txt` of 0 bytes in the root of /dev_usb000

Enable HEN... it will prevent that any plugin is loaded. Go to multiMAN or IRISMAN and delete the files that are causing the freeze.

Remove the USB device or delete the empty `boot_plugins.txt`, reboot and enable HEN again.

**Comment by Viniciaao** [comment]
yes, I didn't remember that procedure because I'm in Panic, thank you very
much anyway

Em sáb., 1 de out. de 2022 2:28 PM, Aldo Vargas ***@***.***>
escreveu:
