### ISSUE TITLE
1.47.03 freeze problem

### ISSUE THREAD

**Issue by kbyter75x** [aldostools/webMAN-MOD#79]
If you enter any game folder inside /DEV_HDD0/GAME via web browser, the PS3 will freeze and the power button will stop responding (only two beeps when you hit it). So, you will have to pull off the AC cable and put it on again and turn the PS3 on for it to work again.

**Comment by masterzorag** [comment]
👎 **NEVER "pull off the AC cable" !!!** 👎 
Instead, keep off button pressed until ps3 powers off (4 seconds or so...)

**Comment by bdandy** [comment]
@masterzorag sometimes pressing power button doesn't help

**Comment by aldostools** [comment]
Try holding down the power button for 15-20 seconds... the console will turn off without having to unplug the power cable.

**Comment by Joonie86** [comment]
Closing old issues that have no further feedback. Please try the latest wMM and report back.
