### ISSUE TITLE
download.ps3 considers data url as invalid

### ISSUE THREAD

**Issue by HenrINC** [aldostools/webMAN-MOD#791]
http://<ps3_ip>/download.ps3?url=data:text/plain;base64,VEVTVA==?to=dev_hdd0/test.txt should create a test.txt file on dev_hdd0 containing "TEST"

But i'm getting a 400 error "ERROR: Invalid URL Download canceled"

**Comment by aldostools** [comment]
Hello Henri,
Thank you for you comments. As far as I know, the VSH method download_interface->DownloadURL mainly supports http and https addresses.

By the way, there are 2 errors in your URL (missing / in /dev_hdd0 and the order of the parameters). The correct syntax is this:
`/download.ps3?to=`&lt;path>`&url=`&lt;url>

If you want to save a text to a local file, you should use one of the following web commands:
`/edit.ps3?f=`&lt;path>`&t=`&lt;text>
`/write.ps3/`&lt;path>`&t=`&lt;text>

e.g.
http://&lt;ps3_ip>/edit.ps3?f=/dev_hdd0/test.txt&t=TEST

For additional information information about the web commands visit:
https://github.com/aldostools/webMAN-MOD/wiki/Web-Commands

**Comment by HenrINC** [comment]
Thanks for your answer
