### ISSUE TITLE
Add the ability to group PSN/PKG titles in webMAN MOD, and be able to launch them there.

### ISSUE THREAD

**Issue by kernaltrap8** [aldostools/webMAN-MOD#792]
Hello,
A user on the Playstation Homebrew discord would like this feature added, as they want all backups (JB Folder in this case) to be grouped alongside PKG/PSN games.

This could be done with simple editing to the content scanner in webMAN MOD, however I have no idea how to do this (even tho I know JS/HTML)

If this could be implemented, that would be great
Thanks,
James

**Comment by aldostools** [comment]
It is not a "simple editing of the content scanner". That module is very complex to maintain... 

For PSN/PKG I recommend to use the Album mode, which is an official feature of XMB.
[![Create PS3 Album](https://img.youtube.com/vi/SovS4R-Q_OE/0.jpg)](https://www.youtube.com/watch?v=SovS4R-Q_OE)

**Comment by kernaltrap8** [comment]
Ah, I see, maybe I could contribute if you need extra help. The user wants all backups and PSN titles to be contained in webMAN Games. If this is not possible or perhaps too hard/not practical, I can explain so to the user.

Oh and a side note for myself, can I put special charecters in Album names? (such as the star that is next to REBUG TOOLBOX)

**Comment by aldostools** [comment]
You can uncheck webMAN Games in /setup.ps3 to make the subfolders appear directly on Games column and next to the albums.

Yes, you can use special characters in Album names.

**Comment by kernaltrap8** [comment]
Hey, thanks mate. Will try out the special characters after I unbrick my PS3 
Long story short, I used the wrong stage2 for DEX, and I have to format the HDD outside the console to enter recovery to reinstall DREX, because I cant boot VSH, or even get into recovery (will show Cannot start if HDD is removed and console is booted.)
Have a nice rest of your day/night,
James
