### ISSUE TITLE
Can't get three drives scanned - Upper limit to game count?

### ISSUE THREAD

**Issue by mdlarussa** [aldostools/webMAN-MOD#793]
Three external 2TB drives, MBR/FAT32.  One directly attached to USB2 (appearing as USB001), two attached via powered, official playstation usb hub to USB1 (appearing as USB006 and USB007).  All browseable via file manager.  001 has PS3ISO and PSPISO, 006 has PSXISO and GAMEI, 007 has PS3ISO.  For some reason, I can't get all three to successfully scan and be visible to WebmanMOD.  Any combination of two will work fine if I leave one unplugged.

Is there a max number of supported games? I think i'm at about 3k games across all platforms.  XML scan takes under 10 minutes.

**Comment by aldostools** [comment]
Yes there are different max count based on the selected memory usage in /setup.ps3
https://github.com/aldostools/webMAN-MOD/wiki/~-Plugin-Memory-Usage

**Comment by mdlarussa** [comment]
Worked like a charm.  Thank you very much for the help!
