### ISSUE TITLE
/dev_hdd0/autoexec.bat not working

### ISSUE THREAD

**Issue by mdlarussa** [aldostools/webMAN-MOD#794]
I tried writing a multi-line boot up script remapping several hdd0 folders to usb alternatives, mainly to free up internal space for PS2 isos.  

```
logfile /dev_hdd0/boot.log
if exists /dev_hdd0/game; log "hdd0-game already exists"
md /dev_hdd0/game; log "created hdd0/game"
map /dev_hdd0/game=/dev_usb000/game; log "mapped hdd game to point to usb game"
map /dev_hdd0/GAMES=/dev_usb000/GAMES; log "mapped hdd games to point to usb games"
map /dev_hdd0/GAMEI=/dev_usb000/GAMEI; log "mapped hdd gamei to point to usb gamei"
log "Script completed!"
```

However, I can't get the script to fire on reboot, either as boot_init.ini or autoexec.bat.  I see several txt files in the root of the hdd (boot_plugins*.txt) that look like they're doing stuff for WMM as well.  Could I name it similar to those?

I stripped down my script to a single line:
```
/extgd.ps3?1
```
But it still doesn't fire off.  Or maybe it does but doesn't successfully complete.  I can run that command in the browser and immediately see the results, so I'm just not sure why it isn't working at startup.

Is this how you would handle redirecting games/GAMEI/etc. to external?  If it isn't please let me know so I can explore other options, if any.

**Comment by aldostools** [comment]
Thank you for your comments.

Lite edition doesn't include support for batch scripts. Please make sure that you're using full or standard edition.

In batch scripts, the command separators is the line break. The semicolon is used at the beginning of the line for remarks. The semicolons can be used as command separator in URL lines that start with /

If you're running on CFW, the plugin is loaded even before the TV shows the display. Therefore autoexec.bat is executed before XMB or USB devices are loaded. I recommend to include `wait 
xmb` or `lwait /dev_usb000` at the beginning of the script.

You can add the command `beep` or `beep2` or `beep3` to have feedback when the script is running.

The `if` block should be terminated with `end if` or `end`. It can contain 1 or more commands is separated lines.

**Comment by mdlarussa** [comment]
so file is saved as /dev_hdd0/boot_init.ini, but I also tried with it saved as /dev_hdd0/autoexec.bat.

```
lwait /dev_usb000
logfile /dev_hdd0/boot.log
beep
log @info11
log @info13
log @info14
log @info17
log @info20
log @info24
if exists /dev_hdd0/game
log "hdd0-game already exists"
del /dev_hdd0/game
end if
md /dev_hdd0/game
log "created hdd0/game"
map /dev_hdd0/game=/dev_usb000/game
log "mapped hdd game to point to usb game"
map /dev_hdd0/GAMES=/dev_usb000/GAMES
log "mapped hdd games to point to usb games"
map /dev_hdd0/GAMEI=/dev_usb000/GAMEI
log "mapped hdd gamei to point to usb gamei"
log "Script completed!"
beep2
```

no go for execution, I do a hard reboot via Ultimate Toolbox, it goes blank, yellow-green leds, then comes back on.

**Comment by mdlarussa** [comment]
I tried both file names with simply ```/buzzer.ps3mapi?snd=1``` followed by a blank line.  No luck there either.

**Comment by mdlarussa** [comment]
For some reason, reinstalling WMM fixed the issue.  Maybe the full install didn't complete or got corrupted.  My script seemed a too complicated to really troubleshoot, so I simplified it to: 
```
lwait /dev_usb006
logfile /dev_hdd0/boot.log
/buzzer.ps3mapi?snd=3
/extgd.ps3?1
/buzzer.ps3mapi?snd=2
```

**Comment by aldostools** [comment]
Probably you installed the lite edition inadvertently. I'm glad that you got it working.
