### ISSUE TITLE
[Question] Centralized Cheat Database

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#795]
How can i rename that kind of cheat files to use in /dev_hdd0/tmp/artemis/?

LittleBigPlanet BCAS20078 BCES00141 BCES00611 BCUS98148 v01.00 av01.30 tv01.28.ncl

I'm doing this way 

BCAS20078_01.00.ncl
.
.
.
BCUS98148_01.00.ncl
.
.
.
BCAS20078_01.30.ncl
.
.

What av and tv means? it supports up to v1.30? and what about v01.28?

![image](https://user-images.githubusercontent.com/110236244/199164630-cbe77013-33a7-4d04-9dc8-699302779034.png)

**Comment by LuanTeles** [comment]
> How can i rename that kind of cheat files to use in /dev_hdd0/tmp/artemis/?
> 
> LittleBigPlanet BCAS20078 BCES00141 BCES00611 BCUS98148 v01.00 av01.30 tv01.28.ncl
> 
> I'm doing this way
> 
> BCAS20078_01.00.ncl . . . BCUS98148_01.00.ncl . . . BCAS20078_01.30.ncl . .
> 
> What av and tv means? it supports up to v1.30? and what about v01.28?
> 
> ![image](https://user-images.githubusercontent.com/110236244/199164630-cbe77013-33a7-4d04-9dc8-699302779034.png)

**Comment by LuanTeles** [comment]
BLJM60218_v01.00_av01.00.ncl

It confuses me as well :P

**Comment by aldostools** [comment]
The file names come from the original names used on @bucanero's database.
I guess av means app version or alternative version.

The centralized codelist database copies the .ncl automatically to `/dev_hdd0/tmp/art.txt` when webMAN detects during the process polling that a game is running and finds a file like `/dev_hdd0/tmp/artemis/BLES12345_01.00.ncl`

The artemis option must be checked in /setup.ps3

This is the code that performs that feature:
![image](https://user-images.githubusercontent.com/974897/199242602-5961cb4c-1777-474c-845b-efd0f09aa1a8.png)
