### ISSUE TITLE
[Question] Payload Order

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#798]
Aldo

I use

`if Mamba
	move /dev_hdd0/game/PS34KPROX/USRDIR/toolbox/xmls/CFW_Cobra_Tools.xml,/dev_hdd0/game/PS34KPROX/USRDIR/toolbox/xmls/CFW_Cobra_Tools.off
	move /dev_hdd0/game/PS34KPROX/USRDIR/toolbox/xmls/CFW_Mamba_Tools.off,/dev_hdd0/game/PS34KPROX/USRDIR/toolbox/xmls/CFW_Mamba_Tools.xml

elseif Debug
	move /dev_hdd0/game/PS34KPROX/USRDIR/toolbox/xmls/CFW_Cobra_Tools.off,/dev_hdd0/game/PS34KPROX/USRDIR/toolbox/xmls/CFW_Cobra_Tools.xml
	move /dev_hdd0/game/PS34KPROX/USRDIR/toolbox/xmls/CFW_Mamba_Tools.xml,/dev_hdd0/game/PS34KPROX/USRDIR/toolbox/xmls/CFW_Mamba_Tools.off
	copy /dev_hdd0/game/PS34KPROX/USRDIR/toolbox/icons/on.png,/dev_hdd0/game/PS34KPROX/USRDIR/toolbox/icons/payloads/cobra/debug_mode.png
	copy /dev_hdd0/game/PS34KPROX/USRDIR/toolbox/icons/off.png,/dev_hdd0/game/PS34KPROX/USRDIR/toolbox/icons/payloads/cobra/release_mode.png

elseif Cobra
	move /dev_hdd0/game/PS34KPROX/USRDIR/toolbox/xmls/CFW_Cobra_Tools.off,/dev_hdd0/game/PS34KPROX/USRDIR/toolbox/xmls/CFW_Cobra_Tools.xml
	move /dev_hdd0/game/PS34KPROX/USRDIR/toolbox/xmls/CFW_Mamba_Tools.xml,/dev_hdd0/game/PS34KPROX/USRDIR/toolbox/xmls/CFW_Mamba_Tools.off`

I need to add checks for  noCobra, PS3HEN and DEX, what order should i use? is there any check for CEX?  i need it for reverting the changes if the user returns to CEX after the DEX contition is performanced before,

**Comment by aldostools** [comment]
I haven't tested this code, but I think something like this should work:
````vb
if noCobra
move /dev_hdd0/a/file1,/dev_hdd0/file2
else if Cobra
move /dev_hdd0/b/file1,/dev_hdd0/file2
else if Debug
move /dev_hdd0/c/file1,/dev_hdd0/file2
else if Mamba
move /dev_hdd0/d/file1,/dev_hdd0/file2
else if PS3HEN
move /dev_hdd0/e/file1,/dev_hdd0/file2
end if

**Comment by LuanTeles** [comment]
> I haven't tested this code, but I think something like this should work:
> 
> ```vbnet
> if noCobra
> move /dev_hdd0/a/file1,/dev_hdd0/file2
> else if Cobra
> move /dev_hdd0/b/file1,/dev_hdd0/file2
> else if Debug
> move /dev_hdd0/c/file1,/dev_hdd0/file2
> else if Mamba
> move /dev_hdd0/d/file1,/dev_hdd0/file2
> else if PS3HEN
> move /dev_hdd0/e/file1,/dev_hdd0/file2
> end if
> ```

i remember you saying to use MAMBA before COBRA as MAMBA is part of cobra [here](https://github.com/aldostools/webMAN-MOD/issues/744)

" elseif Debug must be checked before Cobra.
Mamba & Debug are also Cobra. So Cobra must be the last check.
The last else is not necessary if you are not going to put commands between else and end if."

now thinking about that, isn't PS3HEN part of cobra too? as it is a pseudo cobra 8.1?

**Comment by aldostools** [comment]
Yes, you're right. I used the same order as they appear in the source code.

Mamba and HEN are "Cobra" too.  So "Cobra" should be tested after them.

**Comment by LuanTeles** [comment]
Thanks Aldo, i'll try it

**Comment by LuanTeles** [comment]
So i'm using this way, Is it right?

The "no cobra" is just to enable it back as it is disabled if the user enters in recovery mode and most users don't know it and how to enable it back.

![image](https://user-images.githubusercontent.com/110236244/199811343-6191019d-9fe6-496f-9464-f6d0dcc8b6f6.png)

**Comment by LuanTeles** [comment]
Other question is there a way to use "if firmware" to firmwares lower and highter than?

e.g 

If firmware > 4.xx
move ....

and 

If firmware < 4.xx
.
.
.

**Comment by aldostools** [comment]
No. It checks specific versions.

**Comment by Debuggerpro88** [comment]
The WEBMAN went you trying put FPS the pS3 Shutting down sometime the problem maybe is the FPS COUNTER
