### ISSUE TITLE
Cant set "info" to "None" in Webman Mod Setup page

### ISSUE THREAD

**Issue by korn3r** [aldostools/webMAN-MOD#80]
In "Webman Mod Setup" i cant set "info" parameter to None - it always changes back to "ID".

**Comment by aldostools** [comment]
Thank you for your feedback. The issue has been fixed in the current build of webMAN MOD 1.47.04+4.

You can re-download the latest version from the following link:
https://github.com/aldostools/webMAN-MOD/releases/latest
