### ISSUE TITLE
[Feature Request] Packet Monitor

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#806]
Aldo would be possible to add a feature for network monitoring? so we can see what ps3 are sending/receiving from network?

**Comment by aldostools** [comment]
/cpursx.ps3 shows what is being transferred through ftp. But it isn't detailed, only the last file accessed.

The source code is open if you need custom features like the one you requested.

**Comment by LuanTeles** [comment]
I'm trying to capture the PS Store .xml as i'm trying to customize it
https://www.psx-place.com/threads/accessing-the-old-and-faster-psn-store.38468/#post-348787

I can't use a packet monitor due to my faulty lan port

Thanks for the info aldo, i didn't know that /cpursx.ps3  shows what is being transferred through ftp, it is really nice.

**Comment by kostirez1** [comment]
@LuanTeles is the PS Store traffic encrypted? If it's not, you should be able to capture it using any proxy software running on the same network as your PS3, such as [OWASP ZAP](https://www.zaproxy.org/) or [Fiddler](https://www.telerik.com/fiddler/fiddler-classic). ZAProxy even allows you to capture and modify encrypted traffic, but you would have to disable certificate verification to accept self-signed certificates.

**Comment by aldostools** [comment]
Many years ago I used Charles proxy with a custom certificate to sniff the traffic of the PSN store.

I don't know if Charles still works with PS3 encrypted traffic, but it would worth a try.

**Comment by Masamune3210** [comment]
As far as I know, it should still work for the most part at least, they cant change the security that the PS3 uses much since A. It would take a major retooling of the PSN client on the PS3 or a complete cutoff if they were unwilling, and B. They know the console is mostly lost since if they changed the keys or something, people could just get the new ones with a phat

**Comment by Masamune3210** [comment]
At least, as far as I understand it
