### ISSUE TITLE
Adding ps3mapi_process_page_allocate & ps3mapi_process_page_free to PS3MAPI server

### ISSUE THREAD

**Issue by TheRouletteBoi** [aldostools/webMAN-MOD#807]
Can the following be added to ps3mapi_server.h

MEMORY
int ps3mapi_process_page_allocate(process_id_t pid, u64 size, u64 page_size, u64 flags, u64 is_executable, u64 *page_table)
int ps3mapi_process_page_free(process_id_t pid, u64 flags, u64 *page_table)

THREAD
int ps3mapi_create_process_thread(process_id_t pid, thread_t *thread, void *entry, u64 arg, int prio, size_t stacksize, char *threadname)

MODULE
int ps3mapi_get_process_module_segments(process_id_t pid, sys_prx_id_t prx_id, sys_prx_module_info_t *info)

**Comment by aldostools** [comment]
Yes, but if you make a pull request it would be easier / faster...

I could try to implement these functions in the weekend, but it may take even more time due I'm busy dealing with some personal subjects.
