### ISSUE TITLE
Can't Set Memory or Read Memory with PS3MAPI

### ISSUE THREAD

**Issue by avze** [aldostools/webMAN-MOD#809]
So I recently just got a new PS3 and installed webmanMOD 1.47.42 and I can connect and attach to the game using ps3mapi but just cant read memory or set memory with it. How Can I fix this issue?

**Comment by aldostools** [comment]
Please, verify if a previous version of webMAN MOD is able to get/set the process memory.

Latest build has changes in ps3mapi server. It requires to be enabled in /setup.ps3 (the PS3MAPI option found in the section for combo shortcuts). The option is disabled by default. If it is enabled, you must restart the console to get the ps3mapi server running.

You can get/set the process memory through the web interface or remotely using NetCheat (which requires ps3mapi server running).

**Comment by Mr-Beacon00** [comment]
> Please, verify if a previous version of webMAN MOD is able to get/set the process memory.
> 
> Latest build has changes in ps3mapi server. It requires to be enabled in /setup.ps3 (the PS3MAPI option found in the section for combo shortcuts). The option is disabled by default. If it is enabled, you must restart the console to get the ps3mapi server running.
> 
> You can get/set the process memory through the web interface or remotely using NetCheat (which requires ps3mapi server running).

same issue here. 1.47.40 and lower version don't have this problem.
1.47.41 and higher version can't read memory from NetCheat or PS3MAPI Tools.

**Comment by aldostools** [comment]
Thank you for your feedback. Please use the old version until the cause of the fault in the current version is identified.

**Comment by aldostools** [comment]
@Mr-Beacon00 Could you try using this test build of 1.47.42?
[webftp_server_test_20221210.zip](https://github.com/aldostools/webMAN-MOD/files/10200344/webftp_server_test_20221210.zip)

I have changed a check for kernell_full in PASV introduced recently by @kostirez1 for FTP server (also implemented in PS3MAPI server). Iinstead of abort the connection, it will wait for 100ms and continue trying.
````C
	bool kernel_full = wait_for_new_socket();

	if(kernel_full)
	{
		sys_ppu_thread_sleep(100000);
		continue; // retrying
	}
````

**Comment by avze** [comment]
I replaced it in dev_hdd0/plugins and did a full reboot and tested it on my own application and netcheat and still can't read or write memory

**Comment by aldostools** [comment]
Thank you @avze for your feedback. 

In that case, I honestly don't know what could be the cause of the bug. I compared 1.47.40 vs 1.47.42 and the main change that could be related to this issue is that check for kernel_full in PASV.

If you need to use NetCheat, please use 1.47.40 until a fix is found.

**Comment by aldostools** [comment]
@avze  @Mr-Beacon00 please test this new build (replace the sprx in /dev_hdd0/plugins and reboot):
[webftp_server_test2_ps3mapi.zip](https://github.com/aldostools/webMAN-MOD/files/10202606/webftp_server_test2_ps3mapi.zip)

I found something weird parsing the NetCheat commands received by the PS3MAPI server

NOTE: Remember to enable ps3mapi in /setup.ps3
![image](https://user-images.githubusercontent.com/974897/206914888-8ac31de3-03d6-47cc-bfec-4f83a6cb2bdb.png)

**Comment by aldostools** [comment]
This is an updater pkg that includes more fixes to ps3mapi server. It is untested.
[updater_test.zip](https://github.com/aldostools/webMAN-MOD/files/10203647/updater_test.zip)

**Comment by Mr-Beacon00** [comment]
> This is an updater pkg that includes more fixes to ps3mapi server. It is untested. [updater_test.zip](https://github.com/aldostools/webMAN-MOD/files/10203647/updater_test.zip)

ok test complete I can read and write memory now

**Comment by GuillaumeMrNiato** [comment]
Work for me too on a DECR1000A thanks !
