### ISSUE TITLE
IDPS & MEM Settings -> "Profile" Cant be changed

### ISSUE THREAD

**Issue by korn3r** [aldostools/webMAN-MOD#81]
If i change "profile" in IDPS & MEM Settings, after reboot it reverts to "Default".
I`m using Russian language. Switched language to English - nothing changed, it still reverts to "Default" profile after reboot.
I could misunderstood purpose of that setting since i cant find information about it. I thought i could have different settings for different users: for example one user has "Offline" mode disabled, while other one has it enabled.
Sorry if that setting is working as intended or shouldnt work at all.

**Comment by Joonie86** [comment]
Closing old issues that have no further feedback. Please try the latest wMM and report back.
