### ISSUE TITLE
[Feature request] Implement a memory view

### ISSUE THREAD

**Issue by therevtanker2100** [aldostools/webMAN-MOD#810]
Can a memory view be implemented on webman setup that works kind of like bgtoolset? After you've of course added the software flasher publicly when it's fully tested and ready.

**Comment by aldostools** [comment]
There are already various hex viewers in webMAN MOD that let you view:
- /peek.lv1?&lt;address> => view LV1 memory
- /peek.lv2?&lt;address> => view LV2 memory
- /getmem.ps3mapi => view  process memory, LV1 memory, LV2 memory, FLASH memory, HDD0 sectors, USB0/USB1 sectors

They have their respective write command: /poke.lv1, /poke.lv2, /setmem.ps3mapi
