### ISSUE TITLE
[Issue] HDD Activity/Slow System on High Fan Speeds

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#821]
Aldo, every time my system hits high fan speeds it gets slow even booting and the hdd led activity becames intense, if i low the fan speeds below 80% the system becames normal again.

Any clue?

Manual mode or Dynamic Mode, if it gets like 80% the system gets slow

**Comment by LuanTeles** [comment]
LOL i set it to 95% and restarted, my system can't boot anymore lol

Black screen and hdd0 led on, it blinks before loading webman but as soon as the fan speed is loaded by webman it becomes slow

**Comment by LuanTeles** [comment]
If i remove the power cord to reset the fan values i can enter into recovery mode but if i let the system load webman fan speed and try to enter into recovery mode, it says system storage not found lol

Maybe a conflict with Nat new firmware? i think he disabled the deletion of boot_plugins.txt when entering into recovey mode, because webman is still loading, i'll revert back to 4.89.2 to disable the pluguins without needing to format my hdd

**Comment by aldostools** [comment]
Delete /dev_hdd0/tmp/wm_config.bin

**Comment by LuanTeles** [comment]
I lost my erk so i installed a DB fw + hen and i reseted the webMAN config, why this happened? lol
