### ISSUE TITLE
ps2 game not showing in webman game list

### ISSUE THREAD

**Issue by ilqar200** [aldostools/webMAN-MOD#835]
Hello. I have problem with webman. I searched about this problem but not found solution. I have webman mod latest installed on my ps3 with hen.. I have installed ps2 game Gta Vice city (.pkg file) on my ps3 . The game itself works fine. But it not shows in webman game list . I have tried to select option MAX PS2+ (368K PS3 + 768K PS2) and mc option with 4-bg value and restarted ps3 . I have also tried refresh xmb and game list in webman . But all of this has no effect.The game not showing in webman game list . How to solve this problem ? thanks.

**Comment by aldostools** [comment]
webMAN only shows the PS2 games stored as .iso or .BIN.ENC in the folder /dev_hdd0/PS2ISO

The PKG files are not listed in webMAN Games

**Comment by ilqar200** [comment]
> webMAN only shows the PS2 games stored as .iso or .BIN.ENC in the folder /dev_hdd0/PS2ISO
> 
> The PKG files are not listed in webMAN Games

The game in folder devhdd000/game

**Comment by ilqar200** [comment]
> webMAN only shows the PS2 games stored as .iso or .BIN.ENC in the folder /dev_hdd0/PS2ISO
> 
> The PKG files are not listed in webMAN Games

How to configure webman to show ps2 game  installed as pkg in list ?

**Comment by aldostools** [comment]
webMAN only shows the PS2 games stored as .iso or .BIN.ENC in the folder /dev_hdd0/PS2ISO <==

The PKG files are NOT listed in webMAN Games. Only ISO or .BIN.ENC

**Comment by ilqar200** [comment]
> webMAN only shows the PS2 games stored as .iso or .BIN.ENC in the folder /dev_hdd0/PS2ISO <==
> 
> The PKG files are NOT listed in webMAN Games. Only ISO or .BIN.ENC

And there is no way to show ps2 game (pkg) in list ?

**Comment by aldostools** [comment]
> > webMAN only shows the PS2 games stored as .iso or .BIN.ENC in the folder /dev_hdd0/PS2ISO
> > The PKG files are not listed in webMAN Games
> 
> How to configure webman to show ps2 game installed as pkg in list ?

They are not listed in webMAN Games. You have to access them from the standard shortcut in Games column

**Comment by ilqar200** [comment]
> > > webMAN only shows the PS2 games stored as .iso or .BIN.ENC in the folder /dev_hdd0/PS2ISO
> > > The PKG files are not listed in webMAN Games
> > 
> > 
> > How to configure webman to show ps2 game installed as pkg in list ?
> 
> They are not listed in webMAN Games. You have to access them from the standard shortcut in Games column

Is there anyway to show ps2 game(pkg)  in list ?
