### ISSUE TITLE
[ps3netsrv] Is the data sent to client right?

### ISSUE THREAD

**Issue by jhonathanc** [aldostools/webMAN-MOD#837]
https://github.com/aldostools/webMAN-MOD/blob/d217866f181936b5be737ca99d8d5e6cc6a3f13f/_Projects_/ps3netsrv/src/main.cpp#L1243

Hi Aldos, is the data sent to client right on read_dir_entry_command? Because both results are being filled, but not used...

I implemented this to ps3netsrv-android, but it looks a little weird (or maybe I didn't understand what's going on here).

**Comment by aldostools** [comment]
Hello Jonathan
There are 2 methods for read directories.

The first method is the original that reads each directory entry, one by
one.

The second method process_read_dir_entry_cmd(client_t reads all the entries
in a single call, then send the results. This method was a modification
implemented by DeanK for multiMAN. It is used also by webMAN and sMAN.

**Comment by jhonathanc** [comment]
but the `process_read_dir_entry_cmd` never send the results filled inside the method:

	netiso_read_dir_entry_result result_v1;
	netiso_read_dir_entry_result_v2 result_v2;

It just send the file name:

`int send_ret = send(client->s, (char *)entry->d_name, d_name_len, 0);`

**Comment by jhonathanc** [comment]
Oh, I see what I did wrong. Sorry. I'll close the issue. Thanks.
