### ISSUE TITLE
How do I disable sLaunch & the syscall that doesn't allow me to mount discs after I have del cfw syscalls

### ISSUE THREAD

**Issue by DeityofSwA** [aldostools/webMAN-MOD#84]
entire question is in title

**Comment by aldostools** [comment]
By default all the CFW syscalls are deleted.
If you want to keep syscalls 8 enabled like in the earlier versions, go to /setup.ps3 and select PS3MAPI enabled, in the box next to DEL CFW SYSCALLS at the bottom of the window.

Note: first expand the section for the XMB / In-game PAD Shortcuts.

Keeping the syscall 8 enabled (fake disabled) will let you mount games and enable the syscalls without reboot, but it is less safe to access PSN.

**Comment by N2022062** [comment]
Keeping the syscall 8 enabled


where is the option?

**Comment by Joonie86** [comment]
Closing old issues that have no further feedback. Please try the latest wMM and report back.
