### ISSUE TITLE
webMAN-MOD lite uninstall not working?

### ISSUE THREAD

**Issue by mkardi** [aldostools/webMAN-MOD#841]
When I select either Uninstall webMAN-MOD or Reset from webMAN-MOD menu nothing seems to happen.
PS3 will only show **delete.ps3: OK** message on top right corner, but webMAN is not removed even after manual reboot.

Workaround is to install standard edition over lite, then reset and uninstall options do work.

Is this a bug or intended?

**Comment by aldostools** [comment]
It is intentional.... Lite edition doesn't include several features to keep the plugin small, one of them is the uninstall command.

**Comment by mkardi** [comment]
Thank you for explaining as it makes sense. This issue can be closed.
