### ISSUE TITLE
[Docs] Wiki doesn't mention REDKEY folder

### ISSUE THREAD

**Issue by dracc** [aldostools/webMAN-MOD#842]
`ps3netsrv` as provided in this repository supports the REDKEY folder which can be used for .dkey files, but the wiki makes no mention of it.

**Comment by aldostools** [comment]
The note about REDKEY has been added a moment ago.
https://github.com/aldostools/webMAN-MOD/wiki/~-PS3-NET-Server

**Comment by dracc** [comment]
Thank you!
