### ISSUE TITLE
how to change BD/DVD region

### ISSUE THREAD

**Issue by Dannydai123** [aldostools/webMAN-MOD#846]
Hi aldo,

dont know how to change region on latest full version of mod. find nothing about this.

BTW, what " toggle rebug" "toggle debug menu" , click on it, but nothing happened.

thanks

Danny

**Comment by aldostools** [comment]
If you mean change console region, that is done changing the product code in IDPS.

For BD/DVD region, webMAN only calls the opcode with the selected region and Cobra/HEN does the rest.

The "toggle rebug" "toggle debug menu" are option for Rebug firmware. They don't exist in Evilnat CFW or HEN.

**Comment by Dannydai123** [comment]
then how to call that opcode ? there is no menus or web commands?

**Comment by Dannydai123** [comment]
I found configuration form. but it doesn't work no matter what region it is .

**Comment by aldostools** [comment]
webMAN-MOD has the options in /setup.ps3

You have to expand the sections to find it, the option is hidden by default.

**Comment by Dannydai123** [comment]
thanks, Aldo.  some other guys tried. DVD related flags in a ".sysregister" (dont remember file name) file are many. cobra author even didn't know this.  setting BD/DVD via your setup page doesnt work. esp for DVD (regions and PAL/NTSC). I gave up.

**Comment by aldostools** [comment]
The option for setting BD/DVD in webMAN MOD is only a web interface that makes a call to Cobra/HEN payload.

If the option is not working it should be an issue with the payload or the physical drive.

I don't use DVD/BD on PS3, but I guess you could try spoofing the region in your IDPS.
