### ISSUE TITLE
is this the same "aldotools" from aldotools.com?

### ISSUE THREAD

**Issue by snes1423** [aldostools/webMAN-MOD#847]
i tried leaving a message via aldotools.com about CVGS 1.5b2 for Mac OS 9.2.2 and the message wouldn't go through sorry if this is off topic but could you create and/or show how to create a modchip patch for CVGS 1.5b2 from what i understand you created a lot of patches for CVGS back in the day
[CVGS 1.5b2 Update Read Me.txt](https://github.com/aldostools/webMAN-MOD/files/11082034/CVGS.1.5b2.Update.Read.Me.txt)
i have attached the readme file from the mac version seems to have preliminary support for cheat codes and fixes for FF9 and FF6 as well as GPU acceleration for FF7
and here is a copy of 1.5b2
http://old.mac.gdn/apps/VirtualGameStation.sit_.bin

**Comment by aldostools** [comment]
Hello,
Thank you for your comments. Yes, I'm the developer of the old CVGS patches that you refer.

My official site now is https://aldostools.org 

However, all the related work to that emulator & patches has been stopped for decades.
