### ISSUE TITLE
video rec

### ISSUE THREAD

**Issue by bujman** [aldostools/webMAN-MOD#85]
at starting cause frezze or black screen and not respond... need diconnet ps3... (sorry for my bad englis...)

**Comment by aldostools** [comment]
Video recording is a feature that is not supported by many games.
It also requires a large amount of free memory and only can be used in-game.
So, the compatibility is very limited.

To maximize the memory usage I implemented the new combo shortcut SELECT+R3+L2+R2 that loads video_rec.sprx and unloads webMAN MOD.

If you refers to that feature, I have added in the most recent commit a delay of 3 seconds before unload plugin. You can check if it prevents the aforementioned freeze.
https://github.com/aldostools/webMAN-MOD/releases/latest

**Comment by bujman** [comment]
this time not freeze (rebot xmb) becaus the game not suportting... i trying other game and partialitiy work... (show starting rec a finish...)  but ai cant find the mp4 archive... (i search in hd00/video and others place...)  i manualy load video rec and disable webman mod... (the combo rebot the ps3...) 

tnx for ur time, info and all... (i am a noob... so maybe my info its wrong...)

**Comment by Joonie86** [comment]
Closing old issues that have no further feedback. Please try the latest wMM and report back.
