### ISSUE TITLE
I can't install webman.

### ISSUE THREAD

**Issue by Fareast07** [aldostools/webMAN-MOD#850]
- I just updated my firmware and got my self the latest hen, when i tried to reinstall webman, i found my self in a pickle.
  - You see when i press L1+X to install the full version the ps3 doesrestart like usual after a message shows saying installing "webman mod full", or something like that, but when i activate the hen the folder isn't here, and when i try to install the lite version by simply pressing X, i get this message again "webman mod full". 
    - Thank you in advance.

**Comment by LuanTeles** [comment]
Are you using a USB drive with boot_plugins in it?

If not, try to delete your boot_plugins.txt (dev_hdd0) and launch the webMAN installer again.

**Comment by Fareast07** [comment]
> 

it worked ^^
the cause was indeed the Boot.txt file, it was in my USB drive, had been searching all over but didn't seem to find anyone having this issue. thanks for the help ^^
also is it really not a commun issue ?

**Comment by LuanTeles** [comment]
Not really Haha

no problem!
