### ISSUE TITLE
Updated PS1 Libcrypt Database

### ISSUE THREAD

**Issue by Rallye89** [aldostools/webMAN-MOD#855]
Updated PS1 Libcrypt Database:

Sony - PlayStation - SBI Subchannels (231) (2023-04-01 01-25-03)
https://mega.nz/file/9VRB2CzZ#a-P4CiugtenA4CEfzIpeZzouH3SaM9GLogF0cR1jYZI

Sony - PlayStation - LSD Subchannels (231) (2023-04-01 01-25-03)
https://mega.nz/file/ZYAFHYSI#7Gdrrlq8bNuWFeiS8hIhIC1NN6pyLESUrumnFQD0M7s

Another disc added to redump, now the list has 231 dumps.

Include this in new versions and online:
https://ps3.aldostools.org/lsd.html
https://ps3.aldostools.org/sbi.html

Thank you for your work, Aldo!

**Comment by aldostools** [comment]
Updated
