### ISSUE TITLE
PS2 games now blackscreen after dex dbhfw

### ISSUE THREAD

**Issue by robokingscosmosps3** [aldostools/webMAN-MOD#856]
After installing evilnat of course 
When I launch I don't get the ps2 logo even trying the placeholder. could you link me to socat?

**Comment by aldostools** [comment]
AFAIK socat does not work with ps2 emulator.

Return to CEX mode if you want to play PS2 games.

**Comment by robokingscosmosps3** [comment]
Turns out it was otheros impacting it
