### ISSUE TITLE
After using webMAN MOD in PS2 Mode [Read Description]

### ISSUE THREAD

**Issue by robokingscosmosps3** [aldostools/webMAN-MOD#858]
Apparently it causes the ip address to disappear on Evilnat after leaving PS2 mode on PS3 making me have to reboot everytime I launch a PS2 game

**Comment by robokingscosmosps3** [comment]
I can't open up ps3xploit.me or google.com due to lack of internet connection from PS2 Mode

**Comment by aldostools** [comment]
When ps2 emulation is started, the PS3 unloads the GameOS kernel to have enough resources to run the emulator. Once you quit the ps2 game, the LV2 kernel is reloaded through a soft reboot.

If you're unable to access the Internet, it could be due a misconfiguration of your network settings or router. Or in the worst case, a hardware issue.

I recommend that set your network to use a static IP

**Comment by robokingscosmosps3** [comment]
It might be a hardware problem. my previous ps3 was never like this with webman mod installed. i guess i might as well prefer a phone connection than the wifi to see if that still works.
