### ISSUE TITLE
Installs, but not working

### ISSUE THREAD

**Issue by swindlesmccoop** [aldostools/webMAN-MOD#859]
Recently I decided to do an HDD replacement because my previous one was miniscule. I went through all of the steps and did a backup to an external drive and restored from that with the new drive. At first everything was fine except for WebMAN, which was acting weird when I opened the WebUI (settings were not formatted properly and would not save when changed). I figured it was probably just because I restored a backup and thought nothing of it and reinstalled, and it started to work. That was, until I decided to rebuild my database to get some of my PSN games working on the XMB, then it disappeared from the XMB. I thought this was strange so I reinstalled and the WebMAN folder shows up now on the XMB, but selecting it doesn't actually do anything. I tried to rebuild the database after installing it again but it didn't change anything, the folder was still there but not working.

**Comment by aldostools** [comment]
Try uninstalling webMAN MOD, reinstall it again using the installer in this link
https://github.com/aldostools/webMAN-MOD/releases

Also make sure that Cobra is enabled and boot_plugins.txt is created (they get disabled when you enter to recovery menu)

**Comment by swindlesmccoop** [comment]
Yep, Cobra being disabled was my issue. I didn't realize it gets disabled when you go to recovery.
