### ISSUE TITLE
Ps3netserver error not found "libstdc++-6.dll".

### ISSUE THREAD

**Issue by rocknard** [aldostools/webMAN-MOD#86]
Hello, Aldos, nice to see you.

I'm trying to start ps3netsrv_20170310.zip (old versions was fine) and get this error:

http://imageshack.com/a/img924/9430/U9WJLv.png

With older versions (2012?) i don't get this error (don't use it libstdc++-6 MinCG?).

Thank you.

**Specs:**
Windows XP SP3 
Firewall and AV not blocking anything.

EDIT: **i get this error if i add one more "Share", in this case "Share2". If i only active "Share1", not error prompted. With "ps3netsrv.exe" from WebMAN v1.47 i don't get this error after add "share1 and share2"  #folders.**

**Comment by aldostools** [comment]
Try copying libstdc++-6.dll to c:\Windows\System32 (or C:\Windows\SysWow64 if your OS is 64bit)

The error is because the GUI makes a copy of ps3netsrv.exe to separate folders, but the copy are not finding the required dlls.

**Comment by rocknard** [comment]
Thank you, aldos. I thinked about that possibility.

I needed copy "libgcc_s_dw2-1.dll" and "libstdc++-6.dll".

Thank you.
