### ISSUE TITLE
[Feature Request] XBM ScreenShot and webPAD shortcuts

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#860]
Aldo i would like to suggest the addition of these 2 shortcuts in /setup.ps3 to easy access.

**Comment by aldostools** [comment]
I'm not sure what you mean. Please submit a PR or provide a more graphical detail.

**Comment by LuanTeles** [comment]
I mean, a button like the blue ones (or something like that)  to take a XMB screenshot and one to open the webPAD  

Those are useful features and most of the users are not aware.

![image](https://user-images.githubusercontent.com/110236244/231277326-c219fa3d-a230-41ca-b7f6-537ae2536224.png)

**Comment by LuanTeles** [comment]
Btw webPAD button toggle seems not to work on win11 with egde?

the toggle appears as a broken image icon (i couldn't capture it on the ss)

I'm usinG it as my ds3 is broken


![image](https://user-images.githubusercontent.com/110236244/231278515-7996ee97-dc99-4810-aa31-071bb8ad22b9.png)

**Comment by aldostools** [comment]
`/xmb.ps3$screenshot` is already one of the suggested options for  the custom combo R2+SQUARE

The /setup.ps3 is already very busy. I don't want to add more superfluous features.

In regards to webPAD link. It doesn't have use on PS3. There are various links in the documentation that point to:
http://pad.aldostools.org
