### ISSUE TITLE
Webman auto-playing 3in1 game iso?

### ISSUE THREAD

**Issue by Xickic** [aldostools/webMAN-MOD#861]
I have an Assassin's Creed Ezio Trilogy iso, these are 3 games that need to be separatly launched from xmb. I've used webman classics maker to transfer the iso to the xmb. When i mount it from there the first game auto-plays right after mounting (i cant launch the other two). When i didn't use webmans classics maker a while ago games didn't auto-play for me. Even just regular games dont auto-play only this one. Could u help me? I don't think that it has to do with the classics maker but maybe? I don't know. I hope you can help me so that i can play the other two.

Thank you in advance.
Xickic

**Comment by aldostools** [comment]
In webMAN Setup settings there is an option called Auto-Play. If it is checked, the game is started automatically.

Also if you keep pressing X, the game is started after mount it.

If the game has only one disc icon, but multiple games PS3_GM01, 02, etc. Mounting the same again changes the entry point to PS3_GM02.

**Comment by Xickic** [comment]
Auto-play isn't turned on, and I don't press anything at all. It is like you say there are 3 discs after mounting (I see them very briefly) but before I can  select another disc the first one auto-plays. No other game does this for me.

It has only 1 PS3_GAME, but I believe it has packages inside that for the other two games. I think when I select the other 2 discs these pkgs will install but as I said I cant open them.

**Comment by aldostools** [comment]
Auto-Play sometimes is triggered if the face buttons in the controller are sticky.

If you keep pressing CIRCLE after mounting the game,  Auto-Play is cancelled.

The 3 disc icons is a normal behavior for these multi-game discs. You could create 3 different ISO images with a single game each, but that requires too much work.

**Comment by Xickic** [comment]
Alright thanks alot.
