### ISSUE TITLE
[Request] Improvements to PS3 Game Cover Sizes (sMAN)

### ISSUE THREAD

**Issue by web1018** [aldostools/webMAN-MOD#863]
Hello,

The cover sizes for the PS3 disc games that are selected from XMB are squished and doesn't look right as a result. If it's possible to make any improvements on it so that its cover sizes are in the correct size as it's displayed within the folder they are selected from. 

Thank you

**Comment by aldostools** [comment]
This subject is discussed in
https://github.com/aldostools/webMAN-MOD/wiki/Game-Paths-&-Covers#covers
