### ISSUE TITLE
AUDIO CD flac backups? FEATURE SUGGESTION

### ISSUE THREAD

**Issue by deadpahn** [aldostools/webMAN-MOD#867]
Hello,

I was wondering if cd ripping could be implemented? As PCs slowly lose dvd/cd drives I feel like an old PS3 would do the trick. For example, I have one that overheats anytime I boot a game. I would love to have it be repurposed for backing up my music collection (and perhaps even making rips of my DVD movies also?). I know it sounds stupid at first but if you give it some thought it makes sense. I do have one of those $40 usb dvd drives but it's kind of annoying. Having a single purpose media backup center would be cool.

Thanks for all the work you devs do :)

**Comment by aldostools** [comment]
CD/DVD/Bluray ripping is not among the goals of webMAN MOD plugin.

FLAC is not an [audio format natively supported by PS3](https://manuals.playstation.net/document/en/ps3/current/music/filetypes.html).  

The PS3 has an official feature that allows CD ripping from XMB.
https://manuals.playstation.net/document/en/ps3/current/music/cdimport.html
This feature only supports [AAC, MP3 and ATRAC](https://manuals.playstation.net/document/en/ps3/current/settings/cdimport.html). 

For ripping game discs I recommend to use [multiMAN](https://store.brewology.com/ahomebrew.php?brewid=24), [IRISMAN](https://store.brewology.com/ahomebrew.php?brewid=250), [ManaGunZ](https://store.brewology.com/ahomebrew.php?brewid=284). There is also a [SACD Ripper](https://store.brewology.com/ahomebrew.php?brewid=305) that you could check.
