### ISSUE TITLE
Make media files on NTFS drives available for XMB player

### ISSUE THREAD

**Issue by Invictaz** [aldostools/webMAN-MOD#87]
I hope videos on the NTFS usb drives are able to be played in the XMB videoplayer.
Same for music and pictures.

The FakeISO support in Irisman does not work for 
-DVD folders
-MKV files
-Music folders

**Comment by aldostools** [comment]
Use prepNTFS 1.17. Put the videos in "VIDEO" or "MOVIES" in the root of the drive.

multiMAN and IRISMAN can create ISO from folders. IRISMAN also can create FakeISO for any kind of file (mkv, music, pictures, pkg, pup, etc.).

**Comment by Invictaz** [comment]
Not correct. DVD folders are not recognized in Irisman 3.44
