### ISSUE TITLE
4.2.2 HEN Issue

### ISSUE THREAD

**Issue by RunninPigeon** [aldostools/webMAN-MOD#870]
will this be fixed later? cant get into ps3 hen.

**Comment by aldostools** [comment]
There isn't a known issue with webMAN MOD 1.47.44 on HEN 3.2.2

If you're using a previous version of webMAN MOD, you must update to the latest version.

If you're already on the latest version. Please report your issue in detail in this thread
https://www.psx-place.com/threads/support-thread-ps3hen-bugs-problems-and-other-issues.37327/page-23#post-363531

**Comment by RunninPigeon** [comment]
closing, found out why, just had to delete some txt files lol
