### ISSUE TITLE
[Feature Request] Fan Speed Adjustments via PS3 webBrowser

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#871]
Aldo 

My DS3 is in a bad condition (so no button combo) and i'm on CFW without any modification so no fan speed XMBML menus.

So i was wondering as webMAN MOD doesnt have it XMBML menus for differente fan speeds, only by using /cpursx.ps3? (via XMBML) if arrows buttons or any other compatible solution can be added to increase/decrease the fan speed on that page.

I know that on a remote device it has a fan speed adjustment via slider which is not compatible with the ps3 hence the lack of the it.

So I thought it would be a nice addition for newbies who don't know about the pad combos and want to adjust fan speed on the fly.

![image](https://user-images.githubusercontent.com/110236244/234949202-873e2fad-8c79-4ded-a071-fedcbe0f3e56.png)

![image](https://user-images.githubusercontent.com/110236244/234949398-4535b6b0-f3be-4e1d-99da-bbc1aad21e94.png)

**Comment by aldostools** [comment]
Top CPU/RSX (°C) has a link that acts as UP
The bottom CPU/RSX (°F) has a link that acts as DOWN.

**Comment by LuanTeles** [comment]
Oh that's new to me, but isn't better to add a little arrow?

**Comment by aldostools** [comment]
I find the arrows would look ugly.

That feature has been there almost from the beginning of the project.
