### ISSUE TITLE
[Bug Report] Download commands

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#877]
Aldo i updated webMAN to the latest version and i saw that you made some changes in the /download.ps3 feature

`/download.ps3?to=/dev_hdd0/home/$USERID$/theme/&url=http://github.com/PS3-4K-Pro/Wallpapers/releases/download/Abstract/Abstract_002.png;/delete.ps3/dev_hdd0/home/$USERID$/theme/wallpaper.png;/wait.ps3?5;/rename.ps3/dev_hdd0/home/$USERID$/theme/Abstract_002.png&to=/dev_hdd0/home/$USERID$/theme/wallpaper.png;/browser.ps3/dev_hdd0/home/$USERID$/theme/wallpaper.png;/wait.ps3?10;/popup.ps3?msg_wallpaper_notification&rco=explore_plugin&icon=3&snd=1;/xmb.ps3$xregistry(/setting/user/$USERID$/theme/wallpaper)=1`

It used to work fine , downloads the pkg, then opens the web browser to show the preview and show the notification.

https://www.youtube.com/watch?v=0PszoGYHyTs

but now the download takes place at a lower level than xmb and when the download completes it goes to the game column.

![image](https://github.com/aldostools/webMAN-MOD/assets/110236244/9c51fe5f-1bde-48cd-89fa-ae0041b3f657)

**Comment by LuanTeles** [comment]
Seems like the changes are made upon sandro's request

well, i changed the commands order and i loved that now we can keep the web browser opened while the download is being performanced (much better)

![image](https://github.com/aldostools/webMAN-MOD/assets/110236244/945ba631-9ebd-4eac-b49f-72d18a10e792)

**Comment by LuanTeles** [comment]
The only problems are that the download operation is below the xmb items if the download command is used directly and when it completes when i hit circle to get back to xmb it automatically goes to the game column.

perhaps different syntaxes need to be created for each of the two cases?

well the only thing that is bothering me is going to the game column after each download operation.

**Comment by aldostools** [comment]
Are you using /xmb.ps3/download.ps3 ?

If not, please try with this new command

**Comment by LuanTeles** [comment]
> Are you using /xmb.ps3/download.ps3 ?
> 
> If not, please try with this new command


New command 
`/xmb.ps3/download.ps3?to=/dev_hdd0/home/$USERID$/theme/&url=http://github.com/PS3-4K-Pro/Wallpapers/releases/download/Abstract/Abstract_002.png`

Opens a blank page and downloads the pkg, when it completes and i hit circle it goes to the game column.

Old command (i'm combining /browser.ps3? and download.ps3
`/browser.ps3?https://github.com/PS3-4K-Pro/Wallpapers/raw/main/files/abstract/abstract_001.png;/wait.ps3?3;/download.ps3?to=/dev_hdd0/home/$USERID$/theme/&url=http://github.com/PS3-4K-Pro/Wallpapers/releases/download/Abstract/Abstract_001.png`

Opens the web browser with the preview and downloads the pkg, when it completes and i hit circle it goes to the game column.

How can i use the new one to open a custom url instead of the blank page? so i can save the /browser.ps3? command.


Edit:

Well, maybe this behaviour was the same as before, in old builds

when the download command was performanced eg:

/download.ps3?to=/dev_hdd0/home/$USERID$/theme/&url=http://github.com/PS3-4K-Pro/Wallpapers/releases/download/Abstract/Abstract_002.png

all Items are closed and the download starts in the main xmb

now in recent builds it's performanced without going to the main xmb (much better), maybe we didn't notice it before because of that


But only in newer builds when the downloads completes it goes directly to the game column

**Comment by aldostools** [comment]
A workaround has been added to solve this issue.
Please try downloading the latest installer from GitHub or use the online updater to test the new fixes.

**Comment by LuanTeles** [comment]
@aldostools 

now the it doesn't go to the game column anymore but after hitting circle to go back to xmb the web browser stays opened in background, needing to press PS button and then close it

https://www.youtube.com/watch?v=M0G2NlS49Zg

**Comment by aldostools** [comment]
I already told you that in the other thread #878 (5th post)

> NOTE2: When you press CIRCLE the browser stays open in background. Click on Internet Browser again to return to the page.

**Comment by LuanTeles** [comment]
> I already told you that in the other thread #878 (5th post)
> 
> > NOTE2: When you press CIRCLE the browser stays open in background. Click on Internet Browser again to return to the page.

Oh i missed that, thanks Aldo

**Comment by LuanTeles** [comment]
I nice work-around

http://192.168.0.15/browser.ps3?https://raw.githubusercontent.com/PS3-4K-Pro/Wallpapers/main/files/abstract/abstract_151.png;/download.ps3?to=/dev_hdd0/home/$USERID$/theme/&url=http://github.com/PS3-4K-Pro/Wallpapers/releases/download/Abstract/Abstract_151.png;/pad.ps3?psbtn;/delete.ps3/dev_hdd0/home/$USERID$/theme/wallpaper.png;/rename.ps3/dev_hdd0/home/$USERID$/theme/Abstract_151.png&to=/dev_hdd0/home/$USERID$/theme/wallpaper.png

When the download completes and i hit circle it quickly executes /pad.ps3?psbtn so the web browser gets in first plane again then hitting circle will close the browser when the user wants to
