### ISSUE TITLE
[Bug Report] Duplicated folder

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#878]
Aldo something strage is happening 

my command to install themes used to work fine but now it doesn't, i dont know when it got broken

See Here

`/install.ps3?to=/dev_hdd0/downloads/theme&url=http://github.com/PS3-4K-Pro/Themes/releases/download/A/Air.p3t;/popup.ps3?msg_theme_notification&rco=explore_plugin&icon=3&snd=1;/wait.ps3/dev_hdd0/downloads/theme/Air.p3t;/wait.ps3?5;/install.ps3/dev_hdd0/downloads/theme/Air.p3t`

i set it to download to dev_hdd0/download/theme but it is downloading to dev_hdd0/downloads/theme/theme

 
![image](https://github.com/aldostools/webMAN-MOD/assets/110236244/02dfa76c-4122-4e66-8250-ed6232f454a0)

**Comment by aldostools** [comment]
Thank you for the report.

**Comment by aldostools** [comment]
I tested your URL and for some reason it's throwing the error 0x80710A06 - SSL Connect Handshake error, or SSL certificate verification failed.

To bypass this error I changed the URL to one allowed by PS3 and the theme downloaded to the expected folder 
![image](https://github.com/aldostools/webMAN-MOD/assets/974897/4928d4c9-e2f9-4716-8a07-b43096fa712a)


Here is the URL that I used.
```
http://10.0.0.8/install.ps3?to=/dev_hdd0/downloads/theme&url=https://raw.githubusercontent.com/PS3-4K-Pro/Themes/main/files/Air.p3t;/popup.ps3?msg_theme_notification&rco=explore_plugin&icon=3&snd=1;/wait.ps3/dev_hdd0/downloads/theme/Air.p3t;/wait.ps3?5;/install.ps3/dev_hdd0/downloads/theme/Air.p3t
```

Try downloading the latest installer from GitHub or use the online updater (which is quicker) to test the new fixes for the issue #877

**Comment by LuanTeles** [comment]
@aldostools 

Oh i see, you are using a dex vsh.self (4,.84)

The 0x80710A06 error occurs in firmwares lower than 4.85 (works if the file is in the repository but not in the release page)
 , github renewed the ssl certificate last month and now it uses DigiCert Global G2 from 2020

DigiCert Global G2 has been introduced in the CA_LIST.cer on 4.85 FW. Nat and I were investigating it but even recalculating the  hash from newer firmwares in vsh.self and libssl.sprx it doesn't work on 4.84 :S

Nat was trying to break the hash in cex vsh.self to see what causes this issue but nothing so far.


Anyway, i updated via online updater and even through the pkg installer, nothing changed here 

it still downloads to  theme/theme folder, overlaps the xmb and go to game column

**Comment by aldostools** [comment]
I don't know what you're doing wrong, but here it downloads the theme to `/dev_hdd0/downloads/theme/Air.p3t`

I changed my VSH to CEX, used the exact link that you provided in the initial post and obtained the same results.

NOTE: The first /install.ps3 that only downloads the file doesn't close the browser, but the second /install.ps3 closes the browser.

NOTE2: When you press CIRCLE the browser stays open in background. Click on Internet Browser again to return to the page.

**Comment by LuanTeles** [comment]
Lemme uninstall webMAN mod and re-install the firmware

 Edit: Done
 
 1. let's use the same commands that you used

`/install.ps3?to=/dev_hdd0/downloads/theme&url=https://raw.githubusercontent.com/PS3-4K-Pro/Themes/main/files/Air.p3t;/popup.ps3?msg_theme_notification&rco=explore_plugin&icon=3&snd=1;/wait.ps3/dev_hdd0/downloads/theme/Air.p3t;/wait.ps3?5;/install.ps3/dev_hdd0/downloads/theme/Air.p3t
`

VIdeo:

https://youtu.be/gSroq3Kh4M8

![image](https://github.com/aldostools/webMAN-MOD/assets/110236244/bd7e3cb6-29de-4382-82a3-603b85525f97)
![image](https://github.com/aldostools/webMAN-MOD/assets/110236244/cf0c85b0-3b4f-429d-a990-415eee1b901f)

The notification is right it says downloading to "dev_hdd0/downloads/theme" but in fact it is " dev_hdd0/downoads/theme/theme"

**Comment by aldostools** [comment]
Delete downloads/theme folder, install wMM 1.47.45

**Comment by LuanTeles** [comment]
> /install.ps3?to=/dev_hdd0/downloads/theme&url=https://raw.githubusercontent.com/PS3-4K-Pro/Themes/main/files/Air.p3t;/popup.ps3?msg_theme_notification&rco=explore_plugin&icon=3&snd=1;/wait.ps3/dev_hdd0/downloads/theme/Air.p3t;/wait.ps3?5;/install.ps3/dev_hdd0/downloads/theme/Air.p3t

Same lol

the notification and html still says .44 (only The installer says .55). i deleted tmp, xmlhost and the plugins folder to make sure but same thing


![image](https://github.com/aldostools/webMAN-MOD/assets/110236244/9b025e06-99d1-402c-b68b-d9a559ac2240)
![image](https://github.com/aldostools/webMAN-MOD/assets/110236244/be40d211-d79f-4a23-b2d2-2fbcd080b179)

**Comment by aldostools** [comment]
Oh I changed the version everywhere, but I forgot to change it in main.c
That's why I don't change the version so often... they are too many files to update.

Thanks for the report. I updated the packages with the correct version.

**Comment by aldostools** [comment]
BTW could you test using the link from Chrome on the PC?? That's how I tested it.

**Comment by LuanTeles** [comment]
> BTW could you test using the link from Chrome on the PC?? That's how I tested it.

Sure, lemme download it, but the same happens via XMBML

**Comment by aldostools** [comment]
I mean that I tested your link /install.ps3.... using Chrome to download it on the  PS3

**Comment by LuanTeles** [comment]
Same
![image](https://github.com/aldostools/webMAN-MOD/assets/110236244/c3855d3f-a076-4a9d-a906-a279a54871f6)
![image](https://github.com/aldostools/webMAN-MOD/assets/110236244/43b1c37e-cdb6-4679-9f62-2b8e2bde9328)

**Comment by LuanTeles** [comment]
Aldo

/install.ps3?to=/dev_hdd0/downloads

automatically creates the theme subfolder

maybe you made if its a p3t file it automatically creates the theme folder? or it can be a bug as it also saves a copy to dev_hdd0/theme folder and its duplicating the theme path because of it

Edit: I thought that using /download.ps3 should work but the same

/download.ps3?to=/dev_hdd0/downloads/theme&url=https://raw.githubusercontent.com/PS3-4K-Pro/Themes/main/files/Air.p3t

**Comment by aldostools** [comment]
If the parameter `?to=` is omitted, the default path for .p3t is /dev_hdd0/theme
If the parameter is provided, the file is downloaded to that path. In your example: /dev_hdd0/downloads/theme

The theme is copied to /dev_hdd0/theme when it is installed.

I tested this link (I only added the IP):
http://10.0.0.8/install.ps3?to=/dev_hdd0/downloads/theme&url=http://github.com/PS3-4K-Pro/Themes/releases/download/A/Air.p3t;/popup.ps3?msg_theme_notification&rco=explore_plugin&icon=3&snd=1;/wait.ps3/dev_hdd0/downloads/theme/Air.p3t;/wait.ps3?5;/install.ps3/dev_hdd0/downloads/theme/Air.p3t

**Comment by LuanTeles** [comment]
> If the parameter `?to=` is omitted, the default path for .p3t is /dev_hdd0/theme If the parameter is provided, the file is downloaded to that path. In your example: /dev_hdd0/downloads/theme
> 
> The theme is copied to /dev_hdd0/theme when it is installed.
> 
> I tested this link (I only added the IP): http://10.0.0.8/install.ps3?to=/dev_hdd0/downloads/theme&url=http://github.com/PS3-4K-Pro/Themes/releases/download/A/Air.p3t;/popup.ps3?msg_theme_notification&rco=explore_plugin&icon=3&snd=1;/wait.ps3/dev_hdd0/downloads/theme/Air.p3t;/wait.ps3?5;/install.ps3/dev_hdd0/downloads/theme/Air.p3t


Got it but in our case it acts like the parameter is missing lol

well i can use ...?to=/dev_hdd0/downloads/ and let it as it is

**Comment by aldostools** [comment]
Well you can customize the link, my point is that your link worked fine on my system without any additional modification than the IP address of my PS3 to call it from Chrome on my PC.

**Comment by LuanTeles** [comment]
> Well you can customize the link, my point is that your link worked fine on my system without any additional modification than the IP address of my PS3 to call it from Chrome on my PC.

That's wierd even though XMBML it duplicates the theme folder in my end.

**Comment by aldostools** [comment]
For the moment I don't plan to make additional changes, unless the bug could be reproduced on my side.

**Comment by LuanTeles** [comment]
I just tried

/install.ps3?url=http://github.com/PS3-4K-Pro/Themes/releases/download/O/OceanDynamicGlideshowTheme.p3t;/popup.ps3?msg_theme_notification&rco=explore_plugin&icon=3&snd=1;/wait.ps3/dev_hdd0/theme/OceanDynamicGlideshowTheme.p3t;/wait.ps3?5;/install.ps3/dev_hdd0/theme/OceanDynamicGlideshowTheme.p3t

without the parameter ?to= and now it downloads to dev_hdd0/theme/theme haha


Edit:

Now i'm using ?to=/dev_hdd0

/install.ps3?to=/dev_hdd0&url=http://github.com/PS3-4K-Pro/Themes/releases/download/O/OceanDynamicGlideshowTheme.p3t;/popup.ps3?msg_theme_notification&rco=explore_plugin&icon=3&snd=1;/wait.ps3/dev_hdd0/theme/OceanDynamicGlideshowTheme.p3t;/wait.ps3?5;/install.ps3/dev_hdd0/theme/OceanDynamicGlideshowTheme.p3t

Works perfectly it keeps the theme in the theme folder and also installs it 👍

**Comment by LuanTeles** [comment]
I got here by chance and now I realized the problem, I use Devil's extended download plugin and it automatically creates the "theme" folder if a p3t file is downloaded, so that's why I was having this problem

**Comment by aldostools** [comment]
If the problem is not webMAN MOD, but the extended download plugin, then you can close the issue.
