### ISSUE TITLE
webMAN not installing on HEN.

### ISSUE THREAD

**Issue by crucian-syl** [aldostools/webMAN-MOD#880]
webMAN not installing on HEN, used to work but now it messed up even my HEN loader and I have to launch HEN from my browser.

**Comment by aldostools** [comment]
What is the exact error?

If it is an error with the installer, try downloading the installer again from github and reinstall the plugin or use the online updater if you have access to webMAN Setup menu.

**Comment by crucian-syl** [comment]
> 
Yes, I am going to try installing again the PKG. I don't have webMAN anymore, there's nothing else than the installer that's not working, so I don't have access to the setup menu. 

I will be trying to do a photo at the error that appears in the top right corner.

**Comment by crucian-syl** [comment]
The error message is: 

Boot Plugins Text Have Been Deleted!
Update webMAN-MOD from PKG
Manager after reboot.

**Comment by crucian-syl** [comment]
I can't update because it doesn't show up nowhere

**Comment by crucian-syl** [comment]
Trying to download again the PKG

**Comment by crucian-syl** [comment]
Still same error. I didn't delete anything though.

**Comment by aldostools** [comment]
It's the HEN installer that is deleting the boot_plugin.txt and showing the error.

Once you have installed HEN, you only need to run the HEN Enabler and install the PKG for webMAN MOD.

After install the PKG of webMAN MOD, you must *RUN* the installer. After reboot, enable HEN again (do not reinstall HEN!!).

You can delete the icon of webMAN MOD installer after you get the webMAN Games menu showing on XMB.

**Comment by crucian-syl** [comment]
Thanks, but I can't enable HEN without reinstalling it because it just loads forever.

**Comment by aldostools** [comment]
The "load forever" was fixed in HEN 3.2.2. Please download and install the latest HEN installer.

After the installation, reinstall the latest build of webMAN MOD,

**Comment by crucian-syl** [comment]
I already have HEN 3.2.2 and it worked untill yesterday. Sorry for disturbing, I will try to resolve with the information you gave me. Thanks.
