### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#886]
Aldo

I use the PS3SETTINGS.SFT to update some xRegistry settings but it only works on DEX, so i'm trying to set this one

/xmb.ps3$xregistry(/setting/system/updateServerUrl)=http://github.com/PS3-4K-Pro/Firmware-Updates/raw/main/cfw/ps3-updatelist.txt

via webMAN mod and my xregistry gets corrupted, i think it's because that value is empty by default, even xRegistry editpr can't open the sys file after using this command.

do you know how can i fix it?

**Comment by aldostools** [comment]
The /xmb.ps3$registry() command only can REPLACE existing values.

The new value cannot be longer than the current value in xRegistry.sys. Otherwise the file structure will be corrupted.
