### ISSUE TITLE
PS3 freeze when click most shortcuts on xmb.

### ISSUE THREAD

**Issue by owendswang** [aldostools/webMAN-MOD#888]
HEN3.2.2
webMAN 1.47.45

I'm a new user of PS3. Just jailbreaked it and installed HEN and webMAN.
It frees when I click most webMAN shortcuts on XMB. But on webpage, it works mostly. Sometimes it freezes too.
After clearing webMAN tmp cache, it becomes normal for some time. But after I installed new games, it happens again.
Or generally, it just freezes at some actions, like enable display FPS, it freeze every time now.

Is it OK to install multiMAN and IRISMAN on it at the same time? Is it because the conflicts?

**Comment by aldostools** [comment]
The FPS plugin tend to cause freeze on some systems. Avoid to use it if it is causing issues.

You can have multiMAN and IRISMAN installed at the same time without conflicts. They normally resolve the conflicts internally.

The latest version of multiMAN executes prepNTFS which uses a different file format for the cached files in tmp and could be the cause of your freezes.

The issue should be solved running prepISO or installing the unofficial HEN version of multiMAN that doesn't run prepNTFS.self.

**Comment by owendswang** [comment]
Thanks a lot for expaining. I will try.
