### ISSUE TITLE
Can't mount image while running ps1 game

### ISSUE THREAD

**Issue by goomba000** [aldostools/webMAN-MOD#89]
I am having an issue trying to mount an image from the web interface (accessed from my laptop).  Here's the situation where the problem occurs:

I'm playing a multi-disc ps1 game (Chrono Cross) which requires inserting the second disc at a certain point in the game.  With the game still running, using the web interface, I can unmount the current (first) disc fine (I get "Game unmounted.") or eject it (I get "Disc ejected.").  However, when I navigate to Games and I click on the image of the second disc to mount it, I get "Error!" which links to http://<ps3 ip>/dev_bdvd, this page giving a 404 error.  This presents a problem because that game (and a few others) doesn't allow saving at the end of disc 1; the disc swap must be done on the fly.

Note however that I can mount that second disc just fine from the web interface if the PS3 is in the XMB instead of in-game.

Relevant info:
Rebug CFW 4.81.2 /w Cobra (integrated webMAN disabled)
webMAN 1.47.04 MOD

**Comment by aldostools** [comment]
Try using /mount_ps3 instead of /mount.ps3

/mount.ps3 shows an error when a game is mounted in-game.
This error is intended to prevent that a game is mounted accidentally while you're playing.

Also try updating to the latest release ;)

**Comment by goomba000** [comment]
Hi. Indeed it works, thank you!  I guess I missed that in the doc.  Also I updated to 1.47.05.  May I suggest showing an error like of "Error: Can't mount image while in-game.  Use mount_ps3 to force mount." or something along those lines

Anyway, thank you again, I appreciate your work!
