### ISSUE TITLE
Button Combos: Select+R1 and Select+L1 -> Instant freeze

### ISSUE THREAD

**Issue by ozapft** [aldostools/webMAN-MOD#891]
Hello Aldo,

how is it going?
I tried the button combos for mounting the previous game and mounting next game. But unfortunately the ps3 freezes immediately. 
I‘m using the latest webMAN mod with HEN 3.22 and FW 4.86 on a PS3 Superslim. 
The PS3 iso files are on an external HDD (NTFS Filesystem).

Thanks in advance for your efforts.

**Comment by aldostools** [comment]
Please report your issue to PS3HEN team... it looks like a bug in payload or at least I don't get that issue on CFW 4.90

**Comment by ozapft** [comment]
Hello Aldo,
I'm sorry that I have to open the issue again.
I have tested older webman versions today. Version 1.47.40 from 05/01/2022 does not show the error. With this version I can use both button combos without freeze.
I also tested versions 1.47.41 to 1.47.45. These versions freeze at the button combo.

**Comment by MartinsVision** [comment]
I have the same issue on 4.9

**Comment by aldostools** [comment]
The issue was fixed in the latest build updated today. Please re-download the installer or use the online updater to get the fix.

**Comment by Lksrvl** [comment]
My console freezes when used with webman enabled

**Comment by aldostools** [comment]
Please download again the PKG installer found in GitHub. Install that PKG again.

The version may be the same number.
