### ISSUE TITLE
[Question] wm_request

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#894]
Aldo, does wm_request supports conditional commands (if, else...)?

**Comment by aldostools** [comment]
No, they are not supported directly, but wm_request can use the /mount.ps3 command to execute a .bat script file. These files support conditional commands.

**Comment by LuanTeles** [comment]
I'm trying but the script is not running  in-game, only on XMB

I made the installer install the wm_request and I need it to run while the installer is still open.

my wm_request:

`/mount.ps3/dev_hdd0/game/PS34KPROX/USRDIR/toolbox/scripts/vsh_checker.bat`

vsh_checker.bat

`/popup.ps3/TEST!&icon=7&snd=2

if firmware 4.90
	copy /dev_hdd0/game/PS34KPROX/USRDIR/toolbox/patches/vsh/evilnat_4.90/,/
else if firmware 4.89
	copy /dev_hdd0/game/PS34KPROX/USRDIR/toolbox/patches/vsh/evilnat_4.89/enable/,/
else if firmware 4.88
	copy /dev_hdd0/game/PS34KPROX/USRDIR/toolbox/patches/vsh/evilnat_4.88/enable/,/
else if firmware 4.84
	copy /dev_hdd0/game/PS34KPROX/USRDIR/toolbox/patches/vsh/rebug/enable/,/
else
end if
`

**Comment by aldostools** [comment]
/mount_ps3 bypass the in-game check that prevents mount a game accidentally if /mount.ps3 is used
