### ISSUE TITLE
PS3 Crashes After installing webMAN MOD

### ISSUE THREAD

**Issue by mohamedhk2** [aldostools/webMAN-MOD#896]
@aldostools

I have a PS3 with 4.90 HEN installed. I tried installing the latest version of webMAN MOD, but it didn't work properly.
I then attempted to install a previous version 1.47.43/1.47.42, and encountered a freeze when enabling HEN.
I even tried installing OFW 4.90 and reinstalling HEN, but I keep experiencing the same problem.
It seems like I've lost my HEN installation. Is there any solution or script to remove webMAN files without HEN?

**Comment by aldostools** [comment]
Due changes in lv2 kernel offsets in 4.90, versions older than 1.47.44 are not compatible.

**Comment by mohamedhk2** [comment]
> Due changes in lv2 kernel offsets in 4.90, versions older than 1.47.44 are not compatible.

How can I resolve this issue?

**Comment by aldostools** [comment]
Install HFW 4.90 (not OFW 4.90) then reinstall HEN.

Put in the root directory of an USB pendrive an empty file (0 bytes) named boot_plugins.txt and plug it in the PS3 before enable HEN. This file will prevent that webMAN MOD be loaded.

To uninstall webMAN MOD there is an option to uninstall it in webMAN Setup menu. Or from PS3 Internet Browser go to http://0/delete.ps3?uninstall

This thread explains how to uninstall webMAN MOD manually:
https://www.psx-place.com/threads/how-to-uninstall-webman-mod.28521/

**Comment by mohamedhk2** [comment]
> Install HFW 4.90 (not OFW 4.90) then reinstall HEN.
> 
> Put in the root directory of an USB pendrive an empty file (0 bytes) named boot_plugins.txt and plug it in the PS3 before enable HEN. This file will prevent that webMAN MOD be loaded.
> 
> To uninstall webMAN MOD there is an option to uninstall it in webMAN Setup menu. Or from PS3 Internet Browser go to http://0/delete.ps3?uninstall
> 
> This thread explains how to uninstall webMAN MOD manually: https://www.psx-place.com/threads/how-to-uninstall-webman-mod.28521/

Thank you, man! The solution worked!
