### ISSUE TITLE
[Question] Copy + Wildcard

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#897]
Aldo as i'm implementing the persitent notification in various options here, i'll ask you some advices

I have a XMB option that shows the xmb screenshots taken  it also has an option to copy them to an external usb drive

/popup.ps3?The operation take a while/nPlease wait.../popup.ps3$Copying...;/copy.ps3/dev_hdd0/*.bmp&to=/dev_usb000/PICTURE/;/popup.ps3*

As the screenshots are saved to the root of the dev_hdd0 and the copy operation is searching for .BMP files in all over the hdd, it takes here more than 30+ minutes to get it done. Is there a better alternative available?

**Comment by aldostools** [comment]
The screenshots can be saved to a specific directory if the path is provided.

Currently /copy.ps3 scans recursively the subdirectories when wildcards are used

**Comment by LuanTeles** [comment]
Yeap, but i'm using the default L2 + R2 + SELECT + START combo, i know i could use custom combos for it, but the user may change it, that's why i'm leaving the default combo in the description of the item

IIRC if the path is given, only one image can be saved or has it been changed?

Dunno what option is better 

![image](https://github.com/aldostools/webMAN-MOD/assets/110236244/8f16fd02-d162-4b6a-b815-81414db7d40c)
![image](https://github.com/aldostools/webMAN-MOD/assets/110236244/5b082908-ea1f-476e-9f75-52eae0a68d75)

**Comment by aldostools** [comment]
In the next build I will add a check to prevent recursive copy from root folder of /dev_hdd0

**Comment by LuanTeles** [comment]
@aldostools 

Many thanks 👍 

Now it is taking less than 5 seconds
