### ISSUE TITLE
PSX Iso

### ISSUE THREAD

**Issue by ruffonetas** [aldostools/webMAN-MOD#9]
Webman mod  1.43.35 freezes when  try to load a PS1 ISO  from usb in fat32 the 1.43.33 the PS1 work  great

**Comment by aldostools** [comment]
The PS1 games that I have tested worked fine from usb fat32

Could you provide more details about the issue?
Like name of the game, fiile name and path where it's stored, sector size of the image (e.g. 2352), file format (iso, img, mdf or cue/bin), does the game have audio tracks?

**Comment by ruffonetas** [comment]
Hi, the games format is bin,cue, the games as stored in a usb sandisk 32GB
formated in fat32, the folder name is PSXISO and all games produce freezes
and blackscreen, many thanks

2016-09-02 20:46 GMT-05:00 Aldo Vargas notifications@github.com:

**Comment by aldostools** [comment]
Could you test again with the current build published few minutes ago?
https://github.com/aldostools/webMAN-MOD/releases/tag/1.43.35

In this commit, I removed the buggy code that caused issues in PSXISO:
https://github.com/aldostools/webMAN-MOD/commit/3e6dddfd201b2703d24dab4179b569524856c125
