### ISSUE TITLE
The page cannot be displayed. ( 8071053d )

### ISSUE THREAD

**Issue by shad00m** [aldostools/webMAN-MOD#90]
I updated from some 1.4x version (I believe it was 1.44.x or 1.42.x)
to the latest 1.47.05.

And now I get a "The page cannot be displayed. (8071053d) when I try to open the Webman Setup.
URL says http://localhost/setup.ps3

it was working totally fine before I updated webman. I didn't update anything else.
Do I need to remove the plugin or something manually?

**Comment by aldostools** [comment]
Check if the /setup.ps3 can be accessed from PC using http://_ip-address-of-your-ps3_/setup.ps3

Also check that your Internet connection is enabled in your Network settings (second column in XMB from left to right).

Can other pages be accessed? Like http://localhost/cpursx.ps3 or  http://localhost/

You can try deleting /dev_hdd0/tmp/wm_config.bin and restart, just in case the wm_config.bin is corrupted.

**Comment by Joonie86** [comment]
Closing old issues that have no further feedback. Please try the latest wMM and report back.

**Comment by joeythecode3r** [comment]
Having this issue right now, nothing mentioned here works 🫤

**Comment by aldostools** [comment]
If you're getting error 8071053d is could be due webMAN MOD is not being loaded or due a hardware issue.

Unplug all USB devices, just in case you have an external /boot_plugins.txt that is preventing the plugin to load.

Make sure that HEN is enabler or Cobra is enabled if you're on CFW, then try reinstalling webMAN MOD.

After installation /dev_hdd0/boot_plugins.txt should exists with a line of text indicating the path where webftp_server.sprx is located.

Hardware issues should be solved replacing the damaged components.

**Comment by joeythecode3r** [comment]
Trying to delete webman jst freezes my ps3...

**Comment by aldostools** [comment]
The wiki explains how to uninstall webMAN MOD manually.
https://github.com/aldostools/webMAN-MOD/wiki/~-Uninstalling-webMAN-MOD

**Comment by RobertoTorino** [comment]
I had it a few times, found out that if you reboot with rebuild database the issue is solved.
