### ISSUE TITLE
[Bug] PS3 Isos gameboot

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#902]
Aldo, the dynamic gameboots work fine, but not on the first launch

Seems like when you first mount a game the animation will not run, only the sound, is it the normal behaviour? i do't remember because i don't play in the ps3.

**Comment by aldostools** [comment]
There is patch in Ultimate Toolbox that extends the time of boot sound. I'm not sure if it works or needs to be ported to 4.90.

In regards to ps3. The plugin assumes that the default gameboot is PS3. It restores the PS3 gameboot only on certain events, since the patch is reset when the game returns to XMB.

**Comment by LuanTeles** [comment]
I'll go back to 4.88 to see if it is a problem with the sprx/rco that needs to be ported

**Comment by LuanTeles** [comment]
Edit: Seems i'm wrong, even ps2 isos gameboot dont play if it is the first thing you mount with webMAN mod

**Comment by LuanTeles** [comment]
Also when i exit a ps2 game, i can't mount anything with webMAN i get "webman not ready" i think i already reported this issue and you couldn't reproduce

The internet connection is also lost, I will ask some friends to see it happens to them too

**Comment by aldostools** [comment]
To know better what is happening you could use socat with the debug version of Cobra to see the debug messages.

You could check if that happens with the lite or standard editions too, in case that the network issue is due the large memory footprint of the full edition.

**Comment by LuanTeles** [comment]
@aldostools i went back to Rebug 4.84.3 (Cobra v8.3) ps3 game isos dynamic gameboot still don't work, no gameboot and some times  the default one (ps logo). (when the patch is not applied or going back to xmb and launch it again, as it is resetted)

PS2 dynamic gameboot is working

Maybe it got broken in some builds ago.

**Comment by aldostools** [comment]
ps3 is assumed to be default gameboot. if the search pattern is not found in the memory range searched, the patch is not applied.

**Comment by LuanTeles** [comment]
@aldostools I just installed .34 and now it is working,  so just the ps3 one got broken at some point in newer builds

**Comment by aldostools** [comment]
> @aldostools I just installed .34 and now it is working, so just the ps3 one got broken at some point in newer builds

hmmm I don't know if I will have time to fix it. There is a large number of changes between .34 and .45, so it's difficult to check.

Anyway it's good to know that .34 works.

**Comment by LuanTeles** [comment]
The fun thing is that only the ps3 logo got affected by the issue.

I'll try newer builds to see the exactly one that it got broken, i just went that low because it's the one that the feature got introduced.

btw, i tried the lite version and same issue after exiting a ps2 game, my lan port is broken so i can't use socat, i'll see if i fimd someone with the same problem as me.

**Comment by LuanTeles** [comment]
@aldostools the .38 is the last one that it works.

so maybe just the anim name for the ps3 games is wrong or something.

i said it doesn't work on first launch because it was getting reset when exiting to cmb so it doesn't work at all, all the others works, maybe just the ps3_gameboot plane name that is wrong.

but also the others requires at least one game mounted before in newer builds.

.38 everything is perfect

**Comment by aldostools** [comment]
I did a quick compare of patch_gameboot.h between .38 and .45 and I couldn't find big differences, except that .45 uses case insensitive strings to detect the emulator type.

I added support for GAMES folder in this test build [webftp_server_1.47.45_20230708.zip](https://github.com/aldostools/webMAN-MOD/files/11992390/webftp_server_1.47.45_20230708.zip) in case you're testing with these type of games.

**Comment by LuanTeles** [comment]
> I did a quick compare of patch_gameboot.h between .38 and .45 and I couldn't find big differences, except that .45 uses case insensitive strings to detect the emulator type.
> 
> I added support for GAMES folder in this test build [webftp_server_1.47.45_20230708.zip](https://github.com/aldostools/webMAN-MOD/files/11992390/webftp_server_1.47.45_20230708.zip) in case you're testing with these type of games.

Indeed i was using JB format games in my tests, now they are working, thanks Aldo.

So the support for GAMES that was removed? as they were working in .38

Now seems that even ps2 isos are getting the gameboot on the first try, everything is perfect now

**Comment by LuanTeles** [comment]
@aldostools Any info about the write.ps3?

**Comment by aldostools** [comment]
> @aldostools Any info about the write.ps3?

Search that command in the wiki
https://github.com/aldostools/webMAN-MOD/wiki/Web-Commands

**Comment by LuanTeles** [comment]
> > @aldostools Any info about the write.ps3?
> 
> Search that command in the wiki https://github.com/aldostools/webMAN-MOD/wiki/Web-Commands

I know, I think you didn't see the other issue I opened today, I asked if there is a size limit because it doesn't work just on a file here with the size of 145KB, I use it to enable/disable each xmb item individually, but only in this file it doesn't work

**Comment by aldostools** [comment]
> I know, I think you didn't see the other issue I opened today, I asked if there is a size limit because it doesn't work just on a file here with the size of 145KB, I use it to enable/disable each xmb item individually, but only in this file it doesn't work

The web commands /write.ps3 & /write_ps3 has a read limit of 128KB
https://github.com/aldostools/webMAN-MOD/blob/master/include/cmd/write_trunc_unzip.h#L68

**Comment by LuanTeles** [comment]
> > I know, I think you didn't see the other issue I opened today, I asked if there is a size limit because it doesn't work just on a file here with the size of 145KB, I use it to enable/disable each xmb item individually, but only in this file it doesn't work
> 
> The web commands /write.ps3 & /write_ps3 has a read limit of 128KB https://github.com/aldostools/webMAN-MOD/blob/master/include/cmd/write_trunc_unzip.h#L68

Thanks for the info Aldo, I will try to reduce the size. I think I overdid my options to uninstall games through the xml that categorizes the xmb in folders, XMB games + webman games.

I added support for the extended profiles and upper and lower case.

i added extra +/- 150 lines for each folder, ps3, ps2, ps1....

Maybe the best idea is to split the xml, one just with the uninstall queries.

![image](https://github.com/aldostools/webMAN-MOD/assets/110236244/1896573b-cb74-403f-85ec-629454ab0515)
![image](https://github.com/aldostools/webMAN-MOD/assets/110236244/9b120b8a-870a-4012-a1f6-1ac5f5c092ea)
![image](https://github.com/aldostools/webMAN-MOD/assets/110236244/a867b63a-8c44-42be-8519-49157a058ea4)
![image](https://github.com/aldostools/webMAN-MOD/assets/110236244/66af754d-e738-476c-bc6b-5a26f624b0a1)
![image](https://github.com/aldostools/webMAN-MOD/assets/110236244/9092b691-d5f3-4085-98b5-071dd1eccae2)
