### ISSUE TITLE
'Virus detected'

### ISSUE THREAD

**Issue by Zarh** [aldostools/webMAN-MOD#91]
When i try to download sources with Chrome, the download fail because it detect a 'virus'.

**Comment by 4ipon4ik** [comment]
Deal with your antivirus, chrome or it's extensions. I have chrome and don't have this issue. You can't execute .pkg files in PC anyway, :\

**Comment by aldostools** [comment]
Most of the files in the source code are plain text files (.h or .c).
However the source also include some Windows executable files too (_make.exe, ps3netsrv.exe, some ps3 tools and dlls, etc.)

As far as I know none of these files have virus (at least my antivirus haven't detected any), so it can be a false positive in your antivirus or Chrome.

@Zarh It would help me if you could identify me the specific file that is triggering the virus alert.

**Comment by Zarh** [comment]
I'm sry don't have this issue anymore, I can't tell you which file was causing it...

FYI, the trojan detected was https://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=Trojan%3aWin32%2fSpursint.F!cl&threatid=2147717281&enterprise=0
