### ISSUE TITLE
External drive exFAT vs NTFS

### ISSUE THREAD

**Issue by mkardi** [aldostools/webMAN-MOD#914]
webMAN-MOD supports both exFAT and NTFS for external drives.

I am curious if one have any advantage over another from performance standpoint? I assume NTFS has bigger footprint.
Which one has lower overhead / memory usage, or there is no measurable difference?

**Comment by aldostools** [comment]
webMAN MOD supports FAT32 and UFS2  (the internal HDD file system) as native file systems 
That means that they don't require any extra software to recognize the disk storage.

exFAT/NTFS/ext2/ext3/ext4 are also supported in raw sector mode though prepISO. That means that after prepISO is executed, the cache files are stored in the internal HDD containing a list of raw sectors for each ISO in the external disk. 

webMAN MOD mounts the cached files *.ntfs[***ISO] using the VSH plugin **raw_iso.sprx** which acts as a communication proxy between Cobra and ISO stored in the external disk in exFAT/NTFS/ext2/ext3/ext4 format. Therefore the **memory usage is the same** for any of these ISO.

I don't know of any performance difference between these file systems. The performance is more relative to the disk type (SDD, mechanical HDD or hybrid), spin speed, cluster size, disk fragmentation, the cable (USB 2.0 specification is the faster speed even if USB 3.2 is used), among other variables.

NTFS has the advantage that if the standard or full editions are used, the files can be accessed through FTP.
Also webMAN MOD can scan the NTFS files without prepISO. Although prepISO is recommended method for better results.

exFAT disks only can be managed using IRISMAN File Manager or Simple File Manager or from a PC.

**Comment by mkardi** [comment]
Thank you very much aldostools, it answered my question :)
