### ISSUE TITLE
Some iso's doesn't work from external NTFS HDD

### ISSUE THREAD

**Issue by FloatDoubling** [aldostools/webMAN-MOD#919]
I got a jailborken PS3 with 4.84.2 Rebug D-REX installed, also WebMAN MOD latest version (1.47.45), prepISO addon 1.30, and bunch of other homebrews, such as MultiMAN, IrisMAN, ManaGunZ etc.

My external 1TB HDD is formatted in NTFS MBR, single partition, all ISO's are in PS3ISO root folder. I got 10 iso's on it. When i run prepISO via webMAN games menu, all games from HDD are correctly shown in webMAN PS3 games menu and also in any other backup manager.

![image](https://github.com/aldostools/webMAN-MOD/assets/115502326/804ae54a-0d3d-4d08-8b8e-ef301a8c91c2)

The thing is, when i load some iso via webMAN or any other manager, boot it up, it shows black screen for 2-3 seconds, my monitor blinks (resolution change from 720p to 1080p) and i kicked back to XMB without any reason whatsoever. From what i got on HDD and tested for this time, 2 iso are not loading: God of War III (BCES00510) and Sleeping Dogs (BLUS30927), 4 iso are loading: Sonic Unleashed, God of War Collection, Need for Speed Most Wanted and Skate 3. Changing USB HDD connection port does nothing (i got 4 of them on console, all same result).

All iso are properly dumped to JB folder via PS3 Dumper 3.3.6, then they were rebuilded with proper IRD via 3k3y ISO Tools, all files and regions hashes verified, even on PS3 with HDD connected and ManaGunZ manager via IRD check, that showed all files hashes correct to their IRD.

![image](https://github.com/aldostools/webMAN-MOD/assets/115502326/1f6e0dbe-9227-49ff-9299-aad30033263f)

![image](https://github.com/aldostools/webMAN-MOD/assets/115502326/14b655f9-25c8-4693-9585-7ae229096479)

**Comment by aldostools** [comment]
Please try running prepISO again and check if the games work. 

Some versions of multiMAN may replace the files in /dev_hdd0/tmp/wmtmp with an incompatible version of the cached files.

It is recommended to keep defragmented the external HDD and run prepISO after it's done. If the ISO is too fragmented, it may cause black screens or the game may not start.

If the issue persists, you can try playing the ISO from /dev_hdd0/PS3ISO to verify that the ISO is not corrupted.

You can try dumping again the game from your original disc, then rebuild the ISO using IRISMAN, multiMAN or ManaGunZ

**Comment by FloatDoubling** [comment]
Thanks for your reply Aldo, yeah i redid everything, i checked hdd with special software for bad regions and general drive health, it was all perfect (HDD is new with 28 hours uptime), fragmentation was on 0%, cause i didn't delete nothing from it. So it's not HDD definetely.

Turns out, because i have my PS3 on DEX Rebug firmware with console itself converted to DEX, i had to change one little option in debug settings: Boot mode. By default, it was in System Software Mode, but i had to change it ot Release mode and ALL my iso's from external HDD started to work perfectly. I need to be more careful and selective with DEX firmware and debug settings i guess.
