### ISSUE TITLE
FTP cant use

### ISSUE THREAD

**Issue by N2022062** [aldostools/webMAN-MOD#92]
newest ver. wm
either filezilla or flashfxp cant dl file
but can show list

**Comment by masterzorag** [comment]
http://fireftp.net provides a simply firefox addon, give it a try...

**Comment by N2022062** [comment]
i find the problem
when p3 start,u should press L2 R2 to open admin Every time
if u open u can use FTP 2 dl...

**Comment by aldostools** [comment]
Try disabling the combo "ADMIN/USER MODE" in /setup.ps3 and restart.

Or delete /dev_hdd0/tmp/wm_config.bin and restart the console to start using again the default settings.

**Comment by N2022062** [comment]
tried!worked!
thx!
