### ISSUE TITLE
Question about PS2 emulator configs

### ISSUE THREAD

**Issue by mkardi** [aldostools/webMAN-MOD#926]
How does emulator configs from PS2CONFIG.pkg work when running PS2 games on PS3?
I understand there are different versions of backwards compatibility configs such as NET, GX, SOFT etc.

Which version is used when I run PS2 game, does it detect console model and then pick most suitable one?
If I add my own .CONFIG in /PS2ISO folder next to game ISO then does it override what was installed with PS2CONFIG.pkg package?

**Comment by aldostools** [comment]
The PKG is only needed if you use PS2 images in .BIN.ENC format. If you have CFW and use ISO, the configs are already included in webMAN MOD.

If the .CONFIG file exists in the same folder of the ISO, it overrides the ones in the configs database.

If it doesn't exists, webMAN MOD searches the database and select the most appropriate if finds one that match with the game Id.

The recommended search order is CUSTOM, NET, SOFT, GX.

**Comment by mkardi** [comment]
Thank you for explaining.
I have PS3 with CFW so I guess installing PKG does not make any sense.

What do you mean that configs are already included with webMAN MOD?
PS2CONFIG.pkg is around 100MB while webMAN MOD is way smaller, does installer still include everything from PKG?

**Comment by aldostools** [comment]
The configs for ISO are very small. Only take around 6MB in webMAN MOD installer and in the database PKG.

The database PKG includes the encrypted configs for .BIN.ENC that weight around 90MB. These files are not included in webMAN MOD installer.

**Comment by mkardi** [comment]
I see, thanks and we can close this topic.
