### ISSUE TITLE
Icon "icon_wm_root" from Standard Theme has incorrect opacity and scale (fix here)

### ISSUE THREAD

**Issue by Zoukambada** [aldostools/webMAN-MOD#931]
As the header says, the Standard Theme (wm_theme_standard.pkg by deank ) has its "icon_wm_root.png" in incorrect opacity and scale.
The current icon is smaller and has no transparency in its fill.

The image below is the fixed ICON. It just needs to replace the current (/dev_hdd0/tmp/wm_icons/) and to be repacked in the theme pkg.

Preview:
![icon_wm_root](https://github.com/aldostools/webMAN-MOD/assets/8125662/2c1ecca1-9ef0-420e-af96-9ce72613e5fe)

File:
[icon_wm_root-wm_theme_standard.zip](https://github.com/aldostools/webMAN-MOD/files/12389264/icon_wm_root-wm_theme_standard.zip)

**Comment by aldostools** [comment]
Thank you. I've updated the package with your fixed icon.
https://github.com/aldostools/Resources/releases/download/Themes/wm_theme_standard.pkg
