### ISSUE TITLE
[Improvement] dev_blind operations

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#938]
Aldo, if a web command/script with copy/move operations requires the dev_blind to be enabled and it is not, can webMAN temporarily enable it to execute the operation?

**Comment by aldostools** [comment]
If the user navigates to `/dev_blind` using FTP or the web file manager, it is enabled automatically.

If a web command/script requires to write to `/dev_blind`, it must be enabled explicitly.

There is an option in /setup.ps3 to enable /dev_blind at startup. It allows to write to flash memory at any time.

**Comment by LuanTeles** [comment]
Yeap, i know i was just thinking because some homebrews can disable the dev_blind without the user noticing it, the XMBM+ manager is one of them, i launched it and after i tried to use web commands through my XMBML that requires dev_blind and it didn't show any error, so i thought it enabled by itself but i was wrong, the operation failed without any feedback.

But the best way is adding the command to enable the dev_blinf explicitly in every command that requires it, i'll add it in all my xmbml+ commands.
