### ISSUE TITLE
Cant change betwen editions ps3hen

### ISSUE THREAD

**Issue by alfredox123** [aldostools/webMAN-MOD#939]
I pressed the buttons to change editions and it doesnt do anything, i have a fresh intall of webMAN MOD 1.47.45 and hfw 4.90.1 with hen 3.2.2. Dont know if i need to check something first to make it work?

**Comment by aldostools** [comment]
Please check in /setup.ps3 that the combo UNLOAD WM (`L3`+`R2`+`R3`) is checked in the section **XMB/In-Game PAD SHORTCUTS**

In the folder `/dev_hdd0/plugins` should exist the following 2 plugins:
* webftp_server.sprx
* webftp_server_lite.sprx

**Comment by alfredox123** [comment]
It's working now thx, is there a way to start in default as the lite edition?

**Comment by aldostools** [comment]
Install the Lite edition using the installer or edit /dev_hdd0/boot_plugins.txt  and change the path to this one:

`/dev_hdd0/plugins/webftp_server_lite.sprx`
