### ISSUE TITLE
dev_bdvd mounting error PS2

### ISSUE THREAD

**Issue by pitrako** [aldostools/webMAN-MOD#943]
If I copy and paste manually games work, but It would be easier auto copying the game and this feature of webman mod is not working, maybe showing copy progress too in xmb would be a good idea.

**Comment by aldostools** [comment]
Try updating to the latest build 4f9edb380711f9cceacff55c69fdb96543142cfc using the online updater found in webMAN MOD Setup on the XMB.

Please reboot after update and test again.

**Comment by pitrako** [comment]
Now it works, thanks.
