### ISSUE TITLE
Trying to edit memory with PS3MAPI, keep getting `Error: -2147418099`

### ISSUE THREAD

**Issue by kernaltrap8** [aldostools/webMAN-MOD#944]
I'm trying to edit memory for a patch in a game, and it keeps erroring out. I'm doing it this way to see if the patch works before making a SPRX to automate the process.

---
![image](https://github.com/aldostools/webMAN-MOD/assets/94473358/d374eace-8c98-40ae-a652-b8756f55b116)

Console is running EVILNAT 4.90 DPEX, converted to DEX kernel.

---
![image](https://github.com/aldostools/webMAN-MOD/assets/94473358/3e3b7838-748c-4faa-a23b-7169e344f078)

**Comment by kostirez1** [comment]
Error 8001000D, [Invalid memory access](https://github.com/PhoenixARC/PS3ErrDB/blob/15c3d0f9f390eaffaae2a0cb9bca820d9114e7e5/bin/Debug/db.txt#L34C48-L34C48)

Either the address is wrong, or the patch lands beyond the writable memory segment.

**Comment by aldostools** [comment]
Also I suggest to check the patch using [NetCheatPS3](https://github.com/Dnawrkshp/NetCheatPS3)

https://netcheat.gamehacking.org/ncUpdater/

**Comment by kernaltrap8** [comment]
> Error 8001000D, [Invalid memory access](https://github.com/PhoenixARC/PS3ErrDB/blob/15c3d0f9f390eaffaae2a0cb9bca820d9114e7e5/bin/Debug/db.txt#L34C48-L34C48)
> 
> Either the address is wrong, or the patch lands beyond the writable memory segment.

im sure the address is correct, i found it using a memdump. you'd think i'd be able to write to LV0 memory with peek/poke, but i guess not.

> Also I suggest to check the patch using [NetCheatPS3](https://github.com/Dnawrkshp/NetCheatPS3)

>
> https://netcheat.gamehacking.org/ncUpdater/

i'll try this out.

**Comment by jordywastaken** [comment]
As kostirez said, the error is an invalid memory access. The offset you are using looks to be in decimal, webman thinks it's hexadecimal (base 10 vs base 16) which results in poking/peeking into a non-mapped area (in this case, 0x3971470 instead of 0x3C998E).
You can use Google or any other tool to convert from decimal to hexadecimal

![image](https://github.com/aldostools/webMAN-MOD/assets/113445560/599e0652-f529-4a6e-9b71-cb0bf5201104)

I hope it helps 🙂

**Comment by kernaltrap8** [comment]
> As kostirez said, the error is an invalid memory access. The offset you are using looks to be in decimal, webman thinks it's hexadecimal (base 10 vs base 16) which results in poking/peeking into a non-mapped area (in this case, 0x3971470 instead of 0x3C998E).
> You can use Google or any other tool to convert from decimal to hexadecimal

the offset is in hexadecimal, it should be what HxD gives me. i know its the correct offset because when i search for it in wmM it gives me the correct values. correct values being the same things i see in the memory dump in HxD. could it be erroring out because its in LV1 memory space?

**Comment by aldostools** [comment]
Try forcing hex entering **0x**3971470. The value 3971470 is ambiguous.

**Comment by jordywastaken** [comment]
> the offset is in hexadecimal, it should be what HxD gives me. i know its the correct offset because when i search for it in wmM it gives me the correct values. correct values being the same things i see in the memory dump in HxD. could it be erroring out because its in LV1 memory space?

Could you provide a screenshot of HxD with your dump? Because what you described is a bit vague, we need to know more if you want us to help 🙂

**Comment by kernaltrap8** [comment]
> Could you provide a screenshot of HxD with your dump? Because what you described is a bit vague, we need to know more if you want us to help 🙂

of course.

![image](https://github.com/aldostools/webMAN-MOD/assets/94473358/91b2547a-5c0f-406b-b92b-8baaee6c50e4)

the value highlighted is the value i need to change. i have to change it to a `01`. WoR does a check to see if you're on a retail or debug build, and changes the value (01 = debug, 00 = retail) accordingly in memory. i need to test this to make sure it works, but keep getting invalid memory access errors.

> Try forcing hex entering 0x3971470. The value 3971470 is ambiguous.


tried this, doesnt work. 

![image](https://github.com/aldostools/webMAN-MOD/assets/94473358/f5afb6f2-fbe9-42ee-98e5-547e586ad033)

**Comment by jordywastaken** [comment]
Was it a full memory dump made with webman or a process dump?

**Comment by kernaltrap8** [comment]
> Was it a full memory dump made with webman or a process dump?

full memory dump, exactly `268,435,456` bytes

**Comment by jordywastaken** [comment]
Try to dump the process instead. A full memory dump is different than a process dump, thus making the memory addresses or offsets for the game different,

**Comment by aldostools** [comment]
Note: By default the size of the process dump is 0x400000 (4MB). The dump size can be increased changing the value in the URL.

Verify that the value shown in the text box when you "Get" the memory start with `2AF92804` like the hex code in the dump.
If it gets a different value, then the offset is wrong.

**Comment by kernaltrap8** [comment]
> Try to dump the process instead. A full memory dump is different than a process dump, thus making the memory addresses or offsets for the game different,

the values are only found in LV1 process memory. i thought that was strange, but perhaps the way the game works is why. the files are usually compressed but are uncompressed in memory when the game boots.



> Note: By default the size of the process dump is 0x400000 (4MB). The dump size can be increased changing the value in the URL.
> 
> Verify that the value shown in the text box when you "Get" the memory start with `2AF92804` like the hex code in the dump. If it gets a different value, then the offset is wrong.

the offsets are both the same in HxD and in webMAN MOD, so i know the value is correct. why i cant edit it is beyond me. im very new to editing memory on PS3, so i dont know if this is a common issue or not.

**Comment by aldostools** [comment]
Check if you can use **/poke.lv1**?`address`=`new value`

First use /peek.lv1?`address`  to verify that you're reading the proper memory address.

**Comment by kernaltrap8** [comment]
> Check if you can use **/poke.lv1**?`address`=`new value`
> 
> First use /peek.lv1?`address` to verify that you're reading the proper memory address.

this worked! thanks for the help Aldo.

**Comment by jordywastaken** [comment]
Not to be the annoying guy, but poking lv1 is only available on cfw, so no hen support for your debug-build check patch 🙁

**Comment by kernaltrap8** [comment]
> Not to be the annoying guy, but poking lv1 is only available on cfw, so no hen support for your debug-build check patch 🙁

this is true. however, this is temporary for now. later on i will edit game files to have the game do it itself (essentially the opposite of what it does now) or, do memory edits with a SPRX.

**Comment by jordywastaken** [comment]
I see, good luck with your project! 👍
