### ISSUE TITLE
[Suggestion] webMAN Download Link 

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#946]
Aldo, can you add the webman download link in this section:

![image](https://github.com/aldostools/webMAN-MOD/assets/110236244/b1f2de98-7980-41ae-80b1-08098fb2b571)

So the user can access the repository and be able to download it directly to the ps3. clicking in the assets button on the release page via ps3 web browser does nothing so one can't download it

**Comment by aldostools** [comment]
Thank you for the suggestion. Unfortunately the other links (cover packs, retroarch, etc.) don't download either.
It would not make any difference if I addi direct link to webMAN MOD. Github site is not PS3 friendly.

**Comment by LuanTeles** [comment]
Actually they all work

If you are on DEX vsh.self, switch to the CEX one, the current github certificates (since may) only works on fw 4,85+

![image](https://github.com/aldostools/webMAN-MOD/assets/110236244/8ccc6b41-51a4-4942-89d0-1e0dd73c6240)
![image](https://github.com/aldostools/webMAN-MOD/assets/110236244/de90ce2d-8dc7-4586-96c7-d9707eaa024b)
![image](https://github.com/aldostools/webMAN-MOD/assets/110236244/2e7c3c14-a0c5-4f83-8955-5d02a199a628)

**Comment by aldostools** [comment]
Thanks for the information. I guess it would be better to create a web page for download from PS3 browser. I will try to work on this tonight or in the weekend.

**Comment by aldostools** [comment]
Try http://ps3.aldostools.org/links.html

**Comment by LuanTeles** [comment]
works good aldo :)
