### ISSUE TITLE
[BUG] webMan latest not installing

### ISSUE THREAD

**Issue by quimodotcom** [aldostools/webMAN-MOD#947]
For some reason, my PS3 is flashing the installing message then after giving me the error "An error occured during the install operation (8001002C)" then after exiting the install process, opening anything except for shouting down the system will black screen the console and reboot it.

PS3 SUPER SLIM
PS3HEN 3.2.2
webMan 1.47.44/45

**Comment by aldostools** [comment]
The error 0x8001002C means "Too many files open."

Do you have any Homebrew Store or additional plugins installed on your console? They could cause conflict with webMAN MOD. I recommend to make a fresh install (reinstall HFW + HEN + webMAN MOD). The error could be related to some issue with your internal HDD. Before reinstall everything I recommend that go to Recovery menu and check the file system.

Are you updating from web or installing webMAN MOD from Github, Brewology or another source?
I recommend that install the pacakge from Brewology or https://github.com/aldostools/webMAN-MOD/releases

**Comment by quimodotcom** [comment]
> The error 0x8001002C means "Too many files open."
> 
> Do you have any Homebrew Store or additional plugins installed on your console? They could cause conflict with webMAN MOD. I recommend to make a fresh install (reinstall HFW + HEN + webMAN MOD). The error could be related to some issue with your internal HDD. Before reinstall everything I recommend that go to Recovery menu and check the file system.
> 
> Are you updating from web or installing webMAN MOD from Github, Brewology or another source? I recommend that install the pacakge from Brewology or https://github.com/aldostools/webMAN-MOD/releases

If that does mean Too many files open, That gives me one big hint as to what it could be, and I will test it later today.

For anyone wondering, At the moment PKGi is bugged where if you start a download, you are black screened out of using the tool while it is downloading - which means no way to stop the download. PKGi's newest release has also been bugging out a few things so that's most definitely the answer!

Thanks for the reply aldostools!

Edit: will be leaving this issue open while these downloads are finishing then will update this thread.

**Comment by quimodotcom** [comment]
It has finished all the downloads and still the same error without the installing message flashing

**Comment by quimodotcom** [comment]
FIXED!!!

SOLUTION: If you get the error mentioned above, Download the webMan.pkg from the playstation browser. For some reason, the browser wouldn't load a new page so every time I had to clear cache to progress and the use the File -× Address function to download it from brewology!
