### ISSUE TITLE
Connect to NAS

### ISSUE THREAD

**Issue by carlni2008** [aldostools/webMAN-MOD#948]
I have a Synalogy DS218j which I hope that webMAN can connect to and able to play all my games thats stoared there.
How do I configure webMAN or my NAS so thay can connect?
Thanks a lot!

**Comment by aldostools** [comment]
Use ps3netsrv to stream your games to webMAN MOD. The server is available for multiple platforms. There is an old version for Synology in the repository or you can compile your own version.

Check https://github.com/aldostools/webMAN-MOD/wiki/~-PS3-NET-Server

If you have doubts you can ask in PSX-PLACE forums.

**Comment by carlni2008** [comment]
![image](https://github.com/aldostools/webMAN-MOD/assets/61369052/5e305a96-6bd4-4773-a58c-c5301717e280)
Which one should I use?

**Comment by aldostools** [comment]
The docker version worked on a Synology DS1821. You can try that one.
https://www.psx-place.com/threads/ps3-net-server-for-synology-nas.34351/

**Comment by carlni2008** [comment]
I'll try the precompiled ARM version from https://github.com/aldostools/webMAN-MOD/tree/master/_Projects_/ps3netsrv/bins/old for now.

**Comment by kostirez1** [comment]
> The docker version worked on a Synology DS1821.

Synology sadly never shipped Docker extension for ARM based machines.

> I'll try the precompiled ARM version from https://github.com/aldostools/webMAN-MOD/tree/master/_Projects_/ps3netsrv/bins/old for now.

Looks like the `SynologyDS1512_ARM` version is compiled for ARM v8, while the `Marvell Armada 385` in DS218j is ARM v7 (+ NEON) based. You may need a different build for that architecture.

Also, DSM supports [upstart (DSM v6)](https://gist.github.com/SanCoder-Q/f3755435e6e8bd46ba95bf0ec54ae1a4) and [systemd (DSM v7)](https://gist.github.com/SanCoder-Q/f3755435e6e8bd46ba95bf0ec54ae1a4?permalink_comment_id=3844174#gistcomment-3844174) service management, which will make your life easier. 🙂

**Comment by carlni2008** [comment]
Yep I just realized I can't install docker on the machine.

Compiling is going to be such a pain for me as I have no knowledge on compiling.

**Comment by kostirez1** [comment]
Try this build: [ps3netsrv_DS218j_armada38x_static.zip](https://github.com/aldostools/webMAN-MOD/files/12563393/ps3netsrv_DS218j_armada38x_static.zip)

Built using [armada38x-gcc850_glibc226_hard-GPL.txz](https://global.synologydownload.com/download/ToolChain/toolchain/7.1-42661/Marvell%20Armada%2038x%20Linux%203.10.108/armada38x-gcc850_glibc226_hard-GPL.txz) from Synology.
Makefile addition:
```
CC = arm-unknown-linux-gnueabi/bin/arm-unknown-linux-gnueabi-gcc
CXX = arm-unknown-linux-gnueabi/bin/arm-unknown-linux-gnueabi-g++
```

`file` command output: `ps3netsrv: ELF 32-bit LSB executable, ARM, EABI5 version 1 (GNU/Linux), statically linked, for GNU/Linux 3.2.0, with debug_info, not stripped` 

Even though it's a toolchain for DSM v7, there shouldn't be any issues on v6 since it's statically linked (has no dependencies).

**Comment by carlni2008** [comment]
> Try this build: [ps3netsrv_DS218j_armada38x_static.zip](https://github.com/aldostools/webMAN-MOD/files/12563393/ps3netsrv_DS218j_armada38x_static.zip)
> 
> Built using [armada38x-gcc850_glibc226_hard-GPL.txz](https://global.synologydownload.com/download/ToolChain/toolchain/7.1-42661/Marvell%20Armada%2038x%20Linux%203.10.108/armada38x-gcc850_glibc226_hard-GPL.txz) from Synology. Makefile addition:
> 
> ```
> CC = arm-unknown-linux-gnueabi/bin/arm-unknown-linux-gnueabi-gcc
> CXX = arm-unknown-linux-gnueabi/bin/arm-unknown-linux-gnueabi-g++
> ```
> 
> `file` command output: `ps3netsrv: ELF 32-bit LSB executable, ARM, EABI5 version 1 (GNU/Linux), statically linked, for GNU/Linux 3.2.0, with debug_info, not stripped`
> 
> Even though it's a toolchain for DSM v7, there shouldn't be any issues on v6 since it's statically linked (has no dependencies).

Hi sorry I know this might be a dumb question, but can you give a bit more detailed instructions on what to do with the file please? Thanks.

**Comment by carlni2008** [comment]
@kostirez1 Thanks lot for your built! This file worked flawlessly! Thank you very much.
