### ISSUE TITLE
Silent Hill NTSC-U won't work via WebMAN

### ISSUE THREAD

**Issue by shawly** [aldostools/webMAN-MOD#95]
I'm on Rebug 4.81.2 with WebMAN-MOD 1.47.05 and I can't play the NTSC version of Silent Hill, the game will mount without issues but if I start the game the screen just stays black, the PS3 doesn't freeze, I can still exit to XMB.

I also tried different dumps since I thought it was my dump that had issues but none of them work. After that I tried **the PAL version which does load and is playable**.

This issue was reproducable on my old PS3 too, after it died I bought another PS3 Slim which has exactly the same issue, the CFW was freshly installed after I got the PS3 and I immediately tried to play the game only to find out that it also won't play on my new system.

I also tried to use an older version of webMAN, I've downgraded until version 1.45.02, none of the webMAN builds that support FW 4.81 work with Silent Hill.
This issue was also reproducable on FW 4.80.
This has been tried with Cobra 7.3 on Rebug 4.80.1 and Cobra 7.5 on the latest Rebug 4.81.2

**Steps to reproduce the issue**
1. Get any dump of the NTSC-U version of Silent Hill
2. Transfer the game to the PS3
3. Mount the game via WebMAN
4. Try to play the game

The game will start but you won't even see the Playstation logo, other PSX games work just fine for example the NTSC version of Resident Evil.

**Workaround**
1. Open Rebug Toolbox
2. Disable COBRA
3. Mount the game via MultiMAN (Cobra Mode)
4. Start the game

This workaround works, but since it requires a restart of the system and the cooling fan spins on maximum, it's not a viable option to play the game.

**Comment by hanswurst31** [comment]
how do you start the game in multiman/cobra mode when cobra is disabled? i get the massage that cobra is disabled

**Comment by shawly** [comment]
Exactly like I described in the workaround. But since the fan is spinning like hell I don't use this workaround, I use the PAL version of Silent Hill.

**Comment by hanswurst31** [comment]
the cobra mode gives me the error tgat the cobra mode is not active

**Comment by shawly** [comment]
So? I don't get this error, I can't help you bro..

**Comment by wahlmanj** [comment]
I had a few issues with a number of games myself until recently. Once I converted my games to ISO's and didn't use the games folder anymore all of them work using webman and sman perfectly. Try to convert it to a iso put it in PS3ISO and see if it runs. Im betting money it will work without mm using that method. What is the game called specifically BLESxxxx OR BLUSxxxx What?

Edit - Wait is this a PS1 or PS2 game? If it is not disregard my fix.

**Comment by 44daniel** [comment]
solution 1 : convert iso to pkg
solution 2: uninstall webman mod (This is the command: http://127.0.0.1 /delete.ps3?uninstall   or http://ip address /delete.ps3?uninstall ), Delete any webMAN configuration files & folders in /dev_hdd0/tmp/which names start with "wm". Delete the /dev_hdd0/xmlhost folder as well.  Launch webman mod  Updater & keep pressing L1 until the console reboots. Reconfigure webMAN-MOD completely.

**Comment by Joonie86** [comment]
Closing old issues that have no further feedback. Please try the latest wMM and report back.
