### ISSUE TITLE
[Suggestion] IDPS and PSID input field

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#952]
Aldo, can you add the ability for the user to put the full IDPS/PSID in the input field and have both fields automatically filled in?

![image](https://github.com/aldostools/webMAN-MOD/assets/110236244/c591642c-4be5-46f4-a92f-276bf2448073)

the current way, you have to divide the IDPS/PSID and paste it in the first field and then the rest in the second and well, it's kinda boring

**Comment by LuanTeles** [comment]
Still on IDPS/PSID, evilnat firmwares now have the option of falsifying the PSID and IDPS from txt files, I'm wondering about which one will have the priority webMAN or Cobra? Does webMAN detect these files and load them from there instead of the one defined in wm_config or it takes the priority?


I haven't tried it yet, but this came to mind.

**Comment by aldostools** [comment]
I don't plan to implement this "feature".

The IDPS/PSID a one time setting. From a PC or table/smartphone it isn't difficut to paste on both fields.
