### ISSUE TITLE
Webman installer pkg from Releases is corrupted

### ISSUE THREAD

**Issue by didiraja** [aldostools/webMAN-MOD#955]
Last week downloaded installer pkg from repo e worked fine. Repeating the process yesterday and today, and xmb says data are corrupted. After that, noted there's commits from 3/4 days ago. Downloading from Brewology is working totally fine.

Just to let you know.

**Comment by aldostools** [comment]
I have re-uploaded the pkg. You can test downloading the file again from
https://github.com/aldostools/webMAN-MOD/releases

**Comment by didiraja** [comment]
@aldostools thank you so much for the answer and huge effort on tools
