### ISSUE TITLE
vsh plugins go boom

### ISSUE THREAD

**Issue by jordywastaken** [aldostools/webMAN-MOD#958]
Hi, an issue i've encountered many times already, i can't load any of my vsh plugins alongside webman with boot_plugins.txt on Hen, it loads perfectly fine on cfw.

This issue happened first in early 2022 with the release of the Akari vsh menu, people have been reporting issues and system hangs when loading it with webman.

I've been looking for a way to fix this but i can't figure out why it doesn't work, i tried loading webman before and after my plugins and it still goes kaboom

**Comment by aldostools** [comment]
If webMAN MOD can load alone, you can load other VSH plugins using the page /home.ps3mapi

In /setup.ps3, make sure that the option "Disable content scan on startup" is checked. Save and reboot.
This option may cause conflicts with other plugins, due it uses a large amount of memory during the scanning.

**Comment by jordywastaken** [comment]
I already have "Disable content scan on startup" enabled, so i don't think that's the issue

I used a debug hen payload to get logs and it seems like it's a module loading issue, there's probably not enough memory to load both considering the hen enabler runs in the web browser which already uses quite a lot of it

Oh btw i know i can load my plugins with page /home.ps3mapi on hen without issue but users don't want to have to load them manually

**Comment by aldostools** [comment]
Yes the debug payload of HEN/Cobra/Mamba uses much more memory and may cause issues.

Could you test with the normal payload? It should allow start both plugins.

Just as an informative note: it is possible to load VSH plugins automatically from webMAN MOD using the `autoexec.bat` script or using a custom combo.

**Comment by jordywastaken** [comment]
My ps3 still hangs when loading with the normal hen payload, anyway, i'm just gonna make an homebrew to start my plugins on hen, should be way easier than debugging this issue
