### ISSUE TITLE
in-game System Info notifications stopped working

### ISSUE THREAD

**Issue by Kyogre** [aldostools/webMAN-MOD#96]
How did I get that problem:
1. connect PS3 to wifi point
2. loose wifi connection (for example disable access point what you was connected to)
3. go to Settings -> Network settings -> Internet Connection -> Disable
4. reboot (maybe this step doesn't matter)
5. you will get "system info [select+start combination] notifications" stop working in game's xmb (but still works in standard xmb, and works if you spawn many notifications via holding start+select [you hear beep sound] and then exit from game to standard xmb)
After those steps you can even go further:
6. reinstall Rebug CFW (I done it via system storage)
7. now you get system info notifications working again (even after reboot)
8. update Cobra from 7.5 to 7.52 via rebug toolbox
9. reboot and you will get system info notifications stopped working
10. if you press triangle+R2 (disable syscalls combination) in game's xmb (that will change IP address from "offline" to "offline [noSC]"), you will get system info notifications working again immediately

How to fix that issue permanently:
1. go to Settings -> Network settings -> Internet Connection -> Enable
2. connect ethernet cable to PS3 and setup ethernet connection
3. system info notifications will work again

My additional observations:
[for set-up'ed ethernet cable connection, and it doesn't matter if cable is connected or disconnected] if you set Settings -> Network settings -> Internet Connection -> Disabled, system info notifications will stop working, but notifications will start working again immediately after you set Internet Connection to Enabled (even without reboot)
[for wifi connection, wifi need to be set-up'ed in settings but disconnected] if you set Settings -> Network settings -> Internet Connection -> Disabled, system info notifications will stop working (like as in my first observation), BUT after doing that if you set Internet Connection back to Enabled, system info notifications will still don't work, so you will be forced to connect ethernet cable and set-up ethernet connection to overwrite wifi connection to fix that issue

**Comment by Kyogre** [comment]
I think that it is related to disabling internet via settings, or more specifically to IP-address changing, or even more specifically to network status name that is shown in system info notification. But I don't know why notifications still work when you are in standard xmb (not in-game) in spite of notifications don't work in in-game xmb...
P.S. I am using Rebug REX (CEX) 4.81.2 + latest Webman Mod 1.47.05 (GUI language set to Russian)

**Comment by Kyogre** [comment]
But I don't know why notifications still work when you are in standard xmb (not in-game) in spite of notifications don't work in in-game xmb...

**Comment by Kyogre** [comment]
Also system info notifications will stop working if you just switch from Cobra (7.52) payload to Mamba PRX Autoloader 3.1.4 (Mamba 7.3). Symptoms are the same as in steps 5 and 10. In this case it maybe related not to network status but to payload (cobra/mamba) status.

**Comment by Joonie86** [comment]
Closing old issues that have no further feedback. Please try the latest wMM and report back.
