### ISSUE TITLE
Issue mounting PS3 ISO on ps3netsvr when using PS3ISO.INI

### ISSUE THREAD

**Issue by casasfernando** [aldostools/webMAN-MOD#965]
I'm in the process of converting my JB backups into ISO for better management.
I'm using the latest version of ps3netsvr on Windows, to serve my JB backups. ps3netsvr is installed on a different drive (D:) than the one holding the backups (H:)
My shared folder structure on ps3netsvr looks like this:

```
GAMEI
GAMES
PKG
PS3ISO
GAMES.INI (Contains only one line: H:\Roms\PS3\JBBackups)
```

In the GAMES.INI file I added the path to the directory containing all the JB backup foders (e.g.: H:\Roms\PS3\JBBackups) and **this is working fine**. I'm able to mount the backups from my PS3 without any problems.
Today I decided to start creating ISO files out of the JB backups for better management so I went ahead and converted one of my backups to ISO (genps3iso -unencrypted-) using PS3 ISO Rebuilder.
I created a new folder for the ISOs (e.g.: H:\Roms\PS3\ISO) and saved the ISO file there (e.g.: H:\Roms\PS3\ISO\BLES00750.iso). Then I created the file PS3ISO.INI containing the path to the ISO images folder in the ps3netsvr folder structure. The new ps3netsvr folder structure looks like this:

```
GAMEI
GAMES
PKG
PS3ISO
GAMES.INI (Contains only one line: H:\Roms\PS3\JBBackups)
PS3ISO.INI (Contains only one line: H:\Roms\PS3\ISO)
```

Unfortunately **this is not working**. webman MOD is able to scan and find the ISO file but when it tries to mount it it's failing with a file not found error and for some reason the path is trying to mount is `/net0/PS3ISO/H:/Roms/PS3/ISO/BLES00750.iso` instead of `/net0/PS3ISO/BLES00750.iso`.
After doing some troubleshooting I found that if I remove the PS3ISO.INI file and place the ISO file inside the PS3ISO folder in the ps3netsvr folder structure, webman MOD is able to mount the ISO file without any issues and the path it is using for mounting it is the "expected" one `/net0/PS3ISO/BLES00750.iso`.
File and folder permission are the same in both cases.

Software versions I'm using:
- PS3 firmware: 4.90
- PS3HEN 3.2.2
- ps3netsvr 20220813
- webMAN MOD 1.47.45

Am I doing something wrong? Any ideas?

Thanks

**Comment by Don-Keballs** [comment]
I've also had this issue and haven't been able to setup other directories.

https://www.psx-place.com/threads/ps3-net-server-tutorial.1618/page-11#post-368788

**Comment by casasfernando** [comment]
@Don-Keballs after further troubleshooting I found the cause of the problem.
In webman MOD setup page, in the "Scan for content" section, I mistakenly checked the "Scan remote sub-directories" checkbox, right below the "Scan for LAN games/videos" options.

![image](https://github.com/aldostools/webMAN-MOD/assets/15861819/78b9db59-87fe-4dcb-8c4b-4317c34012fb)

After unchecking it and running a new scan to refresh the XML file, I was able to mount the ISO files in the PS3ISO virtual directory as expected.

@aldostools what is that option intended for? When should it be checked?
I mistakenly thought that it needs to be checked for webman MOD to be able to find content in sub-directories on ps3netsvr (e.g.: PS3ISO\My_Game\My_Game.iso).

Thanks

**Comment by aldostools** [comment]
@casasfernando I'm glad that you could fix your issue. Honestly I wouldn't be able to help without know that you made that change.

The option "Scan remote sub-directories" is a feature introduced months ago that basically adds // to the end of the remote path to be scanned. My fork of ps3netsrv performs recursive directory scanning and returns all the files in the folder and subdirectories in a single response when it detects // in the path.

If the option is unchecked the scanning is performed only in the specific folders GAMES, PS3ISO, PSXISO, etc.

The "Scan remote sub-directories" could not work if you're using a version of ps3netsrv that is not compatible with the feature. 

Other issues could be related to the operating system handling "//", large amount of files in the subdirectories, bad file names, etc.

**Comment by Don-Keballs** [comment]
> @Don-Keballs after further troubleshooting I found the cause of the problem. In webman MOD setup page, in the "Scan for content" section, I mistakenly checked the "Scan remote sub-directories" checkbox, right below the "Scan for LAN games/videos" options.
> 
> ![image](https://user-images.githubusercontent.com/15861819/278155361-78b9db59-87fe-4dcb-8c4b-4317c34012fb.png)
> 
> After unchecking it and running a new scan to refresh the XML file, I was able to mount the ISO files in the PS3ISO virtual directory as expected.
> 
> @aldostools what is that option intended for? When should it be checked? I mistakenly thought that it needs to be checked for webman MOD to be able to find content in sub-directories on ps3netsvr (e.g.: PS3ISO\My_Game\My_Game.iso).
> 
> Thanks

Awesome! Thanks for sharing. Will have to set up the server again and test it out.

**Comment by casasfernando** [comment]
@aldostools thanks for taking the time to reply.
I’m still a bit confused with how the feature works:

1. Is it expected that the real absolute path of the ISO file on the server is used instead of the virtual directory path when the option is checked? As I mentioned above webmanMOD was trying to mount `/net0/PS3ISO/H:/Roms/PS3/ISO/GameA/GameA.iso` instead of `/net0/PS3ISO/GameA/GameA.iso `.
2. I **unchecked** the ***Scan remote sub-directories*** option and everything works. webmanMOD is able to mount the ISO files, etc. Yet my folder structure under the virtual directory path contains sub-directories (one for each game) with the ISO file for the game inside.
For example:
Content of PS3ISO.INI: `H:\Roms\PS3\ISO`
Folder structure:
```
H:\Roms\PS3\ISO\GameA\GameA.iso
H:\Roms\PS3\ISO\GameB\GameB.iso
…
```
Shouldn’t webmanMOD fail to find the ISO files because they are in sub-directories and the option above is unchecked?

Thanks

**Comment by aldostools** [comment]
As I commented earlier, the checkbox for "Scan remote sub-directories" basically adds // to the path. So /PS3ISO is scanned as /PS3ISO// in ps3netsvr associated to /net0. When the server gets a request for open directory with // in the path, it performs a recursive scan in the directory and returns all the files in the same request.

I would have to reproduce the issue to verify if it is a bug or a bad configuration.

At the moment I cannot dedicate time to check it.

**Comment by casasfernando** [comment]
Got it.
Thanks a lot and feel free to close the issue since at the moment with the option unchecked everything works.

**Comment by Don-Keballs** [comment]
Tested this out today and can confirm un-checking that box works. Will update my PSX Place post to help others who may have this issue in the future. Nice discovery @casasfernando
