### ISSUE TITLE
webMAN-MOD dissapeared after hard crash from copying files, cannot reinstall

### ISSUE THREAD

**Issue by ddmdareal** [aldostools/webMAN-MOD#967]
As the title says, tho i will also mention i was running a game at the time (Crysis 3) and as tried to copy update files for it using the webMAN web ui the ps3 shut off, did the system scan and and after booting back up webMAN is no longer there. Trying to reinstall it (both the full edition by holding L1 and Lite edition) will show the webman mod folder icon but nothing else appears and the web ui also doesn't work. As far as ive browsed i don't see my issue anywhere. Any ideas?

**Comment by aldostools** [comment]
If you're using CFW it is possible that Cobra was disabled after crash or boot_plugins.txt was removed from /dev_hdd0
Try enabling Cobra and reboot. If the problem persists, my suggestion is delete webMAN MOD, then reinstall the CFW and webMAN MOD.

If you're on HEN, try removing all USB devices before enable HEN. If you have a blank boot_plugins.txt on one of the USB devices attached to the PS3 it will prevent that webMAN MOD is loaded.

To delete webMAN MOD, open a File Manager like multiMAN or IRISMAN and delete /dev_hdd0/plugins/webftp_server.sprx, /dev_hdd0/tmp/wm_config.bin and the folders /dev_hdd0/tmp/wmtmp and /dev_hdd0/xmlhost

There are more files, but these are the most important that should be deleted.

**Comment by ddmdareal** [comment]
Sorry ive forgotten to mention i was using CFW, but i should've taken a deeper look as it seems Cobra was disabled all this time XD. Thanks👍
