### ISSUE TITLE
Fans set straight to max when PS3 turned on, slows back down when boot starts

### ISSUE THREAD

**Issue by tqoo** [aldostools/webMAN-MOD#969]
On certain CECHL/CECHP models, when the console is turned on, the fans will immediately spin to max for the first five seconds. Then as the system starts to boot, the fans slow down until it is at normal speeds. This only happens when the dynamic fan control is enabled.

This issue has been brought up before (#119). Has there been any new fixes made for the issue? It's a bit of a hassle using the physical power switch at the back...

Tested on Rebug CFW 4.82 CEX & 4.84.2 REX

**Comment by aldostools** [comment]
If I recall correctly, this doesn't happen if the PS3 is shutdown using the combo L3+R2+X.
It seems that the PS3 remembers the last fan speed when it is turned off from XMB or with the power button.

Have you tried using Evilnat 4.90? I'm not sure, but I think this issue was fixed in that CFW.

**Comment by tqoo** [comment]
Updating to Evilnat 4.90 fixed the issue! Thanks for helping.
