### ISSUE TITLE
ps1_netemu broken on 1.47.05

### ISSUE THREAD

**Issue by Joechinchains** [aldostools/webMAN-MOD#97]
Hi. I recently updated from a few versions back and I noticed ps1_netemu is no longer working as it used to.

I have a few problematic PS1 titles that I usually hold down R2 with when mounting - the message that ps1_netemu has been loaded still appears as before but upon selecting the disc I just get a black screen, with every game. No BIOS logo, just pure black, with the usual XMB menu still accessible via the PS button. ps1_emu (via L2) still works normally and ps1_netemu is still working fine on other loaders such as IRISMAN.

Happy to go through IRISMAN for now but I would be thrilled if this would work properly through WebMAN once again, any suggestions to get it going are welcome.

**Comment by Joonie86** [comment]
Closing old issues that have no further feedback. Please try the latest wMM and report back.
