### ISSUE TITLE
froze

### ISSUE THREAD

**Issue by Lksrvl** [aldostools/webMAN-MOD#972]
sometimes the console freezes due to webman and does not respond at all. And tell me where I can download HEN for firmware fhw 4.90.2

**Comment by Lksrvl** [comment]
> sometimes the console freezes due to webman and does not respond at all

**Comment by aldostools** [comment]
There are many reasons why webMAN MOD could not respond:
1- the plugin may not be loaded at all
2- it may have conflicts with other plugins
3- it could be a defective HDD or another hardware issue (e.g. network card, motherboard, etc.)
4- it could be a network issue (if you're accessing webMAN remotely)
5- it could be a configuration issue
6- it could be a memory issue (e.g. VSH memory with not enough free memory due theme, mods, images, etc.)
7- it could be a bug in the payload PS3HEN
8- it could be a bug in webMAN MOD if you are not using the latest build

PS3HEN can be downloaded and installed from the official site https://www.ps3xploit.me

The required HFW 4.90 can be downloaded from this thread:
https://www.psx-place.com/threads/hfw-4-90-1-hybrid-firmware.39758/

**Comment by Lksrvl** [comment]
Thank you
