### ISSUE TITLE
Webman mod "losing" Http and FTP access after console power off.

### ISSUE THREAD

**Issue by AlbertoMSB** [aldostools/webMAN-MOD#976]
Greetings.
I installed the latest Evilnat (4.90 CEX) for my console and updated Webman mod (via the update Webman Mod option) and I'm having the following issue:
Everytime I power down the console (PS3 CECH-2001a), when I turn it back on, if I try to access the webman HTTP settings page or FTP via PC, both return me the error "Connection_refused", even tho the message of Webman Mod 1.47.45 [full] is being displayed on start and it being capable of loading games via net, only returning if I run the "webman MOD 1.47.45 Installer" under the "games" menu. (After powering down and booting the console again, the issue persists).
My "boot_plugins.txt" only contains one line: "/dev_hdd0/plugins/webftp_server.sprx" and the options "Disable FTP service" and "Disable remote access to FTP/WWW services" are both UNCHECKED.
What I've tried:
- Fully formatting the PS3's HDD and reinstalling both CFW and Webman Mod from scratch
- Changing the HDD in case it was defective
- Increasing the "Plugin memory usage" to 1280 KB
- unistalling Webman Mod (via the Webman Games > Webman Setup > Uninstall webMAN MOD option) and reinstalling again with the latest release posted here.
- Tried both Wired and wireless connection, both resulted in the same error.

All to no avail, with the issue persisting. Can you give me some Help on what I'm doing wrong?

**Comment by aldostools** [comment]
It looks like webMAN MOD is not being loaded.

1. Verify if Cobra payload is enabled.
2. If your console is running on DEX mode, the plugin should be loaded through /dev_hdd0/boot_plugins_dex.txt
3. Verify that the file exists in the path indicated in the text file.

If webMAN MOD is running, it should show a notification with the system information when you press SELECT+START.

If it's showing the notification, but you still get the connection error, it could be an issue with the network not enabled or a possible hardware issue with the network card.

If the notification is not showing, the plugin was not loaded or could have crashed.

**Comment by aldostools** [comment]
Other tests that you could try are:
1. Delete /dev_hdd0/tmp/wm_config.bin and reboot.
2. Check if webMAN MOD Lite edition works better
3. Check if sman.sprx works better

**Comment by AlbertoMSB** [comment]
Thank you for the quick response!
Seems like the issue was with "/dev_hdd0/tmp/wm_config.bin". After deleting it and rebooting, both Http and FTP functionality were restored and continued to work after re-doing the configs for network games.
One question before closing: 
After deleting the file, the "Plugin memory usage" was set to "Standard (896 Kb)", would you recommend changing it?

**Comment by AlbertoMSB** [comment]
Thank you for the quick response!
Seems like the issue was with "/dev_hdd0/tmp/wm_config.bin". After deleting it and rebooting, both Http and FTP functionality were restored and continued to work after re-doing the configs for network games.
One question before closing:
After deleting the file, the "Plugin memory usage" was set to "Standard (896 Kb)", would you recommend changing it?

**Comment by aldostools** [comment]
If it's working, don't make changes.

I only recommend to check Disable content scanning at startup.

**Comment by AlbertoMSB** [comment]
Already was disabled, thanks!
