### ISSUE TITLE
Slaunch doesnt show cover correct

### ISSUE THREAD

**Issue by N2022062** [aldostools/webMAN-MOD#98]
i put cover in MM folder
/dev_hdd0/game/BLES80608/USRDIR/covers/
Webman can show it correct,but slaunch doesnt show cover correct?
where should i put cover in slaunch?

**Comment by N2022062** [comment]
![img_0753](https://cloud.githubusercontent.com/assets/6193203/26527398/16547104-43c6-11e7-8973-82debee56f52.JPG)

**Comment by aldostools** [comment]
The path is correct. The issue could be the format of your pictures.

You can try installing the following pack of images (they show fine on my console, so I expect they show fine on yours too):
http://www.mediafire.com/file/vhen5jwz59b26v2

**Comment by N2022062** [comment]
i found the problem.
the cover‘s width MUST at least 260.
if less than 260 it'll show the picture above.
the height is any long ok.

**Comment by aldostools** [comment]
Thank you for your feedback. I'll take that in count.

Meanwhile you can use the package of covers in the link that I posted above. It shows the covers properly.
