### ISSUE TITLE
Iso's do black screen with webMAN MOD 1.47.45 on external NTFS HDD

### ISSUE THREAD

**Issue by xshower24** [aldostools/webMAN-MOD#981]
I recently upgraded from Evilnat CEX 4.89 to Evilnat CEX 4.90.
I didn't test all my 29 ps3 iso's since the update, but two of them (Demon 's Souls, Pro Evolution Soccer 2010) cause black screen when i start them after mounting with webman 1.47.45.
This two games worked fine with webMAN in 4.89 and also worked fine now in 4.90, but only when i tried to move them on the internal HDD.
The problem is that with multiMAN and irisMAN they start whitout problem even from the external HDD, so I've come to the conclusion that is a webMAN related problem.
During the black screen i can navigate the xmb with the PS  button to go back to the home, but after three beeps.

I also already tried to: 
Uninstall webMAN and reinstall it from the new pkj
Update from pkj "update only"
Update from xmb online updater
Rebuild database
File system check

**Comment by aldostools** [comment]
Are these games stored on NTFS or exFAT? If so, I recommend to run prepISO again to re-scan the games.

Also you can try copying one of these games to the internal HDD and mount it from there with webMAN MOD.

mutliMAN and IRISMAN mount the PS3 ISO's in the exact same Cobra API used by webMAN MOD, So there shouldn't be any difference (except for NTFS games that each backup manager use their own rawseciso plugin).

**Comment by xshower24** [comment]
Hi Aldo, thank you for responding and for the incredible work you do.
The games are, in fact, on a NTFS HDD that, at the time, i formatted in the correct way (MBR if i remember right).
As i wrote in the first comment, copying these games to the internal HDD and mount it with webMAN MOD solves the problem, and the differences with multiMAN and IRISMAN are that with them i can mount them directly from the NTFS HDD.
My problem comes when webMAN is so much esier and faster for mount games compared to the others solutions, so i wonder if this NTFS plugin will change in the future versions.

**Comment by aldostools** [comment]
You could try copying /dev_hdd0/game/IRISMAN00/sprx_iso to /dev_hdd0/tmp/wm_res
Rename the file to replace **raw_iso.sprx**

**Comment by xshower24** [comment]
I tried and it worked! Thank you so much🙏
I will need to do this after every webMAN MOD update?

**Comment by aldostools** [comment]
For the moment, yes.

**Comment by xshower24** [comment]
Okay, thank you again and my best wishes for your really important work for the community.
Have a good day :)

**Comment by ozapft** [comment]
The error described is due to the last update of Webman mod. With the version from 10/3/23, demons souls starts from an external NTFS hdd.

**Comment by aldostools** [comment]
@ozapft thank you for the information. I'll revert the updated version of raw_iso.sprx.

**Comment by xshower24** [comment]
I downloaded the new pkg and can confirm that the problem is gone🙌
