### ISSUE TITLE
WebMan re-install fails (Evilnat 4.90)

### ISSUE THREAD

**Issue by itsmemax** [aldostools/webMAN-MOD#985]
I had a perfectly working WebMan 1.47.45 on Evilnat 4.90 with many of the addons (NTFS USB HDD with all my PS3 ISOs, PS2 and PSX roms working, etc.)

I stupidly tried removing the icon of the WebMan installer from XMB for aesthetic reasons, little did I know that clicking delete on this, will remove WebMan and mess up all the work I did on that PS3 
:'(

Anyways, I downloaded the WebMan PKG again, tried both GitHub and Brewology, put them on the USB stick, installed the PKG, but that's where I run into the problem. When I click the installer (with L1 and without), the screen shows the "installing WebMan Mod full" but only for a split second, it seems the installation is aborted and never completes. A Webman folder is created on XMB but it completely empty.

I tried installing both PKGs and installer many times, restarting, I deleted the wm-config.bin file that I saw the developer recommending on several other threads with "empty webman folder" issue, but nothing helped.
I would greatly appreciate any help with this to get my console back to functioning condition :(

Thank you.

**Comment by aldostools** [comment]
I recommend you that use IRISMAN or multiMAN's File Manager and delete webMAN MOD manually. These are the main files and folders:

/dev_hdd0/boot_plugins.txt
/dev_hdd0/plugins/webftp_server.sprx
/dev_hdd0/tmp/wm_config.bin
/dev_hdd0/tmp/wmtmp
/dev_hdd0/tmp/wm_res
/dev_hdd0/tmp/wm_lang
/dev_hdd0/xmlhost
/dev_hdd0/game/XMBMANPLS

Download and install the latest package from https://github.com/aldostools/webMAN-MOD/releases

Make sure that you have all USB devices unplugged. Install prepISO and full version of webMAN MOD. Run the installer.

After reboot, go to 0/setup.ps3 and check "Disable scan content on startup". Save settings and reboot.

Attach the USB devices with your games and run prepISO to re-scan your games.

If the problem persits, try asking for additional ideas on PSX-PLACE forum.

**Comment by itsmemax** [comment]
Thanks a lot for the reply and all the work you do for the community!
I did as you suggested, using Irisman:

/dev_hdd0/boot_plugins.txt - deleted
/dev_hdd0/plugins/webftp_server.sprx - deleted (there is also a 'lite" version, should I delete it too?)
/dev_hdd0/tmp/wm_config.bin - deleted
/dev_hdd0/tmp/wmtmp - deleted
/dev_hdd0/tmp/wm_res - deleted

Then something happened, and I cannot see "delete" option anymore, only "Truncate". After truncating the following folders:
/dev_hdd0/tmp/wm_lang
/dev_hdd0/xmlhost
/dev_hdd0/game/XMBMANPLS

Nothing happens, the folders and all the files are still there untouched.
What am I doing wrong?
Thank you!

**Comment by aldostools** [comment]
IIRC If you press LEFT or RIGHT buttons the option should change from Truncate to Delete.
Alternatively you can press SQUARE to select multiple files and delete them individually.

Anyway these folders only contain resource files. They should be overwritten when you reinstall webMAN MOD.

**Comment by itsmemax** [comment]
So if it helps, I can confirm that the install doesn't happen. Before manually deleting them as you suggested, I opened those files after repeatedly running the installation file, and they contained information from the original install that was accidentally uninstalled.

In any case, manually removing and attempting reinstall failed just like before.
Something is stopping the reinstall.
Hoping to get more ideas/suggestions.

**Comment by aldostools** [comment]
Please make sure that Cobra is enabled.

If possible, you could try resetting PS3 system or formatting the HDD.
Take in count that this option erases all the content in the HDD and you will have to reinstall all the games, DLC, resync saves, trophies, etc.

Alternatively you could try installing a new HDD.

sMAN is another alternative to webMAN MOD that you could consider.

**Comment by LuanTeles** [comment]
Probably is due to cobra, once i got the same problem until i realized that my cobra was disabled

Aldo, maybe your installer can check for cobra and if it is enabled it writes a boot_plugins.txt if not, it writes to boot_plugins_nocobra.txt.

**Comment by itsmemax** [comment]
It worked!
Everything is back to normal and working :)
It was apparently the Cobra thing.
I'm so happy!
Thank you so much!
