### ISSUE TITLE
On 1.47.05 LBP3 thinks an additional controller is attached

### ISSUE THREAD

**Issue by acaN** [aldostools/webMAN-MOD#99]
Hello!

I have a weird issue with 1.47.05 (or maybe earlier update — did not go through all of them):

When i launch LittleBigPlanet 3 on rebug 4.81.2 with stock 1.45.09 mod, all works as expected.

When i update webMAN MOD to 1.47.05, game thinks that an additional controller is connected to PS3 adding a second unplayable sackboy on the screen making game impossible to play. When I really connect a second controller, game throws in THIRD sackboy, so the second one is still unplayable.

This is not related to the game location (hdd0, usb0 or net0). webMAN settings are same for both versions (stock).

How can i fix this?

UPD: I tried to clear syscalls and unload webMAN prior to launching LBP3, but second (exceess) sackboy still appears :(

**Comment by aldostools** [comment]
It seems that the VIRTUAL_PAD is being activated by some of your previous actions before launching the game (e.g. remote install of PKG or /download.ps3).

You can turn off the virtual pad at any moment using the web command: **/pad.ps3?off**

Or you could use the LITE edition that doesn't include support for VIRTUAL_PAD, but also doesn't support other features like NET server or native NTFS support (games scanned with prepNTFS are supported).

**Comment by acaN** [comment]
Thank you!

That was it. Though, I go straight to game launch when console starts and have to turn off virtual pad after every reboot or on/off cycle.
Don't know what may cause enabling it.
Anyway, it is not so important. Thank you a lot for your work and help.
