### ISSUE TITLE
sLaunch MOD 1.16b broken input with multiple controllers

### ISSUE THREAD

**Issue by kar0sh1** [aldostools/webMAN-MOD#992]
Using sLaunch, the input is hyper-sensitive when multiple controllers are connected.  It's very difficult to zero in on a single item without overshooting it or going to another page of games entirely.  It is possible to move the cursor one item at a time, but it requires a frustrating superfast tap-release.  

Furthermore, the 'select' button hotkey to swtich in and out of the favorites view does not work either.

The problem only exists for controllers connected via bluetooth (not wired).  All the controllers I tested with are authentic OEM Sony DualShock 3 and have no problems.

This problem was introduced with the sLaunch sprx packaged with webMAN MOD v1.47.37 at the end of 2021.

Perhaps also related, only controller 1 is able to flip though sLaunch pages quickly.  With all other controllers, L1/R1 do nothing until the page has completed loading all game icons (as was the behavior before the update)

STEPS TO REPRODUCE: 
* connect multiple controllers, at least one being over wireless via PS3 bluetooth
* enter slaunch
* using a wireless controller, move cursor around and observe the hyper speed / double input
* attempt to enter favorites via select button without success.

EXTRA CREDIT:
* plug in one wired controller and one wireless
* enter slaunch
* move cursor around, observe difference between the two controllers:  wired good, wireless bad
* attempt to enter favorites via select button:  wired works, wireless doesn't
* attempt to fast page flip (L1/R1 before page loads all images):  controller 1 works, other controllers don't

PS3: CECH-2101A
CFW: EvilNat v4.90 CEX
WebMAN MOD: v1.47.45 (2023-11-22; md5:d0bb3aee64ffd75673f32038e6e4f7a6)

**Comment by aldostools** [comment]
Hello @kar0sh1 
Thank you for the bug report. I only have one controller available, so I cannot reproduce your issue.
However, I made some changes that maybe you could test.

Unzip the following zip and upload `slaunch.sprx` to `/dev_hdd0/tmp/wm_res` in your PS3
LINK REMOVED

**Comment by kar0sh1** [comment]
Thanks for looking into this, Aldo.  This latest sLaunch (v1.16c, md5: 238a8f05aa08ea060b4a8d8341d11e11) has the same problem with the hyper-sensitivity of wireless controllers, with perhaps only a slight improvement.  The one certain difference I noticed with this build is there is now a long delay in the page switching (L1/R1), so the older version is actually better.

The latest release build of sLaunch (v1.16b) is perfect if only one controller is connected.  The input response is good, page flipping is fast, and switching in and out of favorites works.  

Here is my use case:  Even just for single player use, I like to keep a few other controllers connected, ie. fight stick, Brook adapter, guitar hero dongle, etc. and switch out the contoller number from the accessory settings menu.  I'd prefer to keep them connected for convenience and to save on the wear and tear on the USB ports... but as the sLaunch navigation becomes unbearable, I've resorted to unplugging everything except the one controller I'm using.

I think it would be very helpful if you could see this issue for yourself.  If you don't have another DualShock 3 to test with, you can also use almost any other PS3 input device.  I've tested and observed the same behavior with all of the following:

* DualShock 3
* PS3 Move Motion Controller
* PS3 Move Navigation Controller
* HORI RAP N
* Brook Wingman XE
* Activision Guitar Hero wireless adapter (only a problem when guitar connected)
* DualShock 4 (manually added Bluetooth device)

**Comment by aldostools** [comment]
Thank you for your feedback. 
I have tested the original release 1.6b and this new version 1.16d connecting the DS3 to port 2 and a SIXAXIS to port 1 and to be honest I didn't notice big differences (1.16d has a delay of 1 millisecond between pad readings, so it's a bit slower)

I hope this version works as you expect it.
LINK REMOVED

EDIT:
I think could reproduce your issue even with 1.16d. I will try to fix it.

**Comment by aldostools** [comment]
You can check if sLaunchMOD 1.17 is now fixed
LINK REMOVED

**Comment by kar0sh1** [comment]
Thanks again Aldo.  Unfortunately, sLaunch v1.17 appears to be behaving exactly the same as the previous versions.  When you test, make sure both controllers are connected before you start sLaunch.  Also make sure you test with one connected via Bluetooth (not wired USB).  The double input problem is not subtle.. you should notice it immediately.  Have your volume set so you can hear the navigation sounds.

To isolate the problem, if it's even possible, perhaps try to ignore input from all controllers except P1?

**Comment by aldostools** [comment]
I made some adjustments to the code and relesed a new sLaunch 1.17

Use the online updater or download the full installer from github or brewology.

**Comment by kar0sh1** [comment]
Thanks Aldo.  All looks good now.  No more double input, fast paging works on secondary controllers, favorites toggle works on all inputs.  Awesome.  Thanks again.
