### ISSUE TITLE
[Question] Refresh XMB without the need of reloading the XMB

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#994]
Aldo, do you remember when I suggested a way to scan for new games without needing to reload the XMB about 2 years ago? Do you plan to implement it? I just remembered it because there are no more new features on webMAN for a while, so this could be one.

**Comment by LuanTeles** [comment]
Well, the only drawback would be that a lot of code that is already working and other dependencies would need to be recoded. I don't know if it's worth the hassle.

**Comment by aldostools** [comment]
Currently I do not have plans to make major changes to webMAN MOD.

The source code is available. If other developers make improvements or add new features, I'll be glad to include them.
