### ISSUE TITLE
[HELP] Strange Problems

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#998]
Aldo, I'm using a custom ps3update-list.txt on my PS3 Pro Mod, it works fine for most people, but some can't get into PSN if the file exists, do you have any clues?

I found out that this is the problem in a YouTube video, because I remembered that I used to see this type of error when an update came out and people would install ps3update-list to bypass it. Then I saw a video where a guy said to remove this file if the user has problems, this happens even when using the spoofed one that is on the psx-place forums.

Curious, isn't it? works for most, but for some it doesn't

**Comment by LuanTeles** [comment]
another thing is that my PRO MOD has built-in webman, it works well on CFW and HEN, but if the user has an SSD + HEN, the system hangs while enabling hen, without my mod webMAN works very well with SDD, but with my mod it doesn't work, even deleting all .txt and .bat scripts.

Is there any configuration or something similar that the webman needs to have on HEN using SSD that I may not have included?

Holding r2 or just deleting the webftp_server.sprx solve the issue, but i can't find why it happens only on SDD+HEN

**Comment by aldostools** [comment]
SSD has known issues that doesn't happen if a mechanic HDD is installed.
For instance, physical PS2 discs are recognized as Data Disc on phat models with PS2 backward compatibility.

I don't know of any workaround to fix that issue.

The issue with ps3update-list.txt could be a timing issue when the plugin is loaded.

webMAN MOD basically performs this call if the file exists when the plugin is loaded (usually on startup).
```
vshnet_setUpdateUrl("http://127.0.0.1/dev_hdd0/ps3-updatelist.txt");
```

Some consoles require a larger delay for some USB storage devices. That time that can be configured in:
https://github.com/aldostools/webMAN-MOD/wiki/Setup-Options#startup-delays

A simple test that you could ask to the users is that start the console without any USB storage device attached.

I don't know if it's related, but HEN has known issues with map_path probably related to newest bguerville's mappath.c implementation

**Comment by LuanTeles** [comment]
> The issue with ps3update-list.txt could be a timing issue when the plugin is loaded.
> 
> webMAN MOD basically performs this call if the file exists when the plugin is loaded (usually on startup).
> 
> Some consoles require a larger delay for some USB storage devices. That time that can be configured in: https://github.com/aldostools/webMAN-MOD/wiki/Setup-Options#startup-delays
> 
> A simple test that you could ask to the users is that start the console without any USB storage device attached.
>

Got it, i'll test it and report back!

if it's related to this, i can make the script change the delay in the wm_config.bin.

Thanks for the tip.

**Comment by LuanTeles** [comment]
> I don't know if it's related, but HEN has known issues with map_path probably related to newest bguerville's mappath.c implementation.

i will revert the map_path to the previous one before bguerville implementation too see if it is the issue.

**Comment by LuanTeles** [comment]
> > I don't know if it's related, but HEN has known issues with map_path probably related to newest bguerville's mappath.c implementation.
> 
> i will revert the map_path to the previous one before bguerville implementation and see if it is the issue.

Hm, but maybe it's not related to his map_path implementation as it works on normal HEN.

Edit: Well, i forgot that official hen doesn't have remaps as i have, so maybe it's the issue, i'll start making a delay before the map_paths to see if it works, if not i'll remove all the remaps to see.

i also added many cobra 8.4 changes to my hen cobra, as the PSN Protection, the ability to restore the syscalls via toggle (
i'm using a XMBML menu to call the SACD sprx to restore the syscalls and some others related to evilnat patches, but i don't think it is caused by some of them.

**Comment by LuanTeles** [comment]
Finally, I got an SSD for my PS3.

And I found the issue, well, to be honest, it's a strange behavior, and I doubt that using an SSD can consume more memory, but I don't have any other explanation.

On HEN, I use a plugin ([ip_text](https://github.com/jordywastaken/ip_text)) by @jordywastaken that mimics the dex explorer_plugin to work on HEN right after activation . I use it to display the IP address and the current online server that works together with an XMBML menu that i made and webMAN commands.

Everything used to run smoothly on all CFW and HEN setups, but now, with the SSD, it seems like webMAN and the ip_text plugin aren't playing nice together. If I disable webMAN, HEN activates just fine with the ip_text plugin. If I disable the ip_text plugin, HEN also activates smoothly with webMAN. However, having both enabled results in HEN activating, but the web browser won't close. If I attempt to close it, the system hangs until it eventually crashes.

I wonder what could be the cause of this. Using HDD, both work togheter without any issues, and using SSD only on CFW, they work together, on HEN the webbrowser will not close and crash the system

![image](https://github.com/aldostools/webMAN-MOD/assets/110236244/de0a065e-0509-4196-98fc-20babd6aa6eb)

**Comment by LuanTeles** [comment]
Well, i disabled the plugin from the boot_plugins.txt and made my boot_init.txt load it, it's working just fine now

But i still wonder what can be the cause that only using a SSD on HEN have.


Btw, i think HEN needs a little delay to load the plugins, i tried to add in the payload itself and i couldn't make it work, i will try now in the hen plugin.sprx

**Comment by LuanTeles** [comment]
Well looks like i can't enable more than one plugin at a time on SSD, no matter which ones, if more than one is enabled the webbrowser will not close and the system will freeze, loading other plugins via webMAN works
